#!/bin/sh
# $Id: version,v 1.10 2017/09/27 01:57:15 leschen Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/woodlawn_linux/version,v $
#------------------------------------------------------------------
# Version control file for woodlawn
#
# Copyright (c) 2013 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.10  2017/09/27 01:57:15  leschen
# Bump up to 1.0.7
#
# Revision 1.9  2015/03/31 04:01:00  leschen
# Bump up to 1.0.6
#
# Revision 1.8  2015/02/04 07:19:22  leschen
# Bump up to 1.0.5
#
# Revision 1.7  2014/11/12 06:09:51  leschen
# Bump up to 1.0.4
#
# Revision 1.6  2014/03/17 07:06:15  leschen
# Bump up to 1.0.3
#
# Revision 1.5  2014/02/21 02:16:55  leschen
# Bump up to 1.0.2
#
# Revision 1.4  2013/12/12 09:24:35  leschen
# Bump up to 1.0.1
#
# Revision 1.3  2013/10/09 02:44:20  leschen
# Bump up to 1.0.0
#
# Revision 1.2  2013/10/08 08:48:32  tirawan
# Woodlawn collapsed to main trunk
#
# Revision 1.1.4.3  2013/08/29 05:34:20  leschen
# Bump up to 0.0.5
#
# Revision 1.1.4.2  2013/08/20 10:59:11  tirawan
# Branch into woodlawn-branch2 and port woodlawn code
#
# Revision 1.1.2.3  2013/07/02 08:07:21  leschen
# Bump up to 0.0.4
#
# Revision 1.1.2.2  2013/06/18 01:44:40  leschen
# Bump up to 0.0.3
#
# Revision 1.1.2.1  2013/04/24 10:37:26  tirawan
# Initial check-in for woodlawn linux code
#
# Revision 1.2  2013/03/29 08:42:09  kuangik
# Bump up to 0.0.2
#
# Revision 1.1  2013/03/13 06:43:02  kuangik
# Add for the first time
#
# Revision 1.1  2013/03/02 11:39:54  kuangik
# Add banner for version control
#
#
# $Endlog$

MAJOR_VERSION=1
MINOR_VERSION=0
RELEASE=7
