#!/bin/sh
# $Id: version,v 1.33 2021/10/06 05:40:49 tshanmug Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/tsn/version,v $
#------------------------------------------------------------------
# Version control file for espn-turbo
#
# Copyright (c) 2017 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.33  2021/10/06 05:40:49  tshanmug
# UNDO : Bump up TSN APP version to v6.0.10
#
# Revision 1.32  2021/09/27 19:10:45  tshanmug
# Bump up TSN APP version to v6.0.10
#
# Revision 1.31  2020/07/10 11:36:51  steja
# Enhanced TSN LTE Series
# 1.CSCvu76591 [TSN-H/TSN-GFAST] Modify SIM_DETECT pin Test item
# 2.CSCvu72092: [TSN-H/TSN-GFAST] Enhance the LTE USB port number change dynamically
# 3.CSCvu72089: [TSN-H/TSN-GFAST] Adjust LTE Power Sequence
#
# Revision 1.30.8.2  2020/06/24 08:58:52  steja
# Support seperate SIM_DETECT Pin test insert and removal
#
# Revision 1.30.8.1  2020/06/19 08:27:50  steja
# For private test
#
# Revision 1.30  2020/01/18 07:43:41  sherliu2
# Bump up version
#
# Revision 1.29  2019/10/16 02:28:40  sherliu2
# Bumped up version
#
# Revision 1.28  2019/08/15 09:53:41  shjung
# Bump up version
#
# Revision 1.27  2019/07/03 03:50:13  sherliu2
# Bumped up version
#
# Revision 1.26  2019/06/26 10:26:25  yungchen
# CSCvq20258 : one sim card sku can not get expect result with at+cpin
# Bumped up version to V6.0.4
#
# Revision 1.25  2019/06/18 09:18:52  steja
# 1. Revert back to v6.0.3
# 2. Supported Cooper USB Lte Dongle
#
# Revision 1.23  2019/06/14 07:16:18  shjung
# Bumped up version
#
# Revision 1.22  2019/05/20 08:01:05  shjung
# Bumped up version
#
# Revision 1.21  2019/03/07 09:57:06  lucywang
# Bump up version to v6.0.1
#
# Revision 1.20  2018/11/27 06:30:47  shjung
# Bump up version to v5.0.0
#
# Revision 1.19  2018/10/18 06:51:37  iachang
# Bump up version to v4.0.6
#
# Revision 1.18  2018/09/25 13:21:42  iachang
# Bump up version to v4.0.5
#
# Revision 1.17  2018/08/20 06:28:33  shjung
# Bump up version to v4.0.4
#
# Revision 1.16  2018/08/06 11:17:32  iachang
# Bump up version to v4.0.3
#
# Revision 1.15  2018/07/13 00:54:39  lucywang
# Bump up version to v4.0.2
#
# Revision 1.14  2018/06/29 14:14:52  palin2
# Bump up version to v4.0.1
#
# Revision 1.13  2018/06/07 02:53:01  lucywang
# Bump up version to v4.0.0
#
# Revision 1.12  2018/06/06 07:17:29  lucywang
# Bump up version to v3.0.2
#
# Revision 1.11  2018/06/01 12:20:39  letsai
# Bump up version to v4.0.1
#
# Revision 1.10  2018/05/23 08:45:37  shjung
# Bump up version to v3.0.1
#
# Revision 1.9  2018/04/16 08:32:49  shjung
# Bump up version to 3.0.0
#
# Revision 1.8  2018/03/27 12:46:38  hondwang
# Code modify for Star_C1101_4PLTEP_4PLTEPWX and Pluggable LTE EM7455, WP7601, WP7603 ER
#
# Revision 1.7  2018/02/09 09:56:56  hondwang
# Merge Star branch star-branch-c9xx to main trunk
#
# Revision 1.5  2017/12/01 13:58:43  palin2
# Bump up version to v1.0.3
#
# Revision 1.4  2017/10/19 16:05:49  palin2
# Bump up version to v1.0.2.
#
# Revision 1.3  2017/09/08 02:16:48  steja
# Bump up to V1.0.1
#
# Revision 1.2  2017/08/02 14:21:50  steja
# Support TSN-H/M platform code
#
# Revision 1.1.8.2  2017/07/29 03:41:21  steja
# tsn-branch5 synced with Maintrunk repositories
#
# Revision 1.1.6.2  2017/07/20 13:38:08  steja
# tsn-branch4 merge with maintrunk
#
# Revision 1.1.4.5.2.3  2017/07/13 12:55:26  steja
# Bump up
#
# Revision 1.1.4.5.2.2  2017/05/18 12:46:41  steja
# Bump up
#
# Revision 1.1.4.5.2.1  2017/03/08 14:50:44  steja
# Bump up V0.0.7
#
# Revision 1.1.4.5  2016/11/25 13:31:36  steja
# Bump up version
#
# Revision 1.1.4.4  2016/08/16 09:02:20  steja
# Bump up version
#
# Revision 1.1.4.3  2016/07/22 14:54:55  steja
# Bump up version
#
# Revision 1.1.4.2  2016/06/30 06:22:52  steja
# tsn-branch2 sync with main trunk
#
# Revision 1.1.2.3  2016/06/21 12:59:17  steja
# bump up version
#
# Revision 1.1.2.2  2016/06/20 01:56:32  steja
# Bump up version
#
# Revision 1.1.2.1  2016/03/08 09:55:11  steja
# Initial Check-in
#
# $Endlog$
#

MAJOR_VERSION=6
MINOR_VERSION=0
RELEASE=9
