#!/bin/sh
# $Id: version,v 1.17 2021/08/05 08:16:57 xiaolaya Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/tabei-l/version,v $
#------------------------------------------------------------------
# Version control file for espn-turbo
#
# Copyright (c) 2020-2021 by cisco Systems, Inc
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.17  2021/08/05 08:16:57  xiaolaya
# Bump version to V3.0.5
#
# Revision 1.16  2021/06/10 02:40:24  xiaolaya
# Bump version back to V3.0.4
#
# Revision 1.15  2021/06/04 01:12:51  xiaolaya
# Bump version to 3.0.5
#
# Revision 1.14  2021/05/13 08:49:58  kodko
# Support M.2 testcard.
#
# Revision 1.13  2021/04/20 06:51:35  xiaolaya
# Bump version to V3.0.3
#
# Revision 1.12  2021/04/20 06:46:54  xiaolaya
# *** empty log message ***
#
# Revision 1.11  2021/01/12 06:21:58  iachang
# Bump version to V3.0.2
#
# Revision 1.10  2020/12/17 08:43:50  kehuang2
# Bump to V3.0.1
#
# Revision 1.9  2020/10/20 01:40:36  kehuang2
# Bump to V3.0.0
#
# Revision 1.8  2020/10/07 08:20:48  kehuang2
# CSCvv99413: Collapse Promethium-L into main trunk
#
# Revision 1.7  2020/09/21 06:12:33  kehuang2
# Bump to V2.0.1
#
# Revision 1.6  2020/08/18 02:56:40  kehuang2
# Collapse Promethium into main trunk
#
# Revision 1.5  2020/06/04 06:28:38  kehuang2
# Bump to V1.0.3
#
# Revision 1.4  2020/04/10 08:06:54  kehuang2
# Bump to V1.0.2
#
# Revision 1.3  2019/12/30 06:06:28  kehuang2
# Bump to V1.0.1
#
# Revision 1.2  2019/10/17 02:16:28  kehuang2
# Collapse Tabei-L into main trunk
#
# Revision 1.1.4.17  2019/09/16 01:53:26  kehuang2
# Bump to V0.0.14
#
# Revision 1.1.4.16  2019/07/17 06:05:23  kehuang2
# Bump to V0.0.13
#
# Revision 1.1.4.15  2019/06/06 01:11:11  kehuang2
# Bump to V0.0.12
#
# Revision 1.1.4.14  2019/05/17 02:00:40  kehuang2
# Bump to V0.0.11
#
# Revision 1.1.4.13  2019/04/19 10:18:10  kehuang2
# Bump to V0.0.10
#
# Revision 1.1.4.12  2019/04/08 00:42:16  kodko
# Bump to V0.0.9
#
# Revision 1.1.4.11  2019/04/02 08:45:38  kehuang2
# Bump to V0.0.8
#
# Revision 1.1.4.10  2019/02/27 07:23:19  harrchan
# Bump to V0.0.7
#
# Revision 1.1.4.9  2019/01/18 06:27:09  kodko
# Bump to V0.0.6
#
# Revision 1.1.4.8  2019/01/15 02:03:43  kodko
# Bump to V0.0.5
#
# Revision 1.1.4.7  2018/12/20 09:42:10  kodko
# Bump to V0.0.4
#
# Revision 1.1.4.6  2018/12/17 09:30:10  kodko
# Bump to V0.0.3
#
# Revision 1.1.4.5  2018/12/07 09:39:27  kodko
# Prompt to V0.0.2
#
# Revision 1.1.4.4  2018/11/16 05:42:12  olin2
# Clean up code
#
# Revision 1.1.4.3  2018/11/05 12:17:31  kodko
# Support 64Kbits BIOS EEPROM program.
#
# Revision 1.1.4.2  2018/10/02 01:50:04  harrchan
# Initial commit for Tabei-L P1A bring up.
#
# $Endlog$
#

MAJOR_VERSION=3
MINOR_VERSION=0
RELEASE=5
