#!/bin/sh
# $Id: version,v 1.6 2018/11/23 09:28:46 hondwang Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/plug_serial/version,v $
#------------------------------------------------------------------
# Version control file for Pluggable Serial
#
# Copyright (c) 2016-2018 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.6  2018/11/23 09:28:46  hondwang
# Re-instruct pluggable common code with CDETs CSCvn17216
#
# Revision 1.4  2018/08/02 09:35:01  iachang
# Merge Pluggable Serial from branch star-branch-c9xx to main trunk
#
# Revision 1.3  2018/02/09 09:17:38  hondwang
# Merge Star branch star-branch-c9xx to main trunk
#
# Revision 1.2.2.2  2018/01/20 06:55:09  hondwang
# prepare merge star-branch-c9xx to main trunk
#
# Revision 1.2  2018/01/20 04:59:01  hondwang
# prepare merge star-branch-c9xx to main trunk
#
# Revision 1.1.4.3  2017/10/26 14:57:28  iachang
# Version 0.0.1 for Plug Serial
#
# Revision 1.1.4.2  2017/08/08 07:43:38  hondwang
# add pluggable serial for star-branch-c9xx
#
# Revision 1.1.2.1  2017/07/31 10:49:59  lucywang
# add pluggable serial code of host and module
#
# $Endlog$
#

MAJOR_VERSION=1
MINOR_VERSION=0
RELEASE=0
