#!/bin/sh
# $Id: version,v 1.2 2015/05/25 03:59:21 steja Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/skye_linux/src/version,v $ 
#------------------------------------------------------------------
#
# Version control file for Skye
#
# Copyright (c) 2014-2015 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.2  2015/05/25 03:59:21  steja
# Add Support Skye SM
#
# Revision 1.1.4.2  2015/04/29 11:36:44  steja
# Code check-in to skye-branch2 for ER code review
#
#------------------------------------------------------------------
# Revision 1.1.2.4  2015/02/14 12:39:02  palin2
# Bump up version to v0.0.5
#
# Revision 1.1.2.3  2014/11/28 01:35:35  palin2
# Bump up version to v0.0.4 for Skye P1B BST testing.
#
# Revision 1.1.2.2  2014/08/26 08:16:28  steja
# Bump version for P1A BST testing
#
# Revision 1.1.2.1  2014/07/21 01:57:00  palin2
# Initial check-in Skye module side Diag code.
#
# Revision 1.1.2.1  2014/06/04 09:42:39  palin2
# Add banner for Shrinkray/Skye version control.
#
# $Endlog$
#

MAJOR_VERSION=1
MINOR_VERSION=0
RELEASE=0
