#ifndef __SWITZER_MANHATTAN_X710_GPIO_H__
#define __SWITZER_MANHATTAN_X710_GPIO_H__

/*NOTE: These definitions are excerpted from i40e driver without change
 *>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>{ */

/* I40E_MASK is a macro used on 32 bit registers */
#define I40E_MASK(mask, shift) (mask << shift)

#define I40E_GLGEN_GPIO_CTL(_i) (0x00088100 + ((_i) * 4)) /* _i=0...29 */ /* Reset: POR */
#define I40E_GLGEN_GPIO_CTL_MAX_INDEX 29
#define I40E_GLGEN_GPIO_CTL_PRT_NUM_SHIFT 0
#define I40E_GLGEN_GPIO_CTL_PRT_NUM_MASK I40E_MASK(0x3, I40E_GLGEN_GPIO_CTL_PRT_NUM_SHIFT)
#define I40E_GLGEN_GPIO_CTL_PRT_NUM_NA_SHIFT 3
#define I40E_GLGEN_GPIO_CTL_PRT_NUM_NA_MASK I40E_MASK(0x1, I40E_GLGEN_GPIO_CTL_PRT_NUM_NA_SHIFT)
#define I40E_GLGEN_GPIO_CTL_PIN_DIR_SHIFT 4
#define I40E_GLGEN_GPIO_CTL_PIN_DIR_MASK I40E_MASK(0x1, I40E_GLGEN_GPIO_CTL_PIN_DIR_SHIFT)
#define I40E_GLGEN_GPIO_CTL_TRI_CTL_SHIFT 5
#define I40E_GLGEN_GPIO_CTL_TRI_CTL_MASK I40E_MASK(0x1, I40E_GLGEN_GPIO_CTL_TRI_CTL_SHIFT)
#define I40E_GLGEN_GPIO_CTL_OUT_CTL_SHIFT 6
#define I40E_GLGEN_GPIO_CTL_OUT_CTL_MASK I40E_MASK(0x1, I40E_GLGEN_GPIO_CTL_OUT_CTL_SHIFT)
#define I40E_GLGEN_GPIO_CTL_PIN_FUNC_SHIFT 7
#define I40E_GLGEN_GPIO_CTL_PIN_FUNC_MASK I40E_MASK(0x7, I40E_GLGEN_GPIO_CTL_PIN_FUNC_SHIFT)
#define I40E_GLGEN_GPIO_CTL_LED_INVRT_SHIFT 10
#define I40E_GLGEN_GPIO_CTL_LED_INVRT_MASK I40E_MASK(0x1, I40E_GLGEN_GPIO_CTL_LED_INVRT_SHIFT)
#define I40E_GLGEN_GPIO_CTL_LED_BLINK_SHIFT 11
#define I40E_GLGEN_GPIO_CTL_LED_BLINK_MASK I40E_MASK(0x1, I40E_GLGEN_GPIO_CTL_LED_BLINK_SHIFT)
#define I40E_GLGEN_GPIO_CTL_LED_MODE_SHIFT 12
#define I40E_GLGEN_GPIO_CTL_LED_MODE_MASK I40E_MASK(0x1F, I40E_GLGEN_GPIO_CTL_LED_MODE_SHIFT)
#define I40E_GLGEN_GPIO_CTL_INT_MODE_SHIFT 17
#define I40E_GLGEN_GPIO_CTL_INT_MODE_MASK I40E_MASK(0x3, I40E_GLGEN_GPIO_CTL_INT_MODE_SHIFT)
#define I40E_GLGEN_GPIO_CTL_OUT_DEFAULT_SHIFT 19
#define I40E_GLGEN_GPIO_CTL_OUT_DEFAULT_MASK I40E_MASK(0x1, I40E_GLGEN_GPIO_CTL_OUT_DEFAULT_SHIFT)
#define I40E_GLGEN_GPIO_CTL_PHY_PIN_NAME_SHIFT 20
#define I40E_GLGEN_GPIO_CTL_PHY_PIN_NAME_MASK I40E_MASK(0x3F, I40E_GLGEN_GPIO_CTL_PHY_PIN_NAME_SHIFT)
#define I40E_GLGEN_GPIO_CTL_PRT_BIT_MAP_SHIFT 26
#define I40E_GLGEN_GPIO_CTL_PRT_BIT_MAP_MASK I40E_MASK(0xF, I40E_GLGEN_GPIO_CTL_PRT_BIT_MAP_SHIFT)
#define I40E_GLGEN_GPIO_SET 0x00088184 /* Reset: POR */
#define I40E_GLGEN_GPIO_SET_GPIO_INDX_SHIFT 0
#define I40E_GLGEN_GPIO_SET_GPIO_INDX_MASK I40E_MASK(0x1F, I40E_GLGEN_GPIO_SET_GPIO_INDX_SHIFT)
#define I40E_GLGEN_GPIO_SET_SDP_DATA_SHIFT 5
#define I40E_GLGEN_GPIO_SET_SDP_DATA_MASK I40E_MASK(0x1, I40E_GLGEN_GPIO_SET_SDP_DATA_SHIFT)
#define I40E_GLGEN_GPIO_SET_DRIVE_SDP_SHIFT 6
#define I40E_GLGEN_GPIO_SET_DRIVE_SDP_MASK I40E_MASK(0x1, I40E_GLGEN_GPIO_SET_DRIVE_SDP_SHIFT)
#define I40E_GLGEN_GPIO_STAT 0x0008817C /* Reset: POR */
#define I40E_GLGEN_GPIO_STAT_GPIO_VALUE_SHIFT 0
#define I40E_GLGEN_GPIO_STAT_GPIO_VALUE_MASK I40E_MASK(0x3FFFFFFF, I40E_GLGEN_GPIO_STAT_GPIO_VALUE_SHIFT)
#define I40E_GLGEN_GPIO_TRANSIT 0x00088180 /* Reset: POR */
#define I40E_GLGEN_GPIO_TRANSIT_GPIO_TRANSITION_SHIFT 0
#define I40E_GLGEN_GPIO_TRANSIT_GPIO_TRANSITION_MASK I40E_MASK(0x3FFFFFFF, I40E_GLGEN_GPIO_TRANSIT_GPIO_TRANSITION_SHIFT)

/*NOTE: These definitions are excerpted from i40e driver without change
 *<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<} */

#define I40E_GPIO_IDX_MAX I40E_GLGEN_GPIO_CTL_MAX_INDEX
#define I40E_GLGEN_GPIO_CTRL_FLD_SET(reg__, fldv__, fldn__) \
    (reg__ |= ((fldv__ << I40E_GLGEN_GPIO_CTL_##fldn__##_SHIFT) & \
             I40E_GLGEN_GPIO_CTL_##fldn__##_MASK))

#define I40E_GLGEN_GPIO_CTRL_FLD_CLR(reg__, fldn__) \
    (reg__ &= ~(I40E_GLGEN_GPIO_CTL_##fldn__##_MASK))

#define I40E_GLGEN_GPIO_PIN_NAME(_i) ( \
        ((_i) >= 0 && (_i) <= I40E_GPIO_IDX_MAX) ?    \
        "GPIO_0\0" \
        "GPIO_1\0" \
        "GPIO_2\0" \
        "GPIO_3\0" \
        "SDP0_0\0" \
        "SDP0_1\0" \
        "SDP0_2\0" \
        "SDP0_3\0" \
        "SDP1_0\0" \
        "SDP1_1\0" \
        "SDP1_2\0" \
        "SDP1_3\0" \
        "SDP2_0\0" \
        "SDP2_1\0" \
        "SDP2_2\0" \
        "SDP2_3\0" \
        "SDP3_0\0" \
        "SDP3_1\0" \
        "SDP3_2\0" \
        "SDP3_3\0" \
        "GPIO_4\0" \
        "GPIO_5\0" \
        "LED0_0\0" \
        "LED0_1\0" \
        "LED1_0\0" \
        "LED1_1\0" \
        "LED2_0\0" \
        "LED2_1\0" \
        "LED3_0\0" \
        "LED3_1\n" + ((_i) * (sizeof("GPIO_0"))) : NULL)

#define I40E_GPIO_PIN_GPIO_0  0
#define I40E_GPIO_PIN_GPIO_1  1
#define I40E_GPIO_PIN_GPIO_2  2
#define I40E_GPIO_PIN_GPIO_3  3
#define I40E_GPIO_PIN_SDP0_0  4
#define I40E_GPIO_PIN_SDP0_1  5
#define I40E_GPIO_PIN_SDP0_2  6
#define I40E_GPIO_PIN_SDP0_3  7
#define I40E_GPIO_PIN_SDP1_0  8
#define I40E_GPIO_PIN_SDP1_1  9
#define I40E_GPIO_PIN_SDP1_2  10
#define I40E_GPIO_PIN_SDP1_3  11
#define I40E_GPIO_PIN_SDP2_0  12
#define I40E_GPIO_PIN_SDP2_1  13
#define I40E_GPIO_PIN_SDP2_2  14
#define I40E_GPIO_PIN_SDP2_3  15
#define I40E_GPIO_PIN_SDP3_0  16
#define I40E_GPIO_PIN_SDP3_1  17
#define I40E_GPIO_PIN_SDP3_2  18
#define I40E_GPIO_PIN_SDP3_3  19
#define I40E_GPIO_PIN_GPIO_4  20
#define I40E_GPIO_PIN_GPIO_5  21
#define I40E_GPIO_PIN_LED0_0  22
#define I40E_GPIO_PIN_LED0_1  23
#define I40E_GPIO_PIN_LED1_0  24
#define I40E_GPIO_PIN_LED1_1  25
#define I40E_GPIO_PIN_LED2_0  26
#define I40E_GPIO_PIN_LED2_1  27
#define I40E_GPIO_PIN_LED3_0  28
#define I40E_GPIO_PIN_LED3_1  29

#define SWITZER_MANHATTAN_INTPHY_RST        I40E_GPIO_PIN_SDP0_0
#define SWITZER_MANHATTAN_EXTPHY_RST        I40E_GPIO_PIN_SDP1_1
#define SWITZER_MANHATTAN_P2_LASI0_INT      I40E_GPIO_PIN_SDP1_2
#define SWITZER_MANHATTAN_P3_LASI1_INT      I40E_GPIO_PIN_SDP1_3
/* 2T use different name */
#define SWITZER_MANHATTAN_EXTPHY_INT        SWITZER_MANHATTAN_P2_LASI0_INT

#define SWITZER_MANHATTAN_LED_PORT2_ENB_YEL I40E_GPIO_PIN_SDP2_0
#define SWITZER_MANHATTAN_LED_PORT2_ENB_GRN I40E_GPIO_PIN_SDP2_1
#define SWITZER_MANHATTAN_LED_PORT3_ENB_YEL I40E_GPIO_PIN_SDP3_1
#define SWITZER_MANHATTAN_LED_PORT3_ENB_GRN I40E_GPIO_PIN_SDP3_2

#define SWITZER_MANHATTAN_LED_PORT0_LNK_GRN I40E_GPIO_PIN_LED0_1
#define SWITZER_MANHATTAN_LED_PORT1_LNK_GRN I40E_GPIO_PIN_LED0_0
#define SWITZER_MANHATTAN_LED_PORT2_LNK_GRN I40E_GPIO_PIN_LED1_1
#define SWITZER_MANHATTAN_LED_PORT3_LNK_GRN I40E_GPIO_PIN_LED3_1

#define SWITZER_MANHATTAN_LED_PORT0_ACTIVE_GRN I40E_GPIO_PIN_LED2_1
#define SWITZER_MANHATTAN_LED_PORT1_ACTIVE_GRN I40E_GPIO_PIN_LED2_0

#define SWITZER_MANHATTAN_PRI_IF_RDY        I40E_GPIO_PIN_GPIO_0
#define SWITZER_MANHATTAN_SFP_P3_DSL_DYGP   I40E_GPIO_PIN_GPIO_1
#define SWITZER_MANHATTAN_PSE_INTB          I40E_GPIO_PIN_GPIO_2
#define SWITZER_MANHATTAN_EXTPHY_GPIO0_0    I40E_GPIO_PIN_GPIO_3
#define SWITZER_MANHATTAN_EXTPHY_GPIO0_1    I40E_GPIO_PIN_GPIO_4
#define SWITZER_MANHATTAN_GPIO5_POR_BYPASS  I40E_GPIO_PIN_GPIO_5

#endif
