#!/bin/sh
# $Id: version,v 1.16 2019/09/10 01:03:39 haohsu Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/tachi_bmc/version,v $
#------------------------------------------------------------------
# Version control file for CSX-Tachi
#
# Copyright (c) 2016-2018 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.16  2019/09/10 01:03:39  haohsu
# [CSCvr07313]-Marvell 6320 to BMC eth1 frame error issue
#
# Revision 1.15  2018/12/18 13:37:13  hondwang
# Fix verion wrong, It should be 2.0.4 not 2.0.5
#
# Revision 1.14  2018/12/18 13:29:11  hondwang
# Fix CDETs CSCvn58971 with Goldschlager and Wallander on Tachi-L
#
# Revision 1.13  2018/11/23 01:08:11  haohsu
# Support NIM Goldschlager on Tachi-L
#
# Revision 1.12  2018/08/10 00:52:51  haohsu
# Update version for release
#
# Revision 1.11  2018/05/21 02:47:22  hondwang
# Update version
#
# Revision 1.10  2018/02/09 07:40:08  hondwang
# Modify F2W MCU utility to support offset R/W
#
# Revision 1.9  2017/05/24 06:52:08  haohsu
# Prompt to V2.0.0
#
# Revision 1.8  2017/04/05 08:31:22  kodko
# Roll back to V1.0.4.
#
# Revision 1.7  2017/04/05 03:48:41  kodko
# Prompt to V1.0.5
#
# Revision 1.6  2017/02/05 09:32:25  kodko
# Prompt to V1.0.4
#
# Revision 1.5  2016/08/12 07:39:18  jimmyya
# update version to 1.0.3
#
# Revision 1.4  2016/06/20 06:52:55  benchen2
# Bump up version for Tachi-l for release
#
# Revision 1.3  2016/06/06 18:35:35  huanngo
# Bump up version for Tachi-l for release
#
# Revision 1.2  2016/04/20 11:25:33  benchen2
# add tachi fru portion
#
# Revision 1.1.2.7  2016/03/23 07:05:08  benchen2
# change version to v0.2.2
#
# Revision 1.1.2.6  2016/03/03 02:14:15  benchen2
# change VERSION to 0.2.1
#
# Revision 1.1.2.5  2016/01/13 13:02:11  benchen2
# release v0.2.0
#
# Revision 1.1.2.4  2015/11/19 07:12:45  uid407316
# change version to 0.1.4
#
# Revision 1.1.2.3  2015/10/26 13:02:57  benchen2
# memory test percentage set to 90% and remove overcommit_ratio
#
# Revision 1.1.2.2  2015/09/21 13:09:31  tirawan
# Version to 0.1.2
#
# Revision 1.1.2.1  2015/06/11 02:01:11  tirawan
# Add files for Tachi BMC project
#
# $Endlog$
#

MAJOR_VERSION=2
MINOR_VERSION=0
RELEASE=5
