#!/bin/sh
#------------------------------------------------------------------
# Version control file for Highrise
#
# Copyright (c) 2019-2020 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------

MAJOR_VERSION=1
MINOR_VERSION=0
RELEASE=14
