#!/bin/sh
# $Id: version,v 1.18 2021/01/06 08:42:30 alicehua Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/nutella/version,v $
#------------------------------------------------------------------
# Version control file for espn-turbo
#
# Copyright (c) 2019 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.18  2021/01/06 08:42:30  alicehua
# Bumped up version to V2.0.6
#
# Revision 1.17  2020/10/05 06:07:14  alicehua
# Bumped up version to V2.0.5
#
# Revision 1.16  2020/08/13 00:15:26  alicehua
# Bumped up version to V2.0.4
#
# Revision 1.15  2020/07/13 06:34:32  alicehua
# Bumped up version to V2.0.3
#
# Revision 1.14  2020/05/18 01:14:36  alicehua
# Bumped up version to V2.0.2
#
# Revision 1.13  2020/03/13 06:57:35  alicehua
# Bump up version to V2.0.1
#
# Revision 1.12  2020/03/10 02:28:11  alicehua
# Bump up version to V2.0.0
#
# Revision 1.11  2020/01/14 09:49:51  harrchan
# Bump up version to v1.0.7
#
# Revision 1.10  2019/12/24 03:20:24  harrchan
# Bumped up version to V1.0.6
#
# Revision 1.9  2019/11/29 00:50:53  alicehua
# Bumped up version to V1.0.5
#
# Revision 1.8  2019/10/17 01:06:28  alicehua
# Bumped up version to V1.0.4
#
# Revision 1.7  2019/09/11 10:27:59  alicehua
# Bumped up version to V1.0.3
#
# Revision 1.6  2019/08/28 01:23:16  alicehua
# Bumped up version to V1.0.2
#
# Revision 1.5  2019/08/16 10:58:44  alicehua
# Bump version to V1.0.1
#
# Revision 1.4  2019/07/11 12:31:32  alicehua
# Collapse Nutella codes into main trunk.
#
# Revision 1.3.2.13  2019/07/02 01:46:28  alicehua
# Bumped up version to V0.0.13
#
# Revision 1.3.2.12  2019/07/01 01:48:33  alicehua
# Bumped up version to V0.0.12
#
# Revision 1.3.2.11  2019/06/25 01:19:27  alicehua
# Bumped up version to V0.0.11
#
# Revision 1.3.2.10  2019/06/11 09:52:17  alicehua
# Bumped up version to V0.0.10
#
# Revision 1.3.2.9  2019/05/30 02:49:26  alicehua
# Bumped up version to V0.0.9
#
# Revision 1.3.2.8  2019/05/21 02:22:04  alicehua
# Bumped up version to V0.0.8
#
# Revision 1.3.2.7  2019/05/16 01:32:48  alicehua
# Bump version to 0.0.7
#
# Revision 1.3.2.6  2019/05/03 09:33:59  harrchan
# Bump version to 0.0.6
#
# Revision 1.3.2.5  2019/04/12 01:18:25  harrchan
# Bump version to 0.0.5
#
# Revision 1.3.2.4  2019/03/18 07:56:50  harrchan
# Bump up version to v0.0.4
#
# Revision 1.3.2.3  2019/02/21 07:03:02  harrchan
# Bump up version to v0.0.3
#
# Revision 1.3.2.2  2019/01/11 12:18:23  haohsu
# Initial commit for Nutella project.
#
# $Endlog$
#

MAJOR_VERSION=2
MINOR_VERSION=0
RELEASE=6
