#!/bin/sh
# $Id: version,v 1.9 2015/06/10 00:39:59 ptong Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/fortitude/version,v $
#------------------------------------------------------------------
# Version control file for Fortitude
#
# Copyright (c) 2012-2013 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.9  2015/06/10 00:39:59  ptong
# Bump version to 1.4.3. No code change. 1.4.2 bundled a wrong FPGA image
#
# Revision 1.8  2015/02/27 22:54:55  ptong
# Bump version to 1.4.2. No code change. Just to recompile to fix codesign issue in 1.4.1
#
# Revision 1.7  2014/08/11 23:10:36  ywen
# Bump up version for FPGA version 2.1.0
#
# Revision 1.6  2014/05/07 22:11:03  ywen
# Bump up version
#
# Revision 1.5  2013/04/09 21:11:59  ywen
# Bump up version.
#
# Revision 1.4  2013/03/04 17:16:46  ywen
# bump up version.
#
# Revision 1.3  2013/02/13 23:56:11  ywen
# Bump up version.
#
# Revision 1.2  2013/02/05 16:43:10  ywen
# Bump up version for SB FPGA support.
#
# Revision 1.1  2013/01/22 20:46:41  ywen
# Initial check in for image version control.
#
#
# $Endlog$
#

MAJOR_VERSION=1
MINOR_VERSION=4
RELEASE=3
