/* $Id: curie2ru_miura_reg.h,v 1.1 2020/01/09 01:01:57 jiajliu Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/overlord/neptune/curie_2RU/curie2ru_miura_reg.h,v $
 *------------------------------------------------------------------
 *
 * curie2ru_miura_reg.h - Curie2ru broadcom miura register definitions.
 *
 * Dec. 2018, Nocken Zou <yozou@cisco.com>
 *
 * Copyright (c) 2018 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

#ifndef __CURIE2RU_MIURA_REG_H__
#define __CURIE2RU_MIURA_REG_H__

#define CURIE2RU_MIURA_DEV_PMA_PMD       1
#define CURIE2RU_MIURA_DEV_PCS           3
#define CURIE2RU_MIURA_DEV_CL73_AN       7

#define PHYMOD_MIURA_DIRECT_ACC    0x000000
#define MIURA_PM_TSCE_BASEADR 0x42000000
#define PHYMOD_MIURA_TSCE_BASE_ADDR 0x20000
#define MIURA_MERLIN_BASEADR    0x48000000

#define BCMI_MIURA_DIRECT_PAD_CNTRL_GPIO0_0_CONTROLr (0x00018a82 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_PAD_CNTRL_GPIO1_0_CONTROLr (0x00018a84 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_PAD_CNTRL_GPIO0_1_CONTROLr (0x00018a86 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_PAD_CNTRL_GPIO1_1_CONTROLr (0x00018a88 | PHYMOD_MIURA_DIRECT_ACC)

#define BCMI_MIURA_DIRECT_CTRL_LED_OPMODEr (0x00018ba0 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_CTRL_LED_PARAMSr (0x00018ba1 | PHYMOD_MIURA_DIRECT_ACC)

#define BCMI_MIURA_DIRECT_PAD_CNTRL_MOD_ABS_0_STATUSr (0x00018a6f | PHYMOD_MIURA_DIRECT_ACC)

#define BCMI_MIURA_DIRECT_PAD_CNTRL_LASI_0_CONTROLr (0x00018a4e | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_PAD_CNTRL_LASI_1_CONTROLr (0x00018a50 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_CTRL_PORT0_CONFIGr (0x00018b03 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_CTRL_PORT1_CONFIGr (0x00018b05 | PHYMOD_MIURA_DIRECT_ACC)

#define BCMI_TSCE_XGXS_AN_X4_ENSr (0x0000c180 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_AN_X4_LOC_DEV_CL37_BASE_ABILr (0x0000c181 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)

#define BCMI_MIURA_INDIRECT_MERLIN_PMD_TX_CTRL5r (0x0000d0a5 | MIURA_MERLIN_BASEADR)
#define BCMI_MIURA_INDIRECT_MERLIN_PMD_TX_FIR_CTRL1r (0x0000d110 | MIURA_MERLIN_BASEADR)
#define BCMI_MIURA_INDIRECT_MERLIN_PMD_TX_FIR_CTRL2r (0x0000d111 | MIURA_MERLIN_BASEADR)

/* general ctrl regs */
#define BCMI_MIURA_DIRECT_GEN_CNTRLS_CLOCK_SCALER_CTRLr (0x00018200 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_GEN_CNTRLS_GEN_CONTROL1r (0x00018201 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_GEN_CNTRLS_GEN_CONTROL2r (0x00018202 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_GEN_CNTRLS_GEN_CONTROL3r (0x00018203 | PHYMOD_MIURA_DIRECT_ACC)

#define BCMI_MIURA_DIRECT_MICRO_BOOT_MDIO_PORr (0x000182fe | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_MICRO_BOOT_BOOT_PORr (0x000182ff | PHYMOD_MIURA_DIRECT_ACC)

#define BCMI_MIURA_DIRECT_CTRL_CHIP_IDr (0x00018b00 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_CTRL_CHIP_REVISIONr (0x00018b01 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_CTRL_CHIP_CONFIGr (0x00018b02 | PHYMOD_MIURA_DIRECT_ACC)

#define BCMI_MIURA_DIRECT_MODULE_CNTRL_CONTROLr (0x00018700 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_MODULE_CNTRL_STATUSr (0x00018701 | PHYMOD_MIURA_DIRECT_ACC)

#define BCMI_MIURA_DIRECT_PAD_CNTRL_MDIO1_CONTROLr (0x00018a30 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_PAD_CNTRL_MDIO2_CONTROLr (0x00018a32 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_PAD_CNTRL_ADR0_CONTROLr (0x00018a34 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_PAD_CNTRL_ADR1_CONTROLr (0x00018a36 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_PAD_CNTRL_ADR2_CONTROLr (0x00018a38 | PHYMOD_MIURA_DIRECT_ACC)

#define BCMI_MIURA_DIRECT_M0ACCESS_ADDR_MST_CRAM_MEM_ADD_CTRLr (0x00018400 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_M0ACCESS_ADDR_MST_DRAM_MEM_ADD_CTRLr (0x00018401 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_M0ACCESS_ADDR_MST_VT_ADD_CTRLr (0x00018402 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_M0ACCESS_ADDR_SLV1_CRAM_MEM_ADD_CTRLr (0x00018403 | PHYMOD_MIURA_DIRECT_ACC)

#define BCMI_MIURA_DIRECT_LMI_LMI_RESET_CTRLr (0x00019000 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_LMI_LMI_CMDr (0x00019001 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_LMI_LMI_ADDRr (0x00019002 | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_LMI_LMI_DATAr (0x00019003 | PHYMOD_MIURA_DIRECT_ACC)

#define BCMI_MIURA_DIRECT_GEN_CNTRLS_GPREG_1Cr (0x0001826c | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_GEN_CNTRLS_GPREG_1Dr (0x0001826d | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_GEN_CNTRLS_GPREG_1Er (0x0001826e | PHYMOD_MIURA_DIRECT_ACC)
#define BCMI_MIURA_DIRECT_GEN_CNTRLS_GPREG_1Fr (0x0001826f | PHYMOD_MIURA_DIRECT_ACC)

/*  tsce regs */
#define BCMI_TSCE_XGXS_RX_X4_PCS_CTL0r (0x0000c130 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_TX_X4_PCS_STSr (0x0000c121 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_PMA_CTL0r (0x0000c137 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_PCS_LATCH_STS1r (0x0000c152 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_PCS_LATCH_STS0r (0x0000c153 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_PCS_LIVE_STSr (0x0000c154 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)

#define BCMI_TSCE_XGXS_PMD_X1_STSr (0x00009012 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_PMD_X4_CTLr (0x0000c010 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_PMD_X4_MODEr (0x0000c011 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_PMD_X4_STSr (0x0000c012 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)

#define BCMI_TSCE_XGXS_RX_X4_FEC0r (0x0000c131 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_FEC1r (0x0000c132 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_FEC_CORRBLKSLr (0x0000c157 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_FEC_CORRBLKSHr (0x0000c158 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_FEC_UNCORRBLKSLr (0x0000c159 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_FEC_UNCORRBLKSHr (0x0000c15a | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_FEC_BURST_ERR_STSLr (0x0000c142 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_FEC_BURST_ERR_STSHr (0x0000c143 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_RX_X4_FEC_DBG_ERRAHr (0x0000c141 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_PKTGEN_CRCERRCNTr (0x00009033 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_PATGEN_TXPKTCNT_Ur (0x0000c040 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_PATGEN_TXPKTCNT_Lr (0x0000c041 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_PATGEN_RXPKTCNT_Ur (0x0000c042 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#define BCMI_TSCE_XGXS_PATGEN_RXPKTCNT_Lr (0x0000c043 | PHYMOD_MIURA_TSCE_BASE_ADDR | MIURA_PM_TSCE_BASEADR)
#endif /* __CURIE2RU_MIURA_REG_H__ */

/*
 *-----------------------------------------------------------------------------
$Log: curie2ru_miura_reg.h,v $
Revision 1.1  2020/01/09 01:01:57  jiajliu
Merge Curie 2RU to main trunk

$Endlog$
 *-----------------------------------------------------------------------------
 */
