#!/bin/sh
# $Id: version,v 1.19 2021/08/20 01:38:25 xiaolaya Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/overlord/neptune/curie_2RU/version,v $
#------------------------------------------------------------------
# Version control file for Curie 2RU
#
# Copyright (c) 2019-2020 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.19  2021/08/20 01:38:25  xiaolaya
# Bump version to V1.11.3
#
# Revision 1.18  2021/08/05 08:15:21  xiaolaya
# Bump version to V1.11.2
#
# Revision 1.17  2021/07/15 02:21:58  chenglso
# *** empty log message ***
#
# Revision 1.16  2021/07/14 02:35:50  chenglso
# show NIM Daughter info during the carrier initialization
#
# Revision 1.15  2021/06/04 17:29:55  tshanmug
# bump up version for curie1RU (v2.13.0) and Curie2ru (V1.11.0)
#
# Revision 1.14  2021/06/04 01:06:17  xiaolaya
# Bump version to 1.10.1
#
# Revision 1.13  2021/06/02 02:56:25  alpeng
# merge sears into trunk
#
# Revision 1.12  2021/04/20 06:54:45  xiaolaya
# Bump version to V1.10.0
#
# Revision 1.11  2021/03/31 10:20:56  xiaolaya
# Add M2 Testcard support
#
# Revision 1.10  2021/02/24 03:46:38  xiaolaya
# Fix bug for Switzer-Carrier SM Daughter NIM Daughter VM cookie
#
# Revision 1.9  2021/01/11 13:42:30  xiaolaya
# Bump version to 1.7.0
#
# Revision 1.8  2020/12/23 11:32:13  jiajliu
# Bump version to 1.6.0
#
# Revision 1.7  2020/09/14 03:22:00  qingcwan
# Bump curie2ru version.
#
# Revision 1.6.10.1  2020/12/02 03:57:22  tshanmug
# Sears Antenna test updated
#
# Revision 1.6  2020/05/22 06:30:20  qingcwan
# Bump version to 1.4.0
#
# Revision 1.5  2020/04/20 12:06:16  jiajliu
# Bump version to 1.3.2
#
# Revision 1.4  2020/04/06 06:06:40  letsai
# Bump version to 1.3.1
#
# Revision 1.3  2020/03/18 07:57:29  letsai
# Bump version to 1.3.0
#
# Revision 1.2  2020/03/11 17:50:36  jiajliu
# Fix BCM57412 MAC programming and bump version to 1.2.0
#
# Revision 1.1  2020/01/09 01:02:07  jiajliu
# Merge Curie 2RU to main trunk
#
# $Endlog$

MAJOR_VERSION=1
MINOR_VERSION=11
RELEASE=3

