#!/bin/sh
# $Id: version,v 1.2 2020/03/13 12:06:54 letsai Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/grimlock/version,v $
#------------------------------------------------------------------
# Version control file for Grimlock
#
# Copyright (c) 2020 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.2  2020/03/13 12:06:54  letsai
# Merge Grimlock NIM to maintrunk
#
# Revision 1.1.4.2  2020/01/15 03:30:12  wilbhuan
# 1. Initial code of Grimlock NIM application.
# 2. Leveraged from Fortitude Grimlock NIM.
# 3. Only replace all Fortitude related word as Grimlock.
# 4. Fortitude's T1/E1 function doesn't remove.
#
# $Endlog$
#

MAJOR_VERSION=1
MINOR_VERSION=0
RELEASE=0
