#!/bin/sh
# $Id: version,v 1.52 2020/04/06 06:05:00 letsai Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/overlord/utah/version,v $
#------------------------------------------------------------------
# Version control file for xformers
#
# Copyright (c) 2013 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.52  2020/04/06 06:05:00  letsai
# Bump version to 6.14.1
#
# Revision 1.51  2020/03/18 07:55:24  letsai
# Bump version to 6.14.0
#
# Revision 1.50  2019/09/11 07:18:15  alpeng
# CSCvr18160 - adjust NIOS mode setup on Utah
#
# Revision 1.49  2019/08/26 03:39:08  alpeng
# bump to 6.13.1 - CSCvq64781
#
# Revision 1.48  2019/08/19 12:55:32  mingding
# CSCvk64124-39: bump version for release with supporting SM-Nightwatch
#
# Revision 1.47  2018/07/04 03:06:08  alpeng
# bump up version 6.11.7 CSCvk04736-2
#
# Revision 1.46  2018/05/10 03:24:12  leschen
# Bump up version to V6.11.6
#
# Revision 1.45  2017/09/29 03:12:49  harrchan
# Bump version to 6.11.3
#
# Revision 1.44  2017/08/16 03:00:44  harrchan
# Bump version to 6.11.2
#
# Revision 1.43  2017/06/19 01:31:46  olin2
# Bump version to 6.11.1
#
# Revision 1.42  2017/04/17 07:41:44  umlin
# Bump version to 6.11.0, new product Reva-SM supported in this release
#
# Revision 1.41  2017/03/23 03:45:17  haohsu
# Bump version to 6.10.1, support Kaziranga project
#
# Revision 1.40  2016/05/09 13:06:29  umlin
# Bump version to 6.10.0, new product Reva supported in this release
#
# Revision 1.39  2016/03/22 06:17:03  alpeng
# Bump version to 6.9.0, for F35 host side code update
#
# Revision 1.38  2016/01/21 02:53:20  olin2
# Bump version to 6.8.0
#
# Revision 1.37  2015/06/23 23:03:59  ptong
# Tune Linux memory overcommit ratio to 80%, bump version to 6.7.1
#
# Revision 1.36  2015/06/05 06:13:42  alpeng
# bump to 6.7.0
#
# Revision 1.35  2015/05/26 08:35:32  steja
# Bump version to V6.6.0
#
# Revision 1.34  2015/05/15 01:17:53  hondwang
# bump to version 6.5.0
#
# Revision 1.33  2015/03/31 07:37:36  leschen
# Bump version to 6.4.2
#
# Revision 1.32  2015/03/23 20:14:05  ptong
# Bunp version to 6.4.1
#
# Revision 1.31  2015/02/26 03:27:56  meho
# Bump version to 6.4.0
#
# Revision 1.30  2015/02/24 18:45:31  srane
# bump version to 6.3.0
#
# Revision 1.29  2014/12/04 19:18:47  ptong
# Bump version to 6.2.0
#
# Revision 1.28  2014/11/14 01:18:53  leschen
# Bump up to V6.1.0
#
# Revision 1.27  2014/10/18 00:08:47  ptong
# Bump version to 6.0.0
#
# Revision 1.26  2014/10/07 01:00:12  ptong
# Bump version to 5.4.0
#
# Revision 1.25  2014/09/17 13:40:33  jamlin
# Bump up the version.
#
# Revision 1.24  2014/08/22 23:56:09  ptong
# Bump version to V5.2.0
#
# Revision 1.23  2014/07/23 02:32:41  ptong
# Bump version to 5.1.0
#
# Revision 1.22  2014/06/27 23:13:08  ptong
# Bump version to 5.0.0 to support Broadcom Greyhound GESW
#
# Revision 1.21  2014/06/19 22:00:52  ptong
# Incorporated BCM sdk-6.4.1-EA2 for 10G-KR interface. New code works on O2, June, and non Greyhound USD regression
#
# Revision 1.20  2014/06/05 09:19:48  alpeng
# Bump version to 4.2 to support new clock chip for margining
#
# Revision 1.19  2014/05/21 06:57:41  alpeng
# bump to version 4.1
#
# Revision 1.18  2014/04/02 22:26:08  ptong
# Bump version to 4.0. Release with victory-kernel and prepare for new GESW.
#
# Revision 1.17  2014/03/21 18:43:05  ptong
# Bump version to 3.8 for utah pre-pilot release
#
# Revision 1.16  2014/03/06 19:51:43  ptong
# Bump version to 3.7 for utah pre-pilot release
#
# Revision 1.15  2014/02/18 22:51:28  ptong
# Bump version to 3.6 for utah pre-pilot release
#
# Revision 1.14  2014/01/22 22:18:56  ptong
# Bump version to 3.5.0
#
# Revision 1.13  2013/12/21 01:40:27  ptong
# Bump version to 3.4 to support Dagger. Fixed issues on CPU core check, and PCIe lane check. Support PLX eeprom programming in kernel
#
# Revision 1.12  2013/12/13 19:20:20  ptong
# Bump version to 3.3. Added fan RPM display, I2C test check platform type and work accordingly. Fixed HDD test. Kernel: enlarged 1548 eye. work with ROMMON bringup4, PCIe lane checked
#
# Revision 1.11  2013/12/05 22:52:52  ptong
# Bump version to 3.2. Fixed Utah PSU, POE support and PCIe bus change dur to ROMMON UTAHBRINGUP4
#
# Revision 1.10  2013/12/03 00:47:49  ptong
# Bump version to 3.1
#
# Revision 1.9  2013/11/18 02:32:46  ptong
# Bump version to 3.0 for support of Sword
#
# Revision 1.8  2013/10/22 18:10:44  ptong
# Bump version to 2.1.0. Fixed BCM sal_free BAD_PTR issue, Added eMMC DFU utils, work around for testcard PCIe test with PLX switch
#
# Revision 1.7  2013/10/02 22:15:51  ptong
# Bump version to 2.0.0. Release to support P1B in EDVT
#
# Revision 1.6  2013/09/11 21:41:08  ptong
# Bump version to 1.0.0 and support i211 eeprom MAC programming for P1B
#
# Revision 1.5  2013/09/09 17:55:19  ptong
# Bump minor version to 3
#
# Revision 1.4  2013/08/24 00:51:00  ptong
# Minor change and clean up for 0.2.0 release
#
# Revision 1.3  2013/07/16 01:34:46  ptong
# Bump minor version to 1
#
# Revision 1.2  2013/05/28 18:25:04  ptong
# Reset version to 0.0
#
# Revision 1.1  2013/05/09 05:53:00  alpeng
# add utah tree
# $Endlog$
#

MAJOR_VERSION=6
MINOR_VERSION=14
RELEASE=1
