#!/bin/sh
# $Id: version,v 1.5 2020/04/20 02:28:24 lucywang Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/nanook/version,v $
#------------------------------------------------------------------
# Version control file for Nanook
#
# Copyright (c) 2019 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.5  2020/04/20 02:28:24  lucywang
#
# 1. Fixed unplug/plug NIM module dynamically issue and added NIM cookie
# 2. Added to support NIM Prince
# 3. (CSCvn43011) add retry workaround for Deverton issue
# 4. add debug message and set default value to seneors
# 5. Reverted Register value of temp/press snsr after test
# 6. Bumped up version to 1.0.2
#
# Revision 1.4  2019/12/20 06:09:01  yungchen
# Bumped up version
#
# Revision 1.3  2019/12/13 06:26:31  yungchen
# Bumped up version
#
# Revision 1.2  2019/12/11 10:10:36  lucywang
# Merged Nanook to main trunk
#

MAJOR_VERSION=1
MINOR_VERSION=0
RELEASE=2
