#!/bin/sh
# $Id: version,v 1.24 2014/12/15 23:37:51 ptong Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/overlord/cavium/version,v $
#------------------------------------------------------------------
# Version control file for Overlord Data Plane
#
# Copyright (c) 2013 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.24  2014/12/15 23:37:51  ptong
# Bump version to 11.1.0
#
# Revision 1.23  2014/10/29 03:14:41  alpeng
# bump to version 11.0
#
# Revision 1.22  2014/09/10 04:27:25  alpeng
# bump to version 10.2
#
# Revision 1.21  2014/05/15 02:42:23  alpeng
# bump up version to 10.1
#
# Revision 1.20  2014/05/05 17:36:01  ptong
# Bump version to 10.0
#
# Revision 1.19  2014/04/03 20:43:22  ptong
# Bump version to 9.2
#
# Revision 1.18  2014/02/18 03:37:15  alpeng
# Bump to version 9.1
#
# Revision 1.17  2013/10/08 01:38:25  alpeng
# Bump version to 9.0
#
# Revision 1.16  2013/07/22 17:51:28  ptong
# Bump version to 8.2
#
# Revision 1.15  2013/05/23 20:52:02  ptong
# Bump version to 8.0
#
# Revision 1.14  2013/03/15 00:03:02  ptong
# Bump version to 7.1
#
# Revision 1.13  2013/02/28 23:14:08  ptong
# Bump version to 7.0
#
# Revision 1.12  2013/02/23 07:31:55  ptong
# Fixed the problem due to new ROMMON changed the PCIe bus numbering and bumped diag version to 6.3
#
# Revision 1.11  2013/01/26 00:29:36  ptong
# Bump version to 6.2
#
# Revision 1.10  2013/01/14 19:55:20  ptong
# Bump version to 6.1
#
# Revision 1.9  2012/12/21 02:15:12  ptong
# Bump version to 6.0
#
# Revision 1.8  2012/11/29 22:58:40  ptong
# Bump version to 5.0
#
# Revision 1.7  2012/11/05 23:56:23  ptong
# Bump version to 4.2
#
# Revision 1.6  2012/10/25 22:44:32  ptong
# Bump version to 4.1
#
# Revision 1.5  2012/10/18 06:06:46  ptong
# Bump version to 4.0
#
# Revision 1.4  2012/09/27 23:50:58  ptong
# Bump version to 3.1
#
# Revision 1.3  2012/09/18 23:56:42  ptong
# Bump major version to 3
#
# Revision 1.2  2012/08/24 23:11:40  ptong
# Increase the fiber output amplitude in PHY-1548
#
# Revision 1.1  2012/08/10 22:51:38  ptong
# Add version banner
#
# $Endlog$
#

MAJOR_VERSION=11
MINOR_VERSION=1
RELEASE=0
