/* $Id: ag_mg_regs_uart.h,v 1.1 2012/04/18 18:08:27 srane Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/sp27dsp/dss/inc/ag_mg_regs_uart.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_uart.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_uart.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of LSI Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * The SP2704 DSP provides a universal asynchronous receiver transmitter (UART) that
 * performs serial-to-parallel conversion of data received from a peripheral device
 * and parallel-to-serial conversion of data transmitted to a peripheral device.
 * 
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *
 *  UARTDR
 *  UARTRSR
 *  UARTFR
 *  UARTILPR
 *  UARTIBRD
 *  UARTFBRD
 *  UARTLCR_H
 *  UARTCR
 *  UARTIFLS
 *  UARTIMSC
 *  UARTRIS
 *  UARTMIS
 *  UARTICR
 *  UARTDMACR
 *  UARTPERIPHID0
 *  UARTPERIPHID1
 *  UARTPERIPHID2
 *  UARTPERIPHID3
 *  UARTPCELLID0
 *  UARTPCELLID1
 *  UARTPCELLID2
 *  UARTPCELLID3
*
* Prefix naming conventions :
*   AG_MG_REGS_XXX_RA : register/memory physical address
*   AG_MG_REGS_XXX_RO : register/memory address offset
*   AG_MG_REGS_XXX_RM : register mask
*   AG_MG_REGS_XXX_BO : bit/field offset from LSB
*   AG_MG_REGS_XXX_BM : bit/field mask
*   AG_MG_REGS_XXX_U  : bitfields in C union typedef
*   AG_MG_REGS_XXX_S  : registers in C struct typedef
*   AG_MG_REGS_XX_RPT : number of identical registers in array
*   AG_MG_REGS_XX_IVL : interval between registers in array
*
* NOTE: user may redefine ag_mg_regs_register
*       in ag_mg_regs_regops.h if necessary
* NOTE: access mode of individual bit fields matches that
*       of containing register unless indicated otherwise
*/

#ifndef AG_MG_REGS_UART_REGISTERS_H
#define AG_MG_REGS_UART_REGISTERS_H

#include "ag_mg_regs_regops.h"


/*
 * Generated by HSI Designer release 2.3.5.
 */


/*
 * UARTDR (Control register0)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_UARTDR_RO                         0x00000000
#define AG_MG_REGS_UARTDR_RM                         0x00000FFF

#define AG_MG_REGS_UARTDR_DATA_BO                    0
#define AG_MG_REGS_UARTDR_DATA_BM                    0x000000FF

#define AG_MG_REGS_UARTDR_FE_BO                      8
#define AG_MG_REGS_UARTDR_FE_BM                      0x00000100

#define AG_MG_REGS_UARTDR_PE_BO                      9
#define AG_MG_REGS_UARTDR_PE_BM                      0x00000200

#define AG_MG_REGS_UARTDR_BE_BO                      10
#define AG_MG_REGS_UARTDR_BE_BM                      0x00000400

#define AG_MG_REGS_UARTDR_OE_BO                      11
#define AG_MG_REGS_UARTDR_OE_BM                      0x00000800

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTDR_U
{
    struct
    {
        ag_mg_regs_register
            data : 8,
            fe : 1,
            pe : 1,
            be : 1,
            oe : 1,
            fill0 : 20;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartdr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTRSR_RO                        0x00000004
#define AG_MG_REGS_UARTRSR_RM                        0x0000000F

#define AG_MG_REGS_UARTRSR_FE_BO                     0
#define AG_MG_REGS_UARTRSR_FE_BM                     0x00000001

#define AG_MG_REGS_UARTRSR_PE_BO                     1
#define AG_MG_REGS_UARTRSR_PE_BM                     0x00000002

#define AG_MG_REGS_UARTRSR_BE_BO                     2
#define AG_MG_REGS_UARTRSR_BE_BM                     0x00000004

#define AG_MG_REGS_UARTRSR_OE_BO                     3
#define AG_MG_REGS_UARTRSR_OE_BM                     0x00000008

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTRSR_U
{
    struct
    {
        ag_mg_regs_register
            fe : 1,
            pe : 1,
            be : 1,
            oe : 1,
            fill0 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartrsr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTFR_RO                         0x00000018
#define AG_MG_REGS_UARTFR_RM                         0x000001FF

#define AG_MG_REGS_UARTFR_BUSY_BO                    3
#define AG_MG_REGS_UARTFR_BUSY_BM                    0x00000008

#define AG_MG_REGS_UARTFR_RXFE_BO                    4
#define AG_MG_REGS_UARTFR_RXFE_BM                    0x00000010

#define AG_MG_REGS_UARTFR_TXFF_BO                    5
#define AG_MG_REGS_UARTFR_TXFF_BM                    0x00000020

#define AG_MG_REGS_UARTFR_RXFF_BO                    6
#define AG_MG_REGS_UARTFR_RXFF_BM                    0x00000040

#define AG_MG_REGS_UARTFR_TXFE_BO                    7
#define AG_MG_REGS_UARTFR_TXFE_BM                    0x00000080


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTFR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 3,
            busy : 1,
            rxfe : 1,
            txff : 1,
            rxff : 1,
            txfe : 1,
            fill1 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartfr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_UARTILPR_RO                       0x00000020
#define AG_MG_REGS_UARTILPR_RM                       0x000000FF

#define AG_MG_REGS_UARTILPR_ILPDVSR_BO               0
#define AG_MG_REGS_UARTILPR_ILPDVSR_BM               0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTILPR_U
{
    struct
    {
        ag_mg_regs_register
            ilpdvsr : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartilpr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_UARTIBRD_RO                       0x00000024
#define AG_MG_REGS_UARTIBRD_RM                       0x0000FFFF

#define AG_MG_REGS_UARTIBRD_BAUDDIVINT_BO            0
#define AG_MG_REGS_UARTIBRD_BAUDDIVINT_BM            0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTIBRD_U
{
    struct
    {
        ag_mg_regs_register
            bauddivint : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartibrd_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_UARTFBRD_RO                       0x00000028
#define AG_MG_REGS_UARTFBRD_RM                       0x0000003F

#define AG_MG_REGS_UARTFBRD_BAUDDIVFRAC_BO           0
#define AG_MG_REGS_UARTFBRD_BAUDDIVFRAC_BM           0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTFBRD_U
{
    struct
    {
        ag_mg_regs_register
            bauddivfrac : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartfbrd_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_UARTLCR_H_RO                      0x0000002C
#define AG_MG_REGS_UARTLCR_H_RM                      0x000000FF

#define AG_MG_REGS_UARTLCR_H_BRK_BO                  0
#define AG_MG_REGS_UARTLCR_H_BRK_BM                  0x00000001

#define AG_MG_REGS_UARTLCR_H_PEN_BO                  1
#define AG_MG_REGS_UARTLCR_H_PEN_BM                  0x00000002

#define AG_MG_REGS_UARTLCR_H_EPS_BO                  2
#define AG_MG_REGS_UARTLCR_H_EPS_BM                  0x00000004

#define AG_MG_REGS_UARTLCR_H_STP2_BO                 3
#define AG_MG_REGS_UARTLCR_H_STP2_BM                 0x00000008

#define AG_MG_REGS_UARTLCR_H_FEN_BO                  4
#define AG_MG_REGS_UARTLCR_H_FEN_BM                  0x00000010

#define AG_MG_REGS_UARTLCR_H_WLEN_BO                 5
#define AG_MG_REGS_UARTLCR_H_WLEN_BM                 0x00000060

#define AG_MG_REGS_UARTLCR_H_SPS_BO                  7
#define AG_MG_REGS_UARTLCR_H_SPS_BM                  0x00000080

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTLCR_H_U
{
    struct
    {
        ag_mg_regs_register
            brk : 1,
            pen : 1,
            eps : 1,
            stp2 : 1,
            fen : 1,
            wlen : 2,
            sps : 1,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartlcr_h_u;
#endif


/*
 * Initialization value: 0x00000300  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_UARTCR_RO                         0x00000030
#define AG_MG_REGS_UARTCR_RM                         0x0000FF87

#define AG_MG_REGS_UARTCR_UARTEN_BO                  0
#define AG_MG_REGS_UARTCR_UARTEN_BM                  0x00000001

#define AG_MG_REGS_UARTCR_SIREN_BO                   1
#define AG_MG_REGS_UARTCR_SIREN_BM                   0x00000002

#define AG_MG_REGS_UARTCR_SIRLP_BO                   2
#define AG_MG_REGS_UARTCR_SIRLP_BM                   0x00000004

#define AG_MG_REGS_UARTCR_LBE_BO                     7
#define AG_MG_REGS_UARTCR_LBE_BM                     0x00000080

#define AG_MG_REGS_UARTCR_TXE_BO                     8
#define AG_MG_REGS_UARTCR_TXE_BM                     0x00000100

#define AG_MG_REGS_UARTCR_RXE_BO                     9
#define AG_MG_REGS_UARTCR_RXE_BM                     0x00000200


#define AG_MG_REGS_UARTCR_RTSEN_BO                   14
#define AG_MG_REGS_UARTCR_RTSEN_BM                   0x00004000

#define AG_MG_REGS_UARTCR_CTSEN_BO                   15
#define AG_MG_REGS_UARTCR_CTSEN_BM                   0x00008000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTCR_U
{
    struct
    {
        ag_mg_regs_register
            uarten : 1,
            siren : 1,
            sirlp : 1,
            fill2 : 4,
            lbe : 1,
            txe : 1,
            rxe : 1,
            fill1 : 4,
            rtsen : 1,
            ctsen : 1,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartcr_u;
#endif


/*
 * Initialization value: 0x00000012  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_UARTIFLS_RO                       0x00000034
#define AG_MG_REGS_UARTIFLS_RM                       0x0000003F

#define AG_MG_REGS_UARTIFLS_TXIFLSEL_BO              0
#define AG_MG_REGS_UARTIFLS_TXIFLSEL_BM              0x00000007

#define AG_MG_REGS_UARTIFLS_RXIFLSEL_BO              3
#define AG_MG_REGS_UARTIFLS_RXIFLSEL_BM              0x00000038

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTIFLS_U
{
    struct
    {
        ag_mg_regs_register
            txiflsel : 3,
            rxiflsel : 3,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartifls_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_UARTIMSC_RO                       0x00000038
#define AG_MG_REGS_UARTIMSC_RM                       0x000007FF

#define AG_MG_REGS_UARTIMSC_RIMIM_BO                 0
#define AG_MG_REGS_UARTIMSC_RIMIM_BM                 0x00000001

#define AG_MG_REGS_UARTIMSC_CTSMIM_BO                1
#define AG_MG_REGS_UARTIMSC_CTSMIM_BM                0x00000002

#define AG_MG_REGS_UARTIMSC_DCDMIM_BO                2
#define AG_MG_REGS_UARTIMSC_DCDMIM_BM                0x00000004

#define AG_MG_REGS_UARTIMSC_DSRMIM_BO                3
#define AG_MG_REGS_UARTIMSC_DSRMIM_BM                0x00000008

#define AG_MG_REGS_UARTIMSC_RXIM_BO                  4
#define AG_MG_REGS_UARTIMSC_RXIM_BM                  0x00000010

#define AG_MG_REGS_UARTIMSC_TXIM_BO                  5
#define AG_MG_REGS_UARTIMSC_TXIM_BM                  0x00000020

#define AG_MG_REGS_UARTIMSC_RTIM_BO                  6
#define AG_MG_REGS_UARTIMSC_RTIM_BM                  0x00000040

#define AG_MG_REGS_UARTIMSC_FEIM_BO                  7
#define AG_MG_REGS_UARTIMSC_FEIM_BM                  0x00000080

#define AG_MG_REGS_UARTIMSC_PEIM_BO                  8
#define AG_MG_REGS_UARTIMSC_PEIM_BM                  0x00000100

#define AG_MG_REGS_UARTIMSC_BEIM_BO                  9
#define AG_MG_REGS_UARTIMSC_BEIM_BM                  0x00000200

#define AG_MG_REGS_UARTIMSC_OEIM_BO                  10
#define AG_MG_REGS_UARTIMSC_OEIM_BM                  0x00000400

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTIMSC_U
{
    struct
    {
        ag_mg_regs_register
            rimim : 1,
            ctsmim : 1,
            dcdmim : 1,
            dsrmim : 1,
            rxim : 1,
            txim : 1,
            rtim : 1,
            feim : 1,
            peim : 1,
            beim : 1,
            oeim : 1,
            fill0 : 21;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartimsc_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTRIS_RO                        0x0000003C
#define AG_MG_REGS_UARTRIS_RM                        0x000007FF

#define AG_MG_REGS_UARTRIS_RIRMIS_BO                 0
#define AG_MG_REGS_UARTRIS_RIRMIS_BM                 0x00000001

#define AG_MG_REGS_UARTRIS_CTSRMIS_BO                1
#define AG_MG_REGS_UARTRIS_CTSRMIS_BM                0x00000002

#define AG_MG_REGS_UARTRIS_DCDRMIS_BO                2
#define AG_MG_REGS_UARTRIS_DCDRMIS_BM                0x00000004

#define AG_MG_REGS_UARTRIS_DSRRMIS_BO                3
#define AG_MG_REGS_UARTRIS_DSRRMIS_BM                0x00000008

#define AG_MG_REGS_UARTRIS_RXRIS_BO                  4
#define AG_MG_REGS_UARTRIS_RXRIS_BM                  0x00000010

#define AG_MG_REGS_UARTRIS_TXRIS_BO                  5
#define AG_MG_REGS_UARTRIS_TXRIS_BM                  0x00000020

#define AG_MG_REGS_UARTRIS_RTRIS_BO                  6
#define AG_MG_REGS_UARTRIS_RTRIS_BM                  0x00000040

#define AG_MG_REGS_UARTRIS_FERIS_BO                  7
#define AG_MG_REGS_UARTRIS_FERIS_BM                  0x00000080

#define AG_MG_REGS_UARTRIS_PERIS_BO                  8
#define AG_MG_REGS_UARTRIS_PERIS_BM                  0x00000100

#define AG_MG_REGS_UARTRIS_BERIS_BO                  9
#define AG_MG_REGS_UARTRIS_BERIS_BM                  0x00000200

#define AG_MG_REGS_UARTRIS_OERIS_BO                  10
#define AG_MG_REGS_UARTRIS_OERIS_BM                  0x00000400

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTRIS_U
{
    struct
    {
        ag_mg_regs_register
            rirmis : 1,
            ctsrmis : 1,
            dcdrmis : 1,
            dsrrmis : 1,
            rxris : 1,
            txris : 1,
            rtris : 1,
            feris : 1,
            peris : 1,
            beris : 1,
            oeris : 1,
            fill0 : 21;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartris_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTMIS_RO                        0x00000040
#define AG_MG_REGS_UARTMIS_RM                        0x000007FF

#define AG_MG_REGS_UARTMIS_RIMMIS_BO                 0
#define AG_MG_REGS_UARTMIS_RIMMIS_BM                 0x00000001

#define AG_MG_REGS_UARTMIS_CTSMMIS_BO                1
#define AG_MG_REGS_UARTMIS_CTSMMIS_BM                0x00000002

#define AG_MG_REGS_UARTMIS_DCDMMIS_BO                2
#define AG_MG_REGS_UARTMIS_DCDMMIS_BM                0x00000004

#define AG_MG_REGS_UARTMIS_DSRMMIS_BO                3
#define AG_MG_REGS_UARTMIS_DSRMMIS_BM                0x00000008

#define AG_MG_REGS_UARTMIS_RXMIS_BO                  4
#define AG_MG_REGS_UARTMIS_RXMIS_BM                  0x00000010

#define AG_MG_REGS_UARTMIS_TXMIS_BO                  5
#define AG_MG_REGS_UARTMIS_TXMIS_BM                  0x00000020

#define AG_MG_REGS_UARTMIS_RTMIS_BO                  6
#define AG_MG_REGS_UARTMIS_RTMIS_BM                  0x00000040

#define AG_MG_REGS_UARTMIS_FEMIS_BO                  7
#define AG_MG_REGS_UARTMIS_FEMIS_BM                  0x00000080

#define AG_MG_REGS_UARTMIS_PEMIS_BO                  8
#define AG_MG_REGS_UARTMIS_PEMIS_BM                  0x00000100

#define AG_MG_REGS_UARTMIS_BEMIS_BO                  9
#define AG_MG_REGS_UARTMIS_BEMIS_BM                  0x00000200

#define AG_MG_REGS_UARTMIS_OEMIS_BO                  10
#define AG_MG_REGS_UARTMIS_OEMIS_BM                  0x00000400

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTMIS_U
{
    struct
    {
        ag_mg_regs_register
            rimmis : 1,
            ctsmmis : 1,
            dcdmmis : 1,
            dsrmmis : 1,
            rxmis : 1,
            txmis : 1,
            rtmis : 1,
            femis : 1,
            pemis : 1,
            bemis : 1,
            oemis : 1,
            fill0 : 21;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartmis_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_UARTICR_RO                        0x00000044
#define AG_MG_REGS_UARTICR_RM                        0x000007FF

#define AG_MG_REGS_UARTICR_RIMIC_BO                  0
#define AG_MG_REGS_UARTICR_RIMIC_BM                  0x00000001

#define AG_MG_REGS_UARTICR_CTSMIC_BO                 1
#define AG_MG_REGS_UARTICR_CTSMIC_BM                 0x00000002

#define AG_MG_REGS_UARTICR_DCDMIC_BO                 2
#define AG_MG_REGS_UARTICR_DCDMIC_BM                 0x00000004

#define AG_MG_REGS_UARTICR_DSRMIC_BO                 3
#define AG_MG_REGS_UARTICR_DSRMIC_BM                 0x00000008

#define AG_MG_REGS_UARTICR_RXIC_BO                   4
#define AG_MG_REGS_UARTICR_RXIC_BM                   0x00000010

#define AG_MG_REGS_UARTICR_TXIC_BO                   5
#define AG_MG_REGS_UARTICR_TXIC_BM                   0x00000020

#define AG_MG_REGS_UARTICR_RTIC_BO                   6
#define AG_MG_REGS_UARTICR_RTIC_BM                   0x00000040

#define AG_MG_REGS_UARTICR_FEIC_BO                   7
#define AG_MG_REGS_UARTICR_FEIC_BM                   0x00000080

#define AG_MG_REGS_UARTICR_PEIC_BO                   8
#define AG_MG_REGS_UARTICR_PEIC_BM                   0x00000100

#define AG_MG_REGS_UARTICR_BEIC_BO                   9
#define AG_MG_REGS_UARTICR_BEIC_BM                   0x00000200

#define AG_MG_REGS_UARTICR_OEIC_BO                   10
#define AG_MG_REGS_UARTICR_OEIC_BM                   0x00000400

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTICR_U
{
    struct
    {
        ag_mg_regs_register
            rimic : 1,
            ctsmic : 1,
            dcdmic : 1,
            dsrmic : 1,
            rxic : 1,
            txic : 1,
            rtic : 1,
            feic : 1,
            peic : 1,
            beic : 1,
            oeic : 1,
            fill0 : 21;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uarticr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_UARTDMACR_RO                      0x00000048
#define AG_MG_REGS_UARTDMACR_RM                      0x00000007

#define AG_MG_REGS_UARTDMACR_RXDMAE_BO               0
#define AG_MG_REGS_UARTDMACR_RXDMAE_BM               0x00000001

#define AG_MG_REGS_UARTDMACR_TXDMAE_BO               1
#define AG_MG_REGS_UARTDMACR_TXDMAE_BM               0x00000002

#define AG_MG_REGS_UARTDMACR_DMAONERR_BO             2
#define AG_MG_REGS_UARTDMACR_DMAONERR_BM             0x00000004

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTDMACR_U
{
    struct
    {
        ag_mg_regs_register
            rxdmae : 1,
            txdmae : 1,
            dmaonerr : 1,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartdmacr_u;
#endif


/*
 * UARTPERIPHID0 (Peripheral identification register)
 * Initialization value: 0x00000011  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTPERIPHID0_RO                  0x00000FE0
#define AG_MG_REGS_UARTPERIPHID0_RM                  0x000000FF

#define AG_MG_REGS_UARTPERIPHID0_PARTNUMBER0_BO      0
#define AG_MG_REGS_UARTPERIPHID0_PARTNUMBER0_BM      0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTPERIPHID0_U
{
    struct
    {
        ag_mg_regs_register
            partnumber0 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartperiphid0_u;
#endif


/*
 * UARTPERIPHID1 (Peripheral identification register)
 * Initialization value: 0x00000010  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTPERIPHID1_RO                  0x00000FE4
#define AG_MG_REGS_UARTPERIPHID1_RM                  0x000000FF

#define AG_MG_REGS_UARTPERIPHID1_PARTNUMBER1_BO      0
#define AG_MG_REGS_UARTPERIPHID1_PARTNUMBER1_BM      0x0000000F

#define AG_MG_REGS_UARTPERIPHID1_DESIGNER0_BO        4
#define AG_MG_REGS_UARTPERIPHID1_DESIGNER0_BM        0x000000F0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTPERIPHID1_U
{
    struct
    {
        ag_mg_regs_register
            partnumber1 : 4,
            designer0 : 4,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartperiphid1_u;
#endif


/*
 * UARTPERIPHID2 (Peripheral identification register)
 * Initialization value: 0x00000034  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTPERIPHID2_RO                  0x00000FE8
#define AG_MG_REGS_UARTPERIPHID2_RM                  0x000000FF

#define AG_MG_REGS_UARTPERIPHID2_DESIGNER1_BO        0
#define AG_MG_REGS_UARTPERIPHID2_DESIGNER1_BM        0x0000000F

#define AG_MG_REGS_UARTPERIPHID2_REVISION_BO         4
#define AG_MG_REGS_UARTPERIPHID2_REVISION_BM         0x000000F0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTPERIPHID2_U
{
    struct
    {
        ag_mg_regs_register
            designer1 : 4,
            revision : 4,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartperiphid2_u;
#endif


/*
 * UARTPERIPHID3 (Peripheral identification register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTPERIPHID3_RO                  0x00000FEC
#define AG_MG_REGS_UARTPERIPHID3_RM                  0x000000FF

#define AG_MG_REGS_UARTPERIPHID3_CONFIGURATION_BO    0
#define AG_MG_REGS_UARTPERIPHID3_CONFIGURATION_BM    0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTPERIPHID3_U
{
    struct
    {
        ag_mg_regs_register
            configuration : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartperiphid3_u;
#endif


/*
 * UARTPCELLID0 (PrimeCell identification register)
 * Initialization value: 0x0000000D  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTPCELLID0_RO                   0x00000FF0
#define AG_MG_REGS_UARTPCELLID0_RM                   0x000000FF

#define AG_MG_REGS_UARTPCELLID0_PCELLID0_BO          0
#define AG_MG_REGS_UARTPCELLID0_PCELLID0_BM          0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTPCELLID0_U
{
    struct
    {
        ag_mg_regs_register
            pcellid0 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartpcellid0_u;
#endif


/*
 * UARTPCELLID1 (PrimeCell identification register)
 * Initialization value: 0x000000F0  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTPCELLID1_RO                   0x00000FF4
#define AG_MG_REGS_UARTPCELLID1_RM                   0x000000FF

#define AG_MG_REGS_UARTPCELLID1_PCELLID1_BO          0
#define AG_MG_REGS_UARTPCELLID1_PCELLID1_BM          0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTPCELLID1_U
{
    struct
    {
        ag_mg_regs_register
            pcellid1 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartpcellid1_u;
#endif


/*
 * UARTPCELLID2 (PrimeCell identification register)
 * Initialization value: 0x00000005  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTPCELLID2_RO                   0x00000FF8
#define AG_MG_REGS_UARTPCELLID2_RM                   0x000000FF

#define AG_MG_REGS_UARTPCELLID2_PCELLID2_BO          0
#define AG_MG_REGS_UARTPCELLID2_PCELLID2_BM          0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_UARTPCELLID2_U
{
    struct
    {
        ag_mg_regs_register
            pcellid2 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_uartpcellid2_u;
#endif


/*
 * UARTPCELLID3 (PrimeCell identification register)
 * Initialization value: 0x000000B1  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_UARTPCELLID3_RO                   0x00000FFC
#define AG_MG_REGS_UARTPCELLID3_RM                   0x000000FF

#define AG_MG_REGS_UARTPCELLID3_PCELLID3_BO          0
#define AG_MG_REGS_UARTPCELLID3_PCELLID3_BM          0x000000FF
/*
 * Physical register addresses for accessing UART
 */
#ifdef AG_MG_REGS_BUILT_FOR_DSS
#define AG_MG_REGS_UART_BASE		0xC3047000
#else
#define AG_MG_REGS_UART_BASE		0x30047000
#endif
#define AG_MG_REGS_UART_REG(ro)		(AG_MG_REGS_UART_BASE+(ro))

#define AG_MG_REGS_UARTDR_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTDR_RO)
#define AG_MG_REGS_UARTRSR_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTRSR_RO)
#define AG_MG_REGS_UARTFR_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTFR_RO)
#define AG_MG_REGS_UARTILPR_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTILPR_RO)
#define AG_MG_REGS_UARTIBRD_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTIBRD_RO)
#define AG_MG_REGS_UARTFBRD_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTFBRD_RO)
#define AG_MG_REGS_UARTLCR_H_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTLCR_H_RO)
#define AG_MG_REGS_UARTCR_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTCR_RO)
#define AG_MG_REGS_UARTIFLS_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTIFLS_RO)
#define AG_MG_REGS_UARTIMSC_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTIMSC_RO)
#define AG_MG_REGS_UARTRIS_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTRIS_RO)
#define AG_MG_REGS_UARTMIS_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTMIS_RO)
#define AG_MG_REGS_UARTICR_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTICR_RO)
#define AG_MG_REGS_UARTDMACR_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTDMACR_RO)
#define AG_MG_REGS_UARTPERIPHID0_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTPERIPHID0_RO)
#define AG_MG_REGS_UARTPERIPHID1_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTPERIPHID1_RO)
#define AG_MG_REGS_UARTPERIPHID2_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTPERIPHID2_RO)
#define AG_MG_REGS_UARTPERIPHID3_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTPERIPHID3_RO)
#define AG_MG_REGS_UARTPCELLID0_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTPCELLID0_RO)
#define AG_MG_REGS_UARTPCELLID1_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTPCELLID1_RO)
#define AG_MG_REGS_UARTPCELLID2_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTPCELLID2_RO)
#define AG_MG_REGS_UARTPCELLID3_RA	AG_MG_REGS_UART_REG(AG_MG_REGS_UARTPCELLID3_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_UART_REGS_S
{
	ag_mg_regs_uartdr_u	uartdr ;
	ag_mg_regs_uartrsr_u	uartrsr ;
	ag_mg_regs_uartfr_u	uartfr ;
	ag_mg_regs_uartilpr_u	uartilpr ;
	ag_mg_regs_uartibrd_u	uartibrd ;
	ag_mg_regs_uartfbrd_u	uartfbrd ;
	ag_mg_regs_uartlcr_h_u	uartlcr_h ;
	ag_mg_regs_uartcr_u	uartcr ;
	ag_mg_regs_uartifls_u	uartifls ;
	ag_mg_regs_uartimsc_u	uartimsc ;
	ag_mg_regs_uartris_u	uartris ;
	ag_mg_regs_uartmis_u	uartmis ;
	ag_mg_regs_uarticr_u	uarticr ;
	ag_mg_regs_uartdmacr_u	uartdmacr ;
	ag_mg_regs_uartperiphid0_u	uartperiphid0 ;
	ag_mg_regs_uartperiphid1_u	uartperiphid1 ;
	ag_mg_regs_uartperiphid2_u	uartperiphid2 ;
	ag_mg_regs_uartperiphid3_u	uartperiphid3 ;
	ag_mg_regs_uartpcellid0_u	uartpcellid0 ;
	ag_mg_regs_uartpcellid1_u	uartpcellid1 ;
	ag_mg_regs_uartpcellid2_u	uartpcellid2 ;
} ag_mg_regs_uart_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_uart_reg_s *uart_regs =
*       (volatile ag_mg_regs_uart_reg_s *)AG_MG_REGS_UART_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_uart.h,v $
Revision 1.1  2012/04/18 18:08:27  srane
Initial checkin


$Endlog$
*/

