/* $Id: ag_mg_regs_mac.h,v 1.1 2012/04/18 18:08:26 srane Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/sp27dsp/dss/inc/ag_mg_regs_mac.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_mac.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_mac.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of LSI Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * The Packet Processor Block (PPB) contains two each of these blocks:
 * Packet Classification Engine (PCE), Transmit Direct Memory Access (TXD),
 * and Gigabit Ethernet Media Access Control (MAC). One PCE is attached to
 * the receive side of a MAC and one TXD is connected to the transmit side
 * of a MAC. The MAC transmits/receives packet traffic via SGMII. The PCE
 * receives the packets from the MAC, sorts them and sends them to the
 * appropriate destination via a programmable DMA engine. The TXD grabs data
 * from the source and loads it into the MAC which transmits the data off chip.
 *
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *  MAC_ENPAUSE
 *  MAC_SA1
 *  MAC_SA2
 *  MAC_TIMING
 *  MAC_CONTROL
 *  MAC_STATUS
 *  MAC_PRBSTATUS
 *  MAC_SGMII
 *  MAC_PRBSCTL
 *  MAC_ANCTRL
 *  MAC_ANSTAT
 *  MAC_ERRSTAT
 *  MAC_PFILTER
 *  MAC_MULTI1
 *  MAC_MULTI2
 *  MAC_MULTI3
 *  MAC_MULTI4
 *  MAC_UNI1
 *  MAC_UNI2
 *  MAC_UNI3
 *  MAC_UNI4
 *  MAC_UNI5
 *  MAC_SMIICTRL
 *  MAC_SMIISTATUS
 *  MAC_INTMASKC37
 *  MAC_CNT0
 *  MAC_CNT1
 *  MAC_CNT2
 *  MAC_CNT3
 *  MAC_CNT4
 *  MAC_CNT5
 *  MAC_CNT6
 *  MAC_CNT7
 *  MAC_CNT8
 *  MAC_CNT9
 *  MAC_CNT10
 *  MAC_CNT11
 *  MAC_CNT12
 *  MAC_CNT13
 *  MAC_CNT14
 *  MAC_CNT15
 *  MAC_CNT16
 *  MAC_CNT17
 *  MAC_CNT18
 *  MAC_CNT19
 *  MAC_CNT20
 *  MAC_CNT21
 *  MAC_CNT22
 *  MAC_CNT23
 *  MAC_CNT24
 *  MAC_CNT25
 *  MAC_CNT26TRANSMIT
 *  MAC_CNT27
 *  MAC_CNT28
 *  MAC_CNT29
 *  MAC_CNT30
 *  MAC_CNT31
 *  MAC_CNT32
 *  MAC_CNT33
 *  MAC_CNT34
 *  MAC_CNT35
 *  MAC_CNT36
 *  MAC_CNT37
 *  MAC_CNT38
 *  MAC_CNT39
 *  MAC_CNT40
 *  MAC_CNT41
 *  MAC_CNT42
 *  MAC_CNT43
 *  MAC_OVF1
 *  MAC_OVF2
 *  MAC_MASK1
 *  MAC_MASK2
 *  MAC_BINCTL
 *
 * Prefix naming conventions :
 *   AG_MG_REGS_XXX_RA : register/memory physical address
 *   AG_MG_REGS_XXX_RO : register/memory address offset
 *   AG_MG_REGS_XXX_RM : register mask
 *   AG_MG_REGS_XXX_BO : bit/field offset from LSB
 *   AG_MG_REGS_XXX_BM : bit/field mask
 *   AG_MG_REGS_XXX_U  : bitfields in C union typedef
 *   AG_MG_REGS_XXX_S  : registers in C struct typedef
 *   AG_MG_REGS_XX_RPT : number of identical registers in array
 *   AG_MG_REGS_XX_IVL : interval between registers in array
 *
 * NOTE: user may redefine ag_mg_regs_register
 *       in ag_mg_regs_regops.h if necessary
 * NOTE: access mode of individual bit fields matches that
 *       of containing register unless indicated otherwise
 */

#ifndef AG_MG_REGS_MAC_REGISTERS_H
#define AG_MG_REGS_MAC_REGISTERS_H

#include "ag_mg_regs_regops.h"
/*
 * Generated by HSI Designer release 2.3.5.
 */

/*
 * MAC_ENPAUSE (MAC Enable and Pause Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_ENPAUSE_RO                                0x00000000
#define AG_MG_REGS_MAC_ENPAUSE_RM                                0xFFFF007F

#define AG_MG_REGS_MAC_ENPAUSE_GMAC_TX_PAUSE_EN_BO               0
#define AG_MG_REGS_MAC_ENPAUSE_GMAC_TX_PAUSE_EN_BM               0x00000001

#define AG_MG_REGS_MAC_ENPAUSE_GMAC_RX_PAUSE_EN_BO               1
#define AG_MG_REGS_MAC_ENPAUSE_GMAC_RX_PAUSE_EN_BM               0x00000002

#define AG_MG_REGS_MAC_ENPAUSE_PORT_ENABLE_BO                    2
#define AG_MG_REGS_MAC_ENPAUSE_PORT_ENABLE_BM                    0x00000004

#define AG_MG_REGS_MAC_ENPAUSE_GMAC_RX_EN_BO                     3
#define AG_MG_REGS_MAC_ENPAUSE_GMAC_RX_EN_BM                     0x00000008

#define AG_MG_REGS_MAC_ENPAUSE_GMII_BYPASS_MODE_BO               4
#define AG_MG_REGS_MAC_ENPAUSE_GMII_BYPASS_MODE_BM               0x00000010

#define AG_MG_REGS_MAC_ENPAUSE_GMAC_TX_INIT_PAUSE_BO             5
#define AG_MG_REGS_MAC_ENPAUSE_GMAC_TX_INIT_PAUSE_BM             0x00000020

#define AG_MG_REGS_MAC_ENPAUSE_GPIO_CLK_MUX_SELECT_BO            6
#define AG_MG_REGS_MAC_ENPAUSE_GPIO_CLK_MUX_SELECT_BM            0x00000040

#define AG_MG_REGS_MAC_ENPAUSE_MAC_PAUSE_QUANTA_BO               16
#define AG_MG_REGS_MAC_ENPAUSE_MAC_PAUSE_QUANTA_BM               0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_ENPAUSE_U
{
    struct
    {
        ag_mg_regs_register
            gmac_tx_pause_en : 1,
            gmac_rx_pause_en : 1,
            port_enable : 1,
            gmax_rx_en : 1,
            gmii_bypass_mode : 1,
            gmac_tx_init_pause : 1,
            gpio_clk_mux_select : 1,
            fill0 : 9,
            pause_quanta : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_enpause_u;
#endif


/*
 * MAC_SA1 (MAC Source Address Register (Low Word))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_SA1_RO                                    0x00000004
#define AG_MG_REGS_MAC_SA1_RM                                    0xFFFFFFFF

#define AG_MG_REGS_MAC_SA1_SA_REG1_BO                            0
#define AG_MG_REGS_MAC_SA1_SA_REG1_BM                            0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_SA1_U
{
    struct
    {
        ag_mg_regs_register
            sa_reg1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_sa1_u;
#endif


/*
 * MAC_SA2 (MAC Source Address Register (Low Word))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_SA2_RO                                    0x00000008
#define AG_MG_REGS_MAC_SA2_RM                                    0x0000FFFF

#define AG_MG_REGS_MAC_SA2_SA_REG2_BO                            0
#define AG_MG_REGS_MAC_SA2_SA_REG2_BM                            0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_SA2_U
{
    struct
    {
        ag_mg_regs_register
            sa_reg2 : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_sa2_u;
#endif


/*
 * MAC_TIMING (MAC Timing Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_TIMING_RO                                 0x0000000C
#define AG_MG_REGS_MAC_TIMING_RM                                 0x0000003F

#define AG_MG_REGS_MAC_TIMING_SIFG_BO                            0
#define AG_MG_REGS_MAC_TIMING_SIFG_BM                            0x00000001

#define AG_MG_REGS_MAC_TIMING_FIXED_BO                           1
#define AG_MG_REGS_MAC_TIMING_FIXED_BM                           0x00000002

#define AG_MG_REGS_MAC_TIMING_FSTMR_BO                           2
#define AG_MG_REGS_MAC_TIMING_FSTMR_BM                           0x00000004

#define AG_MG_REGS_MAC_TIMING_ZEROB_BO                           3
#define AG_MG_REGS_MAC_TIMING_ZEROB_BM                           0x00000008

#define AG_MG_REGS_MAC_TIMING_INFRTY_BO                          4
#define AG_MG_REGS_MAC_TIMING_INFRTY_BM                          0x00000010

#define AG_MG_REGS_MAC_TIMING_SELEXTPAUSE_BO                     5
#define AG_MG_REGS_MAC_TIMING_SELEXTPAUSE_BM                     0x00000020

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_TIMING_U
{
    struct
    {
        ag_mg_regs_register
            sifg : 1,
            fixed : 1,
            fstmr : 1,
            zerob : 1,
            infrty : 1,
            selextpause : 1,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_timing_u;
#endif


/*
 * MAC_CONTROL (MAC Host Side Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_CONTROL_RO                                0x00000010
#define AG_MG_REGS_MAC_CONTROL_RM                                0x0000007F

#define AG_MG_REGS_MAC_CONTROL_DEBUGS_BO                         0
#define AG_MG_REGS_MAC_CONTROL_DEBUGS_BM                         0x00000001

#define AG_MG_REGS_MAC_CONTROL_AFLUSH_BO                         1
#define AG_MG_REGS_MAC_CONTROL_AFLUSH_BM                         0x00000002

#define AG_MG_REGS_MAC_CONTROL_TXFLUSH_BO                        2
#define AG_MG_REGS_MAC_CONTROL_TXFLUSH_BM                        0x00000004

#define AG_MG_REGS_MAC_CONTROL_DISRXPAD_BO                       3
#define AG_MG_REGS_MAC_CONTROL_DISRXPAD_BM                       0x00000008

#define AG_MG_REGS_MAC_CONTROL_RXABDIS_BO                        4
#define AG_MG_REGS_MAC_CONTROL_RXABDIS_BM                        0x00000010

#define AG_MG_REGS_MAC_CONTROL_RXCRCSTRIP_BO                     5
#define AG_MG_REGS_MAC_CONTROL_RXCRCSTRIP_BM                     0x00000020

#define AG_MG_REGS_MAC_CONTROL_TXPAD_BO                          6
#define AG_MG_REGS_MAC_CONTROL_TXPAD_BM                          0x00000040

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CONTROL_U
{
    struct
    {
        ag_mg_regs_register
            debugs : 1,
            aflush : 1,
            txflush : 1,
            disrxpad : 1,
            rxabdis : 1,
            rxcrcstrip : 1,
            txpad : 1,
            fill0 : 25;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_control_u;
#endif


/*
 * MAC_STATUS (MAC Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MAC_STATUS_RO                                 0x00000014
#define AG_MG_REGS_MAC_STATUS_RM                                 0x00003FFF

#define AG_MG_REGS_MAC_STATUS_TXEDONE_BO                         0
#define AG_MG_REGS_MAC_STATUS_TXEDONE_BM                         0x00000001

#define AG_MG_REGS_MAC_STATUS_TXUND_BO                           1
#define AG_MG_REGS_MAC_STATUS_TXUND_BM                           0x00000002

#define AG_MG_REGS_MAC_STATUS_RXOVR_BO                           2
#define AG_MG_REGS_MAC_STATUS_RXOVR_BM                           0x00000004

#define AG_MG_REGS_MAC_STATUS_PAUSE_BO                           3
#define AG_MG_REGS_MAC_STATUS_PAUSE_BM                           0x00000008

#define AG_MG_REGS_MAC_STATUS_MACDEBUG_BO                        4
#define AG_MG_REGS_MAC_STATUS_MACDEBUG_BM                        0x00003FF0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_STATUS_U
{
    struct
    {
        ag_mg_regs_register
            txedone : 1,
            txund : 1,
            rxovr : 1,
            pause : 1,
            macdebug : 10,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_status_u;
#endif


/*
 * MAC_PRBSTATUS (MAC PRBS Error Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MAC_PRBSTATUS_RO                              0x00000018
#define AG_MG_REGS_MAC_PRBSTATUS_RM                              0x000000FF

#define AG_MG_REGS_MAC_PRBSTATUS_PRBSECNT_BO                     0
#define AG_MG_REGS_MAC_PRBSTATUS_PRBSECNT_BM                     0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_PRBSTATUS_U
{
    struct
    {
        ag_mg_regs_register
            prbsecnt : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_prbstatus_u;
#endif


/*
 * MAC_SGMII (MAC SGMII Enable and Reset Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_SGMII_RO                                  0x0000001C
#define AG_MG_REGS_MAC_SGMII_RM                                  0x00000007

#define AG_MG_REGS_MAC_SGMII_SGMIIEN_BO                          0
#define AG_MG_REGS_MAC_SGMII_SGMIIEN_BM                          0x00000001

#define AG_MG_REGS_MAC_SGMII_C37INTDISABLE_BO                    1
#define AG_MG_REGS_MAC_SGMII_C37INTDISABLE_BM                    0x00000002

#define AG_MG_REGS_MAC_SGMII_C73INTDISABLE_BO                    2
#define AG_MG_REGS_MAC_SGMII_C73INTDISABLE_BM                    0x00000004

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_SGMII_U
{
    struct
    {
        ag_mg_regs_register
            sgmiien : 1,
            c37intdisable : 1,
            c73intdisable : 1,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_sgmii_u;
#endif


/*
 * MAC_PRBSCTL (MAC PRBS Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_PRBSCTL_RO                                0x00000020
#define AG_MG_REGS_MAC_PRBSCTL_RM                                0x07FFFFFF

#define AG_MG_REGS_MAC_PRBSCTL_PRBSEN_BO                         0
#define AG_MG_REGS_MAC_PRBSCTL_PRBSEN_BM                         0x00000001

#define AG_MG_REGS_MAC_PRBSCTL_PRBSDATA_BO                       1
#define AG_MG_REGS_MAC_PRBSCTL_PRBSDATA_BM                       0x000007FE

#define AG_MG_REGS_MAC_PRBSCTL_PRBSSEED_BO                       11
#define AG_MG_REGS_MAC_PRBSCTL_PRBSSEED_BM                       0x001FF800

#define AG_MG_REGS_MAC_PRBSCTL_LOADS_BO                          21
#define AG_MG_REGS_MAC_PRBSCTL_LOADS_BM                          0x00200000

#define AG_MG_REGS_MAC_PRBSCTL_INVC_BO                           22
#define AG_MG_REGS_MAC_PRBSCTL_INVC_BM                           0x00400000

#define AG_MG_REGS_MAC_PRBSCTL_CNTRST_BO                         23
#define AG_MG_REGS_MAC_PRBSCTL_CNTRST_BM                         0x00800000

#define AG_MG_REGS_MAC_PRBSCTL_LOOPBACK_BO                       24
#define AG_MG_REGS_MAC_PRBSCTL_LOOPBACK_BM                       0x01000000

#define AG_MG_REGS_MAC_PRBSCTL_PATAA_BO                          25
#define AG_MG_REGS_MAC_PRBSCTL_PATAA_BM                          0x02000000

#define AG_MG_REGS_MAC_PRBSCTL_PAT55_BO                          26
#define AG_MG_REGS_MAC_PRBSCTL_PAT55_BM                          0x04000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_PRBSCTL_U
{
    struct
    {
        ag_mg_regs_register
            prbsen : 1,
            prbsdata : 10,
            prbsseed : 10,
            loads : 1,
            invc : 1,
            cntrst : 1,
            loopback : 1,
            pataa : 1,
            pat55 : 1,
            fill0 : 5;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_prbsctl_u;
#endif


/*
 * MAC_ANCTRL (MAC Autonegotiation Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_ANCTRL_RO                                 0x00000024
#define AG_MG_REGS_MAC_ANCTRL_RM                                 0x000007FF

#define AG_MG_REGS_MAC_ANCTRL_RESTART_BO                         0
#define AG_MG_REGS_MAC_ANCTRL_RESTART_BM                         0x00000001

#define AG_MG_REGS_MAC_ANCTRL_ENABLE_BO                          1
#define AG_MG_REGS_MAC_ANCTRL_ENABLE_BM                          0x00000002

#define AG_MG_REGS_MAC_ANCTRL_FDUPLEX_BO                         2
#define AG_MG_REGS_MAC_ANCTRL_FDUPLEX_BM                         0x00000004

#define AG_MG_REGS_MAC_ANCTRL_GOODF_BO                           3
#define AG_MG_REGS_MAC_ANCTRL_GOODF_BM                           0x00000008

#define AG_MG_REGS_MAC_ANCTRL_SPMODE_BO                          4
#define AG_MG_REGS_MAC_ANCTRL_SPMODE_BM                          0x00000030

#define AG_MG_REGS_MAC_ANCTRL_ANSPEED_BO                         6
#define AG_MG_REGS_MAC_ANCTRL_ANSPEED_BM                         0x00000040

#define AG_MG_REGS_MAC_ANCTRL_ANOFF_BO                           7
#define AG_MG_REGS_MAC_ANCTRL_ANOFF_BM                           0x00000080

#define AG_MG_REGS_MAC_ANCTRL_FCONINITEN_BO                      8
#define AG_MG_REGS_MAC_ANCTRL_FCONINITEN_BM                      0x00000100

#define AG_MG_REGS_MAC_ANCTRL_RXPAUSEN_BO                        9
#define AG_MG_REGS_MAC_ANCTRL_RXPAUSEN_BM                        0x00000200

#define AG_MG_REGS_MAC_ANCTRL_FIBER_BO                           10
#define AG_MG_REGS_MAC_ANCTRL_FIBER_BM                           0x00000400

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_ANCTRL_U
{
    struct
    {
        ag_mg_regs_register
            restart : 1,
            enable : 1,
            fduplex : 1,
            goodf : 1,
            spmode : 2,
            anspeed : 1,
            anoff : 1,
            fconiniten : 1,
            rxpausen : 1,
            fiber : 1,
            fill0 : 21;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_anctrl_u;
#endif


/*
 * MAC_ANSTAT (MAC Autonegotiation Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MAC_ANSTAT_RO                                 0x00000028
#define AG_MG_REGS_MAC_ANSTAT_RM                                 0x00001FFF

#define AG_MG_REGS_MAC_ANSTAT_MR_AN_COMPLETE_BO                  0
#define AG_MG_REGS_MAC_ANSTAT_MR_AN_COMPLETE_BM                  0x00000001

#define AG_MG_REGS_MAC_ANSTAT_REMOTE_HD_FD_BO                    1
#define AG_MG_REGS_MAC_ANSTAT_REMOTE_HD_FD_BM                    0x00000006

#define AG_MG_REGS_MAC_ANSTAT_REMOTE_PAUSE_BO                    3
#define AG_MG_REGS_MAC_ANSTAT_REMOTE_PAUSE_BM                    0x00000018

#define AG_MG_REGS_MAC_ANSTAT_REMOTE_FAULT_BO                    5
#define AG_MG_REGS_MAC_ANSTAT_REMOTE_FAULT_BM                    0x00000060

#define AG_MG_REGS_MAC_ANSTAT_AUTONEG_RX_PAUSE_EN_BO             7
#define AG_MG_REGS_MAC_ANSTAT_AUTONEG_RX_PAUSE_EN_BM             0x00000080

#define AG_MG_REGS_MAC_ANSTAT_AUTONEG_TX_PAUSE_EN_BO             8
#define AG_MG_REGS_MAC_ANSTAT_AUTONEG_TX_PAUSE_EN_BM             0x00000100

#define AG_MG_REGS_MAC_ANSTAT_GMII_LINK_OK_BO                    9
#define AG_MG_REGS_MAC_ANSTAT_GMII_LINK_OK_BM                    0x00000200

#define AG_MG_REGS_MAC_ANSTAT_GMII_FULL_DUPLEX_BO                10
#define AG_MG_REGS_MAC_ANSTAT_GMII_FULL_DUPLEX_BM                0x00000400

#define AG_MG_REGS_MAC_ANSTAT_GMII_SPEED_MODE_BO                 11
#define AG_MG_REGS_MAC_ANSTAT_GMII_SPEED_MODE_BM                 0x00001800

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_ANSTAT_U
{
    struct
    {
        ag_mg_regs_register
            mr_an_complete : 1,
            remote_hd_fd : 2,
            remote_pause : 2,
            remote_fault : 2,
            autoneg_rx_pause_en : 1,
            autoneg_tx_pause_en : 1,
            gmii_link_ok : 1,
            gmii_full_duplex : 1,
            gmii_speed_mode : 2,
            fill0 : 19;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_anstat_u;
#endif


/*
 * MAC_ERRSTAT (MAC Error Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MAC_ERRSTAT_RO                                0x0000002C
#define AG_MG_REGS_MAC_ERRSTAT_RM                                0x000003FF

#define AG_MG_REGS_MAC_ERRSTAT_SGDEBUG_BO                        0
#define AG_MG_REGS_MAC_ERRSTAT_SGDEBUG_BM                        0x000003FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_ERRSTAT_U
{
    struct
    {
        ag_mg_regs_register
            sgdebug : 10,
            fill0 : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_errstat_u;
#endif


/*
 * MAC_PFILTER (MAC Packet Filter Engine Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_PFILTER_RO                                0x00000030
#define AG_MG_REGS_MAC_PFILTER_RM                                0x0000001F

#define AG_MG_REGS_MAC_PFILTER_FILTEN_BO                         0
#define AG_MG_REGS_MAC_PFILTER_FILTEN_BM                         0x00000001

#define AG_MG_REGS_MAC_PFILTER_BRDFILT_BO                        1
#define AG_MG_REGS_MAC_PFILTER_BRDFILT_BM                        0x00000002

#define AG_MG_REGS_MAC_PFILTER_MULTIFLT_BO                       2
#define AG_MG_REGS_MAC_PFILTER_MULTIFLT_BM                       0x00000004

#define AG_MG_REGS_MAC_PFILTER_UNIFILT_BO                        3
#define AG_MG_REGS_MAC_PFILTER_UNIFILT_BM                        0x00000008

#define AG_MG_REGS_MAC_PFILTER_PAUSEFLT_BO                       4
#define AG_MG_REGS_MAC_PFILTER_PAUSEFLT_BM                       0x00000010

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_PFILTER_U
{
    struct
    {
        ag_mg_regs_register
            filten : 1,
            brdfilt : 1,
            multiflt : 1,
            unifilt : 1,
            pauseflt : 1,
            fill0 : 27;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_pfilter_u;
#endif


/*
 * MAC_MULTI1 (MAC Multicast Has Register 1)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_MULTI1_RO                                 0x00000034
#define AG_MG_REGS_MAC_MULTI1_RM                                 0xFFFFFFFF

#define AG_MG_REGS_MAC_MULTI1_HASH1_BO                           0
#define AG_MG_REGS_MAC_MULTI1_HASH1_BM                           0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_MULTI1_U
{
    struct
    {
        ag_mg_regs_register
            hash1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_multi1_u;
#endif


/*
 * MAC_MULTI2 (MAC Multicast Has Register 2)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_MULTI2_RO                                 0x00000038
#define AG_MG_REGS_MAC_MULTI2_RM                                 0xFFFFFFFF

#define AG_MG_REGS_MAC_MULTI2_HASH2_BO                           0
#define AG_MG_REGS_MAC_MULTI2_HASH2_BM                           0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_MULTI2_U
{
    struct
    {
        ag_mg_regs_register
            hash2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_multi2_u;
#endif


/*
 * MAC_MULTI3 (MAC Multicast Has Register 3)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_MULTI3_RO                                 0x0000003C
#define AG_MG_REGS_MAC_MULTI3_RM                                 0xFFFFFFFF

#define AG_MG_REGS_MAC_MULTI3_HASH3_BO                           0
#define AG_MG_REGS_MAC_MULTI3_HASH3_BM                           0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_MULTI3_U
{
    struct
    {
        ag_mg_regs_register
            hash3;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_multi3_u;
#endif


/*
 * MAC_MULTI4 (MAC Multicast Has Register 4)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_MULTI4_RO                                 0x00000040
#define AG_MG_REGS_MAC_MULTI4_RM                                 0xFFFFFFFF

#define AG_MG_REGS_MAC_MULTI4_HASH4_BO                           0
#define AG_MG_REGS_MAC_MULTI4_HASH4_BM                           0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_MULTI4_U
{
    struct
    {
        ag_mg_regs_register
            hash4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_multi4_u;
#endif


/*
 * MAC_UNI1 (MAC Unicast Address Register 1)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_UNI1_RO                                   0x00000044
#define AG_MG_REGS_MAC_UNI1_RM                                   0xFFFFFFFF

#define AG_MG_REGS_MAC_UNI1_UNI1L_BO                             0
#define AG_MG_REGS_MAC_UNI1_UNI1L_BM                             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_UNI1_U
{
    struct
    {
        ag_mg_regs_register
            uni1l;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_uni1_u;
#endif


/*
 * MAC_UNI2 (MAC Unicast Address Register 2)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_UNI2_RO                                   0x00000048
#define AG_MG_REGS_MAC_UNI2_RM                                   0xFFFFFFFF

#define AG_MG_REGS_MAC_UNI2_UNI2L_BO                             0
#define AG_MG_REGS_MAC_UNI2_UNI2L_BM                             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_UNI2_U
{
    struct
    {
        ag_mg_regs_register
            uni2l;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_uni2_u;
#endif


/*
 * MAC_UNI3 (MAC Unicast Address Register 3)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_UNI3_RO                                   0x0000004C
#define AG_MG_REGS_MAC_UNI3_RM                                   0xFFFFFFFF

#define AG_MG_REGS_MAC_UNI3_UNI1H_BO                             0
#define AG_MG_REGS_MAC_UNI3_UNI1H_BM                             0x0000FFFF

#define AG_MG_REGS_MAC_UNI3_UNI2H_BO                             16
#define AG_MG_REGS_MAC_UNI3_UNI2H_BM                             0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_UNI3_U
{
    struct
    {
        ag_mg_regs_register
            uni1h : 16,
            uni2h : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_uni3_u;
#endif


/*
 * MAC_UNI4 (MAC Unicast Address Register 4)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_UNI4_RO                                   0x00000050
#define AG_MG_REGS_MAC_UNI4_RM                                   0xFFFFFFFF

#define AG_MG_REGS_MAC_UNI4_UNI3L_BO                             0
#define AG_MG_REGS_MAC_UNI4_UNI3L_BM                             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_UNI4_U
{
    struct
    {
        ag_mg_regs_register
            uni3l;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_uni4_u;
#endif


/*
 * MAC_UNI5 (MAC Unicast Address Register 5)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_UNI5_RO                                   0x00000054
#define AG_MG_REGS_MAC_UNI5_RM                                   0x0000FFFF

#define AG_MG_REGS_MAC_UNI5_UNI3H_BO                             0
#define AG_MG_REGS_MAC_UNI5_UNI3H_BM                             0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_UNI5_U
{
    struct
    {
        ag_mg_regs_register
            uni3h : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_uni5_u;
#endif


/*
 * MAC_SMIICTRL (MAC SMII Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_SMIICTRL_RO                               0x00000058
#define AG_MG_REGS_MAC_SMIICTRL_RM                               0x000001FF

#define AG_MG_REGS_MAC_SMIICTRL_SMIIEN_BO                        0
#define AG_MG_REGS_MAC_SMIICTRL_SMIIEN_BM                        0x00000001

#define AG_MG_REGS_MAC_SMIICTRL_SMIISYNC_BO                      1
#define AG_MG_REGS_MAC_SMIICTRL_SMIISYNC_BM                      0x00000002

#define AG_MG_REGS_MAC_SMIICTRL_SMIIPHY_BO                       2
#define AG_MG_REGS_MAC_SMIICTRL_SMIIPHY_BM                       0x00000004

#define AG_MG_REGS_MAC_SMIICTRL_SMIIFERR_BO                      3
#define AG_MG_REGS_MAC_SMIICTRL_SMIIFERR_BM                      0x00000008

#define AG_MG_REGS_MAC_SMIICTRL_SMIITXD47_BO                     4
#define AG_MG_REGS_MAC_SMIICTRL_SMIITXD47_BM                     0x000000F0

#define AG_MG_REGS_MAC_SMIICTRL_SMIIMASK_BO                      8
#define AG_MG_REGS_MAC_SMIICTRL_SMIIMASK_BM                      0x00000100

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_SMIICTRL_U
{
    struct
    {
        ag_mg_regs_register
            smiien : 1,
            smiisync : 1,
            smiiphy : 1,
            smiiferr : 1,
            smiitxd47 : 4,
            smiimask : 1,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_smiictrl_u;
#endif


/*
 * MAC_SMIISTATUS (MAC SMII Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MAC_SMIISTATUS_RO                             0x0000005C
#define AG_MG_REGS_MAC_SMIISTATUS_RM                             0x000001FF

#define AG_MG_REGS_MAC_SMIISTATUS_SMIIR47_BO                     0
#define AG_MG_REGS_MAC_SMIISTATUS_SMIIR47_BM                     0x0000000F

#define AG_MG_REGS_MAC_SMIISTATUS_SMIILINK_BO                    4
#define AG_MG_REGS_MAC_SMIISTATUS_SMIILINK_BM                    0x00000010

#define AG_MG_REGS_MAC_SMIISTATUS_SMIIDUP_BO                     5
#define AG_MG_REGS_MAC_SMIISTATUS_SMIIDUP_BM                     0x00000020

#define AG_MG_REGS_MAC_SMIISTATUS_SMIISPEED_BO                   6
#define AG_MG_REGS_MAC_SMIISTATUS_SMIISPEED_BM                   0x000000C0

#define AG_MG_REGS_MAC_SMIISTATUS_SMIIERR_BO                     8
#define AG_MG_REGS_MAC_SMIISTATUS_SMIIERR_BM                     0x00000100

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_SMIISTATUS_U
{
    struct
    {
        ag_mg_regs_register
            smiir47 : 4,
            smiilink : 1,
            smiidup : 1,
            smiispeed : 2,
            smiierr : 1,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_smiistatus_u;
#endif


/*
 * MAC_INTMASKC37 (MAC Clause 37 Autonegotiation Interrupt Mask Register)
 * Initialization value: 0x00001FFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_INTMASKC37_RO                             0x00000060
#define AG_MG_REGS_MAC_INTMASKC37_RM                             0x00001FFF

#define AG_MG_REGS_MAC_INTMASKC37_MR_AN_COMPLETE_MASK_BO         0
#define AG_MG_REGS_MAC_INTMASKC37_MR_AN_COMPLETE_MASK_BM         0x00000001

#define AG_MG_REGS_MAC_INTMASKC37_REMOTE_HD_FD_MASK_BO           1
#define AG_MG_REGS_MAC_INTMASKC37_REMOTE_HD_FD_MASK_BM           0x00000006

#define AG_MG_REGS_MAC_INTMASKC37_REMOTE_PAUSE_MASK_BO           3
#define AG_MG_REGS_MAC_INTMASKC37_REMOTE_PAUSE_MASK_BM           0x00000018

#define AG_MG_REGS_MAC_INTMASKC37_REMOTE_FAULT_MASK_BO           5
#define AG_MG_REGS_MAC_INTMASKC37_REMOTE_FAULT_MASK_BM           0x00000060

#define AG_MG_REGS_MAC_INTMASKC37_AUTONEG_RX_PAUSE_EN_MASK_BO    7
#define AG_MG_REGS_MAC_INTMASKC37_AUTONEG_RX_PAUSE_EN_MASK_BM    0x00000080

#define AG_MG_REGS_MAC_INTMASKC37_AUTONEG_TX_PAUSE_EN_MASK_BO    8
#define AG_MG_REGS_MAC_INTMASKC37_AUTONEG_TX_PAUSE_EN_MASK_BM    0x00000100

#define AG_MG_REGS_MAC_INTMASKC37_GMII_LINK_OK_MASK_BO           9
#define AG_MG_REGS_MAC_INTMASKC37_GMII_LINK_OK_MASK_BM           0x00000200

#define AG_MG_REGS_MAC_INTMASKC37_GMII_FULL_DUPLEX_MASK_BO       10
#define AG_MG_REGS_MAC_INTMASKC37_GMII_FULL_DUPLEX_MASK_BM       0x00000400

#define AG_MG_REGS_MAC_INTMASKC37_GMII_SPEED_MODE_MASK_BO        11
#define AG_MG_REGS_MAC_INTMASKC37_GMII_SPEED_MODE_MASK_BM        0x00001800

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_INTMASKC37_U
{
    struct
    {
        ag_mg_regs_register
            mr_an_complete_mask : 1,
            remote_hd_fd_mask : 2,
            remote_pause_mask : 2,
            remote_fault_mask : 2,
            autoneg_rx_pause_en_mask : 1,
            autoneg_tx_pause_en_mask : 1,
            gmii_link_ok_mask : 1,
            gmii_full_duplex_mask : 1,
            gmii_speed_mode_mask : 2,
            fill0 : 19;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_intmaskc37_u;
#endif


/*
 * MAC_CNT0 (Transmit and Receive 64 byte Frame Counter (Width: 24 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT0_RO                                   0x00000800
#define AG_MG_REGS_MAC_CNT0_RM                                   0x00FFFFFF

#define AG_MG_REGS_MAC_CNT0_FRMCNT0_BO                           0
#define AG_MG_REGS_MAC_CNT0_FRMCNT0_BM                           0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT0_U
{
    struct
    {
        ag_mg_regs_register
            frmcnt0 : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt0_u;
#endif


/*
 * MAC_CNT1 (Transmit and Receive 65- to 127-byte Frame Counter (Width: 24 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT1_RO                                   0x00000804
#define AG_MG_REGS_MAC_CNT1_RM                                   0x00FFFFFF

#define AG_MG_REGS_MAC_CNT1_FRMCNT1_BO                           0
#define AG_MG_REGS_MAC_CNT1_FRMCNT1_BM                           0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT1_U
{
    struct
    {
        ag_mg_regs_register
            frmcnt1 : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt1_u;
#endif


/*
 * MAC_CNT2 (Transmit and Receive 128- to 255-byte Frame Counter (Width: 24)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT2_RO                                   0x00000808
#define AG_MG_REGS_MAC_CNT2_RM                                   0x00FFFFFF

#define AG_MG_REGS_MAC_CNT2_FRMCNT2_BO                           0
#define AG_MG_REGS_MAC_CNT2_FRMCNT2_BM                           0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT2_U
{
    struct
    {
        ag_mg_regs_register
            frmcnt2 : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt2_u;
#endif


/*
 * MAC_CNT3 (Transmit and Receive 256- to 511-byte Frame Counter (Width: 24)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT3_RO                                   0x0000080C
#define AG_MG_REGS_MAC_CNT3_RM                                   0x00FFFFFF

#define AG_MG_REGS_MAC_CNT3_FRMCNT3_BO                           0
#define AG_MG_REGS_MAC_CNT3_FRMCNT3_BM                           0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT3_U
{
    struct
    {
        ag_mg_regs_register
            frmcnt3 : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt3_u;
#endif


/*
 * MAC_CNT4 (Transmit and Receive 512- to 1023-byte Frame Counter (Width: 24)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT4_RO                                   0x00000810
#define AG_MG_REGS_MAC_CNT4_RM                                   0x00FFFFFF

#define AG_MG_REGS_MAC_CNT4_FRMCNT4_BO                           0
#define AG_MG_REGS_MAC_CNT4_FRMCNT4_BM                           0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT4_U
{
    struct
    {
        ag_mg_regs_register
            frmcnt4 : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt4_u;
#endif


/*
 * MAC_CNT5 (Transmit and Receive 1024- to 1518-byte Frame Counter (Width: 24)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT5_RO                                   0x00000814
#define AG_MG_REGS_MAC_CNT5_RM                                   0x00FFFFFF

#define AG_MG_REGS_MAC_CNT5_FRMCNT5_BO                           0
#define AG_MG_REGS_MAC_CNT5_FRMCNT5_BM                           0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT5_U
{
    struct
    {
        ag_mg_regs_register
            frmcnt5 : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt5_u;
#endif


/*
 * MAC_CNT6 (Transmit and Receive 1519- to 1522-byte Good VLAN Frame Count)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT6_RO                                   0x00000818
#define AG_MG_REGS_MAC_CNT6_RM                                   0x00FFFFFF

#define AG_MG_REGS_MAC_CNT6_FRMCNT6_BO                           0
#define AG_MG_REGS_MAC_CNT6_FRMCNT6_BM                           0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT6_U
{
    struct
    {
        ag_mg_regs_register
            frmcnt6 : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt6_u;
#endif


/*
 * MAC_CNT7 (Receive Byte Coutner (Width: 30 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT7_RO                                   0x0000081C
#define AG_MG_REGS_MAC_CNT7_RM                                   0x3FFFFFFF

#define AG_MG_REGS_MAC_CNT7_RXBYTECNT_BO                         0
#define AG_MG_REGS_MAC_CNT7_RXBYTECNT_BM                         0x3FFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT7_U
{
    struct
    {
        ag_mg_regs_register
            rxbytecnt : 30,
            fill0 : 2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt7_u;
#endif


/*
 * MAC_CNT8 (Receive Packet Coutner (Width: 24 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT8_RO                                   0x00000820
#define AG_MG_REGS_MAC_CNT8_RM                                   0x00FFFFFF

#define AG_MG_REGS_MAC_CNT8_RXFRMCNT_BO                          0
#define AG_MG_REGS_MAC_CNT8_RXFRMCNT_BM                          0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT8_U
{
    struct
    {
        ag_mg_regs_register
            rxfrmcnt : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt8_u;
#endif


/*
 * MAC_CNT9 (Receive FCS Error Coutner (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT9_RO                                   0x00000824
#define AG_MG_REGS_MAC_CNT9_RM                                   0x0003FFFF

#define AG_MG_REGS_MAC_CNT9_RXFCSERR_BO                          0
#define AG_MG_REGS_MAC_CNT9_RXFCSERR_BM                          0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT9_U
{
    struct
    {
        ag_mg_regs_register
            rxfcserr : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt9_u;
#endif


/*
 * MAC_CNT10 (Receive Multicast Packet Counter (Width: 24 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT10_RO                                  0x00000828
#define AG_MG_REGS_MAC_CNT10_RM                                  0x00FFFFFF

#define AG_MG_REGS_MAC_CNT10_RXMULTICNT_BO                       0
#define AG_MG_REGS_MAC_CNT10_RXMULTICNT_BM                       0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT10_U
{
    struct
    {
        ag_mg_regs_register
            rxmulticnt : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt10_u;
#endif


/*
 * MAC_CNT11 (Receive Broadcast Packet Counter (Width: 24 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT11_RO                                  0x0000082C
#define AG_MG_REGS_MAC_CNT11_RM                                  0x00FFFFFF

#define AG_MG_REGS_MAC_CNT11_RXBRDCNT_BO                         0
#define AG_MG_REGS_MAC_CNT11_RXBRDCNT_BM                         0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT11_U
{
    struct
    {
        ag_mg_regs_register
            rxbrdcnt : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt11_u;
#endif


/*
 * MAC_CNT12 (Receive Control Frame Packet Counter (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT12_RO                                  0x00000830
#define AG_MG_REGS_MAC_CNT12_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT12_RXCTRLCNT_BO                        0
#define AG_MG_REGS_MAC_CNT12_RXCTRLCNT_BM                        0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT12_U
{
    struct
    {
        ag_mg_regs_register
            rxctrlcnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt12_u;
#endif


/*
 * MAC_CNT13 (Receive PAUSE Frame Packet Counter (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT13_RO                                  0x00000834
#define AG_MG_REGS_MAC_CNT13_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT13_RXPAUSCNT_BO                        0
#define AG_MG_REGS_MAC_CNT13_RXPAUSCNT_BM                        0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT13_U
{
    struct
    {
        ag_mg_regs_register
            rxpauscnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt13_u;
#endif


/*
 * MAC_CNT14 (Receive Unknown OP Code Coutner (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT14_RO                                  0x00000838
#define AG_MG_REGS_MAC_CNT14_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT14_RXUNKCNT_BO                         0
#define AG_MG_REGS_MAC_CNT14_RXUNKCNT_BM                         0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT14_U
{
    struct
    {
        ag_mg_regs_register
            rxunkcnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt14_u;
#endif


/*
 * MAC_CNT15 (Receive Alignment Error Counter (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT15_RO                                  0x0000083C
#define AG_MG_REGS_MAC_CNT15_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT15_RXALICNT_BO                         0
#define AG_MG_REGS_MAC_CNT15_RXALICNT_BM                         0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT15_U
{
    struct
    {
        ag_mg_regs_register
            rxalicnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt15_u;
#endif


/*
 * MAC_CNT16 (Receive Frame Length Error Counter (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT16_RO                                  0x00000840
#define AG_MG_REGS_MAC_CNT16_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT16_RXLENCNT_BO                         0
#define AG_MG_REGS_MAC_CNT16_RXLENCNT_BM                         0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT16_U
{
    struct
    {
        ag_mg_regs_register
            rxlencnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt16_u;
#endif


/*
 * MAC_CNT17 (Receive Code Error Counter (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT17_RO                                  0x00000844
#define AG_MG_REGS_MAC_CNT17_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT17_RXCODCNT_BO                         0
#define AG_MG_REGS_MAC_CNT17_RXCODCNT_BM                         0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT17_U
{
    struct
    {
        ag_mg_regs_register
            rxcodcnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt17_u;
#endif


/*
 * MAC_CNT18 (Receive Carrier Sense Error Counter (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT18_RO                                  0x00000848
#define AG_MG_REGS_MAC_CNT18_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT18_RXCSCNT_BO                          0
#define AG_MG_REGS_MAC_CNT18_RXCSCNT_BM                          0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT18_U
{
    struct
    {
        ag_mg_regs_register
            rxcscnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt18_u;
#endif


/*
 * MAC_CNT19 (Receive Undersize Packet Counter (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT19_RO                                  0x0000084C
#define AG_MG_REGS_MAC_CNT19_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT19_RXUSZCNT_BO                         0
#define AG_MG_REGS_MAC_CNT19_RXUSZCNT_BM                         0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT19_U
{
    struct
    {
        ag_mg_regs_register
            rxuszcnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt19_u;
#endif


/*
 * MAC_CNT20 (Receive Oversize Packet Counter (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT20_RO                                  0x00000850
#define AG_MG_REGS_MAC_CNT20_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT20_RXOVSZCNT_BO                        0
#define AG_MG_REGS_MAC_CNT20_RXOVSZCNT_BM                        0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT20_U
{
    struct
    {
        ag_mg_regs_register
            rxovszcnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt20_u;
#endif


/*
 * MAC_CNT21 (Receive Fragments Counter (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT21_RO                                  0x00000854
#define AG_MG_REGS_MAC_CNT21_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT21_RXFRAGCNT_BO                        0
#define AG_MG_REGS_MAC_CNT21_RXFRAGCNT_BM                        0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT21_U
{
    struct
    {
        ag_mg_regs_register
            rxfragcnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt21_u;
#endif


/*
 * MAC_CNT22 (Receive Jabber Counter (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT22_RO                                  0x00000858
#define AG_MG_REGS_MAC_CNT22_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT22_RXJABCNT_BO                         0
#define AG_MG_REGS_MAC_CNT22_RXJABCNT_BM                         0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT22_U
{
    struct
    {
        ag_mg_regs_register
            rxjabcnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt22_u;
#endif


/*
 * MAC_CNT23 (Receive Packets Filtered Count (Width: 24 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT23_RO                                  0x0000085C
#define AG_MG_REGS_MAC_CNT23_RM                                  0x00FFFFFF

#define AG_MG_REGS_MAC_CNT23_RXFILTCNT_BO                        0
#define AG_MG_REGS_MAC_CNT23_RXFILTCNT_BM                        0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT23_U
{
    struct
    {
        ag_mg_regs_register
            rxfiltcnt : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt23_u;
#endif


/*
 * MAC_CNT24 (Transmit Byte Counter (Width: 30 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT24_RO                                  0x00000860
#define AG_MG_REGS_MAC_CNT24_RM                                  0x3FFFFFFF

#define AG_MG_REGS_MAC_CNT24_TXBYTECNT_BO                        0
#define AG_MG_REGS_MAC_CNT24_TXBYTECNT_BM                        0x3FFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT24_U
{
    struct
    {
        ag_mg_regs_register
            txbytecnt : 30,
            fill0 : 2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt24_u;
#endif


/*
 * MAC_CNT25 (Transmit Packet Coutner (Width: 24 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT25_RO                                  0x00000864
#define AG_MG_REGS_MAC_CNT25_RM                                  0x00FFFFFF

#define AG_MG_REGS_MAC_CNT25_TXFRMCNT_BO                         0
#define AG_MG_REGS_MAC_CNT25_TXFRMCNT_BM                         0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT25_U
{
    struct
    {
        ag_mg_regs_register
            txfrmcnt : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt25_u;
#endif


/*
 * MAC_CNT26TRANSMIT (Multicast Packet Counter (Width: 24 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT26TRANSMIT_RO                          0x00000868
#define AG_MG_REGS_MAC_CNT26TRANSMIT_RM                          0x00FFFFFF

#define AG_MG_REGS_MAC_CNT26TRANSMIT_TXMULTICNT_BO               0
#define AG_MG_REGS_MAC_CNT26TRANSMIT_TXMULTICNT_BM               0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT26TRANSMIT_U
{
    struct
    {
        ag_mg_regs_register
            txmulticnt : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt26transmit_u;
#endif


/*
 * MAC_CNT27 (Transmit Broadcast Packet Counter (Width: 24 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT27_RO                                  0x0000086C
#define AG_MG_REGS_MAC_CNT27_RM                                  0x00FFFFFF

#define AG_MG_REGS_MAC_CNT27_TXBRDCNT_BO                         0
#define AG_MG_REGS_MAC_CNT27_TXBRDCNT_BM                         0x00FFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT27_U
{
    struct
    {
        ag_mg_regs_register
            txbrdcnt : 24,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt27_u;
#endif


/*
 * MAC_CNT28 (Transmit PAUSE Control Frame Counter (Width: 18 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT28_RO                                  0x00000870
#define AG_MG_REGS_MAC_CNT28_RM                                  0x0003FFFF

#define AG_MG_REGS_MAC_CNT28_TXPAUSCNT_BO                        0
#define AG_MG_REGS_MAC_CNT28_TXPAUSCNT_BM                        0x0003FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT28_U
{
    struct
    {
        ag_mg_regs_register
            txpauscnt : 18,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt28_u;
#endif


/*
 * MAC_CNT29 (Transmit Deferral Packet Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT29_RO                                  0x00000874
#define AG_MG_REGS_MAC_CNT29_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT29_TXDEFCNT_BO                         0
#define AG_MG_REGS_MAC_CNT29_TXDEFCNT_BM                         0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT29_U
{
    struct
    {
        ag_mg_regs_register
            txdefcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt29_u;
#endif


/*
 * MAC_CNT30 (Transmit Excessive Deferral Packet Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT30_RO                                  0x00000878
#define AG_MG_REGS_MAC_CNT30_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT30_TXEDEFCNT_BO                        0
#define AG_MG_REGS_MAC_CNT30_TXEDEFCNT_BM                        0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT30_U
{
    struct
    {
        ag_mg_regs_register
            txedefcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt30_u;
#endif


/*
 * MAC_CNT31 (Transmit Single Collision Packet Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT31_RO                                  0x0000087C
#define AG_MG_REGS_MAC_CNT31_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT31_TXSCOLCNT_BO                        0
#define AG_MG_REGS_MAC_CNT31_TXSCOLCNT_BM                        0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT31_U
{
    struct
    {
        ag_mg_regs_register
            txscolcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt31_u;
#endif


/*
 * MAC_CNT32 (Transmit Multiple Collision Packet Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT32_RO                                  0x00000880
#define AG_MG_REGS_MAC_CNT32_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT32_TXMCOLCNT_BO                        0
#define AG_MG_REGS_MAC_CNT32_TXMCOLCNT_BM                        0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT32_U
{
    struct
    {
        ag_mg_regs_register
            txmcolcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt32_u;
#endif


/*
 * MAC_CNT33 (Transmit Late Collision Packet Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT33_RO                                  0x00000884
#define AG_MG_REGS_MAC_CNT33_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT33_TXLCOLCNT_BO                        0
#define AG_MG_REGS_MAC_CNT33_TXLCOLCNT_BM                        0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT33_U
{
    struct
    {
        ag_mg_regs_register
            txlcolcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt33_u;
#endif


/*
 * MAC_CNT34 (Transmit Excessive Collision Packet Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT34_RO                                  0x00000888
#define AG_MG_REGS_MAC_CNT34_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT34_TXECOLCNT_BO                        0
#define AG_MG_REGS_MAC_CNT34_TXECOLCNT_BM                        0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT34_U
{
    struct
    {
        ag_mg_regs_register
            txecolcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt34_u;
#endif


/*
 * MAC_CNT35 (Transmit Total Collision Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT35_RO                                  0x0000088C
#define AG_MG_REGS_MAC_CNT35_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT35_TXTCOLCNT_BO                        0
#define AG_MG_REGS_MAC_CNT35_TXTCOLCNT_BM                        0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT35_U
{
    struct
    {
        ag_mg_regs_register
            txtcolcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt35_u;
#endif


/*
 * MAC_CNT36 (Transmit PAUSE Frames Honored Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT36_RO                                  0x00000890
#define AG_MG_REGS_MAC_CNT36_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT36_TXPFHCNT_BO                         0
#define AG_MG_REGS_MAC_CNT36_TXPFHCNT_BM                         0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT36_U
{
    struct
    {
        ag_mg_regs_register
            txpfhcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt36_u;
#endif


/*
 * MAC_CNT37 (Receive Overflow Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT37_RO                                  0x00000894
#define AG_MG_REGS_MAC_CNT37_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT37_RXOVFCNT_BO                         0
#define AG_MG_REGS_MAC_CNT37_RXOVFCNT_BM                         0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT37_U
{
    struct
    {
        ag_mg_regs_register
            rxovfcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt37_u;
#endif


/*
 * MAC_CNT38 (Transmit Jabber Frame Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT38_RO                                  0x00000898
#define AG_MG_REGS_MAC_CNT38_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT38_TXJABCNT_BO                         0
#define AG_MG_REGS_MAC_CNT38_TXJABCNT_BM                         0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT38_U
{
    struct
    {
        ag_mg_regs_register
            txjabcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt38_u;
#endif


/*
 * MAC_CNT39 (Transmit FCS Error Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT39_RO                                  0x0000089C
#define AG_MG_REGS_MAC_CNT39_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT39_TXFCSERR_BO                         0
#define AG_MG_REGS_MAC_CNT39_TXFCSERR_BM                         0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT39_U
{
    struct
    {
        ag_mg_regs_register
            txfcserr : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt39_u;
#endif


/*
 * MAC_CNT40 (Transmit Control Frame Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT40_RO                                  0x000008A0
#define AG_MG_REGS_MAC_CNT40_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT40_TXCTRLCNT_BO                        0
#define AG_MG_REGS_MAC_CNT40_TXCTRLCNT_BM                        0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT40_U
{
    struct
    {
        ag_mg_regs_register
            txctrlcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt40_u;
#endif


/*
 * MAC_CNT41 (Transmit Oversize Frame Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT41_RO                                  0x000008A4
#define AG_MG_REGS_MAC_CNT41_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT41_TXOVRCNT_BO                         0
#define AG_MG_REGS_MAC_CNT41_TXOVRCNT_BM                         0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT41_U
{
    struct
    {
        ag_mg_regs_register
            txovrcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt41_u;
#endif


/*
 * MAC_CNT42 (Transmit Undersize Frame Counter (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT42_RO                                  0x000008A8
#define AG_MG_REGS_MAC_CNT42_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT42_TXUNDCNT_BO                         0
#define AG_MG_REGS_MAC_CNT42_TXUNDCNT_BM                         0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT42_U
{
    struct
    {
        ag_mg_regs_register
            txundcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt42_u;
#endif


/*
 * MAC_CNT43 (Transmit Fragments Frame Coutner (Width: 14 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Clear on Read Only
 */
#define AG_MG_REGS_MAC_CNT43_RO                                  0x000008AC
#define AG_MG_REGS_MAC_CNT43_RM                                  0x00003FFF

#define AG_MG_REGS_MAC_CNT43_TXFRAGCNT_BO                        0
#define AG_MG_REGS_MAC_CNT43_TXFRAGCNT_BM                        0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_CNT43_U
{
    struct
    {
        ag_mg_regs_register
            txfragcnt : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_cnt43_u;
#endif


/*
 * MAC_OVF1 (Counter Overflow Register 1 (Width: 32 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MAC_OVF1_RO                                   0x000008B0
#define AG_MG_REGS_MAC_OVF1_RM                                   0xFFFFFFFF

#define AG_MG_REGS_MAC_OVF1_OVFL_BO                              0
#define AG_MG_REGS_MAC_OVF1_OVFL_BM                              0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_OVF1_U
{
    struct
    {
        ag_mg_regs_register
            ovfl;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_ovf1_u;
#endif


/*
 * MAC_OVF2 (Counter Overflow Register 2 (Width: 32 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MAC_OVF2_RO                                   0x000008B4
#define AG_MG_REGS_MAC_OVF2_RM                                   0x00000FFF

#define AG_MG_REGS_MAC_OVF2_OVFH_BO                              0
#define AG_MG_REGS_MAC_OVF2_OVFH_BM                              0x00000FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_OVF2_U
{
    struct
    {
        ag_mg_regs_register
            ovfh : 12,
            fill0 : 20;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_ovf2_u;
#endif


/*
 * MAC_MASK1 (Counter Overflow Interrupt Mask Register 1 (Width: 32 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_MASK1_RO                                  0x000008B8
#define AG_MG_REGS_MAC_MASK1_RM                                  0xFFFFFFFF

#define AG_MG_REGS_MAC_MASK1_MASKL_BO                            0
#define AG_MG_REGS_MAC_MASK1_MASKL_BM                            0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_MASK1_U
{
    struct
    {
        ag_mg_regs_register
            maskl;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_mask1_u;
#endif


/*
 * MAC_MASK2 (Counter Overflow Interrupt Mask Register 2 (Width: 32 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_MASK2_RO                                  0x000008BC
#define AG_MG_REGS_MAC_MASK2_RM                                  0x00000FFF

#define AG_MG_REGS_MAC_MASK2_MASKH_BO                            0
#define AG_MG_REGS_MAC_MASK2_MASKH_BM                            0x00000FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MAC_MASK2_U
{
    struct
    {
        ag_mg_regs_register
            maskh : 12,
            fill0 : 20;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mac_mask2_u;
#endif


/*
 * MAC_BINCTL (Counter Bin Control Register (Width: 2 bits))
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MAC_BINCTL_RO                                 0x000008C0
#define AG_MG_REGS_MAC_BINCTL_RM                                 0x00000003

#define AG_MG_REGS_MAC_BINCTL_BINCTL_BO                          0
#define AG_MG_REGS_MAC_BINCTL_BINCTL_BM                          0x00000003

/*
* Physical register addresses (for accessing MACp, where p = 0 or 1)
*/
#ifdef AG_MG_REGS_BUILT_FOR_DSS
#define AG_MG_REGS_MAC_BASE		0xC3044000
#else
#define AG_MG_REGS_MAC_BASE		0x30044000
#endif

#define AG_MG_REGS_MAC_REG(p,ro)		(AG_MG_REGS_MAC_BASE+(0x8000*(p)+(ro)))

#define AG_MG_REGS_MAC_ENPAUSE_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_ENPAUSE_RO)
#define AG_MG_REGS_MAC_SA1_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_SA1_RO)
#define AG_MG_REGS_MAC_SA2_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_SA2_RO)
#define AG_MG_REGS_MAC_TIMING_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_TIMING_RO)
#define AG_MG_REGS_MAC_CONTROL_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CONTROL_RO)
#define AG_MG_REGS_MAC_STATUS_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_STATUS_RO)
#define AG_MG_REGS_MAC_PRBSTATUS_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_PRBSTATUS_RO)
#define AG_MG_REGS_MAC_SGMII_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_SGMII_RO)
#define AG_MG_REGS_MAC_PRBSCTL_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_PRBSCTL_RO)
#define AG_MG_REGS_MAC_ANCTRL_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_ANCTRL_RO)
#define AG_MG_REGS_MAC_ANSTAT_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_ANSTAT_RO)
#define AG_MG_REGS_MAC_ERRSTAT_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_ERRSTAT_RO)
#define AG_MG_REGS_MAC_PFILTER_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_PFILTER_RO)
#define AG_MG_REGS_MAC_MULTI1_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_MULTI1_RO)
#define AG_MG_REGS_MAC_MULTI2_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_MULTI2_RO)
#define AG_MG_REGS_MAC_MULTI3_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_MULTI3_RO)
#define AG_MG_REGS_MAC_MULTI4_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_MULTI4_RO)
#define AG_MG_REGS_MAC_UNI1_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_UNI1_RO)
#define AG_MG_REGS_MAC_UNI2_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_UNI2_RO)
#define AG_MG_REGS_MAC_UNI3_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_UNI3_RO)
#define AG_MG_REGS_MAC_UNI4_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_UNI4_RO)
#define AG_MG_REGS_MAC_UNI5_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_UNI5_RO)
#define AG_MG_REGS_MAC_SMIICTRL_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_SMIICTRL_RO)
#define AG_MG_REGS_MAC_SMIISTATUS_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_SMIISTATUS_RO)
#define AG_MG_REGS_MAC_INTMASKC37_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_INTMASKC37_RO)
#define AG_MG_REGS_MAC_CNT0_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT0_RO)
#define AG_MG_REGS_MAC_CNT1_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT1_RO)
#define AG_MG_REGS_MAC_CNT2_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT2_RO)
#define AG_MG_REGS_MAC_CNT3_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT3_RO)
#define AG_MG_REGS_MAC_CNT4_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT4_RO)
#define AG_MG_REGS_MAC_CNT5_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT5_RO)
#define AG_MG_REGS_MAC_CNT6_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT6_RO)
#define AG_MG_REGS_MAC_CNT7_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT7_RO)
#define AG_MG_REGS_MAC_CNT8_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT8_RO)
#define AG_MG_REGS_MAC_CNT9_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT9_RO)
#define AG_MG_REGS_MAC_CNT10_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT10_RO)
#define AG_MG_REGS_MAC_CNT11_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT11_RO)
#define AG_MG_REGS_MAC_CNT12_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT12_RO)
#define AG_MG_REGS_MAC_CNT13_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT13_RO)
#define AG_MG_REGS_MAC_CNT14_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT14_RO)
#define AG_MG_REGS_MAC_CNT15_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT15_RO)
#define AG_MG_REGS_MAC_CNT16_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT16_RO)
#define AG_MG_REGS_MAC_CNT17_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT17_RO)
#define AG_MG_REGS_MAC_CNT18_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT18_RO)
#define AG_MG_REGS_MAC_CNT19_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT19_RO)
#define AG_MG_REGS_MAC_CNT20_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT20_RO)
#define AG_MG_REGS_MAC_CNT21_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT21_RO)
#define AG_MG_REGS_MAC_CNT22_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT22_RO)
#define AG_MG_REGS_MAC_CNT23_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT23_RO)
#define AG_MG_REGS_MAC_CNT24_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT24_RO)
#define AG_MG_REGS_MAC_CNT25_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT25_RO)
#define AG_MG_REGS_MAC_CNT26TRANSMIT_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT26TRANSMIT_RO)
#define AG_MG_REGS_MAC_CNT27_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT27_RO)
#define AG_MG_REGS_MAC_CNT28_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT28_RO)
#define AG_MG_REGS_MAC_CNT29_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT29_RO)
#define AG_MG_REGS_MAC_CNT30_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT30_RO)
#define AG_MG_REGS_MAC_CNT31_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT31_RO)
#define AG_MG_REGS_MAC_CNT32_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT32_RO)
#define AG_MG_REGS_MAC_CNT33_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT33_RO)
#define AG_MG_REGS_MAC_CNT34_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT34_RO)
#define AG_MG_REGS_MAC_CNT35_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT35_RO)
#define AG_MG_REGS_MAC_CNT36_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT36_RO)
#define AG_MG_REGS_MAC_CNT37_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT37_RO)
#define AG_MG_REGS_MAC_CNT38_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT38_RO)
#define AG_MG_REGS_MAC_CNT39_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT39_RO)
#define AG_MG_REGS_MAC_CNT40_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT40_RO)
#define AG_MG_REGS_MAC_CNT41_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT41_RO)
#define AG_MG_REGS_MAC_CNT42_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT42_RO)
#define AG_MG_REGS_MAC_CNT43_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_CNT43_RO)
#define AG_MG_REGS_MAC_OVF1_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_OVF1_RO)
#define AG_MG_REGS_MAC_OVF2_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_OVF2_RO)
#define AG_MG_REGS_MAC_MASK1_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_MASK1_RO)
#define AG_MG_REGS_MAC_MASK2_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_MASK2_RO)
#define AG_MG_REGS_MAC_BINCTL_RA(p)	AG_MG_REGS_MAC_REG(p,AG_MG_REGS_MAC_BINCTL_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
#define AG_MG_REGS_MAC_CONTROL_BOUNDARY     (AG_MG_REGS_MAC_SMIISTAT_RO + sizeof(ag_mg_regs_mac_smiistat_u))
#define AG_MG_REGS_MAC_CONTROL_STATUS_GAP_SIZE     ((AG_MG_REGS_MAC_CNT0_RO - AG_MG_REGS_MAC_CONTROL_BOUNDARY)         / sizeof(ag_mg_regs_register))

typedef struct AG_MG_REGS_MAC_REGS_S
{
	ag_mg_regs_mac_enpause_u	mac_enpause ;
	ag_mg_regs_mac_sa1_u	mac_sa1 ;
	ag_mg_regs_mac_sa2_u	mac_sa2 ;
	ag_mg_regs_mac_timing_u	mac_timing ;
	ag_mg_regs_mac_control_u	mac_control ;
	ag_mg_regs_mac_status_u	mac_status ;
	ag_mg_regs_mac_prbstatus_u	mac_prbstatus ;
	ag_mg_regs_mac_sgmii_u	mac_sgmii ;
	ag_mg_regs_mac_prbsctl_u	mac_prbsctl ;
	ag_mg_regs_mac_anctrl_u	mac_anctrl ;
	ag_mg_regs_mac_anstat_u	mac_anstat ;
	ag_mg_regs_mac_errstat_u	mac_errstat ;
	ag_mg_regs_mac_pfilter_u	mac_pfilter ;
	ag_mg_regs_mac_multi1_u	mac_multi1 ;
	ag_mg_regs_mac_multi2_u	mac_multi2 ;
	ag_mg_regs_mac_multi3_u	mac_multi3 ;
	ag_mg_regs_mac_multi4_u	mac_multi4 ;
	ag_mg_regs_mac_uni1_u	mac_uni1 ;
	ag_mg_regs_mac_uni2_u	mac_uni2 ;
	ag_mg_regs_mac_uni3_u	mac_uni3 ;
	ag_mg_regs_mac_uni4_u	mac_uni4 ;
	ag_mg_regs_mac_uni5_u	mac_uni5 ;
	ag_mg_regs_mac_smiictrl_u	mac_smiictrl ;
	ag_mg_regs_mac_smiistatus_u	mac_smiistatus ;
	ag_mg_regs_mac_intmaskc37_u	mac_intmaskc37 ;
	ag_mg_regs_register fill0[487];
	ag_mg_regs_mac_cnt0_u	mac_cnt0 ;
	ag_mg_regs_mac_cnt1_u	mac_cnt1 ;
	ag_mg_regs_mac_cnt2_u	mac_cnt2 ;
	ag_mg_regs_mac_cnt3_u	mac_cnt3 ;
	ag_mg_regs_mac_cnt4_u	mac_cnt4 ;
	ag_mg_regs_mac_cnt5_u	mac_cnt5 ;
	ag_mg_regs_mac_cnt6_u	mac_cnt6 ;
	ag_mg_regs_mac_cnt7_u	mac_cnt7 ;
	ag_mg_regs_mac_cnt8_u	mac_cnt8 ;
	ag_mg_regs_mac_cnt9_u	mac_cnt9 ;
	ag_mg_regs_mac_cnt10_u	mac_cnt10 ;
	ag_mg_regs_mac_cnt11_u	mac_cnt11 ;
	ag_mg_regs_mac_cnt12_u	mac_cnt12 ;
	ag_mg_regs_mac_cnt13_u	mac_cnt13 ;
	ag_mg_regs_mac_cnt14_u	mac_cnt14 ;
	ag_mg_regs_mac_cnt15_u	mac_cnt15 ;
	ag_mg_regs_mac_cnt16_u	mac_cnt16 ;
	ag_mg_regs_mac_cnt17_u	mac_cnt17 ;
	ag_mg_regs_mac_cnt18_u	mac_cnt18 ;
	ag_mg_regs_mac_cnt19_u	mac_cnt19 ;
	ag_mg_regs_mac_cnt20_u	mac_cnt20 ;
	ag_mg_regs_mac_cnt21_u	mac_cnt21 ;
	ag_mg_regs_mac_cnt22_u	mac_cnt22 ;
	ag_mg_regs_mac_cnt23_u	mac_cnt23 ;
	ag_mg_regs_mac_cnt24_u	mac_cnt24 ;
	ag_mg_regs_mac_cnt25_u	mac_cnt25 ;
	ag_mg_regs_mac_cnt26transmit_u	mac_cnt26transmit ;
	ag_mg_regs_mac_cnt27_u	mac_cnt27 ;
	ag_mg_regs_mac_cnt28_u	mac_cnt28 ;
	ag_mg_regs_mac_cnt29_u	mac_cnt29 ;
	ag_mg_regs_mac_cnt30_u	mac_cnt30 ;
	ag_mg_regs_mac_cnt31_u	mac_cnt31 ;
	ag_mg_regs_mac_cnt32_u	mac_cnt32 ;
	ag_mg_regs_mac_cnt33_u	mac_cnt33 ;
	ag_mg_regs_mac_cnt34_u	mac_cnt34 ;
	ag_mg_regs_mac_cnt35_u	mac_cnt35 ;
	ag_mg_regs_mac_cnt36_u	mac_cnt36 ;
	ag_mg_regs_mac_cnt37_u	mac_cnt37 ;
	ag_mg_regs_mac_cnt38_u	mac_cnt38 ;
	ag_mg_regs_mac_cnt39_u	mac_cnt39 ;
	ag_mg_regs_mac_cnt40_u	mac_cnt40 ;
	ag_mg_regs_mac_cnt41_u	mac_cnt41 ;
	ag_mg_regs_mac_cnt42_u	mac_cnt42 ;
	ag_mg_regs_mac_cnt43_u	mac_cnt43 ;
	ag_mg_regs_mac_ovf1_u	mac_ovf1 ;
	ag_mg_regs_mac_ovf2_u	mac_ovf2 ;
	ag_mg_regs_mac_mask1_u	mac_mask1 ;
	ag_mg_regs_mac_mask2_u	mac_mask2 ;
} ag_mg_regs_mac_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_mac_reg_s *macM_regs =
*       (volatile ag_mg_regs_mac_reg_s *)(AG_MG_REGS_MAC_BASE + (0x8000*M));
* where M = 0 or 1
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_mac.h,v $
Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

