/* $Id: ag_mg_regs_mdio.h,v 1.1 2012/04/18 18:08:26 srane Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/sp27dsp/dss/inc/ag_mg_regs_mdio.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_mdio.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_mdio.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of LSI Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * Implements the MDIO interface defined in the IEEE 802.3 standard.
 * Supports both Clause 22 and Clause 45 definitions.
 * Operates only as a bus master.
 * 
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * This file describes the programmable registers of the MDIO module.
 *
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *  MDIO_CTRL
 *  MDIO_STATUS
 *  MDIO_CLKOFST
 *  MDIO_CLKPER
 *
 * Prefix naming conventions :
 *   AG_MG_REGS_XXX_RA : register/memory physical address
 *   AG_MG_REGS_XXX_RO : register/memory address offset
 *   AG_MG_REGS_XXX_RM : register mask
 *   AG_MG_REGS_XXX_BO : bit/field offset from LSB
 *   AG_MG_REGS_XXX_BM : bit/field mask
 *   AG_MG_REGS_XXX_U  : bitfields in C union typedef
 *   AG_MG_REGS_XXX_S  : registers in C struct typedef
 *   AG_MG_REGS_XX_RPT : number of identical registers in array
 *   AG_MG_REGS_XX_IVL : interval between registers in array
 *
 * NOTE: user may redefine ag_mg_regs_register
 *       in ag_mg_regs_regops.h if necessary
 * NOTE: access mode of individual bit fields matches that
 *       of containing register unless indicated otherwise
 */

#ifndef AG_MG_REGS_MDIO_REGISTERS_H
#define AG_MG_REGS_MDIO_REGISTERS_H

#include "ag_mg_regs_regops.h"


/*
 * Generated by HSI Designer release 2.3.5.
 */

/*
 * MDIO_CTRL (MDIO Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MDIO_CTRL_RO              0x00000000
#define AG_MG_REGS_MDIO_CTRL_RM              0xFFFFFFFF

#define AG_MG_REGS_MDIO_CTRL_DATA_BO         0
#define AG_MG_REGS_MDIO_CTRL_DATA_BM         0x0000FFFF

#define AG_MG_REGS_MDIO_CTRL_PORTADDR_BO     16
#define AG_MG_REGS_MDIO_CTRL_PORTADDR_BM     0x001F0000

#define AG_MG_REGS_MDIO_CTRL_DEVADDR_BO      21
#define AG_MG_REGS_MDIO_CTRL_DEVADDR_BM      0x03E00000

#define AG_MG_REGS_MDIO_CTRL_MDIOISEL_BO     26
#define AG_MG_REGS_MDIO_CTRL_MDIOISEL_BM     0x04000000

#define AG_MG_REGS_MDIO_CTRL_OPCODE_BO       27
#define AG_MG_REGS_MDIO_CTRL_OPCODE_BM       0x18000000

#define AG_MG_REGS_MDIO_CTRL_CLAUSE45_BO     29
#define AG_MG_REGS_MDIO_CTRL_CLAUSE45_BM     0x20000000

#define AG_MG_REGS_MDIO_CTRL_PRSUP_BO        30
#define AG_MG_REGS_MDIO_CTRL_PRSUP_BM        0x40000000

#define AG_MG_REGS_MDIO_CTRL_BUSY_BO         31
#define AG_MG_REGS_MDIO_CTRL_BUSY_BM         0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MDIO_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            data : 16,
            portaddr : 5,
            devaddr : 5,
            mdioisel : 1,
            opcode : 2,
            clause45 : 1,
            prsup : 1,
            busy : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mdio_ctrl_u;
#endif


/*
 * MDIO_STATUS (MDIO Status Register)
 * Initialization value: 0x40000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MDIO_STATUS_RO            0x00000004
#define AG_MG_REGS_MDIO_STATUS_RM            0xC0000000

#define AG_MG_REGS_MDIO_STATUS_DONE_BO       30
#define AG_MG_REGS_MDIO_STATUS_DONE_BM       0x40000000

#define AG_MG_REGS_MDIO_STATUS_BUSY_BO       31
#define AG_MG_REGS_MDIO_STATUS_BUSY_BM       0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MDIO_STATUS_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 30,
            done : 1,
            busy : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mdio_status_u;
#endif


/*
 * MDIO_CLKOFST (MDIO Clock Offset Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MDIO_CLKOFST_RO           0x00000008
#define AG_MG_REGS_MDIO_CLKOFST_RM           0x000000FF

#define AG_MG_REGS_MDIO_CLKOFST_OFFSET_BO    0
#define AG_MG_REGS_MDIO_CLKOFST_OFFSET_BM    0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MDIO_CLKOFST_U
{
    struct
    {
        ag_mg_regs_register
            offset : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mdio_clkofst_u;
#endif


/*
 * MDIO_CLKPER (MDIO Clock Period Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MDIO_CLKPER_RO            0x0000000C
#define AG_MG_REGS_MDIO_CLKPER_RM            0x000000FF

#define AG_MG_REGS_MDIO_CLKPER_PERIOD_BO     0
#define AG_MG_REGS_MDIO_CLKPER_PERIOD_BM     0x000000FF
/*
* Physical register addresses (for ARM accessing MDIO)
*/
/*
 * Physical register addresses (for arm accessing mdio)
 */
#ifdef AG_MG_REGS_BUILT_FOR_DSS
#define AG_MG_REGS_MDIO_BASE		0xC304E000
#else
#define AG_MG_REGS_MDIO_BASE		0x3004E000
#endif

#define AG_MG_REGS_MDIO_REG(ro)		(AG_MG_REGS_MDIO_BASE+(ro))

#define AG_MG_REGS_MDIO_CTRL_RA	AG_MG_REGS_MDIO_REG(AG_MG_REGS_MDIO_CTRL_RO)
#define AG_MG_REGS_MDIO_STATUS_RA	AG_MG_REGS_MDIO_REG(AG_MG_REGS_MDIO_STATUS_RO)
#define AG_MG_REGS_MDIO_CLKOFST_RA	AG_MG_REGS_MDIO_REG(AG_MG_REGS_MDIO_CLKOFST_RO)
#define AG_MG_REGS_MDIO_CLKPER_RA	AG_MG_REGS_MDIO_REG(AG_MG_REGS_MDIO_CLKPER_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_MDIO_REGS_S
{
	ag_mg_regs_mdio_ctrl_u	mdio_ctrl ;
	ag_mg_regs_mdio_status_u	mdio_status ;
	ag_mg_regs_mdio_clkofst_u	mdio_clkofst ;
} ag_mg_regs_mdio_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_mdio_reg_s *mdio_regs =
*       (volatile ag_mg_regs_mdio_reg_s *) AG_MG_REGS_MDIO_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_mdio.h,v $
Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

