/* $Id: ag_mg_regs_nand_flash.h,v 1.1 2012/04/18 18:08:26 srane Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/sp27dsp/dss/inc/ag_mg_regs_nand_flash.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_nand_flash.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_nand_flash.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of LSI Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * The SP2704 DSP provides a NAND flash controller interface in the PPB to support boot
 * loading. It is accessible by the ARM cores and the DSS cores.
 * 
 * During flash device programming, the NAND flash controller ANDs the write data with
 * the contents of the corresponding flash memory location. Programming of the NAND
 * flash device occurs on a page basis. Even when software does not provide enough
 * write data to fill a page, the flash controller specifies a default write data of 0xFF
 * to the remaining memory locations on the page. ANDing 0xFF with flash memory content
 * preserves the existing content. To overwrite flash memory content, a block erase
 * operation must precede a write operation. While programming occurs on a page basis,
 * erasure occurs on a block basis.
 *
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *  NAND_FLASH_CMDREG
 *  NAND_FLASH_INDEX
 *  NAND_FLASH_STATUS0
 *  NAND_FLASH_STATUS1
 *  NAND_FLASH_ID0
 *  NAND_FLASH_ID1
 *  NAND_FLASH_ID2
 *  NAND_FLASH_ID3
 *  NAND_FLASH_ID4
 *  NAND_FLASH_ID5
 *  NAND_FLASH_ID6
 *  NAND_FLASH_ID7
 *  NAND_FLASH_INTEN
 *  NAND_FLASH_INTSTAT
 *  NAND_FLASH_INTREG
 *  NAND_FLASH_ECCADR
 *  NAND_FLASH_ECCVAL
 *  NAND_FLASH_ECCINJ
 *  NAND_FLASH_EXINDEX
 *  NAND_FLASH_TIMCTL0
 *  NAND_FLASH_TIMCTL1
 *  NAND_FLASH_CONFIG
 *  NAND_FLASH_PECC
 *  NAND_FLASH_DATA_REG
*
* Prefix naming conventions :
*   AG_MG_REGS_XXX_RA : register/memory physical address
*   AG_MG_REGS_XXX_RO : register/memory address offset
*   AG_MG_REGS_XXX_RM : register mask
*   AG_MG_REGS_XXX_BO : bit/field offset from LSB
*   AG_MG_REGS_XXX_BM : bit/field mask
*   AG_MG_REGS_XXX_U  : bitfields in C union typedef
*   AG_MG_REGS_XXX_S  : registers in C struct typedef
*   AG_MG_REGS_XX_RPT : number of identical registers in array
*   AG_MG_REGS_XX_IVL : interval between registers in array
*
* NOTE: user may redefine ag_mg_regs_register
*       in ag_mg_regs_regops.h if necessary
* NOTE: access mode of individual bit fields matches that
*       of containing register unless indicated otherwise
*/

#ifndef AG_MG_REGS_NAND_FLASH_REGISTERS_H
#define AG_MG_REGS_NAND_FLASH_REGISTERS_H

#include "ag_mg_regs_regops.h"

/* 
 * Generated by HSI Designer release 2.3.5.
 */


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_NAND_FLASH_CMDREG_RO                0x00008000
#define AG_MG_REGS_NAND_FLASH_CMDREG_RM                0x000003FF

#define AG_MG_REGS_NAND_FLASH_CMDREG_CMDREG_BO         0
#define AG_MG_REGS_NAND_FLASH_CMDREG_CMDREG_BM         0x000000FF

#define AG_MG_REGS_NAND_FLASH_CMDREG_CSSEL_BO          8
#define AG_MG_REGS_NAND_FLASH_CMDREG_CSSEL_BM          0x00000300

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_CMDREG_U
{
    struct
    {
        ag_mg_regs_register
            cmdreg : 8,
            cssel : 2,
            fill0 : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_cmdreg_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_NAND_FLASH_INDEX_RO                 0x00008004
#define AG_MG_REGS_NAND_FLASH_INDEX_RM                 0xFFFFFFFF

#define AG_MG_REGS_NAND_FLASH_INDEX_INDEX_BO           0
#define AG_MG_REGS_NAND_FLASH_INDEX_INDEX_BM           0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_INDEX_U
{
    struct
    {
        ag_mg_regs_register
            index;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_index_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_STATUS0_RO               0x00008008
#define AG_MG_REGS_NAND_FLASH_STATUS0_RM               0x0000FFFF

#define AG_MG_REGS_NAND_FLASH_STATUS0_STAT0_0_BO       0
#define AG_MG_REGS_NAND_FLASH_STATUS0_STAT0_0_BM       0x000000FF

#define AG_MG_REGS_NAND_FLASH_STATUS0_STAT0_1_BO       8
#define AG_MG_REGS_NAND_FLASH_STATUS0_STAT0_1_BM       0x0000FF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_STATUS0_U
{
    struct
    {
        ag_mg_regs_register
            stat0_0 : 8,
            stat0_1 : 8,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_status0_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_STATUS1_RO               0x0000800C
#define AG_MG_REGS_NAND_FLASH_STATUS1_RM               0x00000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_STATUS1_U
{
    struct
    {
        ag_mg_regs_register nand_flash_status1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_status1_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_ID0_RO                   0x00008010
#define AG_MG_REGS_NAND_FLASH_ID0_RM                   0x0000FFFF

#define AG_MG_REGS_NAND_FLASH_ID0_ID0_0_BO             0
#define AG_MG_REGS_NAND_FLASH_ID0_ID0_0_BM             0x000000FF

#define AG_MG_REGS_NAND_FLASH_ID0_ID0_1_BO             8
#define AG_MG_REGS_NAND_FLASH_ID0_ID0_1_BM             0x0000FF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_ID0_U
{
    struct
    {
        ag_mg_regs_register
            id0_0 : 8,
            id0_1 : 8,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_id0_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_ID1_RO                   0x00008014
#define AG_MG_REGS_NAND_FLASH_ID1_RM                   0x00000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_ID1_U
{
    struct
    {
        ag_mg_regs_register nand_flash_id1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_id1_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_ID2_RO                   0x00008018
#define AG_MG_REGS_NAND_FLASH_ID2_RM                   0x0000FFFF

#define AG_MG_REGS_NAND_FLASH_ID2_ID2_0_BO             0
#define AG_MG_REGS_NAND_FLASH_ID2_ID2_0_BM             0x000000FF

#define AG_MG_REGS_NAND_FLASH_ID2_ID2_1_BO             8
#define AG_MG_REGS_NAND_FLASH_ID2_ID2_1_BM             0x0000FF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_ID2_U
{
    struct
    {
        ag_mg_regs_register
            id2_0 : 8,
            id2_1 : 8,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_id2_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_ID3_RO                   0x0000801C
#define AG_MG_REGS_NAND_FLASH_ID3_RM                   0x00000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_ID3_U
{
    struct
    {
        ag_mg_regs_register nand_flash_id3;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_id3_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_ID4_RO                   0x00008020
#define AG_MG_REGS_NAND_FLASH_ID4_RM                   0x0000FFFF

#define AG_MG_REGS_NAND_FLASH_ID4_ID4_0_BO             0
#define AG_MG_REGS_NAND_FLASH_ID4_ID4_0_BM             0x000000FF

#define AG_MG_REGS_NAND_FLASH_ID4_ID4_1_BO             8
#define AG_MG_REGS_NAND_FLASH_ID4_ID4_1_BM             0x0000FF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_ID4_U
{
    struct
    {
        ag_mg_regs_register
            id4_0 : 8,
            id4_1 : 8,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_id4_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_ID5_RO                   0x00008024
#define AG_MG_REGS_NAND_FLASH_ID5_RM                   0x00000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_ID5_U
{
    struct
    {
        ag_mg_regs_register nand_flash_id5;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_id5_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_ID6_RO                   0x00008028
#define AG_MG_REGS_NAND_FLASH_ID6_RM                   0x0000FFFF

#define AG_MG_REGS_NAND_FLASH_ID6_ID6_0_BO             0
#define AG_MG_REGS_NAND_FLASH_ID6_ID6_0_BM             0x000000FF

#define AG_MG_REGS_NAND_FLASH_ID6_ID6_1_BO             8
#define AG_MG_REGS_NAND_FLASH_ID6_ID6_1_BM             0x0000FF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_ID6_U
{
    struct
    {
        ag_mg_regs_register
            id6_0 : 8,
            id6_1 : 8,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_id6_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_ID7_RO                   0x0000802C
#define AG_MG_REGS_NAND_FLASH_ID7_RM                   0x00000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_ID7_U
{
    struct
    {
        ag_mg_regs_register nand_flash_id7;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_id7_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_NAND_FLASH_INTEN_RO                 0x00008030
#define AG_MG_REGS_NAND_FLASH_INTEN_RM                 0x0000000C

#define AG_MG_REGS_NAND_FLASH_INTEN_READY_BUSY_RISING_BO    2
#define AG_MG_REGS_NAND_FLASH_INTEN_READY_BUSY_RISING_BM	0x00000004

#define AG_MG_REGS_NAND_FLASH_INTEN_READY_BUSY_FALLING_BO   3
#define AG_MG_REGS_NAND_FLASH_INTEN_READY_BUSY_FALLING_BM	0x00000008

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_INTEN_U
{
    struct
    {
        ag_mg_regs_register
			fill0 : 2,
			ready_busy_rising : 1,
			ready_busy_falling : 1,
			fill1 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_inten_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_NAND_FLASH_INTSTAT_RO               0x00008034
#define AG_MG_REGS_NAND_FLASH_INTSTAT_RM               0x0000002C

#define AG_MG_REGS_NAND_FLASH_INTSTAT_READY_BUSY_R_EDGE_BO     2
#define AG_MG_REGS_NAND_FLASH_INTSTAT_READY_BUSY_R_EDGE_BM     0x00000004

#define AG_MG_REGS_NAND_FLASH_INTSTAT_READY_BUSY_F_EDGE_BO     3
#define AG_MG_REGS_NAND_FLASH_INTSTAT_READY_BUSY_F_EDGE_BM     0x00000008

#define AG_MG_REGS_NAND_FLASH_INTSTAT_READY_BUSY_BO     	   5
#define AG_MG_REGS_NAND_FLASH_INTSTAT_READY_BUSY_BM     	   0x00000020

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_INTSTAT_U
{
    struct
    {
        ag_mg_regs_register
			fill0 : 2,
			ready_busy_r_edge : 1,
			ready_busy_f_edge : 1,
            fill1 : 1,
            ready_busy : 1,
            fill2 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_intstat_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_INTREG_RO                0x00008038
#define AG_MG_REGS_NAND_FLASH_INTREG_RM                0x0000001F

#define AG_MG_REGS_NAND_FLASH_INTREG_INTSTAT2_AND_INTEN2_BO		2
#define AG_MG_REGS_NAND_FLASH_INTREG_INTSTAT2_AND_INTEN2_BM		0x00000004

#define AG_MG_REGS_NAND_FLASH_INTREG_INTSTAT3_AND_INTEN3_BO		3
#define AG_MG_REGS_NAND_FLASH_INTREG_INTSTAT3_AND_INTEN3_BM		0x00000008

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_INTREG_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 2,
			intstat2_and_inten2 : 1,
			intstat3_and_inten3 : 1,
            fill1 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_intreg_u;
#endif

/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_NAND_FLASH_EXINDEX_RO               0x00008048
#define AG_MG_REGS_NAND_FLASH_EXINDEX_RM               0x000000FF

#define AG_MG_REGS_NAND_FLASH_EXINDEX_EXINDEX_BO       0
#define AG_MG_REGS_NAND_FLASH_EXINDEX_EXINDEX_BM       0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_EXINDEX_U
{
    struct
    {
        ag_mg_regs_register
            exindex : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_exindex_u;
#endif


/* 
 * Initialization value: 0x01050505  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_NAND_FLASH_TIMCTL0_RO               0x0000804C
#define AG_MG_REGS_NAND_FLASH_TIMCTL0_RM               0xFFFFFFFF

#define AG_MG_REGS_NAND_FLASH_TIMCTL0_TS_BO            0
#define AG_MG_REGS_NAND_FLASH_TIMCTL0_TS_BM            0x000000FF

#define AG_MG_REGS_NAND_FLASH_TIMCTL0_TWP_BO           8
#define AG_MG_REGS_NAND_FLASH_TIMCTL0_TWP_BM           0x0000FF00

#define AG_MG_REGS_NAND_FLASH_TIMCTL0_TRP_BO           16
#define AG_MG_REGS_NAND_FLASH_TIMCTL0_TRP_BM           0x00FF0000

#define AG_MG_REGS_NAND_FLASH_TIMCTL0_TH_BO            24
#define AG_MG_REGS_NAND_FLASH_TIMCTL0_TH_BM            0xFF000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_TIMCTL0_U
{
    struct
    {
        ag_mg_regs_register
            ts : 8,
            twp : 8,
            trp : 8,
            th : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_timctl0_u;
#endif


/* 
 * Initialization value: 0x0F040202  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_NAND_FLASH_TIMCTL1_RO               0x00008050
#define AG_MG_REGS_NAND_FLASH_TIMCTL1_RM               0xFFFFFFFF

#define AG_MG_REGS_NAND_FLASH_TIMCTL1_TWH_BO           0
#define AG_MG_REGS_NAND_FLASH_TIMCTL1_TWH_BM           0x000000FF

#define AG_MG_REGS_NAND_FLASH_TIMCTL1_TRH_BO           8
#define AG_MG_REGS_NAND_FLASH_TIMCTL1_TRH_BM           0x0000FF00

#define AG_MG_REGS_NAND_FLASH_TIMCTL1_TRR_BO           16
#define AG_MG_REGS_NAND_FLASH_TIMCTL1_TRR_BM           0x00FF0000

#define AG_MG_REGS_NAND_FLASH_TIMCTL1_TWB_BO           24
#define AG_MG_REGS_NAND_FLASH_TIMCTL1_TWB_BM           0xFF000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_TIMCTL1_U
{
    struct
    {
        ag_mg_regs_register
            twh : 8,
            trh : 8,
            trr : 8,
            twb : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_timctl1_u;
#endif


/* 
 * Initialization value: 0x00000386  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_NAND_FLASH_CONFIG_RO                0x00008054
#define AG_MG_REGS_NAND_FLASH_CONFIG_RM                0x000003FF

#define AG_MG_REGS_NAND_FLASH_CONFIG_SIZE_BO           0
#define AG_MG_REGS_NAND_FLASH_CONFIG_SIZE_BM           0x00000007

#define AG_MG_REGS_NAND_FLASH_CONFIG_WIDTH_BO          3
#define AG_MG_REGS_NAND_FLASH_CONFIG_WIDTH_BM          0x00000008

#define AG_MG_REGS_NAND_FLASH_CONFIG_DEVICES_BO        4
#define AG_MG_REGS_NAND_FLASH_CONFIG_DEVICES_BM        0x00000030

#define AG_MG_REGS_NAND_FLASH_CONFIG_BANK_BO           6
#define AG_MG_REGS_NAND_FLASH_CONFIG_BANK_BM           0x000000C0

#define AG_MG_REGS_NAND_FLASH_CONFIG_BLOCK_BO          8
#define AG_MG_REGS_NAND_FLASH_CONFIG_BLOCK_BM          0x00000100

#define AG_MG_REGS_NAND_FLASH_CONFIG_WP_BO             9
#define AG_MG_REGS_NAND_FLASH_CONFIG_WP_BM             0x00000200

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_CONFIG_U
{
    struct
    {
        ag_mg_regs_register
            size : 3,
            width : 1,
            devices : 2,
            bank : 2,
            block : 1,
            wp : 1,
            fill0 : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_config_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_NAND_FLASH_PECC_RO                  0x00008058
#define AG_MG_REGS_NAND_FLASH_PECC_RM                  0x00003FFF

#define AG_MG_REGS_NAND_FLASH_PECC_PECC_BO             0
#define AG_MG_REGS_NAND_FLASH_PECC_PECC_BM             0x00000FFF

#define AG_MG_REGS_NAND_FLASH_PECC_PECCSTAT_BO         12
#define AG_MG_REGS_NAND_FLASH_PECC_PECCSTAT_BM         0x00003000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_PECC_U
{
    struct
    {
        ag_mg_regs_register
            pecc : 12,
            peccstat : 2,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_pecc_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_NAND_FLASH_DATAREG_RO             0x00000000
#define AG_MG_REGS_NAND_FLASH_DATAREG_RM             0xFFFFFFFF
#define AG_MG_REGS_NAND_FLASH_DATAREG_RPT            8192
#define AG_MG_REGS_NAND_FLASH_DATAREG_IVL            0x4

#define AG_MG_REGS_NAND_FLASH_DATAREG_DATA_REG_BO    0
#define AG_MG_REGS_NAND_FLASH_DATAREG_DATA_REG_BM    0xFFFFFFFF
#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_NAND_FLASH_DATAREG_U
{
    struct
    {
        ag_mg_regs_register
            data_reg;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_nand_flash_datareg_u;
#endif

/*
 * Physical register addresses (for arm accessing nand_flash)
 */
#ifdef AG_MG_REGS_BUILT_FOR_DSS
#define AG_MG_REGS_NAND_FLASH_BASE		0xC3010000
#else
#define AG_MG_REGS_NAND_FLASH_BASE		0x30010000
#endif
#define AG_MG_REGS_NAND_FLASH_REG(ro)		(AG_MG_REGS_NAND_FLASH_BASE+(ro))
 
#define AG_MG_REGS_NAND_FLASH_CMDREG_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_CMDREG_RO)
#define AG_MG_REGS_NAND_FLASH_INDEX_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_INDEX_RO)
#define AG_MG_REGS_NAND_FLASH_STATUS0_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_STATUS0_RO)
#define AG_MG_REGS_NAND_FLASH_STATUS1_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_STATUS1_RO)
#define AG_MG_REGS_NAND_FLASH_ID0_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_ID0_RO)
#define AG_MG_REGS_NAND_FLASH_ID1_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_ID1_RO)
#define AG_MG_REGS_NAND_FLASH_ID2_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_ID2_RO)
#define AG_MG_REGS_NAND_FLASH_ID3_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_ID3_RO)
#define AG_MG_REGS_NAND_FLASH_ID4_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_ID4_RO)
#define AG_MG_REGS_NAND_FLASH_ID5_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_ID5_RO)
#define AG_MG_REGS_NAND_FLASH_ID6_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_ID6_RO)
#define AG_MG_REGS_NAND_FLASH_ID7_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_ID7_RO)
#define AG_MG_REGS_NAND_FLASH_INTEN_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_INTEN_RO)
#define AG_MG_REGS_NAND_FLASH_INTSTAT_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_INTSTAT_RO)
#define AG_MG_REGS_NAND_FLASH_INTREG_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_INTREG_RO)
#define AG_MG_REGS_NAND_FLASH_EXINDEX_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_EXINDEX_RO)
#define AG_MG_REGS_NAND_FLASH_TIMCTL0_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_TIMCTL0_RO)
#define AG_MG_REGS_NAND_FLASH_TIMCTL1_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_TIMCTL1_RO)
#define AG_MG_REGS_NAND_FLASH_CONFIG_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_CONFIG_RO)
#define AG_MG_REGS_NAND_FLASH_PECC_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_PECC_RO)
#define AG_MG_REGS_NAND_FLASH_DATAREG_RA	AG_MG_REGS_NAND_FLASH_REG(AG_MG_REGS_NAND_FLASH_DATAREG_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_NAND_FLASH_REGS_S
{
	ag_mg_regs_nand_flash_datareg_u	nand_flash_data_reg ;
	ag_mg_regs_nand_flash_cmdreg_u	nand_flash_cmdreg ;
	ag_mg_regs_nand_flash_index_u	nand_flash_index ;
	ag_mg_regs_nand_flash_status0_u	nand_flash_status0 ;
	ag_mg_regs_nand_flash_status1_u	nand_flash_status1 ;
	ag_mg_regs_nand_flash_id0_u	nand_flash_id0 ;
	ag_mg_regs_nand_flash_id1_u	nand_flash_id1 ;
	ag_mg_regs_nand_flash_id2_u	nand_flash_id2 ;
	ag_mg_regs_nand_flash_id3_u	nand_flash_id3 ;
	ag_mg_regs_nand_flash_id4_u	nand_flash_id4 ;
	ag_mg_regs_nand_flash_id5_u	nand_flash_id5 ;
	ag_mg_regs_nand_flash_id6_u	nand_flash_id6 ;
	ag_mg_regs_nand_flash_id7_u	nand_flash_id7 ;
	ag_mg_regs_nand_flash_inten_u	nand_flash_inten ;
	ag_mg_regs_nand_flash_intstat_u	nand_flash_intstat ;
	ag_mg_regs_nand_flash_intreg_u	nand_flash_intreg ;
	ag_mg_regs_nand_flash_exindex_u	nand_flash_exindex ;
	ag_mg_regs_nand_flash_timctl0_u	nand_flash_timctl0 ;
	ag_mg_regs_nand_flash_timctl1_u	nand_flash_timctl1 ;
	ag_mg_regs_nand_flash_config_u	nand_flash_config ;
	ag_mg_regs_nand_flash_pecc_u	nand_flash_pecc ;
} ag_mg_regs_nand_flash_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_nand_flash_reg_s *nand_flash_regs =
*       (volatile ag_mg_regs_nand_flash_reg_s *)AG_MG_REGS_NAND_FLASH_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_nand_flash.h,v $
Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

