/* $Id: ag_mg_regs_dcc.h,v 1.1 2012/04/18 18:08:25 srane Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/sp27dsp/dss/inc/ag_mg_regs_dcc.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_dcc.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
* ag_mg_regs_dss_dcc.h
*
* Copyright (c) 2010 LSI Inc.  All Rights Reserved
*
* This is unpublished proprietary information of LSI Inc.
* This copyright notice does not evidence publication.
*
* The use of the software, documentation, methodologies, and other information
* contained herein is governed solely by the associated license agreements.
* Any inconsistent use shall be deemed to be a misappropriation of the
* intellectual property of LSI Inc. and treated accordingly.
*
* This file defines DSS Subsystem (DSS) Data Cache Control (DCC) registers.
*
* Register addresses defined herein are for
*  code running on the DSS accessing its own DCC.
*
* See "Physical register addresses" below for macros
* used to generate addresses for specific registers.
*
* Registers defined in this file :
 *  DCC_CTRL
 *  DCC_STAT
 *  DCC_ATTR
 *  DCC_DIRECT_START
 *  DCC_DIRECT_END
 *  DCC_FLUSH_START
 *  DCC_FLUSH_END
 *  DCC_EVAC_ADDR
 *  DCC_SEG0
 *  DCC_SEG1
 *  DCC_SEG2
 *  DCC_SEG3
 *  DCC_SEG_CMD
 *  DCC_FBUS
*
* Prefix naming conventions :
*   AG_MG_REGS_XXX_RA : register/memory physical address
*   AG_MG_REGS_XXX_RO : register/memory address offset
*   AG_MG_REGS_XXX_RM : register mask
*   AG_MG_REGS_XXX_BO : bit/field offset from LSB
*   AG_MG_REGS_XXX_BM : bit/field mask
*   AG_MG_REGS_XXX_U  : bitfields in C union typedef
*   AG_MG_REGS_XXX_S  : registers in C struct typedef
*   LSI_SP25XX_XX_RPT : number of identical registers in array
*   LSI_SP25XX_XX_IVL : interval between registers in array
*
* NOTE: user may redefine ag_mg_regs_register
*       in ag_mg_regs_regops.h if necessary
* NOTE: access mode of individual bit fields matches that
*       of containing register unless indicated otherwise
*/

#ifndef AG_MG_REGS_DSS_DCC_REGISTERS_H
#define AG_MG_REGS_DSS_DCC_REGISTERS_H

#include "ag_mg_regs_regops.h"


/* 
 * Generated by HSI Designer release 2.3.5.
 */


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DCC_CTRL_RO                     0x00000000
#define AG_MG_REGS_DCC_CTRL_RM                     0xCC39CC39

#define AG_MG_REGS_DCC_CTRL_CACHE_EN_BO            0
#define AG_MG_REGS_DCC_CTRL_CACHE_EN_BM            0x00000001

#define AG_MG_REGS_DCC_CTRL_PRFL_EN_BO             3
#define AG_MG_REGS_DCC_CTRL_PRFL_EN_BM             0x00000008

#define AG_MG_REGS_DCC_CTRL_DBG_MD_BO              4
#define AG_MG_REGS_DCC_CTRL_DBG_MD_BM              0x00000010

#define AG_MG_REGS_DCC_CTRL_CNCL_EN_BO             5
#define AG_MG_REGS_DCC_CTRL_CNCL_EN_BM             0x00000020

#define AG_MG_REGS_DCC_CTRL_DR_RD_ERR_EN_BO        10
#define AG_MG_REGS_DCC_CTRL_DR_RD_ERR_EN_BM        0x00000400

#define AG_MG_REGS_DCC_CTRL_DR_WR_ERR_EN_BO        11
#define AG_MG_REGS_DCC_CTRL_DR_WR_ERR_EN_BM        0x00000800

#define AG_MG_REGS_DCC_CTRL_SEG_ERR_EN_BO          14
#define AG_MG_REGS_DCC_CTRL_SEG_ERR_EN_BM          0x00004000

#define AG_MG_REGS_DCC_CTRL_WR_RESP_ERR_EN_BO      15
#define AG_MG_REGS_DCC_CTRL_WR_RESP_ERR_EN_BM      0x00008000

#define AG_MG_REGS_DCC_CTRL_CACHE_EN_MSK_BO        16
#define AG_MG_REGS_DCC_CTRL_CACHE_EN_MSK_BM        0x00010000

#define AG_MG_REGS_DCC_CTRL_PRFL_EN_MSK_BO         19
#define AG_MG_REGS_DCC_CTRL_PRFL_EN_MSK_BM         0x00080000

#define AG_MG_REGS_DCC_CTRL_DBG_MD_MSK_BO          20
#define AG_MG_REGS_DCC_CTRL_DBG_MD_MSK_BM          0x00100000

#define AG_MG_REGS_DCC_CTRL_CNCL_EN_MSK_BO         21
#define AG_MG_REGS_DCC_CTRL_CNCL_EN_MSK_BM         0x00200000

#define AG_MG_REGS_DCC_CTRL_DR_RD_ERR_EN_MSK_BO    26
#define AG_MG_REGS_DCC_CTRL_DR_RD_ERR_EN_MSK_BM    0x04000000

#define AG_MG_REGS_DCC_CTRL_DR_WR_ERR_EN_MSK_BO    27
#define AG_MG_REGS_DCC_CTRL_DR_WR_ERR_EN_MSK_BM    0x08000000

#define AG_MG_REGS_DCC_CTRL_SEG_ERR_EN_MSK_BO      30
#define AG_MG_REGS_DCC_CTRL_SEG_ERR_EN_MSK_BM      0x40000000

#define AG_MG_REGS_DCC_CTRL_WR_RESP_ERR_MSK_BO     31
#define AG_MG_REGS_DCC_CTRL_WR_RESP_ERR_MSK_BM     0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            cache_en : 1,
            fill5 : 2,
            prfl_en : 1,
            dbg_md : 1,
            cncl_en : 1,
            fill4 : 4,
            dr_rd_err_en : 1,
            dr_wr_err_en : 1,
            fill3 : 2,
            seg_err_en : 1,
            wr_resp_err_en : 1,
            cache_en_msk : 1,
            fill2 : 2,
            prfl_en_msk : 1,
            dbg_md_msk : 1,
            cncl_en_msk : 1,
            fill1 : 4,
            dr_rd_err_en_msk : 1,
            dr_wr_err_en_msk : 1,
            fill0 : 2,
            seg_err_en_msk : 1,
            wr_resp_err_msk : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_ctrl_u;
#endif


/* 
 * DCC_STAT (DCC Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DCC_STAT_RO                     0x00000020
#define AG_MG_REGS_DCC_STAT_RM                     0x01BF0300

#define AG_MG_REGS_DCC_STAT_DR_RD_ERR_BO           8
#define AG_MG_REGS_DCC_STAT_DR_RD_ERR_BM           0x00000100

#define AG_MG_REGS_DCC_STAT_DR_WR_ERR_BO           9
#define AG_MG_REGS_DCC_STAT_DR_WR_ERR_BM           0x00000200

#define AG_MG_REGS_DCC_STAT_FLINV_LN_BO            16
#define AG_MG_REGS_DCC_STAT_FLINV_LN_BM            0x00010000

#define AG_MG_REGS_DCC_STAT_FLINV_RNG_BO           17
#define AG_MG_REGS_DCC_STAT_FLINV_RNG_BM           0x00020000

#define AG_MG_REGS_DCC_STAT_FLINV_FUL_BO           18
#define AG_MG_REGS_DCC_STAT_FLINV_FUL_BM           0x00040000

#define AG_MG_REGS_DCC_STAT_BUSY_BO                19
#define AG_MG_REGS_DCC_STAT_BUSY_BM                0x00080000

#define AG_MG_REGS_DCC_STAT_EVAC_DBL_ERR_BO        20
#define AG_MG_REGS_DCC_STAT_EVAC_DBL_ERR_BM        0x00100000

#define AG_MG_REGS_DCC_STAT_EVAC_OVR_ERR_BO        21
#define AG_MG_REGS_DCC_STAT_EVAC_OVR_ERR_BM        0x00200000

#define AG_MG_REGS_DCC_STAT_SEG_ERR_BO             23
#define AG_MG_REGS_DCC_STAT_SEG_ERR_BM             0x00800000

#define AG_MG_REGS_DCC_STAT_WR_RESP_ERR_BO         24
#define AG_MG_REGS_DCC_STAT_WR_RESP_ERR_BM         0x01000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_STAT_U
{
    struct
    {
        ag_mg_regs_register
            fill3 : 8,
            dr_rd_err : 1,
            dr_wr_err : 1,
            fill2 : 6,
            flinv_ln : 1,
            flinv_rng : 1,
            flinv_ful : 1,
            busy : 1,
            evac_dbl_err : 1,
            evac_ovr_err : 1,
            fill1 : 1,
            seg_err : 1,
            wr_resp_err : 1,
            fill0 : 7;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_stat_u;
#endif


/* 
 * DCC_ATTR (DCC Attributes Register)
 * Initialization value: 0x02001124  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DCC_ATTR_RO                     0x00000040
#define AG_MG_REGS_DCC_ATTR_RM                     0x0F003FFF

#define AG_MG_REGS_DCC_ATTR_CACHE_SIZE_BO          0
#define AG_MG_REGS_DCC_ATTR_CACHE_SIZE_BM          0x0000000F

#define AG_MG_REGS_DCC_ATTR_WAYS_BO                4
#define AG_MG_REGS_DCC_ATTR_WAYS_BM                0x00000070

#define AG_MG_REGS_DCC_ATTR_LN_WIDTH_BO            7
#define AG_MG_REGS_DCC_ATTR_LN_WIDTH_BM            0x00000780

#define AG_MG_REGS_DCC_ATTR_DC_WIDTH_BO            11
#define AG_MG_REGS_DCC_ATTR_DC_WIDTH_BM            0x00003800

#define AG_MG_REGS_DCC_ATTR_REV_BO                 24
#define AG_MG_REGS_DCC_ATTR_REV_BM                 0x0F000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_ATTR_U
{
    struct
    {
        ag_mg_regs_register
            cache_size : 4,
            ways : 3,
            ln_width : 4,
            dc_width : 3,
            fill1 : 10,
            rev : 4,
            fill0 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_attr_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DCC_DIRECT_START_RO             0x00000060
#define AG_MG_REGS_DCC_DIRECT_START_RM             0xFFFFFFF1

#define AG_MG_REGS_DCC_DIRECT_START_EN_BO          0
#define AG_MG_REGS_DCC_DIRECT_START_EN_BM          0x00000001

#define AG_MG_REGS_DCC_DIRECT_START_AXI_ATTR_BO    4
#define AG_MG_REGS_DCC_DIRECT_START_AXI_ATTR_BM    0x000000F0

#define AG_MG_REGS_DCC_DIRECT_START_ADDR_BO        8
#define AG_MG_REGS_DCC_DIRECT_START_ADDR_BM        0xFFFFFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_DIRECT_START_U
{
    struct
    {
        ag_mg_regs_register
            en : 1,
            fill0 : 3,
            axi_attr : 4,
            addr : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_direct_start_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DCC_DIRECT_END_RO               0x00000080
#define AG_MG_REGS_DCC_DIRECT_END_RM               0xFFFFFF00

#define AG_MG_REGS_DCC_DIRECT_END_ADDR_BO          8
#define AG_MG_REGS_DCC_DIRECT_END_ADDR_BM          0xFFFFFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_DIRECT_END_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 8,
            addr : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_direct_end_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DCC_FLUSH_START_RO              0x000000A0
#define AG_MG_REGS_DCC_FLUSH_START_RM              0xFFFFFF8F

#define AG_MG_REGS_DCC_FLUSH_START_SCOPE_BO        0
#define AG_MG_REGS_DCC_FLUSH_START_SCOPE_BM        0x00000003

#define AG_MG_REGS_DCC_FLUSH_START_TYPE_BO         2
#define AG_MG_REGS_DCC_FLUSH_START_TYPE_BM         0x0000000C

#define AG_MG_REGS_DCC_FLUSH_START_ADDR_BO         7
#define AG_MG_REGS_DCC_FLUSH_START_ADDR_BM         0xFFFFFF80

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_FLUSH_START_U
{
    struct
    {
        ag_mg_regs_register
            scope : 2,
            type : 2,
            fill0 : 3,
            addr : 25;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_flush_start_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DCC_FLUSH_END_RO                0x000000C0
#define AG_MG_REGS_DCC_FLUSH_END_RM                0xFFFFFF80

#define AG_MG_REGS_DCC_FLUSH_END_ADDR_BO           7
#define AG_MG_REGS_DCC_FLUSH_END_ADDR_BM           0xFFFFFF80

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_FLUSH_END_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 7,
            addr : 25;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_flush_end_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DCC_EVAC_ADDR_RO                0x000000E0
#define AG_MG_REGS_DCC_EVAC_ADDR_RM                0xFFFFFF80

#define AG_MG_REGS_DCC_EVAC_ADDR_ADDR_BO           7
#define AG_MG_REGS_DCC_EVAC_ADDR_ADDR_BM           0xFFFFFF80

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_EVAC_ADDR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 7,
            addr : 25;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_evac_addr_u;
#endif


/* 
 * Initialization value: 0x00000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DCC_SEG0_RO                     0x00000400
#define AG_MG_REGS_DCC_SEG0_RM                     0xFFC00001

#define AG_MG_REGS_DCC_SEG0_FIX_BO                 0
#define AG_MG_REGS_DCC_SEG0_FIX_BM                 0x00000001

#define AG_MG_REGS_DCC_SEG0_ADDR_BO                22
#define AG_MG_REGS_DCC_SEG0_ADDR_BM                0xFFC00000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_SEG0_U
{
    struct
    {
        ag_mg_regs_register
            fix : 1,
            fill0 : 21,
            addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_seg0_u;
#endif


/* 
 * Initialization value: 0x00400001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DCC_SEG1_RO                     0x00000420
#define AG_MG_REGS_DCC_SEG1_RM                     0xFFC00001

#define AG_MG_REGS_DCC_SEG1_FIX_BO                 0
#define AG_MG_REGS_DCC_SEG1_FIX_BM                 0x00000001

#define AG_MG_REGS_DCC_SEG1_ADDR_BO                22
#define AG_MG_REGS_DCC_SEG1_ADDR_BM                0xFFC00000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_SEG1_U
{
    struct
    {
        ag_mg_regs_register
            fix : 1,
            fill0 : 21,
            addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_seg1_u;
#endif


/* 
 * Initialization value: 0x20000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DCC_SEG2_RO                     0x00000440
#define AG_MG_REGS_DCC_SEG2_RM                     0xFFC00001

#define AG_MG_REGS_DCC_SEG2_FIX_BO                 0
#define AG_MG_REGS_DCC_SEG2_FIX_BM                 0x00000001

#define AG_MG_REGS_DCC_SEG2_ADDR_BO                22
#define AG_MG_REGS_DCC_SEG2_ADDR_BM                0xFFC00000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_SEG2_U
{
    struct
    {
        ag_mg_regs_register
            fix : 1,
            fill0 : 21,
            addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_seg2_u;
#endif


/* 
 * Initialization value: 0x20400000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DCC_SEG3_RO                     0x00000460
#define AG_MG_REGS_DCC_SEG3_RM                     0xFFC00001

#define AG_MG_REGS_DCC_SEG3_FIX_BO                 0
#define AG_MG_REGS_DCC_SEG3_FIX_BM                 0x00000001

#define AG_MG_REGS_DCC_SEG3_ADDR_BO                22
#define AG_MG_REGS_DCC_SEG3_ADDR_BM                0xFFC00000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_SEG3_U
{
    struct
    {
        ag_mg_regs_register
            fix : 1,
            fill0 : 21,
            addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_seg3_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_DCC_SEG_CMD_RO                  0x00000500
#define AG_MG_REGS_DCC_SEG_CMD_RM                  0xFFC00139

#define AG_MG_REGS_DCC_SEG_CMD_FIX_BO              0
#define AG_MG_REGS_DCC_SEG_CMD_FIX_BM              0x00000001

#define AG_MG_REGS_DCC_SEG_CMD_SEG_ABS_BO          3
#define AG_MG_REGS_DCC_SEG_CMD_SEG_ABS_BM          0x00000008

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_SEG_CMD_U
{
    struct
    {
        ag_mg_regs_register
            fix : 1,
            fill0 : 2,
	    seg_abs : 1,
	    seg_num : 2,
	    fill1 : 2,
	    unfix_all : 1,
            fill2 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_seg_cmd_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DCC_FBUS_RO                  0x00000600
#define AG_MG_REGS_DCC_FBUS_RM                  0x00000001

#define AG_MG_REGS_DCC_FBUS_SYSMEM_BO           0
#define AG_MG_REGS_DCC_FBUS_SYSMEM_BM           0x00000001


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DCC_FBUS_U
{
    struct
    {
        ag_mg_regs_register
            sysmem : 1,
            fill : 31 ;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dcc_fbus_u;
#endif

/*
 * Physical register addresses (for dss accessing dcc)
 */
#define AG_MG_REGS_DCC_BASE		0x90200000
#define AG_MG_REGS_DCC_REG(ro)		(AG_MG_REGS_DCC_BASE+(ro))
 
#define AG_MG_REGS_DCC_CTRL_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_CTRL_RO)
#define AG_MG_REGS_DCC_STAT_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_STAT_RO)
#define AG_MG_REGS_DCC_ATTR_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_ATTR_RO)
#define AG_MG_REGS_DCC_DIRECT_START_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_DIRECT_START_RO)
#define AG_MG_REGS_DCC_DIRECT_END_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_DIRECT_END_RO)
#define AG_MG_REGS_DCC_FLUSH_START_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_FLUSH_START_RO)
#define AG_MG_REGS_DCC_FLUSH_END_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_FLUSH_END_RO)
#define AG_MG_REGS_DCC_EVAC_ADDR_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_EVAC_ADDR_RO)
#define AG_MG_REGS_DCC_SEG0_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_SEG0_RO)
#define AG_MG_REGS_DCC_SEG1_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_SEG1_RO)
#define AG_MG_REGS_DCC_SEG2_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_SEG2_RO)
#define AG_MG_REGS_DCC_SEG3_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_SEG3_RO)
#define AG_MG_REGS_DCC_SEG_CMD_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_SEG_CMD_RO)
#define AG_MG_REGS_DCC_FBUS_RA	AG_MG_REGS_DCC_REG(AG_MG_REGS_DCC_FBUS_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_DCC_REGS_S
{
	ag_mg_regs_dcc_ctrl_u		dcc_ctrl ;
	ag_mg_regs_register		fill0[7] ;
	ag_mg_regs_dcc_stat_u		dcc_stat ;
	ag_mg_regs_register		fill1[7] ;
	ag_mg_regs_dcc_attr_u		dcc_attr ;
	ag_mg_regs_register		fill2[7] ;
	ag_mg_regs_dcc_direct_start_u	dcc_direct_start ;
	ag_mg_regs_register		fill3[7] ;
	ag_mg_regs_dcc_direct_end_u	dcc_direct_end ;
	ag_mg_regs_register		fill4[7] ;
	ag_mg_regs_dcc_flush_start_u	dcc_flush_start ;
	ag_mg_regs_register		fill5[7] ;
	ag_mg_regs_dcc_flush_end_u	dcc_flush_end ;
	ag_mg_regs_register		fill6[7] ;
	ag_mg_regs_dcc_evac_addr_u	dcc_evac_addr ;
	ag_mg_regs_register		fill7[199] ;
	ag_mg_regs_dcc_seg0_u		dcc_seg0 ;
	ag_mg_regs_register		fill8[7] ;
	ag_mg_regs_dcc_seg1_u		dcc_seg1 ;
	ag_mg_regs_register		fill9[7] ;
	ag_mg_regs_dcc_seg2_u		dcc_seg2 ;
	ag_mg_regs_register		fill10[7] ;
	ag_mg_regs_dcc_seg3_u		dcc_seg3 ;
	ag_mg_regs_register		fill11[39] ;
	ag_mg_regs_dcc_seg_cmd_u	dcc_seg_cmd ;
	ag_mg_regs_register		fill12[63] ;
	ag_mg_regs_dcc_fbus_u		dcc_fbus ;
} ag_mg_regs_dcc_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_dcc_reg_s *dcc_regs =
*       (volatile ag_mg_regs_dcc_reg_s *)AG_MG_REGS_DCC_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_dcc.h,v $
Revision 1.1  2012/04/18 18:08:25  srane
Initial checkin


$Endlog$
*/

