/* $Id: ag_mg_regs_ltc.h,v 1.1 2012/04/18 18:08:26 srane Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/sp27dsp/dss/inc/ag_mg_regs_ltc.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_ltc.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_dss_ltc.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of Agere Systems Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * The DSS contains a 512-KB level 2 cache (LTC) controller & a master interface
 * to the DBM for system-level access. The LTC accesses the DDR3 external memory
 * interface to reduce the access times to memory and to increase performance.
 * 
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *
 *  LTC_CTRL
 *  LTC_STAT
 *  LTC_INVAL_START
 *  LTC_INVAL_END
 *
 * Prefix naming conventions :
 *   AG_MG_REGS_XXX_RA : register/memory physical address
 *   AG_MG_REGS_XXX_RO : register/memory address offset
 *   AG_MG_REGS_XXX_RM : register mask
 *   AG_MG_REGS_XXX_BO : bit/field offset from LSB
 *   AG_MG_REGS_XXX_BM : bit/field mask
 *   AG_MG_REGS_XXX_U  : bitfields in C union typedef
 *   AG_MG_REGS_XXX_S  : registers in C struct typedef
 *   AG_MG_REGS_XX_RPT : number of identical registers in array
 *   AG_MG_REGS_XX_IVL : interval between registers in array
 *
 * NOTE: user may redefine ag_mg_regs_register
 *       in ag_mg_regs_regops.h if necessary
 * NOTE: access mode of individual bit fields matches that
 *       of containing register unless indicated otherwise
 */

#ifndef AG_MG_REGS_ltc_REGISTERS_H
#define AG_MG_REGS_ltc_REGISTERS_H

#include "ag_mg_regs_regops.h"

#define AG_MG_REGS_V1P1

/* 
 * Generated by HSI Designer release 2.3.5.
 */
/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LTC_CTRL_RO        			0
#define AG_MG_REGS_LTC_CTRL_BM        			0x009F009F

/* V1.1 only */
#define AG_MG_REGS_LTC_CTRL_ECC_SKIP_MSK_BM		0x00800000
#define AG_MG_REGS_LTC_CTRL_ECC_SKIP_MSK_BO		23

#define AG_MG_REGS_LTC_CTRL_DBG_MD_MSK_BM       0x00100000
#define AG_MG_REGS_LTC_CTRL_DBG_MD_MSK_BO       20

#define AG_MG_REGS_LTC_CTRL_PRFL_EN_MSK_BM      0x00080000
#define AG_MG_REGS_LTC_CTRL_PRFL_EN_MSK_BO      19

/* V1.1 only */
#define AG_MG_REGS_LTC_CTRL_DCC_FA_EN_MSK_BM	0x00040000
#define AG_MG_REGS_LTC_CTRL_DCC_FA_EN_MSK_BO	18

/* V1.1 only */
#define AG_MG_REGS_LTC_CTRL_PCC_FA_EN_MSK_BM	0x00020000
#define AG_MG_REGS_LTC_CTRL_PCC_FA_EN_MSK_BO	17

#define AG_MG_REGS_LTC_CTRL_CACHE_EN_MSK_BM     0x00010000
#define AG_MG_REGS_LTC_CTRL_CACHE_EN_MSK_BO     16

/* V1.1 only */
#define AG_MG_REGS_LTC_CTRL_ECC_SKIP_BM			0x00000080
#define AG_MG_REGS_LTC_CTRL_ECC_SKIP_BO			7

#define AG_MG_REGS_LTC_CTRL_DBG_MD_BM           0x00000010
#define AG_MG_REGS_LTC_CTRL_DBG_MD_BO           4

#define AG_MG_REGS_LTC_CTRL_PRFL_EN_BM          0x00000008
#define AG_MG_REGS_LTC_CTRL_PRFL_EN_BO          3

/* V1.1 only */
#define AG_MG_REGS_LTC_CTRL_DCC_FA_EN_BM		0x00000004
#define AG_MG_REGS_LTC_CTRL_DCC_FA_EN_BO		2

/* V1.1 only */
#define AG_MG_REGS_LTC_CTRL_PCC_FA_EN_BM		0x00020002
#define AG_MG_REGS_LTC_CTRL_PCC_FA_EN_BO		1

#define AG_MG_REGS_LTC_CTRL_CACHE_EN_BM         0x00000001
#define AG_MG_REGS_LTC_CTRL_CACHE_EN_BO         0

#ifdef AG_MG_REGS_USE_C_STRUCTURES

typedef union AG_MG_REGS_LTC_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            cache_en : 1,
            pcc_fa_en : 1,		/* V1.1 only */
            dcc_fa_en : 1,		/* V1.1 only */
            prfl_en : 1,
            fill1 : 12,
            cache_en_msk : 1,
            pcc_fa_en_msk : 1,	/* V1.1 only */
            dcc_fa_en_msk : 1,	/* V1.1 only */
            prfl_en_msk : 1,
            fill2 : 12;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ltc_ctrl_u;

#endif

/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LTC_STAT_RO     				0x00000020
#define AG_MG_REGS_LTC_STAT_BM         			0x000E1C00

#define AG_MG_REGS_LTC_STAT_BUSY_BM             0x00080000
#define AG_MG_REGS_LTC_STAT_BUSY_BO             19

#define AG_MG_REGS_LTC_STAT_INV_FUL_BM          0x00040000
#define AG_MG_REGS_LTC_STAT_INV_FUL_BO          18

#define AG_MG_REGS_LTC_STAT_INV_RANGE_BM        0x00020000
#define AG_MG_REGS_LTC_STAT_INV_RANGE_BO        17

#define AG_MG_REGS_LTC_STAT_BUS_ERR_WR_BM       0x00001000
#define AG_MG_REGS_LTC_STAT_BUS_ERR_WR_BO       12

#define AG_MG_REGS_LTC_STAT_BUS_ERR_BM          0x00000C00
#define AG_MG_REGS_LTC_STAT_BUS_ERR_BO          10

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_LTC_STAT_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 10,
            bus_err : 2,
            bus_err_wr : 1,
            inv_range : 1,
            fill1 : 4,
            inv_ful : 1,
            busy : 1,
            fill2 : 12;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ltc_stat_u;
#endif


/* V1.0 only
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LTC_INVAL_RO        			 0x000000A0
#define AG_MG_REGS_LTC_INVAL_BM        			 0x00000003

#define AG_MG_REGS_LTC_INVAL_SCOPE_BM            0x00000003
#define AG_MG_REGS_LTC_INVAL_SCOPE_BO            0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_LTC_INVAL_U
{
    struct
    {
        ag_mg_regs_register
            scope : 2,
            fill0 : 30;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ltc_inval_u;
#endif

/* V1.1 only
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LTC_INVAL_START_RO        0x000000A0
#define AG_MG_REGS_LTC_INVAL_START_BM        0xFFFFFC03

#define AG_MG_REGS_LTC_INVAL_START_ADDR_BM   0xFFFFFC00
#define AG_MG_REGS_LTC_INVAL_START_ADDR_BO   10

#define AG_MG_REGS_LTC_INVAL_START_SCOPE_BM  0x00000003
#define AG_MG_REGS_LTC_INVAL_START_SCOPE_BO  0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_LTC_INVAL_START_U
{
    struct
    {
        ag_mg_regs_register
            scope : 2,
            fill0 : 8,
            addr : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ltc_inval_start_u;
#endif

/* V1.1 only
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LTC_INVAL_END_RO        0x000000C0
#define AG_MG_REGS_LTC_INVAL_END_BM        0xFFFFFC03

#define AG_MG_REGS_LTC_INVAL_END_ADDR_BM   0xFFFFFC00
#define AG_MG_REGS_LTC_INVAL_END_ADDR_BO   10

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_LTC_INVAL_END_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 10,
            addr : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ltc_inval_end_u;
#endif

/*
* Physical register addresses (for DSS accessing LTC)
*/
#define AG_MG_REGS_LTC_BASE				0x90300000
#define AG_MG_REGS_LTC_REG(ro)			(AG_MG_REGS_LTC_BASE+(ro))

#define AG_MG_REGS_LTC_CTRL_RA			AG_MG_REGS_LTC_REG(AG_MG_REGS_LTC_CTRL_RO)
#define AG_MG_REGS_LTC_STAT_RA			AG_MG_REGS_LTC_REG(AG_MG_REGS_LTC_STAT_RO)

/* V1.0 only */
#define AG_MG_REGS_LTC_INVAL_RA			AG_MG_REGS_LTC_REG(AG_MG_REGS_LTC_INVAL_RO)
/* V1.1 only */
#define AG_MG_REGS_LTC_INVAL_START_RA	AG_MG_REGS_LTC_REG(AG_MG_REGS_LTC_INVAL_START_RO)
/* V1.1 only */
#define AG_MG_REGS_LTC_INVAL_END_RA		AG_MG_REGS_LTC_REG(AG_MG_REGS_LTC_INVAL_END_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES

typedef struct AG_MG_REGS_LTC_REGS_S
{
	ag_mg_regs_ltc_ctrl_u	ltc_ctrl;
	ag_mg_regs_register	FILL1[7];
	ag_mg_regs_ltc_stat_u	ltc_stat;
	ag_mg_regs_register	FILL2[31];
/* V1.1 only */
	ag_mg_regs_ltc_inval_start_u ltc_inval_start;
	ag_mg_regs_register	FILL3[7];
/* V1.1 only */
	ag_mg_regs_ltc_inval_end_u ltc_inval_end;
} ag_mg_regs_ltc_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_ltc_reg_s *ltc_regs =
*       (volatile ag_mg_regs_ltc_reg_s *)AG_MG_REGS_LTC_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_ltc.h,v $
Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

