#!/bin/sh
# $Id: version,v 1.3 2021/04/15 02:21:43 peteteng Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/katar/x86/version,v $
#------------------------------------------------------------------
# Version control file for xformers
#
# Copyright (c) 2016-2018 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.3  2021/04/15 02:21:43  peteteng
# V1.0.1 Release
#
# Revision 1.2  2019/06/14 05:24:52  mikech2
# Collapse katar-branch00 to Main Trunk
#
# Revision 1.1.2.10  2019/06/03 08:52:30  mikech2
# V0.0.11 Release
#
# Revision 1.1.2.9  2019/05/31 06:40:48  benlu
# V0.0.10 release
#
# Revision 1.1.2.8  2019/05/28 02:11:46  mikech2
# V0.0.9 Release
#
# Revision 1.1.2.7  2019/05/10 07:01:30  peteteng
# V0.0.8 Release
#
# Revision 1.1.2.6  2019/04/03 03:47:18  peteteng
# V0.0.7 Release
#
# Revision 1.1.2.5  2019/03/28 03:44:30  peteteng
# V0.0.6 Release
#
# Revision 1.1.2.4  2019/02/11 02:11:25  peteteng
# V0.0.5 Release
#
# Revision 1.1.2.3  2019/01/22 02:01:26  peteteng
# V0.0.4 Release
#
# Revision 1.1.2.2  2018/11/28 14:47:24  peteteng
# V0.0.3 Release
#
# Revision 1.1.2.1  2018/10/22 08:02:35  mikech2
# Move project folder to common/src/katar/x86
#
# Revision 1.1.2.4  2018/10/17 08:24:31  peteteng
# V0.0.2 Release
#
# Revision 1.1.2.3  2018/09/14 06:11:53  mikech2
# Add mem info to system info
#
# Revision 1.1.2.2  2018/09/12 08:32:48  mikech2
# Fix userlogic FPGA update & system info version issue
#
# Revision 1.1.2.1  2018/06/07 01:19:25  peteteng
# add project katar - based on neptune
#
#
#
#
# $Endlog$
#

MAJOR_VERSION=1
MINOR_VERSION=0
RELEASE=1
