#!/bin/sh
# $Id: version,v 1.49 2020/04/06 06:04:22 letsai Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/overlord/x86/version,v $
#------------------------------------------------------------------
# Version control file for xformers
#
# Copyright (c) 2013-2016 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.49  2020/04/06 06:04:22  letsai
# Bump version to 11.15.1
#
# Revision 1.48  2020/03/18 07:54:42  letsai
# Bump version to 11.15.0
#
# Revision 1.47  2019/08/26 03:39:32  alpeng
# bump to 11.14.1 - CSCvq64781
#
# Revision 1.46  2019/08/19 12:55:28  mingding
# CSCvk64124-39: bump version for release with supporting SM-Nightwatch
#
# Revision 1.45  2018/07/24 03:16:14  alpeng
# bump to v11.12.0 for supporting 10G-KR SM TC
#
# Revision 1.44  2017/09/29 03:14:24  harrchan
# Bump version to 11.11.3
#
# Revision 1.43  2017/08/16 02:59:43  harrchan
# Bump version to 11.11.2
#
# Revision 1.42  2017/06/19 01:28:54  olin2
# Bump version to 11.11.1
#
# Revision 1.41  2017/04/17 07:41:39  umlin
# Bump version to 11.11.0, new product Reva-SM supported in this release
#
# Revision 1.40  2017/03/23 03:43:44  haohsu
# Bump version to 11.11.0, support Kaziranga project
#
# Revision 1.39  2016/05/09 13:06:27  umlin
# Bump version to 11.9.0, new product Reva supported in this release
#
# Revision 1.38  2016/03/22 06:15:57  alpeng
# Bump version to 11.8.0, for F35 host side code update
#
# Revision 1.37  2016/01/21 02:50:58  olin2
# Bump version to 11.7.0
#
# Revision 1.36  2015/06/23 23:11:12  ptong
# Fixed PSU1 cookie util for O2. Bump O2 diag version to 11.6.1
#
# Revision 1.35  2015/06/05 06:14:07  alpeng
# bump to 11.6.0
#
# Revision 1.34  2015/05/26 08:36:24  steja
# Bump version to V11.5.0
#
# Revision 1.33  2015/05/15 00:54:40  hondwang
# bump to version 11.4.0
#
# Revision 1.32  2015/03/23 12:17:46  alpeng
# Bump version to 11.3.1
#
# Revision 1.31  2015/02/26 03:26:39  meho
# Bump version to 11.3
#
# Revision 1.30  2015/02/24 18:44:42  srane
# Bump version to 11.2
#
# Revision 1.29  2015/01/08 02:55:50  alpeng
# adjust allocable free memory size to 80%, bump to v11.1.1
#
# Revision 1.28  2014/12/12 23:10:41  ptong
# Add oct_remote_reset in oct_remote_memcheck. Bump version to 11.1.0
#
# Revision 1.27  2014/10/29 03:14:42  alpeng
# bump to version 11.0
#
# Revision 1.26  2014/09/17 13:40:08  jamlin
# Bump up the version.
#
# Revision 1.25  2014/09/10 04:27:24  alpeng
# bump to version 10.2
#
# Revision 1.24  2014/06/19 22:00:52  ptong
# Incorporated BCM sdk-6.4.1-EA2 for 10G-KR interface. New code works on O2, June, and non Greyhound USD regression
#
# Revision 1.23  2014/05/15 02:42:23  alpeng
# bump up version to 10.1
#
# Revision 1.22  2014/05/05 17:36:01  ptong
# Bump version to 10.0
#
# Revision 1.21  2014/04/03 14:10:39  alpeng
# Bump version 9.2
#
# Revision 1.20  2014/02/18 03:37:15  alpeng
# Bump to version 9.1
#
# Revision 1.19  2013/11/21 04:38:56  alpeng
# Bump version to 9.0
#
# Revision 1.18  2013/10/16 03:00:47  leschen
# Bump version to 8.3
#
# Revision 1.17  2013/10/11 01:04:42  leschen
# Bump version to 8.0.2
#
# Revision 1.16  2013/10/08 01:38:25  alpeng
# Bump version to 9.0
#
# Revision 1.15  2013/07/22 17:51:26  ptong
# Bump version to 8.2
#
# Revision 1.14  2013/05/23 20:52:02  ptong
# Bump version to 8.0
#
# Revision 1.13  2013/03/15 00:03:02  ptong
# Bump version to 7.1
#
# Revision 1.12  2013/02/28 23:14:08  ptong
# Bump version to 7.0
#
# Revision 1.11  2013/02/23 07:31:56  ptong
# Fixed the problem due to new ROMMON changed the PCIe bus numbering and bumped diag version to 6.3
#
# Revision 1.10  2013/01/26 00:29:36  ptong
# Bump version to 6.2
#
# Revision 1.9  2013/01/14 19:55:20  ptong
# Bump version to 6.1
#
# Revision 1.8  2012/12/21 02:15:12  ptong
# Bump version to 6.0
#
# Revision 1.7  2012/11/29 22:58:40  ptong
# Bump version to 5.0
#
# Revision 1.6  2012/11/05 23:56:23  ptong
# Bump version to 4.2
#
# Revision 1.5  2012/10/25 22:44:32  ptong
# Bump version to 4.1
#
# Revision 1.4  2012/10/18 06:06:47  ptong
# Bump version to 4.0
#
# Revision 1.3  2012/09/27 23:50:59  ptong
# Bump version to 3.1
#
# Revision 1.2  2012/09/18 23:56:26  ptong
# Bump major version to 3
#
# Revision 1.1  2012/08/07 23:53:57  mcharon
# add version file
#
#
# $Endlog$
#

MAJOR_VERSION=11
MINOR_VERSION=15
RELEASE=1
