#!/bin/sh
# $Id: version,v 1.11 2020/07/16 01:49:22 harrchan Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/viper/version,v $
#------------------------------------------------------------------
# Version control file for espn-turbo
#
# Copyright (c) 2018 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.11  2020/07/16 01:49:22  harrchan
# Bump version to 1.0.8
#
# Revision 1.10  2019/02/18 04:07:02  harrchan
# Bump version to 1.0.7
#
# Revision 1.9  2019/01/15 10:06:05  harrchan
# Bump version to 1.0.6
#
# Revision 1.8  2018/12/10 10:14:00  harrchan
# Bump version to 1.0.5
#
# Revision 1.7  2018/11/09 08:51:01  lucywang
# Bump up version to v1.0.4
#
# Revision 1.6  2018/09/21 03:41:53  harrchan
# Bump up version to v1.0.3
#
# Revision 1.5  2018/09/05 02:56:44  chieyang
# Update version file for Viper-J and Viper-Intel
#
# Revision 1.4  2018/08/31 04:02:03  lucywang
# Bump version to V1.0.1
#
# Revision 1.3  2018/08/14 02:08:30  harrchan
# Bump version to V1.0.0
#
# Revision 1.2  2018/08/06 02:31:52  harrchan
# Merge viper E2E to the main trunk (CSCvk28469)
#
# Revision 1.1.2.3  2018/05/29 07:38:09  harrchan
# Bump up version to v0.0.4
#
# Revision 1.1.2.2  2018/05/15 08:14:07  harrchan
# Bump up version to v0.0.3
#
# Revision 1.1.2.1  2018/02/27 08:06:53  harrchan
# Initial viper application code base
#
#
# $Endlog$
#

MAJOR_VERSION=1
MINOR_VERSION=0
RELEASE=8
