#!/bin/sh
# $Id: version,v 1.3 2015/07/14 06:26:51 xiaoyizh Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/wallander/version,v $
#------------------------------------------------------------------
# Version control file for Wallander
#
# Copyright (c) 2014-2015 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.3  2015/07/14 06:26:51  xiaoyizh
# Bump up Version.
#
# Revision 1.2  2015/03/16 05:54:52  xiaoyizh
# Bump up version.
#
# Revision 1.1  2015/02/26 07:18:30  xiaoyizh
# Initial check in for Wallander.
#
#
# $Endlog$
#

MAJOR_VERSION=1
MINOR_VERSION=2
RELEASE=0
