#!/bin/sh
#$Id: version,v 1.3 2021/06/02 02:56:22 alpeng Exp $
#$Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/hightower-mmwv/version,v $
#------------------------------------------------------------------
# Version control file for Hightower
#
# Copyright (c) 2019-2020 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------

MAJOR_VERSION=0
MINOR_VERSION=1
RELEASE=4

#********************************************************************
# $Log: version,v $
# Revision 1.3  2021/06/02 02:56:22  alpeng
# merge sears into trunk
#
# Revision 1.1.4.9  2021/03/08 04:42:11  tshanmug
# Chrysler version bump up V014
#
# Revision 1.1.4.8  2021/01/27 19:10:48  tshanmug
# Chrysler version bump-up V0.1.3
#
# Revision 1.1.4.7  2021/01/12 05:04:26  ksabzwar
# Bump up version to V0.1.2
#
# Revision 1.1.4.6  2020/10/20 02:49:32  alpeng
# bump to 0.1.1
#
# Revision 1.1.4.5  2020/09/18 07:45:07  alpeng
# bump to version 0.1.0
#
# Revision 1.1.4.4  2020/09/14 17:00:24  ksabzwar
# Bump up version to 0.0.7
#
# Revision 1.1.4.3  2020/08/27 08:16:53  alpeng
# fixed syntax error
#
# Revision 1.1.4.2  2020/08/27 07:19:33  alpeng
# apply cvs header
#
#
# $Endlog$
#

