#!/bin/sh
# $Id: version,v 1.5 2018/08/10 02:37:22 easochen Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/reva/sm/version,v $
#------------------------------------------------------------------
# Version control file for Reva-SM
#
# Copyright (c) 2016-2017 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.5  2018/08/10 02:37:22  easochen
# Reva-SM: Bump up version. V1.0.1
#
# Revision 1.4  2017/04/17 07:36:52  umlin
# Reva-SM: Bump up version. V1.0.0
#
# Revision 1.3  2017/03/20 09:45:34  umlin
# Reva-SM: Bump up version. V0.0.5
#
# Revision 1.2  2017/03/16 05:20:26  umlin
# Reva-SM: Commit Reva-SM module side diag codes to main trunk
#
# Revision 1.1.2.4  2017/02/17 10:29:05  umlin
# Reva-SM: Bump up version. V0.0.4
#
# Revision 1.1.2.3  2016/12/16 10:08:55  umlin
# Reva-SM: Bump up version. V0.0.3
#
# Revision 1.1.2.2  2016/12/08 10:22:57  umlin
# Reva-SM: Bump up version. V0.0.2
#
# Revision 1.1.2.1  2016/10/18 22:05:19  umlin
# Reva-SM: SM-Module side diag, refer to FPGA 24~63 ports memory mapping to add those async loopback test. Removed PPP loopback function because of FPGA PPP logic is removed due to FPGA resource constraint.
#
#
# $Endlog$
#

MAJOR_VERSION=1
MINOR_VERSION=0
RELEASE=1
