idf_component_register(
    SRCS
        "src/main.c"
        "src/diag_menu.c"
        "src/diag_runner.c"
        "src/hal/hal_i2c_helpers.c"
        "src/hal/hal_screen.c"
        "src/hal/hal_touch.c"
        "src/hal/hal_rtc.c"
        "src/hal/hal_imu.c"
        "src/hal/hal_power.c"
        "${PROJECT_DIR}/common/chips/screen_GC9A01/screen_GC9A01.c"
        "${PROJECT_DIR}/common/chips/touch_FT6336/touch_FT6336.c"
        "${PROJECT_DIR}/common/chips/rtc_BM8563/rtc_BM8563.c"
        "${PROJECT_DIR}/common/chips/imu_BMI270/imu_BMI270.c"
        "${PROJECT_DIR}/common/chips/power_AXP2101/power_AXP2101.c"

    INCLUDE_DIRS
        "include"
        "include/hal"
        "src/hal"
        "${PROJECT_DIR}/common/chips/screen_GC9A01"
        "${PROJECT_DIR}/common/chips/touch_FT6336"
        "${PROJECT_DIR}/common/chips/rtc_BM8563"
        "${PROJECT_DIR}/common/chips/imu_BMI270"
        "${PROJECT_DIR}/common/chips/power_AXP2101"

    REQUIRES
        esp_driver_uart
        esp_driver_gpio
        esp_driver_spi
        esp_driver_i2c
        esp_timer
        nvs_flash
        freertos
        esp_system
        log
)
