#!/bin/sh
# $Id: version,v 1.2 2021/09/24 01:21:08 harrchan Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/elixir/version,v $
#------------------------------------------------------------------
# Version control file for Elixir
#
# Copyright (c) 2019 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.2  2021/09/24 01:21:08  harrchan
# Collapse Elixir-branch to Main Trunk.
#
# Revision 1.1.2.8  2021/07/12 02:34:26  illiu
# Release Version V0.0.8
#
# Revision 1.1.2.7  2021/06/07 01:47:00  illiu
# Release Version V0.0.7
#
# Revision 1.1.2.6  2021/04/26 06:23:14  illiu
# Release Version V0.0.6
#
# Revision 1.1.2.5  2021/03/24 01:36:08  illiu
# Release Version V0.0.5
#
# Revision 1.1.2.4  2021/03/04 06:20:43  illiu
# Release Version V0.0.4
#
# Revision 1.1.2.3  2021/01/07 06:27:32  illiu
# Release Version V0.0.3
#
# Revision 1.1.2.2  2020/11/19 09:53:21  illiu
# Release Version V0.0.3
#
# $Endlog$
#

MAJOR_VERSION=1
MINOR_VERSION=0
RELEASE=0
