#!/bin/sh
# $Id: version,v 1.24 2021/08/20 01:33:59 xiaolaya Exp $
# $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/common/src/overlord/neptune/curie_1RU/version,v $
#------------------------------------------------------------------
# Version control file for xformers
#
# Copyright (c) 2016-2018 by cisco Systems, Inc.
# All rights reserved.
#
#------------------------------------------------------------------
# $Log: version,v $
# Revision 1.24  2021/08/20 01:33:59  xiaolaya
# Bump version to V2.13.3
#
# Revision 1.23  2021/08/05 08:14:01  xiaolaya
# Bump version to V2.13.2
#
# Revision 1.22  2021/07/15 02:21:32  chenglso
# *** empty log message ***
#
# Revision 1.21  2021/06/04 17:29:55  tshanmug
# bump up version for curie1RU (v2.13.0) and Curie2ru (V1.11.0)
#
# Revision 1.20  2021/06/04 01:10:33  xiaolaya
# Bump version to 2.12.1
#
# Revision 1.19  2021/06/02 02:56:25  alpeng
# merge sears into trunk
#
# Revision 1.18  2021/04/20 06:53:17  xiaolaya
# Bump version to V2.12.0
#
# Revision 1.17  2021/03/31 10:20:49  xiaolaya
# Add M2 Testcard support
#
# Revision 1.16  2021/02/24 03:46:34  xiaolaya
# Fix bug for Switzer-Carrier SM Daughter NIM Daughter VM cookie
#
# Revision 1.15  2021/01/14 02:16:02  xiaolaya
# Bump version to V2.9.0
#
# Revision 1.14  2020/12/29 03:09:43  alpeng
# refine fan test; bump version to 2.8
#
# Revision 1.13  2020/11/03 06:25:36  leschen
# Bump up version to V2.7.0
#
# Revision 1.12  2020/09/14 03:21:52  qingcwan
# Bump curie1ru version.
#
# Revision 1.11.10.2  2021/03/02 01:04:20  tshanmug
# Sears diag rel version change
#
# Revision 1.11.10.1  2020/12/02 03:57:22  tshanmug
# Sears Antenna test updated
#
# Revision 1.11  2020/06/10 07:47:43  leschen
# Bump up version to V2.5.0
#
# Revision 1.10  2020/05/22 06:27:37  qingcwan
# Bump version to 2.4.0
#
# Revision 1.9  2020/04/06 06:06:07  letsai
# Bump version to 2.3.1
#
# Revision 1.8  2020/03/18 07:56:50  letsai
# Bump version to 2.3.0
#
# Revision 1.7  2020/01/31 07:19:13  leschen
# Bump up version to V2.2.1 for CERT RDT
#
# Revision 1.6  2020/01/03 06:26:14  alpeng
# bumpt to v2.1.0
#
# Revision 1.5  2019/12/21 00:52:38  ptong
# Curie PID change to C8300-1N1S-4T2X and C8300-1N1S-6G
#
# Revision 1.4  2019/12/18 09:18:37  alpeng
# 1. support quack cookie rd/wr; 2. fixed new rommon break nightwatch issue; 3. a workaround for new pim testcard crashed system issue; 4. bump to v2.0.1 for curie
#
# Revision 1.3  2019/08/12 02:21:31  alpeng
# bump to v2.0.0
#
# Revision 1.2  2019/08/06 06:56:15  alpeng
# merge curie, switzer and nightwatch to trunk
#
# Revision 1.1.2.20  2019/07/11 09:12:50  sherliu2
# Bump up version to V1.3.7
#
# Revision 1.1.2.19  2019/06/14 19:09:40  ptong
# Release curie1ru_diag V1.3.6
#
# Revision 1.1.2.18  2019/04/26 03:05:41  alpeng
# Bump up version to V1.3.5
#
# Revision 1.1.2.17  2019/04/19 09:46:34  alpeng
# Bump up version to V1.3.4
#
# Revision 1.1.2.16  2019/04/10 01:12:08  leschen
# Bump up version to V1.3.3
#
# Revision 1.1.2.15  2019/04/09 01:26:50  leschen
# Bump up version to V1.3.2 for Curie P2B
#
# Revision 1.1.2.14  2019/03/27 01:13:51  ptong
# Release curie 1ru V1.3.1 : Separate motheboard PCIe and M.2 NVMe care PCIe scan tests. Use /dev/m2usb for M.2 USB module according to kernel change. Check FPGA M.2 module bits correctly to support M.2 slot test
#
# Revision 1.1.2.13  2019/03/22 01:11:02  ptong
# Release version 1.3.0 for P2B build
#
# Revision 1.1.2.12  2019/02/16 02:39:36  ptong
# Bump version to 1.2.5 for P2A build
#
# Revision 1.1.2.11  2019/02/01 01:13:45  alpeng
# bump to 1.2.4
#
# Revision 1.1.2.10  2019/01/18 02:47:38  alpeng
# bump to ver 1.2.2
#
# Revision 1.1.2.9  2018/12/14 22:35:38  ptong
# Bump version to 1.2.1
#
# Revision 1.1.2.8  2018/12/05 02:06:05  alpeng
# update previous info which is 1.2.0
#
# Revision 1.1.2.7  2018/12/05 01:58:53  alpeng
# Bump version to V1.2.0 for curie 1ru p1c mfg use
#
# Revision 1.1.2.6  2018/11/09 20:53:51  ptong
# Bump version to V1.1.0 for curie 1ru edvt to use
#
# Revision 1.1.2.5  2018/10/10 21:48:17  ptong
# Bump version to V1.0.0 for P1B build
#
# Revision 1.1.2.4  2018/09/13 23:33:03  ptong
# Bump version to V0.1.1
#
# Revision 1.1.2.3  2018/09/12 23:33:32  ptong
# Release curie1ru diag V0.1.0
#
# Revision 1.1.2.2  2018/08/10 20:13:10  ptong
# Init version to 0.0.0
#
# $Endlog$
#

MAJOR_VERSION=2
MINOR_VERSION=13
RELEASE=3
