/* $Id: ag_mg_regs_txd.h,v 1.2 2017/07/28 07:58:35 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_txd.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_txd.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_txd.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of LSI Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * The Packet Processor Block (PPB) contains two each of these blocks:
 * Packet Classification Engine (PCE), Transmit Direct Memory Access (TXD),
 * and Gigabit Ethernet Media Access Control (MAC). One PCE is attached to
 * the receive side of a MAC and one TXD is connected to the transmit side
 * of a MAC. The MAC transmits/receives packet traffic via SGMII. The PCE
 * receives the packets from the MAC, sorts them and sends them to the
 * appropriate destination via a programmable DMA engine. The TXD grabs data
 * from the source and loads it into the MAC which transmits the data off chip.
 *
 * Register addresses and contents defined in this file are for code running
 * on the ARM accessing one of the TXDs in the PPB via the APB bus that is
 * connected to the PPB AXI Bus Matrix by the AXI2APB bridge.
 *
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *  TXD_START
 *  TXD_CONFIG
 *  TXD_STATUS
 *  TXD_BLEN
 *  TXD_FIFOWM
 *  TXD_TRFWM
 *  TXD_EINTTEST
 *  TXD_FINTMASK
 *  TXD_FINTTEST
 *  TXD_BDTSCNT
 *  TXD_BDTECNT
 *  TXD_BDTUCNT
 *  TXD_FIFORD0
 *  TXD_FIFORD1
 *  TXD_CTLRD
 *  TXD_TRFRD0
 *  TXD_TRFRD1
 *  TXD_TRCTLRD
 *  TXD_FIFOTSTRD
 *  TXD_LATENCY
 *  TXD_MAXFRM
 *  TXD_DMARATE
 *  TXD_TRARB
 *  TXD_FLOWCON
 *  TXD_DROPCNT
 *  TXD_REGKEY
 *  TXD_SCHEDCFG
 *  TXD_FCOUNT
 *  TXD_SCHED
 *  TXD_QCTL
 *  TXD_BDBASE
 *  TXD_BDLIMIT
 *  TXD_BDPTR
 *  TXD_EINTSTAT
 *  TXD_EINTMASK
 *  TXD_QFCOUNT
 *
 * Prefix naming conventions :
 *   AG_MG_REGS_XXX_RA : register/memory physical address
 *   AG_MG_REGS_XXX_RO : register/memory address offset
 *   AG_MG_REGS_XXX_RM : register mask
 *   AG_MG_REGS_XXX_BO : bit/field offset from LSB
 *   AG_MG_REGS_XXX_BM : bit/field mask
 *   AG_MG_REGS_XXX_U  : bitfields in C union typedef
 *   AG_MG_REGS_XXX_S  : registers in C struct typedef
 *   AG_MG_REGS_XX_RPT : number of identical registers in array
 *   AG_MG_REGS_XX_IVL : interval between registers in array
 *
 * NOTE: user may redefine ag_mg_regs_register
 *       in ag_mg_regs_regops.h if necessary
 * NOTE: access mode of individual bit fields matches that
 *       of containing register unless indicated otherwise
 */

#ifndef AG_MG_REGS_ARM_TXD_REGISTERS_H
#define AG_MG_REGS_ARM_TXD_REGISTERS_H

#include "ag_mg_regs_regops.h"
/*
 * Generated by HSI Designer release 2.3.5.
 */





/*
 * TXD_START (DMA Start)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_START_RO                       0x00000000
#define AG_MG_REGS_TXD_START_RM                       0x00000001

#define AG_MG_REGS_TXD_START_START_BO                 0
#define AG_MG_REGS_TXD_START_START_BM                 0x00000001

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_START_U
{
    struct
    {
        ag_mg_regs_register
            start : 1,
            fill0 : 31;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_start_u;
#endif


/*
 * TXD_CONFIG (TXD DMA Configuration Register)
 * Initialization value: 0x000000FF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_CONFIG_RO                      0x00000004
#define AG_MG_REGS_TXD_CONFIG_RM                      0x070F1FFF

#define AG_MG_REGS_TXD_CONFIG_BDTU_EOF_BO             0
#define AG_MG_REGS_TXD_CONFIG_BDTU_EOF_BM             0x00000001

#define AG_MG_REGS_TXD_CONFIG_AXIRERR_EOF_BO          1
#define AG_MG_REGS_TXD_CONFIG_AXIRERR_EOF_BM          0x00000002

#define AG_MG_REGS_TXD_CONFIG_AXIWERR_EOF_BO          2
#define AG_MG_REGS_TXD_CONFIG_AXIWERR_EOF_BM          0x00000004

#define AG_MG_REGS_TXD_CONFIG_BDLIMIT_EOF_BO          3
#define AG_MG_REGS_TXD_CONFIG_BDLIMIT_EOF_BM          0x00000008

#define AG_MG_REGS_TXD_CONFIG_MAX_FRM_EOF_BO          4
#define AG_MG_REGS_TXD_CONFIG_MAX_FRM_EOF_BM          0x00000010

#define AG_MG_REGS_TXD_CONFIG_MAX_BD_EOF_BO           5
#define AG_MG_REGS_TXD_CONFIG_MAX_BD_EOF_BM           0x00000020

#define AG_MG_REGS_TXD_CONFIG_MAX_DATA_EOF_BO         6
#define AG_MG_REGS_TXD_CONFIG_MAX_DATA_EOF_BM         0x00000040

#define AG_MG_REGS_TXD_CONFIG_FFUND_EOF_BO            7
#define AG_MG_REGS_TXD_CONFIG_FFUND_EOF_BM            0x00000080

#define AG_MG_REGS_TXD_CONFIG_MAX_FRM_EN_BO           8
#define AG_MG_REGS_TXD_CONFIG_MAX_FRM_EN_BM           0x00000100

#define AG_MG_REGS_TXD_CONFIG_MAX_BD_EN_BO            9
#define AG_MG_REGS_TXD_CONFIG_MAX_BD_EN_BM            0x00000200

#define AG_MG_REGS_TXD_CONFIG_MAX_DAT_EN_BO           10
#define AG_MG_REGS_TXD_CONFIG_MAX_DAT_EN_BM           0x00000400

#define AG_MG_REGS_TXD_CONFIG_FLOW_EN_BO              11
#define AG_MG_REGS_TXD_CONFIG_FLOW_EN_BM              0x00000800

#define AG_MG_REGS_TXD_CONFIG_DROP_EN_BO              12
#define AG_MG_REGS_TXD_CONFIG_DROP_EN_BM              0x00001000

#define AG_MG_REGS_TXD_CONFIG_FIFOTEST_BO             16
#define AG_MG_REGS_TXD_CONFIG_FIFOTEST_BM             0x00010000

#define AG_MG_REGS_TXD_CONFIG_INTTEST_BO              17
#define AG_MG_REGS_TXD_CONFIG_INTTEST_BM              0x00020000

#define AG_MG_REGS_TXD_CONFIG_LOOPBACK_BO             18
#define AG_MG_REGS_TXD_CONFIG_LOOPBACK_BM             0x00040000

#define AG_MG_REGS_TXD_CONFIG_LRMUX_BO                19
#define AG_MG_REGS_TXD_CONFIG_LRMUX_BM                0x00080000

#define AG_MG_REGS_TXD_CONFIG_DFLUSH_BO               24
#define AG_MG_REGS_TXD_CONFIG_DFLUSH_BM               0x01000000

#define AG_MG_REGS_TXD_CONFIG_TFLUSH_BO               25
#define AG_MG_REGS_TXD_CONFIG_TFLUSH_BM               0x02000000

#define AG_MG_REGS_TXD_CONFIG_CCLEAR_BO               26
#define AG_MG_REGS_TXD_CONFIG_CCLEAR_BM               0x04000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_CONFIG_U
{
    struct
    {
        ag_mg_regs_register
            bdtu_eof : 1,
            axirerr_eof : 1,
            axiwerr_eof : 1,
            bdlimit_eof : 1,
            max_frm_eof : 1,
            max_bd_eof : 1,
            max_data_eof : 1,
            ffund_eof : 1,
            max_frm_en : 1,
            max_bd_en : 1,
            max_dat_en : 1,
            flow_en : 1,
            drop_en : 1,
            fill2 : 3,
            fifotest : 1,
            inttest : 1,
            loopback : 1,
            lrmux : 1,
            fill1 : 4,
            dflush : 1,
            tflush : 1,
            cclear : 1,
            fill0 : 5;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_config_u;
#endif


/*
 * TXD_STATUS (TXD DMA Status Register)
 * Initialization value: 0x00000022  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_STATUS_RO                      0x00000008
#define AG_MG_REGS_TXD_STATUS_RM                      0x000F0FFF

#define AG_MG_REGS_TXD_STATUS_ACTIVE_BO               0
#define AG_MG_REGS_TXD_STATUS_ACTIVE_BM               0x00000001

#define AG_MG_REGS_TXD_STATUS_DMAFFE_BO               1
#define AG_MG_REGS_TXD_STATUS_DMAFFE_BM               0x00000002

#define AG_MG_REGS_TXD_STATUS_DMAFFF_BO               2
#define AG_MG_REGS_TXD_STATUS_DMAFFF_BM               0x00000004

#define AG_MG_REGS_TXD_STATUS_DMAFFWM_BO              3
#define AG_MG_REGS_TXD_STATUS_DMAFFWM_BM              0x00000008

#define AG_MG_REGS_TXD_STATUS_DMAFFAF_BO              4
#define AG_MG_REGS_TXD_STATUS_DMAFFAF_BM              0x00000010

#define AG_MG_REGS_TXD_STATUS_TRFFE_BO                5
#define AG_MG_REGS_TXD_STATUS_TRFFE_BM                0x00000020

#define AG_MG_REGS_TXD_STATUS_TRFFF_BO                6
#define AG_MG_REGS_TXD_STATUS_TRFFF_BM                0x00000040

#define AG_MG_REGS_TXD_STATUS_TRFFWM_BO               7
#define AG_MG_REGS_TXD_STATUS_TRFFWM_BM               0x00000080

#define AG_MG_REGS_TXD_STATUS_CCFFE_BO                8
#define AG_MG_REGS_TXD_STATUS_CCFFE_BM                0x00000100

#define AG_MG_REGS_TXD_STATUS_CCFFF_BO                9
#define AG_MG_REGS_TXD_STATUS_CCFFF_BM                0x00000200

#define AG_MG_REGS_TXD_STATUS_TXRAOVER_BO             10
#define AG_MG_REGS_TXD_STATUS_TXRAOVER_BM             0x00000400

#define AG_MG_REGS_TXD_STATUS_TXRFLOWACT_BO           11
#define AG_MG_REGS_TXD_STATUS_TXRFLOWACT_BM           0x00000800

#define AG_MG_REGS_TXD_STATUS_QACTIVITY_BO            16
#define AG_MG_REGS_TXD_STATUS_QACTIVITY_BM            0x000F0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_STATUS_U
{
    struct
    {
        ag_mg_regs_register
            active : 1,
            dmaffe : 1,
            dmafff : 1,
            dmaffwm : 1,
            dmaffaf : 1,
            trffe : 1,
            trfff : 1,
            trffwm : 1,
            ccffe : 1,
            ccfff : 1,
            txraover : 1,
            txrflowact : 1,
            fill1 : 4,
            qactivity : 4,
            fill0 : 12;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_status_u;
#endif


/*
 * TXD_BLEN (TXD Expected Buffer Length Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_BLEN_RO                        0x0000000C
#define AG_MG_REGS_TXD_BLEN_RM                        0x00003FFF

#define AG_MG_REGS_TXD_BLEN_BLENGTH_BO                0
#define AG_MG_REGS_TXD_BLEN_BLENGTH_BM                0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_BLEN_U
{
    struct
    {
        ag_mg_regs_register
            blength : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_blen_u;
#endif


/*
 * TXD_FIFOWM (TXD FIFO Watermark Register)
 * Initialization value: 0x00EF0020  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_FIFOWM_RO                      0x00000010
#define AG_MG_REGS_TXD_FIFOWM_RM                      0x01FF01FF

#define AG_MG_REGS_TXD_FIFOWM_FIFOWM_BO               0
#define AG_MG_REGS_TXD_FIFOWM_FIFOWM_BM               0x000001FF

#define AG_MG_REGS_TXD_FIFOWM_FIFOAF_BO               16
#define AG_MG_REGS_TXD_FIFOWM_FIFOAF_BM               0x01FF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_FIFOWM_U
{
    struct
    {
        ag_mg_regs_register
            fifowm : 9,
            fill1 : 7,
            fifoaf : 9,
            fill0 : 7;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_fifowm_u;
#endif


/*
 * TXD_TRFWM (TXD Tx Remote FIFO Watermark Register)
 * Initialization value: 0x00FF3110  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_TRFWM_RO                       0x00000014
#define AG_MG_REGS_TXD_TRFWM_RM                       0x00000FFF

#define AG_MG_REGS_TXD_TRFWM_TRFIFOWM_BO              0
#define AG_MG_REGS_TXD_TRFWM_TRFIFOWM_BM              0x00000FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_TRFWM_U
{
    struct
    {
        ag_mg_regs_register
            trfifowm : 12,
            fill0 : 20;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_trfwm_u;
#endif


/*
 * TXD_EINTTEST (TXD Exception Interrupt Test Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_EINTTEST_RO                    0x00000018
#define AG_MG_REGS_TXD_EINTTEST_RM                    0x01FFFFFF

#define AG_MG_REGS_TXD_EINTTEST_BDTSTEST_BO           0
#define AG_MG_REGS_TXD_EINTTEST_BDTSTEST_BM           0x00000001

#define AG_MG_REGS_TXD_EINTTEST_BDTETEST_BO           1
#define AG_MG_REGS_TXD_EINTTEST_BDTETEST_BM           0x00000002

#define AG_MG_REGS_TXD_EINTTEST_BDTUTEST_BO           2
#define AG_MG_REGS_TXD_EINTTEST_BDTUTEST_BM           0x00000004

#define AG_MG_REGS_TXD_EINTTEST_FIFOOVTEST_BO         3
#define AG_MG_REGS_TXD_EINTTEST_FIFOOVTEST_BM         0x00000008

#define AG_MG_REGS_TXD_EINTTEST_FIFOUNTEST_BO         4
#define AG_MG_REGS_TXD_EINTTEST_FIFOUNTEST_BM         0x00000010

#define AG_MG_REGS_TXD_EINTTEST_TRFOVTEST_BO          5
#define AG_MG_REGS_TXD_EINTTEST_TRFOVTEST_BM          0x00000020

#define AG_MG_REGS_TXD_EINTTEST_TRFUNTEST_BO          6
#define AG_MG_REGS_TXD_EINTTEST_TRFUNTEST_BM          0x00000040

#define AG_MG_REGS_TXD_EINTTEST_AXIWERRTEST_BO        7
#define AG_MG_REGS_TXD_EINTTEST_AXIWERRTEST_BM        0x00000080

#define AG_MG_REGS_TXD_EINTTEST_AXIRERRTEST_BO        8
#define AG_MG_REGS_TXD_EINTTEST_AXIRERRTEST_BM        0x00000100

#define AG_MG_REGS_TXD_EINTTEST_BDLIMTEST_BO          9
#define AG_MG_REGS_TXD_EINTTEST_BDLIMTEST_BM          0x00000200

#define AG_MG_REGS_TXD_EINTTEST_BDLENTEST_BO          10
#define AG_MG_REGS_TXD_EINTTEST_BDLENTEST_BM          0x00000400

#define AG_MG_REGS_TXD_EINTTEST_MINFRMTEST_BO         11
#define AG_MG_REGS_TXD_EINTTEST_MINFRMTEST_BM         0x00000800

#define AG_MG_REGS_TXD_EINTTEST_SOFSOFTEST_BO         12
#define AG_MG_REGS_TXD_EINTTEST_SOFSOFTEST_BM         0x00001000

#define AG_MG_REGS_TXD_EINTTEST_CROSS4KTEST_BO        13
#define AG_MG_REGS_TXD_EINTTEST_CROSS4KTEST_BM        0x00002000

#define AG_MG_REGS_TXD_EINTTEST_MAXFRMTEST_BO         14
#define AG_MG_REGS_TXD_EINTTEST_MAXFRMTEST_BM         0x00004000

#define AG_MG_REGS_TXD_EINTTEST_BLATENCYTEST_BO       15
#define AG_MG_REGS_TXD_EINTTEST_BLATENCYTEST_BM       0x00008000

#define AG_MG_REGS_TXD_EINTTEST_DLATENCYTEST_BO       16
#define AG_MG_REGS_TXD_EINTTEST_DLATENCYTEST_BM       0x00010000

#define AG_MG_REGS_TXD_EINTTEST_TXRFLOWTEST_BO        17
#define AG_MG_REGS_TXD_EINTTEST_TXRFLOWTEST_BM        0x00020000

#define AG_MG_REGS_TXD_EINTTEST_DMADROPTEST_BO        18
#define AG_MG_REGS_TXD_EINTTEST_DMADROPTEST_BM        0x00040000

#define AG_MG_REGS_TXD_EINTTEST_MACDROPTEST_BO        19
#define AG_MG_REGS_TXD_EINTTEST_MACDROPTEST_BM        0x00080000

#define AG_MG_REGS_TXD_EINTTEST_CCFOVTEST_BO          20
#define AG_MG_REGS_TXD_EINTTEST_CCFOVTEST_BM          0x00100000

#define AG_MG_REGS_TXD_EINTTEST_UNSCHEDTEST_BO        21
#define AG_MG_REGS_TXD_EINTTEST_UNSCHEDTEST_BM        0x00200000

#define AG_MG_REGS_TXD_EINTTEST_BDFFERRTEST_BO        22
#define AG_MG_REGS_TXD_EINTTEST_BDFFERRTEST_BM        0x00400000

#define AG_MG_REGS_TXD_EINTTEST_AXIRERRDTEST_BO       23
#define AG_MG_REGS_TXD_EINTTEST_AXIRERRDTEST_BM       0x00800000

#define AG_MG_REGS_TXD_EINTTEST_INVALIDQTEST_BO       24
#define AG_MG_REGS_TXD_EINTTEST_INVALIDQTEST_BM       0x01000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_EINTTEST_U
{
    struct
    {
        ag_mg_regs_register
            bdtstest : 1,
            bdtetest : 1,
            bdtutest : 1,
            fifoovtest : 1,
            fifountest : 1,
            trfovtest : 1,
            trfuntest : 1,
            axiwerrtest : 1,
            axirerrtest : 1,
            bdlimtest : 1,
            bdlentest : 1,
            minfrmtest : 1,
            sofsoftest : 1,
            cross4ktest : 1,
            maxfrmtest : 1,
            blatencytest : 1,
            dlatencytest : 1,
            txrflowtest : 1,
            dmadroptest : 1,
            macdroptest : 1,
            ccfovtest : 1,
            unschedtest : 1,
            bdfferrtest : 1,
            axirerrdtest : 1,
            invalidqtest : 1,
            fill0 : 7;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_einttest_u;
#endif


/*
 * TXD_FINTMASK (TXD End-of-Frame Interrupt Mask Register)
 * Initialization value: 0x000001FF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_FINTMASK_RO                    0x0000001C
#define AG_MG_REGS_TXD_FINTMASK_RM                    0x000001FF

#define AG_MG_REGS_TXD_FINTMASK_FINTMASK_BO           0
#define AG_MG_REGS_TXD_FINTMASK_FINTMASK_BM           0x000001FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_FINTMASK_U
{
    struct
    {
        ag_mg_regs_register
            fintmask : 9,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_fintmask_u;
#endif


/*
 * TXD_FINTTEST (TXD End-of-Frame Interrupt Test Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_FINTTEST_RO                    0x00000020
#define AG_MG_REGS_TXD_FINTTEST_RM                    0x0FFF01FF

#define AG_MG_REGS_TXD_FINTTEST_FINTTEST_BO           0
#define AG_MG_REGS_TXD_FINTTEST_FINTTEST_BM           0x000001FF

#define AG_MG_REGS_TXD_FINTTEST_INTLIMIT_BO           16
#define AG_MG_REGS_TXD_FINTTEST_INTLIMIT_BM           0x0FFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_FINTTEST_U
{
    struct
    {
        ag_mg_regs_register
            finttest : 9,
            fill1 : 7,
            intlimit : 12,
            fill0 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_finttest_u;
#endif


/*
 * TXD_BDTSCNT (TXD BD Table Structure Exception Count Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_BDTSCNT_RO                     0x00000024
#define AG_MG_REGS_TXD_BDTSCNT_RM                     0x0000FFFF

#define AG_MG_REGS_TXD_BDTSCNT_BDTSCNT_BO             0
#define AG_MG_REGS_TXD_BDTSCNT_BDTSCNT_BM             0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_BDTSCNT_U
{
    struct
    {
        ag_mg_regs_register
            bdtscnt : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_bdtscnt_u;
#endif


/*
 * TXD_BDTECNT (TXD Buffer Descriptor Table Empty Count Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_BDTECNT_RO                     0x00000028
#define AG_MG_REGS_TXD_BDTECNT_RM                     0x0000FFFF

#define AG_MG_REGS_TXD_BDTECNT_BDTECNT_BO             0
#define AG_MG_REGS_TXD_BDTECNT_BDTECNT_BM             0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_BDTECNT_U
{
    struct
    {
        ag_mg_regs_register
            bdtecnt : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_bdtecnt_u;
#endif


/*
 * TXD_BDTUCNT (TXD Buffer Descriptor Table Underrun Count Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_BDTUCNT_RO                     0x0000002C
#define AG_MG_REGS_TXD_BDTUCNT_RM                     0x0000FFFF

#define AG_MG_REGS_TXD_BDTUCNT_BDTUCNT_BO             0
#define AG_MG_REGS_TXD_BDTUCNT_BDTUCNT_BM             0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_BDTUCNT_U
{
    struct
    {
        ag_mg_regs_register
            bdtucnt : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_bdtucnt_u;
#endif


/*
 * TXD_FIFORD0 (TXD DMA FIFO Test Read Access Register)
 * Initialization value: 0x00000000  Initialization mask: 0x00000000
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_FIFORD0_RO                     0x00000030
#define AG_MG_REGS_TXD_FIFORD0_RM                     0xFFFFFFFF

#define AG_MG_REGS_TXD_FIFORD0_FIFODL_BO              0
#define AG_MG_REGS_TXD_FIFORD0_FIFODL_BM              0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_FIFORD0_U
{
    struct
    {
        ag_mg_regs_register
            fifodl;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_fiford0_u;
#endif


/*
 * TXD_FIFORD1 (TXD DMA FIFO Test Read Access Register)
 * Initialization value: 0x00000000  Initialization mask: 0x00000000
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_FIFORD1_RO                     0x00000034
#define AG_MG_REGS_TXD_FIFORD1_RM                     0xFFFFFFFF

#define AG_MG_REGS_TXD_FIFORD1_FIFODH_BO              0
#define AG_MG_REGS_TXD_FIFORD1_FIFODH_BM              0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_FIFORD1_U
{
    struct
    {
        ag_mg_regs_register
            fifodh;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_fiford1_u;
#endif


/*
 * TXD_CTLRD (TXD DMA FIFO Test Control Signal Access Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFE000
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_CTLRD_RO                       0x00000038
#define AG_MG_REGS_TXD_CTLRD_RM                       0x000001FF

#define AG_MG_REGS_TXD_CTLRD_DVBYTES_BO               0
#define AG_MG_REGS_TXD_CTLRD_DVBYTES_BM               0x00000007

#define AG_MG_REGS_TXD_CTLRD_EOF_BO                   3
#define AG_MG_REGS_TXD_CTLRD_EOF_BM                   0x00000008

#define AG_MG_REGS_TXD_CTLRD_ERR_BO                   4
#define AG_MG_REGS_TXD_CTLRD_ERR_BM                   0x00000010

#define AG_MG_REGS_TXD_CTLRD_QNUM_BO                  5
#define AG_MG_REGS_TXD_CTLRD_QNUM_BM                  0x000001E0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_CTLRD_U
{
    struct
    {
        ag_mg_regs_register
            dvbytes : 3,
            eof : 1,
            err : 1,
            qnum : 4,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_ctlrd_u;
#endif


/*
 * TXD_TRFRD0 (TXD TX Remote FIFO Test Access Register)
 * Initialization value: 0x00000000  Initialization mask: 0x00000000
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_TRFRD0_RO                      0x0000003C
#define AG_MG_REGS_TXD_TRFRD0_RM                      0xFFFFFFFF

#define AG_MG_REGS_TXD_TRFRD0_TFIFODL_BO              0
#define AG_MG_REGS_TXD_TRFRD0_TFIFODL_BM              0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_TRFRD0_U
{
    struct
    {
        ag_mg_regs_register
            tfifodl;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_trfrd0_u;
#endif


/*
 * TXD_TRFRD1 (TXD TX Remote FIFO Test Access Register)
 * Initialization value: 0x00000000  Initialization mask: 0x00000000
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_TRFRD1_RO                      0x00000040
#define AG_MG_REGS_TXD_TRFRD1_RM                      0xFFFFFFFF

#define AG_MG_REGS_TXD_TRFRD1_TFIFODH_BO              0
#define AG_MG_REGS_TXD_TRFRD1_TFIFODH_BM              0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_TRFRD1_U
{
    struct
    {
        ag_mg_regs_register
            tfifodh;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_trfrd1_u;
#endif


/*
 * TXD_TRCTLRD (TXD TX Remote FIFO Test Control Signal Access Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFE0
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_TRCTLRD_RO                     0x00000044
#define AG_MG_REGS_TXD_TRCTLRD_RM                     0x0000001F

#define AG_MG_REGS_TXD_TRCTLRD_TVBYTES_BO             0
#define AG_MG_REGS_TXD_TRCTLRD_TVBYTES_BM             0x00000007

#define AG_MG_REGS_TXD_TRCTLRD_TEOF_BO                3
#define AG_MG_REGS_TXD_TRCTLRD_TEOF_BM                0x00000008

#define AG_MG_REGS_TXD_TRCTLRD_TERR_BO                4
#define AG_MG_REGS_TXD_TRCTLRD_TERR_BM                0x00000010

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_TRCTLRD_U
{
    struct
    {
        ag_mg_regs_register
            tvbytes : 3,
            teof : 1,
            terr : 1,
            fill0 : 27;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_trctlrd_u;
#endif


/*
 * TXD_FIFOTSTRD (TXD FIFO Test Access Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_TXD_FIFOTSTRD_RO                   0x00000048
#define AG_MG_REGS_TXD_FIFOTSTRD_RM                   0x00000003

#define AG_MG_REGS_TXD_FIFOTSTRD_DMAFIFORD_BO         0
#define AG_MG_REGS_TXD_FIFOTSTRD_DMAFIFORD_BM         0x00000001

#define AG_MG_REGS_TXD_FIFOTSTRD_TXRFIFORD_BO         1
#define AG_MG_REGS_TXD_FIFOTSTRD_TXRFIFORD_BM         0x00000002

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_FIFOTSTRD_U
{
    struct
    {
        ag_mg_regs_register
            dmafiford : 1,
            txrfiford : 1,
            fill0 : 30;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_fifotstrd_u;
#endif


/*
 * TXD_LATENCY (TXD DMA Latency Limits)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_LATENCY_RO                     0x0000004C
#define AG_MG_REGS_TXD_LATENCY_RM                     0x0FFF0FFF

#define AG_MG_REGS_TXD_LATENCY_MAX_BD_LATENCY_BO      0
#define AG_MG_REGS_TXD_LATENCY_MAX_BD_LATENCY_BM      0x00000FFF

#define AG_MG_REGS_TXD_LATENCY_MAX_DATA_LATENCY_BO    16
#define AG_MG_REGS_TXD_LATENCY_MAX_DATA_LATENCY_BM    0x0FFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_LATENCY_U
{
    struct
    {
        ag_mg_regs_register
            max_bd_latency : 12,
            fill1 : 4,
            max_data_latency : 12,
            fill0 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_latency_u;
#endif


/*
 * TXD_MAXFRM (TXD DMA maximum frame size)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_MAXFRM_RO                      0x00000050
#define AG_MG_REGS_TXD_MAXFRM_RM                      0x00003FFF

#define AG_MG_REGS_TXD_MAXFRM_MAX_FRAME_SIZE_BO       0
#define AG_MG_REGS_TXD_MAXFRM_MAX_FRAME_SIZE_BM       0x00003FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_MAXFRM_U
{
    struct
    {
        ag_mg_regs_register
            max_frame_size : 14,
            fill0 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_maxfrm_u;
#endif


/*
 * TXD_DMARATE (TXD DMA Rate Limiting)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_DMARATE_RO                     0x00000054
#define AG_MG_REGS_TXD_DMARATE_RM                     0xFFFFF301

#define AG_MG_REGS_TXD_DMARATE_RATE_EN_BO             0
#define AG_MG_REGS_TXD_DMARATE_RATE_EN_BM             0x00000001

#define AG_MG_REGS_TXD_DMARATE_RATEMODE_BO            8
#define AG_MG_REGS_TXD_DMARATE_RATEMODE_BM            0x00000100

#define AG_MG_REGS_TXD_DMARATE_SMIICLK_BO             9
#define AG_MG_REGS_TXD_DMARATE_SMIICLK_BM             0x00000200

#define AG_MG_REGS_TXD_DMARATE_RATESHIFT_BO           12
#define AG_MG_REGS_TXD_DMARATE_RATESHIFT_BM           0x00007000

#define AG_MG_REGS_TXD_DMARATE_MULT3_BO               15
#define AG_MG_REGS_TXD_DMARATE_MULT3_BM               0x00008000

#define AG_MG_REGS_TXD_DMARATE_CLKWAIT_BO             16
#define AG_MG_REGS_TXD_DMARATE_CLKWAIT_BM             0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_DMARATE_U
{
    struct
    {
        ag_mg_regs_register
            rate_en : 1,
            fill1 : 7,
            ratemode : 1,
            smiiclk : 1,
            fill0 : 2,
            rateshift : 3,
            mult3 : 1,
            clkwait : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_dmarate_u;
#endif


/*
 * TXD_TRARB (TX Remote Arbitration Control)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_TRARB_RO                       0x00000058
#define AG_MG_REGS_TXD_TRARB_RM                       0x0FFF8FFF

#define AG_MG_REGS_TXD_TRARB_ARB_OVERRIDE_WM_BO       0
#define AG_MG_REGS_TXD_TRARB_ARB_OVERRIDE_WM_BM       0x00000FFF

#define AG_MG_REGS_TXD_TRARB_ARB_MODE_BO              15
#define AG_MG_REGS_TXD_TRARB_ARB_MODE_BM              0x00008000

#define AG_MG_REGS_TXD_TRARB_ARB_RESUME_WM_BO         16
#define AG_MG_REGS_TXD_TRARB_ARB_RESUME_WM_BM         0x0FFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_TRARB_U
{
    struct
    {
        ag_mg_regs_register
            arb_override_wm : 12,
            fill1 : 3,
            arb_mode : 1,
            arb_resume_wm : 12,
            fill0 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_trarb_u;
#endif


/*
 * TXD_FLOWCON (TX Remote flow control)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_FLOWCON_RO                     0x0000005C
#define AG_MG_REGS_TXD_FLOWCON_RM                     0x0FFF0FFF

#define AG_MG_REGS_TXD_FLOWCON_TXR_FLOW_WM_BO         0
#define AG_MG_REGS_TXD_FLOWCON_TXR_FLOW_WM_BM         0x00000FFF

#define AG_MG_REGS_TXD_FLOWCON_TXR_DMADROP_WM_BO      16
#define AG_MG_REGS_TXD_FLOWCON_TXR_DMADROP_WM_BM      0x0FFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_FLOWCON_U
{
    struct
    {
        ag_mg_regs_register
            txr_flow_wm : 12,
            fill1 : 4,
            txr_dmadrop_wm : 12,
            fill0 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_flowcon_u;
#endif


/*
 * TXD_DROPCNT (Frame Drop Counts)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_DROPCNT_RO                     0x00000060
#define AG_MG_REGS_TXD_DROPCNT_RM                     0x0FFF0FFF

#define AG_MG_REGS_TXD_DROPCNT_MAC_DROPCNT_BO         0
#define AG_MG_REGS_TXD_DROPCNT_MAC_DROPCNT_BM         0x00000FFF

#define AG_MG_REGS_TXD_DROPCNT_DMA_DROPCNT_BO         16
#define AG_MG_REGS_TXD_DROPCNT_DMA_DROPCNT_BM         0x0FFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_DROPCNT_U
{
    struct
    {
        ag_mg_regs_register
            mac_dropcnt : 12,
            fill1 : 4,
            dma_dropcnt : 12,
            fill0 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_dropcnt_u;
#endif


/*
 * TXD_REGKEY (TXD Register write protection)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_REGKEY_RO                      0x00000064
#define AG_MG_REGS_TXD_REGKEY_RM                      0x8FFF8FFF

#define AG_MG_REGS_TXD_REGKEY_REGKEY_BO               0
#define AG_MG_REGS_TXD_REGKEY_REGKEY_BM               0x00000FFF

#define AG_MG_REGS_TXD_REGKEY_TXD_WRITE_STAT_BO       15
#define AG_MG_REGS_TXD_REGKEY_TXD_WRITE_STAT_BM       0x00008000

#define AG_MG_REGS_TXD_REGKEY_MAC_REGKEY_BO           16
#define AG_MG_REGS_TXD_REGKEY_MAC_REGKEY_BM           0x0FFF0000

#define AG_MG_REGS_TXD_REGKEY_MAC_WRITE_STAT_BO       31
#define AG_MG_REGS_TXD_REGKEY_MAC_WRITE_STAT_BM       0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_REGKEY_U
{
    struct
    {
        ag_mg_regs_register
            regkey : 12,
            fill1 : 3,
            write_stat : 1,
            mac_regkey : 12,
            fill0 : 3,
            mac_write_stat : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_regkey_u;
#endif


/*
 * TXD_SCHEDCFG (BD queue Scheduler configuration)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_SCHEDCFG_RO                    0x00000068
#define AG_MG_REGS_TXD_SCHEDCFG_RM                    0x0000003F

#define AG_MG_REGS_TXD_SCHEDCFG_MAXSLOT_BO            0
#define AG_MG_REGS_TXD_SCHEDCFG_MAXSLOT_BM            0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_SCHEDCFG_U
{
    struct
    {
        ag_mg_regs_register
            maxslot : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_schedcfg_u;
#endif


/*
 * TXD_FCOUNT (TXD TX Frame Transmitted Count Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_FCOUNT_RO                      0x0000006C
#define AG_MG_REGS_TXD_FCOUNT_RM                      0xFFFFFFFF

#define AG_MG_REGS_TXD_FCOUNT_FCOUNT_BO               0
#define AG_MG_REGS_TXD_FCOUNT_FCOUNT_BM               0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_FCOUNT_U
{
    struct
    {
        ag_mg_regs_register
            fcount;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_fcount_u;
#endif


/*
 * TXD_SCHED (buffer descriptor queue schedule slots)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_SCHED_RO                       0x00000100
#define AG_MG_REGS_TXD_SCHED_RM                       0xFFFFFFFF
#define AG_MG_REGS_TXD_SCHED_RPT                      4
#define AG_MG_REGS_TXD_SCHED_IVL                      0x4

#define AG_MG_REGS_TXD_SCHED_SLOT0_BO                 0
#define AG_MG_REGS_TXD_SCHED_SLOT0_BM                 0x0000000F

#define AG_MG_REGS_TXD_SCHED_SLOT1_BO                 4
#define AG_MG_REGS_TXD_SCHED_SLOT1_BM                 0x000000F0

#define AG_MG_REGS_TXD_SCHED_SLOT2_BO                 8
#define AG_MG_REGS_TXD_SCHED_SLOT2_BM                 0x00000F00

#define AG_MG_REGS_TXD_SCHED_SLOT3_BO                 12
#define AG_MG_REGS_TXD_SCHED_SLOT3_BM                 0x0000F000

#define AG_MG_REGS_TXD_SCHED_SLOT4_BO                 16
#define AG_MG_REGS_TXD_SCHED_SLOT4_BM                 0x000F0000

#define AG_MG_REGS_TXD_SCHED_SLOT5_BO                 20
#define AG_MG_REGS_TXD_SCHED_SLOT5_BM                 0x00F00000

#define AG_MG_REGS_TXD_SCHED_SLOT6_BO                 24
#define AG_MG_REGS_TXD_SCHED_SLOT6_BM                 0x0F000000

#define AG_MG_REGS_TXD_SCHED_SLOT7_BO                 28
#define AG_MG_REGS_TXD_SCHED_SLOT7_BM                 0xF0000000
#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_SCHED_U
{
    struct
    {
        ag_mg_regs_register
            slot0 : 4,
            slot1 : 4,
            slot2 : 4,
            slot3 : 4,
            slot4 : 4,
            slot5 : 4,
            slot6 : 4,
            slot7 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_sched_u;
#endif


/*
 * TXD_QCTL (Queue Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_QCTL_RO                        0x00000800
#define AG_MG_REGS_TXD_QCTL_RM                        0x0000000F
#define AG_MG_REGS_TXD_QCTL_RPT                       9
#define AG_MG_REGS_TXD_QCTL_IVL                       0x40

#define AG_MG_REGS_TXD_QCTL_Q_ACTIVE_BO               0
#define AG_MG_REGS_TXD_QCTL_Q_ACTIVE_BM               0x00000001

#define AG_MG_REGS_TXD_QCTL_INTARMED_BO               1
#define AG_MG_REGS_TXD_QCTL_INTARMED_BM               0x00000002

#define AG_MG_REGS_TXD_QCTL_QCNTCLR_BO                2
#define AG_MG_REGS_TXD_QCTL_QCNTCLR_BM                0x00000004

#define AG_MG_REGS_TXD_QCTL_QPRIORITY_BO              3
#define AG_MG_REGS_TXD_QCTL_QPRIORITY_BM              0x00000008

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_QCTL_U
{
    struct
    {
        ag_mg_regs_register
            q_active : 1,
            intarmed : 1,
            qcntclr : 1,
            qpriority : 1,
            fill0 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_qctl_u;
#endif


/*
 * TXD_BDBASE (TXD Buffer Descriptor Base Address Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_BDBASE_RO                      0x00000804
#define AG_MG_REGS_TXD_BDBASE_RM                      0xFFFFFFFF
#define AG_MG_REGS_TXD_BDBASE_RPT                     9
#define AG_MG_REGS_TXD_BDBASE_IVL                     0x40

#define AG_MG_REGS_TXD_BDBASE_BDBASE_BO               0
#define AG_MG_REGS_TXD_BDBASE_BDBASE_BM               0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_BDBASE_U
{
    struct
    {
        ag_mg_regs_register
            bdbase;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_bdbase_u;
#endif


/*
 * TXD_BDLIMIT (TXD Buffer Descriptor Pointer Limit Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_BDLIMIT_RO                     0x00000808
#define AG_MG_REGS_TXD_BDLIMIT_RM                     0xFFFFFFFF
#define AG_MG_REGS_TXD_BDLIMIT_RPT                    9
#define AG_MG_REGS_TXD_BDLIMIT_IVL                    0x40

#define AG_MG_REGS_TXD_BDLIMIT_BDLIMIT_BO             0
#define AG_MG_REGS_TXD_BDLIMIT_BDLIMIT_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_BDLIMIT_U
{
    struct
    {
        ag_mg_regs_register
            bdlimit;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_bdlimit_u;
#endif


/*
 * TXD_BDPTR (TXD Current Buffer Descriptor Pointer Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_BDPTR_RO                       0x0000080C
#define AG_MG_REGS_TXD_BDPTR_RM                       0xFFFFFFF8
#define AG_MG_REGS_TXD_BDPTR_RPT                      9
#define AG_MG_REGS_TXD_BDPTR_IVL                      0x40

#define AG_MG_REGS_TXD_BDPTR_BDPTR_BO                 3
#define AG_MG_REGS_TXD_BDPTR_BDPTR_BM                 0xFFFFFFF8

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_BDPTR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 3,
            bdptr : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_bdptr_u;
#endif


/*
 * TXD_EINTSTAT (TXD Exception Interrupt Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_TXD_EINTSTAT_RO                    0x00000810
#define AG_MG_REGS_TXD_EINTSTAT_RM                    0x01FFFFFF
#define AG_MG_REGS_TXD_EINTSTAT_RPT                   9
#define AG_MG_REGS_TXD_EINTSTAT_IVL                   0x40

#define AG_MG_REGS_TXD_EINTSTAT_BDTS_BO               0
#define AG_MG_REGS_TXD_EINTSTAT_BDTS_BM               0x00000001

#define AG_MG_REGS_TXD_EINTSTAT_BDTE_BO               1
#define AG_MG_REGS_TXD_EINTSTAT_BDTE_BM               0x00000002

#define AG_MG_REGS_TXD_EINTSTAT_BDTU_BO               2
#define AG_MG_REGS_TXD_EINTSTAT_BDTU_BM               0x00000004

#define AG_MG_REGS_TXD_EINTSTAT_FIFOOV_BO             3
#define AG_MG_REGS_TXD_EINTSTAT_FIFOOV_BM             0x00000008

#define AG_MG_REGS_TXD_EINTSTAT_FIFOUN_BO             4
#define AG_MG_REGS_TXD_EINTSTAT_FIFOUN_BM             0x00000010

#define AG_MG_REGS_TXD_EINTSTAT_TRFOV_BO              5
#define AG_MG_REGS_TXD_EINTSTAT_TRFOV_BM              0x00000020

#define AG_MG_REGS_TXD_EINTSTAT_TRFUN_BO              6
#define AG_MG_REGS_TXD_EINTSTAT_TRFUN_BM              0x00000040

#define AG_MG_REGS_TXD_EINTSTAT_AXIWERR_BO            7
#define AG_MG_REGS_TXD_EINTSTAT_AXIWERR_BM            0x00000080

#define AG_MG_REGS_TXD_EINTSTAT_AXIRERR_BO            8
#define AG_MG_REGS_TXD_EINTSTAT_AXIRERR_BM            0x00000100

#define AG_MG_REGS_TXD_EINTSTAT_BDLIM_BO              9
#define AG_MG_REGS_TXD_EINTSTAT_BDLIM_BM              0x00000200

#define AG_MG_REGS_TXD_EINTSTAT_BLEN_BO               10
#define AG_MG_REGS_TXD_EINTSTAT_BLEN_BM               0x00000400

#define AG_MG_REGS_TXD_EINTSTAT_MINFRM_BO             11
#define AG_MG_REGS_TXD_EINTSTAT_MINFRM_BM             0x00000800

#define AG_MG_REGS_TXD_EINTSTAT_SOFSOF_BO             12
#define AG_MG_REGS_TXD_EINTSTAT_SOFSOF_BM             0x00001000

#define AG_MG_REGS_TXD_EINTSTAT_CROSS4K_BO            13
#define AG_MG_REGS_TXD_EINTSTAT_CROSS4K_BM            0x00002000

#define AG_MG_REGS_TXD_EINTSTAT_MAXFRM_BO             14
#define AG_MG_REGS_TXD_EINTSTAT_MAXFRM_BM             0x00004000

#define AG_MG_REGS_TXD_EINTSTAT_BLATENCY_BO           15
#define AG_MG_REGS_TXD_EINTSTAT_BLATENCY_BM           0x00008000

#define AG_MG_REGS_TXD_EINTSTAT_DLATENCY_BO           16
#define AG_MG_REGS_TXD_EINTSTAT_DLATENCY_BM           0x00010000

#define AG_MG_REGS_TXD_EINTSTAT_TXRFLOW_BO            17
#define AG_MG_REGS_TXD_EINTSTAT_TXRFLOW_BM            0x00020000

#define AG_MG_REGS_TXD_EINTSTAT_DMADROP_BO            18
#define AG_MG_REGS_TXD_EINTSTAT_DMADROP_BM            0x00040000

#define AG_MG_REGS_TXD_EINTSTAT_MACDROP_BO            19
#define AG_MG_REGS_TXD_EINTSTAT_MACDROP_BM            0x00080000

#define AG_MG_REGS_TXD_EINTSTAT_CCFOV_BO              20
#define AG_MG_REGS_TXD_EINTSTAT_CCFOV_BM              0x00100000

#define AG_MG_REGS_TXD_EINTSTAT_UNSCHED_BO            21
#define AG_MG_REGS_TXD_EINTSTAT_UNSCHED_BM            0x00200000

#define AG_MG_REGS_TXD_EINTSTAT_BDFFERR_BO            22
#define AG_MG_REGS_TXD_EINTSTAT_BDFFERR_BM            0x00400000

#define AG_MG_REGS_TXD_EINTSTAT_AXIRERRD_BO           23
#define AG_MG_REGS_TXD_EINTSTAT_AXIRERRD_BM           0x00800000

#define AG_MG_REGS_TXD_EINTSTAT_INVALIDQ_BO           24
#define AG_MG_REGS_TXD_EINTSTAT_INVALIDQ_BM           0x01000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_EINTSTAT_U
{
    struct
    {
        ag_mg_regs_register
            bdts : 1,
            bdte : 1,
            bdtu : 1,
            fifoov : 1,
            fifoun : 1,
            trfov : 1,
            trfun : 1,
            axiwerr : 1,
            axirerr : 1,
            bdlim : 1,
            blen : 1,
            minfrm : 1,
            sofsof : 1,
            cross4k : 1,
            maxfrm : 1,
            blatency : 1,
            dlatency : 1,
            txrflow : 1,
            dmadrop : 1,
            macdrop : 1,
            ccfov : 1,
            unsched : 1,
            bdfferr : 1,
            axirerrd : 1,
            invalidq : 1,
            fill0 : 7;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_eintstat_u;
#endif


/*
 * TXD_EINTMASK (TXD Exception Interrupt Mask Register)
 * Initialization value: 0x01FFFFFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TXD_EINTMASK_RO                    0x00000814
#define AG_MG_REGS_TXD_EINTMASK_RM                    0x01FFFFFF
#define AG_MG_REGS_TXD_EINTMASK_RPT                   9
#define AG_MG_REGS_TXD_EINTMASK_IVL                   0x40

#define AG_MG_REGS_TXD_EINTMASK_BDTSMASK_BO           0
#define AG_MG_REGS_TXD_EINTMASK_BDTSMASK_BM           0x00000001

#define AG_MG_REGS_TXD_EINTMASK_BDTEMASK_BO           1
#define AG_MG_REGS_TXD_EINTMASK_BDTEMASK_BM           0x00000002

#define AG_MG_REGS_TXD_EINTMASK_BDTUMASK_BO           2
#define AG_MG_REGS_TXD_EINTMASK_BDTUMASK_BM           0x00000004

#define AG_MG_REGS_TXD_EINTMASK_FIFOOVMASK_BO         3
#define AG_MG_REGS_TXD_EINTMASK_FIFOOVMASK_BM         0x00000008

#define AG_MG_REGS_TXD_EINTMASK_FIFOUNMASK_BO         4
#define AG_MG_REGS_TXD_EINTMASK_FIFOUNMASK_BM         0x00000010

#define AG_MG_REGS_TXD_EINTMASK_TRFOVMASK_BO          5
#define AG_MG_REGS_TXD_EINTMASK_TRFOVMASK_BM          0x00000020

#define AG_MG_REGS_TXD_EINTMASK_TRFUNMASK_BO          6
#define AG_MG_REGS_TXD_EINTMASK_TRFUNMASK_BM          0x00000040

#define AG_MG_REGS_TXD_EINTMASK_AXIWERRMASK_BO        7
#define AG_MG_REGS_TXD_EINTMASK_AXIWERRMASK_BM        0x00000080

#define AG_MG_REGS_TXD_EINTMASK_AXIRERRMASK_BO        8
#define AG_MG_REGS_TXD_EINTMASK_AXIRERRMASK_BM        0x00000100

#define AG_MG_REGS_TXD_EINTMASK_BDLIMMASK_BO          9
#define AG_MG_REGS_TXD_EINTMASK_BDLIMMASK_BM          0x00000200

#define AG_MG_REGS_TXD_EINTMASK_BDLENMASK_BO          10
#define AG_MG_REGS_TXD_EINTMASK_BDLENMASK_BM          0x00000400

#define AG_MG_REGS_TXD_EINTMASK_MINFRMMASK_BO         11
#define AG_MG_REGS_TXD_EINTMASK_MINFRMMASK_BM         0x00000800

#define AG_MG_REGS_TXD_EINTMASK_SOFSOFMASK_BO         12
#define AG_MG_REGS_TXD_EINTMASK_SOFSOFMASK_BM         0x00001000

#define AG_MG_REGS_TXD_EINTMASK_CROSS4KMASK_BO        13
#define AG_MG_REGS_TXD_EINTMASK_CROSS4KMASK_BM        0x00002000

#define AG_MG_REGS_TXD_EINTMASK_MAXFRMMASK_BO         14
#define AG_MG_REGS_TXD_EINTMASK_MAXFRMMASK_BM         0x00004000

#define AG_MG_REGS_TXD_EINTMASK_BLATENCYMASK_BO       15
#define AG_MG_REGS_TXD_EINTMASK_BLATENCYMASK_BM       0x00008000

#define AG_MG_REGS_TXD_EINTMASK_DLATENCYMASK_BO       16
#define AG_MG_REGS_TXD_EINTMASK_DLATENCYMASK_BM       0x00010000

#define AG_MG_REGS_TXD_EINTMASK_TXRFLOWMASK_BO        17
#define AG_MG_REGS_TXD_EINTMASK_TXRFLOWMASK_BM        0x00020000

#define AG_MG_REGS_TXD_EINTMASK_DMADROPMASK_BO        18
#define AG_MG_REGS_TXD_EINTMASK_DMADROPMASK_BM        0x00040000

#define AG_MG_REGS_TXD_EINTMASK_MACDROPMASK_BO        19
#define AG_MG_REGS_TXD_EINTMASK_MACDROPMASK_BM        0x00080000

#define AG_MG_REGS_TXD_EINTMASK_CCFOVMASK_BO          20
#define AG_MG_REGS_TXD_EINTMASK_CCFOVMASK_BM          0x00100000

#define AG_MG_REGS_TXD_EINTMASK_UNSCHEDMASK_BO        21
#define AG_MG_REGS_TXD_EINTMASK_UNSCHEDMASK_BM        0x00200000

#define AG_MG_REGS_TXD_EINTMASK_BDFFERRMASK_BO        22
#define AG_MG_REGS_TXD_EINTMASK_BDFFERRMASK_BM        0x00400000

#define AG_MG_REGS_TXD_EINTMASK_AXIRERRDMASK_BO       23
#define AG_MG_REGS_TXD_EINTMASK_AXIRERRDMASK_BM       0x00800000

#define AG_MG_REGS_TXD_EINTMASK_INVALIDQMASK_BO       24
#define AG_MG_REGS_TXD_EINTMASK_INVALIDQMASK_BM       0x01000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_EINTMASK_U
{
    struct
    {
        ag_mg_regs_register
            bdtsmask : 1,
            bdtemask : 1,
            bdtumask : 1,
            fifoovmask : 1,
            fifounmask : 1,
            trfovmask : 1,
            trfunmask : 1,
            axiwerrmask : 1,
            axirerrmask : 1,
            bdlimmask : 1,
            bdlenmask : 1,
            minfrmmask : 1,
            sofsofmask : 1,
            cross4kmask : 1,
            maxfrmmask : 1,
            blatencymask : 1,
            dlatencymask : 1,
            txrflowmask : 1,
            dmadropmask : 1,
            macdropmask : 1,
            ccfovmask : 1,
            unschedmask : 1,
            bdfferrmask : 1,
            axirerrdmask : 1,
            invalidqmask : 1,
            fill0 : 7;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_eintmask_u;
#endif


/*
 * TXD_QFCOUNT (Queue TX Frame Transmitted Count)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_TXD_QFCOUNT_RO                     0x00000818
#define AG_MG_REGS_TXD_QFCOUNT_RM                     0xFFFFFFFF
#define AG_MG_REGS_TXD_QFCOUNT_RPT                    9
#define AG_MG_REGS_TXD_QFCOUNT_IVL                    0x40

#define AG_MG_REGS_TXD_QFCOUNT_QFCOUNT_BO             0
#define AG_MG_REGS_TXD_QFCOUNT_QFCOUNT_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TXD_QFCOUNT_U
{
    struct
    {
        ag_mg_regs_register
            qfcount ;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_txd_qfcount_u ;
#endif

/*
* Physical register addresses for accessing TXDp, where p = 0 or 1)
*/
/*
 * Physical register addresses (for arm accessing txd)
 */
#ifdef AG_MG_REGS_BUILT_FOR_DSS
#define AG_MG_REGS_TXD_BASE		0xC3043000
#else
#define AG_MG_REGS_TXD_BASE		0x30043000
#endif

#define AG_MG_REGS_TXD_REG(p,ro)		(AG_MG_REGS_TXD_BASE+(0x8000*(p)+(ro)))

#define AG_MG_REGS_TXD_START_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_START_RO)
#define AG_MG_REGS_TXD_CONFIG_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_CONFIG_RO)
#define AG_MG_REGS_TXD_STATUS_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_STATUS_RO)
#define AG_MG_REGS_TXD_BLEN_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_BLEN_RO)
#define AG_MG_REGS_TXD_FIFOWM_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_FIFOWM_RO)
#define AG_MG_REGS_TXD_TRFWM_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_TRFWM_RO)
#define AG_MG_REGS_TXD_EINTTEST_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_EINTTEST_RO)
#define AG_MG_REGS_TXD_FINTMASK_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_FINTMASK_RO)
#define AG_MG_REGS_TXD_FINTTEST_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_FINTTEST_RO)
#define AG_MG_REGS_TXD_BDTSCNT_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_BDTSCNT_RO)
#define AG_MG_REGS_TXD_BDTECNT_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_BDTECNT_RO)
#define AG_MG_REGS_TXD_BDTUCNT_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_BDTUCNT_RO)
#define AG_MG_REGS_TXD_FIFORD0_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_FIFORD0_RO)
#define AG_MG_REGS_TXD_FIFORD1_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_FIFORD1_RO)
#define AG_MG_REGS_TXD_CTLRD_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_CTLRD_RO)
#define AG_MG_REGS_TXD_TRFRD0_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_TRFRD0_RO)
#define AG_MG_REGS_TXD_TRFRD1_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_TRFRD1_RO)
#define AG_MG_REGS_TXD_TRCTLRD_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_TRCTLRD_RO)
#define AG_MG_REGS_TXD_FIFOTSTRD_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_FIFOTSTRD_RO)
#define AG_MG_REGS_TXD_LATENCY_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_LATENCY_RO)
#define AG_MG_REGS_TXD_MAXFRM_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_MAXFRM_RO)
#define AG_MG_REGS_TXD_DMARATE_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_DMARATE_RO)
#define AG_MG_REGS_TXD_TRARB_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_TRARB_RO)
#define AG_MG_REGS_TXD_FLOWCON_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_FLOWCON_RO)
#define AG_MG_REGS_TXD_DROPCNT_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_DROPCNT_RO)
#define AG_MG_REGS_TXD_REGKEY_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_REGKEY_RO)
#define AG_MG_REGS_TXD_SCHEDCFG_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_SCHEDCFG_RO)
#define AG_MG_REGS_TXD_FCOUNT_RA(p)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_FCOUNT_RO)
#define AG_MG_REGS_TXD_SCHED_RA(p, n)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_SCHED_RO+0x4*(n))
#define AG_MG_REGS_TXD_QCTL_RA(p,q)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_QCTL_RO)+((q)*0x40)
#define AG_MG_REGS_TXD_BDBASE_RA(p,q)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_BDBASE_RO)+((q)*0x40)
#define AG_MG_REGS_TXD_BDLIMIT_RA(p,q)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_BDLIMIT_RO)+((q)*0x40)
#define AG_MG_REGS_TXD_BDPTR_RA(p,q)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_BDPTR_RO)+((q)*0x40)
#define AG_MG_REGS_TXD_EINTSTAT_RA(p,q)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_EINTSTAT_RO)+((q)*0x40)
#define AG_MG_REGS_TXD_EINTMASK_RA(p,q)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_EINTMASK_RO)+((q)*0x40)
#define AG_MG_REGS_TXD_QFCOUNT_RA(p,q)	AG_MG_REGS_TXD_REG(p,AG_MG_REGS_TXD_QFCOUNT_RO)+((q)*0x40)


#ifdef AG_MG_REGS_USE_C_STRUCTURES

typedef struct AG_MG_REGS_TXD_QUE_S
{
	ag_mg_regs_register			RESERVED[9] ;
	ag_mg_regs_txd_qctl_u		txd_qctl ;
	ag_mg_regs_txd_bdbase_u		txd_bdbase ;
	ag_mg_regs_txd_bdlimit_u	txd_bdlimit ;
	ag_mg_regs_txd_bdptr_u		txd_bdptr ;
	ag_mg_regs_txd_eintstat_u	txd_eintstat ;
	ag_mg_regs_txd_eintmask_u	txd_eintmask ;
	ag_mg_regs_txd_qfcount_u	txd_qfcount ;
}ag_mg_regs_txd_que_s ;

typedef struct AG_MG_REGS_TXD_REGS_S
{
	ag_mg_regs_txd_start_u	txd_start ;
	ag_mg_regs_txd_config_u	txd_config ;
	ag_mg_regs_txd_status_u	txd_status ;
	ag_mg_regs_txd_blen_u	txd_blen ;
	ag_mg_regs_txd_fifowm_u	txd_fifowm ;
	ag_mg_regs_txd_trfwm_u	txd_trfwm ;
	ag_mg_regs_txd_einttest_u	txd_einttest ;
	ag_mg_regs_txd_fintmask_u	txd_fintmask ;
	ag_mg_regs_txd_finttest_u	txd_finttest ;
	ag_mg_regs_txd_bdtscnt_u	txd_bdtscnt ;
	ag_mg_regs_txd_bdtecnt_u	txd_bdtecnt ;
	ag_mg_regs_txd_bdtucnt_u	txd_bdtucnt ;
	ag_mg_regs_txd_fiford0_u	txd_fiford0 ;
	ag_mg_regs_txd_fiford1_u	txd_fiford1 ;
	ag_mg_regs_txd_ctlrd_u	txd_ctlrd ;
	ag_mg_regs_txd_trfrd0_u	txd_trfrd0 ;
	ag_mg_regs_txd_trfrd1_u	txd_trfrd1 ;
	ag_mg_regs_txd_trctlrd_u	txd_trctlrd ;
	ag_mg_regs_txd_fifotstrd_u	txd_fifotstrd ;
	ag_mg_regs_txd_latency_u	txd_latency ;
	ag_mg_regs_txd_maxfrm_u	txd_maxfrm ;
	ag_mg_regs_txd_dmarate_u	txd_dmarate ;
	ag_mg_regs_txd_trarb_u	txd_trarb ;
	ag_mg_regs_txd_flowcon_u	txd_flowcon ;
	ag_mg_regs_txd_dropcnt_u	txd_dropcnt ;
	ag_mg_regs_txd_regkey_u	txd_regkey ;
	ag_mg_regs_txd_schedcfg_u	txd_schedcfg ;
	ag_mg_regs_txd_fcount_u	txd_fcount ;
	ag_mg_regs_register		RESERVED_1[36] ;
	ag_mg_regs_txd_sched_u	txd_sched[AG_MG_REGS_TXD_SCHED_RPT] ;
	ag_mg_regs_register		RESERVED_2[435] ;
	ag_mg_regs_txd_que_s 	txd_q[9];
} ag_mg_regs_txd_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_txd_reg_s *txdM_regs =
*       (volatile ag_mg_regs_txd_reg_s *)(AG_MG_REGS_TXD_BASE + (0x8000*M));
* where M = 0 or 1
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_txd.h,v $
Revision 1.2  2017/07/28 07:58:35  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:29  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

