/* $Id: ag_mg_regs_gttimer.h,v 1.2 2017/07/28 07:58:34 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_gttimer.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_gttimer.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_gttimer.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of LSI Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * Each Global Timer (GT) has three modes:
 *	- Interrupt Mode: In this mode, the rising edge of the Global Sync (GTSYNC*)
 *	  is used to trigger an interrupt.
 *	- Counter Mode: In this mode, the rising edge of the Global Sync (GTSYNC*)
 *	  is used to increment the Global Timer. If the count mode is selected, the
 *	  GT continues to count without generating an interrupt. If the count mode
 *	  is not selected, the GT counts up to the preprogrammed value in the Global
 *	  Timer Load Register, resets the Global Timer, and generates an interrupt.
 *	- Timer Mode: In this mode the rising edge of the Global Sync (GTSYNC*) is
 *	  used to reload the GT with the value in the Global Timer Load Register.
 *	  The GT then decrements until the timer reaches zero, reloads the value in
 *	  the Global Timer Load Register, and generates an interrupt
 * 
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *  GTIMER_0
 *  GTIMER_1
 *  GTCTL
 *  GTLOAD_0
 *  GTLOAD_1
 *
 * Prefix naming conventions :
 *   AG_MG_REGS_XXX_RA : register/memory physical address
 *   AG_MG_REGS_XXX_RO : register/memory address offset
 *   AG_MG_REGS_XXX_RM : register mask
 *   AG_MG_REGS_XXX_BO : bit/field offset from LSB
 *   AG_MG_REGS_XXX_BM : bit/field mask
 *   AG_MG_REGS_XXX_U  : bitfields in C union typedef
 *   AG_MG_REGS_XXX_S  : registers in C struct typedef
 *   AG_MG_REGS_XX_RPT : number of identical registers in array
 *   AG_MG_REGS_XX_IVL : interval between registers in array
 *
 * NOTE: user may redefine ag_mg_regs_register
 *       in ag_mg_regs_regops.h if necessary
 * NOTE: access mode of individual bit fields matches that
 *       of containing register unless indicated otherwise
 */

#ifndef AG_MG_REGS_GTTIMER_REGISTERS_H
#define AG_MG_REGS_GTTIMER_REGISTERS_H

#include "ag_mg_regs_regops.h"

/*
 * Generated by HSI Designer release 2.3.5.
 */

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_GTIMER_0_RO              0x00000000
#define AG_MG_REGS_GTIMER_0_RM              0xFFFFFFFF

#define AG_MG_REGS_GTIMER_0_GTIMER_0_BO    0
#define AG_MG_REGS_GTIMER_0_GTIMER_0_BM    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_GTIMER_0_U
{
    struct
    {
        ag_mg_regs_register
            gtimer_0;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_gtimer_0_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_GTIMER_1_RO              0x00000004
#define AG_MG_REGS_GTIMER_1_RM              0xFFFFFFFF

#define AG_MG_REGS_GTIMER_1_GTIMER_1_BO    0
#define AG_MG_REGS_GTIMER_1_GTIMER_1_BM    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_GTIMER_1_U
{
    struct
    {
        ag_mg_regs_register
            gtimer_1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_gtimer_1_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_GTCTL_RO                 0x00000008
#define AG_MG_REGS_GTCTL_RM                 0x0000007F

#define AG_MG_REGS_GTCTL_GTMODE_BO          0
#define AG_MG_REGS_GTCTL_GTMODE_BM          0x00000003

#define AG_MG_REGS_GTCTL_GTMASK_BO          2
#define AG_MG_REGS_GTCTL_GTMASK_BM          0x00000004

#define AG_MG_REGS_GTCTL_GTCNTSEL_BO        3
#define AG_MG_REGS_GTCTL_GTCNTSEL_BM        0x00000008

#define AG_MG_REGS_GTCTL_GTTIMCLK_BO        4
#define AG_MG_REGS_GTCTL_GTTIMCLK_BM        0x00000010

#define AG_MG_REGS_GTCTL_GTRAWSTAT_BO       5
#define AG_MG_REGS_GTCTL_GTRAWSTAT_BM       0x00000020

#define AG_MG_REGS_GTCTL_GTRST_BO           6
#define AG_MG_REGS_GTCTL_GTRST_BM           0x00000040

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_GTCTL_U
{
    struct
    {
        ag_mg_regs_register
            gtmode : 2,
            gtmask : 1,
            gtcntsel : 1,
            gttimclk : 1,
            gtrawstat : 1,
            gtrst : 1,
            fill0 : 25;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_gtctl_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_GTLOAD_0_RO              0x00000010
#define AG_MG_REGS_GTLOAD_0_RM              0xFFFFFFFF

#define AG_MG_REGS_GTLOAD_0_GTLOAD_0_BO    0
#define AG_MG_REGS_GTLOAD_0_GTLOAD_0_BM    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_GTLOAD_0_U
{
    struct
    {
        ag_mg_regs_register
            gtload_0;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_gtload_0_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_GTLOAD_1_RO              0x00000014
#define AG_MG_REGS_GTLOAD_1_RM              0xFFFFFFFF

#define AG_MG_REGS_GTLOAD_1_GTLOAD_1_BO    0
#define AG_MG_REGS_GTLOAD_1_GTLOAD_1_BM    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_GTLOAD_1_U
{
    struct
    {
        ag_mg_regs_register
            gtload_1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_gtload_1_u;
#endif


/*
 * Physical register addresses (for arm accessing gttimer)
 */
#define AG_MG_REGS_GTTIMER_BASE		0x98013000
#define AG_MG_REGS_GTTIMER_RPT		2
#define AG_MG_REGS_GTTIMER_REG(p,ro)		(AG_MG_REGS_GTTIMER_BASE+(ro)+((p)*0x20))

#define AG_MG_REGS_GTTIMER_GTIMER_0_RA(p)	AG_MG_REGS_GTTIMER_REG(p,AG_MG_REGS_GTIMER_0_RO)
#define AG_MG_REGS_GTTIMER_GTIMER_1_RA(p)	AG_MG_REGS_GTTIMER_REG(p,AG_MG_REGS_GTIMER_1_RO)
#define AG_MG_REGS_GTTIMER_GTCTL_RA(p)	AG_MG_REGS_GTTIMER_REG(p,AG_MG_REGS_GTCTL_RO)
#define AG_MG_REGS_GTTIMER_GTLOAD_0_RA(p)	AG_MG_REGS_GTTIMER_REG(p,AG_MG_REGS_GTLOAD_0_RO)
#define AG_MG_REGS_GTTIMER_GTLOAD_1_RA(p)	AG_MG_REGS_GTTIMER_REG(p,AG_MG_REGS_GTLOAD_1_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_GTTIMER_S
{
	ag_mg_regs_gtimer_0_u	gtimer_0 ;
	ag_mg_regs_gtimer_1_u	gtimer_1 ;
	ag_mg_regs_gtctl_u	gtctl ;
	ag_mg_regs_register	fill0 ;
	ag_mg_regs_gtload_0_u	gtload_0 ;
	ag_mg_regs_gtload_1_u	gtload_1 ;
	ag_mg_regs_register	fill1[2] ;
} ag_mg_regs_gttimer_s ;

typedef struct AG_MG_REGS_GTTIMER_REG_S
{
	ag_mg_regs_gttimer_s gttimer[AG_MG_REGS_GTTIMER_RPT];
} ag_mg_regs_gttimer_reg_s;
/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_gttimer_reg_s *gttimer_regs =
*       (volatile ag_mg_regs_gttimer_reg_s *)AG_MG_REGS_GTTIMER_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_gttimer.h,v $
Revision 1.2  2017/07/28 07:58:34  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:25  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:25  srane
Initial checkin


$Endlog$
*/

