/* $Id: ag_mg_regs_srio_grio.h,v 1.2 2017/07/28 07:58:34 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_srio_grio.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_srio_grio.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_srio_grio.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of LSI Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * The SRIO solution consists of three blocks
 *  - generic SRIO core, called GRIO (Generic Rapid IO), this file
 *  - AXI bridge component, called RAB (RIO-AXI Bridge), ag_mg_regs_srio_rab.h
 *  - and a Serializer / Deseserializer (SerDes), ag_mg_regs_serdes.h
 * 
 * The GRIO core is partitioned into inbound and outbound blocks, and these
 * blocks are further partitioned into three implementation layers:
 * physical coding sublayer (PCS), physical protocol, and logical.
 *
 * The GRIO Outbound block is partitioned in logical outbound, physical
 * outbound and transmitter. Logical outbound block implements the functionality
 * of RIO logical layer and transport layer specification.
 *  
 * The GRIO inbound block consists of the receiver, physical PCS block, physical
 * protocol block and logical inbound block. The logical inbound block performs
 * the logical error checks on incoming packets. The result of error check is
 * logged in to the logical error extension registers. Logical inbound block
 * uses the store-and-forward buffer to store the received packets. Once the
 * entire packet is received, the ULI request is generated to inform UL about
 * the packet availability in GRIO.
 *
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *
 *  DIDCAR
 *  DICAR
 *  AIDCAR
 *  AICAR
 *  PEFCAR
 *  SOCAR
 *  DOCAR
 *  PELLCCSR
 *  LCSBA1CSR
 *  BDIDCSR
 *  HBDIDLCSR
 *  CTCSR
 *  PMBH0
 *  PLTOCCSR
 *  PRTOCCSR
 *  PGCSSR
 *  P0LMREQCSR
 *  P0LMRESPCSR
 *  P0LASCSR
 *  P0ESCSR
 *  P0CCSR
 *  ERBH
 *  LTLEDCSR
 *  LTLEECSR
 *  LTLACCSR
 *  LTLDIDCCSR
 *  LTLCCCSR
 *  P0EDCSR
 *  P0ERECSR
 *  P0ECACCSR
 *  P0PCSECCSR0
 *  P0PCSECCSR1
 *  P0PCSECCSR2
 *  P0PCSECCSR3
 *  P0ERCSR
 *  P0ERTCSR
 *  PNR
 *  LLCR
 *  EPWISR
 *  PRETCR
 *  P0ADIDCSR
 *  P0PTAACR
 *  P0IECSR
 *  P0PCR
 *  P0SLCSR
 *  P0SLEICR
 *  P0LLDMR
 *  P0PLDMR
 *  P0PLCTMR
 *  P0LLCTMR
 *  IPBRR1
 *  IPBRR2
*
* Prefix naming conventions :
*   AG_MG_REGS_XXX_RA : register/memory physical address
*   AG_MG_REGS_XXX_RO : register/memory address offset
*   AG_MG_REGS_XXX_RM : register mask
*   AG_MG_REGS_XXX_BO : bit/field offset from LSB
*   AG_MG_REGS_XXX_BM : bit/field mask
*   AG_MG_REGS_XXX_U  : bitfields in C union typedef
*   AG_MG_REGS_XXX_S  : registers in C struct typedef
*   AG_MG_REGS_XX_RPT : number of identical registers in array
*   AG_MG_REGS_XX_IVL : interval between registers in array
*
* NOTE: user may redefine ag_mg_regs_register
*       in ag_mg_regs_regops.h if necessary
* NOTE: access mode of individual bit fields matches that
*       of containing register unless indicated otherwise
*/

#ifndef AG_MG_REGS_SRIO_GRIO_REGISTERS_H
#define AG_MG_REGS_SRIO_GRIO_REGISTERS_H

#include "ag_mg_regs_regops.h"


/*
 * Generated by HSI Designer release 2.3.5.
 */


/*
 * DIDCAR (Device Identity Capability Register)
 * Initialization value: 0x2601000A  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DIDCAR_RO                 0x00000000
#define AG_MG_REGS_DIDCAR_RM                 0xFFFFFFFF

#define AG_MG_REGS_DIDCAR_DVI_BO             0
#define AG_MG_REGS_DIDCAR_DVI_BM             0x0000FFFF

#define AG_MG_REGS_DIDCAR_DI_BO              16
#define AG_MG_REGS_DIDCAR_DI_BM              0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DIDCAR_U
{
    struct
    {
        ag_mg_regs_register
            dvi : 16,
            di : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_didcar_u;
#endif


/*
 * DICAR (Device Information Capability Register)
 * Initialization value: 0x00000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DICAR_RO                  0x00000004
#define AG_MG_REGS_DICAR_RM                  0xFFFFFFFF

#define AG_MG_REGS_DICAR_DR_BO               0
#define AG_MG_REGS_DICAR_DR_BM               0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DICAR_U
{
    struct
    {
        ag_mg_regs_register
            dr;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dicar_u;
#endif


/*
 * AIDCAR (Assembly Identity Capability Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_AIDCAR_RO                 0x00000008
#define AG_MG_REGS_AIDCAR_RM                 0xFFFFFFFF

#define AG_MG_REGS_AIDCAR_AVI_BO             0
#define AG_MG_REGS_AIDCAR_AVI_BM             0x0000FFFF

#define AG_MG_REGS_AIDCAR_AI_BO              16
#define AG_MG_REGS_AIDCAR_AI_BM              0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_AIDCAR_U
{
    struct
    {
        ag_mg_regs_register
            avi : 16,
            ai : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_aidcar_u;
#endif


/*
 * AICAR (Assembly Information Capability Register)
 * Initialization value: 0x00000100  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_AICAR_RO                  0x0000000C
#define AG_MG_REGS_AICAR_RM                  0xFFFFFFFF

#define AG_MG_REGS_AICAR_EFP_BO              0
#define AG_MG_REGS_AICAR_EFP_BM              0x0000FFFF

#define AG_MG_REGS_AICAR_AR_BO               16
#define AG_MG_REGS_AICAR_AR_BM               0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_AICAR_U
{
    struct
    {
        ag_mg_regs_register
            efp : 16,
            ar : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_aicar_u;
#endif


/*
 * PEFCAR (Processing Element Features Capability Register)
 * Initialization value: 0xE0F80089  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_PEFCAR_RO                 0x00000010
#define AG_MG_REGS_PEFCAR_RM                 0xF0F800FF

#define AG_MG_REGS_PEFCAR_EAS_BO             0
#define AG_MG_REGS_PEFCAR_EAS_BM             0x00000007

#define AG_MG_REGS_PEFCAR_EF_BO              3
#define AG_MG_REGS_PEFCAR_EF_BM              0x00000008

#define AG_MG_REGS_PEFCAR_CTLS_BO            4
#define AG_MG_REGS_PEFCAR_CTLS_BM            0x00000010

#define AG_MG_REGS_PEFCAR_CRF_BO             5
#define AG_MG_REGS_PEFCAR_CRF_BM             0x00000020

#define AG_MG_REGS_PEFCAR_RSM_BO             6
#define AG_MG_REGS_PEFCAR_RSM_BM             0x00000040

#define AG_MG_REGS_PEFCAR_FCS_BO             7
#define AG_MG_REGS_PEFCAR_FCS_BM             0x00000080

#define AG_MG_REGS_PEFCAR_DB_BO              19
#define AG_MG_REGS_PEFCAR_DB_BM              0x00080000

#define AG_MG_REGS_PEFCAR_MB_BO              20
#define AG_MG_REGS_PEFCAR_MB_BM              0x00F00000

#define AG_MG_REGS_PEFCAR_SW_BO              28
#define AG_MG_REGS_PEFCAR_SW_BM              0x10000000

#define AG_MG_REGS_PEFCAR_PROC_BO            29
#define AG_MG_REGS_PEFCAR_PROC_BM            0x20000000

#define AG_MG_REGS_PEFCAR_MEM_BO             30
#define AG_MG_REGS_PEFCAR_MEM_BM             0x40000000

#define AG_MG_REGS_PEFCAR_BR_BO              31
#define AG_MG_REGS_PEFCAR_BR_BM              0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PEFCAR_U
{
    struct
    {
        ag_mg_regs_register
            eas : 3,
            ef : 1,
            ctls : 1,
            crf : 1,
            rsm : 1,
            fcs : 1,
            fill1 : 11,
            db : 1,
            mb : 4,
            fill0 : 4,
            sw : 1,
            proc : 1,
            mem : 1,
            br : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pefcar_u;
#endif


/*
 * SOCAR (Source Operations Capability Register)
 * Initialization value: 0x0000FC00  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_SOCAR_RO                  0x00000018
#define AG_MG_REGS_SOCAR_RM                  0xFFC0FFFC

#define AG_MG_REGS_SOCAR_PW_BO               2
#define AG_MG_REGS_SOCAR_PW_BM               0x00000004

#define AG_MG_REGS_SOCAR_ASWAP_BO            3
#define AG_MG_REGS_SOCAR_ASWAP_BM            0x00000008

#define AG_MG_REGS_SOCAR_AC_BO               4
#define AG_MG_REGS_SOCAR_AC_BM               0x00000010

#define AG_MG_REGS_SOCAR_AS_BO               5
#define AG_MG_REGS_SOCAR_AS_BM               0x00000020

#define AG_MG_REGS_SOCAR_AD_BO               6
#define AG_MG_REGS_SOCAR_AD_BM               0x00000040

#define AG_MG_REGS_SOCAR_AI_BO               7
#define AG_MG_REGS_SOCAR_AI_BM               0x00000080

#define AG_MG_REGS_SOCAR_ATS_BO              8
#define AG_MG_REGS_SOCAR_ATS_BM              0x00000100

#define AG_MG_REGS_SOCAR_ACS_BO              9
#define AG_MG_REGS_SOCAR_ACS_BM              0x00000200

#define AG_MG_REGS_SOCAR_D_BO                10
#define AG_MG_REGS_SOCAR_D_BM                0x00000400

#define AG_MG_REGS_SOCAR_M_BO                11
#define AG_MG_REGS_SOCAR_M_BM                0x00000800

#define AG_MG_REGS_SOCAR_NWR_BO              12
#define AG_MG_REGS_SOCAR_NWR_BM              0x00001000

#define AG_MG_REGS_SOCAR_SW_BO               13
#define AG_MG_REGS_SOCAR_SW_BM               0x00002000

#define AG_MG_REGS_SOCAR_NW_BO               14
#define AG_MG_REGS_SOCAR_NW_BM               0x00004000

#define AG_MG_REGS_SOCAR_NR_BO               15
#define AG_MG_REGS_SOCAR_NR_BM               0x00008000

#define AG_MG_REGS_SOCAR_TIES_BO             22
#define AG_MG_REGS_SOCAR_TIES_BM             0x00400000

#define AG_MG_REGS_SOCAR_TIE_BO              23
#define AG_MG_REGS_SOCAR_TIE_BM              0x00800000

#define AG_MG_REGS_SOCAR_ICI_BO              24
#define AG_MG_REGS_SOCAR_ICI_BM              0x01000000

#define AG_MG_REGS_SOCAR_IOR_BO              25
#define AG_MG_REGS_SOCAR_IOR_BM              0x02000000

#define AG_MG_REGS_SOCAR_F_BO                26
#define AG_MG_REGS_SOCAR_F_BM                0x04000000

#define AG_MG_REGS_SOCAR_C_BO                27
#define AG_MG_REGS_SOCAR_C_BM                0x08000000

#define AG_MG_REGS_SOCAR_DCI_BO              28
#define AG_MG_REGS_SOCAR_DCI_BM              0x10000000

#define AG_MG_REGS_SOCAR_RO_BO               29
#define AG_MG_REGS_SOCAR_RO_BM               0x20000000

#define AG_MG_REGS_SOCAR_IR_BO               30
#define AG_MG_REGS_SOCAR_IR_BM               0x40000000

#define AG_MG_REGS_SOCAR_R_BO                31
#define AG_MG_REGS_SOCAR_R_BM                0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SOCAR_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 2,
            pw : 1,
            aswap : 1,
            ac : 1,
            as : 1,
            ad : 1,
            ai : 1,
            ats : 1,
            acs : 1,
            d : 1,
            m : 1,
            nwr : 1,
            sw : 1,
            nw : 1,
            nr : 1,
            fill0 : 6,
            ties : 1,
            tie : 1,
            ici : 1,
            ior : 1,
            f : 1,
            c : 1,
            dci : 1,
            ro : 1,
            ir : 1,
            r : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_socar_u;
#endif


/*
 * DOCAR (Destination Operations Capability Register)
 * Initialization value: 0x0000FC04  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DOCAR_RO                  0x0000001C
#define AG_MG_REGS_DOCAR_RM                  0xFFC0FFFC

#define AG_MG_REGS_DOCAR_PW_BO               2
#define AG_MG_REGS_DOCAR_PW_BM               0x00000004

#define AG_MG_REGS_DOCAR_ASWAP_BO            3
#define AG_MG_REGS_DOCAR_ASWAP_BM            0x00000008

#define AG_MG_REGS_DOCAR_AC_BO               4
#define AG_MG_REGS_DOCAR_AC_BM               0x00000010

#define AG_MG_REGS_DOCAR_AS_BO               5
#define AG_MG_REGS_DOCAR_AS_BM               0x00000020

#define AG_MG_REGS_DOCAR_AD_BO               6
#define AG_MG_REGS_DOCAR_AD_BM               0x00000040

#define AG_MG_REGS_DOCAR_AI_BO               7
#define AG_MG_REGS_DOCAR_AI_BM               0x00000080

#define AG_MG_REGS_DOCAR_ATS_BO              8
#define AG_MG_REGS_DOCAR_ATS_BM              0x00000100

#define AG_MG_REGS_DOCAR_ACS_BO              9
#define AG_MG_REGS_DOCAR_ACS_BM              0x00000200

#define AG_MG_REGS_DOCAR_D_BO                10
#define AG_MG_REGS_DOCAR_D_BM                0x00000400

#define AG_MG_REGS_DOCAR_M_BO                11
#define AG_MG_REGS_DOCAR_M_BM                0x00000800

#define AG_MG_REGS_DOCAR_NWR_BO              12
#define AG_MG_REGS_DOCAR_NWR_BM              0x00001000

#define AG_MG_REGS_DOCAR_SW_BO               13
#define AG_MG_REGS_DOCAR_SW_BM               0x00002000

#define AG_MG_REGS_DOCAR_NW_BO               14
#define AG_MG_REGS_DOCAR_NW_BM               0x00004000

#define AG_MG_REGS_DOCAR_NR_BO               15
#define AG_MG_REGS_DOCAR_NR_BM               0x00008000

#define AG_MG_REGS_DOCAR_TIES_BO             22
#define AG_MG_REGS_DOCAR_TIES_BM             0x00400000

#define AG_MG_REGS_DOCAR_TIE_BO              23
#define AG_MG_REGS_DOCAR_TIE_BM              0x00800000

#define AG_MG_REGS_DOCAR_ICI_BO              24
#define AG_MG_REGS_DOCAR_ICI_BM              0x01000000

#define AG_MG_REGS_DOCAR_IOR_BO              25
#define AG_MG_REGS_DOCAR_IOR_BM              0x02000000

#define AG_MG_REGS_DOCAR_F_BO                26
#define AG_MG_REGS_DOCAR_F_BM                0x04000000

#define AG_MG_REGS_DOCAR_C_BO                27
#define AG_MG_REGS_DOCAR_C_BM                0x08000000

#define AG_MG_REGS_DOCAR_DCI_BO              28
#define AG_MG_REGS_DOCAR_DCI_BM              0x10000000

#define AG_MG_REGS_DOCAR_RO_BO               29
#define AG_MG_REGS_DOCAR_RO_BM               0x20000000

#define AG_MG_REGS_DOCAR_IR_BO               30
#define AG_MG_REGS_DOCAR_IR_BM               0x40000000

#define AG_MG_REGS_DOCAR_R_BO                31
#define AG_MG_REGS_DOCAR_R_BM                0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DOCAR_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 2,
            pw : 1,
            aswap : 1,
            ac : 1,
            as : 1,
            ad : 1,
            ai : 1,
            ats : 1,
            acs : 1,
            d : 1,
            m : 1,
            nwr : 1,
            sw : 1,
            nw : 1,
            nr : 1,
            fill0 : 6,
            ties : 1,
            tie : 1,
            ici : 1,
            ior : 1,
            f : 1,
            c : 1,
            dci : 1,
            ro : 1,
            ir : 1,
            r : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_docar_u;
#endif


/*
 * PELLCCSR (Processing Element Logical layer Control and Status Register)
 * Initialization value: 0x00000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_PELLCCSR_RO               0x0000004C
#define AG_MG_REGS_PELLCCSR_RM               0x00000007

#define AG_MG_REGS_PELLCCSR_EAC_BO           0
#define AG_MG_REGS_PELLCCSR_EAC_BM           0x00000007

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PELLCCSR_U
{
    struct
    {
        ag_mg_regs_register
            eac : 3,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pellccsr_u;
#endif


/*
 * LCSBA1CSR (Local Configuration Space Base Address 1 Cmd. and Stat. Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LCSBA1CSR_RO              0x0000005C
#define AG_MG_REGS_LCSBA1CSR_RM              0x7FFE0000

#define AG_MG_REGS_LCSBA1CSR_LCSBA_BO        17
#define AG_MG_REGS_LCSBA1CSR_LCSBA_BM        0x7FFE0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_LCSBA1CSR_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 17,
            lcsba : 14,
            fill0 : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_lcsba1csr_u;
#endif


/*
 * BDIDCSR (Base Device ID Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_BDIDCSR_RO                0x00000060
#define AG_MG_REGS_BDIDCSR_RM                0x00FFFFFF

#define AG_MG_REGS_BDIDCSR_LBDID_BO          0
#define AG_MG_REGS_BDIDCSR_LBDID_BM          0x0000FFFF

#define AG_MG_REGS_BDIDCSR_BDID_BO           16
#define AG_MG_REGS_BDIDCSR_BDID_BM           0x00FF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_BDIDCSR_U
{
    struct
    {
        ag_mg_regs_register
            lbdid : 16,
            bdid : 8,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_bdidcsr_u;
#endif


/*
 * HBDIDLCSR (Host Base Device ID Lock Command and Status Register)
 * Initialization value: 0x0000FFFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_HBDIDLCSR_RO              0x00000068
#define AG_MG_REGS_HBDIDLCSR_RM              0x0000FFFF

#define AG_MG_REGS_HBDIDLCSR_HBDID_BO        0
#define AG_MG_REGS_HBDIDLCSR_HBDID_BM        0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_HBDIDLCSR_U
{
    struct
    {
        ag_mg_regs_register
            hbdid : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_hbdidlcsr_u;
#endif


/*
 * CTCSR (Component Tag Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CTCSR_RO                  0x0000006C
#define AG_MG_REGS_CTCSR_RM                  0xFFFFFFFF

#define AG_MG_REGS_CTCSR_CT_BO               0
#define AG_MG_REGS_CTCSR_CT_BM               0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CTCSR_U
{
    struct
    {
        ag_mg_regs_register
            ct;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ctcsr_u;
#endif


/*
 * PMBH0 (Port Maintenance Block Header 0)
 * Initialization value: 0x06000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_PMBH0_RO                  0x00000100
#define AG_MG_REGS_PMBH0_RM                  0xFFFFFFFF

#define AG_MG_REGS_PMBH0_EF_ID_BO            0
#define AG_MG_REGS_PMBH0_EF_ID_BM            0x0000FFFF

#define AG_MG_REGS_PMBH0_EF_PTR_BO           16
#define AG_MG_REGS_PMBH0_EF_PTR_BM           0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PMBH0_U
{
    struct
    {
        ag_mg_regs_register
            ef_id : 16,
            ef_ptr : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pmbh0_u;
#endif


/*
 * PLTOCCSR (Port Link Time-Out control Command and Status Register)
 * Initialization value: 0xFFFFFF00  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PLTOCCSR_RO               0x00000120
#define AG_MG_REGS_PLTOCCSR_RM               0xFFFFFF00

#define AG_MG_REGS_PLTOCCSR_TV_BO            8
#define AG_MG_REGS_PLTOCCSR_TV_BM            0xFFFFFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PLTOCCSR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 8,
            tv : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pltoccsr_u;
#endif


/*
 * PRTOCCSR (Port Response Time-Out Control Command and Status Register)
 * Initialization value: 0xFFFFFF00  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PRTOCCSR_RO               0x00000124
#define AG_MG_REGS_PRTOCCSR_RM               0xFFFFFF00

#define AG_MG_REGS_PRTOCCSR_TV_BO            8
#define AG_MG_REGS_PRTOCCSR_TV_BM            0xFFFFFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PRTOCCSR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 8,
            tv : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_prtoccsr_u;
#endif


/*
 * PGCSSR (Port General Control Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PGCSSR_RO                 0x0000013C
#define AG_MG_REGS_PGCSSR_RM                 0xE0000000

#define AG_MG_REGS_PGCSSR_D_BO               29
#define AG_MG_REGS_PGCSSR_D_BM               0x20000000

#define AG_MG_REGS_PGCSSR_M_BO               30
#define AG_MG_REGS_PGCSSR_M_BM               0x40000000

#define AG_MG_REGS_PGCSSR_H_BO               31
#define AG_MG_REGS_PGCSSR_H_BM               0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PGCSSR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 29,
            d : 1,
            m : 1,
            h : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pgcssr_u;
#endif


/*
 * P0LMREQCSR (Port 0 Link Maintenance Request Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0LMREQCSR_RO             0x00000140
#define AG_MG_REGS_P0LMREQCSR_RM             0x00000007

#define AG_MG_REGS_P0LMREQCSR_C_BO           0
#define AG_MG_REGS_P0LMREQCSR_C_BM           0x00000007

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0LMREQCSR_U
{
    struct
    {
        ag_mg_regs_register
            c : 3,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0lmreqcsr_u;
#endif


/*
 * P0LMRESPCSR (Port 0 Link Maintenance Response Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_P0LMRESPCSR_RO            0x00000144
#define AG_MG_REGS_P0LMRESPCSR_RM            0x800003FF

#define AG_MG_REGS_P0LMRESPCSR_LS_BO         0
#define AG_MG_REGS_P0LMRESPCSR_LS_BM         0x0000001F

#define AG_MG_REGS_P0LMRESPCSR_AS_BO         5
#define AG_MG_REGS_P0LMRESPCSR_AS_BM         0x000003E0

#define AG_MG_REGS_P0LMRESPCSR_RV_BO         31
#define AG_MG_REGS_P0LMRESPCSR_RV_BM         0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0LMRESPCSR_U
{
    struct
    {
        ag_mg_regs_register
            ls : 5,
            as : 5,
            fill0 : 21,
            rv : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0lmrespcsr_u;
#endif


/*
 * P0LASCSR (Port 0 Link Local ackID Status Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0LASCSR_RO               0x00000148
#define AG_MG_REGS_P0LASCSR_RM               0x1F001F1F

#define AG_MG_REGS_P0LASCSR_OBA_BO           0
#define AG_MG_REGS_P0LASCSR_OBA_BM           0x0000001F

#define AG_MG_REGS_P0LASCSR_OUTA_BO          8
#define AG_MG_REGS_P0LASCSR_OUTA_BM          0x00001F00

#define AG_MG_REGS_P0LASCSR_IA_BO            24
#define AG_MG_REGS_P0LASCSR_IA_BM            0x1F000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0LASCSR_U
{
    struct
    {
        ag_mg_regs_register
            oba : 5,
            fill2 : 3,
            outa : 5,
            fill1 : 11,
            ia : 5,
            fill0 : 3;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0lascsr_u;
#endif


/*
 * P0ESCSR (Port 0 Error and Status Command and Status Register)
 * Initialization value: 0x00000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0ESCSR_RO                0x00000158
#define AG_MG_REGS_P0ESCSR_RM                0x071F0717

#define AG_MG_REGS_P0ESCSR_PU_BO             0
#define AG_MG_REGS_P0ESCSR_PU_BM             0x00000001

#define AG_MG_REGS_P0ESCSR_PO_BO             1
#define AG_MG_REGS_P0ESCSR_PO_BM             0x00000002

#define AG_MG_REGS_P0ESCSR_PE_BO             2
#define AG_MG_REGS_P0ESCSR_PE_BM             0x00000004

#define AG_MG_REGS_P0ESCSR_PWP_BO            4
#define AG_MG_REGS_P0ESCSR_PWP_BM            0x00000010

#define AG_MG_REGS_P0ESCSR_IES_BO            8
#define AG_MG_REGS_P0ESCSR_IES_BM            0x00000100

#define AG_MG_REGS_P0ESCSR_IEE_BO            9
#define AG_MG_REGS_P0ESCSR_IEE_BM            0x00000200

#define AG_MG_REGS_P0ESCSR_IRS_BO            10
#define AG_MG_REGS_P0ESCSR_IRS_BM            0x00000400

#define AG_MG_REGS_P0ESCSR_OES_BO            16
#define AG_MG_REGS_P0ESCSR_OES_BM            0x00010000

#define AG_MG_REGS_P0ESCSR_OEE_BO            17
#define AG_MG_REGS_P0ESCSR_OEE_BM            0x00020000

#define AG_MG_REGS_P0ESCSR_ORS_BO            18
#define AG_MG_REGS_P0ESCSR_ORS_BM            0x00040000

#define AG_MG_REGS_P0ESCSR_OR_BO             19
#define AG_MG_REGS_P0ESCSR_OR_BM             0x00080000

#define AG_MG_REGS_P0ESCSR_ORE_BO            20
#define AG_MG_REGS_P0ESCSR_ORE_BM            0x00100000

#define AG_MG_REGS_P0ESCSR_ODE_BO            24
#define AG_MG_REGS_P0ESCSR_ODE_BM            0x01000000

#define AG_MG_REGS_P0ESCSR_OFE_BO            25
#define AG_MG_REGS_P0ESCSR_OFE_BM            0x02000000

#define AG_MG_REGS_P0ESCSR_OPD_BO            26
#define AG_MG_REGS_P0ESCSR_OPD_BM            0x04000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0ESCSR_U
{
    struct
    {
        ag_mg_regs_register
            pu : 1,
            po : 1,
            pe : 1,
            fill4 : 1,
            pwp : 1,
            fill3 : 3,
            ies : 1,
            iee : 1,
            irs : 1,
            fill2 : 5,
            oes : 1,
            oee : 1,
            ors : 1,
            or : 1,
            ore : 1,
            fill1 : 3,
            ode : 1,
            ofe : 1,
            opd : 1,
            fill0 : 5;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0escsr_u;
#endif


/*
 * P0CCSR (Port 0 Control Command and Status Register)
 * Initialization value: 0x00600001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0CCSR_RO                 0x0000015C
#define AG_MG_REGS_P0CCSR_RM                 0xFFFE0FFF

#define AG_MG_REGS_P0CCSR_PT_BO              0
#define AG_MG_REGS_P0CCSR_PT_BM              0x00000001

#define AG_MG_REGS_P0CCSR_PL_BO              1
#define AG_MG_REGS_P0CCSR_PL_BM              0x00000002

#define AG_MG_REGS_P0CCSR_DPE_BO             2
#define AG_MG_REGS_P0CCSR_DPE_BM             0x00000004

#define AG_MG_REGS_P0CCSR_SPF_BO             3
#define AG_MG_REGS_P0CCSR_SPF_BM             0x00000008

#define AG_MG_REGS_P0CCSR_RSM_BO             4
#define AG_MG_REGS_P0CCSR_RSM_BM             0x00000FF0

#define AG_MG_REGS_P0CCSR_EB_BO              17
#define AG_MG_REGS_P0CCSR_EB_BM              0x00020000

#define AG_MG_REGS_P0CCSR_FCP_BO             18
#define AG_MG_REGS_P0CCSR_FCP_BM             0x00040000

#define AG_MG_REGS_P0CCSR_MEP_BO             19
#define AG_MG_REGS_P0CCSR_MEP_BM             0x00080000

#define AG_MG_REGS_P0CCSR_ECD_BO             20
#define AG_MG_REGS_P0CCSR_ECD_BM             0x00100000

#define AG_MG_REGS_P0CCSR_IPE_BO             21
#define AG_MG_REGS_P0CCSR_IPE_BM             0x00200000

#define AG_MG_REGS_P0CCSR_OPE_BO             22
#define AG_MG_REGS_P0CCSR_OPE_BM             0x00400000

#define AG_MG_REGS_P0CCSR_PD_BO              23
#define AG_MG_REGS_P0CCSR_PD_BM              0x00800000

#define AG_MG_REGS_P0CCSR_PWO_BO             24
#define AG_MG_REGS_P0CCSR_PWO_BM             0x07000000

#define AG_MG_REGS_P0CCSR_IPW_BO             27
#define AG_MG_REGS_P0CCSR_IPW_BM             0x38000000

#define AG_MG_REGS_P0CCSR_PW_BO              30
#define AG_MG_REGS_P0CCSR_PW_BM              0xC0000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0CCSR_U
{
    struct
    {
        ag_mg_regs_register
            pt : 1,
            pl : 1,
            dpe : 1,
            spf : 1,
            rsm : 8,
            fill0 : 5,
            eb : 1,
            fcp : 1,
            mep : 1,
            ecd : 1,
            ipe : 1,
            ope : 1,
            pd : 1,
            pwo : 3,
            ipw : 3,
            pw : 2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0ccsr_u;
#endif


/*
 * ERBH (Error Reporting Block Header)
 * Initialization value: 0x00000007  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_ERBH_RO                   0x00000600
#define AG_MG_REGS_ERBH_RM                   0xFFFFFFFF

#define AG_MG_REGS_ERBH_EF_ID_BO             0
#define AG_MG_REGS_ERBH_EF_ID_BM             0x0000FFFF

#define AG_MG_REGS_ERBH_EF_PTR_BO            16
#define AG_MG_REGS_ERBH_EF_PTR_BM            0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ERBH_U
{
    struct
    {
        ag_mg_regs_register
            ef_id : 16,
            ef_ptr : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_erbh_u;
#endif


/*
 * LTLEDCSR (Logical/Transport Layer Error Detect Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LTLEDCSR_RO               0x00000608
#define AG_MG_REGS_LTLEDCSR_RM               0xFFC00018

#define AG_MG_REGS_LTLEDCSR_TSE_BO           3
#define AG_MG_REGS_LTLEDCSR_TSE_BM           0x00000008

#define AG_MG_REGS_LTLEDCSR_RETE_BO          4
#define AG_MG_REGS_LTLEDCSR_RETE_BM          0x00000010

#define AG_MG_REGS_LTLEDCSR_UT_BO            22
#define AG_MG_REGS_LTLEDCSR_UT_BM            0x00400000

#define AG_MG_REGS_LTLEDCSR_UR_BO            23
#define AG_MG_REGS_LTLEDCSR_UR_BM            0x00800000

#define AG_MG_REGS_LTLEDCSR_PRT_BO           24
#define AG_MG_REGS_LTLEDCSR_PRT_BM           0x01000000

#define AG_MG_REGS_LTLEDCSR_MRT_BO           25
#define AG_MG_REGS_LTLEDCSR_MRT_BM           0x02000000

#define AG_MG_REGS_LTLEDCSR_ITTE_BO          26
#define AG_MG_REGS_LTLEDCSR_ITTE_BM          0x04000000

#define AG_MG_REGS_LTLEDCSR_ITD_BO           27
#define AG_MG_REGS_LTLEDCSR_ITD_BM           0x08000000

#define AG_MG_REGS_LTLEDCSR_MFE_BO           28
#define AG_MG_REGS_LTLEDCSR_MFE_BM           0x10000000

#define AG_MG_REGS_LTLEDCSR_GER_BO           29
#define AG_MG_REGS_LTLEDCSR_GER_BM           0x20000000

#define AG_MG_REGS_LTLEDCSR_MER_BO           30
#define AG_MG_REGS_LTLEDCSR_MER_BM           0x40000000

#define AG_MG_REGS_LTLEDCSR_IER_BO           31
#define AG_MG_REGS_LTLEDCSR_IER_BM           0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_LTLEDCSR_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 3,
            tse : 1,
            rete : 1,
            fill0 : 17,
            ut : 1,
            ur : 1,
            prt : 1,
            mrt : 1,
            itte : 1,
            itd : 1,
            mfe : 1,
            ger : 1,
            mer : 1,
            ier : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ltledcsr_u;
#endif


/*
 * LTLEECSR (Logical/Transport Layer Error Enable Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LTLEECSR_RO               0x0000060C
#define AG_MG_REGS_LTLEECSR_RM               0xFFC00018

#define AG_MG_REGS_LTLEECSR_TSE_BO           3
#define AG_MG_REGS_LTLEECSR_TSE_BM           0x00000008

#define AG_MG_REGS_LTLEECSR_RETE_BO          4
#define AG_MG_REGS_LTLEECSR_RETE_BM          0x00000010

#define AG_MG_REGS_LTLEECSR_UT_BO            22
#define AG_MG_REGS_LTLEECSR_UT_BM            0x00400000

#define AG_MG_REGS_LTLEECSR_UR_BO            23
#define AG_MG_REGS_LTLEECSR_UR_BM            0x00800000

#define AG_MG_REGS_LTLEECSR_PRT_BO           24
#define AG_MG_REGS_LTLEECSR_PRT_BM           0x01000000

#define AG_MG_REGS_LTLEECSR_MRT_BO           25
#define AG_MG_REGS_LTLEECSR_MRT_BM           0x02000000

#define AG_MG_REGS_LTLEECSR_ITTE_BO          26
#define AG_MG_REGS_LTLEECSR_ITTE_BM          0x04000000

#define AG_MG_REGS_LTLEECSR_ITD_BO           27
#define AG_MG_REGS_LTLEECSR_ITD_BM           0x08000000

#define AG_MG_REGS_LTLEECSR_MFE_BO           28
#define AG_MG_REGS_LTLEECSR_MFE_BM           0x10000000

#define AG_MG_REGS_LTLEECSR_GER_BO           29
#define AG_MG_REGS_LTLEECSR_GER_BM           0x20000000

#define AG_MG_REGS_LTLEECSR_MER_BO           30
#define AG_MG_REGS_LTLEECSR_MER_BM           0x40000000

#define AG_MG_REGS_LTLEECSR_IER_BO           31
#define AG_MG_REGS_LTLEECSR_IER_BM           0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_LTLEECSR_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 3,
            tse : 1,
            rete : 1,
            fill0 : 17,
            ut : 1,
            ur : 1,
            prt : 1,
            mrt : 1,
            itte : 1,
            itd : 1,
            mfe : 1,
            ger : 1,
            mer : 1,
            ier : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ltleecsr_u;
#endif


/*
 * LTLACCSR (Logical/Transport Layer Address Capture Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LTLACCSR_RO               0x00000614
#define AG_MG_REGS_LTLACCSR_RM               0xFFFFFFFB

#define AG_MG_REGS_LTLACCSR_XA_BO            0
#define AG_MG_REGS_LTLACCSR_XA_BM            0x00000003

#define AG_MG_REGS_LTLACCSR_A_BO             3
#define AG_MG_REGS_LTLACCSR_A_BM             0xFFFFFFF8

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_LTLACCSR_U
{
    struct
    {
        ag_mg_regs_register
            xa : 2,
            fill0 : 1,
            a : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ltlaccsr_u;
#endif


/*
 * LTLDIDCCSR (Logical/Transport Layer Device ID Capture Command and Status)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LTLDIDCCSR_RO             0x00000618
#define AG_MG_REGS_LTLDIDCCSR_RM             0xFFFFFFFF

#define AG_MG_REGS_LTLDIDCCSR_SID_BO         0
#define AG_MG_REGS_LTLDIDCCSR_SID_BM         0x000000FF

#define AG_MG_REGS_LTLDIDCCSR_SIDMSB_BO      8
#define AG_MG_REGS_LTLDIDCCSR_SIDMSB_BM      0x0000FF00

#define AG_MG_REGS_LTLDIDCCSR_DID_BO         16
#define AG_MG_REGS_LTLDIDCCSR_DID_BM         0x00FF0000

#define AG_MG_REGS_LTLDIDCCSR_DIDMSB_BO      24
#define AG_MG_REGS_LTLDIDCCSR_DIDMSB_BM      0xFF000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_LTLDIDCCSR_U
{
    struct
    {
        ag_mg_regs_register
            sid : 8,
            sidmsb : 8,
            did : 8,
            didmsb : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ltldidccsr_u;
#endif


/*
 * LTLCCCSR (Logical/Transport Layer Control Capture Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LTLCCCSR_RO               0x0000061C
#define AG_MG_REGS_LTLCCCSR_RM               0xFFFF0000

#define AG_MG_REGS_LTLCCCSR_MI_BO            16
#define AG_MG_REGS_LTLCCCSR_MI_BM            0x00FF0000

#define AG_MG_REGS_LTLCCCSR_TT_BO            24
#define AG_MG_REGS_LTLCCCSR_TT_BM            0x0F000000

#define AG_MG_REGS_LTLCCCSR_FT_BO            28
#define AG_MG_REGS_LTLCCCSR_FT_BM            0xF0000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_LTLCCCSR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 16,
            mi : 8,
            tt : 4,
            ft : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ltlcccsr_u;
#endif


/*
 * P0EDCSR (Port 0 Error Detect Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0EDCSR_RO                0x00000640
#define AG_MG_REGS_P0EDCSR_RM                0x007E0037

#define AG_MG_REGS_P0EDCSR_LTO_BO            0
#define AG_MG_REGS_P0EDCSR_LTO_BM            0x00000001

#define AG_MG_REGS_P0EDCSR_UCS_BO            1
#define AG_MG_REGS_P0EDCSR_UCS_BM            0x00000002

#define AG_MG_REGS_P0EDCSR_DE_BO             2
#define AG_MG_REGS_P0EDCSR_DE_BM             0x00000004

#define AG_MG_REGS_P0EDCSR_PE_BO             4
#define AG_MG_REGS_P0EDCSR_PE_BM             0x00000010

#define AG_MG_REGS_P0EDCSR_NOA_BO            5
#define AG_MG_REGS_P0EDCSR_NOA_BM            0x00000020

#define AG_MG_REGS_P0EDCSR_EM_BO             17
#define AG_MG_REGS_P0EDCSR_EM_BM             0x00020000

#define AG_MG_REGS_P0EDCSR_CRC_BO            18
#define AG_MG_REGS_P0EDCSR_CRC_BM            0x00040000

#define AG_MG_REGS_P0EDCSR_UA_BO             19
#define AG_MG_REGS_P0EDCSR_UA_BM             0x00080000

#define AG_MG_REGS_P0EDCSR_PNA_BO            20
#define AG_MG_REGS_P0EDCSR_PNA_BM            0x00100000

#define AG_MG_REGS_P0EDCSR_AUA_BO            21
#define AG_MG_REGS_P0EDCSR_AUA_BM            0x00200000

#define AG_MG_REGS_P0EDCSR_CCS_BO            22
#define AG_MG_REGS_P0EDCSR_CCS_BM            0x00400000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0EDCSR_U
{
    struct
    {
        ag_mg_regs_register
            lto : 1,
            ucs : 1,
            de : 1,
            fill2 : 1,
            pe : 1,
            noa : 1,
            fill1 : 11,
            em : 1,
            crc : 1,
            ua : 1,
            pna : 1,
            aua : 1,
            ccs : 1,
            fill0 : 9;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0edcsr_u;
#endif


/*
 * P0ERECSR (Port 0 Error Rate Enable Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0ERECSR_RO               0x00000644
#define AG_MG_REGS_P0ERECSR_RM               0x007E0037

#define AG_MG_REGS_P0ERECSR_LTO_BO           0
#define AG_MG_REGS_P0ERECSR_LTO_BM           0x00000001

#define AG_MG_REGS_P0ERECSR_UCS_BO           1
#define AG_MG_REGS_P0ERECSR_UCS_BM           0x00000002

#define AG_MG_REGS_P0ERECSR_DE_BO            2
#define AG_MG_REGS_P0ERECSR_DE_BM            0x00000004

#define AG_MG_REGS_P0ERECSR_PE_BO            4
#define AG_MG_REGS_P0ERECSR_PE_BM            0x00000010

#define AG_MG_REGS_P0ERECSR_NOA_BO           5
#define AG_MG_REGS_P0ERECSR_NOA_BM           0x00000020

#define AG_MG_REGS_P0ERECSR_EM_BO            17
#define AG_MG_REGS_P0ERECSR_EM_BM            0x00020000

#define AG_MG_REGS_P0ERECSR_CRC_BO           18
#define AG_MG_REGS_P0ERECSR_CRC_BM           0x00040000

#define AG_MG_REGS_P0ERECSR_UA_BO            19
#define AG_MG_REGS_P0ERECSR_UA_BM            0x00080000

#define AG_MG_REGS_P0ERECSR_PNA_BO           20
#define AG_MG_REGS_P0ERECSR_PNA_BM           0x00100000

#define AG_MG_REGS_P0ERECSR_AUA_BO           21
#define AG_MG_REGS_P0ERECSR_AUA_BM           0x00200000

#define AG_MG_REGS_P0ERECSR_CCS_BO           22
#define AG_MG_REGS_P0ERECSR_CCS_BM           0x00400000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0ERECSR_U
{
    struct
    {
        ag_mg_regs_register
            lto : 1,
            ucs : 1,
            de : 1,
            fill2 : 1,
            pe : 1,
            noa : 1,
            fill1 : 11,
            em : 1,
            crc : 1,
            ua : 1,
            pna : 1,
            aua : 1,
            ccs : 1,
            fill0 : 9;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0erecsr_u;
#endif


/*
 * P0ECACCSR (Port 0 Error Capture Attributes Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0ECACCSR_RO              0x00000648
#define AG_MG_REGS_P0ECACCSR_RM              0xDFFFFF01

#define AG_MG_REGS_P0ECACCSR_CVI_BO          0
#define AG_MG_REGS_P0ECACCSR_CVI_BM          0x00000001

#define AG_MG_REGS_P0ECACCSR_ECI_BO          8
#define AG_MG_REGS_P0ECACCSR_ECI_BM          0x00FFFF00

#define AG_MG_REGS_P0ECACCSR_ET_BO           24
#define AG_MG_REGS_P0ECACCSR_ET_BM           0x1F000000

#define AG_MG_REGS_P0ECACCSR_IT_BO           30
#define AG_MG_REGS_P0ECACCSR_IT_BM           0xC0000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0ECACCSR_U
{
    struct
    {
        ag_mg_regs_register
            cvi : 1,
            fill1 : 7,
            eci : 16,
            et : 5,
            fill0 : 1,
            it : 2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0ecaccsr_u;
#endif


/*
 * P0PCSECCSR0 (Port 0 Packet/Control Symbol Error Capture Command and Status)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0PCSECCSR0_RO            0x0000064C
#define AG_MG_REGS_P0PCSECCSR0_RM            0xFFFFFFFF

#define AG_MG_REGS_P0PCSECCSR0_C0_BO         0
#define AG_MG_REGS_P0PCSECCSR0_C0_BM         0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0PCSECCSR0_U
{
    struct
    {
        ag_mg_regs_register
            c0;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0pcseccsr0_u;
#endif


/*
 * P0PCSECCSR1 (Port 0 Packet/Control Symbol Error Capture Command and Status)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0PCSECCSR1_RO            0x00000650
#define AG_MG_REGS_P0PCSECCSR1_RM            0xFFFFFFFF

#define AG_MG_REGS_P0PCSECCSR1_C1_BO         0
#define AG_MG_REGS_P0PCSECCSR1_C1_BM         0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0PCSECCSR1_U
{
    struct
    {
        ag_mg_regs_register
            c1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0pcseccsr1_u;
#endif


/*
 * P0PCSECCSR2 (Port 0 Packet/Control Symbol Error Capture Command and Status)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0PCSECCSR2_RO            0x00000654
#define AG_MG_REGS_P0PCSECCSR2_RM            0xFFFFFFFF

#define AG_MG_REGS_P0PCSECCSR2_C2_BO         0
#define AG_MG_REGS_P0PCSECCSR2_C2_BM         0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0PCSECCSR2_U
{
    struct
    {
        ag_mg_regs_register
            c2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0pcseccsr2_u;
#endif


/*
 * P0PCSECCSR3 (Port 0 Packet/Control Symbol Error Capture Command and Status)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0PCSECCSR3_RO            0x00000658
#define AG_MG_REGS_P0PCSECCSR3_RM            0xFFFFFFFF

#define AG_MG_REGS_P0PCSECCSR3_C3_BO         0
#define AG_MG_REGS_P0PCSECCSR3_C3_BM         0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0PCSECCSR3_U
{
    struct
    {
        ag_mg_regs_register
            c3;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0pcseccsr3_u;
#endif


/*
 * P0ERCSR (Port 0 Error Rate  Command and Status Register)
 * Initialization value: 0x80000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0ERCSR_RO                0x00000668
#define AG_MG_REGS_P0ERCSR_RM                0xFF03FFFF

#define AG_MG_REGS_P0ERCSR_ERC_BO            0
#define AG_MG_REGS_P0ERCSR_ERC_BM            0x000000FF

#define AG_MG_REGS_P0ERCSR_PER_BO            8
#define AG_MG_REGS_P0ERCSR_PER_BM            0x0000FF00

#define AG_MG_REGS_P0ERCSR_ERR_BO            16
#define AG_MG_REGS_P0ERCSR_ERR_BM            0x00030000

#define AG_MG_REGS_P0ERCSR_ERB_BO            24
#define AG_MG_REGS_P0ERCSR_ERB_BM            0xFF000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0ERCSR_U
{
    struct
    {
        ag_mg_regs_register
            erc : 8,
            per : 8,
            err : 2,
            fill0 : 6,
            erb : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0ercsr_u;
#endif


/*
 * P0ERTCSR (Port 0 Error Rate Threshold Command and Status Register)
 * Initialization value: 0xFFFF0000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0ERTCSR_RO               0x0000066C
#define AG_MG_REGS_P0ERTCSR_RM               0xFFFF0000

#define AG_MG_REGS_P0ERTCSR_ERDTT_BO         16
#define AG_MG_REGS_P0ERTCSR_ERDTT_BM         0x00FF0000

#define AG_MG_REGS_P0ERTCSR_ERFTT_BO         24
#define AG_MG_REGS_P0ERTCSR_ERFTT_BM         0xFF000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0ERTCSR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 16,
            erdtt : 8,
            erftt : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0ertcsr_u;
#endif


/*
 * PNR (Port Number Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_PNR_RO                    0x00010000
#define AG_MG_REGS_PNR_RM                    0xF0000000

#define AG_MG_REGS_PNR_PN_BO                 28
#define AG_MG_REGS_PNR_PN_BM                 0xF0000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PNR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 28,
            pn : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pnr_u;
#endif


/*
 * LLCR (Logical Layer Configuration Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_LLCR_RO                   0x00010004
#define AG_MG_REGS_LLCR_RM                   0x20000000

#define AG_MG_REGS_LLCR_ECRAB_BO             29
#define AG_MG_REGS_LLCR_ECRAB_BM             0x20000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_LLCR_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 29,
            ecrab : 1,
            fill0 : 2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_llcr_u;
#endif


/*
 * EPWISR (Error/Port-Write Interrupt Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_EPWISR_RO                 0x00010010
#define AG_MG_REGS_EPWISR_RM                 0x80000001

#define AG_MG_REGS_EPWISR_PW_BO              0
#define AG_MG_REGS_EPWISR_PW_BM              0x00000001

#define AG_MG_REGS_EPWISR_P0_BO              31
#define AG_MG_REGS_EPWISR_P0_BM              0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_EPWISR_U
{
    struct
    {
        ag_mg_regs_register
            pw : 1,
            fill0 : 30,
            p0 : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_epwisr_u;
#endif


/*
 * PRETCR (Physical Retry Error Threshold Configuration Register)
 * Initialization value: 0x000000FF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PRETCR_RO                 0x00010080
#define AG_MG_REGS_PRETCR_RM                 0x000000FF

#define AG_MG_REGS_PRETCR_RET_BO             0
#define AG_MG_REGS_PRETCR_RET_BM             0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PRETCR_U
{
    struct
    {
        ag_mg_regs_register
            ret : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pretcr_u;
#endif


/*
 * P0ADIDCSR (Port N Alternate Device ID Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0ADIDCSR_RO              0x00010100
#define AG_MG_REGS_P0ADIDCSR_RM              0x80FFFFFF

#define AG_MG_REGS_P0ADIDCSR_LADID_BO        0
#define AG_MG_REGS_P0ADIDCSR_LADID_BM        0x0000FFFF

#define AG_MG_REGS_P0ADIDCSR_ADID_BO         16
#define AG_MG_REGS_P0ADIDCSR_ADID_BM         0x00FF0000

#define AG_MG_REGS_P0ADIDCSR_ADE_BO          31
#define AG_MG_REGS_P0ADIDCSR_ADE_BM          0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0ADIDCSR_U
{
    struct
    {
        ag_mg_regs_register
            ladid : 16,
            adid : 8,
            fill0 : 7,
            ade : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0adidcsr_u;
#endif


/*
 * P0PTAACR (Port 0 Pass-Through/Accept-All Configuration Register)
 * Initialization value: 0x00000002  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0PTAACR_RO               0x00010120
#define AG_MG_REGS_P0PTAACR_RM               0xF0000003

#define AG_MG_REGS_P0PTAACR_AA_BO            0
#define AG_MG_REGS_P0PTAACR_AA_BM            0x00000001

#define AG_MG_REGS_P0PTAACR_PTE_BO           1
#define AG_MG_REGS_P0PTAACR_PTE_BM           0x00000002

#define AG_MG_REGS_P0PTAACR_PTPN_BO          28
#define AG_MG_REGS_P0PTAACR_PTPN_BM          0xF0000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0PTAACR_U
{
    struct
    {
        ag_mg_regs_register
            aa : 1,
            pte : 1,
            fill0 : 26,
            ptpn : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0ptaacr_u;
#endif


/*
 * P0IECSR (Port 0 Implementation Error Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0IECSR_RO                0x00010130
#define AG_MG_REGS_P0IECSR_RM                0x80000000

#define AG_MG_REGS_P0IECSR_RETE_BO           31
#define AG_MG_REGS_P0IECSR_RETE_BM           0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0IECSR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 31,
            rete : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0iecsr_u;
#endif


/*
 * P0PCR (Port 0 Physical Configuration Register)
 * Initialization value: 0x00008010  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0PCR_RO                  0x00010140
#define AG_MG_REGS_P0PCR_RM                  0x0000A256

#define AG_MG_REGS_P0PCR_HSEN_BO             1
#define AG_MG_REGS_P0PCR_HSEN_BM             0x00000002

#define AG_MG_REGS_P0PCR_OBDEN_BO            2
#define AG_MG_REGS_P0PCR_OBDEN_BM            0x00000004

#define AG_MG_REGS_P0PCR_CCP_BO              4
#define AG_MG_REGS_P0PCR_CCP_BM              0x00000010

#define AG_MG_REGS_P0PCR_LBEN_BO             6
#define AG_MG_REGS_P0PCR_LBEN_BM             0x00000040

#define AG_MG_REGS_P0PCR_EQEN_BO             9
#define AG_MG_REGS_P0PCR_EQEN_BM             0x00000200

#define AG_MG_REGS_P0PCR_RSI_BO              13
#define AG_MG_REGS_P0PCR_RSI_BM              0x00002000

#define AG_MG_REGS_P0PCR_CCC_BO              15
#define AG_MG_REGS_P0PCR_CCC_BM              0x00008000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0PCR_U
{
    struct
    {
        ag_mg_regs_register
            fill6 : 1,
            hsen : 1,
            obden : 1,
            fill5 : 1,
            ccp : 1,
            fill4 : 1,
            lben : 1,
            fill3 : 2,
            eqen : 1,
            fill2 : 3,
            rsi : 1,
            fill1 : 1,
            ccc : 1,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0pcr_u;
#endif


/*
 * P0SLCSR (Port 0 Serial Link Command and Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_P0SLCSR_RO                0x00010158
#define AG_MG_REGS_P0SLCSR_RM                0xF0800000

#define AG_MG_REGS_P0SLCSR_LA_BO             23
#define AG_MG_REGS_P0SLCSR_LA_BM             0x00800000

#define AG_MG_REGS_P0SLCSR_LS3_BO            28
#define AG_MG_REGS_P0SLCSR_LS3_BM            0x10000000

#define AG_MG_REGS_P0SLCSR_LS2_BO            29
#define AG_MG_REGS_P0SLCSR_LS2_BM            0x20000000

#define AG_MG_REGS_P0SLCSR_LS1_BO            30
#define AG_MG_REGS_P0SLCSR_LS1_BM            0x40000000

#define AG_MG_REGS_P0SLCSR_LS0_BO            31
#define AG_MG_REGS_P0SLCSR_LS0_BM            0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0SLCSR_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 23,
            la : 1,
            fill0 : 4,
            ls3 : 1,
            ls2 : 1,
            ls1 : 1,
            ls0 : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0slcsr_u;
#endif


/*
 * P0SLEICR (Port 0 Serial Link Error Injection Configuration Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0SLEICR_RO               0x00010160
#define AG_MG_REGS_P0SLEICR_RM               0xF80FFFFF

#define AG_MG_REGS_P0SLEICR_EIR_BO           0
#define AG_MG_REGS_P0SLEICR_EIR_BM           0x000FFFFF

#define AG_MG_REGS_P0SLEICR_EIC_BO           27
#define AG_MG_REGS_P0SLEICR_EIC_BM           0xF8000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0SLEICR_U
{
    struct
    {
        ag_mg_regs_register
            eir : 20,
            fill0 : 7,
            eic : 5;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0sleicr_u;
#endif


/*
 * P0LLDMR (Port 0 Logical Layer Debug Mode Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0LLDMR_RO                0x00010900
#define AG_MG_REGS_P0LLDMR_RM                0x80000000

#define AG_MG_REGS_P0LLDMR_OID_BO           31
#define AG_MG_REGS_P0LLDMR_OID_BM           0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0LLDMR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 31,
            oid : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0lldmr_u;
#endif


/*
 * P0PLDMR (Port 0 Physical Layer Debug Mode Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0PLDMR_RO                0x00010904
#define AG_MG_REGS_P0PLDMR_RM                0x81F80000

#define AG_MG_REGS_P0PLDMR_TEST_LANE_BO      19
#define AG_MG_REGS_P0PLDMR_TEST_LANE_BM      0x00180000

#define AG_MG_REGS_P0PLDMR_RAW_DATA_BO       21
#define AG_MG_REGS_P0PLDMR_RAW_DATA_BM       0x00200000

#define AG_MG_REGS_P0PLDMR_RPTR_TX_ALL_BO    22
#define AG_MG_REGS_P0PLDMR_RPTR_TX_ALL_BM    0x00400000

#define AG_MG_REGS_P0PLDMR_RPTR_MODE_BO      23
#define AG_MG_REGS_P0PLDMR_RPTR_MODE_BM      0x00800000

#define AG_MG_REGS_P0PLDMR_SAMP_TEST_BO      24
#define AG_MG_REGS_P0PLDMR_SAMP_TEST_BM      0x01000000

#define AG_MG_REGS_P0PLDMR_AHQM_BO           31
#define AG_MG_REGS_P0PLDMR_AHQM_BM           0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0PLDMR_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 19,
            test_lane : 2,
            raw_data : 1,
            rptr_tx_all : 1,
            rptr_mode : 1,
            samp_test : 1,
            fill0 : 6,
            ahqm : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0pldmr_u;
#endif


/*
 * P0PLCTMR (Port 0 Physical Layer Counter Test Mode Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0PLCTMR_RO               0x00010908
#define AG_MG_REGS_P0PLCTMR_RM               0xFFFFFFF0

#define AG_MG_REGS_P0PLCTMR_IBC_BO           4
#define AG_MG_REGS_P0PLCTMR_IBC_BM           0x00000030

#define AG_MG_REGS_P0PLCTMR_CNTSEL_BO        6
#define AG_MG_REGS_P0PLCTMR_CNTSEL_BM        0x000000C0

#define AG_MG_REGS_P0PLCTMR_CNT_BO           8
#define AG_MG_REGS_P0PLCTMR_CNT_BM           0xFFFFFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0PLCTMR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 4,
            ibc : 2,
            cntsel : 2,
            cnt : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0plctmr_u;
#endif


/*
 * P0LLCTMR (Port 0 Logical Layer Counter Test Mode Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_P0LLCTMR_RO               0x0001090C
#define AG_MG_REGS_P0LLCTMR_RM               0xFFFFFFC0

#define AG_MG_REGS_P0LLCTMR_CNTSEL_BO        6
#define AG_MG_REGS_P0LLCTMR_CNTSEL_BM        0x000000C0

#define AG_MG_REGS_P0LLCTMR_CNT_BO           8
#define AG_MG_REGS_P0LLCTMR_CNT_BM           0xFFFFFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_P0LLCTMR_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 6,
            cntsel : 2,
            cnt : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_p0llctmr_u;
#endif


/*
 * IPBRR1 (IP Block Revision Register 1)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_IPBRR1_RO                  0x00010BF8
#define AG_MG_REGS_IPBRR1_RM                  0xFFFFFFFF

#define AG_MG_REGS_IPBRR1_IPMN_BO              0
#define AG_MG_REGS_IPBRR1_IPMN_BM              0x000000FF

#define AG_MG_REGS_IPBRR1_IPMJ_BO           	8
#define AG_MG_REGS_IPBRR1_IPMJ_BM           	0x0000FF00

#define AG_MG_REGS_IPBRR1_IPID_BO              16
#define AG_MG_REGS_IPBRR1_IPID_BM              0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_IPBRR1_U
{
    struct
    {
        ag_mg_regs_register
            ipmn : 8,
            ipmj : 8,
            ipid : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ipbrr1_u;
#endif


/*
 * IPBRR2 (IP Block Revision Register 2)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_IPBRR2_RO                  0x00010BFC
#define AG_MG_REGS_IPBRR2_RM                  0x00FF00FF

#define AG_MG_REGS_IPBRR2_IPCFG_BO              0
#define AG_MG_REGS_IPBRR2_IPCFG_BM              0x000000FF

#define AG_MG_REGS_IPBRR2_IPINT_BO           	16
#define AG_MG_REGS_IPBRR2_IPINT_BM           	0x00FF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_IPBRR2_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 8,
			ipcfg : 8,
            fill0 : 8,
            ipint : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ipbrr2_u;
#endif


/*
 * Virtual register addresses (for arm accessing srio_grio)
 */
#define AG_MG_REGS_SRIO_GRIO_BASE		0x98040000
#define AG_MG_REGS_SRIO_GRIO_REG(p,ro)		(AG_MG_REGS_SRIO_GRIO_BASE + ((p)*0x1000) + ro)

#define AG_MG_REGS_SRIO_GRIO_DIDCAR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_DIDCAR_RO)
#define AG_MG_REGS_SRIO_GRIO_DICAR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_DICAR_RO)
#define AG_MG_REGS_SRIO_GRIO_AIDCAR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_AIDCAR_RO)
#define AG_MG_REGS_SRIO_GRIO_AICAR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_AICAR_RO)
#define AG_MG_REGS_SRIO_GRIO_PEFCAR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_PEFCAR_RO)
#define AG_MG_REGS_SRIO_GRIO_SOCAR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_SOCAR_RO)
#define AG_MG_REGS_SRIO_GRIO_DOCAR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_DOCAR_RO)
#define AG_MG_REGS_SRIO_GRIO_PELLCCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_PELLCCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_LCSBA1CSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_LCSBA1CSR_RO)
#define AG_MG_REGS_SRIO_GRIO_BDIDCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_BDIDCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_HBDIDLCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_HBDIDLCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_CTCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_CTCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_PMBH0_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_PMBH0_RO)
#define AG_MG_REGS_SRIO_GRIO_PLTOCCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_PLTOCCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_PRTOCCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_PRTOCCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_PGCSSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_PGCSSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0LMREQCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0LMREQCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0LMRESPCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0LMRESPCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0LASCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0LASCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0ESCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0ESCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0CCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0CCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_ERBH_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_ERBH_RO)
#define AG_MG_REGS_SRIO_GRIO_LTLEDCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_LTLEDCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_LTLEECSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_LTLEECSR_RO)
#define AG_MG_REGS_SRIO_GRIO_LTLACCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_LTLACCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_LTLDIDCCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_LTLDIDCCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_LTLCCCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_LTLCCCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0EDCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0EDCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0ERECSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0ERECSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0ECACCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0ECACCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0PCSECCSR0_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0PCSECCSR0_RO)
#define AG_MG_REGS_SRIO_GRIO_P0PCSECCSR1_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0PCSECCSR1_RO)
#define AG_MG_REGS_SRIO_GRIO_P0PCSECCSR2_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0PCSECCSR2_RO)
#define AG_MG_REGS_SRIO_GRIO_P0PCSECCSR3_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0PCSECCSR3_RO)
#define AG_MG_REGS_SRIO_GRIO_P0ERCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0ERCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0ERTCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0ERTCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_PNR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_PNR_RO)
#define AG_MG_REGS_SRIO_GRIO_LLCR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_LLCR_RO)
#define AG_MG_REGS_SRIO_GRIO_EPWISR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_EPWISR_RO)
#define AG_MG_REGS_SRIO_GRIO_PRETCR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_PRETCR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0ADIDCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0ADIDCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0PTAACR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0PTAACR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0IECSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0IECSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0PCR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0PCR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0SLCSR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0SLCSR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0SLEICR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0SLEICR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0LLDMR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0LLDMR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0PLDMR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0PLDMR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0PLCTMR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0PLCTMR_RO)
#define AG_MG_REGS_SRIO_GRIO_P0LLCTMR_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_P0LLCTMR_RO)
#define AG_MG_REGS_SRIO_GRIO_IPBRR1_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_IPBRR1_RO)
#define AG_MG_REGS_SRIO_GRIO_IPBRR2_RA(p)	AG_MG_REGS_SRIO_GRIO_REG(p,AG_MG_REGS_IPBRR2_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES

typedef struct AG_MG_REGS_SRIO_GRIO_REGS_S
{
	//beginning of page 0 (GRIO_regs)
	ag_mg_regs_didcar_u		didcar ;
	ag_mg_regs_dicar_u		dicar ;
	ag_mg_regs_aidcar_u		aidcar ;
	ag_mg_regs_aicar_u		aicar ;
	ag_mg_regs_pefcar_u		pefcar ;
	ag_mg_regs_register		RESERVED_0 ;
	ag_mg_regs_socar_u		socar ;
	ag_mg_regs_docar_u		docar ;
	ag_mg_regs_register		RESERVED_1[11] ;
	ag_mg_regs_pellccsr_u	pellccsr ;
	ag_mg_regs_register		RESERVED_2[3] ;
	ag_mg_regs_lcsba1csr_u	lcsba1csr ;
	ag_mg_regs_bdidcsr_u	bdidcsr ;
	ag_mg_regs_register		RESERVED_3 ;
	ag_mg_regs_hbdidlcsr_u	hbdidlcsr ;
	ag_mg_regs_ctcsr_u		ctcsr ;
	ag_mg_regs_register		RESERVED_4[36] ;
	ag_mg_regs_pmbh0_u		pmbh0 ;
	ag_mg_regs_register		RESERVED_5[7] ;
	ag_mg_regs_pltoccsr_u	pltoccsr ;
	ag_mg_regs_prtoccsr_u	prtoccsr ;
	ag_mg_regs_register		RESERVED_6[5] ;
	ag_mg_regs_pgcssr_u		pgcssr ;
	ag_mg_regs_p0lmreqcsr_u		p0lmreqcsr ;
	ag_mg_regs_p0lmrespcsr_u	p0lmrespcsr ;
	ag_mg_regs_p0lascsr_u		p0lascsr ;
	ag_mg_regs_register		RESERVED_7[3] ;
	ag_mg_regs_p0escsr_u		p0escsr ;
	ag_mg_regs_p0ccsr_u		p0ccsr ;
	ag_mg_regs_register		RESERVED_8[296] ;
	ag_mg_regs_erbh_u		erbh ;
	ag_mg_regs_register		RESERVED_9 ;
	ag_mg_regs_ltledcsr_u	ltledcsr ;
	ag_mg_regs_ltleecsr_u	ltleecsr ;
	ag_mg_regs_register		RESERVED_10 ;
	ag_mg_regs_ltlaccsr_u	ltlaccsr ;
	ag_mg_regs_ltldidccsr_u	ltldidccsr ;
	ag_mg_regs_ltlcccsr_u	ltlcccsr ;
	ag_mg_regs_register		RESERVED_11[8] ;
	ag_mg_regs_p0edcsr_u		p0edcsr ;
	ag_mg_regs_p0erecsr_u		p0erecsr ;
	ag_mg_regs_p0ecaccsr_u		p0ecaccsr ;
	ag_mg_regs_p0pcseccsr0_u	p0pcseccsr0 ;
	ag_mg_regs_p0pcseccsr1_u	p0pcseccsr1 ;
	ag_mg_regs_p0pcseccsr2_u	p0pcseccsr2 ;
	ag_mg_regs_p0pcseccsr3_u	p0pcseccsr3 ;
	ag_mg_regs_register		RESERVED_12[3] ;
	ag_mg_regs_p0ercsr_u		p0ercsr ;
	ag_mg_regs_p0ertcsr_u		p0ertcsr ;
	ag_mg_regs_register		RESERVED_13[15972] ;
	//end of page 0
	//beginning of page 0x20
	ag_mg_regs_pnr_u		pnr ;
	ag_mg_regs_llcr_u		llcr ;
	ag_mg_regs_register		RESERVED_14[2] ;
	ag_mg_regs_epwisr_u		epwisr ;
	ag_mg_regs_register		RESERVED_15[27] ;
	ag_mg_regs_pretcr_u		pretcr ;
	ag_mg_regs_register		RESERVED_16[31] ;
	ag_mg_regs_p0adidcsr_u		p0adidcsr ;
	ag_mg_regs_register		RESERVED_17[7] ;
	ag_mg_regs_p0ptaacr_u		p0ptaacr ;
	ag_mg_regs_register		RESERVED_18[3] ;
	ag_mg_regs_p0iecsr_u		p0iecsr ;
	ag_mg_regs_register		RESERVED_19[3] ;
	ag_mg_regs_p0pcr_u		p0pcr ;
	ag_mg_regs_register		RESERVED_20[5] ;
	ag_mg_regs_p0slcsr_u		p0slcsr ;
	ag_mg_regs_register		RESERVED_21 ;
	ag_mg_regs_p0sleicr_u		p0sleicr ;
	//end of page 0x20
	ag_mg_regs_register		RESERVED_22[487];
	//beginning of page 0x21
	ag_mg_regs_p0lldmr_u	p0lldmr	;
	ag_mg_regs_p0pldmr_u	p0pldmr ;
	ag_mg_regs_p0plctmr_u	p0plctmr ;
	ag_mg_regs_p0llctmr_u	p0llctmr ;
	ag_mg_regs_register		RESERVED_24[186] ;
	ag_mg_regs_ipbrr1_u		ipbrr1 ;
	ag_mg_regs_ipbrr2_u		ipbrr2 ;
	//end of page 0x21
} ag_mg_regs_srio_grio_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_srio_grio_reg_s *srio_regs =
*       (volatile ag_mg_regs_srio_grio_reg_s *)AG_MG_REGS_SRIO_BASE;
*/
#endif

#endif
/******** History ********
$Log: ag_mg_regs_srio_grio.h,v $
Revision 1.2  2017/07/28 07:58:34  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:28  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

