/* $Id: ag_mg_regs_srio_rab.h,v 1.2 2017/07/28 07:58:35 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_srio_rab.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_srio_rab.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_srio_rab.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of LSI Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * The SRIO solution consists of three blocks
 *  - generic SRIO core, called GRIO (Generic RapidIO), ag_mg_regs_srio_grio.h
 *  - AXI bridge component, called RAB (RIO-AXI Bridge), this file
 *  - and a Serializer / Deseserializer (SerDes), ag_mg_regs_serdes.h
 *
 * The AXI-RIO Bridge connects the Generic RapidIO (GRIO) to an AMBA Advanced
 * eXtensible Interface (AXI) subsystem on the other side. It supports the
 * following types of transfers:
 *
 *  - AXI PIO (Slave): Request is transferred from AXI to RapidIO. The bridge
 *    acts as AXI Write/Read Slave and RapidIO Initiator
 * 
 *  - AXI (Master): Request is transferred from RapidIO to AXI. The bridge
 *    acts as RapidIO Target and AXI Write/Read Master. Additionally it
 *    handles optional Inbound and Outbound Messaging.
 * 
 * In addition, RapidIO Configuration Space and device specific
 * Control/Status/Debug register can be accessed by either RapidIO Host
 * through RapidIO link, or AXI Master through AXI Write/Read Slave Interface
 * (or APB interface).
 *
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *
 *  RAB_VER
 *  RAB_CAPA
 *  RAB_CTRL
 *  RAB_STAT
 *  RAB_AXI_TIMEOUT
 *  RAB_DME_TIMEOUT
 *  RAB_RST_CTRL
 *  RAB_COOP_LOCK
 *  RAB_STAT_ESEL
 *  RAB_STAT_STAT
 *  RAB_IB_PW_CSR
 *  RAB_IB_PW_DATA
 *  RAB_APB_CSR
 *  RAB_ARB_TIMEOUT
 *  RAB_DESC_RDY_TIMEOUT
 *  RAB_INTR_ENAB_GNRL
 *  RAB_INTR_ENAB_APIO
 *  RAB_INTR_ENAB_RPIO
 *  RAB_INTR_ENAB_IDME
 *  RAB_INTR_ENAB_ODME
 *  RAB_INTR_ENAB_MISC
 *  RAB_INTR_STAT_GNRL
 *  RAB_INTR_STAT_APIO
 *  RAB_INTR_STAT_RPIO
 *  RAB_INTR_STAT_IDME
 *  RAB_INTR_STAT_ODME
 *  RAB_INTR_STAT_MISC
 *  RAB_RIO_PIO_CTRL
 *  RAB_RIO_PIO_STAT
 *  RAB_RIO_AMAP_LUT
 *  RAB_RIO_AMAP_IDSL
 *  RAB_RIO_AMAP_BYPS
 *  RAB_AXI_PIO_CTRL
 *  RAB_AXI_PIO_STAT
 *  RAB_ASLV_STAT_CMD
 *  RAB_ASLV_STAT_ADDR
 *  RAB_AMST_STAT
 *  RAB_APIO_AMAP_CTRL
 *  RAB_APIO_AMAP_SIZE
 *  RAB_APIO_AMAP_ABAR
 *  RAB_APIO_AMAP_RBAR
 *  RAB_OB_DB_CSR
 *  RAB_OB_DB_INFO
 *  RAB_OB_IDB_CSR
 *  RAB_OB_IDB_INFO
 *  RAB_IB_DB_CSR
 *  RAB_IB_DB_INFO
 *  RAB_OB_DME_CTRL
 *  RAB_OB_DME_ADDR
 *  RAB_OB_DME_STAT
 *  RAB_OB_DME_DESC
 *  RAB_OB_DME_TIDMSK
 *  RAB_IB_DME_CTRL
 *  RAB_IB_DME_ADDR
 *  RAB_IB_DME_STAT
 *  RAB_IB_DME_DESC
 *  RAB_LFC_CSR
 *  RAB_LFC_TIMEOUT
 *  RAB_LFC_BLOCKED
 *  RAB_SRDS_CTRL0
*
* Prefix naming conventions :
*   AG_MG_REGS_XXX_RA : register/memory physical address
*   AG_MG_REGS_XXX_RO : register/memory address offset
*   AG_MG_REGS_XXX_RM : register mask
*   AG_MG_REGS_XXX_BO : bit/field offset from LSB
*   AG_MG_REGS_XXX_BM : bit/field mask
*   AG_MG_REGS_XXX_U  : bitfields in C union typedef
*   AG_MG_REGS_XXX_S  : registers in C struct typedef
*   AG_MG_REGS_XX_RPT : number of identical registers in array
*   AG_MG_REGS_XX_IVL : interval between registers in array
*
* NOTE: user may redefine ag_mg_regs_register
*       in ag_mg_regs_regops.h if necessary
* NOTE: access mode of individual bit fields matches that
*       of containing register unless indicated otherwise
*/

#ifndef AG_MG_REGS_SRIO_RAB_REGISTERS_H
#define AG_MG_REGS_SRIO_RAB_REGISTERS_H

#include "ag_mg_regs_regops.h"


/*
 * Generated by HSI Designer release 2.3.5.
 */

/*
 * Initialization value: 0x00131010  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_RAB_VER_RO                                                0x00020000
#define AG_MG_REGS_RAB_VER_RM                                                0x00FFFFFF

#define AG_MG_REGS_RAB_VER_BRIDGE_REVISION_BO                                0
#define AG_MG_REGS_RAB_VER_BRIDGE_REVISION_BM                                0x000000FF

#define AG_MG_REGS_RAB_VER_AXI_VERSION_BO                                    8
#define AG_MG_REGS_RAB_VER_AXI_VERSION_BM                                    0x0000FF00

#define AG_MG_REGS_RAB_VER_RAPIDIO_VERSION_BO                                16
#define AG_MG_REGS_RAB_VER_RAPIDIO_VERSION_BM                                0x00FF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_VER_U
{
    struct
    {
        ag_mg_regs_register
            bridge_revision : 8,
            axi_version : 8,
            rapidio_version : 8,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ver_u;
#endif


/*
 * Initialization value: 0x000C0011  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_RAB_CAPA_RO                                               0x00020004
#define AG_MG_REGS_RAB_CAPA_RM                                               0x000CFFFF

#define AG_MG_REGS_RAB_CAPA_NUMBER_OF_AMBA_PIO_BO                            0
#define AG_MG_REGS_RAB_CAPA_NUMBER_OF_AMBA_PIO_BM                            0x0000000F

#define AG_MG_REGS_RAB_CAPA_NUMBER_OF_RIO_PIO_BO                             4
#define AG_MG_REGS_RAB_CAPA_NUMBER_OF_RIO_PIO_BM                             0x000000F0

#define AG_MG_REGS_RAB_CAPA_NUMBER_OF_WRITE_DMA_BO                           8
#define AG_MG_REGS_RAB_CAPA_NUMBER_OF_WRITE_DMA_BM                           0x00000F00

#define AG_MG_REGS_RAB_CAPA_NUMBER_OF_READ_DMA_BO                            12
#define AG_MG_REGS_RAB_CAPA_NUMBER_OF_READ_DMA_BM                            0x0000F000

#define AG_MG_REGS_RAB_CAPA_DECRIPTORDEPTH_BO                                18
#define AG_MG_REGS_RAB_CAPA_DECRIPTORDEPTH_BM                                0x000C0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_CAPA_U
{
    struct
    {
        ag_mg_regs_register
            number_of_amba_pio : 4,
            number_of_rio_pio : 4,
            number_of_write_dma : 4,
            number_of_read_dma : 4,
            fill1 : 2,
            decriptordepth : 2,
            fill0 : 12;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_capa_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_CTRL_RO                                               0x00020008
#define AG_MG_REGS_RAB_CTRL_RM                                               0x00001FDF

#define AG_MG_REGS_RAB_CTRL_AMBA_PIO_ENABLE_BO                               0
#define AG_MG_REGS_RAB_CTRL_AMBA_PIO_ENABLE_BM                               0x00000001

#define AG_MG_REGS_RAB_CTRL_RIO_PIO_ENABLE_BO                                1
#define AG_MG_REGS_RAB_CTRL_RIO_PIO_ENABLE_BM                                0x00000002

#define AG_MG_REGS_RAB_CTRL_WRITE_DMA_ENABLE_BO                              2
#define AG_MG_REGS_RAB_CTRL_WRITE_DMA_ENABLE_BM                              0x00000004

#define AG_MG_REGS_RAB_CTRL_READ_DMA_ENABLE_BO                               3
#define AG_MG_REGS_RAB_CTRL_READ_DMA_ENABLE_BM                               0x00000008

#define AG_MG_REGS_RAB_CTRL_AXI_BYTE_SWAPPING_ENABLE_BO                      4
#define AG_MG_REGS_RAB_CTRL_AXI_BYTE_SWAPPING_ENABLE_BM                      0x00000010

#define AG_MG_REGS_RAB_CTRL_OB_MESSAGE_ARBITRATION_BO                        6
#define AG_MG_REGS_RAB_CTRL_OB_MESSAGE_ARBITRATION_BM                        0x000000C0


#define AG_MG_REGS_RAB_CTRL_DEPTH_OF_DMA_DESCRIPTORS_ARRAY_BO                8
#define AG_MG_REGS_RAB_CTRL_DEPTH_OF_DMA_DESCRIPTORS_ARRAY_BM                0x00000300

#define AG_MG_REGS_RAB_CTRL_OB_RESPONSE_PRIORITY_BO                          10
#define AG_MG_REGS_RAB_CTRL_OB_RESPONSE_PRIORITY_BM                          0x00000C00

#define AG_MG_REGS_RAB_CTRL_MESSAGE_DESCRIPTOR_MEMORY_EN_BO                  12
#define AG_MG_REGS_RAB_CTRL_MESSAGE_DESCRIPTOR_MEMORY_EN_BM                  0x00001000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            amba_pio_enable : 1,
            rio_pio_enable : 1,
            write_dma_enable : 1,
            read_dma_enable : 1,
            axi_byte_swapping_enable : 1,
            fill1 : 1,
            ob_message_arbitration : 2,
            depth_of_dma_descriptors_array : 2,
            ob_response_priority : 2,
            message_descriptor_memory_en : 1,
            fill0 : 19;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ctrl_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_RAB_STAT_RO                                               0x0002000C
#define AG_MG_REGS_RAB_STAT_RM                                               0x000000FF

#define AG_MG_REGS_RAB_STAT_AXI_PIO_TRANSACTION_PENDING_BO                   0
#define AG_MG_REGS_RAB_STAT_AXI_PIO_TRANSACTION_PENDING_BM                   0x00000001

#define AG_MG_REGS_RAB_STAT_RIO_PIO_TRANSACTION_PENDING_BO                   1
#define AG_MG_REGS_RAB_STAT_RIO_PIO_TRANSACTION_PENDING_BM                   0x00000002

#define AG_MG_REGS_RAB_STAT_WRITE_DMA_TRANSACTION_PENDING_BO                 2
#define AG_MG_REGS_RAB_STAT_WRITE_DMA_TRANSACTION_PENDING_BM                 0x00000004

#define AG_MG_REGS_RAB_STAT_READ_DMA_TRANSACTION_PENDING_BO                  3
#define AG_MG_REGS_RAB_STAT_READ_DMA_TRANSACTION_PENDING_BM                  0x00000008

#define AG_MG_REGS_RAB_STAT_OUTBOUND_MAILBOX_TRANS_PENDING_BO                4
#define AG_MG_REGS_RAB_STAT_OUTBOUND_MAILBOX_TRANS_PENDING_BM                0x00000010

#define AG_MG_REGS_RAB_STAT_INBOUND_MAILBOX_TRANS_PENDING_BO                 5
#define AG_MG_REGS_RAB_STAT_INBOUND_MAILBOX_TRANS_PENDING_BM                 0x00000020

#define AG_MG_REGS_RAB_STAT_OUTBOUND_DOORBELL_TRANS_PENDING_BO               6
#define AG_MG_REGS_RAB_STAT_OUTBOUND_DOORBELL_TRANS_PENDING_BM               0x00000040

#define AG_MG_REGS_RAB_STAT_INBOUND_DOORBELL_TRANS_PENDING_BO                7
#define AG_MG_REGS_RAB_STAT_INBOUND_DOORBELL_TRANS_PENDING_BM                0x00000080

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_STAT_U
{
    struct
    {
        ag_mg_regs_register
            axi_pio_transaction_pending : 1,
            rio_pio_transaction_pending : 1,
            write_dma_transaction_pending : 1,
            read_dma_transaction_pending : 1,
            outbound_mailbox_trans_pending : 1,
            inbound_mailbox_trans_pending : 1,
            outbound_doorbell_trans_pending : 1,
            inbound_doorbell_trans_pending : 1,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_stat_u;
#endif


/*
 * Initialization value: 0x0000FFFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_AXI_TIMEOUT_RO                                        0x00020010
#define AG_MG_REGS_RAB_AXI_TIMEOUT_RM                                        0x0000FFFF

#define AG_MG_REGS_RAB_AXI_TIMEOUT_TIMEOUT_VALUE_BO                          0
#define AG_MG_REGS_RAB_AXI_TIMEOUT_TIMEOUT_VALUE_BM                          0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_AXI_TIMEOUT_U
{
    struct
    {
        ag_mg_regs_register
            timeout_value : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_axi_timeout_u;
#endif


/*
 * Initialization value: 0x0000FFFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_DME_TIMEOUT_RO                                        0x00020014
#define AG_MG_REGS_RAB_DME_TIMEOUT_RM                                        0x0000FFFF

#define AG_MG_REGS_RAB_DME_TIMEOUT_TIMEOUT_VALUE_BO                          0
#define AG_MG_REGS_RAB_DME_TIMEOUT_TIMEOUT_VALUE_BM                          0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_DME_TIMEOUT_U
{
    struct
    {
        ag_mg_regs_register
            timeout_value : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_dme_timeout_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_RST_CTRL_RO                                           0x00020018
#define AG_MG_REGS_RAB_RST_CTRL_RM                                           0x00000101

#define AG_MG_REGS_RAB_RST_CTRL_AXI_PIO_RESET_BO                             0
#define AG_MG_REGS_RAB_RST_CTRL_AXI_PIO_RESET_BM                             0x00000001

#define AG_MG_REGS_RAB_RST_CTRL_RIO_PIO_RESET_BO                             8
#define AG_MG_REGS_RAB_RST_CTRL_RIO_PIO_RESET_BM                             0x00000100

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_RST_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            axi_pio_reset : 1,
            fill1 : 7,
            rio_pio_reset : 1,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_rst_ctrl_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_COOP_LOCK_RO                                          0x0002001C
#define AG_MG_REGS_RAB_COOP_LOCK_RM                                          0xFFFFFFFF

#define AG_MG_REGS_RAB_COOP_LOCK_PROCESS_ID_BO                               0
#define AG_MG_REGS_RAB_COOP_LOCK_PROCESS_ID_BM                               0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_COOP_LOCK_U
{
    struct
    {
        ag_mg_regs_register
            process_id;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_coop_lock_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_STAT_ESEL_RO                                          0x00020020
#define AG_MG_REGS_RAB_STAT_ESEL_RM                                          0x000000FF

#define AG_MG_REGS_RAB_STAT_ESEL_ENGINE_TYPE_BO                              0
#define AG_MG_REGS_RAB_STAT_ESEL_ENGINE_TYPE_BM                              0x00000007

#define AG_MG_REGS_AG_MG_REGS_RAB_STAT_ESEL_ENGINE_BO_RPT                    3
#define AG_MG_REGS_AG_MG_REGS_RAB_STAT_ESEL_ENGINE_BM_RPT                    0x000000F8

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_STAT_ESEL_U
{
    struct
    {
        ag_mg_regs_register
            engine_type : 3,
            engine_num : 5,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_stat_esel_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_RAB_STAT_STAT_RO                                          0x00020024
#define AG_MG_REGS_RAB_STAT_STAT_RM                                          0xFFFFFFFF

#define AG_MG_REGS_RAB_STAT_STAT_NUMBER_OF_SUCCESSFUL_TRANSFERS_BO           0
#define AG_MG_REGS_RAB_STAT_STAT_NUMBER_OF_SUCCESSFUL_TRANSFERS_BM           0x00FFFFFF

#define AG_MG_REGS_RAB_STAT_STAT_NUMBER_OF_ABORTED_TRANSFERS_BO              24
#define AG_MG_REGS_RAB_STAT_STAT_NUMBER_OF_ABORTED_TRANSFERS_BM              0xFF000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_STAT_STAT_U
{
    struct
    {
        ag_mg_regs_register
            number_of_successful_transfers : 24,
            number_of_aborted_transfers : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_stat_stat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_IB_PW_CSR_RO                                          0x00020028
#define AG_MG_REGS_RAB_IB_PW_CSR_RM                                          0x001F0001

#define AG_MG_REGS_RAB_IB_PW_CSR_ENABLE_BO                                   0
#define AG_MG_REGS_RAB_IB_PW_CSR_ENABLE_BM                                   0x00000001

#define AG_MG_REGS_RAB_IB_PW_CSR_NUMBER_OF_WORDS_BO                          16
#define AG_MG_REGS_RAB_IB_PW_CSR_NUMBER_OF_WORDS_BM                          0x001F0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_IB_PW_CSR_U
{
    struct
    {
        ag_mg_regs_register
            enable : 1,
            fill1 : 15,
            number_of_words : 5,
            fill0 : 11;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ib_pw_csr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_RAB_IB_PW_DATA_RO                                         0x0002002C
#define AG_MG_REGS_RAB_IB_PW_DATA_RM                                         0xFFFFFFFF

#define AG_MG_REGS_RAB_IB_PW_DATA_DATA_BO                                    0
#define AG_MG_REGS_RAB_IB_PW_DATA_DATA_BM                                    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_IB_PW_DATA_U
{
    struct
    {
        ag_mg_regs_register
            data;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ib_pw_data_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_APB_CSR_RO                                            0x00020030
#define AG_MG_REGS_RAB_APB_CSR_RM                                            0x3FFFFFFF

#define AG_MG_REGS_RAB_APB_CSR_KEY_BO                                        0
#define AG_MG_REGS_RAB_APB_CSR_KEY_BM                                        0x0000FFFF

#define AG_MG_REGS_RAB_APB_CSR_PAGE_SELECT_BO                                16
#define AG_MG_REGS_RAB_APB_CSR_PAGE_SELECT_BM                                0x1FFF0000

#define AG_MG_REGS_RAB_APB_CSR_GRIO_LOCKED_BO                                29
#define AG_MG_REGS_RAB_APB_CSR_GRIO_LOCKED_BM                                0x20000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_APB_CSR_U
{
    struct
    {
        ag_mg_regs_register
            key : 16,
            page_select : 13,
            grio_locked : 1,
            fill0 : 2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_apb_csr_u;
#endif


/*
 * Initialization value: 0x00000FFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_ARB_TIMEOUT_RO                                        0x00020034
#define AG_MG_REGS_RAB_ARB_TIMEOUT_RM                                        0x0000FFFF

#define AG_MG_REGS_RAB_ARB_TIMEOUT_TIMEOUT_VALUE_BO                          0
#define AG_MG_REGS_RAB_ARB_TIMEOUT_TIMEOUT_VALUE_BM                          0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_ARB_TIMEOUT_U
{
    struct
    {
        ag_mg_regs_register
            timeout_value : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_arb_timeout_u;
#endif


/*
 * Initialization value: 0x0000FFFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_DESC_RDY_TIMEOUT_RO                                   0x00020038
#define AG_MG_REGS_RAB_DESC_RDY_TIMEOUT_RM                                   0x0000FFFF

#define AG_MG_REGS_RAB_DESC_RDY_TIMEOUT_TIMEOUT_VALUE_BO                     0
#define AG_MG_REGS_RAB_DESC_RDY_TIMEOUT_TIMEOUT_VALUE_BM                     0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_DESC_RDY_TIMEOUT_U
{
    struct
    {
        ag_mg_regs_register
            timeout_value : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_desc_rdy_timeout_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_RO                            0x00020040
#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_RM                            0xFFFF007F

#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_AXI_PIO_INTERRUPT_ENABLE_BO        0
#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_AXI_PIO_INTERRUPT_ENABLE_BM        0x00000001

#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_RIO_PIO_INTERRUPT_ENABLE_BO        1
#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_RIO_PIO_INTERRUPT_ENABLE_BM        0x00000002

#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_WRITE_DMA_INTERRUPT_ENABLE_BO      2
#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_WRITE_DMA_INTERRUPT_ENABLE_BM      0x00000004

#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_READ_DMA_INTERRUPT_ENABLE_BO       3
#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_READ_DMA_INTERRUPT_ENABLE_BM       0x00000008

#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_INBOUND_DME_INTERRUPT_ENABLE_BO       4
#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_INBOUND_DME_INTERRUPT_ENABLE_BM       0x00000010

#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_OUTBOUND_DME_INTERRUPT_ENABLE_BO      5
#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_OUTBOUND_DME_INTERRUPT_ENABLE_BM      0x00000020

#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_MISC_INTERRUPT_ENABLE_BO           6
#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_MISC_INTERRUPT_ENABLE_BM           0x00000040

#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_EXTERNAL_INT_OB_DB_ENABLE_BO      16
#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_EXTERNAL_INT_OB_DB_ENABLE_BM	0x7FFF0000

#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_RAB_INT_OB_DB_ENABLE_BO      	31
#define AG_MG_REGS_RAB_INTR_ENAB_GNRL_RAB_INT_OB_DB_ENABLE_BM      	0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_ENAB_GNRL_U
{
    struct
    {
        ag_mg_regs_register
            axi_pio_interrupt_enable : 1,
            rio_pio_interrupt_enable : 1,
            write_dma_interrupt_enable : 1,
            read_dma_interrupt_enable : 1,
            inbound_dme_interrupt_enable : 1,
            outbound_dme_interrupt_enable : 1,
            misc_interrupt_enable : 1,
            fill0 : 9,
            external_int_ob_db_enable : 15,
            rab_int_ob_db_enable : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_enab_gnrl_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_INTR_ENAB_APIO_RO                                     0x00020044
#define AG_MG_REGS_RAB_INTR_ENAB_APIO_RM                                     0x00000101

#define AG_MG_REGS_RAB_INTR_ENAB_APIO_AXI_PIO_TRANS_COMPLETED_BO             0
#define AG_MG_REGS_RAB_INTR_ENAB_APIO_AXI_PIO_TRANS_COMPLETED_BM             0x00000001

#define AG_MG_REGS_RAB_INTR_ENAB_APIO_AXI_PIO_TRANS_FAILED_BO                8
#define AG_MG_REGS_RAB_INTR_ENAB_APIO_AXI_PIO_TRANS_FAILED_BM                0x00000100

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_ENAB_APIO_U
{
    struct
    {
        ag_mg_regs_register
            axi_pio_trans_completed : 1,
            fill1 : 7,
            axi_pio_trans_failed : 1,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_enab_apio_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_INTR_ENAB_RPIO_RO                                     0x00020048
#define AG_MG_REGS_RAB_INTR_ENAB_RPIO_RM                                     0x00000101

#define AG_MG_REGS_RAB_INTR_ENAB_RPIO_RIO_PIO_TRANS_COMPLETED_BO             0
#define AG_MG_REGS_RAB_INTR_ENAB_RPIO_RIO_PIO_TRANS_COMPLETED_BM             0x00000001

#define AG_MG_REGS_RAB_INTR_ENAB_RPIO_RIO_PIO_TRANS_FAILED_BO                8
#define AG_MG_REGS_RAB_INTR_ENAB_RPIO_RIO_PIO_TRANS_FAILED_BM                0x00000100

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_ENAB_RPIO_U
{
    struct
    {
        ag_mg_regs_register
            rio_pio_trans_completed : 1,
            fill1 : 7,
            rio_pio_trans_failed : 1,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_enab_rpio_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_INTR_ENAB_IDME_RO                                     0x00020054
#define AG_MG_REGS_RAB_INTR_ENAB_IDME_RM                                     0xFFFFFFFF

#define AG_MG_REGS_RAB_INTR_ENAB_IDME_IB_DME_ENABLE_BO                       0
#define AG_MG_REGS_RAB_INTR_ENAB_IDME_IB_DME_ENABLE_BM                       0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_ENAB_IDME_U
{
    struct
    {
        ag_mg_regs_register
            ib_dme_enable;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_enab_idme_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_INTR_ENAB_ODME_RO                                     0x00020058
#define AG_MG_REGS_RAB_INTR_ENAB_ODME_RM                                     0x0000003F

#define AG_MG_REGS_RAB_INTR_ENAB_ODME_OB_DME_ENABLE_BO                       0
#define AG_MG_REGS_RAB_INTR_ENAB_ODME_OB_DME_ENABLE_BM                       0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_ENAB_ODME_U
{
    struct
    {
        ag_mg_regs_register
            ob_dme_enable : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_enab_odme_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_RO                                     0x0002005C
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_RM                                     0x00000FFF

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_IB_DOORBELL_RECIEVED_ENABLE_BO         0
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_IB_DOORBELL_RECIEVED_ENABLE_BM         0x00000001

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_OB_DOORBELL_RECIEVED_ENABLE_BO         1
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_OB_DOORBELL_RECIEVED_ENABLE_BM         0x00000002

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_UNEXPECTED_IB_DATA_MESSSAGE_EN_BO      2
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_UNEXPECTED_IB_DATA_MESSSAGE_EN_BM      0x00000004

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_UNSUPPORTED_RIO_REPQUEST_ENABLE_BO     3
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_UNSUPPORTED_RIO_REPQUEST_ENABLE_BM     0x00000008

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_GRIO_PORT_WRITE_RECEIVED_ENABLE_BO     4
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_GRIO_PORT_WRITE_RECEIVED_ENABLE_BM     0x00000010

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_GRIO_ERROR_INTERRUPT_ENABLE_BO         5
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_GRIO_ERROR_INTERRUPT_ENABLE_BM         0x00000020

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_GRIO_LOGICAL_OR_TRANSPORT_ERR_EN_BO    6
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_GRIO_LOGICAL_OR_TRANSPORT_ERR_EN_BM    0x00000040

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_LINK_IPG_RESET_REQUEST_ENABLE_BO       7
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_LINK_IPG_RESET_REQUEST_ENABLE_BM       0x00000080

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_CO_OP_LOCK_CLEAR_ENABLE_BO             8
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_CO_OP_LOCK_CLEAR_ENABLE_BM             0x00000100

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_LFC_BLOCKED_STATUS_CHANGE_BO           9
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_LFC_BLOCKED_STATUS_CHANGE_BM           0x00000200

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_AXI_SLAVE_INT_ENABLE_BO                10
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_AXI_SLAVE_INT_ENABLE_BM                0x00000400

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_AXI_MASTER_INT_ENABLE_BO               11
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_AXI_MASTER_INT_ENABLE_BM               0x00000800

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_ENAB_MISC_U
{
    struct
    {
        ag_mg_regs_register
            ib_doorbell_recieved_enable : 1,
            ob_doorbell_recieved_enable : 1,
            unexpected_ib_data_messsage_en : 1,
            unsupported_rio_repquest_enable : 1,
            grio_port_write_received_enable : 1,
            grio_error_interrupt_enable : 1,
            grio_logical_or_transport_err_en : 1,
            link_ipg_reset_request_enable : 1,
            co_op_lock_clear_enable : 1,
            lfc_blocked_status_change : 1,
            axi_slave_int_enable : 1,
            axi_master_int_enable : 1,
            fill0 : 20;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_enab_misc_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_RAB_INTR_STAT_GNRL_RO                                     0x00020060
#define AG_MG_REGS_RAB_INTR_STAT_GNRL_RM                                     0xFFFF007F

#define AG_MG_REGS_RAB_INTR_STAT_GNRL_AXI_PIO_INTERRUPT_ASSERTED_BO          0
#define AG_MG_REGS_RAB_INTR_STAT_GNRL_AXI_PIO_INTERRUPT_ASSERTED_BM          0x00000001

#define AG_MG_REGS_RAB_INTR_STAT_GNRL_RIO_PIO_INTERRUPT_ASSERTED_BO          1
#define AG_MG_REGS_RAB_INTR_STAT_GNRL_RIO_PIO_INTERRUPT_ASSERTED_BM          0x00000002

#define AG_MG_REGS_RAB_INTR_STAT_GNRL_WRITE_DMA_INTERRUPT_ASSERTED_BO        2
#define AG_MG_REGS_RAB_INTR_STAT_GNRL_WRITE_DMA_INTERRUPT_ASSERTED_BM        0x00000004

#define AG_MG_REGS_RAB_INTR_STAT_GNRL_READ_DMA_INTERRUPT_ASSERTED_BO         3
#define AG_MG_REGS_RAB_INTR_STAT_GNRL_READ_DMA_INTERRUPT_ASSERTED_BM         0x00000008

#define AG_MG_REGS_RAB_INTR_STAT_GNRL_INBOUND_DME_INTERRUPT_ASSERTED_BO      4
#define AG_MG_REGS_RAB_INTR_STAT_GNRL_INBOUND_DME_INTERRUPT_ASSERTED_BM      0x00000010

#define AG_MG_REGS_RAB_INTR_STAT_GNRL_OUTBOUND_DME_INTERRUPT_ENABLE_BO       5
#define AG_MG_REGS_RAB_INTR_STAT_GNRL_OUTBOUND_DME_INTERRUPT_ENABLE_BM       0x00000020

#define AG_MG_REGS_RAB_INTR_STAT_GNRL_MISC_INTERRUPT_ENABLE_BO               6
#define AG_MG_REGS_RAB_INTR_STAT_GNRL_MISC_INTERRUPT_ENABLE_BM               0x00000040

#define AG_MG_REGS_RAB_INTR_STAT_GNRL_EXTERNAL_INT_STATUS_BO                 16
#define AG_MG_REGS_RAB_INTR_STAT_GNRL_EXTERNAL_INT_STATUS_BM                 0x7FFF0000

#define AG_MG_REGS_RAB_INTR_STAT_GNRL_INTERNAL_INT_STATUS_BO                 31
#define AG_MG_REGS_RAB_INTR_STAT_GNRL_INTERNAL_INT_STATUS_BM                 0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_STAT_GNRL_U
{
    struct
    {
        ag_mg_regs_register
            axi_pio_interrupt_asserted : 1,
            rio_pio_interrupt_asserted : 1,
            write_dma_interrupt_asserted : 1,
            read_dma_interrupt_asserted : 1,
            inbound_dme_interrupt_asserted : 1,
            outbound_dme_interrupt_enable : 1,
            misc_interrupt_enable : 1,
            fill0 : 9,
            external_int_status : 15,
            internal_int_status : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_stat_gnrl_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_RAB_INTR_STAT_APIO_RO                                     0x00020064
#define AG_MG_REGS_RAB_INTR_STAT_APIO_RM                                     0x00000101

#define AG_MG_REGS_RAB_INTR_STAT_APIO_AXI_PIO_TRANSACTION_COMPLETED_BO       0
#define AG_MG_REGS_RAB_INTR_STAT_APIO_AXI_PIO_TRANSACTION_COMPLETED_BM       0x00000001

#define AG_MG_REGS_RAB_INTR_STAT_APIO_AXI_PIO_TRANSACTION_FAILED_BO          8
#define AG_MG_REGS_RAB_INTR_STAT_APIO_AXI_PIO_TRANSACTION_FAILED_BM          0x00000100

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_STAT_APIO_U
{
    struct
    {
        ag_mg_regs_register
            axi_pio_transaction_completed : 1,
            fill1 : 7,
            axi_pio_transaction_failed : 1,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_stat_apio_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_RAB_INTR_STAT_RPIO_RO                                     0x00020068
#define AG_MG_REGS_RAB_INTR_STAT_RPIO_RM                                     0x00000101

#define AG_MG_REGS_RAB_INTR_STAT_RPIO_RIO_PIO_TRANSACTION_COMPLETED_BO       0
#define AG_MG_REGS_RAB_INTR_STAT_RPIO_RIO_PIO_TRANSACTION_COMPLETED_BM       0x00000001

#define AG_MG_REGS_RAB_INTR_STAT_RPIO_RIO_PIO_TRANSACTION_FAILED_BO          8
#define AG_MG_REGS_RAB_INTR_STAT_RPIO_RIO_PIO_TRANSACTION_FAILED_BM          0x00000100

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_STAT_RPIO_U
{
    struct
    {
        ag_mg_regs_register
            rio_pio_transaction_completed : 1,
            fill1 : 7,
            rio_pio_transaction_failed : 1,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_stat_rpio_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_RAB_INTR_STAT_IDME_RO                                     0x00020074
#define AG_MG_REGS_RAB_INTR_STAT_IDME_RM                                     0xFFFFFFFF

#define AG_MG_REGS_RAB_INTR_STAT_IDME_INBOUND_DME_INTERRUPT_BO               0
#define AG_MG_REGS_RAB_INTR_STAT_IDME_INBOUND_DME_INTERRUPT_BM               0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_STAT_IDME_U
{
    struct
    {
        ag_mg_regs_register
            inbound_dme_interrupt;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_stat_idme_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_RAB_INTR_STAT_ODME_RO                                     0x00020078
#define AG_MG_REGS_RAB_INTR_STAT_ODME_RM                                     0x0000003F

#define AG_MG_REGS_RAB_INTR_STAT_ODME_OUTBOUND_DME_INTERRUPT_BO              0
#define AG_MG_REGS_RAB_INTR_STAT_ODME_OUTBOUND_DME_INTERRUPT_BM              0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_STAT_ODME_U
{
    struct
    {
        ag_mg_regs_register
            outbound_dme_interrupt : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_stat_odme_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_RAB_INTR_STAT_MISC_RO                                     0x0002007C
#define AG_MG_REGS_RAB_INTR_STAT_MISC_RM                                     0xFF000FFF

#define AG_MG_REGS_RAB_INTR_STAT_MISC_INBOUND_DOORBELL_RECEIVED_BO           0
#define AG_MG_REGS_RAB_INTR_STAT_MISC_INBOUND_DOORBELL_RECEIVED_BM           0x00000001

#define AG_MG_REGS_RAB_INTR_STAT_MISC_OUTBOUND_DOORBELL_DONE_BO              1
#define AG_MG_REGS_RAB_INTR_STAT_MISC_OUTBOUND_DOORBELL_DONE_BM              0x00000002

#define AG_MG_REGS_RAB_INTR_STAT_MISC_UNEXPECTED_INBOUND_DATA_MSG_BO         2
#define AG_MG_REGS_RAB_INTR_STAT_MISC_UNEXPECTED_INBOUND_DATA_MSG_BM         0x00000004

#define AG_MG_REGS_RAB_INTR_STAT_MISC_UNSUPPORTED_RIO_REQUEST_INT_BO         3
#define AG_MG_REGS_RAB_INTR_STAT_MISC_UNSUPPORTED_RIO_REQUEST_INT_BM         0x00000008

#define AG_MG_REGS_RAB_INTR_STAT_MISC_GRIO_PORT_WRITE_RECEIVED_INT_BO        4
#define AG_MG_REGS_RAB_INTR_STAT_MISC_GRIO_PORT_WRITE_RECEIVED_INT_BM        0x00000010

#define AG_MG_REGS_RAB_INTR_STAT_MISC_GRIO_ERROR_INTERRUPT_BO                5
#define AG_MG_REGS_RAB_INTR_STAT_MISC_GRIO_ERROR_INTERRUPT_BM                0x00000020

#define AG_MG_REGS_RAB_INTR_STAT_MISC_GRIO_LOGICAL_OR_TRANSPORT_ERR_BO       6
#define AG_MG_REGS_RAB_INTR_STAT_MISC_GRIO_LOGICAL_OR_TRANSPORT_ERR_BM       0x00000040

#define AG_MG_REGS_RAB_INTR_STAT_MISC_LINK_IPG_RESET_REQUESTED_BO            7
#define AG_MG_REGS_RAB_INTR_STAT_MISC_LINK_IPG_RESET_REQUESTED_BM            0x00000080

#define AG_MG_REGS_RAB_INTR_ENAB_MISC_CO_OP_LOCK_CLEAR_ENABLE_BO             8
#define AG_MG_REGS_RAB_INTR_ENAB_MISC_CO_OP_LOCK_CLEAR_ENABLE_BM             0x00000100

#define AG_MG_REGS_RAB_INTR_STAT_MISC_LFC_BLOCKED_STATUS_CHANGE_BO           9
#define AG_MG_REGS_RAB_INTR_STAT_MISC_LFC_BLOCKED_STATUS_CHANGE_BM           0x00000200

#define AG_MG_REGS_RAB_INTR_STAT_MISC_AXI_SLAVE_INT_BO                       10
#define AG_MG_REGS_RAB_INTR_STAT_MISC_AXI_SLAVE_INT_BM                       0x00000400

#define AG_MG_REGS_RAB_INTR_STAT_MISC_AXI_MASTER_INT_BO                      11
#define AG_MG_REGS_RAB_INTR_STAT_MISC_AXI_MASTER_INT_BM                      0x00000800

#define AG_MG_REGS_RAB_INTR_STAT_MISC_UNEXPECT_IB_DATA_MESSAGE_LOG_BO        24
#define AG_MG_REGS_RAB_INTR_STAT_MISC_UNEXPECT_IB_DATA_MESSAGE_LOG_BM        0xFF000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_INTR_STAT_MISC_U
{
    struct
    {
        ag_mg_regs_register
            inbound_doorbell_received : 1,
            outbound_doorbell_done : 1,
            unexpected_inbound_data_msg : 1,
            unsupported_rio_request_int : 1,
            grio_port_write_received_int : 1,
            grio_error_interrupt : 1,
            grio_logical_or_transport_err : 1,
            link_ipg_reset_requested : 1,
            co_op_lock_clear_enable : 1,
            lfc_blocked_status_change : 1,
            axi_slave_int : 1,
            axi_master_int : 1,
            fill0 : 12,
            unexpect_ib_data_message_log : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_intr_stat_misc_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_RIO_PIO_CTRL_RO                                       0x00020080
#define AG_MG_REGS_RAB_RIO_PIO_CTRL_RM                                       0x00000003

#define AG_MG_REGS_RAB_RIO_PIO_CTRL_PIO_ENABLE_BO                            0
#define AG_MG_REGS_RAB_RIO_PIO_CTRL_PIO_ENABLE_BM                            0x00000001

#define AG_MG_REGS_RAB_RIO_PIO_CTRL_RELAX_ORDERING_BO                        1
#define AG_MG_REGS_RAB_RIO_PIO_CTRL_RELAX_ORDERING_BM                        0x00000002

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_RIO_PIO_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            pio_enable : 1,
            relax_ordering : 1,
            fill0 : 30;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_rio_pio_ctrl_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_RAB_RIO_PIO_STAT_RO                                       0x00020084
#define AG_MG_REGS_RAB_RIO_PIO_STAT_RM                                       0x00000007

#define AG_MG_REGS_RAB_RIO_PIO_STAT_NOT_ENABLED_BO                           0
#define AG_MG_REGS_RAB_RIO_PIO_STAT_NOT_ENABLED_BM                           0x00000001

#define AG_MG_REGS_RAB_RIO_PIO_STAT_INVALID_ADDRESS_MAPPING_BO               1
#define AG_MG_REGS_RAB_RIO_PIO_STAT_INVALID_ADDRESS_MAPPING_BM               0x00000002

#define AG_MG_REGS_RAB_RIO_PIO_STAT_AXI_RESPONSE_ERROR_BO                    2
#define AG_MG_REGS_RAB_RIO_PIO_STAT_AXI_RESPONSE_ERROR_BM                    0x00000004

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_RIO_PIO_STAT_U
{
    struct
    {
        ag_mg_regs_register
            not_enabled : 1,
            invalid_address_mapping : 1,
            axi_response_error : 1,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_rio_pio_stat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_RIO_AMAP_LUT_RO                                       0x00020100
#define AG_MG_REGS_RAB_RIO_AMAP_LUT_RM                                       0xFFFFC01F
#define AG_MG_REGS_RAB_RIO_AMAP_LUT_RPT                                      16
#define AG_MG_REGS_RAB_RIO_AMAP_LUT_IVL                                      0x4

#define AG_MG_REGS_RAB_RIO_AMAP_LUT_ENABLE_BO                                0
#define AG_MG_REGS_RAB_RIO_AMAP_LUT_ENABLE_BM                                0x00000001

#define AG_MG_REGS_RAB_RIO_AMAP_LUT_WINDOW_SIZE_BO                           1
#define AG_MG_REGS_RAB_RIO_AMAP_LUT_WINDOW_SIZE_BM                           0x0000001E

#define AG_MG_REGS_RAB_RIO_AMAP_LUT_OFFSET_BO                                14
#define AG_MG_REGS_RAB_RIO_AMAP_LUT_OFFSET_BM                                0xFFFFC000
#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_RIO_AMAP_LUT_U
{
    struct
    {
        ag_mg_regs_register
            enable : 1,
            window_size : 4,
            fill0 : 9,
            offset : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_rio_amap_lut_u;
#endif


/*
 * Initialization value: 0x00000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_RIO_AMAP_IDSL_RO                                      0x00020140
#define AG_MG_REGS_RAB_RIO_AMAP_IDSL_RM                                      0x0000003F

#define AG_MG_REGS_RAB_RIO_AMAP_IDSL_BIT_SELECT_BO                           0
#define AG_MG_REGS_RAB_RIO_AMAP_IDSL_BIT_SELECT_BM                           0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_RIO_AMAP_IDSL_U
{
    struct
    {
        ag_mg_regs_register
            bit_select : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_rio_amap_idsl_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_RIO_AMAP_BYPS_RO                                      0x00020144
#define AG_MG_REGS_RAB_RIO_AMAP_BYPS_RM                                      0x00000001

#define AG_MG_REGS_RAB_RIO_AMAP_BYPS_ENABLE_BO                               0
#define AG_MG_REGS_RAB_RIO_AMAP_BYPS_ENABLE_BM                               0x00000001

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_RIO_AMAP_BYPS_U
{
    struct
    {
        ag_mg_regs_register
            enable : 1,
            fill0 : 31;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_rio_amap_byps_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_AXI_PIO_CTRL_RO                                       0x00020180
#define AG_MG_REGS_RAB_AXI_PIO_CTRL_RM                                       0x0000000F

#define AG_MG_REGS_RAB_AXI_PIO_CTRL_PIO_ENABLE_BO                            0
#define AG_MG_REGS_RAB_AXI_PIO_CTRL_PIO_ENABLE_BM                            0x00000001

#define AG_MG_REGS_RAB_AXI_PIO_CTRL_MEMORY_MAPPING_ENABLE_BO                 1
#define AG_MG_REGS_RAB_AXI_PIO_CTRL_MEMORY_MAPPING_ENABLE_BM                 0x00000002

#define AG_MG_REGS_RAB_AXI_PIO_CTRL_MAINTENANCE_MAPPING_ENABLE_BO            2
#define AG_MG_REGS_RAB_AXI_PIO_CTRL_MAINTENANCE_MAPPING_ENABLE_BM            0x00000004

#define AG_MG_REGS_RAB_AXI_PIO_CTRL_CCP_ENABLE_BO                            3
#define AG_MG_REGS_RAB_AXI_PIO_CTRL_CCP_ENABLE_BM                            0x00000008

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_AXI_PIO_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            pio_enable : 1,
            memory_mapping_enable : 1,
            maintenance_mapping_enable : 1,
            ccp_enable : 1,
            fill0 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_axi_pio_ctrl_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_RAB_AXI_PIO_STAT_RO                                       0x00020184
#define AG_MG_REGS_RAB_AXI_PIO_STAT_RM                                       0x0000007F

#define AG_MG_REGS_RAB_AXI_PIO_STAT_ENGINE_NOT_ENABLED_BO                    0
#define AG_MG_REGS_RAB_AXI_PIO_STAT_ENGINE_NOT_ENABLED_BM                    0x00000001

#define AG_MG_REGS_RAB_AXI_PIO_STAT_MEMORY_MAPPING_NOT_ENABLED_BO            1
#define AG_MG_REGS_RAB_AXI_PIO_STAT_MEMORY_MAPPING_NOT_ENABLED_BM            0x00000002

#define AG_MG_REGS_RAB_AXI_PIO_STAT_MAINTENANCE_MAPPING_NOT_ENABLED_BO       2
#define AG_MG_REGS_RAB_AXI_PIO_STAT_MAINTENANCE_MAPPING_NOT_ENABLED_BM       0x00000004

#define AG_MG_REGS_RAB_AXI_PIO_STAT_INVALID_AXI_ADDRESS_MAPPING_BO           3
#define AG_MG_REGS_RAB_AXI_PIO_STAT_INVALID_AXI_ADDRESS_MAPPING_BM           0x00000008

#define AG_MG_REGS_RAB_AXI_PIO_STAT_RIO_RESPONSE_ERROR_BO                    4
#define AG_MG_REGS_RAB_AXI_PIO_STAT_RIO_RESPONSE_ERROR_BM                    0x00000010

#define AG_MG_REGS_RAB_AXI_PIO_STAT_RIO_TIMEOUT_ERROR_BO                     5
#define AG_MG_REGS_RAB_AXI_PIO_STAT_RIO_TIMEOUT_ERROR_BM                     0x00000020

#define AG_MG_REGS_RAB_AXI_PIO_STAT_AXI_REQUEST_ERROR_BO                     6
#define AG_MG_REGS_RAB_AXI_PIO_STAT_AXI_REQUEST_ERROR_BM                     0x00000040

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_AXI_PIO_STAT_U
{
    struct
    {
        ag_mg_regs_register
            engine_not_enabled : 1,
            memory_mapping_not_enabled : 1,
            maintenance_mapping_not_enabled : 1,
            invalid_axi_address_mapping : 1,
            rio_response_error : 1,
            rio_timeout_error : 1,
            axi_request_error : 1,
            fill0 : 25;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_axi_pio_stat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_RAB_ASLV_STAT_CMD_RO                                      0x000201C0
#define AG_MG_REGS_RAB_ASLV_STAT_CMD_RM                                      0x03FFFFFF

#define AG_MG_REGS_RAB_ASLV_STAT_CMD_UNSUPPORTED_COMMAND_BO                  0
#define AG_MG_REGS_RAB_ASLV_STAT_CMD_UNSUPPORTED_COMMAND_BM                  0x00000001

#define AG_MG_REGS_RAB_ASLV_STAT_CMD_ERROR_LOG_COMMAND_BO                    1
#define AG_MG_REGS_RAB_ASLV_STAT_CMD_ERROR_LOG_COMMAND_BM                    0x03FFFFFE

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_ASLV_STAT_CMD_U
{
    struct
    {
        ag_mg_regs_register
            unsupported_command : 1,
            error_log_command : 25,
            fill0 : 6;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_aslv_stat_cmd_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_RAB_ASLV_STAT_ADDR_RO                                     0x000201C4
#define AG_MG_REGS_RAB_ASLV_STAT_ADDR_RM                                     0xFFFFFFFF

#define AG_MG_REGS_RAB_ASLV_STAT_ADDR_ERROR_LOG_ADDRESS_BO                   0
#define AG_MG_REGS_RAB_ASLV_STAT_ADDR_ERROR_LOG_ADDRESS_BM                   0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_ASLV_STAT_ADDR_U
{
    struct
    {
        ag_mg_regs_register
            error_log_address;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_aslv_stat_addr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_RAB_AMST_STAT_RO                                          0x000201E0
#define AG_MG_REGS_RAB_AMST_STAT_RM                                          0x0000003F

#define AG_MG_REGS_RAB_AMST_STAT_READ_SLAVE_ERROR_BO                         0
#define AG_MG_REGS_RAB_AMST_STAT_READ_SLAVE_ERROR_BM                         0x00000001

#define AG_MG_REGS_RAB_AMST_STAT_READ_DECODE_ERROR_BO                        1
#define AG_MG_REGS_RAB_AMST_STAT_READ_DECODE_ERROR_BM                        0x00000002

#define AG_MG_REGS_RAB_AMST_STAT_WRITE_SLAVE_ERROR_BO                        2
#define AG_MG_REGS_RAB_AMST_STAT_WRITE_SLAVE_ERROR_BM                        0x00000004

#define AG_MG_REGS_RAB_AMST_STAT_WRITE_DECODE_ERROR_BO                       3
#define AG_MG_REGS_RAB_AMST_STAT_WRITE_DECODE_ERROR_BM                       0x00000008

#define AG_MG_REGS_RAB_AMST_STAT_READ_TIMEOUT_ERROR_BO                       4
#define AG_MG_REGS_RAB_AMST_STAT_READ_TIMEOUT_ERROR_BM                       0x00000010

#define AG_MG_REGS_RAB_AMST_STAT_WRITE_TIMEOUT_ERROR_BO                      5
#define AG_MG_REGS_RAB_AMST_STAT_WRITE_TIMEOUT_ERROR_BM                      0x00000020

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_AMST_STAT_U
{
    struct
    {
        ag_mg_regs_register
            read_slave_error : 1,
            read_decode_error : 1,
            write_slave_error : 1,
            write_decode_error : 1,
            read_timeout_error : 1,
            write_timeout_error : 1,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_amst_stat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_RO                                     0x00020200
#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_RM                                     0xFFFF007F
#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_RPT                                    16
#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_IVL                                    0x10

#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_ENABLE_BO                              0
#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_ENABLE_BM                              0x00000001

#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_TYPE_BO                                1
#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_TYPE_BM                                0x00000006

#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_PRIORITY_BO                            3
#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_PRIORITY_BM                            0x00000018

#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_X_ADDRESS_BO                           5
#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_X_ADDRESS_BM                           0x00000060

#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_DESTINATION_ID_BO                      16
#define AG_MG_REGS_RAB_APIO_AMAP_CTRL_DESTINATION_ID_BM                      0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_APIO_AMAP_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            enable : 1,
            type : 2,
            priority : 2,
            x_address : 2,
            fill0 : 9,
            destination_id : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_apio_amap_ctrl_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_APIO_AMAP_SIZE_RO                                    0x00020204
#define AG_MG_REGS_RAB_APIO_AMAP_SIZE_RM                                    0xFFFFFC00
#define AG_MG_REGS_RAB_APIO_AMAP_SIZE_RPT                                   16
#define AG_MG_REGS_RAB_APIO_AMAP_SIZE_IVL                                   0x10

#define AG_MG_REGS_RAB_APIO_AMAP_SIZE_AXI_WINDOW_SIZE_BO                    10
#define AG_MG_REGS_RAB_APIO_AMAP_SIZE_AXI_WINDOW_SIZE_BM                    0xFFFFFC00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_APIO_AMAP_SIZE_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 10,
            axi_window_size : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_apio_amap_size_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_APIO_AMAP_ABAR_RO                                     0x00020208
#define AG_MG_REGS_RAB_APIO_AMAP_ABAR_RM                                     0x0FFFFFFF
#define AG_MG_REGS_RAB_APIO_AMAP_ABAR_RPT                                    16
#define AG_MG_REGS_RAB_APIO_AMAP_ABAR_IVL                                    0x10

#define AG_MG_REGS_RAB_APIO_AMAP_ABAR_AXI_WINDOW_BASE_BM 0x003FFFFF
#define AG_MG_REGS_RAB_APIO_AMAP_ABAR_AXI_WINDOW_BASE_BO 0

#define AG_MG_REGS_RAB_APIO_AMAP_ABAR_AXI_BASE_UPPER_BM 0x0FC00000
#define AG_MG_REGS_RAB_APIO_AMAP_ABAR_AXI_BASE_UPPER_BO 22

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_APIO_AMAP_ABAR_U
{
    struct
    {
        ag_mg_regs_register
            axi_window_base : 22,
            axi_base_upper : 6,
            fill0 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_apio_amap_abar_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_APIO_AMAP_RBAR_RO                                     0x0002020C
#define AG_MG_REGS_RAB_APIO_AMAP_RBAR_RM                                     0x003FFFFF
#define AG_MG_REGS_RAB_APIO_AMAP_RBAR_RPT                                    16
#define AG_MG_REGS_RAB_APIO_AMAP_RBAR_IVL                                    0x10

#define AG_MG_REGS_RAB_APIO_AMAP_RBAR_RIO_ADDRESS_BASE_BM 0x003FFFFF
#define AG_MG_REGS_RAB_APIO_AMAP_RBAR_RIO_ADDRESS_BASE_BO 0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_APIO_AMAP_RBAR_U
{
    struct
    {
        ag_mg_regs_register
            rio_address_base : 22,
            fill0 : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_apio_amap_rbar_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_OB_DB_CSR_RO                                          0x00020400
#define AG_MG_REGS_RAB_OB_DB_CSR_RM                                          0xFFFF003F
#define AG_MG_REGS_RAB_OB_DB_CSR_RPT                                         8
#define AG_MG_REGS_RAB_OB_DB_CSR_IVL                                         0x8

#define AG_MG_REGS_RAB_OB_DB_CSR_SEND_BO                                     0
#define AG_MG_REGS_RAB_OB_DB_CSR_SEND_BM                                     0x00000001

#define AG_MG_REGS_RAB_OB_DB_CSR_STATUS_BO                                   1
#define AG_MG_REGS_RAB_OB_DB_CSR_STATUS_BM                                   0x0000000E

#define AG_MG_REGS_RAB_OB_DB_CSR_PRIORITY_BO                                 4
#define AG_MG_REGS_RAB_OB_DB_CSR_PRIORITY_BM                                 0x00000030

#define AG_MG_REGS_RAB_OB_DB_CSR_DESTINATION_ID_BO                           16
#define AG_MG_REGS_RAB_OB_DB_CSR_DESTINATION_ID_BM                           0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_OB_DB_CSR_U
{
    struct
    {
        ag_mg_regs_register
            send : 1,
            status : 3,
            priority : 2,
            fill0 : 10,
            destination_id : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ob_db_csr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_OB_DB_INFO_RO                                         0x00020404
#define AG_MG_REGS_RAB_OB_DB_INFO_RM                                         0x0000FFFF
#define AG_MG_REGS_RAB_OB_DB_INFO_RPT                                        8
#define AG_MG_REGS_RAB_OB_DB_INFO_IVL                                        0x8

#define AG_MG_REGS_RAB_OB_DB_INFO_INFO_BO                                    0
#define AG_MG_REGS_RAB_OB_DB_INFO_INFO_BM                                    0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_OB_DB_INFO_U
{
    struct
    {
        ag_mg_regs_register
            info : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ob_db_info_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_OB_IDB_CSR_RO                                         0x00020478
#define AG_MG_REGS_RAB_OB_IDB_CSR_RM                                         0xFFFF007E

#define AG_MG_REGS_RAB_OB_IDB_CSR_STATUS_BO                                  1
#define AG_MG_REGS_RAB_OB_IDB_CSR_STATUS_BM                                  0x0000000E

#define AG_MG_REGS_RAB_OB_IDB_CSR_PRIORITY_BO                                4
#define AG_MG_REGS_RAB_OB_IDB_CSR_PRIORITY_BM                                0x00000030

#define AG_MG_REGS_RAB_OB_IDB_CSR_INFO_SELECT_BO                             6
#define AG_MG_REGS_RAB_OB_IDB_CSR_INFO_SELECT_BM                             0x00000040

#define AG_MG_REGS_RAB_OB_IDB_CSR_DESTINATION_ID_BO                          16
#define AG_MG_REGS_RAB_OB_IDB_CSR_DESTINATION_ID_BM                          0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_OB_IDB_CSR_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 1,
            status : 3,
            priority : 2,
            info_select : 1,
            fill0 : 9,
            destination_id : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ob_idb_csr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_OB_IDB_INFO_RO                                        0x0002047C
#define AG_MG_REGS_RAB_OB_IDB_INFO_RM                                        0x0000FFFF

#define AG_MG_REGS_RAB_OB_IDB_INFO_INFO_FIELD_BO                             0
#define AG_MG_REGS_RAB_OB_IDB_INFO_INFO_FIELD_BM                             0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_OB_IDB_INFO_U
{
    struct
    {
        ag_mg_regs_register
            info_field : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ob_idb_info_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_IB_DB_CSR_RO                                          0x00020480
#define AG_MG_REGS_RAB_IB_DB_CSR_RM                                          0x003F0001

#define AG_MG_REGS_RAB_IB_DB_CSR_ENABLE_BO                                   0
#define AG_MG_REGS_RAB_IB_DB_CSR_ENABLE_BM                                   0x00000001

#define AG_MG_REGS_RAB_IB_DB_CSR_NUMBER_OF_MESSAGES_BO                       16
#define AG_MG_REGS_RAB_IB_DB_CSR_NUMBER_OF_MESSAGES_BM                       0x003F0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_IB_DB_CSR_U
{
    struct
    {
        ag_mg_regs_register
            enable : 1,
            fill1 : 15,
            number_of_messages : 6,
            fill0 : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ib_db_csr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_RAB_IB_DB_INFO_RO                                         0x00020484
#define AG_MG_REGS_RAB_IB_DB_INFO_RM                                         0xFFFFFFFF

#define AG_MG_REGS_RAB_IB_DB_INFO_INFO_BO                                    0
#define AG_MG_REGS_RAB_IB_DB_INFO_INFO_BM                                    0x0000FFFF

#define AG_MG_REGS_RAB_IB_DB_INFO_SOURCE_ID_BO                               16
#define AG_MG_REGS_RAB_IB_DB_INFO_SOURCE_ID_BM                               0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_IB_DB_INFO_U
{
    struct
    {
        ag_mg_regs_register
            info : 16,
            source_id : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ib_db_info_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_OB_DME_CTRL_RO                                        0x00020500
#define AG_MG_REGS_RAB_OB_DME_CTRL_RM                                        0xFF000033
#define AG_MG_REGS_RAB_OB_DME_CTRL_RPT                                       6
#define AG_MG_REGS_RAB_OB_DME_CTRL_IVL                                       0x10

#define AG_MG_REGS_RAB_OB_DME_CTRL_ENGINE_ENABLE_BO                          0
#define AG_MG_REGS_RAB_OB_DME_CTRL_ENGINE_ENABLE_BM                          0x00000001

#define AG_MG_REGS_RAB_OB_DME_CTRL_ENGINE_WAKEUP_BO                          1
#define AG_MG_REGS_RAB_OB_DME_CTRL_ENGINE_WAKEUP_BM                          0x00000002

#define AG_MG_REGS_RAB_OB_DME_CTRL_BUFFER_FULL_THRESHOLD_BO		 	4
#define AG_MG_REGS_RAB_OB_DME_CTRL_BUFFER_FULL_THRESHOLD_BM		 	0x00000030

#define AG_MG_REGS_RAB_OB_DME_CTRL_INDIRECT_ACCESS_DESCRIPTOR_SEL_BO         24
#define AG_MG_REGS_RAB_OB_DME_CTRL_INDIRECT_ACCESS_DESCRIPTOR_SEL_BM         0x0F000000

#define AG_MG_REGS_RAB_OB_DME_CTRL_INDIRECT_ACCESS_WORD_SELECT_BO            28
#define AG_MG_REGS_RAB_OB_DME_CTRL_INDIRECT_ACCESS_WORD_SELECT_BM            0x30000000

#define AG_MG_REGS_RAB_OB_DME_CTRL_DESC_CHAIN_ADDR_UPPER_BO                  30
#define AG_MG_REGS_RAB_OB_DME_CTRL_DESC_CHAIN_ADDR_UPPER_BM                  0xC0000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_OB_DME_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            engine_enable : 1,
            engine_wakeup : 1,
            fill0 : 2,
            buffer_full_threshold : 2,
            fill1 : 18,
            indirect_access_descriptor_sel : 4,
            indirect_access_word_select : 2,
            desc_chain_addr_upper : 2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ob_dme_ctrl_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_OB_DME_ADDR_RO                                        0x00020504
#define AG_MG_REGS_RAB_OB_DME_ADDR_RM                                        0xFFFFFFFF
#define AG_MG_REGS_RAB_OB_DME_ADDR_RPT                                       6
#define AG_MG_REGS_RAB_OB_DME_ADDR_IVL                                       0x10

#define AG_MG_REGS_RAB_OB_DME_ADDR_DESCRIPTOR_CHAIN_ADDRESS_BO               0
#define AG_MG_REGS_RAB_OB_DME_ADDR_DESCRIPTOR_CHAIN_ADDRESS_BM               0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_OB_DME_ADDR_U
{
    struct
    {
        ag_mg_regs_register
            descriptor_chain_address;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ob_dme_addr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_RAB_OB_DME_STAT_RO                                        0x00020508
#define AG_MG_REGS_RAB_OB_DME_STAT_RM                                        0x000003FF
#define AG_MG_REGS_RAB_OB_DME_STAT_RPT                                       6
#define AG_MG_REGS_RAB_OB_DME_STAT_IVL                                       0x10

#define AG_MG_REGS_RAB_OB_DME_STAT_DESCRIPTOR_CHAIN_COMPLETED_BO             0
#define AG_MG_REGS_RAB_OB_DME_STAT_DESCRIPTOR_CHAIN_COMPLETED_BM             0x00000001

#define AG_MG_REGS_RAB_OB_DME_STAT_DESCRIPTOR_TRANSFER_COMPLETED_BO          1
#define AG_MG_REGS_RAB_OB_DME_STAT_DESCRIPTOR_TRANSFER_COMPLETED_BM          0x00000002

#define AG_MG_REGS_RAB_OB_DME_STAT_DESCRIPTOR_FETCH_ERROR_BO                 2
#define AG_MG_REGS_RAB_OB_DME_STAT_DESCRIPTOR_FETCH_ERROR_BM                 0x00000004

#define AG_MG_REGS_RAB_OB_DME_STAT_DESCRIPTOR_ERROR_BO                       3
#define AG_MG_REGS_RAB_OB_DME_STAT_DESCRIPTOR_ERROR_BM                       0x00000008

#define AG_MG_REGS_RAB_OB_DME_STAT_DESCRIPTOR_UPDATE_ERROR_BO                4
#define AG_MG_REGS_RAB_OB_DME_STAT_DESCRIPTOR_UPDATE_ERROR_BM                0x00000010

#define AG_MG_REGS_RAB_OB_DME_STAT_DATA_TRANSACTION_ERROR_BO                 5
#define AG_MG_REGS_RAB_OB_DME_STAT_DATA_TRANSACTION_ERROR_BM                 0x00000020

#define AG_MG_REGS_RAB_OB_DME_STAT_MESSAGE_RESPONSE_ERROR_BO                 6
#define AG_MG_REGS_RAB_OB_DME_STAT_MESSAGE_RESPONSE_ERROR_BM                 0x00000040

#define AG_MG_REGS_RAB_OB_DME_STAT_MESSAGE_RESPONSE_TIMEOUT_BO               7
#define AG_MG_REGS_RAB_OB_DME_STAT_MESSAGE_RESPONSE_TIMEOUT_BM               0x00000080

#define AG_MG_REGS_RAB_OB_DME_STAT_TRANSACTION_PENDING_BO                    8
#define AG_MG_REGS_RAB_OB_DME_STAT_TRANSACTION_PENDING_BM                    0x00000100

#define AG_MG_REGS_RAB_OB_DME_STAT_SLEEPING_BO                               9
#define AG_MG_REGS_RAB_OB_DME_STAT_SLEEPING_BM                               0x00000200

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_OB_DME_STAT_U
{
    struct
    {
        ag_mg_regs_register
            descriptor_chain_completed : 1,
            descriptor_transfer_completed : 1,
            descriptor_fetch_error : 1,
            descriptor_error : 1,
            descriptor_update_error : 1,
            data_transaction_error : 1,
            message_response_error : 1,
            message_response_timeout : 1,
            transaction_pending : 1,
            sleeping : 1,
            fill0 : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ob_dme_stat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_RAB_OB_DME_DESC_RO                                        0x0002050C
#define AG_MG_REGS_RAB_OB_DME_DESC_RM                                        0xFFFFFFFF
#define AG_MG_REGS_RAB_OB_DME_DESC_RPT                                       6
#define AG_MG_REGS_RAB_OB_DME_DESC_IVL                                       0x10

#define AG_MG_REGS_RAB_OB_DME_DESC_DESCRIPTOR_INFO_BO                        0
#define AG_MG_REGS_RAB_OB_DME_DESC_DESCRIPTOR_INFO_BM                        0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_OB_DME_DESC_U
{
    struct
    {
        ag_mg_regs_register
            descriptor_info;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ob_dme_desc_u;
#endif


/*
 * Initialization value: 0x00FFFFFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_OB_DME_TIDMSK_RO										0x000205F0
#define AG_MG_REGS_RAB_OB_DME_TIDMSK_RM										0x00FFFFFF

#define AG_MG_REGS_RAB_OB_DME_TIDMSK_DESTINATION_ID_MASK_BO					0
#define AG_MG_REGS_RAB_OB_DME_TIDMSK_DESTINATION_ID_MASK_BM					0x0000FFFF

#define AG_MG_REGS_RAB_OB_DME_TIDMSK_LETTER_MASK_BO							16
#define AG_MG_REGS_RAB_OB_DME_TIDMSK_LETTER_MASK_BM							0x00030000

#define AG_MG_REGS_RAB_OB_DME_TIDMSK_MBOX_MASK_BO							18
#define AG_MG_REGS_RAB_OB_DME_TIDMSK_MBOX_MASK_BM							0x000C0000

#define AG_MG_REGS_RAB_OB_DME_TIDMSK_XMBOX_MASK_BO							20
#define AG_MG_REGS_RAB_OB_DME_TIDMSK_XMBOX_MASK_BM							0x00F00000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union RAB_OB_DME_TIDMSK_U
{
    struct
    {
    	ag_mg_regs_register
			destination_id_mask : 16,
			letter_mask : 2,
			mbox_mask : 2,
			xmbox_mask : 4,
			fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ob_dme_tidmsk_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_IB_DME_CTRL_RO                                        0x00020600
#define AG_MG_REGS_RAB_IB_DME_CTRL_RM                                        0xF0000FF3
#define AG_MG_REGS_RAB_IB_DME_CTRL_RPT                                       32
#define AG_MG_REGS_RAB_IB_DME_CTRL_IVL                                       0x10

#define AG_MG_REGS_RAB_IB_DME_CTRL_ENGINE_ENABLE_BO                           0
#define AG_MG_REGS_RAB_IB_DME_CTRL_ENGINE_ENABLE_BM                           0x00000001

#define AG_MG_REGS_RAB_IB_DME_CTRL_ENGINE_WAKEUP_BO                          1
#define AG_MG_REGS_RAB_IB_DME_CTRL_ENGINE_WAKEUP_BM                          0x00000002

#define AG_MG_REGS_RAB_IB_DME_CTRL_LETTER_BO                                 4
#define AG_MG_REGS_RAB_IB_DME_CTRL_LETTER_BM                                 0x00000030

#define AG_MG_REGS_RAB_IB_DME_CTRL_MBOX_BO                                   6
#define AG_MG_REGS_RAB_IB_DME_CTRL_MBOX_BM                                   0x000000C0

#define AG_MG_REGS_RAB_IB_DME_CTRL_XMBOX_BO                                  8
#define AG_MG_REGS_RAB_IB_DME_CTRL_XMBOX_BM                                  0x00000F00

#define AG_MG_REGS_RAB_IB_DME_CTRL_DESCRIPTOR_INDIRECT_ACCESS_SEL_BO         28
#define AG_MG_REGS_RAB_IB_DME_CTRL_DESCRIPTOR_INDIRECT_ACCESS_SEL_BM         0x30000000

#define AG_MG_REGS_RAB_IB_DME_CTRL_DESCRIPTOR_CHAIN_UPPER_ADD_BO             30
#define AG_MG_REGS_RAB_IB_DME_CTRL_DESCRIPTOR_CHAIN_UPPER_ADD_BM             0xC0000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_IB_DME_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            engine_enable : 1,
            engine_wakeup : 1,
            fill1 : 2,
            letter : 2,
            mbox : 2,
            xmbox : 4,
            fill0 : 16,
            descriptor_indirect_access_sel : 2,
            descriptor_chain_upper_add : 2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ib_dme_ctrl_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_IB_DME_ADDR_RO                                        0x00020604
#define AG_MG_REGS_RAB_IB_DME_ADDR_RM                                        0xFFFFFFFF
#define AG_MG_REGS_RAB_IB_DME_ADDR_RPT                                       32
#define AG_MG_REGS_RAB_IB_DME_ADDR_IVL                                       0x10

#define AG_MG_REGS_RAB_IB_DME_ADDR_DESCRIPTOR_CHAIN_ADDRESS_BO               0
#define AG_MG_REGS_RAB_IB_DME_ADDR_DESCRIPTOR_CHAIN_ADDRESS_BM               0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_IB_DME_ADDR_U
{
    struct
    {
        ag_mg_regs_register
            descriptor_chain_address;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ib_dme_addr_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_RAB_IB_DME_STAT_RO                                        0x00020608
#define AG_MG_REGS_RAB_IB_DME_STAT_RM                                        0x000003FF
#define AG_MG_REGS_RAB_IB_DME_STAT_RPT                                       32
#define AG_MG_REGS_RAB_IB_DME_STAT_IVL                                       0x10

#define AG_MG_REGS_RAB_IB_DME_STAT_DESCRIPTOR_CHAIN_COMPLETED_BO             0
#define AG_MG_REGS_RAB_IB_DME_STAT_DESCRIPTOR_CHAIN_COMPLETED_BM             0x00000001

#define AG_MG_REGS_RAB_IB_DME_STAT_DESCRIPTOR_TRANSFER_COMPLETED_BO          1
#define AG_MG_REGS_RAB_IB_DME_STAT_DESCRIPTOR_TRANSFER_COMPLETED_BM          0x00000002

#define AG_MG_REGS_RAB_IB_DME_STAT_DESCRIPTOR_FETCH_ERROR_BO                 2
#define AG_MG_REGS_RAB_IB_DME_STAT_DESCRIPTOR_FETCH_ERROR_BM                 0x00000004

#define AG_MG_REGS_RAB_IB_DME_STAT_DESCRIPTOR_ERROR_BO                       3
#define AG_MG_REGS_RAB_IB_DME_STAT_DESCRIPTOR_ERROR_BM                       0x00000008

#define AG_MG_REGS_RAB_IB_DME_STAT_DESCRIPTOR_UPDATE_ERROR_BO                4
#define AG_MG_REGS_RAB_IB_DME_STAT_DESCRIPTOR_UPDATE_ERROR_BM                0x00000010

#define AG_MG_REGS_RAB_IB_DME_STAT_DATA_TRANSACTION_ERROR_BO                 5
#define AG_MG_REGS_RAB_IB_DME_STAT_DATA_TRANSACTION_ERROR_BM                 0x00000020

#define AG_MG_REGS_RAB_IB_DME_STAT_MESSAGE_ERROR_BO                          6
#define AG_MG_REGS_RAB_IB_DME_STAT_MESSAGE_ERROR_BM                          0x00000040

#define AG_MG_REGS_RAB_IB_DME_STAT_MESSAGE_TIMEOUT_BO                        7
#define AG_MG_REGS_RAB_IB_DME_STAT_MESSAGE_TIMEOUT_BM                        0x00000080

#define AG_MG_REGS_RAB_IB_DME_STAT_TRANSACTION_PENDING_BO                    8
#define AG_MG_REGS_RAB_IB_DME_STAT_TRANSACTION_PENDING_BM                    0x00000100

#define AG_MG_REGS_RAB_IB_DME_STAT_SLEEPING_BO                               9
#define AG_MG_REGS_RAB_IB_DME_STAT_SLEEPING_BM                               0x00000200

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_IB_DME_STAT_U
{
    struct
    {
        ag_mg_regs_register
            descriptor_chain_completed : 1,
            descriptor_transfer_completed : 1,
            descriptor_fetch_error : 1,
            descriptor_error : 1,
            descriptor_update_error : 1,
            data_transaction_error : 1,
            message_error : 1,
            message_timeout : 1,
            transaction_pending : 1,
            sleeping : 1,
            fill0 : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ib_dme_stat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_IB_DME_DESC_RO                                        0x0002060C
#define AG_MG_REGS_RAB_IB_DME_DESC_RM                                        0xFFFFFFFF
#define AG_MG_REGS_RAB_IB_DME_DESC_RPT                                       32
#define AG_MG_REGS_RAB_IB_DME_DESC_IVL                                       0x10

#define AG_MG_REGS_RAB_IB_DME_DESC_DESCRIPTOR_INFO_BO                        0
#define AG_MG_REGS_RAB_IB_DME_DESC_DESCRIPTOR_INFO_BM                        0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_IB_DME_DESC_U
{
    struct
    {
        ag_mg_regs_register
            descriptor_info;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_ib_dme_desc_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_LFC_CSR_RO                                            0x00020920
#define AG_MG_REGS_RAB_LFC_CSR_RM                                            0xFFFFFF0D
#define AG_MG_REGS_RAB_LFC_CSR_RPT                                           8
#define AG_MG_REGS_RAB_LFC_CSR_IVL                                           0x4

#define AG_MG_REGS_RAB_LFC_CSR_ENABLE_BO                                     0
#define AG_MG_REGS_RAB_LFC_CSR_ENABLE_BM                                     0x00000001

#define AG_MG_REGS_RAB_LFC_CSR_PRIORITY_BO                                   2
#define AG_MG_REGS_RAB_LFC_CSR_PRIORITY_BM                                   0x0000000C

#define AG_MG_REGS_RAB_LFC_CSR_XOFF_COUNTER_BO                               8
#define AG_MG_REGS_RAB_LFC_CSR_XOFF_COUNTER_BM                               0x0000FF00

#define AG_MG_REGS_RAB_LFC_CSR_TARGET_DEST_ID_BO                           16
#define AG_MG_REGS_RAB_LFC_CSR_TARGET_DEST_ID_BM                           0xFFFF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_LFC_CSR_U
{
    struct
    {
        ag_mg_regs_register
            enable : 1,
            fill1 : 1,
            priority : 2,
            fill0 : 4,
            xoff_counter : 8,
            target_dest_id : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_lfc_csr_u;
#endif


/*
 * Initialization value: 0x00000FFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_LFC_TIMEOUT_RO                                        0x00020960
#define AG_MG_REGS_RAB_LFC_TIMEOUT_RM                                        0x00000FFF

#define AG_MG_REGS_RAB_LFC_TIMEOUT_TIMEOUT_BO                                0
#define AG_MG_REGS_RAB_LFC_TIMEOUT_TIMEOUT_BM                                0x00000FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_LFC_TIMEOUT_U
{
    struct
    {
        ag_mg_regs_register
            timeout : 12,
            fill0 : 20;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_lfc_timeout_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_LFC_BLOCKED_RO                                        0x00020964
#define AG_MG_REGS_RAB_LFC_BLOCKED_RM                                        0x0000FFFF

#define AG_MG_REGS_RAB_LFC_BLOCKED_BLOCKED_BO                                0
#define AG_MG_REGS_RAB_LFC_BLOCKED_BLOCKED_BM                                0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_LFC_BLOCKED_U
{
    struct
    {
        ag_mg_regs_register
            blocked : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_lfc_blocked_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFE
 * Access mode: Read/Write
 */
#define AG_MG_REGS_RAB_SRDS_CTRL0_RO                 0x00020980
#define AG_MG_REGS_RAB_SRDS_CTRL0_RM                 0x00000001

#define AG_MG_REGS_RAB_SRDS_CTRL0_LOOPBACK_BO        0
#define AG_MG_REGS_RAB_SRDS_CTRL0_LOOPBACK_BM        0x00000001

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RAB_SRDS_CTRL0_U
{
    struct
    {
        ag_mg_regs_register
            loopback : 1,
            fill0 : 31;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_rab_srds_ctrl0_u;
#endif

/*
 * Physical register addresses (for accessing srio physical registers)
 */
#define AG_MG_REGS_SRIO_PHYS_BASE		0x98040000
#define AG_MG_REGS_SRIO_PHYS_REG(p,ro)		(AG_MG_REGS_SRIO_PHYS_BASE + ((p)*0x1000) + ro)

/*
 * Virtual register addresses (for arm accessing srio_rab)
 */
#define AG_MG_REGS_SRIO_RAB_BASE		0x98060000
#define AG_MG_REGS_SRIO_RAB_REG(p,ro)	(AG_MG_REGS_SRIO_RAB_BASE + ((p)*0x1000) + ro)

#define AG_MG_REGS_SRIO_RAB_VER_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_VER_RO)
#define AG_MG_REGS_SRIO_RAB_CAPA_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_CAPA_RO)
#define AG_MG_REGS_SRIO_RAB_CTRL_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_CTRL_RO)
#define AG_MG_REGS_SRIO_RAB_STAT_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_STAT_RO)
#define AG_MG_REGS_SRIO_RAB_AXI_TIMEOUT_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_AXI_TIMEOUT_RO)
#define AG_MG_REGS_SRIO_RAB_DME_TIMEOUT_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_DME_TIMEOUT_RO)
#define AG_MG_REGS_SRIO_RAB_RST_CTRL_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_RST_CTRL_RO)
#define AG_MG_REGS_SRIO_RAB_COOP_LOCK_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_COOP_LOCK_RO)
#define AG_MG_REGS_SRIO_RAB_STAT_ESEL_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_STAT_ESEL_RO)
#define AG_MG_REGS_SRIO_RAB_STAT_STAT_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_STAT_STAT_RO)
#define AG_MG_REGS_SRIO_RAB_IB_PW_CSR_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_IB_PW_CSR_RO)
#define AG_MG_REGS_SRIO_RAB_IB_PW_DATA_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_IB_PW_DATA_RO)
#define AG_MG_REGS_SRIO_RAB_APB_CSR_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_APB_CSR_RO)
#define AG_MG_REGS_SRIO_RAB_ARB_TIMEOUT_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_ARB_TIMEOUT_RO)
#define AG_MG_REGS_SRIO_RAB_DESC_RDY_TIMEOUT_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_DESC_RDY_TIMEOUT_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_ENAB_GNRL_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_ENAB_GNRL_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_ENAB_APIO_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_ENAB_APIO_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_ENAB_RPIO_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_ENAB_RPIO_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_ENAB_IDME_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_ENAB_IDME_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_ENAB_ODME_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_ENAB_ODME_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_ENAB_MISC_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_ENAB_MISC_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_STAT_GNRL_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_STAT_GNRL_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_STAT_APIO_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_STAT_APIO_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_STAT_RPIO_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_STAT_RPIO_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_STAT_IDME_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_STAT_IDME_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_STAT_ODME_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_STAT_ODME_RO)
#define AG_MG_REGS_SRIO_RAB_INTR_STAT_MISC_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_INTR_STAT_MISC_RO)
#define AG_MG_REGS_SRIO_RAB_RIO_PIO_CTRL_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_RIO_PIO_CTRL_RO)
#define AG_MG_REGS_SRIO_RAB_RIO_PIO_STAT_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_RIO_PIO_STAT_RO)
#define AG_MG_REGS_SRIO_RAB_RIO_AMAP_LUT_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_RIO_AMAP_LUT_RO + 0x4*(n))
#define AG_MG_REGS_SRIO_RAB_RIO_AMAP_IDSL_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_RIO_AMAP_IDSL_RO)
#define AG_MG_REGS_SRIO_RAB_RIO_AMAP_BYPS_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_RIO_AMAP_BYPS_RO)
#define AG_MG_REGS_SRIO_RAB_AXI_PIO_CTRL_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_AXI_PIO_CTRL_RO)
#define AG_MG_REGS_SRIO_RAB_AXI_PIO_STAT_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_AXI_PIO_STAT_RO)
#define AG_MG_REGS_SRIO_RAB_ASLV_STAT_CMD_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_ASLV_STAT_CMD_RO)
#define AG_MG_REGS_SRIO_RAB_ASLV_STAT_ADDR_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_ASLV_STAT_ADDR_RO)
#define AG_MG_REGS_SRIO_RAB_AMST_STAT_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_AMST_STAT_RO)
#define AG_MG_REGS_SRIO_RAB_APIO_AMAP_CTRL_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_APIO_AMAP_CTRL_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_APIO_AMAP_SIZE_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_APIO_AMAP_SIZE_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_APIO_AMAP_ABAR_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_APIO_AMAP_ABAR_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_APIO_AMAP_RBAR_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_APIO_AMAP_RBAR_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_OB_DB_CSR_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_OB_DB_CSR_RO + 0x8*(n))
#define AG_MG_REGS_SRIO_RAB_OB_DB_INFO_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_OB_DB_INFO_RO + 0x8*(n))
#define AG_MG_REGS_SRIO_RAB_OB_IDB_CSR_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_OB_IDB_CSR_RO)
#define AG_MG_REGS_SRIO_RAB_OB_IDB_INFO_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_OB_IDB_INFO_RO)
#define AG_MG_REGS_SRIO_RAB_IB_DB_CSR_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_IB_DB_CSR_RO)
#define AG_MG_REGS_SRIO_RAB_IB_DB_INFO_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_IB_DB_INFO_RO)
#define AG_MG_REGS_SRIO_RAB_OB_DME_CTRL_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_OB_DME_CTRL_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_OB_DME_ADDR_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_OB_DME_ADDR_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_OB_DME_STAT_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_OB_DME_STAT_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_OB_DME_DESC_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_OB_DME_DESC_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_OB_DME_TIDMSK_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_OB_DME_TIDMSK_RO)
#define AG_MG_REGS_SRIO_RAB_IB_DME_CTRL_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_IB_DME_CTRL_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_IB_DME_ADDR_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_IB_DME_ADDR_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_IB_DME_STAT_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_IB_DME_STAT_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_IB_DME_DESC_RA(p, n)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_IB_DME_DESC_RO + 0x10*(n))
#define AG_MG_REGS_SRIO_RAB_LFC_CSR_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_LFC_CSR_RO)
#define AG_MG_REGS_SRIO_RAB_LFC_TIMEOUT_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_LFC_TIMEOUT_RO)
#define AG_MG_REGS_SRIO_RAB_LFC_BLOCKED_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_LFC_BLOCKED_RO)
#define AG_MG_REGS_SRIO_RAB_SRDS_CTRL0_RA(p)	AG_MG_REGS_SRIO_PHYS_REG(p,AG_MG_REGS_RAB_SRDS_CTRL0_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_RAB_PIO_REGS_S
{
	ag_mg_regs_rab_rio_pio_ctrl_u	rab_rio_pio_ctrl ;
	ag_mg_regs_rab_rio_pio_stat_u	rab_rio_pio_stat ;
} ag_mg_regs_rab_rio_pio_t ;

typedef struct AG_MG_REGS_RAB_AXI_PIO_REGS_S
{
	ag_mg_regs_rab_axi_pio_ctrl_u	rab_axi_pio_ctrl ;
	ag_mg_regs_rab_axi_pio_stat_u	rab_axi_pio_stat ;
} ag_mg_regs_rab_axi_pio_t ;

typedef struct AG_MG_REGS_RAB_AMAP_REGS_S
{
	ag_mg_regs_rab_apio_amap_ctrl_u	rab_apio_amap_ctrl ;
	ag_mg_regs_rab_apio_amap_size_u	rab_apio_amap_size ;
	ag_mg_regs_rab_apio_amap_abar_u	rab_apio_amap_abar ;
	ag_mg_regs_rab_apio_amap_rbar_u	rab_apio_amap_rbar ;
} ag_mg_regs_rab_amap_t ;

typedef struct AG_MG_REGS_OB_DOORBELL_S
{
	ag_mg_regs_rab_ob_db_csr_u	rab_ob_db_csr ;
	ag_mg_regs_rab_ob_db_info_u	rab_ob_db_info ;
} ag_mg_regs_ob_doorbell_t ;

typedef struct AG_MG_REGS_RAB_OB_DME_S
{
	ag_mg_regs_rab_ob_dme_ctrl_u	rab_ob_dme_ctrl ;
	ag_mg_regs_rab_ob_dme_addr_u	rab_ob_dme_addr ;
	ag_mg_regs_rab_ob_dme_stat_u	rab_ob_dme_stat ;
	ag_mg_regs_rab_ob_dme_desc_u	rab_ob_dme_desc ;
} ag_mg_regs_rab_ob_dme_t ;

typedef struct AG_MG_REGS_RAB_IB_DME_S
{
	ag_mg_regs_rab_ib_dme_ctrl_u	rab_ib_dme_ctrl ;
	ag_mg_regs_rab_ib_dme_addr_u	rab_ib_dme_addr ;
	ag_mg_regs_rab_ib_dme_stat_u	rab_ib_dme_stat ;
	ag_mg_regs_rab_ib_dme_desc_u	rab_ib_dme_desc ;

} ag_mg_regs_rab_ib_dme_t ;

typedef struct AG_MG_REGS_SRIO_RAB_REGS_S
{
	//beginning of page 0x40 (RAB_regs)
	ag_mg_regs_rab_ver_u			rab_ver ;
	ag_mg_regs_rab_capa_u			rab_capa ;
	ag_mg_regs_rab_ctrl_u			rab_ctrl ;
	ag_mg_regs_rab_stat_u			rab_stat ;
	ag_mg_regs_rab_axi_timeout_u	rab_axi_timeout ;
	ag_mg_regs_rab_dme_timeout_u	rab_dme_timeout ;
	ag_mg_regs_rab_rst_ctrl_u		rab_rst_ctrl ;
	ag_mg_regs_rab_coop_lock_u		rab_coop_lock ;
	ag_mg_regs_rab_stat_esel_u		rab_stat_esel ;
	ag_mg_regs_rab_stat_stat_u		rab_stat_stat ;
	ag_mg_regs_rab_ib_pw_csr_u		rab_ib_pw_csr ;
	ag_mg_regs_rab_ib_pw_data_u		rab_ib_pw_data ;
	ag_mg_regs_rab_apb_csr_u		rab_apb_csr ;
	ag_mg_regs_rab_arb_timeout_u	rab_arb_timeout ;
	ag_mg_regs_rab_desc_rdy_timeout_u	rab_desc_rdy_timeout ;
	ag_mg_regs_register				RESERVED_0 ;
	ag_mg_regs_rab_intr_enab_gnrl_u	rab_intr_enab_gnrl ;
	ag_mg_regs_rab_intr_enab_apio_u	rab_intr_enab_apio ;
	ag_mg_regs_rab_intr_enab_rpio_u	rab_intr_enab_rpio ;
	ag_mg_regs_register				RESERVED_1[2] ;
	ag_mg_regs_rab_intr_enab_idme_u	rab_intr_enab_idme ;
	ag_mg_regs_rab_intr_enab_odme_u	rab_intr_enab_odme ;
	ag_mg_regs_rab_intr_enab_misc_u	rab_intr_enab_misc ;
	ag_mg_regs_rab_intr_stat_gnrl_u	rab_intr_stat_gnrl ;
	ag_mg_regs_rab_intr_stat_apio_u	rab_intr_stat_apio ;
	ag_mg_regs_rab_intr_stat_rpio_u	rab_intr_stat_rpio ;
	ag_mg_regs_register				RESERVED_2[2] ;
	ag_mg_regs_rab_intr_stat_idme_u	rab_intr_stat_idme ;
	ag_mg_regs_rab_intr_stat_odme_u	rab_intr_stat_odme ;
	ag_mg_regs_rab_intr_stat_misc_u	rab_intr_stat_misc ;
	ag_mg_regs_rab_rio_pio_t		rab_rio_pio ;
	ag_mg_regs_register				RESERVED_3[30] ;
	ag_mg_regs_rab_rio_amap_lut_u	rab_rio_amap_lut[16] ;
	ag_mg_regs_rab_rio_amap_idsl_u	rab_rio_amap_idsl ;
	ag_mg_regs_rab_rio_amap_byps_u	rab_rio_amap_byps ;
	ag_mg_regs_register				RESERVED_4[14] ;
	ag_mg_regs_rab_axi_pio_t 		rab_axi_pio ;
	ag_mg_regs_register				RESERVED_5[14] ;
	ag_mg_regs_rab_aslv_stat_cmd_u	rab_aslv_stat_cmd ;
	ag_mg_regs_rab_aslv_stat_addr_u	rab_aslv_stat_addr ;
	ag_mg_regs_register				RESERVED_6[6] ;
	ag_mg_regs_rab_amst_stat_u		rab_amst_stat ;
	ag_mg_regs_register				RESERVED_7[7] ;
	ag_mg_regs_rab_amap_t 			rab_amap[16] ;
	ag_mg_regs_register				RESERVED_8[64] ;
	ag_mg_regs_ob_doorbell_t 		ob_doorbell[8];
	ag_mg_regs_register				RESERVED_9[14] ;
	ag_mg_regs_rab_ob_idb_csr_u		rab_ob_idb_csr ;
	ag_mg_regs_rab_ob_idb_info_u	rab_ob_idb_info ;
	ag_mg_regs_rab_ib_db_csr_u		rab_ib_db_csr ;
	ag_mg_regs_rab_ib_db_info_u		rab_ib_db_info ;
	ag_mg_regs_register				RESERVED_10[30] ;
	ag_mg_regs_rab_ob_dme_t			rab_ob_dme[6];
	ag_mg_regs_register				RESERVED_11[36];
	ag_mg_regs_rab_ob_dme_tidmsk_u	rab_ob_dme_tidmsk;
	ag_mg_regs_register				RESERVED_12[3] ;
	ag_mg_regs_rab_ib_dme_t 		rab_ib_dme[32] ;
	//end of page 0x40
	//beginning of page 0x41
	ag_mg_regs_register				RESERVED_13[72] ;
	ag_mg_regs_rab_lfc_csr_u		rab_lfc_csr[8] ;
	ag_mg_regs_register				RESERVED_14[8] ;
	ag_mg_regs_rab_lfc_timeout_u	rab_lfc_timeout ;
	ag_mg_regs_rab_lfc_blocked_u	rab_lfc_blocked ;
	ag_mg_regs_register				RESERVED_15[6] ;
	ag_mg_regs_rab_srds_ctrl0_u		rab_srds_ctrl0 ;
	//end of page 0x41
} ag_mg_regs_srio_rab_reg_s ;

typedef struct AG_MG_REGS_SRIO_PHYS_REGS_S
{
	//beginning of page 0x40 (RAB_regs)
	ag_mg_regs_rab_ver_u			rab_ver ;
	ag_mg_regs_rab_capa_u			rab_capa ;
	ag_mg_regs_rab_ctrl_u			rab_ctrl ;
	ag_mg_regs_rab_stat_u			rab_stat ;
	ag_mg_regs_rab_axi_timeout_u	rab_axi_timeout ;
	ag_mg_regs_rab_dme_timeout_u	rab_dme_timeout ;
	ag_mg_regs_rab_rst_ctrl_u		rab_rst_ctrl ;
	ag_mg_regs_rab_coop_lock_u		rab_coop_lock ;
	ag_mg_regs_rab_stat_esel_u		rab_stat_esel ;
	ag_mg_regs_rab_stat_stat_u		rab_stat_stat ;
	ag_mg_regs_rab_ib_pw_csr_u		rab_ib_pw_csr ;
	ag_mg_regs_rab_ib_pw_data_u		rab_ib_pw_data ;
	ag_mg_regs_rab_apb_csr_u		rab_apb_csr ;
	ag_mg_regs_rab_arb_timeout_u	rab_arb_timeout ;
	ag_mg_regs_rab_desc_rdy_timeout_u	rab_desc_rdy_timeout ;
	ag_mg_regs_register				RESERVED_0 ;
	ag_mg_regs_rab_intr_enab_gnrl_u	rab_intr_enab_gnrl ;
	ag_mg_regs_rab_intr_enab_apio_u	rab_intr_enab_apio ;
	ag_mg_regs_rab_intr_enab_rpio_u	rab_intr_enab_rpio ;
	ag_mg_regs_register				RESERVED_1[2] ;
	ag_mg_regs_rab_intr_enab_idme_u	rab_intr_enab_idme ;
	ag_mg_regs_rab_intr_enab_odme_u	rab_intr_enab_odme ;
	ag_mg_regs_rab_intr_enab_misc_u	rab_intr_enab_misc ;
	ag_mg_regs_rab_intr_stat_gnrl_u	rab_intr_stat_gnrl ;
	ag_mg_regs_rab_intr_stat_apio_u	rab_intr_stat_apio ;
	ag_mg_regs_rab_intr_stat_rpio_u	rab_intr_stat_rpio ;
	ag_mg_regs_register				RESERVED_2[2] ;
	ag_mg_regs_rab_intr_stat_idme_u	rab_intr_stat_idme ;
	ag_mg_regs_rab_intr_stat_odme_u	rab_intr_stat_odme ;
	ag_mg_regs_rab_intr_stat_misc_u	rab_intr_stat_misc ;
	ag_mg_regs_rab_rio_pio_t		rab_rio_pio ;
	ag_mg_regs_register				RESERVED_3[30] ;
	ag_mg_regs_rab_rio_amap_lut_u	rab_rio_amap_lut[16] ;
	ag_mg_regs_rab_rio_amap_idsl_u	rab_rio_amap_idsl ;
	ag_mg_regs_rab_rio_amap_byps_u	rab_rio_amap_byps ;
	ag_mg_regs_register				RESERVED_4[14] ;
	ag_mg_regs_rab_axi_pio_t 		rab_axi_pio ;
	ag_mg_regs_register				RESERVED_5[14] ;
	ag_mg_regs_rab_aslv_stat_cmd_u	rab_aslv_stat_cmd ;
	ag_mg_regs_rab_aslv_stat_addr_u	rab_aslv_stat_addr ;
	ag_mg_regs_register				RESERVED_6[6] ;
	ag_mg_regs_rab_amst_stat_u		rab_amst_stat ;
	ag_mg_regs_register				RESERVED_7[7] ;
	ag_mg_regs_rab_amap_t 			rab_amap[16] ;
	ag_mg_regs_register				RESERVED_8[64] ;
	ag_mg_regs_ob_doorbell_t 		ob_doorbell[8];
	ag_mg_regs_register				RESERVED_9[14] ;
	ag_mg_regs_rab_ob_idb_csr_u		rab_ob_idb_csr ;
	ag_mg_regs_rab_ob_idb_info_u	rab_ob_idb_info ;
	ag_mg_regs_rab_ib_db_csr_u		rab_ib_db_csr ;
	ag_mg_regs_rab_ib_db_info_u		rab_ib_db_info ;
	ag_mg_regs_register				RESERVED_10[30] ;
	ag_mg_regs_rab_ob_dme_t			rab_ob_dme[6];
	ag_mg_regs_register				RESERVED_11[36];
	ag_mg_regs_rab_ob_dme_tidmsk_u	rab_ob_dme_tidmsk;
	ag_mg_regs_register				RESERVED_12[3] ;
	ag_mg_regs_rab_ib_dme_t 		rab_ib_dme[32] ;
	//end of page 0x40
	ag_mg_regs_register				paged_area[512];
} ag_mg_regs_srio_phys_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_srio_rab_reg_s *srio_regs =
*       (volatile ag_mg_regs_srio_rab_reg_s *)AG_MG_REGS_SRIO_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_srio_rab.h,v $
Revision 1.2  2017/07/28 07:58:35  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:28  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

