/* $Id: ag_mg_regs_ssp.h,v 1.2 2017/07/28 07:58:35 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_ssp.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_ssp.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_ssp.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of LSI Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * The SP2704 DSP provides a synchronous serial port (SSP) for performing
 * serial-to-parallel conversion on data received from a peripheral device.
 * The SSP is configurable as a master or slave interface for synchronous
 * serial communication with peripheral devices that support Freescale™ SPI
 * format. The SSP is available as an option for boot loading the device, in
 * cases where one of the ARM processors functions as the system host. It also
 * functions as a general-purpose serial link.
 *
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *
 * SSPCPSR
 * SSPCR0
 * SSPCR1
 * SSPDR
 * SSPICR
 * SSPIMSC
 * SSPMIS
 * SSPRIS
 * SSPSR
 * SSPDMACR
 *
 * Prefix naming conventions :
 *   AG_MG_REGS_XXX_RA : register/memory physical address
 *   AG_MG_REGS_XXX_RO : register/memory address offset
 *   AG_MG_REGS_XXX_RM : register mask
 *   AG_MG_REGS_XXX_BO : bit/field offset from LSB
 *   AG_MG_REGS_XXX_BM : bit/field mask
 *   AG_MG_REGS_XXX_U  : bitfields in C union typedef
 *   AG_MG_REGS_XXX_S  : registers in C struct typedef
 *   AG_MG_REGS_XX_RPT : number of identical registers in array
 *   AG_MG_REGS_XX_IVL : interval between registers in array
 *
 * NOTE: user may redefine ag_mg_regs_register
 *       in ag_mg_regs_regops.h if necessary
 * NOTE: access mode of individual bit fields matches that
 *       of containing register unless indicated otherwise
 *
 * Generated by HSI Designer release 2.3.5.
 */

#ifndef AG_MG_REGS_SSP_REGISTERS_H
#define AG_MG_REGS_SSP_REGISTERS_H

#include "ag_mg_regs_regops.h"

/*
 * SSPCR0 (SSP Control Register 0)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_SSPCR0_RO                        0x00000000
#define AG_MG_REGS_SSPCR0_RM                        0x0000FFFF

#define AG_MG_REGS_SSPCR0_DSS_BO                    0
#define AG_MG_REGS_SSPCR0_DSS_BM                    0x0000000F

#define AG_MG_REGS_SSPCR0_FRF_BO                    4
#define AG_MG_REGS_SSPCR0_FRF_BM                    0x00000030

#define AG_MG_REGS_SSPCR0_SPO_BO                    6
#define AG_MG_REGS_SSPCR0_SPO_BM                    0x00000040

#define AG_MG_REGS_SSPCR0_SPH_BO                    7
#define AG_MG_REGS_SSPCR0_SPH_BM                    0x00000080

#define AG_MG_REGS_SSPCR0_SCR_BO                    8
#define AG_MG_REGS_SSPCR0_SCR_BM                    0x0000FF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SSPCR0_U
{
    struct
    {
        ag_mg_regs_register
            dss : 4,
            frf : 2,
            spo : 1,
            sph : 1,
            scr : 8,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_sspcr0_u;
#endif


/*
 * SSPCR1 (SSP Control Register 1)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_SSPCR1_RO                        0x00000004
#define AG_MG_REGS_SSPCR1_RM                        0x0000000F

#define AG_MG_REGS_SSPCR1_LBM_BO                    0
#define AG_MG_REGS_SSPCR1_LBM_BM                    0x00000001

#define AG_MG_REGS_SSPCR1_SSE_BO                    1
#define AG_MG_REGS_SSPCR1_SSE_BM                    0x00000002

#define AG_MG_REGS_SSPCR1_MS_BO                     2
#define AG_MG_REGS_SSPCR1_MS_BM                     0x00000004

#define AG_MG_REGS_SSPCR1_SOD_BO                    3
#define AG_MG_REGS_SSPCR1_SOD_BM                    0x00000008

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SSPCR1_U
{
    struct
    {
        ag_mg_regs_register
            lbm : 1,
            sse : 1,
            ms : 1,
            sod : 1,
            fill0 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_sspcr1_u;
#endif


/*
 * SSPDR (SSP Receive-Transmit FIFO Data Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_SSPDR_RO                         0x00000008
#define AG_MG_REGS_SSPDR_RM                         0x0000FFFF

#define AG_MG_REGS_SSPDR_DATA_BO                    0
#define AG_MG_REGS_SSPDR_DATA_BM                    0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SSPDR_U
{
    struct
    {
        ag_mg_regs_register
            data : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_sspdr_u;
#endif


/*
 * SSPSR (SSP Status Register)
 * Initialization value: 0x00000003  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_SSPSR_RO                         0x0000000C
#define AG_MG_REGS_SSPSR_RM                         0x0000001F

#define AG_MG_REGS_SSPSR_TFE_BO                     0
#define AG_MG_REGS_SSPSR_TFE_BM                     0x00000001

#define AG_MG_REGS_SSPSR_TNF_BO                     1
#define AG_MG_REGS_SSPSR_TNF_BM                     0x00000002

#define AG_MG_REGS_SSPSR_RNE_BO                     2
#define AG_MG_REGS_SSPSR_RNE_BM                     0x00000004

#define AG_MG_REGS_SSPSR_RFF_BO                     3
#define AG_MG_REGS_SSPSR_RFF_BM                     0x00000008

#define AG_MG_REGS_SSPSR_BSY_BO                     4
#define AG_MG_REGS_SSPSR_BSY_BM                     0x00000010

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SSPSR_U
{
    struct
    {
        ag_mg_regs_register
            tfe : 1,
            tnf : 1,
            rne : 1,
            rff : 1,
            bsy : 1,
            fill0 : 27;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_sspsr_u;
#endif


/*
 * SSPCPSR (SSP Clock Prescale Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_SSPCPSR_RO                       0x00000010
#define AG_MG_REGS_SSPCPSR_RM                       0x000000FF

#define AG_MG_REGS_SSPCPSR_CPSDVSR_BO               0
#define AG_MG_REGS_SSPCPSR_CPSDVSR_BM               0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SSPCPSR_U
{
    struct
    {
        ag_mg_regs_register
            cpsdvsr : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_sspcpsr_u;
#endif


/*
 * SSPIMSC (SSP Interrupt Mask Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_SSPIMSC_RO                       0x00000014
#define AG_MG_REGS_SSPIMSC_RM                       0x0000000F

#define AG_MG_REGS_SSPIMSC_RORIM_BO                 0
#define AG_MG_REGS_SSPIMSC_RORIM_BM                 0x00000001

#define AG_MG_REGS_SSPIMSC_RTIM_BO                  1
#define AG_MG_REGS_SSPIMSC_RTIM_BM                  0x00000002

#define AG_MG_REGS_SSPIMSC_RXIM_BO                  2
#define AG_MG_REGS_SSPIMSC_RXIM_BM                  0x00000004

#define AG_MG_REGS_SSPIMSC_TXIM_BO                  3
#define AG_MG_REGS_SSPIMSC_TXIM_BM                  0x00000008

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SSPIMSC_U
{
    struct
    {
        ag_mg_regs_register
            rorim : 1,
            rtim : 1,
            rxim : 1,
            txim : 1,
            fill0 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_sspimsc_u;
#endif


/*
 * SSPRIS (SSP Raw Interrupt Status Register)
 * Initialization value: 0x00000008  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_SSPRIS_RO                        0x00000018
#define AG_MG_REGS_SSPRIS_RM                        0x0000000F

#define AG_MG_REGS_SSPRIS_RORRIS_BO                 0
#define AG_MG_REGS_SSPRIS_RORRIS_BM                 0x00000001

#define AG_MG_REGS_SSPRIS_RTRIS_BO                  1
#define AG_MG_REGS_SSPRIS_RTRIS_BM                  0x00000002

#define AG_MG_REGS_SSPRIS_RXRIS_BO                  2
#define AG_MG_REGS_SSPRIS_RXRIS_BM                  0x00000004

#define AG_MG_REGS_SSPRIS_TXRIS_BO                  3
#define AG_MG_REGS_SSPRIS_TXRIS_BM                  0x00000008

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SSPRIS_U
{
    struct
    {
        ag_mg_regs_register
            rorris : 1,
            rtris : 1,
            rxris : 1,
            txris : 1,
            fill0 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_sspris_u;
#endif


/*
 * SSPMIS (SSP Masked Interrupt Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_SSPMIS_RO                        0x0000001C
#define AG_MG_REGS_SSPMIS_RM                        0x0000000F

#define AG_MG_REGS_SSPMIS_RORMIS_BO                 0
#define AG_MG_REGS_SSPMIS_RORMIS_BM                 0x00000001

#define AG_MG_REGS_SSPMIS_RTMIS_BO                  1
#define AG_MG_REGS_SSPMIS_RTMIS_BM                  0x00000002

#define AG_MG_REGS_SSPMIS_RXMIS_BO                  2
#define AG_MG_REGS_SSPMIS_RXMIS_BM                  0x00000004

#define AG_MG_REGS_SSPMIS_TXMIS_BO                  3
#define AG_MG_REGS_SSPMIS_TXMIS_BM                  0x00000008

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SSPMIS_U
{
    struct
    {
        ag_mg_regs_register
            rormis : 1,
            rtmis : 1,
            rxmis : 1,
            txmis : 1,
            fill0 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_sspmis_u;
#endif


/*
 * SSPICR (SSP Interrupt Clear Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_SSPICR_RO                        0x00000020
#define AG_MG_REGS_SSPICR_RM                        0x00000003

#define AG_MG_REGS_SSPICR_RORIC_BO                  0
#define AG_MG_REGS_SSPICR_RORIC_BM                  0x00000001

#define AG_MG_REGS_SSPICR_RTIC_BO                   1
#define AG_MG_REGS_SSPICR_RTIC_BM                   0x00000002

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SSPICR_U
{
    struct
    {
        ag_mg_regs_register
            roric : 1,
            rtic : 1,
            fill0 : 30;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_sspicr_u;
#endif

/*
 * SSPDMACR (SSP DMA Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_SSPDMACR_RO                        0x00000024
#define AG_MG_REGS_SSPDMACR_RM                        0x00000003

#define AG_MG_REGS_SSPDMACR_RXDMAE_BO                  0
#define AG_MG_REGS_SSPDMACR_RXDMAE_BM                  0x00000001

#define AG_MG_REGS_SSPDMACR_TXDMAE_BO                   1
#define AG_MG_REGS_SSPDMACR_TXDMAE_BM                   0x00000002

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SSPDMACR_U
{
    struct
    {
        ag_mg_regs_register
            rxdmae : 1,
            txdmae : 1,
            fill0 : 30;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_sspdmacr_u;
#endif

/*
 * Physical register addresses (for ARM accessing SSP)
 */
#ifdef AG_MG_REGS_BUILT_FOR_DSS
#define AG_MG_REGS_SSP_BASE               0xC304F000
#else
#define AG_MG_REGS_SSP_BASE               0x3004F000
#endif


#define AG_MG_REGS_SSP_REG(ro)            (AG_MG_REGS_SSP_BASE+(ro))

#define AG_MG_REGS_SSP_SSPCR0_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPCR0_RO)
#define AG_MG_REGS_SSP_SSPCR1_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPCR1_RO)
#define AG_MG_REGS_SSP_SSPDR_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPDR_RO)
#define AG_MG_REGS_SSP_SSPSR_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPSR_RO)
#define AG_MG_REGS_SSP_SSPCPSR_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPCPSR_RO)
#define AG_MG_REGS_SSP_SSPIMSC_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPIMSC_RO)
#define AG_MG_REGS_SSP_SSPRIS_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPRIS_RO)
#define AG_MG_REGS_SSP_SSPMIS_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPMIS_RO)
#define AG_MG_REGS_SSP_SSPICR_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPICR_RO)
#define AG_MG_REGS_SSP_SSPDMACR_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPDMACR_RO)
#define AG_MG_REGS_SSP_SSPPERIPHID0_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPPERIPHID0_RO)
#define AG_MG_REGS_SSP_SSPPERIPHID1_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPPERIPHID1_RO)
#define AG_MG_REGS_SSP_SSPPERIPHID2_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPPERIPHID2_RO)
#define AG_MG_REGS_SSP_SSPPERIPHID3_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPPERIPHID3_RO)
#define AG_MG_REGS_SSP_SSPPCELLID0_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPPCELLID0_RO)
#define AG_MG_REGS_SSP_SSPPCELLID1_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPPCELLID1_RO)
#define AG_MG_REGS_SSP_SSPPCELLID2_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPPCELLID2_RO)
#define AG_MG_REGS_SSP_SSPPCELLID3_RA	AG_MG_REGS_SSP_REG(AG_MG_REGS_SSPPCELLID3_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_SSP_REGS_S
{
	ag_mg_regs_sspcr0_u	sspcr0;
	ag_mg_regs_sspcr1_u	sspcr1;
	ag_mg_regs_sspdr_u	sspdr;
	ag_mg_regs_sspsr_u	sspsr;
	ag_mg_regs_sspcpsr_u	sspcpsr;
	ag_mg_regs_sspimsc_u	sspimsc;
	ag_mg_regs_sspris_u	sspris;
	ag_mg_regs_sspmis_u	sspmis;
	ag_mg_regs_sspicr_u	sspicr;
	ag_mg_regs_sspdmacr_u	sspdmacr ;
} ag_mg_regs_ssp_reg_s ;

/*
 * Recommended C syntax for typical usage :
 *   volatile ag_mg_regs_ssp_reg_s *ssp_regs =
 *       (volatile ag_mg_regs_ssp_reg_s *)AG_MG_REGS_SSP_BASE;
 */
#endif

#endif

/******** History ********
$Log: ag_mg_regs_ssp.h,v $
Revision 1.2  2017/07/28 07:58:35  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:28  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

