/* $Id: ag_mg_regs_cpf.h,v 1.2 2017/07/28 07:58:33 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_cpf.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_cpf.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
* ag_mg_regs_dss_cpf.h
*
* Copyright (c) 2009 LSI Inc.  All Rights Reserved
*
* This is unpublished proprietary information of LSI Inc.
* This copyright notice does not evidence publication.
*
* The use of the software, documentation, methodologies, and other information
* contained herein is governed solely by the associated license agreements.
* Any inconsistent use shall be deemed to be a misappropriation of the
* intellectual property of LSI Inc. and treated accordingly.
*
* This file defines DSP Subsystem (DSS) Cache and System Profiler Unit
* (CPF) registers.
*
* Register addresses defined herein are for
*  code running on the DSS accessing its own CPF.
*
* See "Physical register addresses" below for macros
* used to generate addresses for specific registers.
*
* Registers defined in this file :
 *  CPF_CNT0
 *  CPF_CNT1
 *  CPF_CNT2
 *  CPF_CNT3
 *  CPF_CNT4
 *  CPF_CNT5
 *  CPF_CNT6
 *  CPF_CNT7
 *  CPF_CNT_CFG0
 *  CPF_CNT_CFG1
 *  CPF_CNT_CFG2
 *  CPF_CNT_CFG3
 *  CPF_CNT_CFG4
 *  CPF_CNT_CFG5
 *  CPF_CNT_CFG6
 *  CPF_CNT_CFG7
 *  CPF_CNT_CLR
 *  CPF_CNT_EN
 *  CPF_CNT_OVF
 *  CPF_INT_EN
 *  CPF_GLB_CFG
 *  CPF_EGRP
*
* Prefix naming conventions :
*   AG_MG_REGS_XXX_RA : register/memory physical address
*   AG_MG_REGS_XXX_RO : register/memory address offset
*   AG_MG_REGS_XXX_RM : register mask
*   AG_MG_REGS_XXX_BO : bit/field offset from LSB
*   AG_MG_REGS_XXX_BM : bit/field mask
*   AG_MG_REGS_XXX_U  : bitfields in C union typedef
*   AG_MG_REGS_XXX_S  : registers in C struct typedef
*   AG_MG_REGS_XX_RPT : number of identical registers in array
*   AG_MG_REGS_XX_IVL : interval between registers in array
*
* NOTE: user may redefine ag_mg_regs_register
*       in ag_mg_regs_regops.h if necessary
* NOTE: access mode of individual bit fields matches that
*       of containing register unless indicated otherwise
*/

#ifndef AG_MG_REGS_DSS_CPF_REGISTERS_H
#define AG_MG_REGS_DSS_CPF_REGISTERS_H

#include "ag_mg_regs_regops.h"


/* 
 * Generated by HSI Designer release 2.3.5.
 */





/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT0_RO                 0x00000000
#define AG_MG_REGS_CPF_CNT0_RM                 0xFFFFFFFF

#define AG_MG_REGS_CPF_CNT0_CNT_BO             0
#define AG_MG_REGS_CPF_CNT0_CNT_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT0_U
{
    struct
    {
        ag_mg_regs_register
            cnt;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt0_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT1_RO                 0x00000004
#define AG_MG_REGS_CPF_CNT1_RM                 0xFFFFFFFF

#define AG_MG_REGS_CPF_CNT1_CNT_BO             0
#define AG_MG_REGS_CPF_CNT1_CNT_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT1_U
{
    struct
    {
        ag_mg_regs_register
            cnt;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt1_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT2_RO                 0x00000008
#define AG_MG_REGS_CPF_CNT2_RM                 0xFFFFFFFF

#define AG_MG_REGS_CPF_CNT2_CNT_BO             0
#define AG_MG_REGS_CPF_CNT2_CNT_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT2_U
{
    struct
    {
        ag_mg_regs_register
            cnt;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt2_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT3_RO                 0x0000000C
#define AG_MG_REGS_CPF_CNT3_RM                 0xFFFFFFFF

#define AG_MG_REGS_CPF_CNT3_CNT_BO             0
#define AG_MG_REGS_CPF_CNT3_CNT_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT3_U
{
    struct
    {
        ag_mg_regs_register
            cnt;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt3_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT4_RO                 0x00000010
#define AG_MG_REGS_CPF_CNT4_RM                 0xFFFFFFFF

#define AG_MG_REGS_CPF_CNT4_CNT_BO             0
#define AG_MG_REGS_CPF_CNT4_CNT_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT4_U
{
    struct
    {
        ag_mg_regs_register
            cnt;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt4_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT5_RO                 0x00000014
#define AG_MG_REGS_CPF_CNT5_RM                 0xFFFFFFFF

#define AG_MG_REGS_CPF_CNT5_CNT_BO             0
#define AG_MG_REGS_CPF_CNT5_CNT_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT5_U
{
    struct
    {
        ag_mg_regs_register
            cnt;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt5_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT6_RO                 0x00000018
#define AG_MG_REGS_CPF_CNT6_RM                 0xFFFFFFFF

#define AG_MG_REGS_CPF_CNT6_CNT_BO             0
#define AG_MG_REGS_CPF_CNT6_CNT_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT6_U
{
    struct
    {
        ag_mg_regs_register
            cnt;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt6_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT7_RO                 0x0000001C
#define AG_MG_REGS_CPF_CNT7_RM                 0xFFFFFFFF

#define AG_MG_REGS_CPF_CNT7_CNT_BO             0
#define AG_MG_REGS_CPF_CNT7_CNT_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT7_U
{
    struct
    {
        ag_mg_regs_register
            cnt;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt7_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT_CFG0_RO             0x00000040
#define AG_MG_REGS_CPF_CNT_CFG0_RM             0x0000003F

#define AG_MG_REGS_CPF_CNT_CFG0_EVNT_BO        0
#define AG_MG_REGS_CPF_CNT_CFG0_EVNT_BM        0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT_CFG0_U
{
    struct
    {
        ag_mg_regs_register
            evnt : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt_cfg0_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT_CFG1_RO             0x00000044
#define AG_MG_REGS_CPF_CNT_CFG1_RM             0x0000003F

#define AG_MG_REGS_CPF_CNT_CFG1_EVNT_BO        0
#define AG_MG_REGS_CPF_CNT_CFG1_EVNT_BM        0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT_CFG1_U
{
    struct
    {
        ag_mg_regs_register
            evnt : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt_cfg1_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT_CFG2_RO             0x00000048
#define AG_MG_REGS_CPF_CNT_CFG2_RM             0x0000003F

#define AG_MG_REGS_CPF_CNT_CFG2_EVNT_BO        0
#define AG_MG_REGS_CPF_CNT_CFG2_EVNT_BM        0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT_CFG2_U
{
    struct
    {
        ag_mg_regs_register
            evnt : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt_cfg2_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT_CFG3_RO             0x0000004C
#define AG_MG_REGS_CPF_CNT_CFG3_RM             0x0000003F

#define AG_MG_REGS_CPF_CNT_CFG3_EVNT_BO        0
#define AG_MG_REGS_CPF_CNT_CFG3_EVNT_BM        0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT_CFG3_U
{
    struct
    {
        ag_mg_regs_register
            evnt : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt_cfg3_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT_CFG4_RO             0x00000050
#define AG_MG_REGS_CPF_CNT_CFG4_RM             0x0000003F

#define AG_MG_REGS_CPF_CNT_CFG4_EVNT_BO        0
#define AG_MG_REGS_CPF_CNT_CFG4_EVNT_BM        0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT_CFG4_U
{
    struct
    {
        ag_mg_regs_register
            evnt : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt_cfg4_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT_CFG5_RO             0x00000054
#define AG_MG_REGS_CPF_CNT_CFG5_RM             0x0000003F

#define AG_MG_REGS_CPF_CNT_CFG5_EVNT_BO        0
#define AG_MG_REGS_CPF_CNT_CFG5_EVNT_BM        0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT_CFG5_U
{
    struct
    {
        ag_mg_regs_register
            evnt : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt_cfg5_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT_CFG6_RO             0x00000058
#define AG_MG_REGS_CPF_CNT_CFG6_RM             0x0000003F

#define AG_MG_REGS_CPF_CNT_CFG6_EVNT_BO        0
#define AG_MG_REGS_CPF_CNT_CFG6_EVNT_BM        0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT_CFG6_U
{
    struct
    {
        ag_mg_regs_register
            evnt : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt_cfg6_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT_CFG7_RO             0x0000005C
#define AG_MG_REGS_CPF_CNT_CFG7_RM             0x0000003F

#define AG_MG_REGS_CPF_CNT_CFG7_EVNT_BO        0
#define AG_MG_REGS_CPF_CNT_CFG7_EVNT_BM        0x0000003F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT_CFG7_U
{
    struct
    {
        ag_mg_regs_register
            evnt : 6,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt_cfg7_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT_CLR_RO              0x00000080
#define AG_MG_REGS_CPF_CNT_CLR_RM              0x00FF00FF

#define AG_MG_REGS_CPF_CNT_CLR_CLR0_BO         0
#define AG_MG_REGS_CPF_CNT_CLR_CLR0_BM         0x00000001

#define AG_MG_REGS_CPF_CNT_CLR_CLR1_BO         1
#define AG_MG_REGS_CPF_CNT_CLR_CLR1_BM         0x00000002

#define AG_MG_REGS_CPF_CNT_CLR_CLR2_BO         2
#define AG_MG_REGS_CPF_CNT_CLR_CLR2_BM         0x00000004

#define AG_MG_REGS_CPF_CNT_CLR_CLR3_BO         3
#define AG_MG_REGS_CPF_CNT_CLR_CLR3_BM         0x00000008

#define AG_MG_REGS_CPF_CNT_CLR_CLR4_BO         4
#define AG_MG_REGS_CPF_CNT_CLR_CLR4_BM         0x00000010

#define AG_MG_REGS_CPF_CNT_CLR_CLR5_BO         5
#define AG_MG_REGS_CPF_CNT_CLR_CLR5_BM         0x00000020

#define AG_MG_REGS_CPF_CNT_CLR_CLR6_BO         6
#define AG_MG_REGS_CPF_CNT_CLR_CLR6_BM         0x00000040

#define AG_MG_REGS_CPF_CNT_CLR_CLR7_BO         7
#define AG_MG_REGS_CPF_CNT_CLR_CLR7_BM         0x00000080

#define AG_MG_REGS_CPF_CNT_CLR_CLR0_WE_BO      16
#define AG_MG_REGS_CPF_CNT_CLR_CLR0_WE_BM      0x00010000

#define AG_MG_REGS_CPF_CNT_CLR_CLR1_WE_BO      17
#define AG_MG_REGS_CPF_CNT_CLR_CLR1_WE_BM      0x00020000

#define AG_MG_REGS_CPF_CNT_CLR_CLR2_WE_BO      18
#define AG_MG_REGS_CPF_CNT_CLR_CLR2_WE_BM      0x00040000

#define AG_MG_REGS_CPF_CNT_CLR_CLR3_WE_BO      19
#define AG_MG_REGS_CPF_CNT_CLR_CLR3_WE_BM      0x00080000

#define AG_MG_REGS_CPF_CNT_CLR_CLR4_WE_BO      20
#define AG_MG_REGS_CPF_CNT_CLR_CLR4_WE_BM      0x00100000

#define AG_MG_REGS_CPF_CNT_CLR_CLR5_WE_BO      21
#define AG_MG_REGS_CPF_CNT_CLR_CLR5_WE_BM      0x00200000

#define AG_MG_REGS_CPF_CNT_CLR_CLR6_WE_BO      22
#define AG_MG_REGS_CPF_CNT_CLR_CLR6_WE_BM      0x00400000

#define AG_MG_REGS_CPF_CNT_CLR_CLR7_WE_BO      23
#define AG_MG_REGS_CPF_CNT_CLR_CLR7_WE_BM      0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT_CLR_U
{
    struct
    {
        ag_mg_regs_register
            clr0 : 1,
            clr1 : 1,
            clr2 : 1,
            clr3 : 1,
            clr4 : 1,
            clr5 : 1,
            clr6 : 1,
            clr7 : 1,
            fill1 : 8,
            clr0_we : 1,
            clr1_we : 1,
            clr2_we : 1,
            clr3_we : 1,
            clr4_we : 1,
            clr5_we : 1,
            clr6_we : 1,
            clr7_we : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt_clr_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT_EN_RO               0x00000084
#define AG_MG_REGS_CPF_CNT_EN_RM               0x00FF00FF

#define AG_MG_REGS_CPF_CNT_EN_EN0_BO           0
#define AG_MG_REGS_CPF_CNT_EN_EN0_BM           0x00000001

#define AG_MG_REGS_CPF_CNT_EN_EN1_BO           1
#define AG_MG_REGS_CPF_CNT_EN_EN1_BM           0x00000002

#define AG_MG_REGS_CPF_CNT_EN_EN2_BO           2
#define AG_MG_REGS_CPF_CNT_EN_EN2_BM           0x00000004

#define AG_MG_REGS_CPF_CNT_EN_EN3_BO           3
#define AG_MG_REGS_CPF_CNT_EN_EN3_BM           0x00000008

#define AG_MG_REGS_CPF_CNT_EN_EN4_BO           4
#define AG_MG_REGS_CPF_CNT_EN_EN4_BM           0x00000010

#define AG_MG_REGS_CPF_CNT_EN_EN5_BO           5
#define AG_MG_REGS_CPF_CNT_EN_EN5_BM           0x00000020

#define AG_MG_REGS_CPF_CNT_EN_EN6_BO           6
#define AG_MG_REGS_CPF_CNT_EN_EN6_BM           0x00000040

#define AG_MG_REGS_CPF_CNT_EN_EN7_BO           7
#define AG_MG_REGS_CPF_CNT_EN_EN7_BM           0x00000080

#define AG_MG_REGS_CPF_CNT_EN_EN0_WE_BO        16
#define AG_MG_REGS_CPF_CNT_EN_EN0_WE_BM        0x00010000

#define AG_MG_REGS_CPF_CNT_EN_EN1_WE_BO        17
#define AG_MG_REGS_CPF_CNT_EN_EN1_WE_BM        0x00020000

#define AG_MG_REGS_CPF_CNT_EN_EN2_WE_BO        18
#define AG_MG_REGS_CPF_CNT_EN_EN2_WE_BM        0x00040000

#define AG_MG_REGS_CPF_CNT_EN_EN3_WE_BO        19
#define AG_MG_REGS_CPF_CNT_EN_EN3_WE_BM        0x00080000

#define AG_MG_REGS_CPF_CNT_EN_EN4_WE_BO        20
#define AG_MG_REGS_CPF_CNT_EN_EN4_WE_BM        0x00100000

#define AG_MG_REGS_CPF_CNT_EN_EN5_WE_BO        21
#define AG_MG_REGS_CPF_CNT_EN_EN5_WE_BM        0x00200000

#define AG_MG_REGS_CPF_CNT_EN_EN6_WE_BO        22
#define AG_MG_REGS_CPF_CNT_EN_EN6_WE_BM        0x00400000

#define AG_MG_REGS_CPF_CNT_EN_EN7_WE_BO        23
#define AG_MG_REGS_CPF_CNT_EN_EN7_WE_BM        0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT_EN_U
{
    struct
    {
        ag_mg_regs_register
            en0 : 1,
            en1 : 1,
            en2 : 1,
            en3 : 1,
            en4 : 1,
            en5 : 1,
            en6 : 1,
            en7 : 1,
            fill1 : 8,
            en0_we : 1,
            en1_we : 1,
            en2_we : 1,
            en3_we : 1,
            en4_we : 1,
            en5_we : 1,
            en6_we : 1,
            en7_we : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt_en_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_CNT_OVF_RO              0x00000088
#define AG_MG_REGS_CPF_CNT_OVF_RM              0x00FF00FF

#define AG_MG_REGS_CPF_CNT_OVF_OVF0_BO         0
#define AG_MG_REGS_CPF_CNT_OVF_OVF0_BM         0x00000001

#define AG_MG_REGS_CPF_CNT_OVF_OVF1_BO         1
#define AG_MG_REGS_CPF_CNT_OVF_OVF1_BM         0x00000002

#define AG_MG_REGS_CPF_CNT_OVF_OVF2_BO         2
#define AG_MG_REGS_CPF_CNT_OVF_OVF2_BM         0x00000004

#define AG_MG_REGS_CPF_CNT_OVF_OVF3_BO         3
#define AG_MG_REGS_CPF_CNT_OVF_OVF3_BM         0x00000008

#define AG_MG_REGS_CPF_CNT_OVF_OVF4_BO         4
#define AG_MG_REGS_CPF_CNT_OVF_OVF4_BM         0x00000010

#define AG_MG_REGS_CPF_CNT_OVF_OVF5_BO         5
#define AG_MG_REGS_CPF_CNT_OVF_OVF5_BM         0x00000020

#define AG_MG_REGS_CPF_CNT_OVF_OVF6_BO         6
#define AG_MG_REGS_CPF_CNT_OVF_OVF6_BM         0x00000040

#define AG_MG_REGS_CPF_CNT_OVF_OVF7_BO         7
#define AG_MG_REGS_CPF_CNT_OVF_OVF7_BM         0x00000080

#define AG_MG_REGS_CPF_CNT_OVF_OVF0_WE_BO      16
#define AG_MG_REGS_CPF_CNT_OVF_OVF0_WE_BM      0x00010000

#define AG_MG_REGS_CPF_CNT_OVF_OVF1_WE_BO      17
#define AG_MG_REGS_CPF_CNT_OVF_OVF1_WE_BM      0x00020000

#define AG_MG_REGS_CPF_CNT_OVF_OVF2_WE_BO      18
#define AG_MG_REGS_CPF_CNT_OVF_OVF2_WE_BM      0x00040000

#define AG_MG_REGS_CPF_CNT_OVF_OVF3_WE_BO      19
#define AG_MG_REGS_CPF_CNT_OVF_OVF3_WE_BM      0x00080000

#define AG_MG_REGS_CPF_CNT_OVF_OVF4_WE_BO      20
#define AG_MG_REGS_CPF_CNT_OVF_OVF4_WE_BM      0x00100000

#define AG_MG_REGS_CPF_CNT_OVF_OVF5_WE_BO      21
#define AG_MG_REGS_CPF_CNT_OVF_OVF5_WE_BM      0x00200000

#define AG_MG_REGS_CPF_CNT_OVF_OVF6_WE_BO      22
#define AG_MG_REGS_CPF_CNT_OVF_OVF6_WE_BM      0x00400000

#define AG_MG_REGS_CPF_CNT_OVF_OVF7_WE_BO      23
#define AG_MG_REGS_CPF_CNT_OVF_OVF7_WE_BM      0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_CNT_OVF_U
{
    struct
    {
        ag_mg_regs_register
            ovf0 : 1,
            ovf1 : 1,
            ovf2 : 1,
            ovf3 : 1,
            ovf4 : 1,
            ovf5 : 1,
            ovf6 : 1,
            ovf7 : 1,
            fill1 : 8,
            ovf0_we : 1,
            ovf1_we : 1,
            ovf2_we : 1,
            ovf3_we : 1,
            ovf4_we : 1,
            ovf5_we : 1,
            ovf6_we : 1,
            ovf7_we : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_cnt_ovf_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_INT_EN_RO               0x0000008C
#define AG_MG_REGS_CPF_INT_EN_RM               0x00FF00FF

#define AG_MG_REGS_CPF_INT_EN_INT_EN0_BO       0
#define AG_MG_REGS_CPF_INT_EN_INT_EN0_BM       0x00000001

#define AG_MG_REGS_CPF_INT_EN_INT_EN1_BO       1
#define AG_MG_REGS_CPF_INT_EN_INT_EN1_BM       0x00000002

#define AG_MG_REGS_CPF_INT_EN_INT_EN2_BO       2
#define AG_MG_REGS_CPF_INT_EN_INT_EN2_BM       0x00000004

#define AG_MG_REGS_CPF_INT_EN_INT_EN3_BO       3
#define AG_MG_REGS_CPF_INT_EN_INT_EN3_BM       0x00000008

#define AG_MG_REGS_CPF_INT_EN_INT_EN4_BO       4
#define AG_MG_REGS_CPF_INT_EN_INT_EN4_BM       0x00000010

#define AG_MG_REGS_CPF_INT_EN_INT_EN5_BO       5
#define AG_MG_REGS_CPF_INT_EN_INT_EN5_BM       0x00000020

#define AG_MG_REGS_CPF_INT_EN_INT_EN6_BO       6
#define AG_MG_REGS_CPF_INT_EN_INT_EN6_BM       0x00000040

#define AG_MG_REGS_CPF_INT_EN_INT_EN7_BO       7
#define AG_MG_REGS_CPF_INT_EN_INT_EN7_BM       0x00000080

#define AG_MG_REGS_CPF_INT_EN_INT_EN0_WE_BO    16
#define AG_MG_REGS_CPF_INT_EN_INT_EN0_WE_BM    0x00010000

#define AG_MG_REGS_CPF_INT_EN_INT_EN1_WE_BO    17
#define AG_MG_REGS_CPF_INT_EN_INT_EN1_WE_BM    0x00020000

#define AG_MG_REGS_CPF_INT_EN_INT_EN2_WE_BO    18
#define AG_MG_REGS_CPF_INT_EN_INT_EN2_WE_BM    0x00040000

#define AG_MG_REGS_CPF_INT_EN_INT_EN3_WE_BO    19
#define AG_MG_REGS_CPF_INT_EN_INT_EN3_WE_BM    0x00080000

#define AG_MG_REGS_CPF_INT_EN_INT_EN4_WE_BO    20
#define AG_MG_REGS_CPF_INT_EN_INT_EN4_WE_BM    0x00100000

#define AG_MG_REGS_CPF_INT_EN_INT_EN5_WE_BO    21
#define AG_MG_REGS_CPF_INT_EN_INT_EN5_WE_BM    0x00200000

#define AG_MG_REGS_CPF_INT_EN_INT_EN6_WE_BO    22
#define AG_MG_REGS_CPF_INT_EN_INT_EN6_WE_BM    0x00400000

#define AG_MG_REGS_CPF_INT_EN_INT_EN7_WE_BO    23
#define AG_MG_REGS_CPF_INT_EN_INT_EN7_WE_BM    0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_INT_EN_U
{
    struct
    {
        ag_mg_regs_register
            int_en0 : 1,
            int_en1 : 1,
            int_en2 : 1,
            int_en3 : 1,
            int_en4 : 1,
            int_en5 : 1,
            int_en6 : 1,
            int_en7 : 1,
            fill1 : 8,
            int_en0_we : 1,
            int_en1_we : 1,
            int_en2_we : 1,
            int_en3_we : 1,
            int_en4_we : 1,
            int_en5_we : 1,
            int_en6_we : 1,
            int_en7_we : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_int_en_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_GLB_CFG_RO              0x00000090
#define AG_MG_REGS_CPF_GLB_CFG_RM              0x00030003

#define AG_MG_REGS_CPF_GLB_CFG_GSEN_BO         0
#define AG_MG_REGS_CPF_GLB_CFG_GSEN_BM         0x00000001

#define AG_MG_REGS_CPF_GLB_CFG_GSCFG_BO        1
#define AG_MG_REGS_CPF_GLB_CFG_GSCFG_BM        0x00000002

#define AG_MG_REGS_CPF_GLB_CFG_GSEN_WE_BO      16
#define AG_MG_REGS_CPF_GLB_CFG_GSEN_WE_BM      0x00010000

#define AG_MG_REGS_CPF_GLB_CFG_GSCFG_WE_BO     17
#define AG_MG_REGS_CPF_GLB_CFG_GSCFG_WE_BM     0x00020000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_GLB_CFG_U
{
    struct
    {
        ag_mg_regs_register
            gsen : 1,
            gscfg : 1,
            fill1 : 14,
            gsen_we : 1,
            gscfg_we : 1,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_glb_cfg_u;
#endif


/* 
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_CPF_EGRP_RO                 0x00000094
#define AG_MG_REGS_CPF_EGRP_RM                 0x000000FF

#define AG_MG_REGS_CPF_EGRP_GRPNUM_BO          0
#define AG_MG_REGS_CPF_EGRP_GRPNUM_BM          0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_CPF_EGRP_U
{
    struct
    {
        ag_mg_regs_register
            grpnum : 8,
            rsvd : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_cpf_egrp_u;
#endif

/*
* Physical register addresses (for DSS accessing its own CPF)
*/
/*
 * Physical register addresses (for dss accessing cpf)
 */
#define AG_MG_REGS_CPF_BASE		0x80108000
#define AG_MG_REGS_CPF_REG(ro)		(AG_MG_REGS_CPF_BASE+(ro))
 
#define AG_MG_REGS_CPF_CNT0_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT0_RO)
#define AG_MG_REGS_CPF_CNT1_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT1_RO)
#define AG_MG_REGS_CPF_CNT2_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT2_RO)
#define AG_MG_REGS_CPF_CNT3_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT3_RO)
#define AG_MG_REGS_CPF_CNT4_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT4_RO)
#define AG_MG_REGS_CPF_CNT5_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT5_RO)
#define AG_MG_REGS_CPF_CNT6_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT6_RO)
#define AG_MG_REGS_CPF_CNT7_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT7_RO)
#define AG_MG_REGS_CPF_CNT_CFG0_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT_CFG0_RO)
#define AG_MG_REGS_CPF_CNT_CFG1_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT_CFG1_RO)
#define AG_MG_REGS_CPF_CNT_CFG2_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT_CFG2_RO)
#define AG_MG_REGS_CPF_CNT_CFG3_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT_CFG3_RO)
#define AG_MG_REGS_CPF_CNT_CFG4_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT_CFG4_RO)
#define AG_MG_REGS_CPF_CNT_CFG5_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT_CFG5_RO)
#define AG_MG_REGS_CPF_CNT_CFG6_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT_CFG6_RO)
#define AG_MG_REGS_CPF_CNT_CFG7_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT_CFG7_RO)
#define AG_MG_REGS_CPF_CNT_CLR_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT_CLR_RO)
#define AG_MG_REGS_CPF_CNT_EN_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT_EN_RO)
#define AG_MG_REGS_CPF_CNT_OVF_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_CNT_OVF_RO)
#define AG_MG_REGS_CPF_INT_EN_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_INT_EN_RO)
#define AG_MG_REGS_CPF_GLB_CFG_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_GLB_CFG_RO)
#define AG_MG_REGS_CPF_EGRP_RA	AG_MG_REGS_CPF_REG(AG_MG_REGS_CPF_EGRP_RO)

// useful macros to access individual bits in registers :
//  CPF_CNT_CLR, CPF_CNT_EN, CPF_CNT_OVF, and CPF_INT_EN
// NOTE: b can range from 0 to 7
#define AG_MG_REGS_CPF_GET_BIT_LOW(b,ra)     (((*((ag_mg_regs_register *)ra)) >> b) & 1)
#define AG_MG_REGS_CPF_GET_BIT_HIGH(b,ra)     (((*((ag_mg_regs_register *)ra)) >> (16 + b)) & 1)

#define AG_MG_REGS_CPF_SET_BIT_LOW(b,ra)     (*((ag_mg_regs_register *)ra)) |= (((ag_mg_regs_register)1) << b)
#define AG_MG_REGS_CPF_SET_BIT_HIGH(b,ra)     (*((ag_mg_regs_register *)ra)) |= (((ag_mg_regs_register)1) << (16 + b))


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_CPF_REGS_S
{
	ag_mg_regs_cpf_cnt0_u		cpf_cnt0 ;
	ag_mg_regs_cpf_cnt1_u		cpf_cnt1 ;
	ag_mg_regs_cpf_cnt2_u		cpf_cnt2 ;
	ag_mg_regs_cpf_cnt3_u		cpf_cnt3 ;
	ag_mg_regs_cpf_cnt4_u		cpf_cnt4 ;
	ag_mg_regs_cpf_cnt5_u		cpf_cnt5 ;
	ag_mg_regs_cpf_cnt6_u		cpf_cnt6 ;
	ag_mg_regs_cpf_cnt7_u		cpf_cnt7 ;
	ag_mg_regs_register		FILL0[8] ;
	ag_mg_regs_cpf_cnt_cfg0_u	cpf_cnt_cfg0 ;
	ag_mg_regs_cpf_cnt_cfg1_u	cpf_cnt_cfg1 ;
	ag_mg_regs_cpf_cnt_cfg2_u	cpf_cnt_cfg2 ;
	ag_mg_regs_cpf_cnt_cfg3_u	cpf_cnt_cfg3 ;
	ag_mg_regs_cpf_cnt_cfg4_u	cpf_cnt_cfg4 ;
	ag_mg_regs_cpf_cnt_cfg5_u	cpf_cnt_cfg5 ;
	ag_mg_regs_cpf_cnt_cfg6_u	cpf_cnt_cfg6 ;
	ag_mg_regs_cpf_cnt_cfg7_u	cpf_cnt_cfg7 ;
	ag_mg_regs_cpf_cnt_clr_u	cpf_cnt_clr ;
	ag_mg_regs_cpf_cnt_en_u		cpf_cnt_en ;
	ag_mg_regs_cpf_cnt_ovf_u	cpf_cnt_ovf ;
	ag_mg_regs_cpf_int_en_u		cpf_int_en ;
	ag_mg_regs_cpf_glb_cfg_u	cpf_glb_cfg ;
	ag_mg_regs_cpf_egrp_u		cpf_egrp ;
} ag_mg_regs_cpf_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_cpf_reg_s *cpf_regs =
*       (volatile ag_mg_regs_cpf_reg_s *)AG_MG_REGS_CPF_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_cpf.h,v $
Revision 1.2  2017/07/28 07:58:33  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:24  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:25  srane
Initial checkin


$Endlog$
*/

