/* $Id: ag_mg_regs_oce.h,v 1.2 2017/07/28 07:58:34 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_oce.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_oce.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
* ag_mg_regs_dss_oce.h
*
* Copyright (c) 2010 LSI Inc.  All Rights Reserved
*
* This is unpublished proprietary information of LSI Inc.
* This copyright notice does not evidence publication.
*
* The use of the software, documentation, methodologies, and other information
* contained herein is governed solely by the associated license agreements.
* Any inconsistent use shall be deemed to be a misappropriation of the
* intellectual property of LSI Inc. and treated accordingly.
*
* This file defines DSP Subsystem (DSS) On-Chip Emulator (OCE) registers.
*
* Register addresses defined herein are for
*  code running on the DSS accessing its own OCE.
*
* See "Physical register addresses" below for macros
* used to generate addresses for specific registers.
*
* Registers defined in this file :
 *  OCE_TB_BUFF
 *  OCE_TB_WR
 *  OCE_TB_RD
 *  OCE_TB_CTRL
 *  OCE_ESEL_DTB
 *  OCE_ESEL_ETB
 *  ESEL_ADM
 *  OCE_ESEL_DI
 *  OCE_ESEL_DM
 *  OCE_ESEL_CTRL
 *  OCE_ECNT_EXT
 *  OCE_ECNT_VAL
 *  OCE_ECNT_CTRL
 *  OCE_EDCD_MASK
 *  OCE_EDCD_REF
 *  OCE_EDCD_CTRL
 *  OCE_EDCA5MASK
 *  OCE_EDCA4MASK
 *  OCE_EDCA3MASK
 *  OCE_EDCA2MASK
 *  OCE_EDCA1MASK
 *  OCE_EDCA_MASK
 *  OCE_EDCA5REFID
 *  OCE_EDCA4REFID
 *  OCE_EDCA3REFID
 *  OCE_EDCA2REFID
 *  OCE_EDCA1REFID
 *  OCE_EDCA_REFID
 *  OCE_EDCA5REFB
 *  OCE_EDCA4REFB
 *  OCE_EDCA3REFB
 *  OCE_EDCA2REFB
 *  OCE_EDCA1REFB
 *  OCE_EDCA_REFB
 *  OCE_EDCA5REFA
 *  OCE_EDCA4REFA
 *  OCE_EDCA3REFA
 *  OCE_EDCA2REFA
 *  OCE_EDCA1REFA
 *  OCE_EDCA_REFA
 *  EDCA_XABE
 *  OCE_EDCA5CTRL
 *  OCE_EDCA4CTRL
 *  OCE_EDCA3CTRL
 *  OCE_EDCA2CTRL
 *  OCE_EDCA1CTRL
 *  OCE_EDCA_CTRL
 *  OCE_ECFGH
 *  OCE_ECFGL
 *  OCE_CORECFG
 *  SYSREV
 *  OCE_PC_MMU
 *  OCE_PC_DETECT
 *  OCE_PC_EXCP
 *  OCE_EE_CTRL
 *  OCE_ETRSMTH
 *  OCE_ETRSMTL
 *  OCE_ERCVH
 *  OCE_ERCVL
 *  OCE_EMCR
 *  OCE_ESR

*
* Prefix naming conventions :
*   AG_MG_REGS_XXX_RA : register/memory physical address
*   AG_MG_REGS_XXX_RO : register/memory address offset
*   AG_MG_REGS_XXX_RM : register mask
*   AG_MG_REGS_XXX_BO : bit/field offset from LSB
*   AG_MG_REGS_XXX_BM : bit/field mask
*   AG_MG_REGS_XXX_U  : bitfields in C union typedef
*   AG_MG_REGS_XXX_S  : registers in C struct typedef
*   AG_MG_REGS_XX_RPT : number of identical registers in array
*   AG_MG_REGS_XX_IVL : interval between registers in array
*
* NOTE: user may redefine ag_mg_regs_register
*       in ag_mg_regs_regops.h if necessary
* NOTE: access mode of individual bit fields matches that
*       of containing register unless indicated otherwise
*/

#ifndef AG_MG_REGS_DSS_OCE_REGISTERS_H
#define AG_MG_REGS_DSS_OCE_REGISTERS_H

#include "ag_mg_regs_regops.h"


/*
 * Generated by HSI Designer release 2.3.5.
 */





/*
 * OCE_TB_BUFF (OCE DSS Emulator Trace Buffer Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OCE_TB_BUFF_RO                    0x0000014C
#define AG_MG_REGS_OCE_TB_BUFF_RM                    0xFFFFFFFF

#define AG_MG_REGS_OCE_TB_BUFF_TBBUFF_BO             0
#define AG_MG_REGS_OCE_TB_BUFF_TBBUFF_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_TB_BUFF_U
{
    struct
    {
        ag_mg_regs_register
            tbbuff;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_tb_buff_u;
#endif


/*
 * OCE_TB_WR (OCE DSS Emulator Trace Buffer Write Pointer Register)
 * Initialization value: 0x0000  Initialization mask: 0xFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_TB_WR_RO                      0x00000148
#define AG_MG_REGS_OCE_TB_WR_RM                      0x0000FFFF

#define AG_MG_REGS_OCE_TB_WR_TBWR_BO                 0
#define AG_MG_REGS_OCE_TB_WR_TBWR_BM                 0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_TB_WR_U
{
    struct
    {
        unsigned short
            tbwr;
    } fields;
    unsigned short reg;
} ag_mg_regs_oce_tb_wr_u;
#endif


/*
 * OCE_TB_RD (OCE DSS Emulator Trace Buffer Read Pointer Register)
 * Initialization value: 0x0000  Initialization mask: 0xFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_TB_RD_RO                      0x00000144
#define AG_MG_REGS_OCE_TB_RD_RM                      0x0000FFFF

#define AG_MG_REGS_OCE_TB_RD_TBRD_BO                 0
#define AG_MG_REGS_OCE_TB_RD_TBRD_BM                 0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_TB_RD_U
{
    struct
    {
        unsigned short
            tbrd;
    } fields;
    unsigned short reg;
} ag_mg_regs_oce_tb_rd_u;
#endif


/*
 * OCE_TB_CTRL (OCE DSS Emulator Trace Buffer Control Register)
 * Initialization value: 0x0000  Initialization mask: 0xFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_TB_CTRL_RO                    0x00000140
#define AG_MG_REGS_OCE_TB_CTRL_RM                    0x0000C3FF

#define AG_MG_REGS_OCE_TB_CTRL_TCHOF_BO              0
#define AG_MG_REGS_OCE_TB_CTRL_TCHOF_BM              0x00000001

#define AG_MG_REGS_OCE_TB_CTRL_TINT_BO               1
#define AG_MG_REGS_OCE_TB_CTRL_TINT_BM               0x00000002

#define AG_MG_REGS_OCE_TB_CTRL_TEXEC_BO              2
#define AG_MG_REGS_OCE_TB_CTRL_TEXEC_BM              0x00000004

#define AG_MG_REGS_OCE_TB_CTRL_TMARK_BO              3
#define AG_MG_REGS_OCE_TB_CTRL_TMARK_BM              0x00000008

#define AG_MG_REGS_OCE_TB_CTRL_TEN_BO                4
#define AG_MG_REGS_OCE_TB_CTRL_TEN_BM                0x00000010

#define AG_MG_REGS_OCE_TB_CTRL_TLOOP_BO              5
#define AG_MG_REGS_OCE_TB_CTRL_TLOOP_BM              0x00000020

#define AG_MG_REGS_OCE_TB_CTRL_TCOUNT_BO             6
#define AG_MG_REGS_OCE_TB_CTRL_TCOUNT_BM             0x00000040

#define AG_MG_REGS_OCE_TB_CTRL_TCNTEXT_BO            7
#define AG_MG_REGS_OCE_TB_CTRL_TCNTEXT_BM            0x00000080

#define AG_MG_REGS_OCE_TB_CTRL_TRTE_BO               8
#define AG_MG_REGS_OCE_TB_CTRL_TRTE_BM               0x00000100

#define AG_MG_REGS_OCE_TB_CTRL_TSUB_BO               9
#define AG_MG_REGS_OCE_TB_CTRL_TSUB_BM               0x00000200

#define AG_MG_REGS_OCE_TB_CTRL_RTP_BO                14
#define AG_MG_REGS_OCE_TB_CTRL_RTP_BM                0x00004000

#define AG_MG_REGS_OCE_TB_CTRL_PRM_BO                15
#define AG_MG_REGS_OCE_TB_CTRL_PRM_BM                0x00008000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_TB_CTRL_U
{
    struct
    {
        unsigned short
            tchof : 1,
            tint : 1,
            texec : 1,
            tmark : 1,
            ten : 1,
            tloop : 1,
            tcount : 1,
            tcntext : 1,
            trte : 1,
            tsub : 1,
            fill0 : 4,
            rtp : 1,
            prm : 1;
    } fields;
    unsigned short reg;
} ag_mg_regs_oce_tb_ctrl_u;
#endif


/*
 * OCE_ESEL_DTB (OCE DSS Emulator Event Selector Mask Disable Trace Register)
 * Initialization value: 0x0000  Initialization mask: 0xFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_ESEL_DTB_RO                   0x00000134
#define AG_MG_REGS_OCE_ESEL_DTB_RM                   0x0000FFFF

#define AG_MG_REGS_OCE_ESEL_DTB_EDCA_BO              0
#define AG_MG_REGS_OCE_ESEL_DTB_EDCA_BM              0x0000003F

#define AG_MG_REGS_OCE_ESEL_DTB_EXT_ENA_BO           6
#define AG_MG_REGS_OCE_ESEL_DTB_EXT_ENA_BM           0x000000C0

#define AG_MG_REGS_OCE_ESEL_DTB_EDCD_BO              8
#define AG_MG_REGS_OCE_ESEL_DTB_EDCD_BM              0x00000100

#define AG_MG_REGS_OCE_ESEL_DTB_COUNT_BO             9
#define AG_MG_REGS_OCE_ESEL_DTB_COUNT_BM             0x00000200

#define AG_MG_REGS_OCE_ESEL_DTB_EE_BO                10
#define AG_MG_REGS_OCE_ESEL_DTB_EE_BM                0x00007C00

#define AG_MG_REGS_OCE_ESEL_DTB_DEBUGEV_BO           15
#define AG_MG_REGS_OCE_ESEL_DTB_DEBUGEV_BM           0x00008000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ESEL_DTB_U
{
    struct
    {
        unsigned short
            edca : 6,
            ext_ena : 2,
            edcd : 1,
            count : 1,
            ee : 5,
            debugev : 1;
    } fields;
    unsigned short reg;
} ag_mg_regs_oce_esel_dtb_u;
#endif


/*
 * OCE_ESEL_ETB (OCE DSS Emulator Event Selector Mask Enable Trace Register)
 * Initialization value: 0x0000  Initialization mask: 0xFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_ESEL_ETB_RO                   0x00000130
#define AG_MG_REGS_OCE_ESEL_ETB_RM                   0x0000FFFF

#define AG_MG_REGS_OCE_ESEL_ETB_EDCA_BO              0
#define AG_MG_REGS_OCE_ESEL_ETB_EDCA_BM              0x0000003F

#define AG_MG_REGS_OCE_ESEL_ETB_EXT_ENA_BO           6
#define AG_MG_REGS_OCE_ESEL_ETB_EXT_ENA_BM           0x000000C0

#define AG_MG_REGS_OCE_ESEL_ETB_EDCD_BO              8
#define AG_MG_REGS_OCE_ESEL_ETB_EDCD_BM              0x00000100

#define AG_MG_REGS_OCE_ESEL_ETB_COUNT_BO             9
#define AG_MG_REGS_OCE_ESEL_ETB_COUNT_BM             0x00000200

#define AG_MG_REGS_OCE_ESEL_ETB_EE_BO                10
#define AG_MG_REGS_OCE_ESEL_ETB_EE_BM                0x00007C00

#define AG_MG_REGS_OCE_ESEL_ETB_BEBUGEV_BO           15
#define AG_MG_REGS_OCE_ESEL_ETB_BEBUGEV_BM           0x00008000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ESEL_ETB_U
{
    struct
    {
        unsigned short
            edca : 6,
            ext_ena : 2,
            edcd : 1,
            count : 1,
            ee : 5,
            bebugev : 1;
    } fields;
    unsigned short reg;
} ag_mg_regs_oce_esel_etb_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_ESEL_ADM_RO                       0x0000012C
#define AG_MG_REGS_ESEL_ADM_RM                       0x000001FF

#define AG_MG_REGS_ESEL_ADM_EDCA0_BO                 0
#define AG_MG_REGS_ESEL_ADM_EDCA0_BM                 0x00000001

#define AG_MG_REGS_ESEL_ADM_EDCA1_BO                 1
#define AG_MG_REGS_ESEL_ADM_EDCA1_BM                 0x00000002

#define AG_MG_REGS_ESEL_ADM_EDCA2_BO                 2
#define AG_MG_REGS_ESEL_ADM_EDCA2_BM                 0x00000004

#define AG_MG_REGS_ESEL_ADM_EDCA3_BO                 3
#define AG_MG_REGS_ESEL_ADM_EDCA3_BM                 0x00000008

#define AG_MG_REGS_ESEL_ADM_EDCA4_BO                 4
#define AG_MG_REGS_ESEL_ADM_EDCA4_BM                 0x00000010

#define AG_MG_REGS_ESEL_ADM_EDCA5_BO                 5
#define AG_MG_REGS_ESEL_ADM_EDCA5_BM                 0x00000020

#define AG_MG_REGS_ESEL_ADM_EXT_ENA1_BO              6
#define AG_MG_REGS_ESEL_ADM_EXT_ENA1_BM              0x00000040

#define AG_MG_REGS_ESEL_ADM_EXT_ENA2_BO              7
#define AG_MG_REGS_ESEL_ADM_EXT_ENA2_BM              0x00000080

#define AG_MG_REGS_ESEL_ADM_EDCD_BO                  8
#define AG_MG_REGS_ESEL_ADM_EDCD_BM                  0x00000100

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ESEL_ADM_U
{
    struct
    {
        ag_mg_regs_register
            edca0 : 1,
            edca1 : 1,
            edca2 : 1,
            edca3 : 1,
            edca4 : 1,
            edca5 : 1,
            ext_ena1 : 1,
            ext_ena2 : 1,
            edcd : 1,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_esel_adm_u;
#endif


/*
 * OCE_ESEL_DI (OCE DSS Emulator Event Selector Mask Debug Exception Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_ESEL_DI_RO                    0x00000128
#define AG_MG_REGS_OCE_ESEL_DI_RM                    0x0001FFFF

#define AG_MG_REGS_OCE_ESEL_DI_EDCA_BO               0
#define AG_MG_REGS_OCE_ESEL_DI_EDCA_BM               0x0000003F

#define AG_MG_REGS_OCE_ESEL_DI_EXT_ENA_BO            6
#define AG_MG_REGS_OCE_ESEL_DI_EXT_ENA_BM            0x000000C0

#define AG_MG_REGS_OCE_ESEL_DI_EDCD_BO               8
#define AG_MG_REGS_OCE_ESEL_DI_EDCD_BM               0x00000100

#define AG_MG_REGS_OCE_ESEL_DI_COUNT_BO              9
#define AG_MG_REGS_OCE_ESEL_DI_COUNT_BM              0x00000200

#define AG_MG_REGS_OCE_ESEL_DI_EE_BO                 10
#define AG_MG_REGS_OCE_ESEL_DI_EE_BM                 0x00007C00

#define AG_MG_REGS_OCE_ESEL_DI_DEBUGEV_BO            15
#define AG_MG_REGS_OCE_ESEL_DI_DEBUGEV_BM            0x00008000

#define AG_MG_REGS_OCE_ESEL_DI_TBFULL_BO             16
#define AG_MG_REGS_OCE_ESEL_DI_TBFULL_BM             0x00010000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ESEL_DI_U
{
    struct
    {
        ag_mg_regs_register
            edca : 6,
            ext_ena : 2,
            edcd : 1,
            count : 1,
            ee : 5,
            debugev : 1,
            tbfull : 1,
            fill0 : 15;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_esel_di_u;
#endif


/*
 * OCE_ESEL_DM (OCE DSS Emulator Event Selector Mask Debug Mode Register)
 * Initialization value: 0x00010000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_ESEL_DM_RO                    0x00000124
#define AG_MG_REGS_OCE_ESEL_DM_RM                    0x0001FFFF

#define AG_MG_REGS_OCE_ESEL_DM_EDCA_BO               0
#define AG_MG_REGS_OCE_ESEL_DM_EDCA_BM               0x0000003F

#define AG_MG_REGS_OCE_ESEL_DM_EXT_ENA_BO            6
#define AG_MG_REGS_OCE_ESEL_DM_EXT_ENA_BM            0x000000C0

#define AG_MG_REGS_OCE_ESEL_DM_EDCD_BO               8
#define AG_MG_REGS_OCE_ESEL_DM_EDCD_BM               0x00000100

#define AG_MG_REGS_OCE_ESEL_DM_COUNT_BO              9
#define AG_MG_REGS_OCE_ESEL_DM_COUNT_BM              0x00000200

#define AG_MG_REGS_OCE_ESEL_DM_EE_BO                 10
#define AG_MG_REGS_OCE_ESEL_DM_EE_BM                 0x00007C00

#define AG_MG_REGS_OCE_ESEL_DM_DEBUGEV_BO            15
#define AG_MG_REGS_OCE_ESEL_DM_DEBUGEV_BM            0x00008000

#define AG_MG_REGS_OCE_ESEL_DM_TBFULL_BO             16
#define AG_MG_REGS_OCE_ESEL_DM_TBFULL_BM             0x00010000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ESEL_DM_U
{
    struct
    {
        ag_mg_regs_register
            edca : 6,
            ext_ena : 2,
            edcd : 1,
            count : 1,
            ee : 5,
            debugev : 1,
            tbfull : 1,
            fill0 : 15;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_esel_dm_u;
#endif


/*
 * OCE_ESEL_CTRL (OCE DSS Emulator Event Selector Control Register)
 * Initialization value: 0x00  Initialization mask: 0xFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_ESEL_CTRL_RO                  0x00000120
#define AG_MG_REGS_OCE_ESEL_CTRL_RM                  0x0000001B

#define AG_MG_REGS_OCE_ESEL_CTRL_SELDM_BO            0
#define AG_MG_REGS_OCE_ESEL_CTRL_SELDM_BM            0x00000001

#define AG_MG_REGS_OCE_ESEL_CTRL_SELDI_BO            1
#define AG_MG_REGS_OCE_ESEL_CTRL_SELDI_BM            0x00000002

#define AG_MG_REGS_OCE_ESEL_CTRL_SELETB_BO           3
#define AG_MG_REGS_OCE_ESEL_CTRL_SELETB_BM           0x00000008

#define AG_MG_REGS_OCE_ESEL_CTRL_SELDTB_BO           4
#define AG_MG_REGS_OCE_ESEL_CTRL_SELDTB_BM           0x00000010

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ESEL_CTRL_U
{
    struct
    {
        unsigned char
            seldm : 1,
            seldi : 1,
            fill1 : 1,
            seletb : 1,
            seldtb : 1,
            fill0 : 3;
    } fields;
    unsigned char reg;
} ag_mg_regs_oce_esel_ctrl_u;
#endif


/*
 * OCE_ECNT_EXT (OCE DSS Emulator Extension Counter Value RegisterE)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_ECNT_EXT_RO                   0x00000108
#define AG_MG_REGS_OCE_ECNT_EXT_RM                   0xFFFFFFFF

#define AG_MG_REGS_OCE_ECNT_EXT_ECNTEXT_BO           0
#define AG_MG_REGS_OCE_ECNT_EXT_ECNTEXT_BM           0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ECNT_EXT_U
{
    struct
    {
        ag_mg_regs_register
            ecntext;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_ecnt_ext_u;
#endif


/*
 * OCE_ECNT_VAL (OCE DSS Emulator Event Counter Value Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_ECNT_VAL_RO                   0x00000104
#define AG_MG_REGS_OCE_ECNT_VAL_RM                   0xFFFFFFFF

#define AG_MG_REGS_OCE_ECNT_VAL_ECNTVAL_BO           0
#define AG_MG_REGS_OCE_ECNT_VAL_ECNTVAL_BM           0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ECNT_VAL_U
{
    struct
    {
        ag_mg_regs_register
            ecntval;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_ecnt_val_u;
#endif


/*
 * OCE_ECNT_CTRL (OCE DSS Emulator Event Counter Control Register)
 * Initialization value: 0x0000  Initialization mask: 0xFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_ECNT_CTRL_RO                  0x00000100
#define AG_MG_REGS_OCE_ECNT_CTRL_RM                  0x000003FF

#define AG_MG_REGS_OCE_ECNT_CTRL_ECNTWHAT_BO         0
#define AG_MG_REGS_OCE_ECNT_CTRL_ECNTWHAT_BM         0x0000000F

#define AG_MG_REGS_OCE_ECNT_CTRL_ECNTEN_BO           4
#define AG_MG_REGS_OCE_ECNT_CTRL_ECNTEN_BM           0x000000F0

#define AG_MG_REGS_OCE_ECNT_CTRL_EXT_BO              8
#define AG_MG_REGS_OCE_ECNT_CTRL_EXT_BM              0x00000100

#define AG_MG_REGS_OCE_ECNT_CTRL_TEST_BO             9
#define AG_MG_REGS_OCE_ECNT_CTRL_TEST_BM             0x00000200

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ECNT_CTRL_U
{
    struct
    {
        unsigned short
            ecntwhat : 4,
            ecnten : 4,
            ext : 1,
            test : 1,
            fill0 : 6;
    } fields;
    unsigned short reg;
} ag_mg_regs_oce_ecnt_ctrl_u;
#endif


/*
 * OCE_EDCD_MASK (OCE DSS Emulator EDCD Mask Register)
 * Initialization value: 0xFFFFFFFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_EDCD_MASK_RO                  0x000000E8
#define AG_MG_REGS_OCE_EDCD_MASK_RM                  0xFFFFFFFF

#define AG_MG_REGS_OCE_EDCD_MASK_OCE_EDCD_MASK_BO    0
#define AG_MG_REGS_OCE_EDCD_MASK_OCE_EDCD_MASK_BM    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_EDCD_MASK_U
{
    struct
    {
        ag_mg_regs_register
            edcd_mask;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_edcd_mask_u;
#endif


/*
 * OCE_EDCD_REF (OCE DSS Emulator EDCD Reference Value Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_EDCD_REF_RO                   0x000000E4
#define AG_MG_REGS_OCE_EDCD_REF_RM                   0xFFFFFFFF

#define AG_MG_REGS_OCE_EDCD_REF_OCE_EDCD_REF_BO      0
#define AG_MG_REGS_OCE_EDCD_REF_OCE_EDCD_REF_BM      0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_EDCD_REF_U
{
    struct
    {
        ag_mg_regs_register
            edcd_ref;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_edcd_ref_u;
#endif


/*
 * OCE_EDCD_CTRL (OCE DSS Emulator EDCD Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_EDCD_CTRL_RO                  0x000000E0
#define AG_MG_REGS_OCE_EDCD_CTRL_RM                  0x0001C37F

#define AG_MG_REGS_OCE_EDCD_CTRL_ATS_BO              0
#define AG_MG_REGS_OCE_EDCD_CTRL_ATS_BM              0x00000001

#define AG_MG_REGS_OCE_EDCD_CTRL_CCS_BO              1
#define AG_MG_REGS_OCE_EDCD_CTRL_CCS_BM              0x00000006

#define AG_MG_REGS_OCE_EDCD_CTRL_EDCDEN_BO           3
#define AG_MG_REGS_OCE_EDCD_CTRL_EDCDEN_BM           0x00000078

#define AG_MG_REGS_OCE_EDCD_CTRL_AWS_BO              8
#define AG_MG_REGS_OCE_EDCD_CTRL_AWS_BM              0x00000300

#define AG_MG_REGS_OCE_EDCD_CTRL_PLC_BO              14
#define AG_MG_REGS_OCE_EDCD_CTRL_PLC_BM              0x0001C000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_EDCD_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            ats : 1,
            ccs : 2,
            edcden : 4,
            fill2 : 1,
            aws : 2,
            fill1 : 4,
            plc : 3,
            fill0 : 15;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_edcd_ctrl_u;
#endif


/*
 * OCE_EDCA_MASK<0-5> (OCE DSS Emulator EDCA Mask Registers)
 * Initialization value: 0xFFFFFFFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_EDCA_MASK_RO                  0x000000C0
#define AG_MG_REGS_OCE_EDCA_MASK_RM                  0xFFFFFFFF

#define AG_MG_REGS_OCE_EDCA_MASK_EDCAMASK_BO         0
#define AG_MG_REGS_OCE_EDCA_MASK_EDCAMASK_BM         0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_EDCA_MASK_U
{
    struct
    {
        ag_mg_regs_register
            edcamask;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_edca_mask_u;
#endif


/*
 * OCE_EDCA_REFID<0-5> (OCE DSS Emulator EDCA Reference Process ID Registers)
 * Initialization value: 0x0000  Initialization mask: 0xFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_EDCA_REFID_RO                 0x000000A0
#define AG_MG_REGS_OCE_EDCA_REFID_RM                 0x000080FF

#define AG_MG_REGS_OCE_EDCA_REFID_PROCID_BO          0
#define AG_MG_REGS_OCE_EDCA_REFID_PROCID_BM          0x000000FF

#define AG_MG_REGS_OCE_EDCA_REFID_IDEN_BO            15
#define AG_MG_REGS_OCE_EDCA_REFID_IDEN_BM            0x00008000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_EDCA_REFID_U
{
    struct
    {
        unsigned short
            procid : 8,
            fill0 : 7,
            iden : 1;
    } fields;
    unsigned short reg;
} ag_mg_regs_oce_edca_refid_u;
#endif


/*
 * OCE_EDCA_REFB<0-5> (OCE DSS Emulator EDCA Reference Value B Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_EDCA_REFB_RO                  0x00000080
#define AG_MG_REGS_OCE_EDCA_REFB_RM                  0xFFFFFFFF

#define AG_MG_REGS_OCE_EDCA_REFB_EDCAREFB_BO         0
#define AG_MG_REGS_OCE_EDCA_REFB_EDCAREFB_BM         0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_EDCA_REFB_U
{
    struct
    {
        ag_mg_regs_register
            edcarefb;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_edca_refb_u;
#endif


/*
 * OCE_EDCA_REFA<0-5> (OCE DSS Emulator EDCA Reference Value A Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_EDCA_REFA_RO                  0x00000060
#define AG_MG_REGS_OCE_EDCA_REFA_RM                  0xFFFFFFFF

#define AG_MG_REGS_OCE_EDCA_REFA_EDCAREFA_BO         0
#define AG_MG_REGS_OCE_EDCA_REFA_EDCAREFA_BM         0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_EDCA_REFA_U
{
    struct
    {
        ag_mg_regs_register
            edcarefa;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_edca_refa_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_EDCA_XABE_RO                      0x00000058
#define AG_MG_REGS_EDCA_XABE_RM                      0x00000FFF

#define AG_MG_REGS_EDCA_XABE_EDCA0_BO                0
#define AG_MG_REGS_EDCA_XABE_EDCA0_BM                0x00000003

#define AG_MG_REGS_EDCA_XABE_EDCA1_BO                2
#define AG_MG_REGS_EDCA_XABE_EDCA1_BM                0x0000000C

#define AG_MG_REGS_EDCA_XABE_EDCA2_BO                4
#define AG_MG_REGS_EDCA_XABE_EDCA2_BM                0x00000030

#define AG_MG_REGS_EDCA_XABE_EDCA3_BO                6
#define AG_MG_REGS_EDCA_XABE_EDCA3_BM                0x000000C0

#define AG_MG_REGS_EDCA_XABE_EDCA4_BO                8
#define AG_MG_REGS_EDCA_XABE_EDCA4_BM                0x00000300

#define AG_MG_REGS_EDCA_XABE_EDCA5_BO                10
#define AG_MG_REGS_EDCA_XABE_EDCA5_BM                0x00000C00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_EDCA_XABE_U
{
    struct
    {
        ag_mg_regs_register
            edca0 : 2,
            edca1 : 2,
            edca2 : 2,
            edca3 : 2,
            edca4 : 2,
            edca5 : 2,
            fill0 : 20;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_edca_xabe_u;
#endif


/*
 * OCE_EDCA_CTRL<0-5> (OCE DSS Emulator EDCA Control Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_EDCA_CTRL_RO                  0x00000040
#define AG_MG_REGS_OCE_EDCA_CTRL_RM                  0x0003FFFF

#define AG_MG_REGS_OCE_EDCA_CTRL_BS_BO               0
#define AG_MG_REGS_OCE_EDCA_CTRL_BS_BM               0x00000003

#define AG_MG_REGS_OCE_EDCA_CTRL_ATS_BO              2
#define AG_MG_REGS_OCE_EDCA_CTRL_ATS_BM              0x0000000C

#define AG_MG_REGS_OCE_EDCA_CTRL_CACS_BO             4
#define AG_MG_REGS_OCE_EDCA_CTRL_CACS_BM             0x00000030

#define AG_MG_REGS_OCE_EDCA_CTRL_CBCS_BO             6
#define AG_MG_REGS_OCE_EDCA_CTRL_CBCS_BM             0x000000C0

#define AG_MG_REGS_OCE_EDCA_CTRL_CS_BO               8
#define AG_MG_REGS_OCE_EDCA_CTRL_CS_BM               0x00000300

#define AG_MG_REGS_OCE_EDCA_CTRL_EDCAEN_BO           10
#define AG_MG_REGS_OCE_EDCA_CTRL_EDCAEN_BM           0x00003C00

#define AG_MG_REGS_OCE_EDCA_CTRL_PLC_BO              14
#define AG_MG_REGS_OCE_EDCA_CTRL_PLC_BM              0x0001C000

#define AG_MG_REGS_OCE_EDCA_CTRL_NSYNC_BO            17
#define AG_MG_REGS_OCE_EDCA_CTRL_NSYNC_BM            0x00020000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_EDCA_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            bs : 2,
            ats : 2,
            cacs : 2,
            cbcs : 2,
            cs : 2,
            edcaen : 4,
            plc : 3,
            nsync : 1,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_edca_ctrl_u;
#endif


/*
 * OCE_ECFGH (OCE DSS Emulator Configuration Register High)
 * Initialization value: 0x000007FF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OCE_ECFGH_RO                      0x0000003C
#define AG_MG_REGS_OCE_ECFGH_RM                      0x0000FFFF

#define AG_MG_REGS_OCE_ECFGH_TBSIZE_BO               0
#define AG_MG_REGS_OCE_ECFGH_TBSIZE_BM               0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ECFGH_U
{
    struct
    {
        ag_mg_regs_register
            tbsize : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_ecfgh_u;
#endif


/*
 * OCE_ECFGL (OCE DSS Emulator Configuration Register Low)
 * Initialization value: 0x3F400000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OCE_ECFGL_RO                      0x00000038
#define AG_MG_REGS_OCE_ECFGL_RM                      0x3FFFFFFF

#define AG_MG_REGS_OCE_ECFGL_OCE_BASE_BM 0x007FFFFF
#define AG_MG_REGS_OCE_ECFGL_OCE_BASE_BO 0

#define AG_MG_REGS_OCE_ECFGL_EDCATP_BO               23
#define AG_MG_REGS_OCE_ECFGL_EDCATP_BM               0x03800000

#define AG_MG_REGS_OCE_ECFGL_EDCDTP_BO               26
#define AG_MG_REGS_OCE_ECFGL_EDCDTP_BM               0x04000000

#define AG_MG_REGS_OCE_ECFGL_CNTTP_BO                27
#define AG_MG_REGS_OCE_ECFGL_CNTTP_BM                0x18000000

#define AG_MG_REGS_OCE_ECFGL_TBTP_BO                 29
#define AG_MG_REGS_OCE_ECFGL_TBTP_BM                 0x20000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ECFGL_U
{
    struct
    {
        ag_mg_regs_register
            base : 23,
            edcatp : 3,
            edcdtp : 1,
            cnttp : 2,
            tbtp : 1,
            fill0 : 2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_ecfgl_u;
#endif


/*
 * OCE_CORECFG (OCE DSS Emulator Core Configuration Register)
 * Initialization value: 0x34106050  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OCE_CORECFG_RO                    0x00000034
#define AG_MG_REGS_OCE_CORECFG_RM                    0xFFFFFFFF

#define AG_MG_REGS_OCE_CORECFG_OCE_CORECFG_BO        0
#define AG_MG_REGS_OCE_CORECFG_OCE_CORECFG_BM        0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_CORECFG_U
{
    struct
    {
        ag_mg_regs_register
            corecfg;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_corecfg_u;
#endif


/*
 * Initialization value: 0x0001  Initialization mask: 0xFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_SYSREV_RO                         0x00000030
#define AG_MG_REGS_SYSREV_RM                         0x0000FFFF

#define AG_MG_REGS_SYSREV_OCE_COREREV_BO             0
#define AG_MG_REGS_SYSREV_OCE_COREREV_BM             0x000000FF

#define AG_MG_REGS_SYSREV_SYSREV_BO                  8
#define AG_MG_REGS_SYSREV_SYSREV_BM                  0x0000FF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SYSREV_U
{
    struct
    {
        unsigned short
            corerev : 8,
            sysrev : 8;
    } fields;
    unsigned short reg;
} ag_mg_regs_sysrev_u;
#endif


/*
 * OCE_PC_MMU (OCE DSS Emulator PC Memory Exception Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OCE_PC_MMU_RO                     0x0000002C
#define AG_MG_REGS_OCE_PC_MMU_RM                     0xFFFFFFFF

#define AG_MG_REGS_OCE_PC_MMU_PCMMU_BO               0
#define AG_MG_REGS_OCE_PC_MMU_PCMMU_BM               0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_PC_MMU_U
{
    struct
    {
        ag_mg_regs_register
            pcmmu;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_pc_mmu_u;
#endif


/*
 * OCE_PC_DETECT (OCE DSS Emulator PC Breakpoint Detection Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OCE_PC_DETECT_RO                  0x00000028
#define AG_MG_REGS_OCE_PC_DETECT_RM                  0xFFFFFFFF

#define AG_MG_REGS_OCE_PC_DETECT_PCBKPT_BO           0
#define AG_MG_REGS_OCE_PC_DETECT_PCBKPT_BM           0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_PC_DETECT_U
{
    struct
    {
        ag_mg_regs_register
            pcbkpt;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_pc_detect_u;
#endif


/*
 * OCE_PC_EXCP (OCE DSS Emulator Exception VLES PC Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OCE_PC_EXCP_RO                    0x0000001C
#define AG_MG_REGS_OCE_PC_EXCP_RM                    0xFFFFFFFF

#define AG_MG_REGS_OCE_PC_EXCP_PCEXCP_BO             0
#define AG_MG_REGS_OCE_PC_EXCP_PCEXCP_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_PC_EXCP_U
{
    struct
    {
        ag_mg_regs_register
            pcexcp;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_pc_excp_u;
#endif


/*
 * OCE_EE_CTRL (OCE DSS Emulator EE Signals Control Register)
 * Initialization value: 0xFFFF  Initialization mask: 0xFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_EE_CTRL_RO                    0x00000018
#define AG_MG_REGS_OCE_EE_CTRL_RM                    0x000087FF

#define AG_MG_REGS_OCE_EE_CTRL_EE0DEF_BO             0
#define AG_MG_REGS_OCE_EE_CTRL_EE0DEF_BM             0x00000003

#define AG_MG_REGS_OCE_EE_CTRL_EE1DEF_BO             2
#define AG_MG_REGS_OCE_EE_CTRL_EE1DEF_BM             0x0000000C

#define AG_MG_REGS_OCE_EE_CTRL_EE2DEF_BO             4
#define AG_MG_REGS_OCE_EE_CTRL_EE2DEF_BM             0x00000030

#define AG_MG_REGS_OCE_EE_CTRL_EE3DEF_BO             6
#define AG_MG_REGS_OCE_EE_CTRL_EE3DEF_BM             0x000000C0

#define AG_MG_REGS_OCE_EE_CTRL_EE4DEF_BO             8
#define AG_MG_REGS_OCE_EE_CTRL_EE4DEF_BM             0x00000300

#define AG_MG_REGS_OCE_EE_CTRL_EE5DEF_BO             10
#define AG_MG_REGS_OCE_EE_CTRL_EE5DEF_BM             0x00000400

#define AG_MG_REGS_OCE_EE_CTRL_EEDDEF_BO             15
#define AG_MG_REGS_OCE_EE_CTRL_EEDDEF_BM             0x00008000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_EE_CTRL_U
{
    struct
    {
        unsigned short
            ee0def : 2,
            ee1def : 2,
            ee2def : 2,
            ee3def : 2,
            ee4def : 2,
            ee5def : 1,
            fill0 : 4,
            eeddef : 1;
    } fields;
    unsigned short reg;
} ag_mg_regs_oce_ee_ctrl_u;
#endif


/*
 * OCE_ETRSMTH (OCE DSS Emulator Transmit Register High)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_OCE_ETRSMTH_RO                    0x00000014
#define AG_MG_REGS_OCE_ETRSMTH_RM                    0xFFFFFFFF

#define AG_MG_REGS_OCE_ETRSMTH_ETRSMTDAT_BO          0
#define AG_MG_REGS_OCE_ETRSMTH_ETRSMTDAT_BM          0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ETRSMTH_U
{
    struct
    {
        ag_mg_regs_register
            etrsmtdat;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_etrsmth_u;
#endif


/*
 * OCE_ETRSMTL (OCE DSS Emulator Transmit Register Low)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_OCE_ETRSMTL_RO                    0x00000010
#define AG_MG_REGS_OCE_ETRSMTL_RM                    0xFFFFFFFF

#define AG_MG_REGS_OCE_ETRSMTL_ETRSMTDAT_BO          0
#define AG_MG_REGS_OCE_ETRSMTL_ETRSMTDAT_BM          0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ETRSMTL_U
{
    struct
    {
        ag_mg_regs_register
            etrsmtdat;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_etrsmtl_u;
#endif


/*
 * OCE_ERCVH (OCE DSS Emulator Receive Register High)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OCE_ERCVH_RO                      0x0000000C
#define AG_MG_REGS_OCE_ERCVH_RM                      0xFFFFFFFF

#define AG_MG_REGS_OCE_ERCVH_ERCVDAT_BO              0
#define AG_MG_REGS_OCE_ERCVH_ERCVDAT_BM              0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ERCVH_U
{
    struct
    {
        ag_mg_regs_register
            ercvdat;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_ercvh_u;
#endif


/*
 * OCE_ERCVL (OCE DSS Emulator Receive Register Low)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OCE_ERCVL_RO                      0x00000008
#define AG_MG_REGS_OCE_ERCVL_RM                      0xFFFFFFFF

#define AG_MG_REGS_OCE_ERCVL_ERCVDAT_BO              0
#define AG_MG_REGS_OCE_ERCVL_ERCVDAT_BM              0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ERCVL_U
{
    struct
    {
        ag_mg_regs_register
            ercvdat;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_ercvl_u;
#endif


/*
 * OCE_EMCR (OCE DSS Emulator Monitor and Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OCE_EMCR_RO                       0x00000004
#define AG_MG_REGS_OCE_EMCR_RM                       0x0FFFC7FF

#define AG_MG_REGS_OCE_EMCR_EDCAST_BO                0
#define AG_MG_REGS_OCE_EMCR_EDCAST_BM                0x0000003F

#define AG_MG_REGS_OCE_EMCR_EXT_ENAST_BO             6
#define AG_MG_REGS_OCE_EMCR_EXT_ENAST_BM             0x000000C0

#define AG_MG_REGS_OCE_EMCR_EDCDST_BO                8
#define AG_MG_REGS_OCE_EMCR_EDCDST_BM                0x00000100

#define AG_MG_REGS_OCE_EMCR_EXTBV_BO                 9
#define AG_MG_REGS_OCE_EMCR_EXTBV_BM                 0x00000200

#define AG_MG_REGS_OCE_EMCR_RTPI_BO                  10
#define AG_MG_REGS_OCE_EMCR_RTPI_BM                  0x00000400

#define AG_MG_REGS_OCE_EMCR_PICCLR_BO                14
#define AG_MG_REGS_OCE_EMCR_PICCLR_BM                0x00004000

#define AG_MG_REGS_OCE_EMCR_DIS_BO                   15
#define AG_MG_REGS_OCE_EMCR_DIS_BM                   0x00008000

#define AG_MG_REGS_OCE_EMCR_IME_BO                   16
#define AG_MG_REGS_OCE_EMCR_IME_BM                   0x00010000

#define AG_MG_REGS_OCE_EMCR_SWDIS_BO                 17
#define AG_MG_REGS_OCE_EMCR_SWDIS_BM                 0x00020000

#define AG_MG_REGS_OCE_EMCR_DEBUGERST_BO             18
#define AG_MG_REGS_OCE_EMCR_DEBUGERST_BM             0x003C0000

#define AG_MG_REGS_OCE_EMCR_RCVINT_BO                22
#define AG_MG_REGS_OCE_EMCR_RCVINT_BM                0x00400000

#define AG_MG_REGS_OCE_EMCR_TBFDM_BO                 23
#define AG_MG_REGS_OCE_EMCR_TBFDM_BM                 0x00800000

#define AG_MG_REGS_OCE_EMCR_TRSINT_BO                24
#define AG_MG_REGS_OCE_EMCR_TRSINT_BM                0x01000000

#define AG_MG_REGS_OCE_EMCR_PICINT_BO                25
#define AG_MG_REGS_OCE_EMCR_PICINT_BM                0x02000000

#define AG_MG_REGS_OCE_EMCR_FDU_BO                   26
#define AG_MG_REGS_OCE_EMCR_FDU_BM                   0x04000000

#define AG_MG_REGS_OCE_EMCR_APBDBG_BO                27
#define AG_MG_REGS_OCE_EMCR_APBDBG_BM                0x08000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_EMCR_U
{
    struct
    {
        ag_mg_regs_register
            edcast : 6,
            ext_enast : 2,
            edcdst : 1,
            extbv : 1,
            rtpi : 1,
            fill1 : 3,
            picclr : 1,
            dis : 1,
            ime : 1,
            swdis : 1,
            debugerst : 4,
            rcvint : 1,
            tbfdm : 1,
            trsint : 1,
            picint : 1,
            fdu : 1,
            apbdbg : 1,
            fill0 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_emcr_u;
#endif


/*
 * OCE_ESR (OCE DSS Emulator Status Register)
 * Initialization value: 0x00F00000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OCE_ESR_RO                        0x00000000
#define AG_MG_REGS_OCE_ESR_RM                        0xDFFFFFFF

#define AG_MG_REGS_OCE_ESR_DREDCA_BO                 0
#define AG_MG_REGS_OCE_ESR_DREDCA_BM                 0x0000003F

#define AG_MG_REGS_OCE_ESR_DREXT_ENA_BO              6
#define AG_MG_REGS_OCE_ESR_DREXT_ENA_BM              0x000000C0

#define AG_MG_REGS_OCE_ESR_DREDCD_BO                 8
#define AG_MG_REGS_OCE_ESR_DREDCD_BM                 0x00000100

#define AG_MG_REGS_OCE_ESR_DRCOUNTER_BO              9
#define AG_MG_REGS_OCE_ESR_DRCOUNTER_BM              0x00000200

#define AG_MG_REGS_OCE_ESR_DREE_BO                   10
#define AG_MG_REGS_OCE_ESR_DREE_BM                   0x00007C00

#define AG_MG_REGS_OCE_ESR_DRSW_BO                   15
#define AG_MG_REGS_OCE_ESR_DRSW_BM                   0x00008000

#define AG_MG_REGS_OCE_ESR_DRTBFULL_BO               16
#define AG_MG_REGS_OCE_ESR_DRTBFULL_BM               0x00010000

#define AG_MG_REGS_OCE_ESR_CORETP_BO                 17
#define AG_MG_REGS_OCE_ESR_CORETP_BM                 0x001E0000

#define AG_MG_REGS_OCE_ESR_REVNO_BO                  21
#define AG_MG_REGS_OCE_ESR_REVNO_BM                  0x00E00000

#define AG_MG_REGS_OCE_ESR_NOCHOF_BO                 24
#define AG_MG_REGS_OCE_ESR_NOCHOF_BM                 0x01000000

#define AG_MG_REGS_OCE_ESR_TBFULL_BO                 25
#define AG_MG_REGS_OCE_ESR_TBFULL_BM                 0x02000000

#define AG_MG_REGS_OCE_ESR_TRSMT_BO                  26
#define AG_MG_REGS_OCE_ESR_TRSMT_BM                  0x04000000

#define AG_MG_REGS_OCE_ESR_RCV_BO                    27
#define AG_MG_REGS_OCE_ESR_RCV_BM                    0x08000000

#define AG_MG_REGS_OCE_ESR_PCKILL_BO                 28
#define AG_MG_REGS_OCE_ESR_PCKILL_BM                 0x10000000

#define AG_MG_REGS_OCE_ESR_CORES_BO                  30
#define AG_MG_REGS_OCE_ESR_CORES_BM                  0xC0000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_ESR_U
{
    struct
    {
        ag_mg_regs_register
            drecda : 6,
            rsvd1 : 2,
            dredcd : 1,
            drcounter : 1,
            dree0 : 1,
            rsvd2 : 4,
            drsw : 1,
            drtbfull : 1,
            scid : 7,
            nochof : 1,
            tbfull : 4,
            trsmt : 1,
            rcv : 1,
            pckill : 1,
            rsvd3 : 1,
            cores : 2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_esr_u;
#endif


/*
 * OCE_RD_STATUS (OCE Read Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OCE_RD_STATUS_RO                        0x00000000
#define AG_MG_REGS_OCE_RD_STATUS_RM                        0xDFFFFFFF

#define AG_MG_REGS_OCE_RD_STATUS_BUSY_BO                 0
#define AG_MG_REGS_OCE_RD_STATUS_BUSY_BM                 0x0000003F

#define AG_MG_REGS_OCE_RD_STATUS_CORES_ENA_BO              6
#define AG_MG_REGS_OCE_RD_STATUS_CORES_ENA_BM              0x000000C0

#define AG_MG_REGS_OCE_RD_STATUS_TB_BUSY_BO                 8
#define AG_MG_REGS_OCE_RD_STATUS_TB_BUSY_BM                 0x00000100


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OCE_RD_STATUS_U
{
    struct
    {
        ag_mg_regs_register
            busy : 1,
            cores : 2,
            tb_busy : 1,
            rsvd : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oce_rd_status_u;
#endif


/*
* Physical register addresses (for DSS accessing its own OCE)
*/
/*
 * Physical register addresses (for dss accessing oce)
 */
#define AG_MG_REGS_OCE_BASE		0x80000000
#define AG_MG_REGS_OCE_REG(ro)		(AG_MG_REGS_OCE_BASE+(ro))

#define AG_MG_REGS_OCE_RD_STATUS_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_RD_STATUS_RO)
#define AG_MG_REGS_OCE_TB_BUFF_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_TB_BUFF_RO)
#define AG_MG_REGS_OCE_TB_WR_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_TB_WR_RO)
#define AG_MG_REGS_OCE_TB_RD_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_TB_RD_RO)
#define AG_MG_REGS_OCE_TB_CTRL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_TB_CTRL_RO)
#define AG_MG_REGS_OCE_ESEL_DTB_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ESEL_DTB_RO)
#define AG_MG_REGS_OCE_ESEL_ETB_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ESEL_ETB_RO)
#define AG_MG_REGS_OCE_ESEL_ADM_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_ESEL_ADM_RO)
#define AG_MG_REGS_OCE_ESEL_DI_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ESEL_DI_RO)
#define AG_MG_REGS_OCE_ESEL_DM_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ESEL_DM_RO)
#define AG_MG_REGS_OCE_ESEL_CTRL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ESEL_CTRL_RO)
#define AG_MG_REGS_OCE_ECNT_EXT_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ECNT_EXT_RO)
#define AG_MG_REGS_OCE_ECNT_VAL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ECNT_VAL_RO)
#define AG_MG_REGS_OCE_ECNT_CTRL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ECNT_CTRL_RO)
#define AG_MG_REGS_OCE_EDCD_MASK_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCD_MASK_RO)
#define AG_MG_REGS_OCE_EDCD_REF_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCD_REF_RO)
#define AG_MG_REGS_OCE_EDCD_CTRL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCD_CTRL_RO)
#define AG_MG_REGS_OCE_EDCA5MASK_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA5MASK_RO)
#define AG_MG_REGS_OCE_EDCA4MASK_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA4MASK_RO)
#define AG_MG_REGS_OCE_EDCA3MASK_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA3MASK_RO)
#define AG_MG_REGS_OCE_EDCA2MASK_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA2MASK_RO)
#define AG_MG_REGS_OCE_EDCA1MASK_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA1MASK_RO)
#define AG_MG_REGS_OCE_EDCA_MASK_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA_MASK_RO)
#define AG_MG_REGS_OCE_EDCA5REFID_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA5REFID_RO)
#define AG_MG_REGS_OCE_EDCA4REFID_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA4REFID_RO)
#define AG_MG_REGS_OCE_EDCA3REFID_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA3REFID_RO)
#define AG_MG_REGS_OCE_EDCA2REFID_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA2REFID_RO)
#define AG_MG_REGS_OCE_EDCA1REFID_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA1REFID_RO)
#define AG_MG_REGS_OCE_EDCA_REFID_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA_REFID_RO)
#define AG_MG_REGS_OCE_EDCA5REFB_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA5REFB_RO)
#define AG_MG_REGS_OCE_EDCA4REFB_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA4REFB_RO)
#define AG_MG_REGS_OCE_EDCA3REFB_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA3REFB_RO)
#define AG_MG_REGS_OCE_EDCA2REFB_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA2REFB_RO)
#define AG_MG_REGS_OCE_EDCA1REFB_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA1REFB_RO)
#define AG_MG_REGS_OCE_EDCA_REFB_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA_REFB_RO)
#define AG_MG_REGS_OCE_EDCA5REFA_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA5REFA_RO)
#define AG_MG_REGS_OCE_EDCA4REFA_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA4REFA_RO)
#define AG_MG_REGS_OCE_EDCA3REFA_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA3REFA_RO)
#define AG_MG_REGS_OCE_EDCA2REFA_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA2REFA_RO)
#define AG_MG_REGS_OCE_EDCA1REFA_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA1REFA_RO)
#define AG_MG_REGS_OCE_EDCA_REFA_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA_REFA_RO)
#define AG_MG_REGS_OCE_EDCA_XABE_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_EDCA_XABE_RO)
#define AG_MG_REGS_OCE_EDCA5CTRL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA5CTRL_RO)
#define AG_MG_REGS_OCE_EDCA4CTRL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA4CTRL_RO)
#define AG_MG_REGS_OCE_EDCA3CTRL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA3CTRL_RO)
#define AG_MG_REGS_OCE_EDCA2CTRL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA2CTRL_RO)
#define AG_MG_REGS_OCE_EDCA1CTRL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA1CTRL_RO)
#define AG_MG_REGS_OCE_EDCA_CTRL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EDCA_CTRL_RO)
#define AG_MG_REGS_OCE_ECFGH_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ECFGH_RO)
#define AG_MG_REGS_OCE_ECFGL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ECFGL_RO)
#define AG_MG_REGS_OCE_CORECFG_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_CORECFG_RO)
#define AG_MG_REGS_OCE_SYSREV_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_SYSREV_RO)
#define AG_MG_REGS_OCE_PC_MMU_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_PC_MMU_RO)
#define AG_MG_REGS_OCE_PC_DETECT_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_PC_DETECT_RO)
#define AG_MG_REGS_OCE_PC_EXCP_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_PC_EXCP_RO)
#define AG_MG_REGS_OCE_EE_CTRL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EE_CTRL_RO)
#define AG_MG_REGS_OCE_ETRSMTH_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ETRSMTH_RO)
#define AG_MG_REGS_OCE_ETRSMTL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ETRSMTL_RO)
#define AG_MG_REGS_OCE_ERCVH_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ERCVH_RO)
#define AG_MG_REGS_OCE_ERCVL_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ERCVL_RO)
#define AG_MG_REGS_OCE_EMCR_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_EMCR_RO)
#define AG_MG_REGS_OCE_ESR_RA	AG_MG_REGS_OCE_REG(AG_MG_REGS_OCE_ESR_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_OCE_REGS_S
{
	ag_mg_regs_oce_esr_u		oce_esr ;
	ag_mg_regs_oce_emcr_u		oce_emcr ;
	ag_mg_regs_oce_ercvl_u		oce_ercvl ;
	ag_mg_regs_oce_ercvh_u		oce_ercvh ;
	ag_mg_regs_oce_etrsmtl_u	oce_etrsmtl ;
	ag_mg_regs_oce_etrsmth_u	oce_etrsmth ;
	ag_mg_regs_oce_ee_ctrl_u	oce_ee_ctrl ;
	ag_mg_regs_oce_pc_excp_u	oce_pc_excp ;
	ag_mg_regs_register		FILL0[2] ;
	ag_mg_regs_oce_pc_detect_u	oce_pc_detect ;
	ag_mg_regs_oce_pc_mmu_u		oce_pc_mmu ;
	ag_mg_regs_sysrev_u		sysrev ;
	ag_mg_regs_oce_corecfg_u	oce_corecfg ;
	ag_mg_regs_oce_ecfgl_u		oce_ecfgl ;
	ag_mg_regs_oce_ecfgh_u		oce_ecfgh ;
	ag_mg_regs_oce_edca_ctrl_u	oce_edca_ctrl[6] ;
	ag_mg_regs_edca_xabe_u		edca_xabe ;
	ag_mg_regs_register		FILL1 ;
	ag_mg_regs_oce_edca_refa_u	oce_edca_refa[6] ;
	ag_mg_regs_register		FILL2[2] ;
	ag_mg_regs_oce_edca_refb_u	oce_edca_refb[6] ;
	ag_mg_regs_register		FILL3[2] ;
	ag_mg_regs_oce_edca_refid_u	oce_edca_refid[6] ;
	ag_mg_regs_register		FILL4[2] ;
	ag_mg_regs_oce_edca_mask_u	oce_edca_mask[6] ;
	ag_mg_regs_register		FILL5[2] ;
	ag_mg_regs_oce_edcd_ctrl_u	oce_edcd_ctrl ;
	ag_mg_regs_oce_edcd_ref_u	oce_edcd_ref ;
	ag_mg_regs_oce_edcd_mask_u	oce_edcd_mask ;
	ag_mg_regs_register		FILL6[5] ;
	ag_mg_regs_oce_ecnt_ctrl_u	oce_ecnt_ctrl ;
	ag_mg_regs_oce_ecnt_val_u	oce_ecnt_val ;
	ag_mg_regs_oce_ecnt_ext_u	oce_ecnt_ext ;
	ag_mg_regs_register		FILL7[5] ;
	ag_mg_regs_oce_esel_ctrl_u	oce_esel_ctrl ;
	ag_mg_regs_oce_esel_dm_u	oce_esel_dm ;
	ag_mg_regs_oce_esel_di_u	oce_esel_di ;
	ag_mg_regs_esel_adm_u		esel_adm ;
	ag_mg_regs_oce_esel_etb_u	oce_esel_etb ;
	ag_mg_regs_oce_esel_dtb_u	oce_esel_dtb ;
	ag_mg_regs_register		FILL8[2] ;
	ag_mg_regs_oce_tb_ctrl_u	oce_tb_ctrl ;
	ag_mg_regs_oce_tb_rd_u		oce_tb_rd ;
	ag_mg_regs_oce_tb_wr_u		oce_tb_wr ;
	ag_mg_regs_oce_tb_buff_u	oce_tb_buff ;
	ag_mg_regs_register		FILL9[40] ;
	ag_mg_regs_oce_rd_status_u	oce_rd_status ;
} ag_mg_regs_oce_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_oce_reg_s *oce_regs =
*       (volatile ag_mg_regs_oce_reg_s *)AG_MG_REGS_OCE_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_oce.h,v $
Revision 1.2  2017/07/28 07:58:34  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:28  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

