/* $Id: ag_mg_regs_dmac31.h,v 1.2 2017/07/28 07:58:34 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_dmac31.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_dmac31.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_dmac31.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of Agere Systems Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * Each DSP subsystem (DSS) contains a single 2-channel DMA Controller (DMAC)
 * for managing the movement of data blocks within the system. There are also
 * two shared 2-channel DMACs directly connected to the Data Bus Matrix (DBM).
 * With the exception of the ability of the DSS DMACs to access the Local memory
 * of the DSS that contains it through a dedicated port, without genrating any DBM
 * traffic, all of the DMA Controllers within the device are functionally identical. 
 *
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *
 *  AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER
 *  AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER
 *  AG_MG_REGS_DMA_SOFTWARE_RESET_REGISTER
 *  AG_MG_REGS_DMA_SRCXCOUNT_CH
 *  AG_MG_REGS_DMA_SRCYCOUNT_CH
 *  AG_MG_REGS_DMA_SRCXMOD_CH
 *  AG_MG_REGS_DMA_SRCYMOD_CH
 *  AG_MG_REGS_DMA_SRCCURADDR_CH
 *  AG_MG_REGS_DMA_SRCACCESS_CH
 *  AG_MG_REGS_DMA_SRCDATAMSK_CH
 *  AG_MG_REGS_DMA_DSTXCOUNT_CH
 *  AG_MG_REGS_DMA_DSTYCOUNT_CH
 *  AG_MG_REGS_DMA_DSTXMOD_CH
 *  AG_MG_REGS_DMA_DSTYMOD_CH
 *  AG_MG_REGS_DMA_DSTCURADDR_CH
 *  AG_MG_REGS_DMA_DSTACCESS_CH
 *  AG_MG_REGS_DMA_NEXTDESCPTR_CH
 *  AG_MG_REGS_DMA_CONFREG_CH
 *  AG_MG_REGS_DMA_STATUSREG_CH
 *  AG_MG_REGS_DMA_DMACOUNTER_CH
 *  AG_MG_REGS_DMA_DMACOUNTER2_CH
 *  AG_MG_REGS_DMA_MODECONFIGREG_CH
 *  AG_MG_REGS_DMA_CURDESCPTR_CH
 *  AG_MG_REGS_DMA_PREVDESCPTR_CH
 *
 * Prefix naming conventions :
 *   AG_MG_REGS_XXX_RA : register/memory physical address
 *   AG_MG_REGS_XXX_RO : register/memory address offset
 *   AG_MG_REGS_XXX_RM : register mask
 *   AG_MG_REGS_XXX_BO : bit/field offset from LSB
 *   AG_MG_REGS_XXX_BM : bit/field mask
 *   AG_MG_REGS_XXX_U  : bitfields in C union typedef
 *   AG_MG_REGS_XXX_S  : registers in C struct typedef
 *   AG_MG_REGS_XX_RPT : number of identical registers in array
 *   AG_MG_REGS_XX_IVL : interval between registers in array
 *
 * NOTE: user may redefine ag_mg_regs_register
 *       in ag_mg_regs_regops.h if necessary
 * NOTE: access mode of individual bit fields matches that
 *       of containing register unless indicated otherwise
 */

#ifndef AG_MG_REGS_DMAC31_REGISTERS_H
#define AG_MG_REGS_DMAC31_REGISTERS_H

#include "ag_mg_regs_regops.h"

/*
 * Generated by HSI Designer release 2.3.5.
 */

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_RO 0x00000F04
#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_BM 0xFFF80003

#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_DESC_PAGE_BM        0xFFF00000
#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_DESC_PAGE_BO        20

#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_DESC_SPACE_BM       0x00080000
#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_DESC_SPACE_BO       19

#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_DMA_DBG_RESUME_BM   0x00010000
#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_DMA_DBG_RESUME_BO   16

#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_CH1_INT_LEVEL_BM    0x00000002
#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_CH1_INT_LEVEL_BO    1

#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_CH_INT_LEVEL_BM     0x00000001
#define AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_CH_INT_LEVEL_BO     0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_U
{
    struct
    {
        ag_mg_regs_register
            ch_int_level : 1,
            ch1_int_level : 1,
            fill0 : 14,
            dbg_resume : 1,
            fill1 : 2,
            desc_space : 1,
            desc_page : 12;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_general_configuration_register_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_RO 0x00000F00
#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_BM 0x0E03000F

#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_PAUSE_ACK_N_BM      0x02000000
#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_PAUSE_ACK_N_BO      25

#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_CH1_ERROR_FLOW_BM   0x00020000
#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_CH1_ERROR_FLOW_BO   17

#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_CH0_ERROR_FLOW_BM   0x00010000
#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_CH0_ERROR_FLOW_BO   16

#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_CH1_ACTIVE_BM       0x00000004
#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_CH1_ACTIVE_BO       2

#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_CH0_ACTIVE_BM       0x00000001
#define AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_CH0_ACTIVE_BO       0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_U
{
    struct
    {
        ag_mg_regs_register
            ch0_active : 1,
            fill0 : 1,
            ch1_active : 1,
            fill1 : 13,
            ch0_error_flow : 1,
            ch1_error_flow : 1,
            fill2 : 7,
            pause_ack_n : 1,
            fill3 : 6;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_general_status_register_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_DMA_SOFTWARE_RESET_REGISTER_RO 0x00000F08
#define AG_MG_REGS_DMA_SOFTWARE_RESET_REGISTER_BM 0x00000000

#define AG_MG_REGS_DMA_SOFTWARE_RESET_REGISTER_SOFT_RESET_BM         0xFFFFFFFF
#define AG_MG_REGS_DMA_SOFTWARE_RESET_REGISTER_SOFT_RESET_BO         0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_SOFTWARE_RESET_REGISTER_U
{
    struct
    {
        ag_mg_regs_register
            soft_reset;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_software_reset_register_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_SRCXCOUNT_CH_RO 0x00000000
#define AG_MG_REGS_DMA_SRCXCOUNT_CH_BM 0x0000FFFF

#define AG_MG_REGS_DMA_SRCXCOUNT_CH_XCOUNTER_BM         0x0000FFFF
#define AG_MG_REGS_DMA_SRCXCOUNT_CH_XCOUNTER_BO         0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_SRCXCOUNT_CH_U
{
    struct
    {
        ag_mg_regs_register
            xcounter : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_srcxcount_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_SRCYCOUNT_CH_RO 0x00000004
#define AG_MG_REGS_DMA_SRCYCOUNT_CH_BM 0x0000FFFF

#define AG_MG_REGS_DMA_SRCYCOUNT_CH_YCOUNTER_BM         0x0000FFFF
#define AG_MG_REGS_DMA_SRCYCOUNT_CH_YCOUNTER_BO         0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_SRCYCOUNT_CH_U
{
    struct
    {
        ag_mg_regs_register
            ycounter : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_srcycount_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_SRCXMOD_CH_RO  0x00000008
#define AG_MG_REGS_DMA_SRCXMOD_CH_BM  0xFFFFFFFF

#define AG_MG_REGS_DMA_SRCXMOD_CH_XMODIFIER_BM        0xFFFFFFFF
#define AG_MG_REGS_DMA_SRCXMOD_CH_XMODIFIER_BO        0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_SRCXMOD_CH_U
{
    struct
    {
        ag_mg_regs_register
            xmodifier;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_srcxmod_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_SRCYMOD_CH_RO  0x0000000C
#define AG_MG_REGS_DMA_SRCYMOD_CH_BM  0xFFFFFFFF

#define AG_MG_REGS_DMA_SRCYMOD_CH_YMODIFIER_BM        0xFFFFFFFF
#define AG_MG_REGS_DMA_SRCYMOD_CH_YMODIFIER_BO        0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_SRCYMOD_CH_U
{
    struct
    {
        ag_mg_regs_register
            ymodifier;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_srcymod_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_SRCCURADDR_CH_RO 0x00000010
#define AG_MG_REGS_DMA_SRCCURADDR_CH_BM 0xFFFFFFFF

#define AG_MG_REGS_DMA_SRCCURADDR_CH_CURRENTSOURCEADDRESS_BM 0xFFFFFFFF
#define AG_MG_REGS_DMA_SRCCURADDR_CH_CURRENTSOURCEADDRESS_BO 0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_SRCCURADDR_CH_U
{
    struct
    {
        ag_mg_regs_register
            currentsourceaddress;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_srccuraddr_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_SRCACCESS_CH_RO 0x00000014
#define AG_MG_REGS_DMA_SRCACCESS_CH_BM 0x00007FFF

#define AG_MG_REGS_DMA_SRCACCESS_CH_TAIL_LENGTH_BM      0x00007800
#define AG_MG_REGS_DMA_SRCACCESS_CH_TAIL_LENGTH_BO      11

#define AG_MG_REGS_DMA_SRCACCESS_CH_ROTATOR_LENGTH_BM   0x000007C0
#define AG_MG_REGS_DMA_SRCACCESS_CH_ROTATOR_LENGTH_BO   6

#define AG_MG_REGS_DMA_SRCACCESS_CH_SRC_SIZE_BM         0x00000038
#define AG_MG_REGS_DMA_SRCACCESS_CH_SRC_SIZE_BO         3

#define AG_MG_REGS_DMA_SRCACCESS_CH_SRC_BURST_BM        0x00000007
#define AG_MG_REGS_DMA_SRCACCESS_CH_SRC_BURST_BO        0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_SRCACCESS_CH_U
{
    struct
    {
        ag_mg_regs_register
            src_burst : 3,
            src_size : 3,
            rotator_length : 5,
            tail_length : 4,
            fill0 : 17;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_srcaccess_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_SRCDATAMSK_CH_RO 0x00000018
#define AG_MG_REGS_DMA_SRCDATAMSK_CH_BM 0xFFFFFFFF

#define AG_MG_REGS_DMA_SRCDATAMSK_CH_DATA_MASK_BM        0xFFFFFFFF
#define AG_MG_REGS_DMA_SRCDATAMSK_CH_DATA_MASK_BO        0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_SRCDATAMSK_CH_U
{
    struct
    {
        ag_mg_regs_register
            data_mask;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_srcdatamsk_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_DSTXCOUNT_CH_RO 0x0000001C
#define AG_MG_REGS_DMA_DSTXCOUNT_CH_BM 0x0000FFFF

#define AG_MG_REGS_DMA_DSTXCOUNT_CH_DESTINATIONXCOUNT_BM 0x0000FFFF
#define AG_MG_REGS_DMA_DSTXCOUNT_CH_DESTINATIONXCOUNT_BO 0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_DSTXCOUNT_CH_U
{
    struct
    {
        ag_mg_regs_register
            destinationxcount : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_dstxcount_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_DSTYCOUNT_CH_RO 0x00000020
#define AG_MG_REGS_DMA_DSTYCOUNT_CH_BM 0x0000FFFF

#define AG_MG_REGS_DMA_DSTYCOUNT_CH_DESTINATIONYCOUNT_BM 0x0000FFFF
#define AG_MG_REGS_DMA_DSTYCOUNT_CH_DESTINATIONYCOUNT_BO 0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_DSTYCOUNT_CH_U
{
    struct
    {
        ag_mg_regs_register
            destinationycount : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_dstycount_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_DSTXMOD_CH_RO  0x00000024
#define AG_MG_REGS_DMA_DSTXMOD_CH_BM  0xFFFFFFFF

#define AG_MG_REGS_DMA_DSTXMOD_CH_XMODIFIER_BM        0xFFFFFFFF
#define AG_MG_REGS_DMA_DSTXMOD_CH_XMODIFIER_BO        0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_DSTXMOD_CH_U
{
    struct
    {
        ag_mg_regs_register
            xmodifier;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_dstxmod_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_DSTYMOD_CH_RO  0x00000028
#define AG_MG_REGS_DMA_DSTYMOD_CH_BM  0xFFFFFFFF

#define AG_MG_REGS_DMA_DSTYMOD_CH_YMODIFIER_BM        0xFFFFFFFF
#define AG_MG_REGS_DMA_DSTYMOD_CH_YMODIFIER_BO        0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_DSTYMOD_CH_U
{
    struct
    {
        ag_mg_regs_register
            ymodifier;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_dstymod_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_DSTCURADDR_CH_RO 0x0000002C
#define AG_MG_REGS_DMA_DSTCURADDR_CH_BM 0xFFFFFFFF

#define AG_MG_REGS_DMA_DSTCURADDR_CH_CURRENTDESTINATIONADDRESS_BM 0xFFFFFFFF
#define AG_MG_REGS_DMA_DSTCURADDR_CH_CURRENTDESTINATIONADDRESS_BO 0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_DSTCURADDR_CH_U
{
    struct
    {
        ag_mg_regs_register
            currentdestinationaddress;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_dstcuraddr_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_DSTACCESS_CH_RO 0x00000030
#define AG_MG_REGS_DMA_DSTACCESS_CH_BM 0x0000003F

#define AG_MG_REGS_DMA_DSTACCESS_CH_DST_SIZE_BM         0x00000038
#define AG_MG_REGS_DMA_DSTACCESS_CH_DST_SIZE_BO         3

#define AG_MG_REGS_DMA_DSTACCESS_CH_DST_BURST_BM        0x00000007
#define AG_MG_REGS_DMA_DSTACCESS_CH_DST_BURST_BO        0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_DSTACCESS_CH_U
{
    struct
    {
        ag_mg_regs_register
            dst_burst : 3,
            dst_size : 3,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_dstaccess_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_NEXTDESCPTR_CH_RO 0x00000034
#define AG_MG_REGS_DMA_NEXTDESCPTR_CH_BM 0xFFFFFFF3

#define AG_MG_REGS_DMA_NEXTDESCPTR_CH_NEXTDESCRIPTORPAGE_BM 0xFFF00000
#define AG_MG_REGS_DMA_NEXTDESCPTR_CH_NEXTDESCRIPTORPAGE_BO 20

#define AG_MG_REGS_DMA_NEXTDESCPTR_CH_NEXTDESCRIPTORADDRESS_BM 0x000FFFF0
#define AG_MG_REGS_DMA_NEXTDESCPTR_CH_NEXTDESCRIPTORADDRESS_BO 4

#define AG_MG_REGS_DMA_NEXTDESCPTR_CH_NEXT_DESC_SPACE_BM         0x00000008
#define AG_MG_REGS_DMA_NEXTDESCPTR_CH_NEXT_DESC_SPACE_BO         3

#define AG_MG_REGS_DMA_NEXTDESCPTR_CH_NEXTDESCRIPTORFAMILY_BM 0x00000003
#define AG_MG_REGS_DMA_NEXTDESCPTR_CH_NEXTDESCRIPTORFAMILY_BO 0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_NEXTDESCPTR_CH_U
{
    struct
    {
        ag_mg_regs_register
            nextdescriptorfamily : 2,
            fill0 : 1,
            nextdescriptorspace : 1,
            nextdescriptoraddress : 16,
            nextdescriptorpage : 12;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_nextdescptr_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_CONFREG_CH_RO  0x00000038
#define AG_MG_REGS_DMA_CONFREG_CH_BM  0x04FFFBFF

#define AG_MG_REGS_DMA_CONFREG_CH_DST_SPACE_BM        0x04000000
#define AG_MG_REGS_DMA_CONFREG_CH_DST_SPACE_BO        26

#define AG_MG_REGS_DMA_CONFREG_CH_SRC_SPACE_BM        0x00800000
#define AG_MG_REGS_DMA_CONFREG_CH_SRC_SPACE_BO        23

#define AG_MG_REGS_DMA_CONFREG_CH_DMA_EXT_ACCESS_PRIOR_BM 0x00400000
#define AG_MG_REGS_DMA_CONFREG_CH_DMA_EXT_ACCESS_PRIOR_BO 22

#define AG_MG_REGS_DMA_CONFREG_CH_DMA_CORE_PRIORITY_ROW_BM 0x00200000
#define AG_MG_REGS_DMA_CONFREG_CH_DMA_CORE_PRIORITY_ROW_BO 21

#define AG_MG_REGS_DMA_CONFREG_CH_DMA_CORE_PRIORITY_BM 0x00100000
#define AG_MG_REGS_DMA_CONFREG_CH_DMA_CORE_PRIORITY_BO 20

#define AG_MG_REGS_DMA_CONFREG_CH_CH_FULL_PRIORITY_BM 0x00080000
#define AG_MG_REGS_DMA_CONFREG_CH_CH_FULL_PRIORITY_BO 19

#define AG_MG_REGS_DMA_CONFREG_CH_CHANNELPRIORITY_BM  0x00070000
#define AG_MG_REGS_DMA_CONFREG_CH_CHANNELPRIORITY_BO  16

#define AG_MG_REGS_DMA_CONFREG_CH_LAST_BLOCK_BM       0x00008000
#define AG_MG_REGS_DMA_CONFREG_CH_LAST_BLOCK_BO       15

#define AG_MG_REGS_DMA_CONFREG_CH_CLEAR_FIFO_BM       0x00004000
#define AG_MG_REGS_DMA_CONFREG_CH_CLEAR_FIFO_BO       14

#define AG_MG_REGS_DMA_CONFREG_CH_START_MEM_LOAD_BM   0x00002000
#define AG_MG_REGS_DMA_CONFREG_CH_START_MEM_LOAD_BO   13

#define AG_MG_REGS_DMA_CONFREG_CH_DMA_EXT_ACCESS_PRIOR_EN_BM 0x00001000
#define AG_MG_REGS_DMA_CONFREG_CH_DMA_EXT_ACCESS_PRIOR_EN_BO 12

#define AG_MG_REGS_DMA_CONFREG_CH_STOP_DST_EOB_BM     0x00000800
#define AG_MG_REGS_DMA_CONFREG_CH_STOP_DST_EOB_BO     11

#define AG_MG_REGS_DMA_CONFREG_CH_NEXT_DESCR_SPACE_BM 0x00000200
#define AG_MG_REGS_DMA_CONFREG_CH_NEXT_DESCR_SPACE_BO 9

#define AG_MG_REGS_DMA_CONFREG_CH_FULL_NEXT_DESCR_ADDR_BM 0x00000100
#define AG_MG_REGS_DMA_CONFREG_CH_FULL_NEXT_DESCR_ADDR_BO 8

#define AG_MG_REGS_DMA_CONFREG_CH_INT_DST_EOT_BM      0x00000080
#define AG_MG_REGS_DMA_CONFREG_CH_INT_DST_EOT_BO      7

#define AG_MG_REGS_DMA_CONFREG_CH_INT_DST_EOB_BM      0x00000040
#define AG_MG_REGS_DMA_CONFREG_CH_INT_DST_EOB_BO      6

#define AG_MG_REGS_DMA_CONFREG_CH_WAIT_FOR_COUNTER_2_BM 0x00000020
#define AG_MG_REGS_DMA_CONFREG_CH_WAIT_FOR_COUNTER_2_BO 5

#define AG_MG_REGS_DMA_CONFREG_CH_COUNTER_2_RESET_BM  0x00000010
#define AG_MG_REGS_DMA_CONFREG_CH_COUNTER_2_RESET_BO  4

#define AG_MG_REGS_DMA_CONFREG_CH_WAIT_FOR_COUNTER_1_BM 0x00000008
#define AG_MG_REGS_DMA_CONFREG_CH_WAIT_FOR_COUNTER_1_BO 3

#define AG_MG_REGS_DMA_CONFREG_CH_COUNTER_1_RESET_BM  0x00000004
#define AG_MG_REGS_DMA_CONFREG_CH_COUNTER_1_RESET_BO  2

#define AG_MG_REGS_DMA_CONFREG_CH_TX_EN_BM            0x00000002
#define AG_MG_REGS_DMA_CONFREG_CH_TX_EN_BO            1

#define AG_MG_REGS_DMA_CONFREG_CH_CHAN_EN_BM          0x00000001
#define AG_MG_REGS_DMA_CONFREG_CH_CHAN_EN_BO          0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_CONFREG_CH_U
{
    struct
    {
        ag_mg_regs_register
            chan_en : 1,
            tx_en : 1,
            counter_1_reset : 1,
            wait_for_counter_1 : 1,
            counter_2_reset : 1,
            wait_for_counter_2 : 1,
            int_dst_eob : 1,
            int_dst_eot : 1,
            full_next_descr_addr : 1,
            next_descr_space : 1,
            fill0 : 1,
            stop_dst_eob : 1,
            dma_ext_access_prior_en : 1,
            start_mem_load : 1,
            clear_fifo : 1,
            last_block : 1,
            channelpriority : 3,
            ch_full_priority : 1,
            dma_core_priority : 1,
            dma_core_priority_row : 1,
            dma_ext_access_prior : 1,
            src_space : 1,
            fill1 : 2,
            dst_space : 1,
            fill2 : 5;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_confreg_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_STATUSREG_CH_RO 0x0000003C
#define AG_MG_REGS_DMA_STATUSREG_CH_BM 0x007F73BF

#define AG_MG_REGS_DMA_STATUSREG_CH_CURR_FAMILY_BM      0x00600000
#define AG_MG_REGS_DMA_STATUSREG_CH_CURR_FAMILY_BO      21

#define AG_MG_REGS_DMA_STATUSREG_CH_WAITING_FOR_COUNTER_2_BM 0x00100000
#define AG_MG_REGS_DMA_STATUSREG_CH_WAITING_FOR_COUNTER_2_BO 20

#define AG_MG_REGS_DMA_STATUSREG_CH_COUNTER_2_OVERFLOW_BM 0x00080000
#define AG_MG_REGS_DMA_STATUSREG_CH_COUNTER_2_OVERFLOW_BO 19

#define AG_MG_REGS_DMA_STATUSREG_CH_WAITING_FOR_COUNTER_1_BM 0x00040000
#define AG_MG_REGS_DMA_STATUSREG_CH_WAITING_FOR_COUNTER_1_BO 18

#define AG_MG_REGS_DMA_STATUSREG_CH_COUNTER_1_OVERFLOW_BM 0x00020000
#define AG_MG_REGS_DMA_STATUSREG_CH_COUNTER_1_OVERFLOW_BO 17

#define AG_MG_REGS_DMA_STATUSREG_CH_CH_PAUSE_WR_EN_BM   0x00010000
#define AG_MG_REGS_DMA_STATUSREG_CH_CH_PAUSE_WR_EN_BO   16

#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ERROR_ACC_DL_BM  0x00004000
#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ERROR_ACC_DL_BO  14

#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ERROR_ACC_DST_BM 0x00002000
#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ERROR_ACC_DST_BO 13

#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ERROR_ACC_SRC_BM 0x00001000
#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ERROR_ACC_SRC_BO 12

#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ERR_FIFO_OVERFLOW_BM 0x00000200
#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ERR_FIFO_OVERFLOW_BO 9

#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ERR_FIFO_UNDERFLOW_BM 0x00000100
#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ERR_FIFO_UNDERFLOW_BO 8

#define AG_MG_REGS_DMA_STATUSREG_CH_CH_PAUSE_BM         0x00000080
#define AG_MG_REGS_DMA_STATUSREG_CH_CH_PAUSE_BO         7

#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ACTIVE_BM        0x00000010
#define AG_MG_REGS_DMA_STATUSREG_CH_CH_ACTIVE_BO        4

#define AG_MG_REGS_DMA_STATUSREG_CH_TRANSFER_COMPLETED_BM 0x00000008
#define AG_MG_REGS_DMA_STATUSREG_CH_TRANSFER_COMPLETED_BO 3

#define AG_MG_REGS_DMA_STATUSREG_CH_BLOCK_COMPLETED_BM  0x00000004
#define AG_MG_REGS_DMA_STATUSREG_CH_BLOCK_COMPLETED_BO  2

#define AG_MG_REGS_DMA_STATUSREG_CH_UNALIGNED_READ_STATUS_BM 0x00000002
#define AG_MG_REGS_DMA_STATUSREG_CH_UNALIGNED_READ_STATUS_BO 1

#define AG_MG_REGS_DMA_STATUSREG_CH_UNALIGNED_WRITE_STATUS_BM 0x00000001
#define AG_MG_REGS_DMA_STATUSREG_CH_UNALIGNED_WRITE_STATUS_BO 0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_STATUSREG_CH_U
{
    struct
    {
        ag_mg_regs_register
            unaligned_write_status : 1,
            unaligned_read_status : 1,
            block_completed : 1,
            transfer_completed : 1,
            ch_active : 1,
            fill0 : 2,
            ch_pause : 1,
            ch_err_fifo_underflow : 1,
            ch_err_fifo_overflow : 1,
            fill1 : 2,
            ch_error_acc_src : 1,
            ch_error_acc_dst : 1,
            ch_error_acc_dl : 1,
            fill2 : 1,
            ch_pause_wr_en : 1,
            counter_1_overflow : 1,
            waiting_for_counter_1 : 1,
            counter_2_overflow : 1,
            waiting_for_counter_2 : 1,
            curr_family : 2,
            fill3 : 9;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_statusreg_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_DMACOUNTER_CH_RO 0x00000040
#define AG_MG_REGS_DMA_DMACOUNTER_CH_BM 0x0000FFFF

#define AG_MG_REGS_DMA_DMA_COUNTER_CH_COUNTER_BM          0x0000FFFF
#define AG_MG_REGS_DMA_DMA_COUNTER_CH_COUNTER_BO          0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_DMACOUNTER_CH_U
{
    struct
    {
        ag_mg_regs_register
            counter : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_dmacounter_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_DMACOUNTER2_CH_RO 0x00000044
#define AG_MG_REGS_DMA_DMACOUNTER2_CH_BM 0x0000FFFF

#define AG_MG_REGS_DMA_DMACOUNTER2_CH_COUNTER_BM          0x0000FFFF
#define AG_MG_REGS_DMA_DMACOUNTER2_CH_COUNTER_BO          0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_DMACOUNTER2_CH_U
{
    struct
    {
        ag_mg_regs_register
            counter : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_dmacounter2_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DMA_MODECONFIGREG_CH_RO 0x00000048
#define AG_MG_REGS_DMA_MODECONFIGREG_CH_BM 0x000001FF

/* this field not used (needed) in V1.1 device which has 4x the FIFO space */
#define AG_MG_REGS_DMA_MODECONFIGREG_CH_REQUEST_AHEAD_V10_BM    0x000001E0
#define AG_MG_REGS_DMA_MODECONFIGREG_CH_REQUEST_AHEAD_V10_BO    5

#define AG_MG_REGS_DMA_MODECONFIGREG_CH_STOP_UNALIGN_LEGAL_SRC_BM 0x00000010
#define AG_MG_REGS_DMA_MODECONFIGREG_CH_STOP_UNALIGN_LEGAL_SRC_BO 4

#define AG_MG_REGS_DMA_MODECONFIGREG_CH_COUNTER_2_SOURCE_BM 0x00000008
#define AG_MG_REGS_DMA_MODECONFIGREG_CH_COUNTER_2_SOURCE_BO 3

#define AG_MG_REGS_DMA_MODECONFIGREG_CH_COUNTER_2_RESET_MODE_BM 0x00000004
#define AG_MG_REGS_DMA_MODECONFIGREG_CH_COUNTER_2_RESET_MODE_BO 2

#define AG_MG_REGS_DMA_MODECONFIGREG_CH_COUNTER_1_SOURCE_BM 0x00000002
#define AG_MG_REGS_DMA_MODECONFIGREG_CH_COUNTER_1_SOURCE_BO 1

#define AG_MG_REGS_DMA_MODECONFIGREG_CH_COUNTER_1_RESET_MODE_BM 0x00000001
#define AG_MG_REGS_DMA_MODECONFIGREG_CH_COUNTER_1_RESET_MODE_BO 0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_MODECONFIGREG_CH_U
{
    struct
    {
        ag_mg_regs_register
            counter_1_reset_mode : 1,
            counter_1_source : 1,
            counter_2_reset_mode : 1,
            counter_2_source : 1,
            stop_unalign_legal_src : 1,
            request_ahead_v10 : 4,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_modeconfigreg_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DMA_CURDESCPTR_CH_RO 0x0000004C
#define AG_MG_REGS_DMA_CURDESCPTR_CH_BM 0xFFFFFFF1

#define AG_MG_REGS_DMA_CURDESCPTR_CH_DESCRIPTOR_PAGE_BM  0xFFF00000
#define AG_MG_REGS_DMA_CURDESCPTR_CH_DESCRIPTOR_PAGE_BO  20

#define AG_MG_REGS_DMA_CURDESCPTR_CH_DESCRIPTOR_ADDRESS_BM 0x000FFFF0
#define AG_MG_REGS_DMA_CURDESCPTR_CH_DESCRIPTOR_ADDRESS_BO 4

#define AG_MG_REGS_DMA_CURDESCPTR_CH_DESCR_SPACE_BM      0x00000008
#define AG_MG_REGS_DMA_CURDESCPTR_CH_DESCR_SPACE_BO      3

#define AG_MG_REGS_DMA_CURDESCPTR_CH_DESCR_FAMILY_BM      0x00000003
#define AG_MG_REGS_DMA_CURDESCPTR_CH_DESCR_FAMILY_BO      0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_CURDESCPTR_CH_U
{
    struct
    {
        ag_mg_regs_register
			descr_family : 2,
			fill0 : 1,
            descr_space : 1,
            descriptor_address : 16,
            descriptor_page : 12;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_curdescptr_ch_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DMA_PREVDESCPTR_CH_RO 0x00000050
#define AG_MG_REGS_DMA_PREVDESCPTR_CH_BM 0xFFFFFFFB

#define AG_MG_REGS_DMA_PREVDESCPTR_CH_DESCRIPTOR_PAGE_BM  0xFFF00000
#define AG_MG_REGS_DMA_PREVDESCPTR_CH_DESCRIPTOR_PAGE_BO  20

#define AG_MG_REGS_DMA_PREVDESCPTR_CH_DESCRIPTOR_ADDRESS_BM 0x000FFFF0
#define AG_MG_REGS_DMA_PREVDESCPTR_CH_DESCRIPTOR_ADDRESS_BO 4

#define AG_MG_REGS_DMA_PREVDESCPTR_CH_DESCR_SPACE_BM      0x00000008
#define AG_MG_REGS_DMA_PREVDESCPTR_CH_DESCR_SPACE_BO      3

#define AG_MG_REGS_DMA_PREVDESCPTR_CH_DESCR_FAMILY_BM     0x00000003
#define AG_MG_REGS_DMA_PREVDESCPTR_CH_DESCR_FAMILY_BO     0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DMA_PREVDESCPTR_CH_U
{
    struct
    {
        ag_mg_regs_register
            descr_family : 2,
            fill0 : 1,
            descr_space : 1,
            descriptor_address : 16,
            descriptor_page : 12;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dma_prevdescptr_ch_u;
#endif


/*
 * Physical register addresses (for ARMs accessing various dmac31s)
 */

#define AG_MG_REGS_DMAC31_DSS0_BASE			0x98001000
#define AG_MG_REGS_DMAC31_DSS1_BASE			0x98003000
#define AG_MG_REGS_DMAC31_DSS2_BASE			0x98061000
#define AG_MG_REGS_DMAC31_DSS3_BASE			0x98063000
#define AG_MG_REGS_DMAC31_G0_BASE			0x98064000
#define AG_MG_REGS_DMAC31_G1_BASE			0x98065000

/*
 * Physical register addresses (for DSSs accessing their own dmac31s)
 */
#define AG_MG_REGS_DMAC31_DSS_BASE			0xCF001000

#define AG_MG_REGS_DMAC31_DMA_CH_RPT                    2
#define AG_MG_REGS_DMAC31_DMA_CH_IVL                    0x80

#define AG_MG_REGS_DMAC31_REG(base, ro)		((base)+(ro))

// NOTE: ch can range from 0 to (AG_MG_REGS_DMAC31_DMA_CH_RPT - 1)
#define AG_MG_REGS_DMAC31_DMA_CH_REG(base, ch, ro)  AG_MG_REGS_DMAC31_REG((base),((ch)*AG_MG_REGS_DMAC31_DMA_CH_IVL)+(ro))

#define AG_MG_REGS_DMAC31_DMA_GENERAL_CONFIGURATION_REGISTER_RA(p)	AG_MG_REGS_DMAC31_REG(p,AG_MG_REGS_DMA_GENERAL_CONFIGURATION_REGISTER_RO)
#define AG_MG_REGS_DMAC31_DMA_GENERAL_STATUS_REGISTER_RA(p)	AG_MG_REGS_DMAC31_REG(p,AG_MG_REGS_DMA_GENERAL_STATUS_REGISTER_RO)
#define AG_MG_REGS_DMAC31_DMA_SOFTWARE_RESET_REGISTER_RA(p)	AG_MG_REGS_DMAC31_REG(p,AG_MG_REGS_DMA_SOFTWARE_RESET_REGISTER_RO)
#define AG_MG_REGS_DMAC31_DMA_SRCXCOUNT_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_SRCXCOUNT_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_SRCYCOUNT_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_SRCYCOUNT_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_SRCXMOD_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_SRCXMOD_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_SRCYMOD_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_SRCYMOD_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_SRCCURADDR_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_SRCCURADDR_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_SRCACCESS_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_SRCACCESS_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_SRCDATAMSK_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_SRCDATAMSK_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_DSTXCOUNT_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_DSTXCOUNT_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_DSTYCOUNT_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_DSTYCOUNT_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_DSTXMOD_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_DSTXMOD_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_DSTYMOD_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_DSTYMOD_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_DSTCURADDR_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_DSTCURADDR_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_DSTACCESS_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_DSTACCESS_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_NEXTDESCPTR_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_NEXTDESCPTR_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_CONFREG_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_CONFREG_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_STATUSREG_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_STATUSREG_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_DMACOUNTER_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_DMACOUNTER_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_DMACOUNTER2_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_DMACOUNTER2_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_MODECONFIGREG_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_MODECONFIGREG_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_CURDESCPTR_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_CURDESCPTR_CH_RO)
#define AG_MG_REGS_DMAC31_DMA_PREVDESCPTR_CH_RA(b, ch)	AG_MG_REGS_DMAC31_DMA_CH_REG(b, ch, AG_MG_REGS_DMA_PREVDESCPTR_CH_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_DMAC31_CH_REGS_S
{
	ag_mg_regs_dma_srcxcount_ch_u	dma_srcxcount_ch ;
	ag_mg_regs_dma_srcycount_ch_u	dma_srcycount_ch ;
	ag_mg_regs_dma_srcxmod_ch_u	dma_srcxmod_ch ;
	ag_mg_regs_dma_srcymod_ch_u	dma_srcymod_ch ;
	ag_mg_regs_dma_srccuraddr_ch_u	dma_srccuraddr_ch ;
	ag_mg_regs_dma_srcaccess_ch_u	dma_srcaccess_ch ;
	ag_mg_regs_dma_srcdatamsk_ch_u	dma_srcdatamsk_ch ;
	ag_mg_regs_dma_dstxcount_ch_u	dma_dstxcount_ch ;
	ag_mg_regs_dma_dstycount_ch_u	dma_dstycount_ch ;
	ag_mg_regs_dma_dstxmod_ch_u	dma_dstxmod_ch ;
	ag_mg_regs_dma_dstymod_ch_u	dma_dstymod_ch ;
	ag_mg_regs_dma_dstcuraddr_ch_u	dma_dstcuraddr_ch ;
	ag_mg_regs_dma_dstaccess_ch_u	dma_dstaccess_ch ;
	ag_mg_regs_dma_nextdescptr_ch_u	dma_nextdescptr_ch ;
	ag_mg_regs_dma_confreg_ch_u	dma_confreg_ch ;
	ag_mg_regs_dma_statusreg_ch_u	dma_statusreg_ch ;
	ag_mg_regs_dma_dmacounter_ch_u	dma_dmacounter_ch ;
	ag_mg_regs_dma_dmacounter2_ch_u	dma_dmacounter2_ch ;
	ag_mg_regs_dma_modeconfigreg_ch_u	dma_modeconfigreg_ch ;
	ag_mg_regs_dma_curdescptr_ch_u	dma_curdescptr_ch ;
	ag_mg_regs_dma_prevdescptr_ch_u	dma_prevdescptr_ch ;
	ag_mg_regs_register		RESERVED_0[11] ;
} ag_mg_regs_dmac_channel_regs_s;

typedef struct AG_MG_REGS_DMAC31_REGS_S
{
	ag_mg_regs_dmac_channel_regs_s	channel[2];
	ag_mg_regs_register		RESERVED_1[896] ;
	ag_mg_regs_dma_general_status_register_u	dma_general_status_register ;
	ag_mg_regs_dma_general_configuration_register_u	dma_general_configuration_register ;
	ag_mg_regs_dma_software_reset_register_u	dma_software_reset_register ;
} ag_mg_regs_dmac31_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_dmac31_reg_s *dmacdss0_regs =
*       (volatile ag_mg_regs_dmac31_reg_s *) AG_MG_REGS_DMAC31_DSS0_BASE;
*   volatile ag_mg_regs_dmac31_reg_s *dmacdss1_regs =
*       (volatile ag_mg_regs_dmac31_reg_s *) AG_MG_REGS_DMAC31_DSS1_BASE;
*   volatile ag_mg_regs_dmac31_reg_s *dmacdss2_regs =
*       (volatile ag_mg_regs_dmac31_reg_s *) AG_MG_REGS_DMAC31_DSS2_BASE;
*   volatile ag_mg_regs_dmac31_reg_s *dmacdss3_regs =
*       (volatile ag_mg_regs_dmac31_reg_s *) AG_MG_REGS_DMAC31_DSS3_BASE;
*   volatile ag_mg_regs_dmac31_reg_s *dmacg0_regs =
*       (volatile ag_mg_regs_dmac31_reg_s *) AG_MG_REGS_DMAC31_G0_BASE;
*   volatile ag_mg_regs_dmac31_reg_s *dmacg1_regs =
*       (volatile ag_mg_regs_dmac31_reg_s *) AG_MG_REGS_DMAC31_G1_BASE;
*
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_dmac31.h,v $
Revision 1.2  2017/07/28 07:58:34  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:25  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:25  srane
Initial checkin


$Endlog$
*/

