/* $Id: ag_mg_regs_pcc.h,v 1.2 2017/07/28 07:58:34 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_pcc.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_pcc.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
* ag_mg_regs_dss_pcc.h
*
* Copyright (c) 2010 LSI Inc.  All Rights Reserved
*
* This is unpublished proprietary information of LSI Inc.
* This copyright notice does not evidence publication.
*
* The use of the software, documentation, methodologies, and other information
* contained herein is governed solely by the associated license agreements.
* Any inconsistent use shall be deemed to be a misappropriation of the
* intellectual property of LSI Inc. and treated accordingly.
*
* This file defines DSS Subsystem (DSS) Program Cache Control (PCC) registers.
*
* Register addresses defined herein are for
*  code running on the DSS accessing its own PCC.
*
* See "Physical register addresses" below for macros
* used to generate addresses for specific registers.
*
* Registers defined in this file :
 *  PCC_CTRL
 *  PCC_STAT
 *  PCC_ATTR
 *  PCC_DIRECT_START
 *  PCC_DIRECT_END
 *  PCC_INVAL_START
 *  PCC_INVAL_END
 *  PCC_UNLCK_ALL
 *  PCC_LCK0_START
 *  PCC_LCK0_END
 *  PCC_LCK1_START
 *  PCC_LCK1_END
 *  PCC_LCK2_START
 *  PCC_LCK2_END
 *  PCC_LCK3_START
 *  PCC_LCK3_END
 *  PCC_SEG0
 *  PCC_SEG1
 *  PCC_SEG2
 *  PCC_SEG3
 *  PCC_SEG_CMD
 *  PCC_FBUS
*
* Prefix naming conventions :
*   AG_MG_REGS_XXX_RA : register/memory physical address
*   AG_MG_REGS_XXX_RO : register/memory address offset
*   AG_MG_REGS_XXX_RM : register mask
*   AG_MG_REGS_XXX_BO : bit/field offset from LSB
*   AG_MG_REGS_XXX_BM : bit/field mask
*   AG_MG_REGS_XXX_U  : bitfields in C union typedef
*   AG_MG_REGS_XXX_S  : registers in C struct typedef
*   LSI_SP25XX_XX_RPT : number of identical registers in array
*   LSI_SP25XX_XX_IVL : interval between registers in array
*
* NOTE: user may redefine ag_mg_regs_register
*       in ag_mg_regs_regops.h if necessary
* NOTE: access mode of individual bit fields matches that
*       of containing register unless indicated otherwise
*/

#ifndef AG_MG_REGS_DSS_PCC_REGISTERS_H
#define AG_MG_REGS_DSS_PCC_REGISTERS_H

#include "ag_mg_regs_regops.h"


/*
 * Generated by HSI Designer release 2.3.5.
 */





/*
 * PCC_CTRL (PCC Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_CTRL_RO                         0x00000000
#define AG_MG_REGS_PCC_CTRL_RM                         0x443F443F

#define AG_MG_REGS_PCC_CTRL_CACHE_EN_BO                0
#define AG_MG_REGS_PCC_CTRL_CACHE_EN_BM                0x00000001

#define AG_MG_REGS_PCC_CTRL_FA_EN_BO                   1
#define AG_MG_REGS_PCC_CTRL_FA_EN_BM                   0x00000002

#define AG_MG_REGS_PCC_CTRL_PF_EN_BO                   2
#define AG_MG_REGS_PCC_CTRL_PF_EN_BM                   0x00000004

#define AG_MG_REGS_PCC_CTRL_PRFL_EN_BO                 3
#define AG_MG_REGS_PCC_CTRL_PRFL_EN_BM                 0x00000008

#define AG_MG_REGS_PCC_CTRL_DBG_MD_BO                  4
#define AG_MG_REGS_PCC_CTRL_DBG_MD_BM                  0x00000010

#define AG_MG_REGS_PCC_CTRL_CNCL_EN_BO                 5
#define AG_MG_REGS_PCC_CTRL_CNCL_EN_BM                 0x00000020

#define AG_MG_REGS_PCC_CTRL_DR_RD_ERR_EN_BO            10
#define AG_MG_REGS_PCC_CTRL_DR_RD_ERR_EN_BM            0x00000400

#define AG_MG_REGS_PCC_CTRL_SEG_ERR_EN_BO              14
#define AG_MG_REGS_PCC_CTRL_SEG_ERR_EN_BM              0x00004000

#define AG_MG_REGS_PCC_CTRL_CACHE_EN_MSK_BO            16
#define AG_MG_REGS_PCC_CTRL_CACHE_EN_MSK_BM            0x00010000

#define AG_MG_REGS_PCC_CTRL_FA_EN_MSK_BO               17
#define AG_MG_REGS_PCC_CTRL_FA_EN_MSK_BM               0x00020000

#define AG_MG_REGS_PCC_CTRL_PF_EN_MSK_BO               18
#define AG_MG_REGS_PCC_CTRL_PF_EN_MSK_BM               0x00040000

#define AG_MG_REGS_PCC_CTRL_PRFL_EN_MSK_BO             19
#define AG_MG_REGS_PCC_CTRL_PRFL_EN_MSK_BM             0x00080000

#define AG_MG_REGS_PCC_CTRL_DBG_MD_MSK_BO              20
#define AG_MG_REGS_PCC_CTRL_DBG_MD_MSK_BM              0x00100000

#define AG_MG_REGS_PCC_CTRL_CNCL_EN_MSK_BO             21
#define AG_MG_REGS_PCC_CTRL_CNCL_EN_MSK_BM             0x00200000

#define AG_MG_REGS_PCC_CTRL_DR_RD_ERR_EN_MSK_BO        26
#define AG_MG_REGS_PCC_CTRL_DR_RD_ERR_EN_MSK_BM        0x04000000

#define AG_MG_REGS_PCC_CTRL_SEG_ERR_EN_MSK_BO          30
#define AG_MG_REGS_PCC_CTRL_SEG_ERR_EN_MSK_BM          0x40000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            cache_en : 1,
            fa_en : 1,
            pf_en : 1,
            prfl_en : 1,
            dbg_md : 1,
            cncl_en : 1,
            fill5 : 4,
            dr_rd_err_en : 1,
            fill4 : 3,
            seg_err_en : 1,
            fill3 : 1,
            cache_en_msk : 1,
            fa_en_msk : 1,
            pf_en_msk : 1,
            prfl_en_msk : 1,
            dbg_md_msk : 1,
            cncl_en_msk : 1,
            fill2 : 4,
            dr_rd_err_en_msk : 1,
            fill1 : 3,
            seg_err_en_msk : 1,
            fill0 : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_ctrl_u;
#endif


/*
 * PCC_STAT (PCC Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_STAT_RO                         0x00000020
#define AG_MG_REGS_PCC_STAT_RM                         0x008F8100

#define AG_MG_REGS_PCC_STAT_DR_RD_ERR_BO               8
#define AG_MG_REGS_PCC_STAT_DR_RD_ERR_BM               0x00000100

#define AG_MG_REGS_PCC_STAT_LCK_RNG_BO                 15
#define AG_MG_REGS_PCC_STAT_LCK_RNG_BM                 0x00008000

#define AG_MG_REGS_PCC_STAT_INV_LN_BO                  16
#define AG_MG_REGS_PCC_STAT_INV_LN_BM                  0x00010000

#define AG_MG_REGS_PCC_STAT_INV_RNG_BO                 17
#define AG_MG_REGS_PCC_STAT_INV_RNG_BM                 0x00020000

#define AG_MG_REGS_PCC_STAT_INV_FUL_BO                 18
#define AG_MG_REGS_PCC_STAT_INV_FUL_BM                 0x00040000

#define AG_MG_REGS_PCC_STAT_BUSY_BO                    19
#define AG_MG_REGS_PCC_STAT_BUSY_BM                    0x00080000

#define AG_MG_REGS_PCC_STAT_SEG_ERR_BO                 23
#define AG_MG_REGS_PCC_STAT_SEG_ERR_BM                 0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_STAT_U
{
    struct
    {
        ag_mg_regs_register
            fill3 : 8,
            dr_rd_err : 1,
            fill2 : 6,
            lck_rng : 1,
            inv_ln : 1,
            inv_rng : 1,
            inv_ful : 1,
            busy : 1,
            fill1 : 3,
            seg_err : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_stat_u;
#endif


/*
 * Initialization value: 0x02001214  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_PCC_ATTR_RO                         0x00000040
#define AG_MG_REGS_PCC_ATTR_RM                         0x0F003FFF

#define AG_MG_REGS_PCC_ATTR_CACHE_SIZE_BO              0
#define AG_MG_REGS_PCC_ATTR_CACHE_SIZE_BM              0x0000000F

#define AG_MG_REGS_PCC_ATTR_WAYS_BO                    4
#define AG_MG_REGS_PCC_ATTR_WAYS_BM                    0x00000070

#define AG_MG_REGS_PCC_ATTR_LN_WIDTH_BO                7
#define AG_MG_REGS_PCC_ATTR_LN_WIDTH_BM                0x00000780

#define AG_MG_REGS_PCC_ATTR_PC_WIDTH_BO                11
#define AG_MG_REGS_PCC_ATTR_PC_WIDTH_BM                0x00003800

#define AG_MG_REGS_PCC_ATTR_REV_BO                     24
#define AG_MG_REGS_PCC_ATTR_REV_BM                     0x0F000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_ATTR_U
{
    struct
    {
        ag_mg_regs_register
            cache_size : 4,
            ways : 3,
            ln_width : 4,
            pc_width : 3,
            fill1 : 10,
            rev : 4,
            fill0 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_attr_u;
#endif


/*
 * Initialization value: 0x00000010  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_DIRECT_START_RO                 0x00000060
#define AG_MG_REGS_PCC_DIRECT_START_RM                 0xFFFFFFF1

#define AG_MG_REGS_PCC_DIRECT_START_EN_BO              0
#define AG_MG_REGS_PCC_DIRECT_START_EN_BM              0x00000001

#define AG_MG_REGS_PCC_DIRECT_START_AXI_ATTR_0_BO      4
#define AG_MG_REGS_PCC_DIRECT_START_AXI_ATTR_0_BM      0x00000010

#define AG_MG_REGS_PCC_DIRECT_START_AXI_ATTR_1_BO      5
#define AG_MG_REGS_PCC_DIRECT_START_AXI_ATTR_1_BM      0x00000020

#define AG_MG_REGS_PCC_DIRECT_START_AXI_ATTR_2_BO      6
#define AG_MG_REGS_PCC_DIRECT_START_AXI_ATTR_2_BM      0x00000040

#define AG_MG_REGS_PCC_DIRECT_START_AXI_ATTR_3_BO      7
#define AG_MG_REGS_PCC_DIRECT_START_AXI_ATTR_3_BM      0x00000080

#define AG_MG_REGS_PCC_DIRECT_START_ADDR_BO            8
#define AG_MG_REGS_PCC_DIRECT_START_ADDR_BM            0xFFFFFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_DIRECT_START_U
{
    struct
    {
        ag_mg_regs_register
            en : 1,
            fill0 : 3,
            axi_attr_0 : 1,
            axi_attr_1 : 1,
            axi_attr_2 : 1,
            axi_attr_3 : 1,
            addr : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_direct_start_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_DIRECT_END_RO                   0x00000080
#define AG_MG_REGS_PCC_DIRECT_END_RM                   0xFFFFFF00

#define AG_MG_REGS_PCC_DIRECT_END_ADDR_BO              8
#define AG_MG_REGS_PCC_DIRECT_END_ADDR_BM              0xFFFFFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_DIRECT_END_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 8,
            addr : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_direct_end_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_INVAL_START_RO                  0x000000A0
#define AG_MG_REGS_PCC_INVAL_START_RM                  0xFFFFFF03

#define AG_MG_REGS_PCC_INVAL_START_SCOPE_BO            0
#define AG_MG_REGS_PCC_INVAL_START_SCOPE_BM            0x00000003

#define AG_MG_REGS_PCC_INVAL_START_ADDR_BO             8
#define AG_MG_REGS_PCC_INVAL_START_ADDR_BM             0xFFFFFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_INVAL_START_U
{
    struct
    {
        ag_mg_regs_register
            scope : 2,
            fill0 : 6,
            addr : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_inval_start_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_INVAL_END_RO                    0x000000C0
#define AG_MG_REGS_PCC_INVAL_END_RM                    0xFFFFFF00

#define AG_MG_REGS_PCC_INVAL_END_ADDR_BO               8
#define AG_MG_REGS_PCC_INVAL_END_ADDR_BM               0xFFFFFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_INVAL_END_U
{
    struct
    {
        ag_mg_regs_register
            fill0 : 8,
            addr : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_inval_end_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_PCC_UNLCK_ALL_RO                    0x000001E0
#define AG_MG_REGS_PCC_UNLCK_ALL_RM                    0xFFFFFFFF

#define AG_MG_REGS_PCC_UNLCK_ALL_PCC_UNLCK_ALL_BO      0
#define AG_MG_REGS_PCC_UNLCK_ALL_PCC_UNLCK_ALL_BM      0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_UNLCK_ALL_U
{
    struct
    {
        ag_mg_regs_register
            unlck_all;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_unlck_all_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_LCK0_START_RO                   0x00000200
#define AG_MG_REGS_PCC_LCK0_START_RM                   0xFFFFFF01

#define AG_MG_REGS_PCC_LCK0_START_EN_BO                0
#define AG_MG_REGS_PCC_LCK0_START_EN_BM                0x00000001

#define AG_MG_REGS_PCC_LCK0_START_START_ADDR_BO        8
#define AG_MG_REGS_PCC_LCK0_START_START_ADDR_BM        0x003FFF00

#define AG_MG_REGS_PCC_LCK0_START_BASE_ADDR_BM 0xFFC00000
#define AG_MG_REGS_PCC_LCK0_START_BASE_ADDR_BO 22

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_LCK0_START_U
{
    struct
    {
        ag_mg_regs_register
            en : 1,
            fill0 : 7,
            start_addr : 14,
            base_addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_lck0_start_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_LCK0_END_RO                     0x00000220
#define AG_MG_REGS_PCC_LCK0_END_RM                     0x003FFF00

#define AG_MG_REGS_PCC_LCK0_END_END_ADDR_BO            8
#define AG_MG_REGS_PCC_LCK0_END_END_ADDR_BM            0x003FFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_LCK0_END_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 8,
            end_addr : 14,
            fill0 : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_lck0_end_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_LCK1_START_RO                   0x00000240
#define AG_MG_REGS_PCC_LCK1_START_RM                   0xFFFFFF01

#define AG_MG_REGS_PCC_LCK1_START_EN_BO                0
#define AG_MG_REGS_PCC_LCK1_START_EN_BM                0x00000001

#define AG_MG_REGS_PCC_LCK1_START_START_ADDR_BO        8
#define AG_MG_REGS_PCC_LCK1_START_START_ADDR_BM        0x003FFF00

#define AG_MG_REGS_PCC_LCK1_START_BASE_ADDR_BM 0xFFC00000
#define AG_MG_REGS_PCC_LCK1_START_BASE_ADDR_BO 22

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_LCK1_START_U
{
    struct
    {
        ag_mg_regs_register
            en : 1,
            fill0 : 7,
            start_addr : 14,
            base_addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_lck1_start_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_LCK1_END_RO                     0x00000260
#define AG_MG_REGS_PCC_LCK1_END_RM                     0x003FFF00

#define AG_MG_REGS_PCC_LCK1_END_END_ADDR_BO            8
#define AG_MG_REGS_PCC_LCK1_END_END_ADDR_BM            0x003FFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_LCK1_END_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 8,
            end_addr : 14,
            fill0 : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_lck1_end_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_LCK2_START_RO                   0x00000280
#define AG_MG_REGS_PCC_LCK2_START_RM                   0xFFFFFF01

#define AG_MG_REGS_PCC_LCK2_START_EN_BO                0
#define AG_MG_REGS_PCC_LCK2_START_EN_BM                0x00000001

#define AG_MG_REGS_PCC_LCK2_START_START_ADDR_BO        8
#define AG_MG_REGS_PCC_LCK2_START_START_ADDR_BM        0x003FFF00

#define AG_MG_REGS_PCC_LCK2_START_BASE_ADDR_BM 0xFFC00000
#define AG_MG_REGS_PCC_LCK2_START_BASE_ADDR_BO 22

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_LCK2_START_U
{
    struct
    {
        ag_mg_regs_register
            en : 1,
            fill0 : 7,
            start_addr : 14,
            base_addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_lck2_start_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_LCK2_END_RO                     0x000002A0
#define AG_MG_REGS_PCC_LCK2_END_RM                     0x003FFF00

#define AG_MG_REGS_PCC_LCK2_END_END_ADDR_BO            8
#define AG_MG_REGS_PCC_LCK2_END_END_ADDR_BM            0x003FFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_LCK2_END_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 8,
            end_addr : 14,
            fill0 : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_lck2_end_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_LCK3_START_RO                   0x000002C0
#define AG_MG_REGS_PCC_LCK3_START_RM                   0xFFFFFF01

#define AG_MG_REGS_PCC_LCK3_START_EN_BO                0
#define AG_MG_REGS_PCC_LCK3_START_EN_BM                0x00000001

#define AG_MG_REGS_PCC_LCK3_START_START_ADDR_BO        8
#define AG_MG_REGS_PCC_LCK3_START_START_ADDR_BM        0x003FFF00

#define AG_MG_REGS_PCC_LCK3_START_BASE_ADDR_BM 0xFFC00000
#define AG_MG_REGS_PCC_LCK3_START_BASE_ADDR_BO 22

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_LCK3_START_U
{
    struct
    {
        ag_mg_regs_register
            en : 1,
            fill0 : 7,
            start_addr : 14,
            base_addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_lck3_start_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_LCK3_END_RO                     0x000002E0
#define AG_MG_REGS_PCC_LCK3_END_RM                     0x003FFF00

#define AG_MG_REGS_PCC_LCK3_END_END_ADDR_BO            8
#define AG_MG_REGS_PCC_LCK3_END_END_ADDR_BM            0x003FFF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_LCK3_END_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 8,
            end_addr : 14,
            fill0 : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_lck3_end_u;
#endif


/*
 * Initialization value: 0x00000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_PCC_SEG0_RO                         0x00000400
#define AG_MG_REGS_PCC_SEG0_RM                         0xFFC00001

#define AG_MG_REGS_PCC_SEG0_FIX_BO                     0
#define AG_MG_REGS_PCC_SEG0_FIX_BM                     0x00000001

#define AG_MG_REGS_PCC_SEG0_ADDR_BO                    22
#define AG_MG_REGS_PCC_SEG0_ADDR_BM                    0xFFC00000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_SEG0_U
{
    struct
    {
        ag_mg_regs_register
            fix : 1,
            fill0 : 21,
            addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_seg0_u;
#endif


/*
 * Initialization value: 0x00400001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_PCC_SEG1_RO                         0x00000420
#define AG_MG_REGS_PCC_SEG1_RM                         0xFFC00001

#define AG_MG_REGS_PCC_SEG1_FIX_BO                     0
#define AG_MG_REGS_PCC_SEG1_FIX_BM                     0x00000001

#define AG_MG_REGS_PCC_SEG1_ADDR_BO                    22
#define AG_MG_REGS_PCC_SEG1_ADDR_BM                    0xFFC00000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_SEG1_U
{
    struct
    {
        ag_mg_regs_register
            fix : 1,
            fill0 : 21,
            addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_seg1_u;
#endif


/*
 * Initialization value: 0x20000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_PCC_SEG2_RO                         0x00000440
#define AG_MG_REGS_PCC_SEG2_RM                         0xFFC00001

#define AG_MG_REGS_PCC_SEG2_FIX_BO                     0
#define AG_MG_REGS_PCC_SEG2_FIX_BM                     0x00000001

#define AG_MG_REGS_PCC_SEG2_ADDR_BO                    22
#define AG_MG_REGS_PCC_SEG2_ADDR_BM                    0xFFC00000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_SEG2_U
{
    struct
    {
        ag_mg_regs_register
            fix : 1,
            fill0 : 21,
            addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_seg2_u;
#endif


/*
 * Initialization value: 0x20400000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_PCC_SEG3_RO                         0x00000460
#define AG_MG_REGS_PCC_SEG3_RM                         0xFFC00001

#define AG_MG_REGS_PCC_SEG3_FIX_BO                     0
#define AG_MG_REGS_PCC_SEG3_FIX_BM                     0x00000001

#define AG_MG_REGS_PCC_SEG3_ADDR_BO                    22
#define AG_MG_REGS_PCC_SEG3_ADDR_BM                    0xFFC00000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_SEG3_U
{
    struct
    {
        ag_mg_regs_register
            fix : 1,
            fill0 : 21,
            addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_seg3_u;
#endif

/* for compatability with V1.0 */
/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_PCC_SEG_CMDV10_RO                      0x00000500
#define AG_MG_REGS_PCC_SEG_CMDV10_RM                      0xFFC00139

#define AG_MG_REGS_PCC_SEG_CMDV10_FIX_BO                  0
#define AG_MG_REGS_PCC_SEG_CMDV10_FIX_BM                  0x00000001

#define AG_MG_REGS_PCC_SEG_CMDV10_SEG_ABS_BO              3
#define AG_MG_REGS_PCC_SEG_CMDV10_SEG_ABS_BM              0x00000008

#define AG_MG_REGS_AG_MG_REGS_PCC_SEG_CMDV10_SEG_BO_RPT   4
#define AG_MG_REGS_AG_MG_REGS_PCC_SEG_CMDV10_SEG_BM_RPT   0x00000030

#define AG_MG_REGS_PCC_SEG_CMDV10_UNFIX_ALL_BO            8
#define AG_MG_REGS_PCC_SEG_CMDV10_UNFIX_ALL_BM            0x00000100

#define AG_MG_REGS_PCC_SEG_CMDV10_ADDR_BO                 22
#define AG_MG_REGS_PCC_SEG_CMDV10_ADDR_BM                 0xFFC00000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_SEG_CMDV10_U
{
    struct
    {
        ag_mg_regs_register
            fix : 1,
            fill2 : 2,
            seg_abs : 1,
            seg_num : 2,
            fill1 : 2,
            unfix_all : 1,
            fill0 : 13,
            addr : 10;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_seg_cmdv10_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_PCC_FBUS_RO                         0x00000600
#define AG_MG_REGS_PCC_FBUS_RM                         0x00000001

/* for compatability with V1.0 */
#define AG_MG_REGS_PCC_FBUS_M2_FBUS_BO                 0
#define AG_MG_REGS_PCC_FBUS_M2_FBUS_BM                 0x00000001

#define AG_MG_REGS_PCC_FBUS_SYSMEM_BO                 0
#define AG_MG_REGS_PCC_FBUS_SYSMEM_BM                 0x00000001

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_PCC_FBUS_U
{
    struct
    {
        ag_mg_regs_register
            sysmem : 1,
            fill0 : 31;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_pcc_fbus_u;
#endif

/*
* Physical register addresses (for DSS accessing PCC)
*/
/*
 * Physical register addresses (for dss accessing pcc)
 */
#define AG_MG_REGS_PCC_BASE		0x90100000
#define AG_MG_REGS_PCC_REG(ro)		(AG_MG_REGS_PCC_BASE+(ro))

#define AG_MG_REGS_PCC_CTRL_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_CTRL_RO)
#define AG_MG_REGS_PCC_STAT_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_STAT_RO)
#define AG_MG_REGS_PCC_ATTR_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_ATTR_RO)
#define AG_MG_REGS_PCC_DIRECT_START_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_DIRECT_START_RO)
#define AG_MG_REGS_PCC_DIRECT_END_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_DIRECT_END_RO)
#define AG_MG_REGS_PCC_INVAL_START_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_INVAL_START_RO)
#define AG_MG_REGS_PCC_INVAL_END_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_INVAL_END_RO)
#define AG_MG_REGS_PCC_UNLCK_ALL_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_UNLCK_ALL_RO)
#define AG_MG_REGS_PCC_LCK0_START_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_LCK0_START_RO)
#define AG_MG_REGS_PCC_LCK0_END_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_LCK0_END_RO)
#define AG_MG_REGS_PCC_LCK1_START_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_LCK1_START_RO)
#define AG_MG_REGS_PCC_LCK1_END_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_LCK1_END_RO)
#define AG_MG_REGS_PCC_LCK2_START_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_LCK2_START_RO)
#define AG_MG_REGS_PCC_LCK2_END_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_LCK2_END_RO)
#define AG_MG_REGS_PCC_LCK3_START_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_LCK3_START_RO)
#define AG_MG_REGS_PCC_LCK3_END_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_LCK3_END_RO)
#define AG_MG_REGS_PCC_SEG0_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_SEG0_RO)
#define AG_MG_REGS_PCC_SEG1_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_SEG1_RO)
#define AG_MG_REGS_PCC_SEG2_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_SEG2_RO)
#define AG_MG_REGS_PCC_SEG3_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_SEG3_RO)
#define AG_MG_REGS_PCC_SEG_CMDV10_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_SEG_CMDV10_RO)
#define AG_MG_REGS_PCC_FBUS_RA	AG_MG_REGS_PCC_REG(AG_MG_REGS_PCC_FBUS_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES

#if 0
typedef struct AG_MG_REGS_PCC_LCK_RANGE_S
{
ag_mg_regs_pcc_lck_range_u  lck_range;
ag_mg_regs_register         fill[7];
} ag_mg_regs_pcc_lck_range_s;
#endif

typedef struct AG_MG_REGS_PCC_REGS_S
{
	ag_mg_regs_pcc_ctrl_u	pcc_ctrl ;
	ag_mg_regs_register	FILL0[7] ;
	ag_mg_regs_pcc_stat_u	pcc_stat ;
	ag_mg_regs_register	FILL1[7] ;
	ag_mg_regs_pcc_attr_u	pcc_attr ;
	ag_mg_regs_register	FILL2[7] ;
	ag_mg_regs_pcc_direct_start_u	pcc_direct_start ;
	ag_mg_regs_register	FILL3[7] ;
	ag_mg_regs_pcc_direct_end_u	pcc_direct_end ;
	ag_mg_regs_register	FILL4[7] ;
	ag_mg_regs_pcc_inval_start_u	pcc_inval_start ;
	ag_mg_regs_register	FILL5[7] ;
	ag_mg_regs_pcc_inval_end_u	pcc_inval_end ;
	ag_mg_regs_register	FILL6[71] ;
	ag_mg_regs_pcc_unlck_all_u	pcc_unlck_all ;
	ag_mg_regs_register	FILL7[7] ;
	ag_mg_regs_pcc_lck0_start_u	pcc_lck0_start ;
	ag_mg_regs_register	FILL8[7] ;
	ag_mg_regs_pcc_lck0_end_u	pcc_lck0_end ;
	ag_mg_regs_register	FILL9[7] ;
	ag_mg_regs_pcc_lck1_start_u	pcc_lck1_start ;
	ag_mg_regs_register	FILL10[7] ;
	ag_mg_regs_pcc_lck1_end_u	pcc_lck1_end ;
	ag_mg_regs_register	FILL11[7] ;
	ag_mg_regs_pcc_lck2_start_u	pcc_lck2_start ;
	ag_mg_regs_register	FILL12[7] ;
	ag_mg_regs_pcc_lck2_end_u	pcc_lck2_end ;
	ag_mg_regs_register	FILL13[7] ;
	ag_mg_regs_pcc_lck3_start_u	pcc_lck3_start ;
	ag_mg_regs_register	FILL14[7] ;
	ag_mg_regs_pcc_lck3_end_u	pcc_lck3_end ;
	ag_mg_regs_register	FILL15[71] ;
	ag_mg_regs_pcc_seg0_u	pcc_seg0 ;
	ag_mg_regs_register	FILL16[7] ;
	ag_mg_regs_pcc_seg1_u	pcc_seg1 ;
	ag_mg_regs_register	FILL17[7] ;
	ag_mg_regs_pcc_seg2_u	pcc_seg2 ;
	ag_mg_regs_register	FILL18[7] ;
	ag_mg_regs_pcc_seg3_u	pcc_seg3 ;
	ag_mg_regs_register	FILL19[39] ;
	ag_mg_regs_pcc_seg_cmdv10_u	pcc_seg_cmdv10 ;
	ag_mg_regs_register	FILL20[63] ;
	ag_mg_regs_pcc_fbus_u pcc_fbus;
} ag_mg_regs_pcc_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_pcc_reg_s *pcc_regs =
*       (volatile ag_mg_regs_pcc_reg_s *)AG_MG_REGS_PCC_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_pcc.h,v $
Revision 1.2  2017/07/28 07:58:34  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:28  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

