/* $Id: ag_mg_regs_dbm.h,v 1.2 2017/07/28 07:58:33 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_dbm.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_dbm.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
* ag_mg_regs_dbm.h
*
* Copyright (c) 2010 LSI Inc.  All Rights Reserved
*
* This is unpublished proprietary information of LSI Inc.
* This copyright notice does not evidence publication.
*
* The use of the software, documentation, methodologies, and other information
* contained herein is governed solely by the associated license agreements.
* Any inconsistent use shall be deemed to be a misappropriation of the
* intellectual property of LSI Inc. and treated accordingly.
*
* DSP Bus Matrix (DBM) semaphore registers provide a software mechanism
 * for the DSP Subsystem(s) (DSS) and the Packet Processor Block (PPB)
 * to negotiate exclusive access to shared resources. These registers are
 * accessible from the DSS(s) and from the PPB. 
*
* See ''Physical register addresses'' below for macros
* used to generate addresses for specific registers.
*
* Registers defined in this file :
*
 *  DBM_SEMR
 *  DBM_SEMS
 *  DBM_SEMC
 *  DBM_SEMRST
 *  DBM_PPB_PORT
 *  DBM_WPROTECT
 *  DBM_CTL
 *  DBM_ECCSTAT
 *  DBM_DATA_AR_CHAN_ARB
 *  DBM_DATA_AW_CHAN_ARB
 *  DBM_DATA_SI_NUM
 *  DBM_DATA_MI_NUM
 *  DBM_DATA_PERIPH_ID_0
 *  DBM_DATA_PERIPH_ID_1
 *  DBM_DATA_PERIPH_ID_2
 *  DBM_DATA_PRIME_ID_0
 *  DBM_DATA_PRIME_ID_1
 *  DBM_DATA_PRIME_ID_2
 *  DBM_DATA_PRIME_ID_3
 *  DBM_CFG_AR_CHAN_ARB
 *  DBM_CFG_AW_CHAN_ARB
 *  DBM_CFG_SI_NUM
 *  DBM_CFG_MI_NUM
 *  DBM_CFG_PERIPH_ID_0
 *  DBM_CFG_PERIPH_ID_1
 *  DBM_CFG_PERIPH_ID_2
 *  DBM_CFG_PRIME_ID_0
 *  DBM_CFG_PRIME_ID_1
 *  DBM_CFG_PRIME_ID_2
 *  DBM_CFG_PRIME_ID_3
*
* Prefix naming conventions :
*   AG_MG_REGS_XXX_RA : register/memory physical address
*   AG_MG_REGS_XXX_RO : register/memory address offset
*   AG_MG_REGS_XXX_RM : register mask
*   AG_MG_REGS_XXX_BO : bit/field offset from LSB
*   AG_MG_REGS_XXX_BM : bit/field mask
*   AG_MG_REGS_XXX_U  : bitfields in C union typedef
*   AG_MG_REGS_XXX_S  : registers in C struct typedef
*   AG_MG_REGS_XX_RPT : number of identical registers in array
*   AG_MG_REGS_XX_IVL : interval between registers in array
*
* NOTE: user may redefine ag_mg_regs_register
*       in ag_mg_regs_regops.h if necessary
* NOTE: access mode of individual bit fields matches that
*       of containing register unless indicated otherwise
*/

#ifndef AG_MG_REGS_DBM_REGISTERS_H
#define AG_MG_REGS_DBM_REGISTERS_H

#include "ag_mg_regs_regops.h"

/* 
 * Generated by HSI Designer release 2.3.5.
 */

/* 
 * DBM_SEMR (DBM Semaphore Request Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Set on Write to 1
 */
#define AG_MG_REGS_DBM_SEMR_RO                 0x00000000

#define AG_MG_REGS_SEMREQ_RO                   AG_MG_REGS_DBM_SEMR_RO
#define AG_MG_REGS_SEMREQ_BO                   0
#define AG_MG_REGS_SEMREQ_BM                   0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_SEMR_U
{
    struct
    {
        ag_mg_regs_register
            semreq : 16,
            fill0 : 16;
	ag_mg_regs_register fill1 ; /* added for the 64bits between regs*/
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_semr_u;
#endif


/* 
 * DBM_SEMS (Semaphore Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_SEMS_RO                 0x00000040

#define AG_MG_REGS_SEMS_RO                     AG_MG_REGS_DBM_SEMS_RO
#define AG_MG_REGS_SEMS_BO                     0
#define AG_MG_REGS_SEMS_BM                     0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_SEMS_U
{
    struct
    {
        ag_mg_regs_register
            sems : 16,
            fill0 : 16;
	ag_mg_regs_register fill1 ; /* added for the 64bits between regs*/
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_sems_u;
#endif


/* 
 * DBM_SEMC (Semaphore Request Cancellation Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DBM_SEMC_RO                 0x00000080

#define AG_MG_REGS_SEMC_RO                     AG_MG_REGS_DBM_SEMC_RO
#define AG_MG_REGS_SEMC_BO                     0
#define AG_MG_REGS_SEMC_BM                     0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_SEMC_U
{
    struct
    {
        ag_mg_regs_register
            semc : 16,
            fill0 : 16;
	ag_mg_regs_register fill1 ; /* added for the 64bits between regs*/
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_semc_u;
#endif


/* 
 * DBM_SEMRST (Semaphore Logic Reset Register)
 * Initialization value: 0x0000FFFF  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DBM_SEMRST_RO               0x000000C0

#define AG_MG_REGS_SEMRST_RO                   AG_MG_REGS_DBM_SEMRST_RO
#define AG_MG_REGS_SEMRST_BO                   0
#define AG_MG_REGS_SEMRST_BM                   0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_SEMRST_U
{
    struct
    {
        ag_mg_regs_register
            semrst : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_semrst_u;
#endif


/* 
 * Initialization value: 0x00A2A00A  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DBM_PPB_PORT_RO             0x000000E0

#define AG_MG_REGS_PPB_PORT2_RO                AG_MG_REGS_DBM_PPB_PORT_RO
#define AG_MG_REGS_PPB_PORT2_BO                21
#define AG_MG_REGS_PPB_PORT2_BM                0x00E00000

#define AG_MG_REGS_PPB_PORT1_RO                AG_MG_REGS_DBM_PPB_PORT_RO
#define AG_MG_REGS_PPB_PORT1_BO                12
#define AG_MG_REGS_PPB_PORT1_BM                0x0007F000

#define AG_MG_REGS_PPB_PORT0_RO                AG_MG_REGS_DBM_PPB_PORT_RO
#define AG_MG_REGS_PPB_PORT0_BO                0
#define AG_MG_REGS_PPB_PORT0_BM                0x0000000F

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_PPB_PORT_U
{
    struct
    {
        ag_mg_regs_register
            ppb_port0 : 4,
            fill0 : 8,
            ppb_port1 : 7,
            fill1 : 2,
            ppb_port2 : 3,
            fill2 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_ppb_port_u;
#endif


/* 
 * DBM_WPROTECT (DBM bank-wise write protect)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DBM_WPROTECT_RO             0x000000E8

#define AG_MG_REGS_WKEY_RO                     AG_MG_REGS_DBM_WPROTECT_RO
#define AG_MG_REGS_WKEY_BO                     16
#define AG_MG_REGS_WKEY_BM                     0xFFFF0000

#define AG_MG_REGS_WPROTECT_RO                 AG_MG_REGS_DBM_WPROTECT_RO
#define AG_MG_REGS_WPROTECT_BO                 0
#define AG_MG_REGS_WPROTECT_BM                 0x0000FFFF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_WPROTECT_U
{
    struct
    {
        ag_mg_regs_register
            wprotect : 16,
            wkey : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_wprotect_u;
#endif


/* 
 * DBM_CTL (DBM Matrix Control)
 * Initialization value: 0x00000003  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DBM_CTL_RO                  0x000000F0

#define AG_MG_REGS_ECCEN_RO                    AG_MG_REGS_DBM_CTL_RO
#define AG_MG_REGS_ECCEN_BO                    1
#define AG_MG_REGS_ECCEN_BM                    0x00000002

#define AG_MG_REGS_DSS_ECCEN_RO                AG_MG_REGS_DBM_CTL_RO
#define AG_MG_REGS_DSS_ECCEN_BO                0
#define AG_MG_REGS_DSS_ECCEN_BM                0x00000001


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CTL_U
{
    struct
    {
        ag_mg_regs_register
            dss_eccen : 1,
            eccen : 1,
            fill0 : 30;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_ctl_u;
#endif


/* 
 * DBM_ECCSTAT (System Memory ECC & DBM status flags)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write
 */
#define AG_MG_REGS_DBM_ECCSTAT_RO              0x000000F8

#define AG_MG_REGS_ERRMULT_RO                  AG_MG_REGS_DBM_ECCSTAT_RO
#define AG_MG_REGS_ERRMULT_BO                  16
#define AG_MG_REGS_ERRMULT_BM                  0xFFFF0000

#define AG_MG_REGS_ERRDETECT_RO                AG_MG_REGS_DBM_ECCSTAT_RO
#define AG_MG_REGS_ERRDETECT_BO                0
#define AG_MG_REGS_ERRDETECT_BM                0x0000FFFF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_ECCSTAT_U
{
    struct
    {
        ag_mg_regs_register
            errdetect : 16,
            errmult : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_eccstat_u;
#endif


/* 
 * DBM_DATA_AR_CHAN_ARB (Read Address Channel Arbitration)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DBM_DATA_AR_CHAN_ARB_RO     0x00001408

#define AG_MG_REGS_AR_WRITE_INTFC_RO              AG_MG_REGS_DBM_DATA_AR_CHAN_ARB_RO
#define AG_MG_REGS_AR_WRITE_INTFC_BO              24
#define AG_MG_REGS_AR_WRITE_INTFC_BM              0xFF000000

#define AG_MG_REGS_AR_PRIORITY_RO                 AG_MG_REGS_DBM_DATA_AR_CHAN_ARB_RO
#define AG_MG_REGS_AR_PRIORITY_BO                 8
#define AG_MG_REGS_AR_PRIORITY_BM                 0x0000FF00

#define AG_MG_REGS_AR_READ_INTFC_RO               AG_MG_REGS_DBM_DATA_AR_CHAN_ARB_RO
#define AG_MG_REGS_AR_READ_INTFC_BO               0
#define AG_MG_REGS_AR_READ_INTFC_BM               0x0000001F


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_DATA_AR_CHAN_ARB_U
{
    struct
    {
        ag_mg_regs_register
            read_intfc_num : 5,
            fill1 : 3,
            priority : 8,
            fill0 : 8,
            write_intfc_num : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_data_ar_chan_arb_u;
#endif


/* 
 * DBM_DATA_AW_CHAN_ARB (Write Address Channel Arbitration)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DBM_DATA_AW_CHAN_ARB_RO     0x0000140C

#define AG_MG_REGS_AW_WRITE_INTFC_RO              AG_MG_REGS_DBM_DATA_AW_CHAN_ARB_RO
#define AG_MG_REGS_AW_WRITE_INTFC_BO              24
#define AG_MG_REGS_AW_WRITE_INTFC_BM              0xFF000000

#define AG_MG_REGS_AW_PRIORITY_RO                 AG_MG_REGS_DBM_DATA_AW_CHAN_ARB_RO
#define AG_MG_REGS_AW_PRIORITY_BO                 8
#define AG_MG_REGS_AW_PRIORITY_BM                 0x0000FF00

#define AG_MG_REGS_AW_READ_INTFC_RO               AG_MG_REGS_DBM_DATA_AW_CHAN_ARB_RO
#define AG_MG_REGS_AW_READ_INTFC_BO               0
#define AG_MG_REGS_AW_READ_INTFC_BM               0x0000001F


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_DATA_AW_CHAN_ARB_U
{
    struct
    {
        ag_mg_regs_register
            read_intfc_num : 5,
            fill1 : 3,
            priority : 8,
            fill0 : 8,
            write_intfc_num : 8;

    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_data_aw_chan_arb_u;
#endif


/* 
 * Initialization value: 0x00000018  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_DATA_SI_RO              0x00001FC0

#define AG_MG_REGS_DBM_DATA_NUM_SLAVE_INTERFACES_RO     AG_MG_REGS_DBM_DATA_SI_RO
#define AG_MG_REGS_DBM_DATA_NUM_SLAVE_INTERFACES_BO     0
#define AG_MG_REGS_DBM_DATA_NUM_SLAVE_INTERFACES_BM     0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_DATA_SI_NUM_U
{
    struct
    {
        ag_mg_regs_register
            num_slave_interfaces : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_data_si_num_u;
#endif


/* 
 * Initialization value: 0x0000001C  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_DATA_MI_RO              0x00001FC4

#define AG_MG_REGS_DBM_DATA_NUM_MASTER_INTERFACES_RO    AG_MG_REGS_DBM_DATA_MI_RO
#define AG_MG_REGS_DBM_DATA_NUM_MASTER_INTERFACES_BO    0
#define AG_MG_REGS_DBM_DATA_NUM_MASTER_INTERFACES_BM    0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_DATA_MI_NUM_U
{
    struct
    {
        ag_mg_regs_register
            num_master_interfaces : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_data_mi_num_u;
#endif


/* 
 * DBM_DATA_PERIPH_ID_0 (PL301 Peripheral ID Register 0)
 * Initialization value: 0x00000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_DATA_PERIPH_ID_0_RO     0x00001FE0

#define AG_MG_REGS_DBM_DATA_PART_NUMBER_0_RO            AG_MG_REGS_DBM_DATA_PERIPH_ID_0_RO
#define AG_MG_REGS_DBM_DATA_PART_NUMBER_0_BO            0
#define AG_MG_REGS_DBM_DATA_PART_NUMBER_0_BM            0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_DATA_PERIPH_ID_0_U
{
    struct
    {
        ag_mg_regs_register
            part_number_0 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_data_periph_id_0_u;
#endif


/* 
 * DBM_DATA_PERIPH_ID_1 (PL301 Peripheral ID Register 1)
 * Initialization value: 0x00000013  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_DATA_PERIPH_ID_1_RO     0x00001FE4

#define AG_MG_REGS_DBM_DATA_DESIGNER_0_RO               AG_MG_REGS_DBM_DATA_PERIPH_ID_1_RO
#define AG_MG_REGS_DBM_DATA_DESIGNER_0_BO               4
#define AG_MG_REGS_DBM_DATA_DESIGNER_0_BM               0x000000F0

#define AG_MG_REGS_DBM_DATA_PART_NUMBER_1_RO            AG_MG_REGS_DBM_DATA_PERIPH_ID_1_RO
#define AG_MG_REGS_DBM_DATA_PART_NUMBER_1_BO            0
#define AG_MG_REGS_DBM_DATA_PART_NUMBER_1_BM            0x0000000F


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_DATA_PERIPH_ID_1_U
{
    struct
    {
        ag_mg_regs_register
            part_number_1 : 4,
            designer_0 : 4,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_data_periph_id_1_u;
#endif


/* 
 * DBM_DATA_PERIPH_ID_2 (PL301 Peripheral ID Register 2)
 * Initialization value: 0x00000034  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_DATA_PERIPH_ID_2_RO     0x00001FE8

#define AG_MG_REGS_DBM_DATA_REVISION_RO                 AG_MG_REGS_DBM_DATA_PERIPH_ID_2_RO
#define AG_MG_REGS_DBM_DATA_REVISION_BO                 4
#define AG_MG_REGS_DBM_DATA_REVISION_BM                 0x000000F0

#define AG_MG_REGS_DBM_DATA_DESIGNER_1_RO               AG_MG_REGS_DBM_DATA_PERIPH_ID_2_RO
#define AG_MG_REGS_DBM_DATA_DESIGNER_1_BO               0
#define AG_MG_REGS_DBM_DATA_DESIGNER_1_BM               0x0000000F


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_DATA_PERIPH_ID_2_U
{
    struct
    {
        ag_mg_regs_register
            designer_1 : 4,
            revision : 4,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_data_periph_id_2_u;
#endif


/* 
 * DBM_DATA_PRIME_ID_0 (PL301 Prime Cell ID Register 0)
 * Initialization value: 0x0000000D  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_DATA_PRIME_ID_0_RO      0x00001FF0

#define AG_MG_REGS_DBM_DATA_PCELL_ID_0_RO               AG_MG_REGS_DBM_DATA_PRIME_ID_0_RO
#define AG_MG_REGS_DBM_DATA_PCELL_ID_0_BO               0
#define AG_MG_REGS_DBM_DATA_PCELL_ID_0_BM               0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_DATA_PRIME_ID_0_U
{
    struct
    {
        ag_mg_regs_register
            pcell_id_0 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_data_prime_id_0_u;
#endif


/* 
 * DBM_DATA_PRIME_ID_1 (PL301 Prime Cell ID Register 1)
 * Initialization value: 0x000000F0  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_DATA_PRIME_ID_1_RO      0x0001FF4

#define AG_MG_REGS_DBM_DATA_PCELL_ID_1_RO               AG_MG_REGS_DBM_DATA_PRIME_ID_1_RO
#define AG_MG_REGS_DBM_DATA_PCELL_ID_1_BO               0
#define AG_MG_REGS_DBM_DATA_PCELL_ID_1_BM               0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_DATA_PRIME_ID_1_U
{
    struct
    {
        ag_mg_regs_register
            pcell_id_1 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_data_prime_id_1_u;
#endif


/* 
 * DBM_DATA_PRIME_ID_2 (PL301 Prime Cell ID Register 2)
 * Initialization value: 0x00000005  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_DATA_PRIME_ID_2_RO      0x00001FF8

#define AG_MG_REGS_DBM_DATA_PCELL_ID_2_RO               AG_MG_REGS_DBM_DATA_PRIME_ID_2_RO
#define AG_MG_REGS_DBM_DATA_PCELL_ID_2_BO               0
#define AG_MG_REGS_DBM_DATA_PCELL_ID_2_BM               0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_DATA_PRIME_ID_2_U
{
    struct
    {
        ag_mg_regs_register
            pcell_id_2 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_data_prime_id_2_u;
#endif


/* 
 * DBM_DATA_PRIME_ID_3 (PL301 Prime Cell ID Register 3)
 * Initialization value: 0x000000B1  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_DATA_PRIME_ID_3_RO      0x00001FFC

#define AG_MG_REGS_DBM_DATA_PCELL_ID_3_RO               AG_MG_REGS_DBM_DATA_PRIME_ID_3_RO
#define AG_MG_REGS_DBM_DATA_PCELL_ID_3_BO               0
#define AG_MG_REGS_DBM_DATA_PCELL_ID_3_BM               0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_DATA_PRIME_ID_3_U
{
    struct
    {
        ag_mg_regs_register
            pcell_id_3 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_data_prime_id_3_u;
#endif


/* 
 * DBM_CFG_AR_CHAN_ARB (Read Address Channel Arbitration)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DBM_CFG_AR_CHAN_ARB_RO      0x00002408
#define AG_MG_REGS_DBM_CFG_AR_CHAN_ARB_RPT     7
#define AG_MG_REGS_DBM_CFG_AR_CHAN_ARB_IVL     0x20

#define AG_MG_REGS_DBM_CFG_AR_ARB_ACCESS_RO               AG_MG_REGS_DBM_CFG_AR_CHAN_ARB_RO
#define AG_MG_REGS_DBM_CFG_AR_ARB_ACCESS_BO               24
#define AG_MG_REGS_DBM_CFG_AR_ARB_ACCESS_BM               0xFF000000

#define AG_MG_REGS_DBM_CFG_AR_SLOT_INT_RO                 AG_MG_REGS_DBM_CFG_AR_CHAN_ARB_RO
#define AG_MG_REGS_DBM_CFG_AR_SLOT_INT_BO                 0
#define AG_MG_REGS_DBM_CFG_AR_SLOT_INT_BM                 0x0000001F


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CFG_AR_CHAN_ARB_U
{
    struct
    {
        ag_mg_regs_register
            slot_int_num : 5,
            arb_access : 8,
            fill0 : 19;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_cfg_ar_chan_arb_u;
#endif


/* 
 * DBM_CFG_AW_CHAN_ARB (Write Address Channel Arbitration)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DBM_CFG_AW_CHAN_ARB_RO      0x0000240C
#define AG_MG_REGS_DBM_CFG_AW_CHAN_ARB_RPT     7
#define AG_MG_REGS_DBM_CFG_AW_CHAN_ARB_IVL     0x20

#define AG_MG_REGS_DBM_CFG_AW_ARB_ACCESS_RO               AG_MG_REGS_DBM_CFG_AW_CHAN_ARB_RO
#define AG_MG_REGS_DBM_CFG_AW_ARB_ACCESS_BO               24
#define AG_MG_REGS_DBM_CFG_AW_ARB_ACCESS_BM               0xFF000000

#define AG_MG_REGS_DBM_CFG_AW_SLOT_INT_RO_RPT             AG_MG_REGS_DBM_CFG_AW_CHAN_ARB_RO
#define AG_MG_REGS_DBM_CFG_AW_SLOT_INT_BO_RPT             0
#define AG_MG_REGS_DBM_CFG_AW_SLOT_INT_BM_RPT             0x0000001F


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CFG_AW_CHAN_ARB_U
{
    struct
    {
        ag_mg_regs_register
            slot_int_num : 5,
            arb_access : 8,
            fill0 : 19;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_cfg_aw_chan_arb_u;
#endif


/* 
 * Initialization value: 0x00000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_CFG_SI_NUM_RO           0x00002FC0

#define AG_MG_REGS_DBM_CFG_NUM_SLAVE_INTERFACES_RO     AG_MG_REGS_DBM_CFG_SI_NUM_RO
#define AG_MG_REGS_DBM_CFG_NUM_SLAVE_INTERFACES_BO     0
#define AG_MG_REGS_DBM_CFG_NUM_SLAVE_INTERFACES_BM     0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CFG_SI_NUM_U
{
    struct
    {
        ag_mg_regs_register
            num_slave_interfaces : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_cfg_si_num_u;
#endif


/* 
 * Initialization value: 0x0000000A  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_CFG_MI_NUM_RO           0x00002FC4

#define AG_MG_REGS_DBM_CFG_NUM_MASTER_INTERFACES_RO    AG_MG_REGS_DBM_CFG_MI_NUM_RO
#define AG_MG_REGS_DBM_CFG_NUM_MASTER_INTERFACES_BO    0
#define AG_MG_REGS_DBM_CFG_NUM_MASTER_INTERFACES_BM    0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CFG_MI_NUM_U
{
    struct
    {
        ag_mg_regs_register
            num_master_interfaces : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_cfg_mi_num_u;
#endif


/* 
 * DBM_CFG_PERIPH_ID_0 (PL301 Peripheral ID Register 0)
 * Initialization value: 0x00000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_CFG_PERIPH_ID_0_RO      0x00002FE0

#define AG_MG_REGS_DBM_CFG_PART_NUMBER_0_RO            AG_MG_REGS_DBM_CFG_PERIPH_ID_0_RO
#define AG_MG_REGS_DBM_CFG_PART_NUMBER_0_BO            0
#define AG_MG_REGS_DBM_CFG_PART_NUMBER_0_BM            0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CFG_PERIPH_ID_0_U
{
    struct
    {
        ag_mg_regs_register
            part_number_0 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_cfg_periph_id_0_u;
#endif


/* 
 * DBM_CFG_PERIPH_ID_1 (PL301 Peripheral ID Register 1)
 * Initialization value: 0x00000013  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_CFG_PERIPH_ID_1_RO      0x00002FE4

#define AG_MG_REGS_DBM_CFG_DESIGNER_0_RO               AG_MG_REGS_DBM_CFG_PERIPH_ID_1_RO
#define AG_MG_REGS_DBM_CFG_DESIGNER_0_BO               4
#define AG_MG_REGS_DBM_CFG_DESIGNER_0_BM               0x000000F0

#define AG_MG_REGS_DBM_CFG_PART_NUMBER_1_RO            AG_MG_REGS_DBM_CFG_PERIPH_ID_1_RO
#define AG_MG_REGS_DBM_CFG_PART_NUMBER_1_BO            0
#define AG_MG_REGS_DBM_CFG_PART_NUMBER_1_BM            0x0000000F


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CFG_PERIPH_ID_1_U
{
    struct
    {
        ag_mg_regs_register
            part_number_1 : 4,
            designer_0 : 4,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_cfg_periph_id_1_u;
#endif


/* 
 * DBM_CFG_PERIPH_ID_2 (PL301 Peripheral ID Register 2)
 * Initialization value: 0x00000034  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_CFG_PERIPH_ID_2_RO      0x00002FE8

#define AG_MG_REGS_DBM_CFG_REVISION_RO                 AG_MG_REGS_DBM_CFG_PERIPH_ID_2_RO
#define AG_MG_REGS_DBM_CFG_REVISION_BO                 4
#define AG_MG_REGS_DBM_CFG_REVISION_BM                 0x000000F0

#define AG_MG_REGS_DBM_CFG_DESIGNER_1_RO               AG_MG_REGS_DBM_CFG_PERIPH_ID_2_RO
#define AG_MG_REGS_DBM_CFG_DESIGNER_1_BO               0
#define AG_MG_REGS_DBM_CFG_DESIGNER_1_BM               0x0000000F


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CFG_PERIPH_ID_2_U
{
    struct
    {
        ag_mg_regs_register
            designer_1 : 4,
            revision : 4,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_cfg_periph_id_2_u;
#endif


/* 
 * DBM_CFG_PRIME_ID_0 (PL301 Prime Cell ID Register 0)
 * Initialization value: 0x0000000D  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_CFG_PRIME_ID_0_RO       0x00002FF0

#define AG_MG_REGS_DBM_CFG_PCELL_ID_0_RO               AG_MG_REGS_DBM_CFG_PRIME_ID_0_RO
#define AG_MG_REGS_DBM_CFG_PCELL_ID_0_BO               0
#define AG_MG_REGS_DBM_CFG_PCELL_ID_0_BM               0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CFG_PRIME_ID_0_U
{
    struct
    {
        ag_mg_regs_register
            pcell_id_0 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_cfg_prime_id_0_u;
#endif


/* 
 * DBM_CFG_PRIME_ID_1 (PL301 Prime Cell ID Register 1)
 * Initialization value: 0x000000F0  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_CFG_PRIME_ID_1_RO       0x00002FF4

#define AG_MG_REGS_DBM_CFG_PCELL_ID_1_RO               AG_MG_REGS_DBM_CFG_PRIME_ID_1_RO
#define AG_MG_REGS_DBM_CFG_PCELL_ID_1_BO               0
#define AG_MG_REGS_DBM_CFG_PCELL_ID_1_BM               0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CFG_PRIME_ID_1_U
{
    struct
    {
        ag_mg_regs_register
            pcell_id_1 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_cfg_prime_id_1_u;
#endif


/* 
 * DBM_CFG_PRIME_ID_2 (PL301 Prime Cell ID Register 2)
 * Initialization value: 0x00000005  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_CFG_PRIME_ID_2_RO       0x00002FF8

#define AG_MG_REGS_DBM_CFG_PCELL_ID_2_RO               AG_MG_REGS_DBM_CFG_PRIME_ID_2_RO
#define AG_MG_REGS_DBM_CFG_PCELL_ID_2_BO               0
#define AG_MG_REGS_DBM_CFG_PCELL_ID_2_BM               0x000000FF


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CFG_PRIME_ID_2_U
{
    struct
    {
        ag_mg_regs_register
            pcell_id_2 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_cfg_prime_id_2_u;
#endif


/* 
 * DBM_CFG_PRIME_ID_3 (PL301 Prime Cell ID Register 3)
 * Initialization value: 0x000000B1  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_DBM_CFG_PRIME_ID_3_RO       0x00002FFC

#define AG_MG_REGS_DBM_CFG_PCELL_ID_3_RO               AG_MG_REGS_DBM_CFG_PRIME_ID_3_RO
#define AG_MG_REGS_DBM_CFG_PCELL_ID_3_BO               0
#define AG_MG_REGS_DBM_CFG_PCELL_ID_3_BM               0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBM_CFG_PRIME_ID_3_U
{
    struct
    {
        ag_mg_regs_register
            pcell_id_2 : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbm_cfg_prime_id_3_u;
#endif

/*
 * Physical register addresses (for arm accessing dbm)
 */
#define AG_MG_REGS_DBM_BASE         0x98050000
#define AG_MG_REGS_DBM_REG(ro)		(AG_MG_REGS_DBM_BASE+(ro))
 
#define AG_MG_REGS_DBM_SEMR_RA(x)	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_SEMR_RO)+((x)*0x8)
#define AG_MG_REGS_DBM_SEMS_RA(x)	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_SEMS_RO)+((x)*8)
#define AG_MG_REGS_DBM_SEMC_RA(x)	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_SEMC_RO)+((x)*8)
#define AG_MG_REGS_DBM_SEMRST_RA	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_SEMRST_RO)
#define AG_MG_REGS_DBM_PPB_PORT_RA	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_PPB_PORT_RO)
#define AG_MG_REGS_DBM_WPROTECT_RA	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_WPROTECT_RO)
#define AG_MG_REGS_DBM_CTL_RA	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_CTL_RO)
#define AG_MG_REGS_DBM_ECCSTAT_RA	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_ECCSTAT_RO)
#define AG_MG_REGS_DBM_DATA_AR_CHAN_ARB_RA(x)	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_DATA_AR_CHAN_ARB_RO)+((x)*0x20)
#define AG_MG_REGS_DBM_DATA_AW_CHAN_ARB_RA(x)	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_DATA_AW_CHAN_ARB_RO)+((x)*0x20)
#define AG_MG_REGS_DBM_DATA_SI_NUM_RA	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_DATA_SI_RO)
#define AG_MG_REGS_DBM_DATA_MI_NUM_RA	AG_MG_REGS_DBM_REG(AG_MG_REGS_DBM_DATA_MI_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_DATA_ARW_CHAN_ARB_S
{
	ag_mg_regs_dbm_data_ar_chan_arb_u	dbm_data_ar_chan_arb ;
	ag_mg_regs_dbm_data_aw_chan_arb_u	dbm_data_aw_chan_arb ;
	ag_mg_regs_register	fill[6] ;
} ag_mg_regs_dbm_data_arw_chan_arb_s ;

typedef struct AG_MG_REGS_CFG_ARW_CHAN_ARB_S
{
	ag_mg_regs_register	fill0[2] ;
	ag_mg_regs_dbm_cfg_ar_chan_arb_u	dbm_cfg_ar_chan_arb ;
	ag_mg_regs_dbm_cfg_aw_chan_arb_u	dbm_cfg_aw_chan_arb ;
	ag_mg_regs_register	fill1[4] ;
} ag_mg_regs_dbm_cfg_arw_chan_arb_s ;

typedef struct AG_MG_REGS_DBM_REGS_S
{
	ag_mg_regs_dbm_semr_u			semr[6] ;
	ag_mg_regs_register			fills0[4] ;
	ag_mg_regs_dbm_sems_u			sems[6] ;
	ag_mg_regs_register			fills1[4] ;
	ag_mg_regs_dbm_semc_u			semc[6] ;
	ag_mg_regs_register			fills2[4] ;
	ag_mg_regs_dbm_semrst_u			semrst ;
	ag_mg_regs_register			fill0[7] ;
	ag_mg_regs_dbm_ppb_port_u		ppb_port ;
	ag_mg_regs_register			fill1 ;
	ag_mg_regs_dbm_wprotect_u		wprotect ;
	ag_mg_regs_register			fill2 ;
	ag_mg_regs_dbm_ctl_u			ctl ;
	ag_mg_regs_register			fill3 ;
	ag_mg_regs_dbm_eccstat_u		eccstat ;
	ag_mg_regs_register			fill4[1219] ;
	ag_mg_regs_dbm_data_arw_chan_arb_s	data_arw_chan_arb[28] ;
	ag_mg_regs_register			fill5[526] ;
	ag_mg_regs_dbm_data_si_num_u		data_si_num ;
	ag_mg_regs_dbm_data_mi_num_u		data_mi_num ;
	ag_mg_regs_register			fill6[6] ;
	ag_mg_regs_dbm_data_periph_id_0_u	data_periph_id_0 ;
	ag_mg_regs_dbm_data_periph_id_1_u	data_periph_id_1 ;
	ag_mg_regs_dbm_data_periph_id_2_u	data_periph_id_2 ;
	ag_mg_regs_register			fill7 ;
	ag_mg_regs_dbm_data_prime_id_0_u	data_prime_id_0 ;
	ag_mg_regs_dbm_data_prime_id_1_u	data_prime_id_1 ;
	ag_mg_regs_dbm_data_prime_id_2_u	data_prime_id_2 ;
	ag_mg_regs_dbm_data_prime_id_3_u	data_prime_id_3 ;
	ag_mg_regs_register			fill8[256] ;
	ag_mg_regs_dbm_cfg_arw_chan_arb_s	cfg_arw_chan_arb[7] ;
	ag_mg_regs_register			fill9[696] ;
	ag_mg_regs_dbm_cfg_si_num_u		cfg_si_num ;
	ag_mg_regs_dbm_cfg_mi_num_u		cfg_mi_num ;
	ag_mg_regs_register			fill10[6] ;
	ag_mg_regs_dbm_cfg_periph_id_0_u	cfg_periph_id_0 ;
	ag_mg_regs_dbm_cfg_periph_id_1_u	cfg_periph_id_1 ;
	ag_mg_regs_dbm_cfg_periph_id_2_u	cfg_periph_id_2 ;
	ag_mg_regs_register			fill11 ;
	ag_mg_regs_dbm_cfg_prime_id_0_u		cfg_prime_id_0 ;
	ag_mg_regs_dbm_cfg_prime_id_1_u		cfg_prime_id_1 ;
	ag_mg_regs_dbm_cfg_prime_id_2_u		cfg_prime_id_2 ;
	ag_mg_regs_dbm_cfg_prime_id_3_u		cfg_prime_id_3 ;
} ag_mg_regs_dbm_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_dbm_reg_s *dbm_reg =
*       (volatile ag_mg_regs_dbm_reg_s *)AG_MG_REGS_DBM_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_dbm.h,v $
Revision 1.2  2017/07/28 07:58:33  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:25  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:25  srane
Initial checkin


$Endlog$
*/

