/* $Id: ag_mg_regs_trng.h,v 1.2 2017/07/28 07:58:35 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_trng.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_trng.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
 * ag_mg_regs_trng.h
 *
 * Copyright (c) 2010 LSI Inc.  All Rights Reserved
 *
 * This is unpublished proprietary information of LSI Inc.
 * This copyright notice does not evidence publication.
 *
 * The use of the software, documentation, methodologies, and other information
 * contained herein is governed solely by the associated license agreements.
 * Any inconsistent use shall be deemed to be a misappropriation of the
 * intellectual property of LSI Inc. and treated accordingly.
 *
 * The True Random Number Generator (TRNG) produces thirty-two 32-bit numbers each
 * 2500 clock cycles and stores them in a 32-word FIFO.
 *
 * See "Physical register addresses" below for macros
 * used to generate addresses for specific registers.
 *
 * Registers defined in this file :
 *
 *  RESEED
 *  POWER_OFF
 *  BIST
 *  SOFTRST
 *  R_STATUS
 *  R_OUT
 *  FIPS_OUT
 *  BIST_SIG
 *  RING_STAT
 *  SEED
 *  RING_DATA
 *  INTR_DATA
 *  INTR_EN
 *  INTR_SHDW
 *
 * Prefix naming conventions :
 *   AG_MG_REGS_XXX_RA : register/memory physical address
 *   AG_MG_REGS_XXX_RO : register/memory address offset
 *   AG_MG_REGS_XXX_RM : register mask
 *   AG_MG_REGS_XXX_BO : bit/field offset from LSB
 *   AG_MG_REGS_XXX_BM : bit/field mask
 *   AG_MG_REGS_XXX_U  : bitfields in C union typedef
 *   AG_MG_REGS_XXX_S  : registers in C struct typedef
 *   AG_MG_REGS_XX_RPT : number of identical registers in array
 *   AG_MG_REGS_XX_IVL : interval between registers in array
 *
 * NOTE: user may redefine ag_mg_regs_register
 *       in ag_mg_regs_regops.h if necessary
 * NOTE: access mode of individual bit fields matches that
 *       of containing register unless indicated otherwise
 */

#ifndef AG_MG_REGS_TRNG_REGISTERS_H
#define AG_MG_REGS_TRNG_REGISTERS_H

#include "ag_mg_regs_regops.h"


/*
 * Generated by HSI Designer release 2.3.5.
 */


/*
 * RESEED (Control register0)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_RESEED_RO                 0x00000004
#define AG_MG_REGS_RESEED_RM                 0x00000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RESEED_U
{
    struct
    {
        ag_mg_regs_register reseed;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_reseed_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_POWER_OFF_RO              0x00000008
#define AG_MG_REGS_POWER_OFF_RM              0x00000001

#define AG_MG_REGS_POWER_OFF_POWER_BO        0
#define AG_MG_REGS_POWER_OFF_POWER_BM        0x00000001

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_POWER_OFF_U
{
    struct
    {
        ag_mg_regs_register
            power : 1,
            fill0 : 31;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_power_off_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_BIST_RO                   0x0000000C
#define AG_MG_REGS_BIST_RM                   0x00000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_BIST_U
{
    struct
    {
        ag_mg_regs_register bist;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_bist_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_SOFTRST_RO                0x00000010
#define AG_MG_REGS_SOFTRST_RM                0x00000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SOFTRST_U
{
    struct
    {
        ag_mg_regs_register softrst;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_softrst_u;
#endif


/*
 * Initialization value: 0x00000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_R_STATUS_RO               0x00000040
#define AG_MG_REGS_R_STATUS_RM               0x0003FFFF

#define AG_MG_REGS_R_STATUS_GO_BO            0
#define AG_MG_REGS_R_STATUS_GO_BM            0x00000001

#define AG_MG_REGS_R_STATUS_CMD_BO           1
#define AG_MG_REGS_R_STATUS_CMD_BM           0x0000001E

#define AG_MG_REGS_R_STATUS_DON_BO           5
#define AG_MG_REGS_R_STATUS_DON_BM           0x00000020

#define AG_MG_REGS_R_STATUS_INTR_BO          6
#define AG_MG_REGS_R_STATUS_INTR_BM          0x00000040

#define AG_MG_REGS_R_STATUS_FNE_BO           7
#define AG_MG_REGS_R_STATUS_FNE_BM           0x00000080

#define AG_MG_REGS_R_STATUS_LEVEL_BO         8
#define AG_MG_REGS_R_STATUS_LEVEL_BM         0x0003FF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_R_STATUS_U
{
    struct
    {
        ag_mg_regs_register
            go : 1,
            cmd : 4,
            don : 1,
            intr : 1,
            fne : 1,
            level : 10,
            fill0 : 14;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_r_status_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_R_OUT_RO                  0x00000044
#define AG_MG_REGS_R_OUT_RM                  0xFFFFFFFF

#define AG_MG_REGS_R_OUT_R_OUT_BO            0
#define AG_MG_REGS_R_OUT_R_OUT_BM            0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_R_OUT_U
{
    struct
    {
        ag_mg_regs_register
            r_out;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_r_out_u;
#endif


/*
 * Initialization value: 0x00000009  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_FIPS_OUT_RO               0x00000048
#define AG_MG_REGS_FIPS_OUT_RM               0x0000001F

#define AG_MG_REGS_FIPS_OUT_FIPS_BO          0
#define AG_MG_REGS_FIPS_OUT_FIPS_BM          0x00000001

#define AG_MG_REGS_FIPS_OUT_MONOBIT_BO       1
#define AG_MG_REGS_FIPS_OUT_MONOBIT_BM       0x00000002

#define AG_MG_REGS_FIPS_OUT_RUNS_BO          2
#define AG_MG_REGS_FIPS_OUT_RUNS_BM          0x00000004

#define AG_MG_REGS_FIPS_OUT_LONG_RUN_BO      3
#define AG_MG_REGS_FIPS_OUT_LONG_RUN_BM      0x00000008

#define AG_MG_REGS_FIPS_OUT_POKER_BO         4
#define AG_MG_REGS_FIPS_OUT_POKER_BM         0x00000010

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_FIPS_OUT_U
{
    struct
    {
        ag_mg_regs_register
            fips : 1,
            monobit : 1,
            runs : 1,
            long_run : 1,
            poker : 1,
            fill0 : 27;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_fips_out_u;
#endif


/*
 * Initialization value: 0x00000300  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_BIST_SIG_RO               0x0000004C
#define AG_MG_REGS_BIST_SIG_RM               0xFFFFFFFF

#define AG_MG_REGS_BIST_SIG_BIST_SIG_BO      0
#define AG_MG_REGS_BIST_SIG_BIST_SIG_BM      0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_BIST_SIG_U
{
    struct
    {
        ag_mg_regs_register
            bist_sig;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_bist_sig_u;
#endif


/*
 * Initialization value: 0x00000012  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_RING_STAT_RO              0x00000050
#define AG_MG_REGS_RING_STAT_RM              0x00000001

#define AG_MG_REGS_RING_STAT_RING_STAT_BO    0
#define AG_MG_REGS_RING_STAT_RING_STAT_BM    0x00000001

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RING_STAT_U
{
    struct
    {
        ag_mg_regs_register
            ring_stat : 1,
            fill0 : 31;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ring_stat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_SEED_RO                   0x00000054
#define AG_MG_REGS_SEED_RM                   0xFFFFFFFF

#define AG_MG_REGS_SEED_SEED_BO              0
#define AG_MG_REGS_SEED_SEED_BM              0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_SEED_U
{
    struct
    {
        ag_mg_regs_register
            seed;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_seed_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_RING_DATA_RO              0x00000058
#define AG_MG_REGS_RING_DATA_RM              0xFFFFFFFF

#define AG_MG_REGS_RING_DATA_RING_DATA_BO    0
#define AG_MG_REGS_RING_DATA_RING_DATA_BM    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_RING_DATA_U
{
    struct
    {
        ag_mg_regs_register
            ring_data;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ring_data_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_INTR_DATA_RO              0x0000005C
#define AG_MG_REGS_INTR_DATA_RM              0x00000001

#define AG_MG_REGS_INTR_DATA_INTR_DATA_BO    0
#define AG_MG_REGS_INTR_DATA_INTR_DATA_BM    0x00000001

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTR_DATA_U
{
    struct
    {
        ag_mg_regs_register
            intr_data : 1,
            fill0 : 31;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intr_data_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_INTR_EN_RO                0x00000060
#define AG_MG_REGS_INTR_EN_RM                0x00000001

#define AG_MG_REGS_INTR_EN_INTR_EN_BO        0
#define AG_MG_REGS_INTR_EN_INTR_EN_BM        0x00000001

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTR_EN_U
{
    struct
    {
        ag_mg_regs_register
            intr_en : 1,
            fill0 : 31;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intr_en_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_INTR_SHDW_RO              0x00000064
#define AG_MG_REGS_INTR_SHDW_RM              0x00000001

#define AG_MG_REGS_INTR_SHDW_INTR_SHDW_BO    0
#define AG_MG_REGS_INTR_SHDW_INTR_SHDW_BM    0x00000001
/*
* Physical register addresses (for ARM accessing TRNG)
*/
#ifdef AG_MG_REGS_BUILT_FOR_DSS
#define AG_MG_REGS_TRNG_BASE               0xC3008000
#else
#define AG_MG_REGS_TRNG_BASE               0x30008000
#endif
#define AG_MG_REGS_TRNG_REG(ro)            (AG_MG_REGS_TRNG_BASE+(ro))

#define AG_MG_REGS_TRNG_EXAMPLE_RA         AG_MG_REGS_TRNG_REG(AG_MG_REGS_TRNG_EXAMPLE_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_TRNG_REGS_S
{
	ag_mg_regs_register		RESERVED_1[1] ;
	ag_mg_regs_reseed_u reseed;
	ag_mg_regs_power_off_u power_off;
	ag_mg_regs_bist_u bist;
	ag_mg_regs_softrst_u softrst;
	ag_mg_regs_register		RESERVED_2[15] ;
	ag_mg_regs_r_status_u status;
	ag_mg_regs_r_out_u r_out;
	ag_mg_regs_fips_out_u fips_out;
	ag_mg_regs_bist_sig_u bist_sig;
	ag_mg_regs_ring_stat_u ring_stat;
	ag_mg_regs_seed_u seed;
	ag_mg_regs_ring_data_u ring_data;
	ag_mg_regs_intr_data_u intr_data;
	ag_mg_regs_intr_en_u intr_en;
} ag_mg_regs_trng_reg_s;
/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_trng_reg_s *trng_regs =
*       (volatile ag_mg_regs_trng_reg_s *) AG_MG_REGS_TRNG_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_trng.h,v $
Revision 1.2  2017/07/28 07:58:35  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:29  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

