/* $Id: ag_mg_regs_tdm.h,v 1.2 2017/07/28 07:58:35 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_tdm.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_tdm.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

 /*
* ag_mg_regs_tdm.h
*
* Copyright (c) 2010 LSI Inc.  All Rights Reserved
*
* This is unpublished proprietary information of LSI Inc.
* This copyright notice does not evidence publication.
*
* The use of the software, documentation, methodologies, and other information
* contained herein is governed solely by the associated license agreements.
* Any inconsistent use shall be deemed to be a misappropriation of the
* intellectual property of LSI Inc. and treated accordingly.
*
* This file defines DSP Bus Matrix (DBM) Time Divison Multiplex (TDM)
* registers. These include registers for six serial interface units (SIU),
* six single word transfer units (SWTU), and a TDM bus arbitrator.
*
* See "Physical register addresses" below for macros
* used to generate addresses for specific registers.
*
* Registers defined in this file :
 *  TDM_SCON0
 *  TDM_SCON1
 *  TDM_SCON2
 *  TDM_SCON3
 *  TDM_SCON4
 *  TDM_SCIEN
 *  TDM_SCIEN1
 *  TDM_SCIEN2
 *  TDM_SCIEN3
 *  TDM_SCIEN4
 *  TDM_SCIEN5
 *  TDM_SCIEN6
 *  TDM_SCIEN7
 *  TDM_SCOEN
 *  TDM_SCOEN1
 *  TDM_SCOEN2
 *  TDM_SCOEN3
 *  TDM_SCOEN4
 *  TDM_SCOEN5
 *  TDM_SCOEN6
 *  TDM_SCOEN7
 *  TDM_SCOMSK
 *  TDM_SCOMK1
 *  TDM_SCOMK2
 *  TDM_SCOMK3
 *  TDM_SCOMK4
 *  TDM_SCOMK5
 *  TDM_SCOMK6
 *  TDM_SCOMK7
 *  TDM_SIDR
 *  TDM_SODR
 *  TDM_STAT
 *  TDM_SCIFR
 *  TDM_SCIFR1
 *  TDM_SCIFR2
 *  TDM_SCIFR3
 *  TDM_SCIFR4
 *  TDM_SCIFR5
 *  TDM_SCIFR6
 *  TDM_SCIFR7
 *  TDM_SCIFR8
 *  TDM_SCIFR9
 *  TDM_SCIFR10
 *  TDM_SCIFR11
 *  TDM_SCIFR12
 *  TDM_SCIFR13
 *  TDM_SCIFR14
 *  TDM_SCIFR15
 *  TDM_SCOFR
 *  TDM_SCOFR1
 *  TDM_SCOFR2
 *  TDM_SCOFR3
 *  TDM_SCOFR4
 *  TDM_SCOFR5
 *  TDM_SCOFR6
 *  TDM_SCOFR7
 *  TDM_SCOFR8
 *  TDM_SCOFR9
 *  TDM_SCOFR10
 *  TDM_SCOFR11
 *  TDM_SCOFR12
 *  TDM_SCOFR13
 *  TDM_SCOFR14
 *  TDM_SCOFR15
 *  TDM_SSTAT
 *  TDM_SCTL
 *  TDM_DCTL
 *  TDM_SSTR
 *  TDM_DSTR
 *  TDM_SRI
 *  TDM_DRI
 *  TDM_SINTC
 *  TDM_DINTC
 *  TDM_SOCE
 *  TDM_DOCE
 *  SLIM0
 *  SBAS0
 *  SCNT0
 *  SADD0
 *  DLIM0
 *  DBAS0
 *  DCNT0
 *  DADD0
 *  SLIM1
 *  SBAS1
 *  SCNT1
 *  SADD1
 *  DLIM1
 *  DBAS1
 *  DCNT1
 *  DADD1
 *  SLIM2
 *  SBAS2
 *  SCNT2
 *  SADD2
 *  DLIM2
 *  DBAS2
 *  DCNT2
 *  DADD2
 *  SLIM3
 *  SBAS3
 *  SCNT3
 *  SADD3
 *  DLIM3
 *  DBAS3
 *  DCNT3
 *  DADD3
 *  SLIM4
 *  SBAS4
 *  SCNT4
 *  SADD4
 *  DLIM4
 *  DBAS4
 *  DCNT4
 *  DADD4
 *  SLIM5
 *  SBAS5
 *  SCNT5
 *  SADD5
 *  DLIM5
 *  DBAS5
 *  DCNT5
 *  DADD5
 *  TDM_DINTMSK
 *  TDM_DINTSTAT
 *  TDM_DINTMSTAT
 *  DINTPMSK0
 *  DINTPSTAT0
 *  DINTPMSTAT0
 *  TDM_DINTMSK1
 *  TDM_DINTSTAT1
 *  TDM_DINTMSTAT1
 *  DINTPMSK1
 *  DINTPSTAT1
 *  DINTPMSTAT1
 *  TDM_DINTMSK2
 *  TDM_DINTSTAT2
 *  TDM_DINTMSTAT2
 *  DINTPMSK2
 *  DINTPSTAT2
 *  DINTPMSTAT2
 *  DINTMSK3
 *  DINTSTAT3
 *  DINTMSTAT3
 *  DINTPMSK3
 *  DINTPSTAT3
 *  DINTPMSTAT3
 *  TDM_PINTMSK
 *  TDM_PINTSTAT
 *  TDM_PINTMSTAT
 *  PINTPMSK
 *  PINTPSTAT
 *  PINTPMSTAT
 *  TDMCLKCTL
 *  TDMSYNCSEL		-- V1.1 only
 *  TDMPORTEN 		-- V1.1 only
 *  ULIM
 *  UCNT
*
* Prefix naming conventions :
*   AG_MG_REGS_XXX_RA : register/memory physical address
*   AG_MG_REGS_XXX_RO : register/memory address offset
*   AG_MG_REGS_XXX_RM : register mask
*   AG_MG_REGS_XXX_BO : bit/field offset from LSB
*   AG_MG_REGS_XXX_BM : bit/field mask
*   AG_MG_REGS_XXX_U  : bitfields in C union typedef
*   AG_MG_REGS_XXX_S  : registers in C struct typedef
*   AG_MG_REGS_XX_RPT : number of identical registers in array
*   AG_MG_REGS_XX_IVL : interval between registers in array
*
* NOTE: user may redefine ag_mg_regs_register
*       in ag_mg_regs_regops.h if necessary
* NOTE: access mode of individual bit fields matches that
*       of containing register unless indicated otherwise
*/

#ifndef AG_MG_REGS_TDM_REGISTERS_H
#define AG_MG_REGS_TDM_REGISTERS_H

#include "ag_mg_regs_regops.h"


/*
 * Generated by HSI Designer release 2.3.5.
 */

/*
 * TDM_SCON0 (TDM SIU<0-1> Input/Output General Control Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCON0_RO                  0x00000000
#define AG_MG_REGS_TDM_SCON0_RM                  0xFFFFFFFF

#define AG_MG_REGS_TDM_SCON0_IFORMAT_BO          0
#define AG_MG_REGS_TDM_SCON0_IFORMAT_BM          0x00000003

#define AG_MG_REGS_TDM_SCON0_IMSB_BO             2
#define AG_MG_REGS_TDM_SCON0_IMSB_BM             0x00000004

#define AG_MG_REGS_TDM_SCON0_ISIZE_BO            3
#define AG_MG_REGS_TDM_SCON0_ISIZE_BM            0x00000078

#define AG_MG_REGS_TDM_SCON0_ICHFOREN_BO         7
#define AG_MG_REGS_TDM_SCON0_ICHFOREN_BM         0x00000080

#define AG_MG_REGS_TDM_SCON0_OFORMAT_BO          8
#define AG_MG_REGS_TDM_SCON0_OFORMAT_BM          0x00000300

#define AG_MG_REGS_TDM_SCON0_OMSB_BO             10
#define AG_MG_REGS_TDM_SCON0_OMSB_BM             0x00000400

#define AG_MG_REGS_TDM_SCON0_OSIZE_BO            11
#define AG_MG_REGS_TDM_SCON0_OSIZE_BM            0x00007800

#define AG_MG_REGS_TDM_SCON0_OCHFOREN_BO         15
#define AG_MG_REGS_TDM_SCON0_OCHFOREN_BM         0x00008000

#define AG_MG_REGS_TDM_SCON0_IFSA_BO             16
#define AG_MG_REGS_TDM_SCON0_IFSA_BM             0x00010000

#define AG_MG_REGS_TDM_SCON0_IFSK_BO             17
#define AG_MG_REGS_TDM_SCON0_IFSK_BM             0x00020000

#define AG_MG_REGS_TDM_SCON0_ICKA_BO             18
#define AG_MG_REGS_TDM_SCON0_ICKA_BM             0x00040000

#define AG_MG_REGS_TDM_SCON0_ICKK_BO             19
#define AG_MG_REGS_TDM_SCON0_ICKK_BM             0x00080000

#define AG_MG_REGS_TDM_SCON0_OFSA_BO             20
#define AG_MG_REGS_TDM_SCON0_OFSA_BM             0x00100000

#define AG_MG_REGS_TDM_SCON0_OFSK_BO             21
#define AG_MG_REGS_TDM_SCON0_OFSK_BM             0x00200000

#define AG_MG_REGS_TDM_SCON0_OCKA_BO             22
#define AG_MG_REGS_TDM_SCON0_OCKA_BM             0x00400000

#define AG_MG_REGS_TDM_SCON0_OCKK_BO             23
#define AG_MG_REGS_TDM_SCON0_OCKK_BM             0x00800000

#define AG_MG_REGS_TDM_SCON0_SIOLB_BO            24
#define AG_MG_REGS_TDM_SCON0_SIOLB_BM            0x01000000

#define AG_MG_REGS_TDM_SCON0_EXTLB_BO            25
#define AG_MG_REGS_TDM_SCON0_EXTLB_BM            0x02000000

#define AG_MG_REGS_TDM_SCON0_SIUCLKEN_BO         26
#define AG_MG_REGS_TDM_SCON0_SIUCLKEN_BM         0x04000000

#define AG_MG_REGS_TDM_SCON0_IINTSEL_BO          27
#define AG_MG_REGS_TDM_SCON0_IINTSEL_BM          0x18000000

#define AG_MG_REGS_TDM_SCON0_OINTSEL_BO          29
#define AG_MG_REGS_TDM_SCON0_OINTSEL_BM          0x60000000

#define AG_MG_REGS_TDM_SCON0_SIUCLKCTL_BO        31
#define AG_MG_REGS_TDM_SCON0_SIUCLKCTL_BM        0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCON0_U
{
    struct
    {
        ag_mg_regs_register
            iformat : 2,
            imsb : 1,
            isize : 4,
            ichforen : 1,
            oformat : 2,
            omsb : 1,
            osize : 4,
            ochforen : 1,
            ifsa : 1,
            ifsk : 1,
            icka : 1,
            ickk : 1,
            ofsa : 1,
            ofsk : 1,
            ocka : 1,
            ockk : 1,
            siolb : 1,
            extlb : 1,
            siuclken : 1,
            iintsel : 2,
            ointsel : 2,
            siuclkctl : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_scon0_u;
#endif


/*
 * TDM_SCON1 (TDM SIU<0-1> Input Frame Control Registers)
 * Initialization value: 0x00004000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCON1_RO                  0x00000004
#define AG_MG_REGS_TDM_SCON1_RM                  0xFFFFFFFF

#define AG_MG_REGS_TDM_SCON1_IFLIM_BO            0
#define AG_MG_REGS_TDM_SCON1_IFLIM_BM            0x000000FF

#define AG_MG_REGS_TDM_SCON1_IFRAME_BO           8
#define AG_MG_REGS_TDM_SCON1_IFRAME_BM           0x00000100

#define AG_MG_REGS_TDM_SCON1_IFSDLY_BO           9
#define AG_MG_REGS_TDM_SCON1_IFSDLY_BM           0x00007E00

#define AG_MG_REGS_TDM_SCON1_IRESET_BO           15
#define AG_MG_REGS_TDM_SCON1_IRESET_BM           0x00008000

#define AG_MG_REGS_TDM_SCON1_ICKE_BO             16
#define AG_MG_REGS_TDM_SCON1_ICKE_BM             0x00010000

#define AG_MG_REGS_TDM_SCON1_IFSE_BO             17
#define AG_MG_REGS_TDM_SCON1_IFSE_BM             0x00020000

#define AG_MG_REGS_TDM_SCON1_ICHDLY_BO           18
#define AG_MG_REGS_TDM_SCON1_ICHDLY_BM           0x03FC0000

#define AG_MG_REGS_TDM_SCON1_ICHDLY_EN_BO        26
#define AG_MG_REGS_TDM_SCON1_ICHDLY_EN_BM        0x04000000

#define AG_MG_REGS_TDM_SCON1_IPARITYEN_BO        27
#define AG_MG_REGS_TDM_SCON1_IPARITYEN_BM        0x08000000

#define AG_MG_REGS_TDM_SCON1_IPARMODE_BO         28
#define AG_MG_REGS_TDM_SCON1_IPARMODE_BM         0x10000000

#define AG_MG_REGS_TDM_SCON1_IPARINTEN_BO        29
#define AG_MG_REGS_TDM_SCON1_IPARINTEN_BM        0x20000000

#define AG_MG_REGS_TDM_SCON1_ICMODE_BO           30
#define AG_MG_REGS_TDM_SCON1_ICMODE_BM           0x40000000

#define AG_MG_REGS_TDM_SCON1_I2XDLY_BO           31
#define AG_MG_REGS_TDM_SCON1_I2XDLY_BM           0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCON1_U
{
    struct
    {
        ag_mg_regs_register
            iflim : 8,
            iframe : 1,
            ifsdly : 6,
            ireset : 1,
            icke : 1,
            ifse : 1,
            ichdly : 8,
            ichdly_en : 1,
            iparityen : 1,
            iparmode : 1,
            iparinten : 1,
            icmode : 1,
            i2xdly : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_scon1_u;
#endif


/*
 * TDM_SCON2 (TDM SIU<0-1> Output Frame Control Registers)
 * Initialization value: 0x00004000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCON2_RO                  0x00000008
#define AG_MG_REGS_TDM_SCON2_RM                  0x5FFFFFFF

#define AG_MG_REGS_TDM_SCON2_OFLIM_BO            0
#define AG_MG_REGS_TDM_SCON2_OFLIM_BM            0x000000FF

#define AG_MG_REGS_TDM_SCON2_OFRAME_BO           8
#define AG_MG_REGS_TDM_SCON2_OFRAME_BM           0x00000100

#define AG_MG_REGS_TDM_SCON2_OFSDLY_BO           9
#define AG_MG_REGS_TDM_SCON2_OFSDLY_BM           0x00007E00

#define AG_MG_REGS_TDM_SCON2_ORESET_BO           15
#define AG_MG_REGS_TDM_SCON2_ORESET_BM           0x00008000

#define AG_MG_REGS_TDM_SCON2_OCKE_BO             16
#define AG_MG_REGS_TDM_SCON2_OCKE_BM             0x00010000

#define AG_MG_REGS_TDM_SCON2_OFSE_BO             17
#define AG_MG_REGS_TDM_SCON2_OFSE_BM             0x00020000

#define AG_MG_REGS_TDM_SCON2_OCHDLY_BO           18
#define AG_MG_REGS_TDM_SCON2_OCHDLY_BM           0x03FC0000

#define AG_MG_REGS_TDM_SCON2_OCHDLY_EN_BO   	 26
#define AG_MG_REGS_TDM_SCON2_OCHDLY_EN_BM	     0x04000000

#define AG_MG_REGS_TDM_SCON2_OPARITYEN_BO        27
#define AG_MG_REGS_TDM_SCON2_OPARITYEN_BM        0x08000000

#define AG_MG_REGS_TDM_SCON2_OPARMODE_BO         28
#define AG_MG_REGS_TDM_SCON2_OPARMODE_BM         0x10000000

#define AG_MG_REGS_TDM_SCON2_OCMODE_BO           30
#define AG_MG_REGS_TDM_SCON2_OCMODE_BM           0x40000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCON2_U
{
    struct
    {
        ag_mg_regs_register
            oflim : 8,
            oframe : 1,
            ofsdly : 6,
            oreset : 1,
            ocke : 1,
            ofse : 1,
            ochdly : 8,
            ochdly_en : 1,
            oparityen : 1,
            oparmode : 1,
            fill1 : 1,
            ocmode : 1,
            fill0 : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_scon2_u;
#endif


/*
 * TDM_SCON3 (TDM SIU<0-1> Input/Output Active Clock Control Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCON3_RO                  0x0000000C
#define AG_MG_REGS_TDM_SCON3_RM                  0x000003FF

#define AG_MG_REGS_TDM_SCON3_AGCKLIM_BO          0
#define AG_MG_REGS_TDM_SCON3_AGCKLIM_BM          0x000000FF

#define AG_MG_REGS_TDM_SCON3_AGNEXT_BO           8
#define AG_MG_REGS_TDM_SCON3_AGNEXT_BM           0x00000100

#define AG_MG_REGS_TDM_SCON3_SCKK_BO             9
#define AG_MG_REGS_TDM_SCON3_SCKK_BM             0x00000200

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCON3_U
{
    struct
    {
        ag_mg_regs_register
            agcklim : 8,
            agnext : 1,
            sckk : 1,
            fill0 : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_scon3_u;
#endif


/*
 * TDM_SCON4 (TDM SIU<0-1> Input/Output Active Frame Sync Control Registers)
 * Initialization value: 0x00008000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCON4_RO                  0x00000010
#define AG_MG_REGS_TDM_SCON4_RM                  0x0000DFFF

#define AG_MG_REGS_TDM_SCON4_AGFSLIM_BO          0
#define AG_MG_REGS_TDM_SCON4_AGFSLIM_BM          0x00001FFF

#define AG_MG_REGS_TDM_SCON4_AGSYNC_BO           14
#define AG_MG_REGS_TDM_SCON4_AGSYNC_BM           0x00004000

#define AG_MG_REGS_TDM_SCON4_AGRESET_BO          15
#define AG_MG_REGS_TDM_SCON4_AGRESET_BM          0x00008000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCON4_U
{
    struct
    {
        ag_mg_regs_register
            agfslim : 13,
            fill1 : 1,
            agsync : 1,
            agreset : 1,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_scon4_u;
#endif


/*
 * TDM_SCIEN<0-7> (TDM SIU<0-1> Input Channel Enable Control Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCIEN_RO                  0x00000014
#define AG_MG_REGS_TDM_SCIEN_RM                  0xFFFFFFFF
#define AG_MG_REGS_TDM_SCIEN_RPT				 0x8
#define AG_MG_REGS_TDM_SCIEN_IVL				 0x4

#define AG_MG_REGS_TDM_SCIEN_ICHEN_BO            0
#define AG_MG_REGS_TDM_SCIEN_ICHEN_BM            0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCIEN_U
{
    struct
    {
        ag_mg_regs_register
            ichen;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_scien_u;
#endif


/*
 * TDM_SCOEN<0-7> (TDM SIU<0-1> Output Channel Enable Control Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCOEN_RO                  0x00000034
#define AG_MG_REGS_TDM_SCOEN_RM                  0xFFFFFFFF
#define AG_MG_REGS_TDM_SCOEN_RPT				 0x8
#define AG_MG_REGS_TDM_SCOEN_IVL				 0x4

#define AG_MG_REGS_TDM_SCOEN_OCHEN_BO            0
#define AG_MG_REGS_TDM_SCOEN_OCHEN_BM            0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCOEN_U
{
    struct
    {
        ag_mg_regs_register
            ochen;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_scoen_u;
#endif


/*
 * TDM_SCOMSK<0-7> (TDM SIU<0-1> Output Channel Mask Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCOMSK_RO                 0x00000054
#define AG_MG_REGS_TDM_SCOMSK_RM                 0xFFFFFFFF
#define AG_MG_REGS_TDM_SCOMSK_RPT				 0x8
#define AG_MG_REGS_TDM_SCOMSK_IVL				 0x4

#define AG_MG_REGS_TDM_SCOMSK_OCHMK_BO          0
#define AG_MG_REGS_TDM_SCOMSK_OCHMK_BM          0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCOMSK_U
{
    struct
    {
        ag_mg_regs_register
            ochmsk;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_scomsk_u;
#endif


/*
 * TDM_SIDR (TDM SIU<0-1> Input Data Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_TDM_SIDR_RO                   0x00000074
#define AG_MG_REGS_TDM_SIDR_RM                   0xFFFFFFFF

#define AG_MG_REGS_TDM_SIDR_TDM_SIDR_BO          0
#define AG_MG_REGS_TDM_SIDR_TDM_SIDR_BM          0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SIDR_U
{
    struct
    {
        ag_mg_regs_register
            sidr;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_sidr_u;
#endif


/*
 * TDM_SODR (TDM SIU<0-1> Output Data Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_TDM_SODR_RO                   0x00000078
#define AG_MG_REGS_TDM_SODR_RM                   0xFFFFFFFF

#define AG_MG_REGS_TDM_SODR_TDM_SODR_BO          0
#define AG_MG_REGS_TDM_SODR_TDM_SODR_BM          0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SODR_U
{
    struct
    {
        ag_mg_regs_register
            sodr;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_sodr_u;
#endif


/*
 * TDM_STAT (TDM SIU<0-1> Input/Output General Status Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_STAT_RO                   0x0000007C
#define AG_MG_REGS_TDM_STAT_RM                   0x00FF3FFF

#define AG_MG_REGS_TDM_STAT_SIDV_BO              0
#define AG_MG_REGS_TDM_STAT_SIDV_BM              0x00000001

#define AG_MG_REGS_TDM_STAT_SIBV_BO              1
#define AG_MG_REGS_TDM_STAT_SIBV_BM              0x00000002

#define AG_MG_REGS_TDM_STAT_IACTIVE_BO           2
#define AG_MG_REGS_TDM_STAT_IACTIVE_BM           0x00000004

#define AG_MG_REGS_TDM_STAT_SODV_BO              3
#define AG_MG_REGS_TDM_STAT_SODV_BM              0x00000008

#define AG_MG_REGS_TDM_STAT_IFERR_BO             4
#define AG_MG_REGS_TDM_STAT_IFERR_BM             0x00000010

#define AG_MG_REGS_TDM_STAT_OFERR_BO             5
#define AG_MG_REGS_TDM_STAT_OFERR_BM             0x00000020

#define AG_MG_REGS_TDM_STAT_IOFLOW_BO            6
#define AG_MG_REGS_TDM_STAT_IOFLOW_BM            0x00000040

#define AG_MG_REGS_TDM_STAT_OUFLOW_BO            7
#define AG_MG_REGS_TDM_STAT_OUFLOW_BM            0x00000080

#define AG_MG_REGS_TDM_STAT_OACTIVE_BO           8
#define AG_MG_REGS_TDM_STAT_OACTIVE_BM           0x00000100

#define AG_MG_REGS_TDM_STAT_OFSDROP_BO           9
#define AG_MG_REGS_TDM_STAT_OFSDROP_BM           0x00000200

#define AG_MG_REGS_TDM_STAT_SIDFULL_BO           10
#define AG_MG_REGS_TDM_STAT_SIDFULL_BM           0x00000400

#define AG_MG_REGS_TDM_STAT_SODFULL_BO           11
#define AG_MG_REGS_TDM_STAT_SODFULL_BM           0x00000800

#define AG_MG_REGS_TDM_STAT_IPARERR_BO           12
#define AG_MG_REGS_TDM_STAT_IPARERR_BM           0x00001000

#define AG_MG_REGS_TDM_STAT_IMULTPERR_BO         13
#define AG_MG_REGS_TDM_STAT_IMULTPERR_BM         0x00002000

#define AG_MG_REGS_TDM_STAT_IPARERRCH_BO         16
#define AG_MG_REGS_TDM_STAT_IPARERRCH_BM         0x00FF0000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_STAT_U
{
    struct
    {
        ag_mg_regs_register
            sidv : 1,
            sibv : 1,
            iactive : 1,
            sodv : 1,
            iferr : 1,
            oferr : 1,
            ioflow : 1,
            ouflow : 1,
            oactive : 1,
            ofsdrop : 1,
            sidfull : 1,
            sodfull : 1,
            iparerr : 1,
            imultperr : 1,
            fill1 : 2,
            iparerrch : 8,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_stat_u;
#endif


/*
 * TDM_SCIFR<0-15> (TDM SIU<0-1> Channel Input Format Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCIFR_RO                  0x00000080
#define AG_MG_REGS_TDM_SCIFR_RM                  0xFFFFFFFF
#define AG_MG_REGS_TDM_SCIFR_RPT                 0x10
#define AG_MG_REGS_TDM_SCIFR_IVL				 0x4

#define AG_MG_REGS_TDM_SCIFR_ICHFOR0_BO          0
#define AG_MG_REGS_TDM_SCIFR_ICHFOR0_BM          0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCIFR_U
{
    struct
    {
        ag_mg_regs_register
            ichfor0;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_scifr_u;
#endif


/*
 * TDM_SCOFR<0-15> (TDM SIU<0-1> Channel Input Format Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCOFR_RO                  0x000000C0
#define AG_MG_REGS_TDM_SCOFR_RM                  0xFFFFFFFF
#define AG_MG_REGS_TDM_SCOFR_RPT                 0x10
#define AG_MG_REGS_TDM_SCOFR_IVL				 0x4

#define AG_MG_REGS_TDM_SCOFR_OCHFOR0_BO          0
#define AG_MG_REGS_TDM_SCOFR_OCHFOR0_BM          0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCOFR_U
{
    struct
    {
        ag_mg_regs_register
            ochfor0;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_scofr_u;
#endif


/*
 * TDM_SSTAT (TDM SWTU<0-1> Status Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SSTAT_RO                  0x00000800
#define AG_MG_REGS_TDM_SSTAT_RM                  0x000000FF

#define AG_MG_REGS_TDM_SSTAT_DERR_BO             0
#define AG_MG_REGS_TDM_SSTAT_DERR_BM             0x00000001

#define AG_MG_REGS_TDM_SSTAT_SERR_BO             1
#define AG_MG_REGS_TDM_SSTAT_SERR_BM             0x00000002

#define AG_MG_REGS_TDM_SSTAT_DPERR_BO            2
#define AG_MG_REGS_TDM_SSTAT_DPERR_BM            0x00000004

#define AG_MG_REGS_TDM_SSTAT_SPERR_BO            3
#define AG_MG_REGS_TDM_SSTAT_SPERR_BM            0x00000008

#define AG_MG_REGS_TDM_SSTAT_DRDY_BO             4
#define AG_MG_REGS_TDM_SSTAT_DRDY_BM             0x00000010

#define AG_MG_REGS_TDM_SSTAT_SRDY_BO             5
#define AG_MG_REGS_TDM_SSTAT_SRDY_BM             0x00000020

#define AG_MG_REGS_TDM_SSTAT_DBSY_BO             6
#define AG_MG_REGS_TDM_SSTAT_DBSY_BM             0x00000040

#define AG_MG_REGS_TDM_SSTAT_SBSY_BO             7
#define AG_MG_REGS_TDM_SSTAT_SBSY_BM             0x00000080

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SSTAT_U
{
    struct
    {
        ag_mg_regs_register
            derr : 1,
            serr : 1,
            dperr : 1,
            sperr : 1,
            drdy : 1,
            srdy : 1,
            dbsy : 1,
            sbsy : 1,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_sstat_u;
#endif


/*
 * TDM_SCTL (TDM SWTU<0-1> Source Control Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCTL_RO                   0x00000804
#define AG_MG_REGS_TDM_SCTL_RM                   0x000003FF

#define AG_MG_REGS_TDM_SCTL_SHALT_BO             0
#define AG_MG_REGS_TDM_SCTL_SHALT_BM             0x00000001

#define AG_MG_REGS_TDM_SCTL_SRUN_BO              1
#define AG_MG_REGS_TDM_SCTL_SRUN_BM              0x00000002

#define AG_MG_REGS_TDM_SCTL_SAUTOLOAD_BO         2
#define AG_MG_REGS_TDM_SCTL_SAUTOLOAD_BM         0x00000004

#define AG_MG_REGS_TDM_SCTL_SSIGCON_BO           3
#define AG_MG_REGS_TDM_SCTL_SSIGCON_BM           0x00000038

#define AG_MG_REGS_TDM_SCTL_SPOSTMOD_BO          6
#define AG_MG_REGS_TDM_SCTL_SPOSTMOD_BM          0x000000C0

#define AG_MG_REGS_TDM_SCTL_SERRINTEN_BO         8
#define AG_MG_REGS_TDM_SCTL_SERRINTEN_BM         0x00000100

#define AG_MG_REGS_TDM_SCTL_SBACKMD_BO           9
#define AG_MG_REGS_TDM_SCTL_SBACKMD_BM           0x00000200

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCTL_U
{
    struct
    {
        ag_mg_regs_register
            shalt : 1,
            srun : 1,
            sautoload : 1,
            ssigcon : 3,
            spostmod : 2,
            serrinten : 1,
            sbackmd : 1,
            fill0 : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_sctl_u;
#endif


/*
 * TDM_DCTL (TDM SWTU<0-1> Destination Control Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_DCTL_RO                   0x00000808
#define AG_MG_REGS_TDM_DCTL_RM                   0x000003FF

#define AG_MG_REGS_TDM_DCTL_DHALT_BO             0
#define AG_MG_REGS_TDM_DCTL_DHALT_BM             0x00000001

#define AG_MG_REGS_TDM_DCTL_DRUN_BO              1
#define AG_MG_REGS_TDM_DCTL_DRUN_BM              0x00000002

#define AG_MG_REGS_TDM_DCTL_DAUTOLOAD_BO         2
#define AG_MG_REGS_TDM_DCTL_DAUTOLOAD_BM         0x00000004

#define AG_MG_REGS_TDM_DCTL_DSIGCON_BO           3
#define AG_MG_REGS_TDM_DCTL_DSIGCON_BM           0x00000038

#define AG_MG_REGS_TDM_DCTL_DPOSTMOD_BO          6
#define AG_MG_REGS_TDM_DCTL_DPOSTMOD_BM          0x000000C0

#define AG_MG_REGS_TDM_DCTL_DERRINTEN_BO         8
#define AG_MG_REGS_TDM_DCTL_DERRINTEN_BM         0x00000100

#define AG_MG_REGS_TDM_DCTL_DBACKMD_BO           9
#define AG_MG_REGS_TDM_DCTL_DBACKMD_BM           0x00000200

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DCTL_U
{
    struct
    {
        ag_mg_regs_register
            dhalt : 1,
            drun : 1,
            dautoload : 1,
            dsigcon : 3,
            dpostmod : 2,
            derrinten : 1,
            dbackmd : 1,
            fill0 : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dctl_u;
#endif



/*
 * TDM_SINTC (TDM SWTU<0-1> Source Interrupt Control Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SINTC_RO                  0x00000810
#define AG_MG_REGS_TDM_SINTC_RM                  0x000003FF

#define AG_MG_REGS_TDM_SINTC_TDM_SINTC_BO        0
#define AG_MG_REGS_TDM_SINTC_TDM_SINTC_BM        0x000003FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SINTC_U
{
    struct
    {
        ag_mg_regs_register
            sintc : 10,
            fill0 : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_sintc_u;
#endif


/*
 * TDM_DINTC (TDM SWTU<0-1> Destination Interrupt Control Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_DINTC_RO                  0x00000814
#define AG_MG_REGS_TDM_DINTC_RM                  0x000003FF

#define AG_MG_REGS_TDM_DINTC_TDM_DINTC_BO        0
#define AG_MG_REGS_TDM_DINTC_TDM_DINTC_BM        0x000003FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DINTC_U
{
    struct
    {
        ag_mg_regs_register
            dintc : 10,
            fill0 : 22;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dintc_u;
#endif


/*
 * TDM_SOCE (TDM SWTU<0-1> Source DSS OCE Breakpoint Select Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SOCE_RO                   0x00000818
#define AG_MG_REGS_TDM_SOCE_RM                   0x0000000F

#define AG_MG_REGS_TDM_SOCE_TDM_SOCE_SEL_BO      0
#define AG_MG_REGS_TDM_SOCE_TDM_SOCE_SEL_BM      0x00000007

#define AG_MG_REGS_TDM_SOCE_TDM_SOCE_EN_BO       0
#define AG_MG_REGS_TDM_SOCE_TDM_SOCE_EN_BM       0x00000008

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SOCE_U
{
    struct
    {
        ag_mg_regs_register
            soce_sel : 3,
            soce_en : 1,
            fill0 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_soce_u;
#endif


/*
 * TDM_DOCE (TDM SWTU<0-1> Desination DSS OCE Breakpoint Select Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_DOCE_RO                   0x0000081C
#define AG_MG_REGS_TDM_DOCE_RM                   0x0000000F

#define AG_MG_REGS_TDM_DOCE_TDM_DOCE_SEL_BO      0
#define AG_MG_REGS_TDM_DOCE_TDM_DOCE_SEL_BM      0x00000007

#define AG_MG_REGS_TDM_DOCE_TDM_DOCE_EN_BO       0
#define AG_MG_REGS_TDM_DOCE_TDM_DOCE_EN_BM       0x00000007


#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DOCE_U
{
    struct
    {
        ag_mg_regs_register
            doce_sel : 3,
            doce_en : 1,
            fill0 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_doce_u;
#endif

/*
 * TDM_SSTR (TDM SWTU<0-1> Source Stride Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SSTR_RO                   0x00000820
#define AG_MG_REGS_TDM_SSTR_RM                   0x00007FFF

#define AG_MG_REGS_TDM_SSTR_TDM_SSTR_BO          0
#define AG_MG_REGS_TDM_SSTR_TDM_SSTR_BM          0x00007FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SSTR_U
{
    struct
    {
        ag_mg_regs_register
            sstr : 15,
            fill0 : 17;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_sstr_u;
#endif


/*
 * TDM_DSTR (TDM SWTU<0-1> Destination Stride Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_DSTR_RO                   0x00000824
#define AG_MG_REGS_TDM_DSTR_RM                   0x00007FFF

#define AG_MG_REGS_TDM_DSTR_TDM_DSTR_BO          0
#define AG_MG_REGS_TDM_DSTR_TDM_DSTR_BM          0x00007FFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DSTR_U
{
    struct
    {
        ag_mg_regs_register
            dstr : 15,
            fill0 : 17;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dstr_u;
#endif




/*
 * TDM_SRI (TDM SWTU<0-1> Source Reindex Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SRI_RO                    0x00000828
#define AG_MG_REGS_TDM_SRI_RM                    0x000FFFFF

#define AG_MG_REGS_TDM_SRI_TDM_SRI_BO            0
#define AG_MG_REGS_TDM_SRI_TDM_SRI_BM            0x000FFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SRI_U
{
    struct
    {
        ag_mg_regs_register
            sri : 20,
            fill0 : 12;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_sri_u;
#endif


/*
 * TDM_DRI (TDM SWTU<0-1> Destination Reindex Registers)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_DRI_RO                    0x0000082C
#define AG_MG_REGS_TDM_DRI_RM                    0x000FFFFF

#define AG_MG_REGS_TDM_DRI_TDM_DRI_BO            0
#define AG_MG_REGS_TDM_DRI_TDM_DRI_BM            0x000FFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DRI_U
{
    struct
    {
        ag_mg_regs_register
            dri : 20,
            fill0 : 12;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dri_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SADD_RO                      0x00010000
#define AG_MG_REGS_TDM_SADD_RM                      0xFFFFFFFF
#define AG_MG_REGS_TDM_SADD_RPT                     256
#define AG_MG_REGS_TDM_SADD_IVL                     0x10

#define AG_MG_REGS_TDM_SADD_SADD_BO             	0
#define AG_MG_REGS_TDM_SADD_SADD_BM             	0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SADD_U
{
    struct
    {
        ag_mg_regs_register
            sadd;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_sadd_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SBAS_RO                      0x00010004
#define AG_MG_REGS_TDM_SBAS_RM                      0xFFFFFFFF
#define AG_MG_REGS_TDM_SBAS_RPT                     256
#define AG_MG_REGS_TDM_SBAS_IVL                     0x10

#define AG_MG_REGS_TDM_SBAS_SBAS_BO             	0
#define AG_MG_REGS_TDM_SBAS_SBAS_BM            		0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SBAS_U
{
    struct
    {
        ag_mg_regs_register
            sbas;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_sbas_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SCNT_RO                      0x00010008
#define AG_MG_REGS_TDM_SCNT_RM                      0x001FFFFF
#define AG_MG_REGS_TDM_SCNT_RPT                     256
#define AG_MG_REGS_TDM_SCNT_IVL                     0x10

#define AG_MG_REGS_TDM_SCNT_SCNT_BO             	0
#define AG_MG_REGS_TDM_SCNT_SCNT_BM             	0x001FFFFF

#define AG_MG_REGS_TDM_SCNT_SCOL_BO					0
#define AG_MG_REGS_TDM_SCNT_SCOL_BM					0x000000FF

#define AG_MG_REGS_TDM_SCNT_SROW_BO					8
#define AG_MG_REGS_TDM_SCNT_SROW_BM					0x0001FF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SCNT_U
{
	struct
	{
		ag_mg_regs_register
			scol : 8,
			srow : 13,
			fill0 : 11;
	} fields_old;
    struct
    {
        ag_mg_regs_register
            scnt : 21,
            fill0 : 11;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_scnt_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_SLIM_RO                      0x0001000C
#define AG_MG_REGS_TDM_SLIM_RM                      0xFC1FFFFF
#define AG_MG_REGS_TDM_SLIM_RPT                     256
#define AG_MG_REGS_TDM_SLIM_IVL                     0x10

#define AG_MG_REGS_TDM_SLIM_SLASTCOL_BO				0
#define AG_MG_REGS_TDM_SLIM_SLASTCOL_BM				0x000000FF

#define AG_MG_REGS_TDM_SLIM_SLASTROW_BO				8
#define AG_MG_REGS_TDM_SLIM_SLASTRPW_BM				0x001FFF00

#define AG_MG_REGS_TDM_SLIM_SLIM_BO					0
#define AG_MG_REGS_TDM_SLIM_SLIM_BM					0x001FFFFF

#define AG_MG_REGS_TDM_SLIM_SUCSEL_BO               26
#define AG_MG_REGS_TDM_SLIM_SUCSEL_BM               0x7C000000

#define AG_MG_REGS_TDM_SLIM_SUCEN_BO                31
#define AG_MG_REGS_TDM_SLIM_SUCEN_BM                0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_SLIM0_U
{
    struct
    {
        ag_mg_regs_register
            slastcol : 8,
			slastrow : 13,
            fill0 : 11;
    } fields_old;
    struct
    {
        ag_mg_regs_register
            slim : 21,
            fill0 : 5,
            sucsel : 5,
            sucen : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_slim_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_DADD_RO                      0x00011000
#define AG_MG_REGS_TDM_DADD_RM                      0xFFFFFFFF
#define AG_MG_REGS_TDM_DADD_RPT                     256
#define AG_MG_REGS_TDM_DADD_IVL                     0x10

#define AG_MG_REGS_TDM_DADD_DADD_BO            	 	0
#define AG_MG_REGS_TDM_DADD_DADD_BM             	0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DADD_U
{
    struct
    {
        ag_mg_regs_register
            dadd;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dadd_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_DBAS_RO                      0x00011004
#define AG_MG_REGS_TDM_DBAS_RM                      0xFFFFFFFF
#define AG_MG_REGS_TDM_DBAS_RPT                     256
#define AG_MG_REGS_TDM_DBAS_IVL                     0x10

#define AG_MG_REGS_TDM_DBAS_DBAS_BO             	0
#define AG_MG_REGS_TDM_DBAS_DBAS_BM             	0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DBAS_U
{
    struct
    {
        ag_mg_regs_register
            dbas;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dbas_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_DCNT_RO                      0x00011008
#define AG_MG_REGS_TDM_DCNT_RM                      0x001FFFFF
#define AG_MG_REGS_TDM_DCNT_RPT                     256
#define AG_MG_REGS_TDM_DCNT_IVL                     0x10

#define AG_MG_REGS_TDM_DCNT_DCNT_BO             	0
#define AG_MG_REGS_TDM_DCNT_DCNT_BM             	0x001FFFFF

#define AG_MG_REGS_TDM_DCNT_DCOL_BO					0
#define AG_MG_REGS_TDM_DCNT_DCOL_BM					0x000000FF

#define AG_MG_REGS_TDM_DCNT_DROW_BO					8
#define AG_MG_REGS_TDM_DCNT_DROW_BM					0x0001FF00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DCNT_U
{
	struct
	{
		ag_mg_regs_register
			dcol : 8,
			drow : 13,
			fill0 : 11;
	} fields_old;
    struct
    {
        ag_mg_regs_register
            dcnt : 21,
            fill0 : 11;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dcnt_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_DLIM_RO                      0x0001100C
#define AG_MG_REGS_TDM_DLIM_RM                      0xFC1FFFFF
#define AG_MG_REGS_TDM_DLIM_RPT                     256
#define AG_MG_REGS_TDM_DLIM_IVL                     0x10

#define AG_MG_REGS_TDM_DLIM_DLASTCOL_BO				0
#define AG_MG_REGS_TDM_DLIM_DLASTCOL_BM				0x000000FF

#define AG_MG_REGS_TDM_DLIM_DLASTROW_BO				8
#define AG_MG_REGS_TDM_DLIM_DLASTROW_BM				0x001FFF00

#define AG_MG_REGS_TDM_DLIM_DUCSEL_BO               26
#define AG_MG_REGS_TDM_DLIM_DUCSEL_BM               0x7C000000

#define AG_MG_REGS_TDM_DLIM_DUCEN_BO                31
#define AG_MG_REGS_TDM_DLIM_DUCEN_BM                0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DLIM_U
{
    struct
    {
        ag_mg_regs_register
            dlastcol : 8,
			dlastrow : 13,
            fill0 : 11;
    } fields_old;
    struct
    {
        ag_mg_regs_register
            dlim : 21,
            fill0 : 5,
            ducsel : 5,
            ducen : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dlim_u;
#endif

/*
 * TDM_DINTMSK<0-2> (TDM Interrupt Mask Registers for DSS Cores)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_DINTMSK_RO                0x00001000
#define AG_MG_REGS_TDM_DINTMSK_RM                0x00FFFFFF
#define AG_MG_REGS_TDM_DINTMSK_RPT				 0x4
#define AG_MG_REGS_TDM_DINTMSK_IVL				 0x18

#define AG_MG_REGS_TDM_DINTMSK_DSIMSK0_BO        0
#define AG_MG_REGS_TDM_DINTMSK_DSIMSK0_BM        0x00000001

#define AG_MG_REGS_TDM_DINTMSK_DSOMSK0_BO        1
#define AG_MG_REGS_TDM_DINTMSK_DSOMSK0_BM        0x00000002

#define AG_MG_REGS_TDM_DINTMSK_DDSMSK0_BO        2
#define AG_MG_REGS_TDM_DINTMSK_DDSMSK0_BM        0x00000004

#define AG_MG_REGS_TDM_DINTMSK_DDDMSK0_BO        3
#define AG_MG_REGS_TDM_DINTMSK_DDDMSK0_BM        0x00000008

#define AG_MG_REGS_TDM_DINTMSK_DSIMSK1_BO        4
#define AG_MG_REGS_TDM_DINTMSK_DSIMSK1_BM        0x00000010

#define AG_MG_REGS_TDM_DINTMSK_DSOMSK1_BO        5
#define AG_MG_REGS_TDM_DINTMSK_DSOMSK1_BM        0x00000020

#define AG_MG_REGS_TDM_DINTMSK_DDSMSK1_BO        6
#define AG_MG_REGS_TDM_DINTMSK_DDSMSK1_BM        0x00000040

#define AG_MG_REGS_TDM_DINTMSK_DDDMSK1_BO        7
#define AG_MG_REGS_TDM_DINTMSK_DDDMSK1_BM        0x00000080

#define AG_MG_REGS_TDM_DINTMSK_DSIMSK2_BO        8
#define AG_MG_REGS_TDM_DINTMSK_DSIMSK2_BM        0x00000100

#define AG_MG_REGS_TDM_DINTMSK_DSOMSK2_BO        9
#define AG_MG_REGS_TDM_DINTMSK_DSOMSK2_BM        0x00000200

#define AG_MG_REGS_TDM_DINTMSK_DDSMSK2_BO        10
#define AG_MG_REGS_TDM_DINTMSK_DDSMSK2_BM        0x00000400

#define AG_MG_REGS_TDM_DINTMSK_DDDMSK2_BO        11
#define AG_MG_REGS_TDM_DINTMSK_DDDMSK2_BM        0x00000800

#define AG_MG_REGS_TDM_DINTMSK_DSIMSK3_BO        12
#define AG_MG_REGS_TDM_DINTMSK_DSIMSK3_BM        0x00001000

#define AG_MG_REGS_TDM_DINTMSK_DSOMSK3_BO        13
#define AG_MG_REGS_TDM_DINTMSK_DSOMSK3_BM        0x00002000

#define AG_MG_REGS_TDM_DINTMSK_DDSMSK3_BO        14
#define AG_MG_REGS_TDM_DINTMSK_DDSMSK3_BM        0x00004000

#define AG_MG_REGS_TDM_DINTMSK_DDDMSK3_BO        15
#define AG_MG_REGS_TDM_DINTMSK_DDDMSK3_BM        0x00008000

#define AG_MG_REGS_TDM_DINTMSK_DSIMSK4_BO        16
#define AG_MG_REGS_TDM_DINTMSK_DSIMSK4_BM        0x00010000

#define AG_MG_REGS_TDM_DINTMSK_DSOMSK4_BO        17
#define AG_MG_REGS_TDM_DINTMSK_DSOMSK4_BM        0x00020000

#define AG_MG_REGS_TDM_DINTMSK_DDSMSK4_BO        18
#define AG_MG_REGS_TDM_DINTMSK_DDSMSK4_BM        0x00040000

#define AG_MG_REGS_TDM_DINTMSK_DDDMSK4_BO        19
#define AG_MG_REGS_TDM_DINTMSK_DDDMSK4_BM        0x00080000

#define AG_MG_REGS_TDM_DINTMSK_DSIMSK5_BO        20
#define AG_MG_REGS_TDM_DINTMSK_DSIMSK5_BM        0x00100000

#define AG_MG_REGS_TDM_DINTMSK_DSOMSK5_BO        21
#define AG_MG_REGS_TDM_DINTMSK_DSOMSK5_BM        0x00200000

#define AG_MG_REGS_TDM_DINTMSK_DDSMSK5_BO        22
#define AG_MG_REGS_TDM_DINTMSK_DDSMSK5_BM        0x00400000

#define AG_MG_REGS_TDM_DINTMSK_DDDMSK5_BO        23
#define AG_MG_REGS_TDM_DINTMSK_DDDMSK5_BM        0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DINTMSK_U
{
    struct
    {
        ag_mg_regs_register
            dsimsk0 : 1,
            dsomsk0 : 1,
            ddsmsk0 : 1,
            dddmsk0 : 1,
            dsimsk1 : 1,
            dsomsk1 : 1,
            ddsmsk1 : 1,
            dddmsk1 : 1,
            dsimsk2 : 1,
            dsomsk2 : 1,
            ddsmsk2 : 1,
            dddmsk2 : 1,
            dsimsk3 : 1,
            dsomsk3 : 1,
            ddsmsk3 : 1,
            dddmsk3 : 1,
            dsimsk4 : 1,
            dsomsk4 : 1,
            ddsmsk4 : 1,
            dddmsk4 : 1,
            dsimsk5 : 1,
            dsomsk5 : 1,
            ddsmsk5 : 1,
            dddmsk5 : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dintmsk_u;
#endif


/*
 * TDM_DINTSTAT<0-2> (TDM Interrupt Status Registers for DSS Cores)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_TDM_DINTSTAT_RO               0x00001004
#define AG_MG_REGS_TDM_DINTSTAT_RM               0x00FFFFFF
#define AG_MG_REGS_TDM_DINTSTAT_RPT				 0x4
#define AG_MG_REGS_TDM_DINTSTAT_IVL				 0x18

#define AG_MG_REGS_TDM_DINTSTAT_DSIINT0_BO       0
#define AG_MG_REGS_TDM_DINTSTAT_DSIINT0_BM       0x00000001

#define AG_MG_REGS_TDM_DINTSTAT_DSOINT0_BO       1
#define AG_MG_REGS_TDM_DINTSTAT_DSOINT0_BM       0x00000002

#define AG_MG_REGS_TDM_DINTSTAT_DDSINT0_BO       2
#define AG_MG_REGS_TDM_DINTSTAT_DDSINT0_BM       0x00000004

#define AG_MG_REGS_TDM_DINTSTAT_DDDINT0_BO       3
#define AG_MG_REGS_TDM_DINTSTAT_DDDINT0_BM       0x00000008

#define AG_MG_REGS_TDM_DINTSTAT_DSIINT1_BO       4
#define AG_MG_REGS_TDM_DINTSTAT_DSIINT1_BM       0x00000010

#define AG_MG_REGS_TDM_DINTSTAT_DSOINT1_BO       5
#define AG_MG_REGS_TDM_DINTSTAT_DSOINT1_BM       0x00000020

#define AG_MG_REGS_TDM_DINTSTAT_DDSINT1_BO       6
#define AG_MG_REGS_TDM_DINTSTAT_DDSINT1_BM       0x00000040

#define AG_MG_REGS_TDM_DINTSTAT_DDDINT1_BO       7
#define AG_MG_REGS_TDM_DINTSTAT_DDDINT1_BM       0x00000080

#define AG_MG_REGS_TDM_DINTSTAT_DSIINT2_BO       8
#define AG_MG_REGS_TDM_DINTSTAT_DSIINT2_BM       0x00000100

#define AG_MG_REGS_TDM_DINTSTAT_DSOINT2_BO       9
#define AG_MG_REGS_TDM_DINTSTAT_DSOINT2_BM       0x00000200

#define AG_MG_REGS_TDM_DINTSTAT_DDSINT2_BO       10
#define AG_MG_REGS_TDM_DINTSTAT_DDSINT2_BM       0x00000400

#define AG_MG_REGS_TDM_DINTSTAT_DDDINT2_BO       11
#define AG_MG_REGS_TDM_DINTSTAT_DDDINT2_BM       0x00000800

#define AG_MG_REGS_TDM_DINTSTAT_DSIINT3_BO       12
#define AG_MG_REGS_TDM_DINTSTAT_DSIINT3_BM       0x00001000

#define AG_MG_REGS_TDM_DINTSTAT_DSOINT3_BO       13
#define AG_MG_REGS_TDM_DINTSTAT_DSOINT3_BM       0x00002000

#define AG_MG_REGS_TDM_DINTSTAT_DDSINT3_BO       14
#define AG_MG_REGS_TDM_DINTSTAT_DDSINT3_BM       0x00004000

#define AG_MG_REGS_TDM_DINTSTAT_DDDINT3_BO       15
#define AG_MG_REGS_TDM_DINTSTAT_DDDINT3_BM       0x00008000

#define AG_MG_REGS_TDM_DINTSTAT_DSIINT4_BO       16
#define AG_MG_REGS_TDM_DINTSTAT_DSIINT4_BM       0x00010000

#define AG_MG_REGS_TDM_DINTSTAT_DSOINT4_BO       17
#define AG_MG_REGS_TDM_DINTSTAT_DSOINT4_BM       0x00020000

#define AG_MG_REGS_TDM_DINTSTAT_DDSINT4_BO       18
#define AG_MG_REGS_TDM_DINTSTAT_DDSINT4_BM       0x00040000

#define AG_MG_REGS_TDM_DINTSTAT_DDDINT4_BO       19
#define AG_MG_REGS_TDM_DINTSTAT_DDDINT4_BM       0x00080000

#define AG_MG_REGS_TDM_DINTSTAT_DSIINT5_BO       20
#define AG_MG_REGS_TDM_DINTSTAT_DSIINT5_BM       0x00100000

#define AG_MG_REGS_TDM_DINTSTAT_DSOINT5_BO       21
#define AG_MG_REGS_TDM_DINTSTAT_DSOINT5_BM       0x00200000

#define AG_MG_REGS_TDM_DINTSTAT_DDSINT5_BO       22
#define AG_MG_REGS_TDM_DINTSTAT_DDSINT5_BM       0x00400000

#define AG_MG_REGS_TDM_DINTSTAT_DDDINT5_BO       23
#define AG_MG_REGS_TDM_DINTSTAT_DDDINT5_BM       0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DINTSTAT_U
{
    struct
    {
        ag_mg_regs_register
            dsiint0 : 1,
            dsoint0 : 1,
            ddsint0 : 1,
            dddint0 : 1,
            dsiint1 : 1,
            dsoint1 : 1,
            ddsint1 : 1,
            dddint1 : 1,
            dsiint2 : 1,
            dsoint2 : 1,
            ddsint2 : 1,
            dddint2 : 1,
            dsiint3 : 1,
            dsoint3 : 1,
            ddsint3 : 1,
            dddint3 : 1,
            dsiint4 : 1,
            dsoint4 : 1,
            ddsint4 : 1,
            dddint4 : 1,
            dsiint5 : 1,
            dsoint5 : 1,
            ddsint5 : 1,
            dddint5 : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dintstat_u;
#endif


/*
 * TDM_DINTMSTAT<0-2> (TDM)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_TDM_DINTMSTAT_RO              0x00001008
#define AG_MG_REGS_TDM_DINTMSTAT_RM              0x00FFFFFF
#define AG_MG_REGS_TDM_DINTMSTAT_RPT			 0x4
#define AG_MG_REGS_TDM_DINTMSTAT_IVL			 0x18

#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT0_BO     0
#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT0_BM     0x00000001

#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT0_BO     1
#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT0_BM     0x00000002

#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT0_BO     2
#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT0_BM     0x00000004

#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT0_BO     3
#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT0_BM     0x00000008

#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT1_BO     4
#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT1_BM     0x00000010

#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT1_BO     5
#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT1_BM     0x00000020

#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT1_BO     6
#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT1_BM     0x00000040

#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT1_BO     7
#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT1_BM     0x00000080

#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT2_BO     8
#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT2_BM     0x00000100

#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT2_BO     9
#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT2_BM     0x00000200

#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT2_BO     10
#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT2_BM     0x00000400

#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT2_BO     11
#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT2_BM     0x00000800

#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT3_BO     12
#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT3_BM     0x00001000

#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT3_BO     13
#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT3_BM     0x00002000

#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT3_BO     14
#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT3_BM     0x00004000

#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT3_BO     15
#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT3_BM     0x00008000

#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT4_BO     16
#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT4_BM     0x00010000

#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT4_BO     17
#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT4_BM     0x00020000

#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT4_BO     18
#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT4_BM     0x00040000

#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT4_BO     19
#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT4_BM     0x00080000

#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT5_BO     20
#define AG_MG_REGS_TDM_DINTMSTAT_DSIMINT5_BM     0x00100000

#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT5_BO     21
#define AG_MG_REGS_TDM_DINTMSTAT_DSOMINT5_BM     0x00200000

#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT5_BO     22
#define AG_MG_REGS_TDM_DINTMSTAT_DDSMINT5_BM     0x00400000

#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT5_BO     23
#define AG_MG_REGS_TDM_DINTMSTAT_DDDMINT5_BM     0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DINTMSTAT_U
{
    struct
    {
        ag_mg_regs_register
            dsimint0 : 1,
            dsomint0 : 1,
            ddsmint0 : 1,
            dddmint0 : 1,
            dsimint1 : 1,
            dsomint1 : 1,
            ddsmint1 : 1,
            dddmint1 : 1,
            dsimint2 : 1,
            dsomint2 : 1,
            ddsmint2 : 1,
            dddmint2 : 1,
            dsimint3 : 1,
            dsomint3 : 1,
            ddsmint3 : 1,
            dddmint3 : 1,
            dsimint4 : 1,
            dsomint4 : 1,
            ddsmint4 : 1,
            dddmint4 : 1,
            dsimint5 : 1,
            dsomint5 : 1,
            ddsmint5 : 1,
            dddmint5 : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dintmstat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_DINTPMSK_RO                  0x0000100C
#define AG_MG_REGS_TDM_DINTPMSK_RM                  0x0000003F
#define AG_MG_REGS_TDM_DINTPMSK_RPT			 		0x4
#define AG_MG_REGS_TDM_DINTPMSK_IVL			 		0x18

#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK0_BO          0
#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK0_BM          0x00000001

#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK1_BO          1
#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK1_BM          0x00000002

#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK2_BO          2
#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK2_BM          0x00000004

#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK3_BO          3
#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK3_BM          0x00000008

#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK4_BO          4
#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK4_BM          0x00000010

#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK5_BO          5
#define AG_MG_REGS_TDM_DINTPMSK_DPEMSK5_BM          0x00000020

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DINTPMSK_U
{
    struct
    {
        ag_mg_regs_register
            dpemsk0 : 1,
            dpemsk1 : 1,
            dpemsk2 : 1,
            dpemsk3 : 1,
            dpemsk4 : 1,
            dpemsk5 : 1,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dintpmsk_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_TDM_DINTPSTAT_RO                 0x00001010
#define AG_MG_REGS_TDM_DINTPSTAT_RM                 0x0000003F
#define AG_MG_REGS_TDM_DINTPSTAT_RPT			 	0x4
#define AG_MG_REGS_TDM_DINTPSTAT_IVL			 	0x18

#define AG_MG_REGS_TDM_DINTPSTAT_DPEINT0_BO         0
#define AG_MG_REGS_TDM_DINTPSTAT_DPEINT0_BM         0x00000001

#define AG_MG_REGS_TDM_DINTPSTAT_DPEINT1_BO         1
#define AG_MG_REGS_TDM_DINTPSTAT_DPEINT1_BM         0x00000002

#define AG_MG_REGS_TDM_DINTPSTAT_DPEINT2_BO         2
#define AG_MG_REGS_DINTPSTAT_DPEINT2_BM         0x00000004

#define AG_MG_REGS_TDM_DINTPSTAT_DPEINT3_BO         3
#define AG_MG_REGS_TDM_DINTPSTAT_DPEINT3_BM         0x00000008

#define AG_MG_REGS_TDM_DINTPSTAT_DPEINT4_BO         4
#define AG_MG_REGS_TDM_DINTPSTAT_DPEINT4_BM         0x00000010

#define AG_MG_REGS_TDM_DINTPSTAT_DPEINT5_BO         5
#define AG_MG_REGS_TDM_DINTPSTAT_DPEINT5_BM         0x00000020

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DINTPSTAT_U
{
    struct
    {
        ag_mg_regs_register
            dpeint0 : 1,
            dpeint1 : 1,
            dpeint2 : 1,
            dpeint3 : 1,
            dpeint4 : 1,
            dpeint5 : 1,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dintpstat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_TDM_DINTPMSTAT_RO                0x00001014
#define AG_MG_REGS_TDM_DINTPMSTAT_RM                0x0000003F
#define AG_MG_REGS_TDM_DINTPMSTAT_RPT			 	0x4
#define AG_MG_REGS_TDM_DINTPMSTAT_IVL			 	0x18

#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT0_BO       0
#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT0_BM       0x00000001

#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT1_BO       1
#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT1_BM       0x00000002

#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT2_BO       2
#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT2_BM       0x00000004

#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT3_BO       3
#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT3_BM       0x00000008

#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT4_BO       4
#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT4_BM       0x00000010

#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT5_BO       5
#define AG_MG_REGS_TDM_DINTPMSTAT_DPEMINT5_BM       0x00000020

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_DINTPMSTAT_U
{
    struct
    {
        ag_mg_regs_register
            dpemint0 : 1,
            dpemint1 : 1,
            dpemint2 : 1,
            dpemint3 : 1,
            dpemint4 : 1,
            dpemint5 : 1,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_dintpmstat_u;
#endif

/*
 * TDM_PINTMSK (TDM Interrupt Mask Register for PPB)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_PINTMSK_RO                0x00001060
#define AG_MG_REGS_TDM_PINTMSK_RM                0x00FFFFFF

#define AG_MG_REGS_TDM_PINTMSK_PSIMSK0_BO        0
#define AG_MG_REGS_TDM_PINTMSK_PSIMSK0_BM        0x00000001

#define AG_MG_REGS_TDM_PINTMSK_PSOMSK0_BO        1
#define AG_MG_REGS_TDM_PINTMSK_PSOMSK0_BM        0x00000002

#define AG_MG_REGS_TDM_PINTMSK_PDSMSK0_BO        2
#define AG_MG_REGS_TDM_PINTMSK_PDSMSK0_BM        0x00000004

#define AG_MG_REGS_TDM_PINTMSK_PDDMSK_BO         3
#define AG_MG_REGS_TDM_PINTMSK_PDDMSK_BM         0x00000008

#define AG_MG_REGS_TDM_PINTMSK_PSIMSK1_BO        4
#define AG_MG_REGS_TDM_PINTMSK_PSIMSK1_BM        0x00000010

#define AG_MG_REGS_TDM_PINTMSK_PSOMSK1_BO        5
#define AG_MG_REGS_TDM_PINTMSK_PSOMSK1_BM        0x00000020

#define AG_MG_REGS_TDM_PINTMSK_PDSMSK1_BO        6
#define AG_MG_REGS_TDM_PINTMSK_PDSMSK1_BM        0x00000040

#define AG_MG_REGS_TDM_PINTMSK_PDDMSK1_BO        7
#define AG_MG_REGS_TDM_PINTMSK_PDDMSK1_BM        0x00000080

#define AG_MG_REGS_TDM_PINTMSK_PSIMSK2_BO        8
#define AG_MG_REGS_TDM_PINTMSK_PSIMSK2_BM        0x00000100

#define AG_MG_REGS_TDM_PINTMSK_PSOMSK2_BO        9
#define AG_MG_REGS_TDM_PINTMSK_PSOMSK2_BM        0x00000200

#define AG_MG_REGS_TDM_PINTMSK_PDSMSK2_BO        10
#define AG_MG_REGS_TDM_PINTMSK_PDSMSK2_BM        0x00000400

#define AG_MG_REGS_TDM_PINTMSK_PDDMSK2_BO        11
#define AG_MG_REGS_TDM_PINTMSK_PDDMSK2_BM        0x00000800

#define AG_MG_REGS_TDM_PINTMSK_PSIMSK3_BO        12
#define AG_MG_REGS_TDM_PINTMSK_PSIMSK3_BM        0x00001000

#define AG_MG_REGS_TDM_PINTMSK_PSOMSK3_BO        13
#define AG_MG_REGS_TDM_PINTMSK_PSOMSK3_BM        0x00002000

#define AG_MG_REGS_TDM_PINTMSK_PDSMSK3_BO        14
#define AG_MG_REGS_TDM_PINTMSK_PDSMSK3_BM        0x00004000

#define AG_MG_REGS_TDM_PINTMSK_PDDMSK3_BO        15
#define AG_MG_REGS_TDM_PINTMSK_PDDMSK3_BM        0x00008000

#define AG_MG_REGS_TDM_PINTMSK_PSIMSK4_BO        16
#define AG_MG_REGS_TDM_PINTMSK_PSIMSK4_BM        0x00010000

#define AG_MG_REGS_TDM_PINTMSK_PSOMSK4_BO        17
#define AG_MG_REGS_TDM_PINTMSK_PSOMSK4_BM        0x00020000

#define AG_MG_REGS_TDM_PINTMSK_PDSMSK4_BO        18
#define AG_MG_REGS_TDM_PINTMSK_PDSMSK4_BM        0x00040000

#define AG_MG_REGS_TDM_PINTMSK_PDDMSK4_BO        19
#define AG_MG_REGS_TDM_PINTMSK_PDDMSK4_BM        0x00080000

#define AG_MG_REGS_TDM_PINTMSK_PSIMSK5_BO        20
#define AG_MG_REGS_TDM_PINTMSK_PSIMSK5_BM        0x00100000

#define AG_MG_REGS_TDM_PINTMSK_PSOMSK5_BO        21
#define AG_MG_REGS_TDM_PINTMSK_PSOMSK5_BM        0x00200000

#define AG_MG_REGS_TDM_PINTMSK_PDSMSK5_BO        22
#define AG_MG_REGS_TDM_PINTMSK_PDSMSK5_BM        0x00400000

#define AG_MG_REGS_TDM_PINTMSK_PDDMSK5_BO        23
#define AG_MG_REGS_TDM_PINTMSK_PDDMSK5_BM        0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_PINTMSK_U
{
    struct
    {
        ag_mg_regs_register
            psimsk0 : 1,
            psomsk0 : 1,
            pdsmsk0 : 1,
            pddmsk : 1,
            psimsk1 : 1,
            psomsk1 : 1,
            pdsmsk1 : 1,
            pddmsk1 : 1,
            psimsk2 : 1,
            psomsk2 : 1,
            pdsmsk2 : 1,
            pddmsk2 : 1,
            psimsk3 : 1,
            psomsk3 : 1,
            pdsmsk3 : 1,
            pddmsk3 : 1,
            psimsk4 : 1,
            psomsk4 : 1,
            pdsmsk4 : 1,
            pddmsk4 : 1,
            psimsk5 : 1,
            psomsk5 : 1,
            pdsmsk5 : 1,
            pddmsk5 : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_pintmsk_u;
#endif


/*
 * TDM_PINTSTAT (TDM Raw Interrupt Status Register for PPB)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_TDM_PINTSTAT_RO               0x00001064
#define AG_MG_REGS_TDM_PINTSTAT_RM               0x00FFFFFF

#define AG_MG_REGS_TDM_PINTSTAT_PSIINT0_BO       0
#define AG_MG_REGS_TDM_PINTSTAT_PSIINT0_BM       0x00000001

#define AG_MG_REGS_TDM_PINTSTAT_PSOINT0_BO       1
#define AG_MG_REGS_TDM_PINTSTAT_PSOINT0_BM       0x00000002

#define AG_MG_REGS_TDM_PINTSTAT_PDSINT0_BO       2
#define AG_MG_REGS_TDM_PINTSTAT_PDSINT0_BM       0x00000004

#define AG_MG_REGS_TDM_PINTSTAT_PDDINT0_BO       3
#define AG_MG_REGS_TDM_PINTSTAT_PDDINT0_BM       0x00000008

#define AG_MG_REGS_TDM_PINTSTAT_PSIINT1_BO       4
#define AG_MG_REGS_TDM_PINTSTAT_PSIINT1_BM       0x00000010

#define AG_MG_REGS_TDM_PINTSTAT_PSOINT1_BO       5
#define AG_MG_REGS_TDM_PINTSTAT_PSOINT1_BM       0x00000020

#define AG_MG_REGS_TDM_PINTSTAT_PDSINT1_BO       6
#define AG_MG_REGS_TDM_PINTSTAT_PDSINT1_BM       0x00000040

#define AG_MG_REGS_TDM_PINTSTAT_PDDINT1_BO       7
#define AG_MG_REGS_TDM_PINTSTAT_PDDINT1_BM       0x00000080

#define AG_MG_REGS_TDM_PINTSTAT_PSIINT2_BO       8
#define AG_MG_REGS_TDM_PINTSTAT_PSIINT2_BM       0x00000100

#define AG_MG_REGS_TDM_PINTSTAT_PSOINT2_BO       9
#define AG_MG_REGS_TDM_PINTSTAT_PSOINT2_BM       0x00000200

#define AG_MG_REGS_TDM_PINTSTAT_PDSINT2_BO       10
#define AG_MG_REGS_TDM_PINTSTAT_PDSINT2_BM       0x00000400

#define AG_MG_REGS_TDM_PINTSTAT_PDDINT2_BO       11
#define AG_MG_REGS_TDM_PINTSTAT_PDDINT2_BM       0x00000800

#define AG_MG_REGS_TDM_PINTSTAT_PSIINT3_BO       12
#define AG_MG_REGS_TDM_PINTSTAT_PSIINT3_BM       0x00001000

#define AG_MG_REGS_TDM_PINTSTAT_PSOINT3_BO       13
#define AG_MG_REGS_TDM_PINTSTAT_PSOINT3_BM       0x00002000

#define AG_MG_REGS_TDM_PINTSTAT_PDSINT3_BO       14
#define AG_MG_REGS_TDM_PINTSTAT_PDSINT3_BM       0x00004000

#define AG_MG_REGS_TDM_PINTSTAT_PDDINT3_BO       15
#define AG_MG_REGS_TDM_PINTSTAT_PDDINT3_BM       0x00008000

#define AG_MG_REGS_TDM_PINTSTAT_PSIINT4_BO       16
#define AG_MG_REGS_TDM_PINTSTAT_PSIINT4_BM       0x00010000

#define AG_MG_REGS_TDM_PINTSTAT_PSOINT4_BO       17
#define AG_MG_REGS_TDM_PINTSTAT_PSOINT4_BM       0x00020000

#define AG_MG_REGS_TDM_PINTSTAT_PDSINT4_BO       18
#define AG_MG_REGS_TDM_PINTSTAT_PDSINT4_BM       0x00040000

#define AG_MG_REGS_TDM_PINTSTAT_PDDINT4_BO       19
#define AG_MG_REGS_TDM_PINTSTAT_PDDINT4_BM       0x00080000

#define AG_MG_REGS_TDM_PINTSTAT_PSIINT5_BO       20
#define AG_MG_REGS_TDM_PINTSTAT_PSIINT5_BM       0x00100000

#define AG_MG_REGS_TDM_PINTSTAT_PSOINT5_BO       21
#define AG_MG_REGS_TDM_PINTSTAT_PSOINT5_BM       0x00200000

#define AG_MG_REGS_TDM_PINTSTAT_PDSINT5_BO       22
#define AG_MG_REGS_TDM_PINTSTAT_PDSINT5_BM       0x00400000

#define AG_MG_REGS_TDM_PINTSTAT_PDDINT5_BO       23
#define AG_MG_REGS_TDM_PINTSTAT_PDDINT5_BM       0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_PINTSTAT_U
{
    struct
    {
        ag_mg_regs_register
            psiint0 : 1,
            psoint0 : 1,
            pdsint0 : 1,
            pddint0 : 1,
            psiint1 : 1,
            psoint1 : 1,
            pdsint1 : 1,
            pddint1 : 1,
            psiint2 : 1,
            psoint2 : 1,
            pdsint2 : 1,
            pddint2 : 1,
            psiint3 : 1,
            psoint3 : 1,
            pdsint3 : 1,
            pddint3 : 1,
            psiint4 : 1,
            psoint4 : 1,
            pdsint4 : 1,
            pddint4 : 1,
            psiint5 : 1,
            psoint5 : 1,
            pdsint5 : 1,
            pddint5 : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_pintstat_u;
#endif


/*
 * TDM_PINTMSTAT (TDM Masked Interrupt Status Register for PPB)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_TDM_PINTMSTAT_RO              0x00001068
#define AG_MG_REGS_TDM_PINTMSTAT_RM              0x00FFFFFF

#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT0_BO     0
#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT0_BM     0x00000001

#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT0_BO     1
#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT0_BM     0x00000002

#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT0_BO     2
#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT0_BM     0x00000004

#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT0_BO     3
#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT0_BM     0x00000008

#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT1_BO     4
#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT1_BM     0x00000010

#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT1_BO     5
#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT1_BM     0x00000020

#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT1_BO     6
#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT1_BM     0x00000040

#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT1_BO     7
#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT1_BM     0x00000080

#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT2_BO     8
#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT2_BM     0x00000100

#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT2_BO     9
#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT2_BM     0x00000200

#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT2_BO     10
#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT2_BM     0x00000400

#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT2_BO     11
#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT2_BM     0x00000800

#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT3_BO     12
#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT3_BM     0x00001000

#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT3_BO     13
#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT3_BM     0x00002000

#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT3_BO     14
#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT3_BM     0x00004000

#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT3_BO     15
#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT3_BM     0x00008000

#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT4_BO     16
#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT4_BM     0x00010000

#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT4_BO     17
#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT4_BM     0x00020000

#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT4_BO     18
#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT4_BM     0x00040000

#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT4_BO     19
#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT4_BM     0x00080000

#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT5_BO     20
#define AG_MG_REGS_TDM_PINTMSTAT_PSIMINT5_BM     0x00100000

#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT5_BO     21
#define AG_MG_REGS_TDM_PINTMSTAT_PSOMINT5_BM     0x00200000

#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT5_BO     22
#define AG_MG_REGS_TDM_PINTMSTAT_PDSMINT5_BM     0x00400000

#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT5_BO     23
#define AG_MG_REGS_TDM_PINTMSTAT_PDDMINT5_BM     0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_PINTMSTAT_U
{
    struct
    {
        ag_mg_regs_register
            psimint0 : 1,
            psomint0 : 1,
            pdsmint0 : 1,
            pddmint0 : 1,
            psimint1 : 1,
            psomint1 : 1,
            pdsmint1 : 1,
            pddmint1 : 1,
            psimint2 : 1,
            psomint2 : 1,
            pdsmint2 : 1,
            pddmint2 : 1,
            psimint3 : 1,
            psomint3 : 1,
            pdsmint3 : 1,
            pddmint3 : 1,
            psimint4 : 1,
            psomint4 : 1,
            pdsmint4 : 1,
            pddmint4 : 1,
            psimint5 : 1,
            psomint5 : 1,
            pdsmint5 : 1,
            pddmint5 : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_pintmstat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_PINTPMSK_RO                   0x0000106C
#define AG_MG_REGS_TDM_PINTPMSK_RM                   0x0000003F

#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK0_BO           0
#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK0_BM           0x00000001

#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK1_BO           1
#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK1_BM           0x00000002

#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK2_BO           2
#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK2_BM           0x00000004

#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK3_BO           3
#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK3_BM           0x00000008

#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK4_BO           4
#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK4_BM           0x00000010

#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK5_BO           5
#define AG_MG_REGS_TDM_PINTPMSK_PPEMSK5_BM           0x00000020

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_PINTPMSK_U
{
    struct
    {
        ag_mg_regs_register
            ppemsk0 : 1,
            ppemsk1 : 1,
            ppemsk2 : 1,
            ppemsk3 : 1,
            ppemsk4 : 1,
            ppemsk5 : 1,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_pintpmsk_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_TDM_PINTPSTAT_RO                  0x00001070
#define AG_MG_REGS_TDM_PINTPSTAT_RM                  0x0000003F

#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT0_BO          0
#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT0_BM          0x00000001

#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT1_BO          1
#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT1_BM          0x00000002

#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT2_BO          2
#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT2_BM          0x00000004

#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT3_BO          3
#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT3_BM          0x00000008

#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT4_BO          4
#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT4_BM          0x00000010

#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT5_BO          5
#define AG_MG_REGS_TDM_PINTPSTAT_PPEINT5_BM          0x00000020

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_PINTPSTAT_U
{
    struct
    {
        ag_mg_regs_register
            ppeint0 : 1,
            ppeint1 : 1,
            ppeint2 : 1,
            ppeint3 : 1,
            ppeint4 : 1,
            ppeint5 : 1,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_pintpstat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_TDM_PINTPMSTAT_RO                 0x00001074
#define AG_MG_REGS_TDM_PINTPMSTAT_RM                 0x0000003F

#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT0_BO        0
#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT0_BM        0x00000001

#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT1_BO        1
#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT1_BM        0x00000002

#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT2_BO        2
#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT2_BM        0x00000004

#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT3_BO        3
#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT3_BM        0x00000008

#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT4_BO        4
#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT4_BM        0x00000010

#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT5_BO        5
#define AG_MG_REGS_TDM_PINTPMSTAT_PPEMINT5_BM        0x00000020

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_PINTPMSTAT_U
{
    struct
    {
        ag_mg_regs_register
            ppemint0 : 1,
            ppemint1 : 1,
            ppemint2 : 1,
            ppemint3 : 1,
            ppemint4 : 1,
            ppemint5 : 1,
            fill0 : 26;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_pintpmstat_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_TDMCLKCTL_RO                  0x00001080
#define AG_MG_REGS_TDM_TDMCLKCTL_RM                  0x000000FF

#define AG_MG_REGS_TDM_TDMCLKCTL_SICKCTL_BO          0
#define AG_MG_REGS_TDM_TDMCLKCTL_SICKCTL_BM          0x0000000F

#define AG_MG_REGS_TDM_TDMCLKCTL_SOCKCTL_BO          4
#define AG_MG_REGS_TDM_TDMCLKCTL_SOCKCTL_BM          0x000000F0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_TDMCLKCTL_U
{
    struct
    {
        ag_mg_regs_register
            sickctl : 4,
            sockctl : 4,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_tdmclkctl_u;
#endif

/* V1.1 only
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_TDMSYNCSEL_RO                  0x00001090
#define AG_MG_REGS_TDM_TDMSYNCSEL_RM                  0x00003F3F

#define AG_MG_REGS_TDM_TDMSYNCSEL_INPUTSEL_BO         0
#define AG_MG_REGS_TDM_TDMSYNCSEL_INPUTSEL_BM         0x0000003F

#define AG_MG_REGS_TDM_TDMSYNCSEL_OUTPUTSEL_BO        8
#define AG_MG_REGS_TDM_TDMSYNCSEL_OUTPUTSEL_BM        0x00003F00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_TDMSYNCSEL_U
{
    struct
    {
        ag_mg_regs_register
            inputsel : 6,
            fill0 : 2,
            outputsel : 6,
            fill1 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_tdmsyncsel_u;
#endif

/* V1.1 only
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_TDMPORTEN_RO                  0x00001094
#define AG_MG_REGS_TDM_TDMPORTEN_RM                  0x00003F3F

#define AG_MG_REGS_TDM_TDMPORTEN_INPUTSEL_BO         0
#define AG_MG_REGS_TDM_TDMPORTEN_INPUTSEL_BM         0x0000003F

#define AG_MG_REGS_TDM_TDMPORTEN_OUTPUTSEL_BO        8
#define AG_MG_REGS_TDM_TDMPORTEN_OUTPUTSEL_BM        0x00003F00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_TDMPORTEN_U
{
    struct
    {
        ag_mg_regs_register
            inputen : 6,
            fill0 : 2,
            outputen : 6,
            fill1 : 18;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_tdmporten_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_ULIM_RO                       0x00001104
#define AG_MG_REGS_TDM_ULIM_RM                       0xF81FFFFF
#define AG_MG_REGS_TDM_ULIM_RPT                      32
#define AG_MG_REGS_TDM_ULIM_IVL                      0x8

#define AG_MG_REGS_TDM_ULIM_ULIM_BO                  0
#define AG_MG_REGS_TDM_ULIM_ULIM_BM                  0x001FFFFF

#define AG_MG_REGS_TDM_ULIM_ULIMSEL_BO               27
#define AG_MG_REGS_TDM_ULIM_ULIMSEL_BM               0x78000000

#define AG_MG_REGS_TDM_ULIM_ULIMEN_BO                31
#define AG_MG_REGS_TDM_ULIM_ULIMEN_BM                0x80000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_TDM_ULIM_U
{
    struct
    {
        ag_mg_regs_register
            ulim : 21,
            fill0 : 6,
            ulimsel : 4,
            ulimen : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_ulim_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_TDM_UCNT_RO                       0x00001100
#define AG_MG_REGS_TDM_UCNT_RM                       0x001FFFFF
#define AG_MG_REGS_TDM_UCNT_RPT                      32
#define AG_MG_REGS_TDM_UCNT_IVL                      0x8

#define AG_MG_REGS_TDM_UCNT_UCNT_BO                  0
#define AG_MG_REGS_TDM_UCNT_UCNT_BM                  0x001FFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES

typedef union AG_MG_REGS_TDM_UCNT_U
{
    struct
    {
        ag_mg_regs_register
            ucnt : 21,
            fill0 : 11;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_tdm_ucnt_u;
#endif

/*
* Physical register addresses (for ARM accessing TDM)
*/
/*
 * Physical register addresses (for arm accessing tdm)
 */

#define AG_MG_REGS_TDM_BASE		0x98010000
#define AG_MG_REGS_TDM_SWTU_PTR_BASE 	0x98020000

#define AG_MG_REGS_TDM_RPT      6
#define AG_MG_REGS_TDM_IVL      0x100

#define AG_MG_REGS_TDM_REG(p, ro)		(AG_MG_REGS_TDM_BASE+(AG_MG_REGS_TDM_IVL*(p)+(ro)))

#define AG_MG_REGS_TDM_SCON0_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SCON0_RO)
#define AG_MG_REGS_TDM_SCON1_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SCON1_RO)
#define AG_MG_REGS_TDM_SCON2_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SCON2_RO)
#define AG_MG_REGS_TDM_SCON3_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SCON3_RO)
#define AG_MG_REGS_TDM_SCON4_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SCON4_RO)
#define AG_MG_REGS_TDM_SCIEN_RA(p, n)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SCIEN_RO+(0x4*n))
#define AG_MG_REGS_TDM_SCOEN_RA(p, n)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SCOEN_RO+(0x4*n))
#define AG_MG_REGS_TDM_SCOMSK_RA(p, n)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SCOMSK_RO+(0x4*n))
#define AG_MG_REGS_TDM_SIDR_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SIDR_RO)
#define AG_MG_REGS_TDM_SODR_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SODR_RO)
#define AG_MG_REGS_TDM_STAT_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_STAT_RO)
#define AG_MG_REGS_TDM_SCIFR_RA(p, n)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SCIFR_RO+(0x4*n))
#define AG_MG_REGS_TDM_SCOFR_RA(p, n)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SCOFR_RO+(0x4*n))

/* SWTU */
#define AG_MG_REGS_TDM_SSTAT_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SSTAT_RO)
#define AG_MG_REGS_TDM_SCTL_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SCTL_RO)
#define AG_MG_REGS_TDM_DCTL_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_DCTL_RO)
#define AG_MG_REGS_TDM_SSTR_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SSTR_RO)
#define AG_MG_REGS_TDM_DSTR_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_DSTR_RO)
#define AG_MG_REGS_TDM_SRI_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SRI_RO)
#define AG_MG_REGS_TDM_DRI_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_DRI_RO)
#define AG_MG_REGS_TDM_SINTC_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SINTC_RO)
#define AG_MG_REGS_TDM_DINTC_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_DINTC_RO)
#define AG_MG_REGS_TDM_SOCE_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_SOCE_RO)
#define AG_MG_REGS_TDM_DOCE_RA(p)	AG_MG_REGS_TDM_REG(p, AG_MG_REGS_TDM_DOCE_RO)

#define AG_MG_REGS_TDM_SADD_RA(p, ch)	AG_MG_REGS_TDM_REG(p*0x20, (AG_MG_REGS_TDM_SADD_RO+(ch*AG_MG_REGS_TDM_SADD_IVL)))
#define AG_MG_REGS_TDM_SBAS_RA(p, ch)	AG_MG_REGS_TDM_REG(p*0x20, (AG_MG_REGS_TDM_SBAS_RO+(ch*AG_MG_REGS_TDM_SBAS_IVL)))
#define AG_MG_REGS_TDM_SCNT_RA(p, ch)	AG_MG_REGS_TDM_REG(p*0x20, (AG_MG_REGS_TDM_SCNT_RO+(ch*AG_MG_REGS_TDM_SCNT_IVL)))
#define AG_MG_REGS_TDM_SLIM_RA(p, ch)	AG_MG_REGS_TDM_REG(p*0x20, (AG_MG_REGS_TDM_SLIM_RO+(ch*AG_MG_REGS_TDM_SLIM_IVL)))

#define AG_MG_REGS_TDM_DADD_RA(p, ch)	AG_MG_REGS_TDM_REG(p*0x20, (AG_MG_REGS_TDM_DADD_RO+(ch*AG_MG_REGS_TDM_DADD_IVL)))
#define AG_MG_REGS_TDM_DBAS_RA(p, ch)	AG_MG_REGS_TDM_REG(p*0x20, (AG_MG_REGS_TDM_DBAS_RO+(ch*AG_MG_REGS_TDM_DBAS_IVL)))
#define AG_MG_REGS_TDM_DCNT_RA(p, ch)	AG_MG_REGS_TDM_REG(p*0x20, (AG_MG_REGS_TDM_DCNT_RO+(ch*AG_MG_REGS_TDM_DCNT_IVL)))
#define AG_MG_REGS_TDM_DLIM_RA(p, ch)	AG_MG_REGS_TDM_REG(p*0x20, (AG_MG_REGS_TDM_DLIM_RO+(ch*AG_MG_REGS_TDM_DLIM_IVL)))

/* interrupt control */
#define AG_MG_REGS_TDM_DINTMSK_RA(d) AG_MG_REGS_TDM_REG(0, ((d*AG_MG_REGS_TDM_DINTMSK_IVL)+AG_MG_REGS_TDM_DINTMSK_RO))
#define AG_MG_REGS_TDM_DINTSTAT_RA(d)	AG_MG_REGS_TDM_REG(0, ((d*AG_MG_REGS_TDM_DINTMSK_IVL)+AG_MG_REGS_TDM_DINTSTAT_RO))
#define AG_MG_REGS_TDM_DINTMSTAT_RA(d)	AG_MG_REGS_TDM_REG(0, ((d*AG_MG_REGS_TDM_DINTMSK_IVL)+AG_MG_REGS_TDM_DINTMSTAT_RO))
#define AG_MG_REGS_TDM_DINTPMSK_RA(d)	AG_MG_REGS_TDM_REG(0, ((d*AG_MG_REGS_TDM_DINTMSK_IVL)+AG_MG_REGS_TDM_DINTPMSK_RO))
#define AG_MG_REGS_TDM_DINTPSTAT_RA(d)	AG_MG_REGS_TDM_REG(0, ((d*AG_MG_REGS_TDM_DINTMSK_IVL)+AG_MG_REGS_TDM_DINTPSTAT_RO))
#define AG_MG_REGS_TDM_DINTPMSTAT_RA(d)	AG_MG_REGS_TDM_REG(0, ((d*AG_MG_REGS_TDM_DINTMSK_IVL)+AG_MG_REGS_TDM_DINTPMSTAT_RO))

#define AG_MG_REGS_TDM_PINTMSK_RA	AG_MG_REGS_TDM_REG(0, AG_MG_REGS_TDM_PINTMSK_RO)
#define AG_MG_REGS_TDM_PINTSTAT_RA	AG_MG_REGS_TDM_REG(0, AG_MG_REGS_TDM_PINTSTAT_RO)
#define AG_MG_REGS_TDM_PINTMSTAT_RA	AG_MG_REGS_TDM_REG(0, AG_MG_REGS_TDM_PINTMSTAT_RO)
#define AG_MG_REGS_TDM_PINTPMSK_RA	AG_MG_REGS_TDM_REG(0, AG_MG_REGS_TDM_PINTPMSK_RO)
#define AG_MG_REGS_TDM_PINTPSTAT_RA	AG_MG_REGS_TDM_REG(0, AG_MG_REGS_TDM_PINTPSTAT_RO)
#define AG_MG_REGS_TDM_PINTPMSTAT_RA	AG_MG_REGS_TDM_REG(0, AG_MG_REGS_TDM_PINTPMSTAT_RO)

#define AG_MG_REGS_TDM_TDMCLKCTL_RA	AG_MG_REGS_TDM_REG(0, AG_MG_REGS_TDM_TDMCLKCTL_RO)

/* universal counter */
#define AG_MG_REGS_TDM_ULIM_RA(n)	AG_MG_REGS_TDM_REG(0, (AG_MG_REGS_TDM_ULIM_RO + (n*AG_MG_REGS_TDM_ULIM_IVL)))
#define AG_MG_REGS_TDM_UCNT_RA(n)	AG_MG_REGS_TDM_REG(0, (AG_MG_REGS_TDM_UCNT_RO + (n*AG_MG_REGS_TDM_UCNT_IVL)))

/* will be fixed later */
#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_TDM_SIU_S
{
ag_mg_regs_tdm_scon0_u   scon0;
ag_mg_regs_tdm_scon1_u   scon1;
ag_mg_regs_tdm_scon2_u   scon2;
ag_mg_regs_tdm_scon3_u   scon3;
ag_mg_regs_tdm_scon4_u   scon4;
ag_mg_regs_tdm_scien_u   scien[AG_MG_REGS_TDM_SCIEN_RPT];
ag_mg_regs_tdm_scoen_u   scoen[AG_MG_REGS_TDM_SCOEN_RPT];
ag_mg_regs_tdm_scomsk_u  scomsk[AG_MG_REGS_TDM_SCOMSK_RPT];
ag_mg_regs_tdm_sidr_u    sidr;
ag_mg_regs_tdm_sodr_u    sodr;
ag_mg_regs_tdm_stat_u    stat;
ag_mg_regs_tdm_scifr_u   scifr[AG_MG_REGS_TDM_SCIFR_RPT];
ag_mg_regs_tdm_scofr_u   scofr[AG_MG_REGS_TDM_SCOFR_RPT];
} ag_mg_regs_tdm_siu_s;

#define AG_MG_REGS_TDM_SWTU_CTL_TRUE_SIZE     (AG_MG_REGS_TDM_DRI_RO - AG_MG_REGS_TDM_SSTAT_RO+4)
#define AG_MG_REGS_TDM_INTER_SWTU_CTL_GAP_SIZE     ((AG_MG_REGS_TDM_IVL - AG_MG_REGS_TDM_SWTU_CTL_TRUE_SIZE)         / sizeof(ag_mg_regs_register))

typedef struct AG_MG_REGS_TDM_SWT_CTL_S
{
ag_mg_regs_tdm_sstat_u  sstat;
ag_mg_regs_tdm_sctl_u   sctl;
ag_mg_regs_tdm_dctl_u   dctl;
ag_mg_regs_register		RESERVED_1;
ag_mg_regs_tdm_sintc_u  sintc;
ag_mg_regs_tdm_dintc_u  dintc;
ag_mg_regs_tdm_soce_u   soce;
ag_mg_regs_tdm_doce_u   doce;
ag_mg_regs_tdm_sstr_u   sstr;
ag_mg_regs_tdm_dstr_u   dstr;
ag_mg_regs_tdm_sri_u    sri;
ag_mg_regs_tdm_dri_u    dri;
ag_mg_regs_register     RESERVED_2[AG_MG_REGS_TDM_INTER_SWTU_CTL_GAP_SIZE];
} ag_mg_regs_tdm_swtu_ctl_s;

typedef struct AG_MG_REGS_TDM_SRC_BUF_S
{
	ag_mg_regs_tdm_sadd_u   sadd;
	ag_mg_regs_tdm_sbas_u   sbas;
	ag_mg_regs_tdm_scnt_u   scnt;
	ag_mg_regs_tdm_slim_u   slim;
} ag_mg_regs_tdm_swtu_ptr_src_s;

typedef struct AG_MG_REGS_TDM_DST_BUF_S
{
	ag_mg_regs_tdm_dadd_u   dadd;
	ag_mg_regs_tdm_dbas_u   dbas;
	ag_mg_regs_tdm_dcnt_u   dcnt;
	ag_mg_regs_tdm_dlim_u   dlim;
} ag_mg_regs_tdm_swtu_ptr_dst_s;

typedef struct AG_MG_REGS_TDM_SWTU_PTR_S
{
	ag_mg_regs_tdm_swtu_ptr_src_s src[256];
	ag_mg_regs_tdm_swtu_ptr_dst_s dst[256];
} ag_mg_regs_tdm_swtu_ptr_s;

typedef struct AG_MG_REGS_TDM_INT_TO_DSS_CORE_S
{
	ag_mg_regs_tdm_dintmsk_u dintmsk;
	ag_mg_regs_tdm_dintstat_u dintstat;
	ag_mg_regs_tdm_dintmstat_u	dintmstat;
	ag_mg_regs_tdm_dintpmsk_u	dintpmsk;
	ag_mg_regs_tdm_dintpstat_u	dintpstat;
	ag_mg_regs_tdm_dintpmstat_u	dintpmstat;
} ag_mg_regs_tdm_int_to_dss_s;

typedef struct AG_MG_REGS_TDM_INT_TO_PPB_CORE_S
{
	ag_mg_regs_tdm_pintmsk_u pintmsk;
	ag_mg_regs_tdm_pintstat_u pintstat;
	ag_mg_regs_tdm_pintmstat_u	pintmstat;
	ag_mg_regs_tdm_pintpmsk_u	pintpmsk;
	ag_mg_regs_tdm_pintpstat_u	pintpstat;
	ag_mg_regs_tdm_pintpmstat_u	pintpmstat;
} ag_mg_regs_tdm_int_to_ppb_s;

typedef struct AG_MG_REGS_TDM_INT_S
{
	ag_mg_regs_tdm_int_to_dss_s dss_int[4];
	ag_mg_regs_tdm_int_to_ppb_s ppb_int;
	ag_mg_regs_register			RESERVED[2];
	ag_mg_regs_tdm_tdmclkctl_u	tdmclkctl;
	ag_mg_regs_register			RESERVED1[3];
	ag_mg_regs_tdm_tdmsyncsel_u	tdmsyncsel;		/* V1.1 only */
	ag_mg_regs_tdm_tdmporten_u	tdmporten;		/* V1.1 only */
} ag_mg_regs_tdm_int_s;

typedef struct AG_MG_REGS_TDM_UNIVERSAL_CNT_S
{
	ag_mg_regs_tdm_ucnt_u	ucnt;
	ag_mg_regs_tdm_ulim_u	ulim;
} ag_mg_regs_tdm_uni_cnt_s;

#define AG_MG_REGS_TDM_SIU_BOUNDARY     (AG_MG_REGS_TDM_SCON0_RO+(AG_MG_REGS_TDM_RPT*AG_MG_REGS_TDM_IVL))
#define AG_MG_REGS_TDM_SIU_SWTU_CTL_GAP_SIZE     ((AG_MG_REGS_TDM_SSTAT_RO - AG_MG_REGS_TDM_SIU_BOUNDARY)  \
													/ sizeof(ag_mg_regs_register))

#define AG_MG_REGS_TDM_SWTU_CTL_BOUNDARY	(AG_MG_REGS_TDM_SSTAT_RO+(AG_MG_REGS_TDM_RPT*AG_MG_REGS_TDM_IVL))
#define AG_MG_REGS_TDM_SWTU_CTL_INT_GAP_SIZE ((AG_MG_REGS_TDM_DINTMSK_RO - AG_MG_REGS_TDM_SWTU_CTL_BOUNDARY) \
													/ sizeof(ag_mg_regs_register))

#define AG_MG_REGS_TDM_INT_BOUNDARY     (AG_MG_REGS_TDM_DINTMSK_RO+0x98)
#define AG_MG_REGS_TDM_INT_UNI_CNT_GAP_SIZE		((AG_MG_REGS_TDM_UCNT_RO - AG_MG_REGS_TDM_INT_BOUNDARY)\
													/ sizeof(ag_mg_regs_register))

typedef struct AG_MG_REGS_TDM_REGS_S
{
	ag_mg_regs_tdm_siu_s	siu[AG_MG_REGS_TDM_RPT];
	ag_mg_regs_register			RESERVED_0[AG_MG_REGS_TDM_SIU_SWTU_CTL_GAP_SIZE];
	ag_mg_regs_tdm_swtu_ctl_s swtu_ctl[AG_MG_REGS_TDM_RPT];
	ag_mg_regs_register			RESERVED_1[AG_MG_REGS_TDM_SWTU_CTL_INT_GAP_SIZE] ;
	ag_mg_regs_tdm_int_s	tdm_intr;
	ag_mg_regs_register			RESERVED_2[AG_MG_REGS_TDM_INT_UNI_CNT_GAP_SIZE];
	ag_mg_regs_tdm_uni_cnt_s uni_cnt[AG_MG_REGS_TDM_UCNT_RPT];
} ag_mg_regs_tdm_reg_s ;


typedef struct AG_MG_REGS_TDM_SWTU_PTR_REGS_S
{
	ag_mg_regs_tdm_swtu_ptr_s swtu_ptr[AG_MG_REGS_TDM_RPT];
} ag_mg_regs_tdm_swtu_ptr_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_tdm_regs_s *tdm_regs =
*       (volatile ag_mg_regs_tdm_regs_s *)AG_MG_REGS_TDM_BASE;

*   volatile ag_mg_regs_tdm_swtu_ptr_reg_s *tdm_swtu_ptr_regs =
*       (volatile ag_mg_regs_tdm_swtu_ptr_regs_s *)AG_MG_REGS_TDM_SWTU_PTR_BASE;
*/

#endif

#endif

/******** History ********
$Log: ag_mg_regs_tdm.h,v $
Revision 1.2  2017/07/28 07:58:35  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:28  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

