/* $Id: ag_mg_regs_armctl.h,v 1.2 2017/07/28 07:58:33 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_armctl.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_armctl.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
* ag_mg_regs_armctl.h
*
* Copyright (c) 2010 LSI Inc.  All Rights Reserved
*
* This is unpublished proprietary information of LSI Inc.
* This copyright notice does not evidence publication.
*
* The use of the software, documentation, methodologies, and other information
* contained herein is governed solely by the associated license agreements.
* Any inconsistent use shall be deemed to be a misappropriation of the
* intellectual property of LSI Inc. and treated accordingly.
*
* Primarily, the ARM control block controls the handling of interrupts to and from the
* ARM-MP complex in conjunction with the ARM-MP-complex Distributed Interrupt Controller.
* The ARM control block also controls the initialization select for both ARM MP processors
* and the DBM AXI master address selection; the initialization select determines which
* PBM-to-DBM AXI master port each bus master uses for communication with the DBM. The ARM
* control block generates an external interrupt by means of user-generated controls or any
* of the watchdog resets.
*
* The ARM control block also provides controls to enable the ECC circuitry on PPBMEM and
* a register to latch the status of several device pin 'at reset' for system configuration
* purposes.
*
* See "Physical register addresses" below for macros
* used to generate addresses for specific registers.
*
* Registers defined in this file :
*
 *  INTMASK0
 *  INTMASK1
 *  INTMASK2
 *  INTMASK3
 *  INTRAW0
 *  INTRAW1
 *  INTRAW2
 *  INTRAW3
 *  INTRAW4
 *  INTRAW5
 *  INTSTAT0
 *  INTSTAT1
 *  INTSTAT2
 *  INTSTAT3
 *  ARM0_DSS0_INT
 *  ARM0_DSS1_INT
 *  ARM0_DSS2_INT
 *  ARM0_DSS3_INT
 *  ARM1_DSS0_INT
 *  ARM1_DSS1_INT
 *  ARM1_DSS2_INT
 *  ARM1_DSS3_INT
 *  ECC_ENABLE
 *  AXI_MAS_MSB_ADR
 *  VINITHI
 *  OINT_MASK
 *  OINT_GEN
 *  OINT_STATUS
 *  OINT_CLEAR
 *  FLAG_STAT
 *  DBG_CTRL_GEN
 *  FIQ0MASK
 *  FIQ0RAW
 *  FIQ0STAT
 *  ARM0_ARM1_INT
 *  FIQ1MASK
 *  FIQ1RAW
 *  FIQ1STAT
 *  ARM1_ARM0_INT
 *  ARM0_INT
 *  ARM1_INT
*
 * Prefix naming conventions :
 *   AG_MG_REGS_XXX_RA : register/memory physical address
 *   AG_MG_REGS_XXX_RO : register/memory address offset
 *   AG_MG_REGS_XXX_RM : register mask
 *   AG_MG_REGS_XXX_BO : bit/field offset from LSB
 *   AG_MG_REGS_XXX_BM : bit/field mask
 *   AG_MG_REGS_XXX_U  : bitfields in C union typedef
 *   AG_MG_REGS_XXX_S  : registers in C struct typedef
 *   AG_MG_REGS_XX_RPT : number of identical registers in array
 *   AG_MG_REGS_XX_IVL : interval between registers in array
 *
 * NOTE: user may redefine ag_mg_regs_register
 *       in ag_mg_regs_regops.h if necessary
 * NOTE: access mode of individual bit fields matches that
 *       of containing register unless indicated otherwise
 */

#ifndef AG_MG_REGS_ARMCTRL_REGISTERS_H
#define AG_MG_REGS_ARMCTRL_REGISTERS_H

#include "ag_mg_regs_regops.h"


/*
 * Generated by HSI Designer release 2.3.5.
 */

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_INTMASK0_RO                           0x00000000
#define AG_MG_REGS_INTMASK0_RM                           0xFFFFFFFF

#define AG_MG_REGS_INTMASK0_INTMASK0_BO                  0
#define AG_MG_REGS_INTMASK0_INTMASK0_BM                  0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTMASK0_U
{
    struct
    {
        ag_mg_regs_register
            intmask0;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intmask0_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_INTMASK1_RO                           0x00000004
#define AG_MG_REGS_INTMASK1_RM                           0xFFFFFFFF

#define AG_MG_REGS_INTMASK1_INTMASK1_BO                  0
#define AG_MG_REGS_INTMASK1_INTMASK1_BM                  0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTMASK1_U
{
    struct
    {
        ag_mg_regs_register
            intmask1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intmask1_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_INTMASK2_RO                           0x00000008
#define AG_MG_REGS_INTMASK2_RM                           0xFFFFFFFF

#define AG_MG_REGS_INTMASK2_INTMASK2_BO                  0
#define AG_MG_REGS_INTMASK2_INTMASK2_BM                  0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTMASK2_U
{
    struct
    {
        ag_mg_regs_register
            intmask2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intmask2_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_INTMASK3_RO                           0x0000000C
#define AG_MG_REGS_INTMASK3_RM                           0xFFFFFFFF

#define AG_MG_REGS_INTMASK3_INTMASK3_BO                  0
#define AG_MG_REGS_INTMASK3_INTMASK3_BM                  0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTMASK3_U
{
    struct
    {
        ag_mg_regs_register
            intmask3;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intmask3_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_INTRAW0_RO                            0x00000010
#define AG_MG_REGS_INTRAW0_RM                            0xFFFFFFFF

#define AG_MG_REGS_INTRAW0_INTRAW0_BO                    0
#define AG_MG_REGS_INTRAW0_INTRAW0_BM                    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTRAW0_U
{
    struct
    {
        ag_mg_regs_register
            intraw0;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intraw0_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_INTRAW1_RO                            0x00000014
#define AG_MG_REGS_INTRAW1_RM                            0xFFFFFFFF

#define AG_MG_REGS_INTRAW1_INTRAW1_BO                    0
#define AG_MG_REGS_INTRAW1_INTRAW1_BM                    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTRAW1_U
{
    struct
    {
        ag_mg_regs_register
            intraw1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intraw1_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_INTRAW2_RO                            0x00000018
#define AG_MG_REGS_INTRAW2_RM                            0xFFFFFFFF

#define AG_MG_REGS_INTRAW2_INTRAW2_BO                    0
#define AG_MG_REGS_INTRAW2_INTRAW2_BM                    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTRAW2_U
{
    struct
    {
        ag_mg_regs_register
            intraw2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intraw2_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_INTRAW3_RO                            0x0000001C
#define AG_MG_REGS_INTRAW3_RM                            0xFFFFFFFF

#define AG_MG_REGS_INTRAW3_INTRAW3_BO                    0
#define AG_MG_REGS_INTRAW3_INTRAW3_BM                    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTRAW3_U
{
    struct
    {
        ag_mg_regs_register
            intraw3;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intraw3_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_INTRAW4_RO                            0x00000020
#define AG_MG_REGS_INTRAW4_RM                            0xFFFFFFFF

#define AG_MG_REGS_INTRAW4_INTRAW4_BO                    0
#define AG_MG_REGS_INTRAW4_INTRAW4_BM                    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTRAW4_U
{
    struct
    {
        ag_mg_regs_register
            intraw4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intraw4_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Clear on Write to 1
 */
#define AG_MG_REGS_INTRAW5_RO                            0x00000024
#define AG_MG_REGS_INTRAW5_RM                            0xFFFFFFFF

#define AG_MG_REGS_INTRAW5_INTRAW5_BO                    0
#define AG_MG_REGS_INTRAW5_INTRAW5_BM                    0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTRAW5_U
{
    struct
    {
        ag_mg_regs_register
            intraw5;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intraw5_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_INTSTAT0_RO                           0x00000030
#define AG_MG_REGS_INTSTAT0_RM                           0xFFFFFFFF

#define AG_MG_REGS_INTSTAT0_INTSTAT0_BO                  0
#define AG_MG_REGS_INTSTAT0_INTSTAT0_BM                  0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTSTAT0_U
{
    struct
    {
        ag_mg_regs_register
            intstat0;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intstat0_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_INTSTAT1_RO                           0x00000034
#define AG_MG_REGS_INTSTAT1_RM                           0xFFFFFFFF

#define AG_MG_REGS_INTSTAT1_INTSTAT1_BO                  0
#define AG_MG_REGS_INTSTAT1_INTSTAT1_BM                  0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTSTAT1_U
{
    struct
    {
        ag_mg_regs_register
            intstat1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intstat1_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_INTSTAT2_RO                           0x00000038
#define AG_MG_REGS_INTSTAT2_RM                           0xFFFFFFFF

#define AG_MG_REGS_INTSTAT2_INTSTAT2_BO                  0
#define AG_MG_REGS_INTSTAT2_INTSTAT2_BM                  0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTSTAT2_U
{
    struct
    {
        ag_mg_regs_register
            intstat2;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intstat2_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_INTSTAT3_RO                           0x0000003C
#define AG_MG_REGS_INTSTAT3_RM                           0xFFFFFFFF

#define AG_MG_REGS_INTSTAT3_INTSTAT3_BO                  0
#define AG_MG_REGS_INTSTAT3_INTSTAT3_BM                  0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_INTSTAT3_U
{
    struct
    {
        ag_mg_regs_register
            intstat3;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_intstat3_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM0_DSS0_INT_RO                      0x00000040
#define AG_MG_REGS_ARM0_DSS0_INT_RM                      0x00000007

#define AG_MG_REGS_ARM0_DSS0_INT_INTERRUPT_BO         0
#define AG_MG_REGS_ARM0_DSS0_INT_INTERRUPT_BM         0x00000007

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ARM0_DSS0_INT_U
{
    struct
    {
        ag_mg_regs_register
			interrupt0 : 1,
			interrupt1 : 1,
			interrupt2 : 1,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_arm0_dss0_int_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM0_DSS1_INT_RO                      0x00000044
#define AG_MG_REGS_ARM0_DSS1_INT_RM                      0x00000007

#define AG_MG_REGS_ARM0_DSS1_INT_INTERRUPT_BO         0
#define AG_MG_REGS_ARM0_DSS1_INT_INTERRUPT_BM         0x00000007

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ARM0_DSS1_INT_U
{
    struct
    {
        ag_mg_regs_register
			interrupt0 : 1,
			interrupt1 : 1,
			interrupt2 : 1,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_arm0_dss1_int_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM0_DSS2_INT_RO                      0x00000048
#define AG_MG_REGS_ARM0_DSS2_INT_RM                      0x00000007

#define AG_MG_REGS_ARM0_DSS2_INT_INTERRUPT_BO         0
#define AG_MG_REGS_ARM0_DSS2_INT_INTERRUPT_BM         0x00000007

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ARM0_DSS2_INT_U
{
    struct
    {
        ag_mg_regs_register
			interrupt0 : 1,
			interrupt1 : 1,
			interrupt2 : 1,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_arm0_dss2_int_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM0_DSS3_INT_RO                      0x0000004C
#define AG_MG_REGS_ARM0_DSS3_INT_RM                      0x00000007

#define AG_MG_REGS_ARM0_DSS3_INT_INTERRUPT_BO         0
#define AG_MG_REGS_ARM0_DSS3_INT_INTERRUPT_BM         0x00000007

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ARM0_DSS3_INT_U
{
    struct
    {
        ag_mg_regs_register
			interrupt0 : 1,
			interrupt1 : 1,
			interrupt2 : 1,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_arm0_dss3_int_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM1_DSS0_INT_RO                      0x00000050
#define AG_MG_REGS_ARM1_DSS0_INT_RM                      0x00000007

#define AG_MG_REGS_ARM1_DSS0_INT_INTERRUPT_BO         0
#define AG_MG_REGS_ARM1_DSS0_INT_INTERRUPT_BM         0x00000007

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ARM1_DSS0_INT_U
{
    struct
    {
        ag_mg_regs_register
			interrupt0 : 1,
			interrupt1 : 1,
			interrupt2 : 1,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_arm1_dss0_int_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM1_DSS1_INT_RO                      0x00000054
#define AG_MG_REGS_ARM1_DSS1_INT_RM                      0x00000007

#define AG_MG_REGS_ARM1_DSS1_INT_INTERRUPT_BO         0
#define AG_MG_REGS_ARM1_DSS1_INT_INTERRUPT_BM         0x00000007

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ARM1_DSS1_INT_U
{
    struct
    {
        ag_mg_regs_register
			interrupt0 : 1,
			interrupt1 : 1,
			interrupt2 : 1,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_arm1_dss1_int_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM1_DSS2_INT_RO                      0x00000058
#define AG_MG_REGS_ARM1_DSS2_INT_RM                      0x00000007

#define AG_MG_REGS_ARM1_DSS2_INT_INTERRUPT_BO         0
#define AG_MG_REGS_ARM1_DSS2_INT_INTERRUPT_BM         0x00000007

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ARM1_DSS2_INT_U
{
    struct
    {
        ag_mg_regs_register
			interrupt0 : 1,
			interrupt1 : 1,
			interrupt2 : 1,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_arm1_dss2_int_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM1_DSS3_INT_RO                      0x0000005C
#define AG_MG_REGS_ARM1_DSS3_INT_RM                      0x00000007

#define AG_MG_REGS_ARM1_DSS3_INT_INTERRUPT_BO         0
#define AG_MG_REGS_ARM1_DSS3_INT_INTERRUPT_BM         0x00000007

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ARM1_DSS3_INT_U
{
    struct
    {
        ag_mg_regs_register
            interrupt0 : 1,
            interrupt1 : 1,
            interrupt2 : 1,
            fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_arm1_dss3_int_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read / Clear on write to 1
 */
#define AG_MG_REGS_ARM_DSS_STAT_RO                      0x00000060
#define AG_MG_REGS_ARM_DSS_STAT_RM                      0x00FFFFFF

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS0_INT0_BO        0
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS0_INT0_BM        0x00000001

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS0_INT1_BO        1
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS0_INT1_BM        0x00000002

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS0_INT2_BO        2
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS0_INT2_BM        0x00000004

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS1_INT0_BO        3
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS1_INT0_BM        0x00000008

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS1_INT1_BO        4
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS1_INT1_BM        0x00000010

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS1_INT2_BO        5
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS1_INT2_BM        0x00000020

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS2_INT0_BO        6
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS2_INT0_BM        0x00000040

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS2_INT1_BO        7
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS2_INT1_BM        0x00000080

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS2_INT2_BO        8
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS2_INT2_BM        0x00000100

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS3_INT0_BO        9
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS3_INT0_BM        0x00000200

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS3_INT1_BO        10
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS3_INT1_BM        0x00000400

#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS3_INT2_BO        11
#define AG_MG_REGS_ARM_DSS_STAT_ARM0_DSS3_INT2_BM        0x00000800

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS0_INT0_BO        12
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS0_INT0_BM        0x00001000

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS0_INT1_BO        13
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS0_INT1_BM        0x00002000

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS0_INT2_BO        14
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS0_INT2_BM        0x00004000

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS1_INT0_BO        15
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS1_INT0_BM        0x00008000

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS1_INT1_BO        16
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS1_INT1_BM        0x00010000

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS1_INT2_BO        17
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS1_INT2_BM        0x00020000

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS2_INT0_BO        18
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS2_INT0_BM        0x00040000

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS2_INT1_BO        19
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS2_INT1_BM        0x00080000

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS2_INT2_BO        20
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS2_INT2_BM        0x00100000

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS3_INT0_BO        21
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS3_INT0_BM        0x00200000

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS3_INT1_BO        22
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS3_INT1_BM        0x00400000

#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS3_INT2_BO        23
#define AG_MG_REGS_ARM_DSS_STAT_ARM1_DSS3_INT2_BM        0x00800000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ARM_DSS_STAT_U
{
    struct
    {
        ag_mg_regs_register
            arm0_dss0_int0 : 1,
            arm0_dss0_int1 : 1,
            arm0_dss0_int2 : 1,
            arm0_dss1_int0 : 1,
            arm0_dss1_int1 : 1,
            arm0_dss1_int2 : 1,
            arm0_dss2_int0 : 1,
            arm0_dss2_int1 : 1,
            arm0_dss2_int2 : 1,
            arm0_dss3_int0 : 1,
            arm0_dss3_int1 : 1,
            arm0_dss3_int2 : 1,
            arm1_dss0_int0 : 1,
            arm1_dss0_int1 : 1,
            arm1_dss0_int2 : 1,
            arm1_dss1_int0 : 1,
            arm1_dss1_int1 : 1,
            arm1_dss1_int2 : 1,
            arm1_dss2_int0 : 1,
            arm1_dss2_int1 : 1,
            arm1_dss2_int2 : 1,
            arm1_dss3_int0 : 1,
            arm1_dss3_int1 : 1,
            arm1_dss3_int2 : 1,
            fill0 : 8;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_arm_dss_stat_u;
#endif

/*
 * Initialization value: 0x00000001  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_ECC_ENABLE_RO                         0x00000064
#define AG_MG_REGS_ECC_ENABLE_RM                         0x00000001

#define AG_MG_REGS_ECC_ENABLE_ECC_ENABLE_BO              0
#define AG_MG_REGS_ECC_ENABLE_ECC_ENABLE_BM              0x00000001

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ECC_ENABLE_U
{
    struct
    {
        ag_mg_regs_register
            ecc_enable : 1,
            fill0 : 31;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_ecc_enable_u;
#endif


/*
 * Initialization value: 0x000002AA  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_AXI_MAS_MSB_ADR_RO                    0x00000068
#define AG_MG_REGS_AXI_MAS_MSB_ADR_RM                    0x000000FF

#define AG_MG_REGS_AXI_MAS_MSB_ADR_AXI_MAS_MSB_ADR_BO    0
#define AG_MG_REGS_AXI_MAS_MSB_ADR_AXI_MAS_MSB_ADR_BM    0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_AXI_MAS_MSB_ADR_U
{
    struct
    {
        ag_mg_regs_register
            axi_mas_msb_adr : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_axi_mas_msb_adr_u;
#endif


/*
 * Initialization value: 0x00000003  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_VINITHI_RO                            0x0000006C
#define AG_MG_REGS_VINITHI_RM                            0x00000003

#define AG_MG_REGS_VINITHI_ARM0_VINITHI_BO               0
#define AG_MG_REGS_VINITHI_ARM0_VINITHI_BM               0x00000001

#define AG_MG_REGS_VINITHI_ARM1_VINITHI_BO               1
#define AG_MG_REGS_VINITHI_ARM1_VINITHI_BM               0x00000002

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_VINITHI_U
{
    struct
    {
        ag_mg_regs_register
            arm0_vinithi : 1,
            arm1_vinithi : 1,
            fill0 : 30;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_vinithi_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_OINT_MASK_RO                          0x00000070
#define AG_MG_REGS_OINT_MASK_RM                          0x0000FFFF

#define AG_MG_REGS_OINT_MASK_OINT_MASK_BO                0
#define AG_MG_REGS_OINT_MASK_OINT_MASK_BM                0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OINT_MASK_U
{
    struct
    {
        ag_mg_regs_register
            oint_mask : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oint_mask_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_OINT_GEN_RO                           0x00000074
#define AG_MG_REGS_OINT_GEN_RM                           0x0000FFC0

#define AG_MG_REGS_OINT_GEN_OINT_GEN_BO                  6
#define AG_MG_REGS_OINT_GEN_OINT_GEN_BM                  0x0000FFC0

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OINT_GEN_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 6,
            oint_gen : 10,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oint_gen_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_OINT_STATUS_RO                        0x00000078
#define AG_MG_REGS_OINT_STATUS_RM                        0x0000FFFF

#define AG_MG_REGS_OINT_STATUS_OINT_STAT_BO              0
#define AG_MG_REGS_OINT_STATUS_OINT_STAT_BM              0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OINT_STATUS_U
{
    struct
    {
        ag_mg_regs_register
            oint_stat : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oint_status_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_OINT_CLEAR_RO                         0x0000007C
#define AG_MG_REGS_OINT_CLEAR_RM                         0x0000FFFF

#define AG_MG_REGS_OINT_CLEAR_OINT_CLEAR_BO              0
#define AG_MG_REGS_OINT_CLEAR_OINT_CLEAR_BM              0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_OINT_CLEAR_U
{
    struct
    {
        ag_mg_regs_register
            oint_clear : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_oint_clear_u;
#endif


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_FLAG_STAT_RO                          0x00000080
#define AG_MG_REGS_FLAG_STAT_RM                          0x0000FFFF

#define AG_MG_REGS_FLAG_STAT_FLAG_STAT_BO                0
#define AG_MG_REGS_FLAG_STAT_FLAG_STAT_BM                0x0000FFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_FLAG_STAT_U
{
    struct
    {
        ag_mg_regs_register
            flag_stat : 16,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_flag_stat_u;
#endif


/*
 * Initialization value: 0x00000002  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_DBG_CTRL_GEN_RO                       0x00000090
#define AG_MG_REGS_DBG_CTRL_GEN_RM                       0x00000001

#define AG_MG_REGS_DBG_CTRL_GEN_DBG_CTRL_GEN_BO          0
#define AG_MG_REGS_DBG_CTRL_GEN_DBG_CTRL_GEN_BM          0x00000001

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_DBG_CTRL_GEN_U
{
    struct
    {
        ag_mg_regs_register
            dbg_ctrl_gen : 1,
            fill0 : 31;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_dbg_ctrl_gen_u;
#endif


/* ARM Fast Interrupt (FIQ) Controller definitions */

/*
 * All FIQ control registers share a common layout so we only define the bits masks and postions
 * once in a way that is not specific to which MP core the code is running on
 */

#define AG_MG_REGS_FIQ_BIT_POS_TXD0_EOF_B0		0
#define AG_MG_REGS_FIQ_BIT_POS_TXD0_EOF_BM		0x00000001
#define AG_MG_REGS_FIQ_BIT_POS_TXD1_EOF_B0		1
#define AG_MG_REGS_FIQ_BIT_POS_TXD1_EOF_BM		0x00000002
#define AG_MG_REGS_FIQ_BIT_POS_PCE0_EOF_0_B0		2
#define AG_MG_REGS_FIQ_BIT_POS_PCE0_EOF_0_BM		0x00000004
#define AG_MG_REGS_FIQ_BIT_POS_PCE0_EOF_1_B0		3
#define AG_MG_REGS_FIQ_BIT_POS_PCE0_EOF_1_BM		0x00000008
#define AG_MG_REGS_FIQ_BIT_POS_PCE1_EOF_0_B0		4
#define AG_MG_REGS_FIQ_BIT_POS_PCE1_EOF_0_BM		0x00000010
#define AG_MG_REGS_FIQ_BIT_POS_PCE1_EOF_1_B0		5
#define AG_MG_REGS_FIQ_BIT_POS_PCE1_EOF_1_BM		0x00000020
#define AG_MG_REGS_FIQ_BIT_POS_DBM_DMA0_0_B0		6
#define AG_MG_REGS_FIQ_BIT_POS_DBM_DMA0_0_BM		0x00000040
#define AG_MG_REGS_FIQ_BIT_POS_DBM_DMA0_1_B0		7
#define AG_MG_REGS_FIQ_BIT_POS_DBM_DMA0_1_BM		0x00000080
#define AG_MG_REGS_FIQ_BIT_POS_DBM_DMA1_0_B0		8
#define AG_MG_REGS_FIQ_BIT_POS_DBM_DMA1_0_BM		0x00000100
#define AG_MG_REGS_FIQ_BIT_POS_DBM_DMA1_1_B0		9
#define AG_MG_REGS_FIQ_BIT_POS_DBM_DMA1_1_BM		0x00000200
#define AG_MG_REGS_FIQ_BIT_POS_PEI_B0			10
#define AG_MG_REGS_FIQ_BIT_POS_PEI_BM			0x00000400
#define AG_MG_REGS_FIQ_BIT_POS_SRIO0_B0			11
#define AG_MG_REGS_FIQ_BIT_POS_SRIO0_BM			0x00000800
#define AG_MG_REGS_FIQ_BIT_POS_SRIO1_B0			12
#define AG_MG_REGS_FIQ_BIT_POS_SRIO1_BM			0x00001000
#define AG_MG_REGS_FIQ_BIT_POS_GT0_B0			13
#define AG_MG_REGS_FIQ_BIT_POS_GT0_BM			0x00002000
#define AG_MG_REGS_FIQ_BIT_POS_GT1_B0			14
#define AG_MG_REGS_FIQ_BIT_POS_GT1_BM			0x00004000
#define AG_MG_REGS_FIQ_BIT_POS_DSS0_ARM_0_B0		15
#define AG_MG_REGS_FIQ_BIT_POS_DSS0_ARM_0_BM		0x00008000
#define AG_MG_REGS_FIQ_BIT_POS_DSS0_ARM_1_B0		16
#define AG_MG_REGS_FIQ_BIT_POS_DSS0_ARM_1_BM		0x00010000
#define AG_MG_REGS_FIQ_BIT_POS_DSS0_ARM_2_B0		17
#define AG_MG_REGS_FIQ_BIT_POS_DSS0_ARM_2_BM		0x00020000
#define AG_MG_REGS_FIQ_BIT_POS_DSS1_ARM_0_B0		18
#define AG_MG_REGS_FIQ_BIT_POS_DSS1_ARM_0_BM		0x00040000
#define AG_MG_REGS_FIQ_BIT_POS_DSS1_ARM_1_B0		19
#define AG_MG_REGS_FIQ_BIT_POS_DSS1_ARM_1_BM		0x00080000
#define AG_MG_REGS_FIQ_BIT_POS_DSS1_ARM_2_B0		20
#define AG_MG_REGS_FIQ_BIT_POS_DSS1_ARM_2_BM		0x00100000
#define AG_MG_REGS_FIQ_BIT_POS_DSS2_ARM_0_B0		21
#define AG_MG_REGS_FIQ_BIT_POS_DSS2_ARM_0_BM		0x00200000
#define AG_MG_REGS_FIQ_BIT_POS_DSS2_ARM_1_B0		22
#define AG_MG_REGS_FIQ_BIT_POS_DSS2_ARM_1_BM		0x00400000
#define AG_MG_REGS_FIQ_BIT_POS_DSS2_ARM_2_B0		23
#define AG_MG_REGS_FIQ_BIT_POS_DSS2_ARM_2_BM		0x00800000
#define AG_MG_REGS_FIQ_BIT_POS_DSS3_ARM_0_B0		24
#define AG_MG_REGS_FIQ_BIT_POS_DSS3_ARM_0_BM		0x01000000
#define AG_MG_REGS_FIQ_BIT_POS_DSS3_ARM_1_B0		25
#define AG_MG_REGS_FIQ_BIT_POS_DSS3_ARM_1_BM		0x02000000
#define AG_MG_REGS_FIQ_BIT_POS_DSS3_ARM_2_B0		26
#define AG_MG_REGS_FIQ_BIT_POS_DSS3_ARM_2_BM		0x04000000

#define AG_MG_REGS_FIQ_BIT_POS_ARM1_ARM0_0_B0		27
#define AG_MG_REGS_FIQ_BIT_POS_ARM1_ARM0_0_BM		0x08000000
#define AG_MG_REGS_FIQ_BIT_POS_ARM1_ARM0_1_B0		28
#define AG_MG_REGS_FIQ_BIT_POS_ARM1_ARM0_1_BM		0x10000000
#define AG_MG_REGS_FIQ_BIT_POS_ARM1_ARM0_2_B0		29
#define AG_MG_REGS_FIQ_BIT_POS_ARM1_ARM0_2_BM		0x20000000

#define AG_MG_REGS_FIQ_BIT_POS_ARM0_ARM1_0_B0		27
#define AG_MG_REGS_FIQ_BIT_POS_ARM0_ARM1_0_BM		0x08000000
#define AG_MG_REGS_FIQ_BIT_POS_ARM0_ARM1_1_B0		28
#define AG_MG_REGS_FIQ_BIT_POS_ARM0_ARM1_1_BM		0x10000000
#define AG_MG_REGS_FIQ_BIT_POS_ARM0_ARM1_2_B0		29
#define AG_MG_REGS_FIQ_BIT_POS_ARM0_ARM1_2_BM		0x20000000

#define AG_MG_REGS_FIQ_BIT_POS_ARM_SW_INT_0_B0		30
#define AG_MG_REGS_FIQ_BIT_POS_ARM_SW_INT_0_BM		0x40000000
#define AG_MG_REGS_FIQ_BIT_POS_ARM_SW_INT_1_B0		31
#define AG_MG_REGS_FIQ_BIT_POS_ARM_SW_INT_1_BM		0x80000000


/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read / Write
 */
#define AG_MG_REGS_FIQ0MASK_RO				0x000000A0
#define AG_MG_REGS_FIQ0MASK_RM				0xFFFFFFFF

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read / COW1
 */
#define AG_MG_REGS_FIQ0RAW_RO				0x000000A4
#define AG_MG_REGS_FIQ0RAW_RM				0xFFFFFFFF

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_FIQ0STAT_RO				0x000000A8
#define AG_MG_REGS_FIQ0STAT_RM				0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_FIQ0STAT_U
{
    struct
    {
        ag_mg_regs_register
	    txd0_eof : 1,
	    txd1_eof : 1,
	    pce0_eof_0 : 1,
	    pce0_eof_1 : 1,
	    pce1_eof_0 : 1,
	    pce1_eof_1 : 1,
	    dbm_dma0_0 : 1,
	    dbm_dma0_1 : 1,
	    dbm_dma1_0 : 1,
	    dbm_dma1_1 : 1,
	    pei : 1,
	    srio0 : 1,
	    srio1 : 1,
	    gt0 : 1,
	    gt1 : 1,
	    dss0_arm0_0 : 1,
	    dss0_arm0_1 : 1,
	    dss0_arm0_2 : 1,
	    dss1_arm0_0 : 1,
	    dss1_arm0_1 : 1,
	    dss1_arm0_2 : 1,
	    dss2_arm0_0 : 1,
	    dss2_arm0_1 : 1,
	    dss2_arm0_2 : 1,
	    dss3_arm0_0 : 1,
	    dss3_arm0_1 : 1,
	    dss3_arm0_2 : 1,
	    arm1_arm0_0 : 1,
	    arm1_arm0_1 : 1,
	    arm1_arm0_2 : 1,
	    arm0_sw_int_0 : 1,
	    arm0_sw_int_1 : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_fiq0bits_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM0_ARM1_INT_RO			0x000000AC
#define AG_MG_REGS_ARM0_ARM1_INT_RM			0x00000000

#define AG_MG_REGS_ARM0_ARM1_INT_ARM_ARM_INT0_BO	0
#define AG_MG_REGS_ARM0_ARM1_INT_ARM_ARM_INT0_BM	0x00000001

#define AG_MG_REGS_ARM0_ARM1_INT_ARM_ARM_INT1_BO	1
#define AG_MG_REGS_ARM0_ARM1_INT_ARM_ARM_INT1_BM	0x00000002

#define AG_MG_REGS_ARM0_ARM1_INT_ARM_ARM_INT2_BO	2
#define AG_MG_REGS_ARM0_ARM1_INT_ARM_ARM_INT2_BM	0x00000004

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ARM_ARM_INT_U
{
    struct
    {
        ag_mg_regs_register
	    arm_arm_int0 : 1,
	    arm_arm_int1 : 1,
	    arm_arm_int2 : 1,
	    fill0 : 29;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_arm_arm_int_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read / Write
 */
#define AG_MG_REGS_FIQ1MASK_RO				0x000000B0
#define AG_MG_REGS_FIQ1MASK_RM				0xFFFFFFFF

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read / COW1
 */
#define AG_MG_REGS_FIQ1RAW_RO				0x000000B4
#define AG_MG_REGS_FIQ1RAW_RM				0xFFFFFFFF

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_FIQ1STAT_RO				0x000000B8
#define AG_MG_REGS_FIQ1STAT_RM				0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_FIQ1MASK_U
{
    struct
    {
        ag_mg_regs_register
	    txd0_eof : 1,
	    txd1_eof : 1,
	    pce0_eof_0 : 1,
	    pce0_eof_1 : 1,
	    pce1_eof_0 : 1,
	    pce1_eof_1 : 1,
	    dbm_dma0_0 : 1,
	    dbm_dma0_1 : 1,
	    dbm_dma1_0 : 1,
	    dbm_dma1_1 : 1,
	    pei : 1,
	    srio0 : 1,
	    srio1 : 1,
	    gt0 : 1,
	    gt1 : 1,
	    dss0_arm1_0 : 1,
	    dss0_arm1_1 : 1,
	    dss0_arm1_2 : 1,
	    dss1_arm1_0 : 1,
	    dss1_arm1_1 : 1,
	    dss1_arm1_2 : 1,
	    dss2_arm1_0 : 1,
	    dss2_arm1_1 : 1,
	    dss2_arm1_2 : 1,
	    dss3_arm1_0 : 1,
	    dss3_arm1_1 : 1,
	    dss3_arm1_2 : 1,
	    arm0_arm1_0 : 1,
	    arm0_arm1_1 : 1,
	    arm0_arm1_2 : 1,
	    arm1_sw_int_0 : 1,
	    arm1_sw_int_1 : 1;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_fiq1bits_u;
#endif

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM1_ARM0_INT_RO			0x000000BC
#define AG_MG_REGS_ARM1_ARM0_INT_RM			0x00000000

#define AG_MG_REGS_ARM1_ARM0_INT_ARM_ARM_INT0_BO	0
#define AG_MG_REGS_ARM1_ARM0_INT_ARM_ARM_INT0_BM	0x00000001

#define AG_MG_REGS_ARM1_ARM0_INT_ARM_ARM_INT1_BO	1
#define AG_MG_REGS_ARM1_ARM0_INT_ARM_ARM_INT1_BM	0x00000002

#define AG_MG_REGS_ARM1_ARM0_INT_ARM_ARM_INT2_BO	2
#define AG_MG_REGS_ARM1_ARM0_INT_ARM_ARM_INT2_BM	0x00000004

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM0_INT_RO		0x000000C0
#define AG_MG_REGS_ARM0_INT_RM		0x00000000

#define AG_MG_REGS_ARM0_INT_SW_INT0_BO	0
#define AG_MG_REGS_ARM0_INT_SW_INT0_BM	0x00000001

#define AG_MG_REGS_ARM0_INT_SW_INT1_BO	1
#define AG_MG_REGS_ARM0_INT_SW_INT1_BM	0x00000002

/*
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Write Only
 */
#define AG_MG_REGS_ARM1_INT_RO		0x000000C4
#define AG_MG_REGS_ARM1_INT_RM		0x00000000

#define AG_MG_REGS_ARM1_INT_SW_INT0_BO	0
#define AG_MG_REGS_ARM1_INT_SW_INT0_BM	0x00000001

#define AG_MG_REGS_ARM1_INT_SW_INT1_BO	1
#define AG_MG_REGS_ARM1_INT_SW_INT1_BM	0x00000002



#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_ARM_SW_INT_U
{
    struct
    {
        ag_mg_regs_register
	    sw_int0 : 1,
	    sw_int1 : 1,
	    fill0 : 30;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_arm_sw_int_u;
#endif




/*
 * Physical register addresses (for arm accessing armctrl)
 */
#ifdef AG_MG_REGS_BUILT_FOR_DSS
#define AG_MG_REGS_ARMCTL_BASE		0xC3045000
#else
#define AG_MG_REGS_ARMCTL_BASE		0x30045000
#endif

#define AG_MG_REGS_ARMCTL_REG(ro)		(AG_MG_REGS_ARMCTL_BASE+(ro))

#define AG_MG_REGS_ARMCTL_INTMASK0_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTMASK0_RO)
#define AG_MG_REGS_ARMCTL_INTMASK1_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTMASK1_RO)
#define AG_MG_REGS_ARMCTL_INTMASK2_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTMASK2_RO)
#define AG_MG_REGS_ARMCTL_INTMASK3_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTMASK3_RO)
#define AG_MG_REGS_ARMCTL_INTRAW0_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTRAW0_RO)
#define AG_MG_REGS_ARMCTL_INTRAW1_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTRAW1_RO)
#define AG_MG_REGS_ARMCTL_INTRAW2_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTRAW2_RO)
#define AG_MG_REGS_ARMCTL_INTRAW3_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTRAW3_RO)
#define AG_MG_REGS_ARMCTL_INTRAW4_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTRAW4_RO)
#define AG_MG_REGS_ARMCTL_INTRAW5_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTRAW5_RO)
#define AG_MG_REGS_ARMCTL_INTSTAT0_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTSTAT0_RO)
#define AG_MG_REGS_ARMCTL_INTSTAT1_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTSTAT1_RO)
#define AG_MG_REGS_ARMCTL_INTSTAT2_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTSTAT2_RO)
#define AG_MG_REGS_ARMCTL_INTSTAT3_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_INTSTAT3_RO)
#define AG_MG_REGS_ARMCTL_ARM0_DSS0_INT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM0_DSS0_INT_RO)
#define AG_MG_REGS_ARMCTL_ARM0_DSS1_INT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM0_DSS1_INT_RO)
#define AG_MG_REGS_ARMCTL_ARM0_DSS2_INT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM0_DSS2_INT_RO)
#define AG_MG_REGS_ARMCTL_ARM0_DSS3_INT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM0_DSS3_INT_RO)
#define AG_MG_REGS_ARMCTL_ARM1_DSS0_INT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM1_DSS0_INT_RO)
#define AG_MG_REGS_ARMCTL_ARM1_DSS1_INT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM1_DSS1_INT_RO)
#define AG_MG_REGS_ARMCTL_ARM1_DSS2_INT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM1_DSS2_INT_RO)
#define AG_MG_REGS_ARMCTL_ARM1_DSS3_INT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM1_DSS3_INT_RO)
#define AG_MG_REGS_ARMCTL_ARM_DSS_STAT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM_DSS_STAT_RO)
#define AG_MG_REGS_ARMCTL_ECC_ENABLE_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ECC_ENABLE_RO)
#define AG_MG_REGS_ARMCTL_AXI_MAS_MSB_ADR_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_AXI_MAS_MSB_ADR_RO)
#define AG_MG_REGS_ARMCTL_VINITHI_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_VINITHI_RO)
#define AG_MG_REGS_ARMCTL_OINT_MASK_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_OINT_MASK_RO)
#define AG_MG_REGS_ARMCTL_OINT_GEN_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_OINT_GEN_RO)
#define AG_MG_REGS_ARMCTL_OINT_STATUS_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_OINT_STATUS_RO)
#define AG_MG_REGS_ARMCTL_OINT_CLEAR_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_OINT_CLEAR_RO)
#define AG_MG_REGS_ARMCTL_FLAG_STAT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_FLAG_STAT_RO)
#define AG_MG_REGS_ARMCTL_DBG_CTRL_GEN_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_DBG_CTRL_GEN_RO)
#define AG_MG_REGS_FIQ0MASK_RA		AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_FIQ0MASK_RO)
#define AG_MG_REGS_FIQ0RAW_RA		AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_FIQ0RAW_RO)
#define AG_MG_REGS_FIQ0STAT_RA		AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_FIQ0STAT_RO)
#define AG_MG_REGS_ARM0_ARM1_INT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM0_ARM1_INT_RO)
#define AG_MG_REGS_FIQ1MASK_RA		AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_FIQ1MASK_RO)
#define AG_MG_REGS_FIQ1RAW_RA		AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_FIQ1RAW_RO)
#define AG_MG_REGS_FIQ1STAT_RA		AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_FIQ1STAT_RO)
#define AG_MG_REGS_ARM1_ARM0_INT_RA	AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM1_ARM0_INT_RO)
#define AG_MG_REGS_ARM0_INT_RA		AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM0_INT_RO)
#define AG_MG_REGS_ARM1_INT_RA		AG_MG_REGS_ARMCTL_REG(AG_MG_REGS_ARM1_INT_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES

typedef struct AG_MG_REGS_ARMCTL_REGS_S
{
	ag_mg_regs_intmask0_u	intmask0 ;
	ag_mg_regs_intmask1_u	intmask1 ;
	ag_mg_regs_intmask2_u	intmask2 ;
	ag_mg_regs_intmask3_u	intmask3 ;
	ag_mg_regs_intraw0_u	intraw0 ;
	ag_mg_regs_intraw1_u	intraw1 ;
	ag_mg_regs_intraw2_u	intraw2 ;
	ag_mg_regs_intraw3_u	intraw3 ;
	ag_mg_regs_intraw4_u	intraw4 ;
	ag_mg_regs_intraw5_u	intraw5 ;
	ag_mg_regs_register	fill0[2] ;
	ag_mg_regs_intstat0_u	intstat0 ;
	ag_mg_regs_intstat1_u	intstat1 ;
	ag_mg_regs_intstat2_u	intstat2 ;
	ag_mg_regs_intstat3_u	intstat3 ;
	ag_mg_regs_arm0_dss0_int_u	arm0_dss0_int ;
	ag_mg_regs_arm0_dss1_int_u	arm0_dss1_int ;
	ag_mg_regs_arm0_dss2_int_u	arm0_dss2_int ;
	ag_mg_regs_arm0_dss3_int_u	arm0_dss3_int ;
	ag_mg_regs_arm1_dss0_int_u	arm1_dss0_int ;
	ag_mg_regs_arm1_dss1_int_u	arm1_dss1_int ;
	ag_mg_regs_arm1_dss2_int_u	arm1_dss2_int ;
	ag_mg_regs_arm1_dss3_int_u	arm1_dss3_int ;
	ag_mg_regs_arm_dss_stat_u	arm_dss_stat;
	ag_mg_regs_ecc_enable_u	ecc_enable ;
	ag_mg_regs_axi_mas_msb_adr_u	axi_mas_msb_adr ;
	ag_mg_regs_vinithi_u	vinithi ;
	ag_mg_regs_oint_mask_u	oint_mask ;
	ag_mg_regs_oint_gen_u	oint_gen ;
	ag_mg_regs_oint_status_u	oint_status ;
	ag_mg_regs_oint_clear_u	oint_clear ;
	ag_mg_regs_flag_stat_u	flag_stat ;
	ag_mg_regs_register		fill1[3] ;
	ag_mg_regs_dbg_ctrl_gen_u	dbg_ctrl_gen ;
	ag_mg_regs_register		fill2[3] ;
	ag_mg_regs_fiq0bits_u	fiq0mask ;
	ag_mg_regs_fiq0bits_u	fiq0raw ;
	ag_mg_regs_fiq0bits_u	fiq0stat ;
	ag_mg_regs_arm_arm_int_u	arm0arm1int ;
	ag_mg_regs_fiq1bits_u	fiq1mask ;
	ag_mg_regs_fiq1bits_u	fiq1raw ;
	ag_mg_regs_fiq1bits_u	fiq1stat ;
	ag_mg_regs_arm_arm_int_u	arm1arm0int ;
	ag_mg_regs_arm_sw_int_u	arm0swint ;
	ag_mg_regs_arm_sw_int_u	arm1swint ;
} ag_mg_regs_armctrl_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_armctrl_reg_s *armctrl_reg =
*       (volatile ag_mg_regs_armctrl_reg_s *)AG_MG_REGS_ARMCTL_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_armctl.h,v $
Revision 1.2  2017/07/28 07:58:33  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:24  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:25  srane
Initial checkin


$Endlog$
*/

