/* $Id: ag_mg_regs_mpu.h,v 1.2 2017/07/28 07:58:34 harrchan Exp $
 * $Source: /auto/diag/ngd-linux-rep/cvs/ng_diag/dsp_src/src/oakenshield_dsp/dss/inc/ag_mg_regs_mpu.h,v $
 *------------------------------------------------------------------
 * ag_mg_regs_mpu.h
 *
 * Mar 2012, Smita Rane
 *
 * Copyright (c) 2012-2017 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *------------------------------------------------------------------
 */

/*
* ag_mg_regs_dss_mpu.h
*
* Copyright (c) 2009 LSI Inc.  All Rights Reserved
*
* This is unpublished proprietary information of LSI Inc.
* This copyright notice does not evidence publication.
*
* The use of the software, documentation, methodologies, and other information
* contained herein is governed solely by the associated license agreements.
* Any inconsistent use shall be deemed to be a misappropriation of the
* intellectual property of LSI Inc. and treated accordingly.
*
* This file defines DSS Subsystem (DSS) Memory Protection Unit (MPU) registers.
*
* Register addresses defined herein are for
*  code running on the DSS accessing its own MPU.
*
* See "Physical register addresses" below for macros
* used to generate addresses for specific registers.
*
* Registers defined in this file :
 *  MPU_CTRL
 *  MPU_ATTRDF
 *  MPU_CBGE
 *  MPU_XP_ESTAT
 *  MPU_XP_EADDR
 *  MPU_XD_ESTAT
 *  MPU_XD_EADDR
 *  MPU_XA_ESTAT
 *  MPU_XA_EADDR
 *  MPU_XB_ESTAT
 *  MPU_XB_EADDR
 *  MPU_ATT_RANGE0
 *  MPU_ATT_RANGE1
 *  MPU_ATT_RANGE2
 *  MPU_ATT_RANGE3
 *  MPU_ATT_RANGE4
 *  MPU_ATT_RANGE5
 *  MPU_ATT_RANGE6
 *  MPU_ATT_RANGE7
 *  MPU_RANGE
 *  MPU_RANGE1
 *  MPU_RANGE2
 *  MPU_RANGE3
 *  MPU_RANGE4
 *  MPU_RANGE5
 *  MPU_RANGE6
 *  MPU_RANGE7
 *  MPU_PROCID
*
* Prefix naming conventions :
*   AG_MG_REGS_XXX_RA : register/memory physical address
*   AG_MG_REGS_XXX_RO : register/memory address offset
*   AG_MG_REGS_XXX_RM : register mask
*   AG_MG_REGS_XXX_BO : bit/field offset from LSB
*   AG_MG_REGS_XXX_BM : bit/field mask
*   AG_MG_REGS_XXX_U  : bitfields in C union typedef
*   AG_MG_REGS_XXX_S  : registers in C struct typedef
*   LSI_SP25XX_XX_RPT : number of identical registers in array
*   LSI_SP25XX_XX_IVL : interval between registers in array
*
* NOTE: user may redefine ag_mg_regs_register
*       in ag_mg_regs_regops.h if necessary
* NOTE: access mode of individual bit fields matches that
*       of containing register unless indicated otherwise
*/

#ifndef AG_MG_REGS_DSS_MPU_REGISTERS_H
#define AG_MG_REGS_DSS_MPU_REGISTERS_H

#include "ag_mg_regs_regops.h"


/*
 * Generated by HSI Designer release 2.3.5.
 */





/*
 * MPU_CTRL (MPU Control Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MPU_CTRL_RO                     0x00000000
#define AG_MG_REGS_MPU_CTRL_RM                     0x00000111

#define AG_MG_REGS_MPU_CTRL_MPUEN_BO               0
#define AG_MG_REGS_MPU_CTRL_MPUEN_BM               0x00000001

#define AG_MG_REGS_MPU_CTRL_WCCEN_BO               4
#define AG_MG_REGS_MPU_CTRL_WCCEN_BM               0x00000010

#define AG_MG_REGS_MPU_CTRL_ACEN_BO                8
#define AG_MG_REGS_MPU_CTRL_ACEN_BM                0x00000100

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_CTRL_U
{
    struct
    {
        ag_mg_regs_register
            mpuen : 1,
            fill2 : 3,
            wccen : 1,
            fill1 : 3,
            acen : 1,
            fill0 : 23;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_ctrl_u;
#endif


/*
 * MPU_ATTRDF (MPU Default Attributes Register)
 * Initialization value: 0x0E000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MPU_ATTRDF_RO                   0x00000020
#define AG_MG_REGS_MPU_ATTRDF_RM                   0x0F0F3F0F

#define AG_MG_REGS_MPU_ATTRDF_XAXBACCESS_BO        0
#define AG_MG_REGS_MPU_ATTRDF_XAXBACCESS_BM        0x0000000F

#define AG_MG_REGS_MPU_ATTRDF_XPACCESS_BO          8
#define AG_MG_REGS_MPU_ATTRDF_XPACCESS_BM          0x00000F00

#define AG_MG_REGS_MPU_ATTRDF_XDACCESS_BO          16
#define AG_MG_REGS_MPU_ATTRDF_XDACCESS_BM          0x000F0000

#define AG_MG_REGS_MPU_ATTRDF_AXI_ATTR_BO          24
#define AG_MG_REGS_MPU_ATTRDF_AXI_ATTR_BM          0x0F000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_ATTRDF_U
{
    struct
    {
        ag_mg_regs_register
            xaxbaccess : 4,
            fill3 : 4,
            xpaccess : 4,
            fill2 : 4,
            xdaccess : 4,
            fill1 : 4,
            axi_attr : 4,
            fill0 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_attrdf_u;
#endif


/*
 * MPU_CBGE (MPU Core Bus Global Exception Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MPU_CBGE_RO                     0x000000E0
#define AG_MG_REGS_MPU_CBGE_RM                     0x0000000F

#define AG_MG_REGS_MPU_CBGE_EXCP_BO                0
#define AG_MG_REGS_MPU_CBGE_EXCP_BM                0x00000001

#define AG_MG_REGS_MPU_CBGE_EXCPNUM_BO             1
#define AG_MG_REGS_MPU_CBGE_EXCPNUM_BM             0x0000000E

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_CBGE_U
{
    struct
    {
        ag_mg_regs_register
            excp : 1,
            excpnum : 3,
            fill0 : 28;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_cbge_u;
#endif


/*
 * MPU_XP_ESTAT (MPU XP Exception Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MPU_XP_ESTAT_RO                 0x00000100
#define AG_MG_REGS_MPU_XP_ESTAT_RM                 0x000000FE

#define AG_MG_REGS_MPU_XP_ESTAT_ATTR_BO            1
#define AG_MG_REGS_MPU_XP_ESTAT_ATTR_BM            0x0000007E

#define AG_MG_REGS_MPU_XP_ESTAT_EXCP_BO            7
#define AG_MG_REGS_MPU_XP_ESTAT_EXCP_BM            0x00000080

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_XP_ESTAT_U
{
    struct
    {
        ag_mg_regs_register
            fill1 : 1,
            attr : 6,
            excp : 1,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_xp_estat_u;
#endif


/*
 * MPU_XP_EADDR (MPU XP Exception Address Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MPU_XP_EADDR_RO                 0x00000120
#define AG_MG_REGS_MPU_XP_EADDR_RM                 0xFFFFFFFF

#define AG_MG_REGS_MPU_XP_EADDR_ADR_BO             0
#define AG_MG_REGS_MPU_XP_EADDR_ADR_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_XP_EADDR_U
{
    struct
    {
        ag_mg_regs_register
            adr;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_xp_eaddr_u;
#endif


/*
 * MPU_XD_ESTAT (MPU XD Exception Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MPU_XD_ESTAT_RO                 0x00000140
#define AG_MG_REGS_MPU_XD_ESTAT_RM                 0x00000F82

#define AG_MG_REGS_MPU_XD_ESTAT_WR_BO              1
#define AG_MG_REGS_MPU_XD_ESTAT_WR_BM              0x00000002

#define AG_MG_REGS_MPU_XD_ESTAT_EXCP_BO            7
#define AG_MG_REGS_MPU_XD_ESTAT_EXCP_BM            0x00000080

#define AG_MG_REGS_MPU_XD_ESTAT_RANGE_BO           8
#define AG_MG_REGS_MPU_XD_ESTAT_RANGE_BM           0x00000F00

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_XD_ESTAT_U
{
    struct
    {
        ag_mg_regs_register
            fill2 : 1,
            wr : 1,
            fill1 : 5,
            excp : 1,
            range : 4,
            fill0 : 20;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_xd_estat_u;
#endif


/*
 * MPU_XD_EADDR (MPU XD Exception Address Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MPU_XD_EADDR_RO                 0x00000160
#define AG_MG_REGS_MPU_XD_EADDR_RM                 0xFFFFFFFF

#define AG_MG_REGS_MPU_XD_EADDR_ADR_BO             0
#define AG_MG_REGS_MPU_XD_EADDR_ADR_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_XD_EADDR_U
{
    struct
    {
        ag_mg_regs_register
            adr;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_xd_eaddr_u;
#endif


/*
 * MPU_XA_ESTAT (MPU XA Exception Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MPU_XA_ESTAT_RO                 0x00000180
#define AG_MG_REGS_MPU_XA_ESTAT_RM                 0x0000FFFF

#define AG_MG_REGS_MPU_XA_ESTAT_ESM_BO             0
#define AG_MG_REGS_MPU_XA_ESTAT_ESM_BM             0x00000001

#define AG_MG_REGS_MPU_XA_ESTAT_ATTR_BO            1
#define AG_MG_REGS_MPU_XA_ESTAT_ATTR_BM            0x0000007E

#define AG_MG_REGS_MPU_XA_ESTAT_EXCP_BO            7
#define AG_MG_REGS_MPU_XA_ESTAT_EXCP_BM            0x00000080

#define AG_MG_REGS_MPU_XA_ESTAT_CMD_BO             8
#define AG_MG_REGS_MPU_XA_ESTAT_CMD_BM             0x00000F00

#define AG_MG_REGS_MPU_XA_ESTAT_SZ_BO              12
#define AG_MG_REGS_MPU_XA_ESTAT_SZ_BM              0x00003000

#define AG_MG_REGS_MPU_XA_ESTAT_BRES_BO            14
#define AG_MG_REGS_MPU_XA_ESTAT_BRES_BM            0x00004000

#define AG_MG_REGS_MPU_XA_ESTAT_WRES_BO            15
#define AG_MG_REGS_MPU_XA_ESTAT_WRES_BM            0x00008000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_XA_ESTAT_U
{
    struct
    {
        ag_mg_regs_register
            esm : 1,
            attr : 6,
            excp : 1,
            cmd : 4,
            sz : 2,
            bres : 1,
            wres : 1,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_xa_estat_u;
#endif


/*
 * MPU_XA_EADDR (MPU XA Exception Address Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MPU_XA_EADDR_RO                 0x000001A0
#define AG_MG_REGS_MPU_XA_EADDR_RM                 0xFFFFFFFF

#define AG_MG_REGS_MPU_XA_EADDR_ADR_BO             0
#define AG_MG_REGS_MPU_XA_EADDR_ADR_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_XA_EADDR_U
{
    struct
    {
        ag_mg_regs_register
            adr;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_xa_eaddr_u;
#endif


/*
 * MPU_XB_ESTAT (MPU XB Exception Status Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MPU_XB_ESTAT_RO                 0x000001C0
#define AG_MG_REGS_MPU_XB_ESTAT_RM                 0x0000FFFF

#define AG_MG_REGS_MPU_XB_ESTAT_ESM_BO             0
#define AG_MG_REGS_MPU_XB_ESTAT_ESM_BM             0x00000001

#define AG_MG_REGS_MPU_XB_ESTAT_ATTR_BO            1
#define AG_MG_REGS_MPU_XB_ESTAT_ATTR_BM            0x0000007E

#define AG_MG_REGS_MPU_XB_ESTAT_EXCP_BO            7
#define AG_MG_REGS_MPU_XB_ESTAT_EXCP_BM            0x00000080

#define AG_MG_REGS_MPU_XB_ESTAT_CMD_BO             8
#define AG_MG_REGS_MPU_XB_ESTAT_CMD_BM             0x00000F00

#define AG_MG_REGS_MPU_XB_ESTAT_SZ_BO              12
#define AG_MG_REGS_MPU_XB_ESTAT_SZ_BM              0x00003000

#define AG_MG_REGS_MPU_XB_ESTAT_BRES_BO            14
#define AG_MG_REGS_MPU_XB_ESTAT_BRES_BM            0x00004000

#define AG_MG_REGS_MPU_XB_ESTAT_WRES_BO            15
#define AG_MG_REGS_MPU_XB_ESTAT_WRES_BM            0x00008000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_XB_ESTAT_U
{
    struct
    {
        ag_mg_regs_register
            esm : 1,
            attr : 6,
            excp : 1,
            cmd : 4,
            sz : 2,
            bres : 1,
            wres : 1,
            fill0 : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_xb_estat_u;
#endif


/*
 * MPU_XB_EADDR (MPU XB Exception Address Register)
 * Initialization value: 0x00000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MPU_XB_EADDR_RO                 0x000001E0
#define AG_MG_REGS_MPU_XB_EADDR_RM                 0xFFFFFFFF

#define AG_MG_REGS_MPU_XB_EADDR_ADR_BO             0
#define AG_MG_REGS_MPU_XB_EADDR_ADR_BM             0xFFFFFFFF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_XB_EADDR_U
{
    struct
    {
        ag_mg_regs_register
            adr;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_xb_eaddr_u;
#endif


/*
 * MPU_ATT_RANGE<0-7> (MPU Attribute Range Registers)
 * Initialization value: 0x0E000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MPU_ATT_RANGE_RO               0x00000400
#define AG_MG_REGS_MPU_ATT_RANGE_RM               0x0F0F0F0F

#define AG_MG_REGS_MPU_ATT_RANGE_XAXBACCESS_BO    0
#define AG_MG_REGS_MPU_ATT_RANGE_XAXBACCESS_BM    0x0000000F

#define AG_MG_REGS_MPU_ATT_RANGE_XPACCESS_BO      8
#define AG_MG_REGS_MPU_ATT_RANGE_XPACCESS_BM      0x00000F00

#define AG_MG_REGS_MPU_ATT_RANGE_XDACCESS_BO      16
#define AG_MG_REGS_MPU_ATT_RANGE_XDACCESS_BM      0x000F0000

#define AG_MG_REGS_MPU_ATT_RANGE_AXI_ATTR_BO      24
#define AG_MG_REGS_MPU_ATT_RANGE_AXI_ATTR_BM      0x0F000000

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_ATT_RANGE_U
{
    struct
    {
        ag_mg_regs_register
            xaxbaccess : 4,
            fill3 : 4,
            xpaccess : 4,
            fill2 : 4,
            xdaccess : 4,
            fill1 : 4,
            axi_attr : 4,
            fill0 : 4;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_att_u;
#endif

/*
 * Initialization value: 0x0E000000  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MPU_ATT_RANGE0_RO               0x00000400
#define AG_MG_REGS_MPU_ATT_RANGE0_RM               0x0F0F0F0F

#define AG_MG_REGS_MPU_ATT_RANGE1_RO               0x00000420
#define AG_MG_REGS_MPU_ATT_RANGE1_RM               0x0F0F0F0F

#define AG_MG_REGS_MPU_ATT_RANGE2_RO               0x00000440
#define AG_MG_REGS_MPU_ATT_RANGE2_RM               0x0F0F0F0F

#define AG_MG_REGS_MPU_ATT_RANGE3_RO               0x00000460
#define AG_MG_REGS_MPU_ATT_RANGE3_RM               0x0F0F0F0F

#define AG_MG_REGS_MPU_ATT_RANGE4_RO               0x00000480
#define AG_MG_REGS_MPU_ATT_RANGE4_RM               0x0F0F0F0F

#define AG_MG_REGS_MPU_ATT_RANGE5_RO               0x000004A0
#define AG_MG_REGS_MPU_ATT_RANGE5_RM               0x0F0F0F0F

#define AG_MG_REGS_MPU_ATT_RANGE6_RO               0x000004C0
#define AG_MG_REGS_MPU_ATT_RANGE6_RM               0x0F0F0F0F

#define AG_MG_REGS_MPU_ATT_RANGE7_RO               0x000004E0
#define AG_MG_REGS_MPU_ATT_RANGE7_RM               0x0F0F0F0F

/*
 * MPU_RANGE<0-7> (MPU Address Range Registers)
 * Initialization value: 0x0000001E  Initialization mask: 0xFFFFFFFF
 * Access mode: Read/Write
 */
#define AG_MG_REGS_MPU_RANGE_RO                    0x00000800
#define AG_MG_REGS_MPU_RANGE_RM                    0xFFFF003F

#define AG_MG_REGS_MPU_RANGE_EN_BO                 0
#define AG_MG_REGS_MPU_RANGE_EN_BM                 0x00000001

#define AG_MG_REGS_MPU_RANGE_SZ_BO                 1
#define AG_MG_REGS_MPU_RANGE_SZ_BM                 0x0000003E

#define AG_MG_REGS_MPU_RANGE_BASEH_BM 0xFFFF0000
#define AG_MG_REGS_MPU_RANGE_BASEH_BO 16

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_RANGE_U
{
    struct
    {
        ag_mg_regs_register
            en : 1,
            sz : 5,
            fill0 : 10,
            baseh : 16;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_range_u;
#endif


/*
 * MPU_PROCID (MPU ProcessID Register)
 * Initialization value: 0x00000000  Initialization mask: 0x000000FF
 * Access mode: Read Only
 */
#define AG_MG_REGS_MPU_PROCID_RO                   0x00000C00
#define AG_MG_REGS_MPU_PROCID_RM                   0x000000FF

#define AG_MG_REGS_MPU_PROCID_PROCID_BO            0
#define AG_MG_REGS_MPU_PROCID_PROCID_BM            0x000000FF

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef union AG_MG_REGS_MPU_PROCID_U
{
    struct
    {
        ag_mg_regs_register
            id : 8,
            fill0 : 24;
    } fields;
    ag_mg_regs_register reg;
} ag_mg_regs_mpu_procid_u;
#endif

/*
* Physical register addresses (for DSS accessing its own MPU)
*/
/*
 * Physical register addresses (for dss accessing mpu)
 */
#define AG_MG_REGS_MPU_BASE			0x80110000
#define AG_MG_REGS_MPU_REG(ro)		(AG_MG_REGS_MPU_BASE+(ro))

#define AG_MG_REGS_MPU_CTRL_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_CTRL_RO)
#define AG_MG_REGS_MPU_ATTRDF_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_ATTRDF_RO)
#define AG_MG_REGS_MPU_CBGE_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_CBGE_RO)
#define AG_MG_REGS_MPU_XP_ESTAT_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_XP_ESTAT_RO)
#define AG_MG_REGS_MPU_XP_EADDR_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_XP_EADDR_RO)
#define AG_MG_REGS_MPU_XD_ESTAT_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_XD_ESTAT_RO)
#define AG_MG_REGS_MPU_XD_EADDR_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_XD_EADDR_RO)
#define AG_MG_REGS_MPU_XA_ESTAT_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_XA_ESTAT_RO)
#define AG_MG_REGS_MPU_XA_EADDR_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_XA_EADDR_RO)
#define AG_MG_REGS_MPU_XB_ESTAT_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_XB_ESTAT_RO)
#define AG_MG_REGS_MPU_XB_EADDR_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_XB_EADDR_RO)
#define AG_MG_REGS_MPU_ATT_RANGE0_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_ATT_RANGE0_RO)
#define AG_MG_REGS_MPU_ATT_RANGE1_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_ATT_RANGE1_RO)
#define AG_MG_REGS_MPU_ATT_RANGE2_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_ATT_RANGE2_RO)
#define AG_MG_REGS_MPU_ATT_RANGE3_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_ATT_RANGE3_RO)
#define AG_MG_REGS_MPU_ATT_RANGE4_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_ATT_RANGE4_RO)
#define AG_MG_REGS_MPU_ATT_RANGE5_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_ATT_RANGE5_RO)
#define AG_MG_REGS_MPU_ATT_RANGE6_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_ATT_RANGE6_RO)
#define AG_MG_REGS_MPU_ATT_RANGE7_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_ATT_RANGE7_RO)
#define AG_MG_REGS_MPU_RANGE_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_RANGE_RO)
#define AG_MG_REGS_MPU_RANGE1_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_RANGE1_RO)
#define AG_MG_REGS_MPU_RANGE2_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_RANGE2_RO)
#define AG_MG_REGS_MPU_RANGE3_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_RANGE3_RO)
#define AG_MG_REGS_MPU_RANGE4_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_RANGE4_RO)
#define AG_MG_REGS_MPU_RANGE5_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_RANGE5_RO)
#define AG_MG_REGS_MPU_RANGE6_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_RANGE6_RO)
#define AG_MG_REGS_MPU_RANGE7_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_RANGE7_RO)
#define AG_MG_REGS_MPU_PROCID_RA	AG_MG_REGS_MPU_REG(AG_MG_REGS_MPU_PROCID_RO)

#ifdef AG_MG_REGS_USE_C_STRUCTURES
typedef struct AG_MG_REGS_MPU_ATT_REGS_S
{
	ag_mg_regs_mpu_att_u  att;
	ag_mg_regs_register   fill[7];
} ag_mg_regs_mpu_att_regs_s;

typedef struct AG_MG_REGS_MPU_RANGE_REGS_S
{
ag_mg_regs_mpu_range_u  range;
ag_mg_regs_register     fill[7];
} ag_mg_regs_mpu_range_regs_s;

typedef struct AG_MG_REGS_MPU_REGS_S
{
	ag_mg_regs_mpu_ctrl_u		ctrl ;
	ag_mg_regs_register		RESERVED_0[7] ;
	ag_mg_regs_mpu_attrdf_u		attrdf ;
	ag_mg_regs_register		RESERVED_1[47] ;
	ag_mg_regs_mpu_cbge_u		cbge ;
	ag_mg_regs_register		RESERVED_2[7] ;
	ag_mg_regs_mpu_xp_estat_u	xp_estat ;
	ag_mg_regs_register		RESERVED_3[7] ;
	ag_mg_regs_mpu_xp_eaddr_u	xp_eaddr ;
	ag_mg_regs_register		RESERVED_4[7] ;
	ag_mg_regs_mpu_xd_estat_u	xd_estat ;
	ag_mg_regs_register		RESERVED_5[7] ;
	ag_mg_regs_mpu_xd_eaddr_u	xd_eaddr ;
	ag_mg_regs_register		RESERVED_6[7] ;
	ag_mg_regs_mpu_xa_estat_u	xa_estat ;
	ag_mg_regs_register		RESERVED_7[7] ;
	ag_mg_regs_mpu_xa_eaddr_u	xa_eaddr ;
	ag_mg_regs_register		RESERVED_8[7] ;
	ag_mg_regs_mpu_xb_estat_u	xb_estat ;
	ag_mg_regs_register		RESERVED_9[7] ;
	ag_mg_regs_mpu_xb_eaddr_u	xb_eaddr ;
	ag_mg_regs_register		RESERVED_10[135] ;
	ag_mg_regs_mpu_att_regs_s	att_regs[8];
	ag_mg_regs_register		RESERVED_11[192] ;
	ag_mg_regs_mpu_range_regs_s	range_regs[8] ;
	ag_mg_regs_register		RESERVED_26[192] ;
	ag_mg_regs_mpu_procid_u		mpu_procid ;
} ag_mg_regs_mpu_reg_s ;

/*
* Recommended C syntax for typical usage :
*   volatile ag_mg_regs_mpu_reg_s *mpu_regs =
*       (volatile ag_mg_regs_mpu_reg_s *)AG_MG_REGS_MPU_BASE;
*/
#endif

#endif

/******** History ********
$Log: ag_mg_regs_mpu.h,v $
Revision 1.2  2017/07/28 07:58:34  harrchan
Collapse Oakenshield-branch to Main Trunk.

Revision 1.1.2.1  2017/06/29 08:14:27  harrchan
Initial commit code for Oakenshield

Revision 1.1  2012/04/18 18:08:26  srane
Initial checkin


$Endlog$
*/

